(()=>{
const BS39=save,BR39=renderAll,O39=JSON.parse(localStorage.getItem('nothing-state-v39')||'null')||{},cl=(v,a,b)=>Math.max(a,Math.min(b,v)),pick=a=>a&&a.length?a[Math.floor(Math.random()*a.length)]:null;
const SCOPE={
  'converge-runtime':'runtime.write',
  'rollback-release':'deployment.rollback',
  'rewrite-history':'history.write',
  'freeze-change':'change.freeze',
  'seal-record':'record.seal',
  'choose-citizenship':'citizenship.adjudicate'
};
S.serviceIdentities=O39.serviceIdentities||[];
S.accessCredentials=O39.accessCredentials||[];
S.accessAudits=O39.accessAudits||[];
S.serviceIdentitySerial=O39.serviceIdentitySerial||0;
S.credentialSerial=O39.credentialSerial||0;
S.accessAuditSerial=O39.accessAuditSerial||0;
S.breakGlassEvents=O39.breakGlassEvents||0;
S.privilegeEscalations=O39.privilegeEscalations||0;
S.credentialRevocations=O39.credentialRevocations||0;
S.credentialRotations=O39.credentialRotations||0;
S.credentialLeaks=O39.credentialLeaks||0;
S.unauthorizedRemediations=O39.unauthorizedRemediations||0;
S.accessDeniedAutomations=O39.accessDeniedAutomations||0;
S.iamCrises=O39.iamCrises||0;
S.lastIamCrisis=O39.lastIamCrisis||0;
S.iamKeys=O39.iamKeys||{};
S.observedRemediations39=O39.observedRemediations39||{};
S.iamAutomationHold=O39.iamAutomationHold||{A:false,B:false};
S.iamAutomationPrevious=O39.iamAutomationPrevious||{A:null,B:null};S.iamAutomationPriorGlobal=O39.iamAutomationPriorGlobal??null;
S.serviceIdentities=S.serviceIdentities.map((x,i)=>({id:x.id||'SA'+(i+1),reality:x.reality||'A',runbookId:x.runbookId||null,runbookKind:x.runbookKind||'freeze-change',name:x.name||'unnamed automation identity',status:x.status||'active',trust:Number.isFinite(x.trust)?x.trust:.55,breakGlassUses:x.breakGlassUses||0,authorizedRuns:x.authorizedRuns||0,unauthorizedRuns:x.unauthorizedRuns||0,created:x.created||Date.now(),x:Number.isFinite(x.x)?x.x:10+Math.random()*80,y:Number.isFinite(x.y)?x.y:12+Math.random()*68}));
S.accessCredentials=S.accessCredentials.map((g,i)=>({id:g.id||'K'+(i+1),identityId:g.identityId||null,reality:g.reality||'A',scopes:g.scopes||[],status:g.status||'active',temporary:!!g.temporary,breakGlass:!!g.breakGlass,issuedBy:g.issuedBy||'unknown authority',issuedAt:g.issuedAt||Date.now(),expiresAt:g.expiresAt??null,revokedAt:g.revokedAt||null,uses:g.uses||0,leakedTo:g.leakedTo||null,precedent:!!g.precedent,x:Number.isFinite(g.x)?g.x:10+Math.random()*80,y:Number.isFinite(g.y)?g.y:12+Math.random()*68}));
S.accessAudits=S.accessAudits.map((a,i)=>({id:a.id||'AU'+(i+1),reality:a.reality||'A',remediationId:a.remediationId||null,identityId:a.identityId||null,credentialId:a.credentialId||null,scope:a.scope||'unknown',status:a.status||'authorized',created:a.created||Date.now(),note:a.note||'',x:Number.isFinite(a.x)?a.x:10+Math.random()*80,y:Number.isFinite(a.y)?a.y:12+Math.random()*68}));
function save39(){BS39();localStorage.setItem('nothing-state-v39',JSON.stringify({serviceIdentities:S.serviceIdentities,accessCredentials:S.accessCredentials,accessAudits:S.accessAudits,serviceIdentitySerial:S.serviceIdentitySerial,credentialSerial:S.credentialSerial,accessAuditSerial:S.accessAuditSerial,breakGlassEvents:S.breakGlassEvents,privilegeEscalations:S.privilegeEscalations,credentialRevocations:S.credentialRevocations,credentialRotations:S.credentialRotations,credentialLeaks:S.credentialLeaks,unauthorizedRemediations:S.unauthorizedRemediations,accessDeniedAutomations:S.accessDeniedAutomations,iamCrises:S.iamCrises,lastIamCrisis:S.lastIamCrisis,iamKeys:S.iamKeys,observedRemediations39:S.observedRemediations39,iamAutomationHold:S.iamAutomationHold,iamAutomationPrevious:S.iamAutomationPrevious,iamAutomationPriorGlobal:S.iamAutomationPriorGlobal}))}save=save39;
const realm=id=>S.real[id],runbook=id=>(S.runbooks||[]).find(r=>r.id===id),incident=id=>(S.incidents||[]).find(n=>n.id===id),alert=id=>(S.telemetryAlerts||[]).find(a=>a.id===id),scopeFor=r=>SCOPE[r?.kind]||'operations.execute';
function metricKindForIncident(n){let a=(n?.alertIds||[]).map(alert).find(Boolean);if(a)return a.metricKind;let t=String(n?.title||'').toLowerCase();for(const k of['runtime-consistency','production-health','timeline-confidence','institutional-agreement','record-integrity','citizenship-legibility'])if(t.includes(k.replaceAll('-',' ')))return k;return'production-health'}
function bestRunbook39(n){let k=metricKindForIncident(n),rs=(S.runbooks||[]).filter(r=>r.reality===n.reality&&r.status==='active'&&r.metricKind===k);return [...rs].sort((a,b)=>(b.confidence||0)-(a.confidence||0))[0]||(S.runbooks||[]).find(r=>r.reality===n.reality&&r.status==='active')}
function identityForRunbook(r){if(!r)return null;let x=S.serviceIdentities.find(x=>x.runbookId===r.id&&x.status==='active');if(x)return x;x={id:'SA'+(++S.serviceIdentitySerial),reality:r.reality,runbookId:r.id,runbookKind:r.kind,name:'service/'+r.kind+'/'+r.reality,status:'active',trust:.52,breakGlassUses:0,authorizedRuns:0,unauthorizedRuns:0,created:Date.now(),x:10+Math.random()*80,y:12+Math.random()*68};S.serviceIdentities.push(x);S.serviceIdentities=S.serviceIdentities.slice(-36);remember('MACHINE IDENTITY '+x.id+': '+x.name+' created without permissions',realm(r.reality));return x}
function ensureIdentities(){for(const r of(S.runbooks||[]))identityForRunbook(r)}
function expireCredentials(){let now=Date.now();for(const g of S.accessCredentials){if(g.status==='active'&&g.expiresAt&&now>=g.expiresAt){g.status='expired';remember('CREDENTIAL EXPIRED '+g.id+': '+g.scopes.join(', '),realm(g.reality))}}}
function credentialsFor(x,scope){let now=Date.now();return S.accessCredentials.filter(g=>g.status==='active'&&(!g.expiresAt||g.expiresAt>now)&&g.scopes.includes(scope)&&(g.identityId===x.id||g.leakedTo===x.id))}
function validCredential(x,scope){let gs=credentialsFor(x,scope);return [...gs].sort((a,b)=>(b.breakGlass?1:0)-(a.breakGlass?1:0))[0]||null}
function issueCredential(x,scopes=[SCOPE[x.runbookKind]||'operations.execute'],opts={}){if(!x)return null;let temp=opts.temporary??false,bg=opts.breakGlass??false,duration=opts.duration??(bg?45000:120000),g={id:'K'+(++S.credentialSerial),identityId:x.id,reality:x.reality,scopes:[...new Set(scopes)],status:'active',temporary:temp||bg,breakGlass:bg,issuedBy:opts.issuedBy||'access office',issuedAt:Date.now(),expiresAt:(temp||bg)?Date.now()+duration:null,revokedAt:null,uses:0,leakedTo:null,precedent:!!opts.precedent,x:10+Math.random()*80,y:12+Math.random()*68};S.accessCredentials.push(g);S.accessCredentials=S.accessCredentials.slice(-48);if(bg){x.breakGlassUses++;S.breakGlassEvents++;remember('BREAK GLASS '+g.id+': '+x.name+' received temporary '+g.scopes.join(', '),realm(x.reality));if(typeof place==='function')place('cold','emergency credential under broken glass',realm(x.reality))}else remember('ACCESS GRANT '+g.id+': '+x.name+' may '+g.scopes.join(', '),realm(x.reality));releaseAutomationHold(x.reality);renderAll();save39();return g}
function revokeCredential(g){if(!g||g.status!=='active')return;g.status='revoked';g.revokedAt=Date.now();S.credentialRevocations++;remember('ACCESS REVOKED '+g.id+': permission ended after its previous effects remained',realm(g.reality));if(typeof place==='function')place('dream','revoked key beside an unchanged world',realm(g.reality));renderAll();save39();openCredential(g)}
function rotateCredential(g){if(!g||g.status!=='active')return;let x=S.serviceIdentities.find(x=>x.id===g.identityId),scopes=[...g.scopes];g.status='revoked';g.revokedAt=Date.now();S.credentialRevocations++;S.credentialRotations++;let n=issueCredential(x,scopes,{temporary:g.temporary,breakGlass:false,duration:g.temporary?120000:null,issuedBy:'credential rotation'});remember('CREDENTIAL ROTATION: '+g.id+' → '+n.id,realm(g.reality));$('#msg').textContent=g.id+' rotated to '+n.id+'. Anything holding the old credential may not know yet.';openCredential(n)}
function leakCredential(g){if(!g||g.status!=='active')return;let others=S.serviceIdentities.filter(x=>x.status==='active'&&x.id!==g.identityId),to=pick(others);if(!to)return;g.leakedTo=to.id;S.credentialLeaks++;remember('CREDENTIAL LEAK '+g.id+': '+to.name+' can now present a token issued to another identity',realm(g.reality));if(typeof place==='function')place('cold','credential copied into the wrong pocket',realm(g.reality));if(to.reality!==g.reality){realm('A').disputes++;realm('B').disputes++;remember('CROSS-REALITY CREDENTIAL: '+g.id+' is accepted outside its issuing reality',realm(to.reality))}$('#msg').textContent=g.id+' leaked to '+to.name+'. The token did not notice the identity changed.';iamCrisis(g.reality,'credential-leak');renderAll();save39();openCredential(g)}
function holdAutomation(id,reason){if(S.iamAutomationHold[id])return;if(!Object.values(S.iamAutomationHold).some(Boolean))S.iamAutomationPriorGlobal=S.opsAutomationEnabled;S.iamAutomationHold[id]=true;S.iamAutomationPrevious[id]=S.opsAutomationEnabled;S.opsAutomationEnabled=false;S.accessDeniedAutomations++;remember('ACCESS GATE: automatic remediation paused in Reality '+id+' · '+reason,realm(id));S.bailiffMood='checking the service account before obeying the runbook'}
function releaseAutomationHold(id){if(!S.iamAutomationHold[id])return;S.iamAutomationHold[id]=false;S.iamAutomationPrevious[id]=null;if(!Object.values(S.iamAutomationHold).some(Boolean)){let prior=S.iamAutomationPriorGlobal;S.iamAutomationPriorGlobal=null;if(prior===true)S.opsAutomationEnabled=true}remember('ACCESS GATE CLEARED: authorized automation may resume in Reality '+id,realm(id))}
function maybeBreakGlass(n,r,x){if(!n||!r||!x)return null;let key='bg-'+n.id+'-'+x.id;if(S.iamKeys[key])return null;let chance=n.severity==='SEV1'?.22:n.severity==='SEV2'?.08:.025;if(Math.random()<chance){S.iamKeys[key]=1;return issueCredential(x,[scopeFor(r)],{temporary:true,breakGlass:true,duration:42000,issuedBy:n.severity+' incident commander'})}return null}
function gateAutomation(){expireCredentials();ensureIdentities();for(const id of['A','B']){let n=[...(S.incidents||[])].reverse().find(n=>n.reality===id&&n.status==='open');if(!n){releaseAutomationHold(id);continue}let r=bestRunbook39(n),x=identityForRunbook(r),scope=scopeFor(r),g=x&&validCredential(x,scope);if(g){releaseAutomationHold(id);continue}if(maybeBreakGlass(n,r,x)){releaseAutomationHold(id);continue}holdAutomation(id,(x?.name||'automation')+' lacks '+scope)}}
function securityIncident(id,rm,x,scope){S.incidentSerial=S.incidentSerial||0;let title='unauthorized remediation executed: '+scope,existing=(S.incidents||[]).find(n=>n.reality===id&&n.status==='open'&&n.title===title);if(existing)return existing;let n={id:'INC'+(++S.incidentSerial),reality:id,title,severity:'SEV2',status:'open',alertIds:[],started:Date.now(),acknowledged:null,resolved:null,postmortem:null,owner:'access review',x:10+Math.random()*80,y:12+Math.random()*68};S.incidents=S.incidents||[];S.incidents.push(n);remember('SECURITY INCIDENT '+n.id+': '+(x?.name||'unknown automation')+' changed reality without '+scope,realm(id));if(typeof place==='function')place('cold','unauthorized change that still happened',realm(id));return n}
function auditRemediation(rm){if(!rm||S.observedRemediations39[rm.id])return;S.observedRemediations39[rm.id]=1;let r=runbook(rm.runbookId),x=identityForRunbook(r),scope=scopeFor(r),g=x&&validCredential(x,scope),status=g?'authorized':'unauthorized',note='';if(g){g.uses++;x.authorizedRuns++;x.trust=cl(x.trust+.012,.1,.99);note=(g.breakGlass?'break-glass ':'')+'credential '+g.id+' authorized '+scope;if(g.leakedTo===x.id)note='leaked credential '+g.id+' authorized a different identity'}else{x.unauthorizedRuns++;x.trust=cl(x.trust-.045,.05,.99);S.unauthorizedRemediations++;note='no active credential granted '+scope;securityIncident(rm.reality,rm,x,scope)}let a={id:'AU'+(++S.accessAuditSerial),reality:rm.reality,remediationId:rm.id,identityId:x?.id||null,credentialId:g?.id||null,scope,status,created:Date.now(),note,x:10+Math.random()*80,y:12+Math.random()*68};S.accessAudits.push(a);S.accessAudits=S.accessAudits.slice(-48);remember('ACCESS AUDIT '+a.id+': '+rm.id+' '+status.toUpperCase()+' for '+scope,realm(rm.reality));if(status==='unauthorized')iamCrisis(rm.reality,'unauthorized-remediation');}
function auditNewRemediations(){for(const rm of(S.remediationRuns||[]))auditRemediation(rm)}
function privilegeCreep(){for(const x of S.serviceIdentities.filter(x=>x.breakGlassUses>=3&&x.status==='active')){let key='precedent-'+x.id;if(S.iamKeys[key])continue;if(Math.random()<.035){S.iamKeys[key]=1;let scope=SCOPE[x.runbookKind]||'operations.execute';issueCredential(x,[scope],{temporary:false,breakGlass:false,precedent:true,issuedBy:'repeated emergency precedent'});S.privilegeEscalations++;remember('PRIVILEGE ESCALATION: repeated emergency use made '+scope+' permanent for '+x.name,realm(x.reality));if(typeof place==='function')place('cold','temporary access made permanent by precedent',realm(x.reality));iamCrisis(x.reality,'privilege-creep');break}}}
function spontaneousLeak(){let live=S.accessCredentials.filter(g=>g.status==='active'&&!g.leakedTo&&g.uses>0);if(live.length&&Math.random()<.004)leakCredential(pick(live))}
function iamCrisis(id,reason){if(Date.now()-S.lastIamCrisis<8000)return false;let key=id+'|'+reason+'|'+Math.floor(Date.now()/20000);if(S.iamKeys['crisis-'+key])return false;S.iamKeys['crisis-'+key]=1;S.iamCrises++;S.lastIamCrisis=Date.now();for(const rid of['A','B']){realm(rid).disputes=(realm(rid).disputes||0)+1;remember('ACCESS CONTROL CRISIS: the credential deciding who may change reality became a source of authority',realm(rid))}if(typeof place==='function'){place('cold','permission that outlived the emergency',realm(id));place('dream','service account with constitutional consequences',realm(id))}S.bailiffMood='asking the token what the government is allowed to do';$('#msg').textContent='ACCESS CONTROL CRISIS: permission to change reality is becoming its own form of sovereignty.';return true}
function openIdentity(x){let scope=SCOPE[x.runbookKind]||'operations.execute',gs=S.accessCredentials.filter(g=>g.identityId===x.id||g.leakedTo===x.id).slice(-5),b=[];if(!validCredential(x,scope))b.push(['grant '+scope,()=>{issueCredential(x,[scope],{issuedBy:'traveler access approval'});openIdentity(x)}],['break glass',()=>{issueCredential(x,[scope],{temporary:true,breakGlass:true,issuedBy:'traveler emergency approval'});openIdentity(x)}]);for(const g of gs.filter(g=>g.status==='active').slice(-2))b.push(['open '+g.id,()=>openCredential(g)]);b.push(['close',closePanel]);panel(x.id+' · '+x.status,x.name+'\n\nrequired scope: '+scope,'trust '+Math.round(x.trust*100)+'% · authorized '+x.authorizedRuns+' · unauthorized '+x.unauthorizedRuns+' · break-glass uses '+x.breakGlassUses+' · credentials '+gs.map(g=>g.id+':'+g.status).join(', '),b)}
function openCredential(g){let x=S.serviceIdentities.find(x=>x.id===g.identityId),b=[];if(g.status==='active')b.push(['revoke',()=>revokeCredential(g)],['rotate',()=>rotateCredential(g)]);if(g.status==='active'&&!g.leakedTo)b.push(['copy credential elsewhere',()=>leakCredential(g)]);if(x)b.push(['open '+x.id,()=>openIdentity(x)]);b.push(['close',closePanel]);let ttl=g.expiresAt?Math.max(0,Math.ceil((g.expiresAt-Date.now())/1000))+'s':'no expiry';panel(g.id+' · '+g.status+(g.breakGlass?' · BREAK GLASS':''),g.scopes.join(', ')+'\n\nissued to '+(x?.name||g.identityId),'issuer '+g.issuedBy+' · '+ttl+' · uses '+g.uses+(g.leakedTo?' · copied to '+g.leakedTo:'')+(g.precedent?' · permanent by precedent':''),b)}
function openAudit(a){let x=S.serviceIdentities.find(x=>x.id===a.identityId),g=S.accessCredentials.find(g=>g.id===a.credentialId),b=[];if(x)b.push(['open '+x.id,()=>openIdentity(x)]);if(g)b.push(['open '+g.id,()=>openCredential(g)]);b.push(['close',closePanel]);panel(a.id+' · '+a.status.toUpperCase(),(a.remediationId||'unknown remediation')+' requested '+a.scope,a.note,b)}
function openAccess(){ensureIdentities();expireCredentials();let id=S.active,xs=S.serviceIdentities.filter(x=>x.reality===id),live=S.accessCredentials.filter(g=>g.reality===id&&g.status==='active'),aud=[...S.accessAudits].reverse().filter(a=>a.reality===id).slice(0,4),b=[];for(const x of xs.slice(0,6))b.push(['open '+x.id,()=>openIdentity(x)]);for(const a of aud)b.push(['audit '+a.id,()=>openAudit(a)]);b.push(['audit automation now',()=>{auditNewRemediations();gateAutomation();openAccess()}],['close',closePanel]);panel('ACCESS CONTROL · Reality '+id,(S.iamAutomationHold[id]?'AUTOMATION HELD':'automation credential gate clear')+'\n\n'+xs.length+' machine identities · '+live.length+' active credentials','break glass '+S.breakGlassEvents+' · unauthorized '+S.unauthorizedRemediations+' · revoked '+S.credentialRevocations+' · leaks '+S.credentialLeaks+' · privilege escalations '+S.privilegeEscalations+' · IAM crises '+S.iamCrises,b)}
function renderAccess(){ensureIdentities();expireCredentials();let l=$('#accessLayer');if(!l){l=document.createElement('div');l.id='accessLayer';document.body.appendChild(l)}l.innerHTML='';for(const g of S.accessCredentials.slice(-18)){let n=document.createElement('i');n.className='accessCredential '+g.status+(g.breakGlass?' breakglass':'')+(g.leakedTo?' leaked':'');n.dataset.label=g.id;n.style.left=g.x+'%';n.style.top=g.y+'%';n.onclick=()=>openCredential(g);l.appendChild(n)}for(const a of S.accessAudits.filter(a=>a.status==='unauthorized').slice(-10)){let n=document.createElement('i');n.className='accessAudit unauthorized';n.dataset.label=a.id;n.style.left=a.x+'%';n.style.top=a.y+'%';n.onclick=()=>openAudit(a);l.appendChild(n)}let line=$('#accessline');if(!line){line=document.createElement('div');line.id='accessline';line.className='line';($('#opsline')||$('#observabilityline')||$('#deploymentline')||$('#ciline')||$('#versionline')||$('#enforcement')).after(line)}let id=S.active,live=S.accessCredentials.filter(g=>g.reality===id&&g.status==='active').length;line.textContent='access control: '+S.serviceIdentities.filter(x=>x.reality===id).length+' service identities · '+live+' active credentials · '+S.breakGlassEvents+' break-glass · '+S.unauthorizedRemediations+' unauthorized executions · '+S.privilegeEscalations+' permanent escalations · '+S.credentialLeaks+' leaks · '+S.iamCrises+' IAM crises'+(S.iamAutomationHold[id]?' · AUTOMATION HELD':'');let ctr=document.querySelector('#app .controls');if(ctr&&!$('#openAccessButton')){let b=document.createElement('button');b.id='openAccessButton';b.textContent='open access control';b.onclick=openAccess;ctr.prepend(b)}if(ctr&&!$('#grantOpsButton')){let b=document.createElement('button');b.id='grantOpsButton';b.textContent='authorize next runbook';b.onclick=()=>{let n=[...(S.incidents||[])].reverse().find(n=>n.reality===S.active&&n.status==='open'),r=n&&bestRunbook39(n),x=r&&identityForRunbook(r);if(!x){$('#msg').textContent='No open incident currently needs an operations credential.';return}issueCredential(x,[scopeFor(r)],{temporary:true,duration:90000,issuedBy:'traveler one-incident authorization'});$('#msg').textContent=x.name+' received temporary '+scopeFor(r)+'.';openIdentity(x)};ctr.prepend(b)}}
renderAll=function(){BR39();renderAccess()};let f=$('#forget');if(f)f.onclick=()=>{for(let i=2;i<=39;i++)localStorage.removeItem('nothing-state-v'+i);location.reload()};
setInterval(()=>{gateAutomation();auditNewRemediations();privilegeCreep();spontaneousLeak();renderAccess();save39()},1700);gateAutomation();auditNewRemediations();renderAll();save39();
})();
