(()=>{
const BS27=save,BR27=renderAll,O27=JSON.parse(localStorage.getItem('nothing-state-v27')||'null')||{},oldCross=cross,pick=a=>a&&a.length?a[Math.floor(Math.random()*a.length)]:null,cl=(v,a,b)=>Math.max(a,Math.min(b,v));
S.passports=O27.passports||[];S.borderAttempts=O27.borderAttempts||0;S.borderDenials=O27.borderDenials||0;S.borderAdmissions=O27.borderAdmissions||0;S.asylumClaims=O27.asylumClaims||0;S.asylumGrants=O27.asylumGrants||0;S.statelessEvents=O27.statelessEvents||0;S.borderIncidents=O27.borderIncidents||0;S.passportSerial=O27.passportSerial||0;S.lastBorderIncident=O27.lastBorderIncident||0;S.travelerStatus=O27.travelerStatus||'undocumented';S.lastDeniedDestination=O27.lastDeniedDestination||null;
S.passports=S.passports.map((p,i)=>({id:p.id||'P'+(i+1),subject:p.subject||'traveler',citizenship:p.citizenship||'A',issuerType:p.issuerType||'reality',issuerId:p.issuerId||p.citizenship,status:p.status||'valid',issued:p.issued||Date.now(),uses:p.uses||0,denials:p.denials||0,recognition:p.recognition||{A:null,B:null},x:Number.isFinite(p.x)?p.x:10+Math.random()*80,y:Number.isFinite(p.y)?p.y:12+Math.random()*68}));
function save27(){BS27();localStorage.setItem('nothing-state-v27',JSON.stringify({passports:S.passports,borderAttempts:S.borderAttempts,borderDenials:S.borderDenials,borderAdmissions:S.borderAdmissions,asylumClaims:S.asylumClaims,asylumGrants:S.asylumGrants,statelessEvents:S.statelessEvents,borderIncidents:S.borderIncidents,passportSerial:S.passportSerial,lastBorderIncident:S.lastBorderIncident,travelerStatus:S.travelerStatus,lastDeniedDestination:S.lastDeniedDestination}))}save=save27;
const passport=()=>[...S.passports].reverse().find(p=>p.subject==='traveler'&&p.status==='valid');
const custodian=id=>[...(S.custodians||[])].reverse().find(c=>c.reality===id&&['acting','entrenched'].includes(c.status));
const exile=id=>[...(S.exileGovernments||[])].reverse().find(g=>g.home===id&&['exiled','recognized','blocked'].includes(g.status));
const charter=id=>[...(S.constitutions||[])].reverse().find(c=>c.reality===id&&c.status==='ratified');
const mandate=id=>[...(S.mandates||[])].reverse().find(m=>m.status==='active'&&(m.scope==='both'||m.scope===id));
function authority(id){let c=custodian(id),g=exile(id),k=charter(id),m=mandate(id);if(c)return{type:'continuity',id:c.id,authority:c.authority||.6,label:'continuity government '+c.id};if(k)return{type:'constitution',id:k.id,authority:k.authority||.6,label:'constitutional government '+k.id};if(m)return{type:'mandate',id:m.id,authority:m.authority||.6,label:'public mandate '+m.id};if(g)return{type:'exile',id:g.id,authority:g.legitimacy||.55,label:'government in exile '+g.id};return{type:'memory',id:id,authority:.45,label:'lived memory of Reality '+id}}
function rivalAuthority(id){let g=exile(id),c=custodian(id);if(g&&c)return{type:'exile',id:g.id,authority:g.legitimacy||.55,label:'government in exile '+g.id};return null}
function issuePassport(citizenship=S.active,issuer=null){issuer=issuer||authority(citizenship);let p={id:'P'+(++S.passportSerial),subject:'traveler',citizenship,issuerType:issuer.type,issuerId:issuer.id,status:'valid',issued:Date.now(),uses:0,denials:0,recognition:{A:null,B:null},x:10+Math.random()*80,y:12+Math.random()*68};S.passports.push(p);S.passports=S.passports.slice(-18);S.travelerStatus='documented citizen of Reality '+citizenship;remember('PASSPORT '+p.id+' issued to the traveler by '+issuer.label,S.real[citizenship]);$('#msg').textContent=issuer.label+' issued you '+p.id+'. The simulation now has paperwork for you.';renderAll();save27();return p}
function recognition(p,dest,auth){let score=.34+(auth.authority||.5)*.42;if(p.citizenship===dest)score+=.12;if(p.issuerId===auth.id)score+=.3;if(p.issuerType==='constitution'&&auth.type==='continuity')score-=.12;if(p.issuerType==='continuity'&&auth.type==='constitution')score-=.1;if(p.issuerType==='exile'&&auth.type==='continuity')score-=.26;if(p.issuerType==='continuity'&&auth.type==='exile')score-=.24;if(p.status!=='valid')score-=.45;return cl(score,.05,.95)}
function inspect(p,dest){let a=authority(dest),r=rivalAuthority(dest),main=Math.random()<recognition(p,dest,a),rival=r?Math.random()<recognition(p,dest,r):null;p.recognition[dest]=main;return{a,r,main,rival}}
function incident(dest,p,x){if(!x.r||x.rival===null||x.main===x.rival||Date.now()-S.lastBorderIncident<9000)return;S.borderIncidents++;S.lastBorderIncident=Date.now();for(const r of[S.real.A,S.real.B]){r.timelineDrift++;r.disputes++;remember('BORDER INCIDENT: two governments disagree whether '+p.id+' exists as valid identity',r)}if(typeof place==='function'){place('cold','checkpoint claimed by two governments',S.real[dest]);place('dream','passport valid on only one desk',S.real[dest==='A'?'B':'A'])}S.bailiffMood='checking passports issued by both governments';$('#msg').textContent='BORDER INCIDENT: '+x.a.label+' and '+x.r.label+' disagree about your papers.'}
function performCross(){S.lastDeniedDestination=null;oldCross();S.borderAdmissions++;let p=passport();if(p)p.uses++;S.travelerStatus='admitted to Reality '+S.active;save27()}
function deny(dest,p,x){S.borderDenials++;S.lastDeniedDestination=dest;p.denials++;S.travelerStatus='refused entry to Reality '+dest;remember('ENTRY REFUSED: traveler carrying '+p.id+' was stopped at the rift',S.real[dest]);if(typeof place==='function')place('cold','border waiting room',S.real[dest]);$('#msg').textContent='ENTRY REFUSED by '+x.a.label+'. Your passport is recognized on the wrong side of the checkpoint.';openPassport(p,dest,x);save27()}
function borderCross(){let dest=other();S.borderAttempts++;let p=passport();if(!p){S.travelerStatus='undocumented at the rift';$('#msg').textContent='PASSPORT CONTROL: Reality '+dest+' wants documents you do not have.';openUndocumented(dest);save27();return}let x=inspect(p,dest);incident(dest,p,x);if(x.main||x.rival===true){performCross();if(x.main!==x.rival&&x.r)remember('ADMITTED UNDER PROTEST: '+p.id,S.real[dest]);return}deny(dest,p,x)}
function asylum(dest=S.lastDeniedDestination){if(!dest)return;S.asylumClaims++;let p=passport(),a=authority(dest),pressure=(S.dualPowerCrises||0)+(S.emergencyCrises||0)+(S.circuitSplits||0);let chance=cl(.3+pressure*.035+(p&&p.citizenship!==dest?.08:0)-(a.authority||.5)*.08,.12,.72);if(Math.random()<chance){S.asylumGrants++;S.travelerStatus='temporary asylum in Reality '+dest;remember('ASYLUM GRANTED: traveler admitted without settled nationality',S.real[dest]);if(typeof place==='function')place('warm','temporary protection desk',S.real[dest]);if(S.active!==dest)oldCross();$('#msg').textContent='Reality '+dest+' granted temporary asylum. Your passport question remains unresolved.'}else{$('#msg').textContent='Asylum was denied. The border wrote down that you are still here.';remember('ASYLUM DENIED: traveler remained at the checkpoint',S.real[S.active])}closePanel();renderAll();save27()}
function becomeStateless(p){if(!p||p.status!=='valid')return;p.status='void';S.statelessEvents++;S.travelerStatus='stateless';for(const r of[S.real.A,S.real.B]){r.timelineDrift++;r.disputes++;remember('STATELESS PERSON: neither reality accepts responsibility for '+p.id,r)}if(typeof place==='function'){place('dream','country of no return address',S.real.A);place('dream','country of no return address',S.real.B)}$('#msg').textContent=p.id+' was voided. You now belong legally to neither reality.';closePanel();renderAll();save27()}
function appealPassport(p,dest){let x=inspect(p,dest),r=x.r;if(r&&Math.random()<cl((r.authority||.5)+.08,.15,.85)){p.recognition[dest]=true;S.travelerStatus='recognized by rival government of Reality '+dest;remember('RIVAL RECOGNITION: '+r.label+' recognizes '+p.id,S.real[dest]);$('#msg').textContent=r.label+' recognized your passport. The government controlling the checkpoint still may not.'}else{p.denials++;$('#msg').textContent='The passport appeal produced another stamp but no agreement.';if(p.denials>=3&&Math.random()<.4)becomeStateless(p)}openPassport(p,dest);save27()}
function openUndocumented(dest){let b=[['apply for passport',()=>{let p=issuePassport(S.active);closePanel();openPassport(p,dest)}],['request asylum',()=>asylum(dest)],['cross without documents',()=>{let a=authority(dest);if(Math.random()<.22-(a.authority||.5)*.08){remember('UNRECORDED CROSSING: traveler entered without documents',S.real[dest]);closePanel();performCross()}else{$('#msg').textContent='The checkpoint noticed you trying to become an undocumented event.';S.borderDenials++;closePanel();renderAll()}}],['close',closePanel]];panel('passport control · Reality '+dest,'The rift is now a border. The border has noticed that you exist.','traveler status: '+S.travelerStatus+' · no valid passport',b)}
function openPassport(p,dest=null,x=null){let b=[];if(dest)b.push(['request asylum',()=>asylum(dest)],['appeal to rival authority',()=>appealPassport(p,dest)]);b.push(['void my passport',()=>becomeStateless(p)],['close',closePanel]);let rec='A '+(p.recognition.A===null?'unchecked':p.recognition.A?'recognized':'rejected')+' · B '+(p.recognition.B===null?'unchecked':p.recognition.B?'recognized':'rejected');panel(p.id+' · '+p.status+' passport','TRAVEL DOCUMENT\nSubject: you\nCitizenship: Reality '+p.citizenship+'\nIssuer: '+p.issuerType+' '+p.issuerId,'uses '+p.uses+' · denials '+p.denials+' · '+rec+' · status '+S.travelerStatus,b)}
function renderBorder(){let l=$('#borderLayer');if(!l){l=document.createElement('div');l.id='borderLayer';document.body.appendChild(l)}l.innerHTML='';for(const p of S.passports.slice(-10)){let n=document.createElement('i');n.className='passport '+p.status;n.dataset.label=p.id+' '+p.citizenship;n.style.left=p.x+'%';n.style.top=p.y+'%';n.onclick=()=>openPassport(p);l.appendChild(n)}let cp=$('#checkpoint');if(!cp){cp=document.createElement('div');cp.id='checkpoint';cp.onclick=()=>{let p=passport();p?openPassport(p,other()):openUndocumented(other())};document.body.appendChild(cp)}cp.dataset.label='PASSPORT CONTROL · entry to Reality '+other();let line=$('#borderline');if(!line){line=document.createElement('div');line.id='borderline';line.className='line';($('#exileline')||$('#continuityline')||$('#judiciaryline')||$('#enforcement')).after(line)}line.textContent='border: '+S.borderAttempts+' inspections · '+S.borderAdmissions+' admitted · '+S.borderDenials+' refused · '+S.asylumGrants+'/'+S.asylumClaims+' asylum · '+S.statelessEvents+' stateless events · '+S.borderIncidents+' incidents · '+S.travelerStatus;let ctr=document.querySelector('#app .controls');if(ctr&&!$('#passportButton')){let b=document.createElement('button');b.id='passportButton';b.textContent='open passport';b.onclick=()=>{let p=passport();p?openPassport(p):openUndocumented(other())};ctr.prepend(b)}if(ctr&&!$('#passportApplyButton')){let b=document.createElement('button');b.id='passportApplyButton';b.textContent='apply for passport';b.onclick=()=>{let p=issuePassport(S.active);openPassport(p)};ctr.prepend(b)}}
cross=function(){borderCross()};$('#rift').onclick=()=>borderCross();
renderAll=function(){BR27();renderBorder()};let f=$('#forget');if(f)f.onclick=()=>{for(let i=2;i<=27;i++)localStorage.removeItem('nothing-state-v'+i);location.reload()};
setInterval(()=>{let p=passport();if(p&&p.status==='valid'&&p.denials>=3&&p.recognition.A===false&&p.recognition.B===false&&Math.random()<.08)becomeStateless(p);renderBorder();save27()},1600);renderAll();save27();
})();
