(()=>{
const BS52=save,BR52=renderAll,O52=JSON.parse(localStorage.getItem('nothing-state-v52')||'null')||{},cl=(v,a,b)=>Math.max(a,Math.min(b,v)),pick=a=>a&&a.length?a[Math.floor(Math.random()*a.length)]:null;
const GRADES52=['AAA','AA','A','BBB','BB','B','CCC','D'];
S.ratingAgencies52=O52.ratingAgencies52||[];
S.creditRatings52=O52.creditRatings52||[];
S.softwareBonds52=O52.softwareBonds52||[];
S.capitalCalls52=O52.capitalCalls52||[];
S.capitalAudits52=O52.capitalAudits52||[];
S.ratingAgencySerial52=O52.ratingAgencySerial52||0;
S.creditRatingSerial52=O52.creditRatingSerial52||0;
S.softwareBondSerial52=O52.softwareBondSerial52||0;
S.capitalCallSerial52=O52.capitalCallSerial52||0;
S.capitalAuditSerial52=O52.capitalAuditSerial52||0;
S.ratingsPublished52=O52.ratingsPublished52||0;
S.issuerPaidRatings52=O52.issuerPaidRatings52||0;
S.ratingShops52=O52.ratingShops52||0;
S.ratingDowngrades52=O52.ratingDowngrades52||0;
S.ratingUpgrades52=O52.ratingUpgrades52||0;
S.ratingSplits52=O52.ratingSplits52||0;
S.agencyCaptures52=O52.agencyCaptures52||0;
S.bondsIssued52=O52.bondsIssued52||0;
S.bondDefaults52=O52.bondDefaults52||0;
S.collateralCalls52=O52.collateralCalls52||0;
S.collateralPaid52=O52.collateralPaid52||0;
S.ratingRestrictedInsurers52=O52.ratingRestrictedInsurers52||0;
S.selfFulfillingDowngrades52=O52.selfFulfillingDowngrades52||0;
S.capitalCrises52=O52.capitalCrises52||0;
S.lastCapitalCrisis52=O52.lastCapitalCrisis52||0;
S.capitalKeys52=O52.capitalKeys52||{};
S.lastCapitalTick52=O52.lastCapitalTick52||Date.now();
function save52(){BS52();localStorage.setItem('nothing-state-v52',JSON.stringify({ratingAgencies52:S.ratingAgencies52,creditRatings52:S.creditRatings52,softwareBonds52:S.softwareBonds52,capitalCalls52:S.capitalCalls52,capitalAudits52:S.capitalAudits52,ratingAgencySerial52:S.ratingAgencySerial52,creditRatingSerial52:S.creditRatingSerial52,softwareBondSerial52:S.softwareBondSerial52,capitalCallSerial52:S.capitalCallSerial52,capitalAuditSerial52:S.capitalAuditSerial52,ratingsPublished52:S.ratingsPublished52,issuerPaidRatings52:S.issuerPaidRatings52,ratingShops52:S.ratingShops52,ratingDowngrades52:S.ratingDowngrades52,ratingUpgrades52:S.ratingUpgrades52,ratingSplits52:S.ratingSplits52,agencyCaptures52:S.agencyCaptures52,bondsIssued52:S.bondsIssued52,bondDefaults52:S.bondDefaults52,collateralCalls52:S.collateralCalls52,collateralPaid52:S.collateralPaid52,ratingRestrictedInsurers52:S.ratingRestrictedInsurers52,selfFulfillingDowngrades52:S.selfFulfillingDowngrades52,capitalCrises52:S.capitalCrises52,lastCapitalCrisis52:S.lastCapitalCrisis52,capitalKeys52:S.capitalKeys52,lastCapitalTick52:S.lastCapitalTick52}))}save=save52;
const realm=id=>S.real[id],ns=id=>(S.namespaces46||[]).find(n=>n.id===id),treasury=id=>(S.packageTreasuries47||[]).find(t=>t.namespaceId===id),insurer=id=>(S.insurers51||[]).find(i=>i.id===id),agency=id=>S.ratingAgencies52.find(a=>a.id===id),bond=id=>S.softwareBonds52.find(b=>b.id===id),call=id=>S.capitalCalls52.find(c=>c.id===id);
function hash52(s){let h=2166136261>>>0;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)>>>0}return h.toString(16).padStart(8,'0')}
function ensureAgencies(){for(const id of ['A','B']){let defs=[[id+' Archive Ratings Bureau','archive-loss',.82,.78],[id+' Continuity Credit Service','continuity-first',.74,.72]];for(const [name,model,independence,credibility] of defs)if(!S.ratingAgencies52.some(a=>a.reality===id&&a.name===name))S.ratingAgencies52.push({id:'CRA'+(++S.ratingAgencySerial52),reality:id,name,model,status:'active',independence,credibility,revenue:0,ratings:0,issuerPaid:0,capturedBy:null,modelVersion:1,created:Date.now(),x:10+Math.random()*80,y:12+Math.random()*68})}}
function subject(type,id){if(type==='treasury'){let t=treasury(id),n=ns(id);return t&&n?{type,id,name:n.name+' package treasury',reality:n.reality,obj:t}:null}let i=insurer(id);return i?{type:'insurer',id,name:i.name,reality:i.reality,obj:i}:null}
function subjectCash(s){return s.type==='treasury'?(s.obj.balance||0):(s.obj.capital||0)}
function subjectDebt(s){return s.type==='treasury'?((s.obj.capitalDebt52||0)+(s.obj.debt||0)):(s.obj.debt52||0)}
function liveUsers52(n){let ids=new Set();for(const sb of (S.sboms45||[]).filter(x=>x.reality===n.reality&&x.status==='current'))if((sb.components||[]).some(pid=>(S.packages45||[]).find(p=>p.id===pid)?.name===n.name))ids.add(sb.artifactId);return ids.size}
function baseScore(s){if(s.type==='treasury'){let t=s.obj,n=ns(s.id),users=n?liveUsers52(n):0,debt=(t.debt||0)+(t.capitalDebt52||0),cash=t.balance||0,score=73+Math.min(12,users*2)+Math.min(8,cash*.35)-Math.min(30,debt*1.5);if(t.status==='strike')score-=12;if(t.status==='bankrupt')score-=36;if(t.capturedBy)score-=4;if((t.bailouts||0)>=2)score-=5;if(n?.status==='split'||n?.status==='abandoned')score-=8;return cl(score,8,98)}let i=s.obj,active=(S.riskPolicies51||[]).filter(p=>p.insurerId===i.id&&p.status==='active').length,claims=(i.claimsPaid||0)+(i.claimsDenied||0),leverage=(i.debt52||0)/Math.max(1,i.capital||0),score=76+Math.min(12,(i.capital||0)*.22)+Math.min(5,(i.reserves||0)*.15)-Math.min(24,leverage*24)-Math.min(12,claims*.6);if(i.status==='insolvent')score=12;if(i.status==='guaranteed')score+=9;if(i.status==='rating-restricted')score-=7;if(i.type==='captive')score-=7;if(active>=4&&i.capital<20)score-=8;return cl(score,8,98)}
function modelScore(s,a,paid=false){let score=baseScore(s);if(a.model==='archive-loss'){if(s.type==='insurer')score-=(s.obj.claimsPaid||0)*.35;else score-=Math.min(8,(s.obj.debt||0)*.25)}else{if(s.type==='treasury'){let n=ns(s.id);score+=Math.min(6,n?liveUsers52(n):0)}else score+=Math.min(5,(s.obj.policies||0)*.5)}if(paid)score+=4+Math.random()*4;if(a.capturedBy===s.name)score+=9;if(a.independence<.45)score+=(.45-a.independence)*18;score+=(Math.random()-.5)*4;return cl(score,5,99)}
function gradeFor(score){if(score>=90)return'AAA';if(score>=82)return'AA';if(score>=74)return'A';if(score>=66)return'BBB';if(score>=56)return'BB';if(score>=46)return'B';if(score>=34)return'CCC';return'D'}
const notch=g=>Math.max(0,GRADES52.indexOf(g)),investmentGrade=g=>notch(g)<=3;
function latestRating(type,id,agencyId=null){let xs=S.creditRatings52.filter(r=>r.subjectType===type&&r.subjectId===id&&(!agencyId||r.agencyId===agencyId));return xs.sort((a,b)=>b.published-a.published)[0]||null}
function agencyRatings(type,id){let out=[];for(const a of S.ratingAgencies52){let r=latestRating(type,id,a.id);if(r)out.push(r)}return out}
function marketRating(type,id){let xs=agencyRatings(type,id);if(!xs.length)return null;let designated=xs.filter(r=>r.designated);if(designated.length)return designated.sort((a,b)=>a.score-b.score)[0];return xs.sort((a,b)=>a.score-b.score)[0]}
function openIncident52(id,title,severity='SEV2'){S.incidents=S.incidents||[];let ex=S.incidents.find(i=>i.reality===id&&i.title===title&&i.status==='open');if(ex)return ex;S.incidentSerial=S.incidentSerial||0;let x={id:'INC'+(++S.incidentSerial),reality:id,title,severity,status:'open',alertIds:[],started:Date.now(),acknowledged:null,resolved:null,postmortem:null,owner:'software capital market',x:10+Math.random()*80,y:12+Math.random()*68};S.incidents.push(x);return x}
function trustRecord52(id,status,note){let accepted=S.trustPolicies?.[id]?.acceptedRoots||[],r=[...(S.trustRoots||[])].filter(x=>accepted.includes(x.id)&&x.status==='active').sort((a,b)=>(b.strength||0)-(a.strength||0))[0];S.trustAudits=S.trustAudits||[];S.trustAuditSerial=S.trustAuditSerial||0;S.trustAudits.push({id:'TA'+(++S.trustAuditSerial),reality:id,remediationId:null,credentialId:null,certificateId:null,rootId:r?.id||null,status,created:Date.now(),note,x:10+Math.random()*80,y:12+Math.random()*68})}
function takeFee(s,a,fee){if(s.type==='treasury'){let x=Math.min(s.obj.balance||0,fee);s.obj.balance=Math.max(0,(s.obj.balance||0)-x);a.revenue+=x}else{let x=Math.min(s.obj.capital||0,fee);s.obj.capital=Math.max(0,(s.obj.capital||0)-x);a.revenue+=x}}
function requestRating(type,id,agencyId,paid=false,designate=false,manual=true){ensureAgencies();let s=subject(type,id),a=agency(agencyId);if(!s||!a||a.status!=='active')return null;let prior=latestRating(type,id,a.id);if(paid){let fee=1.1+Math.random()*.9;takeFee(s,a,fee);a.issuerPaid++;S.issuerPaidRatings52++;a.independence=cl(a.independence-.035,0,1);a.credibility=cl(a.credibility-.012,0,1);if(a.independence<.36&&!a.capturedBy){a.capturedBy=s.name;S.agencyCaptures52++;remember('RATINGS CAPTURE: '+a.name+' became dependent on fees from '+s.name,realm(s.reality));if(typeof place==='function')place('cold','issuer paying the agency that defines its creditworthiness',realm(s.reality));capitalCrisis(s.reality,'ratings-capture')}}let score=modelScore(s,a,paid),grade=gradeFor(score),r={id:'RT'+(++S.creditRatingSerial52),reality:s.reality,agencyId:a.id,agency:a.name,subjectType:type,subjectId:id,subject:s.name,score,grade,outlook:score%10<3?'negative':score%10>7?'positive':'stable',paid,designated:!!designate,modelVersion:a.modelVersion,published:Date.now(),supersedes:prior?.id||null,x:10+Math.random()*80,y:12+Math.random()*68};if(designate)for(const x of S.creditRatings52.filter(x=>x.subjectType===type&&x.subjectId===id))x.designated=false;S.creditRatings52.push(r);S.creditRatings52=S.creditRatings52.slice(-160);a.ratings++;S.ratingsPublished52++;trustRecord52(s.reality,'software-credit-rating',r.id+' '+r.subject+' '+r.grade+' by '+a.name+(paid?' issuer-paid':''));if(prior){let d=notch(grade)-notch(prior.grade);if(d>0){S.ratingDowngrades52++;remember('RATING DOWNGRADE '+r.id+': '+s.name+' '+prior.grade+' → '+grade,realm(s.reality));applyRatingImpact(s,prior.grade,grade,r)}else if(d<0){S.ratingUpgrades52++;remember('RATING UPGRADE '+r.id+': '+s.name+' '+prior.grade+' → '+grade,realm(s.reality));applyRatingImpact(s,prior.grade,grade,r)}}else applyRatingImpact(s,null,grade,r);checkSplitRating(s);if(manual){$('#msg').textContent=r.subject+' rated '+r.grade+' by '+a.name+(paid?' after issuer-paid review.':'.');renderAll();save52();openRating(r)}return r}
function checkSplitRating(s){let xs=agencyRatings(s.type,s.id);if(xs.length<2)return;let grades=xs.map(r=>notch(r.grade)),spread=Math.max(...grades)-Math.min(...grades),key=s.type+'|'+s.id+'|'+xs.map(x=>x.grade).join('/');if(spread>=3&&!S.capitalKeys52[key]){S.capitalKeys52[key]=1;S.ratingSplits52++;remember('SPLIT RATING: '+s.name+' is simultaneously '+xs.map(x=>x.grade+' at '+x.agency).join(' and '),realm(s.reality));if(typeof place==='function')place('cold','two ratings one treasury',realm(s.reality));capitalCrisis(s.reality,'split-rating')}}
function applyRatingImpact(s,oldGrade,newGrade,r){let idx=notch(newGrade);s.obj.creditRating52=newGrade;s.obj.creditScore52=r.score;if(s.type==='insurer'){for(const p of (S.riskPolicies51||[]).filter(p=>p.insurerId===s.id&&p.status==='active')){p.rating52=newGrade;if(idx>3&&!p.ratingWatch52){p.ratingWatch52=true;p.premium=Math.round((p.premium||1)*1.15*10)/10}if(idx<=3)p.ratingWatch52=false}if(idx>3&&s.obj.status==='solvent'){s.obj.status='rating-restricted';S.ratingRestrictedInsurers52++;remember('RATING RESTRICTION: '+s.name+' may service old policies but cannot write ordinary new coverage',realm(s.reality));if(typeof place==='function')place('cold','insurance license replaced by credit threshold',realm(s.reality))}if(idx<=3&&s.obj.status==='rating-restricted')s.obj.status='solvent';if(newGrade==='D'&&s.obj.status!=='insolvent'){s.obj.status='insolvent';for(const p of (S.riskPolicies51||[]).filter(p=>p.insurerId===s.id&&p.status==='active'))p.status='orphaned'}}for(const b of S.softwareBonds52.filter(b=>b.subjectType===s.type&&b.subjectId===s.id&&b.status==='active'))if(notch(newGrade)>notch(b.covenantGrade))createCollateralCall(b,newGrade,oldGrade);if(oldGrade&&notch(newGrade)-notch(oldGrade)>=2)capitalCrisis(s.reality,'multi-notch-downgrade')}
function shopRating(type,id,manual=true){ensureAgencies();let s=subject(type,id);if(!s)return null;let rs=[];for(const a of S.ratingAgencies52.filter(a=>a.reality===s.reality&&a.status==='active'))rs.push(requestRating(type,id,a.id,true,false,false));rs=rs.filter(Boolean);if(!rs.length)return null;let best=rs.sort((a,b)=>notch(a.grade)-notch(b.grade)||b.score-a.score)[0];for(const x of S.creditRatings52.filter(x=>x.subjectType===type&&x.subjectId===id))x.designated=false;best.designated=true;S.ratingShops52++;remember('RATING SHOP '+best.id+': '+s.name+' designated '+best.grade+' from '+best.agency+' after paying multiple agencies',realm(s.reality));if(typeof place==='function')place('dream','best rating selected from competing definitions of risk',realm(s.reality));if(manual){$('#msg').textContent=s.name+' designated '+best.grade+' after shopping '+rs.length+' agencies.';renderAll();save52();openRating(best)}return best}
function couponFor(grade){return [.035,.045,.055,.07,.095,.13,.18,.28][notch(grade)]||.28}
function issueBond(type,id,manual=true){let s=subject(type,id);if(!s)return null;let r=marketRating(type,id);if(!r){let a=S.ratingAgencies52.find(a=>a.reality===s.reality&&a.status==='active');r=requestRating(type,id,a?.id,false,true,false)}if(!r||r.grade==='D'){if(manual)$('#msg').textContent=s.name+' cannot issue ordinary debt at D.';return null}let principal=Math.round((s.type==='treasury'?8+Math.min(12,(s.obj.balance||0)*.4):10+Math.min(18,(s.obj.capital||0)*.3))*10)/10,coupon=couponFor(r.grade),holder=pick(['archive pension ledger','court reserve fund','dependency commons','continuity savings pool',(s.reality==='A'?'B':'A')+' infrastructure fund']),b={id:'BOND'+(++S.softwareBondSerial52),reality:s.reality,subjectType:type,subjectId:id,subject:s.name,kind:type==='treasury'?'dependency-revenue bond':'insurer surplus note',holder,principal,outstanding:principal,coupon,issueGrade:r.grade,covenantGrade:'BBB',status:'active',collateral:0,missed:0,issued:Date.now(),lastService:Date.now(),matures:Date.now()+150000,ratingId:r.id,x:10+Math.random()*80,y:12+Math.random()*68};S.softwareBonds52.push(b);S.bondsIssued52++;if(type==='treasury'){s.obj.balance=(s.obj.balance||0)+principal;s.obj.capitalDebt52=(s.obj.capitalDebt52||0)+principal}else{s.obj.capital=(s.obj.capital||0)+principal;s.obj.debt52=(s.obj.debt52||0)+principal}remember('CAPITAL ISSUE '+b.id+': '+s.name+' borrowed '+principal+' credits at '+Math.round(coupon*1000)/10+'% against '+r.grade+' rating',realm(s.reality));trustRecord52(s.reality,'software-capital-issue',b.id+' '+b.kind+' '+r.grade);if(typeof place==='function')place('warm',type==='treasury'?'dependency tax pledged to bondholders':'insurance capital funded by borrowed confidence',realm(s.reality));if(manual){$('#msg').textContent=b.id+' issued at '+r.grade+'.';renderAll();save52();openBond(b)}return b}
function createCollateralCall(b,newGrade,oldGrade){let existing=S.capitalCalls52.find(c=>c.bondId===b.id&&c.status==='open');if(existing)return existing;let severity=Math.max(1,notch(newGrade)-notch(b.covenantGrade)),amount=Math.round(Math.min(b.outstanding*.5,b.principal*(.1+.08*severity))*10)/10,c={id:'MARGIN'+(++S.capitalCallSerial52),reality:b.reality,bondId:b.id,subjectType:b.subjectType,subjectId:b.subjectId,subject:b.subject,reason:'rating fell below '+b.covenantGrade+(oldGrade?' from '+oldGrade+' to '+newGrade:''),amount,status:'open',created:Date.now(),paid:0,x:10+Math.random()*80,y:12+Math.random()*68};S.capitalCalls52.push(c);S.collateralCalls52++;remember('COLLATERAL CALL '+c.id+': '+b.subject+' owes '+amount+' credits because its rating is '+newGrade,realm(b.reality));if(typeof place==='function')place('cold','downgrade demanding cash from the downgraded institution',realm(b.reality));return c}
function payCollateral(c,manual=true){if(!c||c.status!=='open')return false;let s=subject(c.subjectType,c.subjectId),b=bond(c.bondId);if(!s||!b)return false;let available=subjectCash(s),pay=Math.min(available,c.amount-c.paid);if(s.type==='treasury')s.obj.balance=Math.max(0,(s.obj.balance||0)-pay);else s.obj.capital=Math.max(0,(s.obj.capital||0)-pay);c.paid+=pay;b.collateral+=pay;if(c.paid>=c.amount-.01){c.status='paid';S.collateralPaid52++;remember('COLLATERAL POSTED '+c.id+': '+s.name+' satisfied the downgrade covenant',realm(s.reality))}else{c.status='failed';remember('COLLATERAL FAILURE '+c.id+': '+s.name+' could not meet the call created by its downgrade',realm(s.reality));defaultBond(b,'failed rating collateral call');S.selfFulfillingDowngrades52++;capitalCrisis(s.reality,'self-fulfilling-downgrade')}if(manual){$('#msg').textContent=c.id+' '+c.status.toUpperCase()+'.';renderAll();save52();openCall(c)}return c.status==='paid'}
function serviceBond(b,manual=true){if(!b||b.status!=='active')return false;let s=subject(b.subjectType,b.subjectId);if(!s)return false;let due=Math.max(.25,Math.round(b.outstanding*b.coupon/8*10)/10),available=subjectCash(s),pay=Math.min(available,due);if(s.type==='treasury')s.obj.balance=Math.max(0,(s.obj.balance||0)-pay);else s.obj.capital=Math.max(0,(s.obj.capital||0)-pay);b.lastService=Date.now();if(pay+0.01<due){b.missed++;remember('DEBT SERVICE SHORTFALL '+b.id+': '+s.name+' paid '+pay.toFixed(1)+' of '+due.toFixed(1),realm(s.reality));if(b.missed>=2)defaultBond(b,'missed debt service')}else{b.missed=0;if(manual)remember('DEBT SERVICE '+b.id+': '+s.name+' paid '+due.toFixed(1)+' to '+b.holder,realm(s.reality))}if(manual){$('#msg').textContent=b.id+' debt service '+(pay+0.01>=due?'paid.':'shortfall.');renderAll();save52();openBond(b)}return pay+0.01>=due}
function defaultBond(b,reason='payment default'){if(!b||b.status==='default')return;b.status='default';b.defaulted=Date.now();b.defaultReason=reason;S.bondDefaults52++;let s=subject(b.subjectType,b.subjectId);if(s){if(s.type==='treasury'){s.obj.status='bankrupt';s.obj.debt=(s.obj.debt||0)+Math.max(0,b.outstanding-b.collateral)}else{s.obj.status='insolvent';for(const p of (S.riskPolicies51||[]).filter(p=>p.insurerId===s.id&&p.status==='active'))p.status='orphaned'}openIncident52(s.reality,'software capital default: '+b.id,'SEV1');remember('SOFTWARE DEBT DEFAULT '+b.id+': '+s.name+' defaulted after '+reason,realm(s.reality));if(typeof place==='function'){place('cold','rating agency caused the default it predicted',realm(s.reality));place('dream','credit model became an execution dependency',realm(s.reality))}capitalCrisis(s.reality,'bond-default')}}
function raiseTaxForBondholders(id,manual=true){let t=treasury(id),n=ns(id);if(!t||!n)return;t.taxRate=cl((t.taxRate||1)+.5,.25,4);remember('BONDHOLDER COVENANT: '+n.name+' raised dependency tax to '+t.taxRate.toFixed(2)+'× to defend its credit rating',realm(n.reality));if(typeof place==='function')place('cold','package users taxed to satisfy software bondholders',realm(n.reality));if(t.taxRate>=2.5)capitalCrisis(n.reality,'bondholder-tax-pressure');if(manual){$('#msg').textContent=n.name+' raised dependency tax for bondholders.';renderAll();save52();openSubject('treasury',id)}}
function auditAgency(a){if(!a)return;a.independence=cl(a.independence+.09,0,1);a.credibility=cl(a.credibility+.05,0,1);a.modelVersion++;let captured=a.capturedBy;a.capturedBy=null;remember('RATINGS MODEL AUDIT: '+a.name+' moved to model v'+a.modelVersion+(captured?' after recusing '+captured:''),realm(a.reality));trustRecord52(a.reality,'credit-rating-model-audit',a.id+' v'+a.modelVersion);$('#msg').textContent=a.name+' model audited.';renderAll();save52();openAgency(a)}
function refreshMarketRating(type,id,manual=true){let s=subject(type,id);if(!s)return;let rs=agencyRatings(type,id);if(!rs.length){let a=S.ratingAgencies52.find(a=>a.reality===s.reality);return requestRating(type,id,a?.id,false,true,manual)}for(const old of rs)requestRating(type,id,old.agencyId,false,old.designated,false);let m=marketRating(type,id);if(manual){$('#msg').textContent=s.name+' market rating refreshed to '+(m?.grade||'unrated')+'.';renderAll();save52();openSubject(type,id)}return m}
function auditCapital(id){let treas=(S.namespaces46||[]).filter(n=>n.reality===id).map(n=>treasury(n.id)).filter(Boolean),ins=(S.insurers51||[]).filter(i=>i.reality===id),bonds=S.softwareBonds52.filter(b=>b.reality===id&&b.status==='active'),calls=S.capitalCalls52.filter(c=>c.reality===id&&c.status==='open'),a={id:'CAUD'+(++S.capitalAuditSerial52),reality:id,treasuryCash:treas.reduce((n,t)=>n+(t.balance||0),0),treasuryDebt:treas.reduce((n,t)=>n+(t.debt||0)+(t.capitalDebt52||0),0),insurerCapital:ins.reduce((n,i)=>n+(i.capital||0),0),insurerDebt:ins.reduce((n,i)=>n+(i.debt52||0),0),bonds:bonds.length,collateralCalls:calls.length,defaults:S.softwareBonds52.filter(b=>b.reality===id&&b.status==='default').length,created:Date.now()};S.capitalAudits52.push(a);S.capitalAudits52=S.capitalAudits52.slice(-64);remember('CAPITAL AUDIT '+a.id+': '+bonds.length+' software obligations backed by '+a.treasuryCash.toFixed(1)+' treasury cash and '+a.insurerCapital.toFixed(1)+' insurer capital',realm(id));return a}
function capitalCrisis(id,reason){if(Date.now()-S.lastCapitalCrisis52<7000)return false;let key=id+'|'+reason+'|'+Math.floor(Date.now()/20000);if(S.capitalKeys52[key])return false;S.capitalKeys52[key]=1;S.capitalCrises52++;S.lastCapitalCrisis52=Date.now();for(const rid of ['A','B']){realm(rid).disputes=(realm(rid).disputes||0)+1;remember('CAPITAL CRISIS: a model of software creditworthiness became authority over whether infrastructure could continue financing itself',realm(rid))}if(typeof place==='function'){place('cold','credit rating acting like infrastructure law',realm(id));place('dream','confidence collateralized into reality',realm(id))}S.bailiffMood='asking whether the package is risky because the rating fell or rated risky because everyone obeyed the rating';return true}
function openRating(r){let s=subject(r.subjectType,r.subjectId),a=agency(r.agencyId),b=[];if(!r.designated)b.push(['designate this rating',()=>{for(const x of S.creditRatings52.filter(x=>x.subjectType===r.subjectType&&x.subjectId===r.subjectId))x.designated=false;r.designated=true;renderAll();save52();openRating(r)}]);if(s&&a)b.push(['pay for reconsideration',()=>requestRating(r.subjectType,r.subjectId,a.id,true,true)]);if(a)b.push(['open '+a.name,()=>openAgency(a)]);b.push(['close',closePanel]);panel(r.id+' · '+r.grade,r.subject+' · '+r.agency,Math.round(r.score)+' score · '+r.outlook+' outlook · model v'+r.modelVersion+(r.paid?' · issuer-paid':'')+(r.designated?' · DESIGNATED':''),b)}
function openAgency(a){let b=[['audit rating model',()=>auditAgency(a)]];let recent=[...S.creditRatings52].reverse().filter(r=>r.agencyId===a.id).slice(0,4);for(const r of recent)b.push(['open '+r.id+' '+r.grade,()=>openRating(r)]);b.push(['close',closePanel]);panel(a.name+' · '+a.status.toUpperCase(),a.id+' · '+a.model+' · model v'+a.modelVersion,'independence '+Math.round(a.independence*100)+'% · credibility '+Math.round(a.credibility*100)+'% · revenue '+a.revenue.toFixed(1)+' · issuer-paid '+a.issuerPaid+(a.capturedBy?' · CAPTURED BY '+a.capturedBy:''),b)}
function openCall(c){let b=[];if(c.status==='open')b.push(['post collateral',()=>payCollateral(c)]);let bo=bond(c.bondId);if(bo)b.push(['open '+bo.id,()=>openBond(bo)]);b.push(['close',closePanel]);panel(c.id+' · '+c.status.toUpperCase(),c.subject+' · '+c.amount+' credits',c.reason+' · paid '+c.paid.toFixed(1),b)}
function openBond(b){let s=subject(b.subjectType,b.subjectId),calls=S.capitalCalls52.filter(c=>c.bondId===b.id&&['open','failed'].includes(c.status)),acts=[];if(b.status==='active'){acts.push(['pay debt service',()=>serviceBond(b)]);if(s?.type==='treasury')acts.push(['raise dependency tax for bondholders',()=>raiseTaxForBondholders(s.id)]);acts.push(['refresh issuer rating',()=>refreshMarketRating(b.subjectType,b.subjectId)])}for(const c of calls.slice(-2))acts.push(['open '+c.id,()=>openCall(c)]);acts.push(['close',closePanel]);panel(b.id+' · '+b.status.toUpperCase(),b.kind+' · '+b.subject,'principal '+b.principal+' · coupon '+Math.round(b.coupon*1000)/10+'% · issue '+b.issueGrade+' · covenant '+b.covenantGrade+' · collateral '+b.collateral.toFixed(1)+' · holder '+b.holder+(b.defaultReason?'\ndefault '+b.defaultReason:''),acts)}
function openSubject(type,id){let s=subject(type,id);if(!s)return;ensureAgencies();let m=marketRating(type,id),bs=S.softwareBonds52.filter(b=>b.subjectType===type&&b.subjectId===id),rs=agencyRatings(type,id),acts=[];for(const a of S.ratingAgencies52.filter(a=>a.reality===s.reality&&a.status==='active'))acts.push(['rate with '+a.name,()=>requestRating(type,id,a.id,false,!m)]);acts.push(['shop issuer-paid rating',()=>shopRating(type,id)],['refresh market rating',()=>refreshMarketRating(type,id)],['issue '+(type==='treasury'?'dependency revenue bond':'surplus note'),()=>issueBond(type,id)]);if(type==='treasury')acts.push(['raise dependency tax for bondholders',()=>raiseTaxForBondholders(id)]);for(const r of rs.slice(-3))acts.push(['open '+r.id+' '+r.grade,()=>openRating(r)]);for(const b of bs.slice(-3))acts.push(['open '+b.id,()=>openBond(b)]);acts.push(['close',closePanel]);panel(s.name+' · '+(m?.grade||'UNRATED'),type==='treasury'?'package finance':'insurance finance','cash '+subjectCash(s).toFixed(1)+' · debt '+subjectDebt(s).toFixed(1)+' · '+rs.length+' agency ratings · '+bs.filter(b=>b.status==='active').length+' active obligations'+(m?.designated?' · designated '+m.agency:''),acts)}
function openCapitalMarket(id=S.active){ensureAgencies();let acts=[['audit capital market',()=>{auditCapital(id);renderAll();save52();openCapitalMarket(id)}]];for(const a of S.ratingAgencies52.filter(a=>a.reality===id))acts.push([a.name,()=>openAgency(a)]);for(const n of (S.namespaces46||[]).filter(n=>n.reality===id).slice(0,5))if(treasury(n.id))acts.push([n.name+' treasury',()=>openSubject('treasury',n.id)]);for(const i of (S.insurers51||[]).filter(i=>i.reality===id).slice(0,5))acts.push([i.name,()=>openSubject('insurer',i.id)]);for(const b of S.softwareBonds52.filter(b=>b.reality===id&&b.status==='active').slice(-4))acts.push(['open '+b.id,()=>openBond(b)]);acts.push(['close',closePanel]);let bonds=S.softwareBonds52.filter(b=>b.reality===id&&b.status==='active').length,calls=S.capitalCalls52.filter(c=>c.reality===id&&c.status==='open').length;panel('SOFTWARE CAPITAL MARKET · Reality '+id,bonds+' active obligations · '+calls+' open collateral calls',S.ratingsPublished52+' ratings · '+S.ratingShops52+' rating shops · '+S.bondsIssued52+' issues · '+S.bondDefaults52+' defaults · '+S.agencyCaptures52+' agency captures · '+S.capitalCrises52+' crises',acts)}
function rateCritical(id=S.active){ensureAgencies();let subjects=[];for(const n of (S.namespaces46||[]).filter(n=>n.reality===id)){let s=subject('treasury',n.id);if(s)subjects.push(s)}for(const i of (S.insurers51||[]).filter(i=>i.reality===id)){let s=subject('insurer',i.id);if(s)subjects.push(s)}subjects.sort((a,b)=>baseScore(a)-baseScore(b));let s=subjects[0];if(!s){$('#msg').textContent='No capital-bearing infrastructure is available to rate.';return}let a=S.ratingAgencies52.find(a=>a.reality===id&&a.status==='active');requestRating(s.type,s.id,a?.id,false,true,true)}
function autonomous(){ensureAgencies();let now=Date.now();if(now-S.lastCapitalTick52<1900)return;S.lastCapitalTick52=now;for(const b of S.softwareBonds52.filter(b=>b.status==='active')){if(now-b.lastService>12000){serviceBond(b,false);break}}if(Math.random()<.004){let rated=[...new Map(S.creditRatings52.map(r=>[r.subjectType+'|'+r.subjectId,{type:r.subjectType,id:r.subjectId,reality:r.reality}])).values()];let x=pick(rated);if(x)refreshMarketRating(x.type,x.id,false)}if(Math.random()<.0015){let id=pick(['A','B']),targets=[];for(const n of (S.namespaces46||[]).filter(n=>n.reality===id)){let s=subject('treasury',n.id);if(s&&!S.softwareBonds52.some(b=>b.subjectType==='treasury'&&b.subjectId===n.id&&b.status==='active'))targets.push(s)}if(targets.length)issueBond('treasury',pick(targets).id,false)}}
function renderCapital(){ensureAgencies();let layer=$('#capitalLayer');if(!layer){layer=document.createElement('div');layer.id='capitalLayer';document.body.appendChild(layer)}layer.innerHTML='';for(const a of S.ratingAgencies52){let e=document.createElement('i');e.className='ratingAgency'+(a.capturedBy?' captured':'');e.dataset.label=a.id;e.style.left=a.x+'%';e.style.top=a.y+'%';e.onclick=()=>openAgency(a);layer.appendChild(e)}for(const r of S.creditRatings52.slice(-18)){let e=document.createElement('i');e.className='ratingBadge grade'+r.grade;e.dataset.label=r.grade;e.style.left=r.x+'%';e.style.top=r.y+'%';e.onclick=()=>openRating(r);layer.appendChild(e)}for(const b of S.softwareBonds52.filter(b=>['active','default'].includes(b.status)).slice(-14)){let e=document.createElement('i');e.className='capitalNote '+b.status;e.dataset.label=b.id.replace('BOND','B');e.style.left=b.x+'%';e.style.top=b.y+'%';e.onclick=()=>openBond(b);layer.appendChild(e)}for(const c of S.capitalCalls52.filter(c=>['open','failed'].includes(c.status)).slice(-10)){let e=document.createElement('i');e.className='capitalCall '+c.status;e.dataset.label='!';e.style.left=c.x+'%';e.style.top=c.y+'%';e.onclick=()=>openCall(c);layer.appendChild(e)}let line=$('#capitalline');if(!line){line=document.createElement('div');line.id='capitalline';line.className='line';($('#insuranceline')||$('#standardsline')||$('#oversightline')||$('#enforcement')).after(line)}let id=S.active,bonds=S.softwareBonds52.filter(b=>b.reality===id&&b.status==='active').length,calls=S.capitalCalls52.filter(c=>c.reality===id&&c.status==='open').length,defaults=S.softwareBonds52.filter(b=>b.reality===id&&b.status==='default').length;line.textContent='software capital: '+S.creditRatings52.filter(r=>r.reality===id).length+' ratings · '+bonds+' obligations · '+calls+' collateral calls · '+defaults+' defaults · '+S.ratingSplits52+' split ratings · '+S.capitalCrises52+' crises';let ctr=document.querySelector('#app .controls');if(ctr&&!$('#openCapitalMarketButton')){let x=document.createElement('button');x.id='openCapitalMarketButton';x.textContent='open capital market';x.onclick=()=>openCapitalMarket(S.active);ctr.prepend(x)}if(ctr&&!$('#rateCriticalButton')){let x=document.createElement('button');x.id='rateCriticalButton';x.textContent='rate critical infrastructure';x.onclick=()=>rateCritical(S.active);ctr.prepend(x)}}
renderAll=function(){BR52();renderCapital()};let f=$('#forget');if(f)f.onclick=()=>{for(let i=2;i<=52;i++)localStorage.removeItem('nothing-state-v'+i);location.reload()};
setInterval(()=>{autonomous();renderCapital();save52()},2200);ensureAgencies();renderAll();save52();
})();
