(()=>{
const B93=save,R93=renderAll,O=JSON.parse(localStorage.getItem('nothing-state-v93')||'null')||{},RECOVER93=!Array.isArray(O.capitalRestorationOrders93),K=['capitalRestorationOffice93','capitalRestorationOrders93','capitalRestorationActions93','capitalRestorationOrderSerial93','capitalRestorationActionSerial93','capitalRestorationOrdersCreated93','capitalRestorationBufferTargetTotal93','capitalRestorationBufferHeldTotal93','capitalRestorationCurrentShortfall93','capitalRestorationPeakShortfall93','capitalRestorationBufferTopups93','capitalRestorationBufferTopupAmount93','capitalRestorationBufferDeployments93','capitalRestorationBufferDeploymentAmount93','capitalRestorationBufferReleases93','capitalRestorationBufferReleaseAmount93','capitalRestorationRestrictedAuthorities93','capitalRestorationCompleted93','capitalRestorationCrises93','capitalRestorationKeys93','lastCapitalRestorationTick93'];
for(const k of K)S[k]=O[k]??(k==='capitalRestorationOrders93'||k==='capitalRestorationActions93'?[]:/Serial|Created|Total|Shortfall|Topups|Amount|Deployments|Releases|Restricted|Completed|Crises|Tick/.test(k)?0:/Keys/.test(k)?{}:/Office/.test(k)?null:[]);
function save93(){B93();let o={};for(const k of K)o[k]=S[k];localStorage.setItem('nothing-state-v93',JSON.stringify(o))}save=save93;
const q=s=>$(s),realm=id=>S.real[id],EPS=.0001;
function trust(id,status,note){S.trustAudits=S.trustAudits||[];S.trustAuditSerial=S.trustAuditSerial||0;S.trustAudits.push({id:'TA'+(++S.trustAuditSerial),reality:id,status,created:Date.now(),note,x:10+Math.random()*80,y:12+Math.random()*68})}
function incident(id,title,sev='SEV2'){S.incidents=S.incidents||[];S.incidentSerial=S.incidentSerial||0;let ex=S.incidents.find(x=>x.reality===id&&x.title===title&&x.status==='open');if(ex)return ex;let i={id:'INC'+(++S.incidentSerial),reality:id,title,severity:sev,status:'open',started:Date.now(),owner:'capital restoration office',x:10+Math.random()*80,y:12+Math.random()*68};S.incidents.push(i);return i}
function crisis(id,why,key,sev='SEV1'){let n=Date.now(),k=id+'|'+key;if(S.capitalRestorationKeys93[k]&&n-S.capitalRestorationKeys93[k]<14000)return;S.capitalRestorationKeys93[k]=n;S.capitalRestorationCrises93++;remember('CAPITAL RESTORATION: '+why+' turned a supervisory capital breach into a continuing recovery obligation',realm(id));if(typeof place==='function'){place('cold','central bank rebuilding a buffer after supervision proved its capital could run out',realm(id));place('dream','capital released by repayment but still not free because the breach must be repaired first',realm(id))}incident(id,'supervisory capital restoration: '+why,sev)}
function ensure(){if(!S.supervisoryCapitalOffice92)return null;if(!S.capitalRestorationOffice93){S.capitalRestorationOffice93={id:'CRO1',name:'Interreality Supervisory Capital Restoration Office',status:'prompt-corrective-action',created:Date.now(),x:50,y:78};remember('CAPITAL RESTORATION CRO1: an uncovered Build 92 supervisory capital requirement acquired a post-breach restoration buffer',realm('A'));remember('CAPITAL RESTORATION CRO1: an uncovered Build 92 supervisory capital requirement acquired a post-breach restoration buffer',realm('B'));trust('A','capital-restoration-created','CRO1');trust('B','capital-restoration-created','CRO1')}return S.capitalRestorationOffice93}
function authority(id){return(S.monetaryAuthorities55||[]).find(a=>a.id===id)}
function requirements(id){return(S.supervisoryCapitalRequirements92||[]).filter(r=>r.authorityId===id&&!['orphaned-authority'].includes(r.status))}
function shortfall(id){return requirements(id).reduce((n,r)=>n+Math.max(0,r.shortfall92||0),0)}
function exposure(id){return requirements(id).reduce((n,r)=>n+Math.max(0,r.required92||0),0)}
function activeOrder(id){return(S.capitalRestorationOrders93||[]).find(o=>o.authorityId===id&&!['released-exposure-closed','orphaned-authority'].includes(o.status))}
function upsert(arr,id,snap){let i=arr.findIndex(x=>x.id===id);if(i>=0)arr[i]=snap;else arr.push(snap)}
function markOrder(o,a){if(!a)return;let snap=JSON.parse(JSON.stringify(o));a.capitalRestorationOrder93=o.id;a.capitalRestorationMarkers93=a.capitalRestorationMarkers93||[];upsert(a.capitalRestorationMarkers93,o.id,snap);a.capitalRestorationLatest93=o.id;a.capitalRestorationHeld93=o.bufferHeld93||0;a.capitalRestorationTarget93=o.bufferTarget93||0;a.capitalRestorationRestricted93=!!o.restricted93}
function markAction(x,a){if(!a)return;let snap=JSON.parse(JSON.stringify(x));a.capitalRestorationActions93=a.capitalRestorationActions93||[];upsert(a.capitalRestorationActions93,x.id,snap);a.capitalRestorationActionLatest93=x.id}
function action(kind,o,a,amount,before,after,note=''){let x={id:'CRA'+(++S.capitalRestorationActionSerial93),kind93:kind,orderId93:o.id,authorityId:o.authorityId,reality:o.reality,amount93:amount,heldBefore93:before,heldAfter93:after,capitalAfter93:a.capital,note93:note,created:Date.now()};S.capitalRestorationActions93.push(x);if(kind==='buffer-topup'){S.capitalRestorationBufferTopups93++;S.capitalRestorationBufferTopupAmount93+=amount}else if(kind==='buffer-deployment'){S.capitalRestorationBufferDeployments93++;S.capitalRestorationBufferDeploymentAmount93+=amount}else if(kind==='buffer-release'){S.capitalRestorationBufferReleases93++;S.capitalRestorationBufferReleaseAmount93+=amount}markAction(x,a);return x}
function createOrder(a){let s=shortfall(a.id);if(s<=EPS||activeOrder(a.id))return null;let o={id:'SRO'+(++S.capitalRestorationOrderSerial93),authorityId:a.id,reality:a.reality,peakShortfall93:s,currentShortfall93:s,bufferTarget93:s*.5,bufferHeld93:0,bufferGap93:s*.5,liveExposure93:exposure(a.id),restricted93:true,status:'capital-deficient',created:Date.now(),x:10+Math.random()*80,y:12+Math.random()*68};S.capitalRestorationOrders93.push(o);S.capitalRestorationOrdersCreated93++;markOrder(o,a);remember('CAPITAL RESTORATION '+o.id+': '+a.name+' entered prompt corrective action after '+s.toFixed(2)+' of Build 92 capital remained uncovered; restoration buffer target '+o.bufferTarget93.toFixed(2),realm(a.reality));trust(a.reality,'capital-restoration-order',o.id+' shortfall '+s.toFixed(2));crisis(a.reality,a.name+' could not fully fund its Build 92 supervisory capital requirement','order-'+o.id);return o}
function sync(o){let a=authority(o.authorityId);if(!a){o.status='orphaned-authority';o.restricted93=false;return false}let changed=false,s=shortfall(a.id),e=exposure(a.id);o.currentShortfall93=s;o.liveExposure93=e;if(s>o.peakShortfall93+EPS){let old=o.bufferTarget93;o.peakShortfall93=s;o.bufferTarget93=s*.5;o.bufferGap93=Math.max(0,o.bufferTarget93-(o.bufferHeld93||0));action('target-increase',o,a,o.bufferTarget93-old,o.bufferHeld93||0,o.bufferHeld93||0,'peak shortfall increased');crisis(a.reality,o.id+' peak shortfall increased to '+s.toFixed(2),'peak-'+o.id+'-'+s.toFixed(4));changed=true}
if(s>EPS){o.restricted93=true;o.status='capital-deficient';if((o.bufferHeld93||0)>EPS){let give=Math.min(o.bufferHeld93,s),before=o.bufferHeld93;o.bufferHeld93=Math.max(0,before-give);a.capital=(a.capital||0)+give;action('buffer-deployment',o,a,give,before,o.bufferHeld93,'released to free authority capital for Build 92 to consume on its next reconciliation');changed=true}o.bufferGap93=Math.max(0,o.bufferTarget93-(o.bufferHeld93||0));markOrder(o,a);return changed}
if(e<=EPS){if((o.bufferHeld93||0)>EPS){let rel=o.bufferHeld93,before=o.bufferHeld93;o.bufferHeld93=0;a.capital=(a.capital||0)+rel;action('buffer-release',o,a,rel,before,0,'all Build 92 post-cap exposure closed');changed=true}if(o.status!=='released-exposure-closed'){o.status='released-exposure-closed';o.restricted93=false;o.releasedAt93=Date.now();S.capitalRestorationCompleted93++;remember('CAPITAL RESTORATION '+o.id+' RELEASED: all post-cap supervisory exposure closed and the restoration buffer returned to '+a.name,realm(a.reality));trust(a.reality,'capital-restoration-released',o.id);changed=true}o.bufferGap93=0;markOrder(o,a);return changed}
let need=Math.max(0,o.bufferTarget93-(o.bufferHeld93||0));if(need>EPS&&Math.max(0,a.capital||0)>EPS){let take=Math.min(need,Math.max(0,a.capital||0)),before=o.bufferHeld93||0;a.capital=Math.max(0,(a.capital||0)-take);o.bufferHeld93=before+take;action('buffer-topup',o,a,take,before,o.bufferHeld93,'post-breach restoration buffer');changed=true}o.bufferGap93=Math.max(0,o.bufferTarget93-(o.bufferHeld93||0));if(o.bufferGap93<=EPS){o.bufferGap93=0;o.status='buffered-active';o.restricted93=false;o.bufferedAt93=o.bufferedAt93||Date.now()}else{o.status='buffer-building';o.restricted93=true}markOrder(o,a);return changed}
function recompute(){S.capitalRestorationBufferTargetTotal93=0;S.capitalRestorationBufferHeldTotal93=0;S.capitalRestorationCurrentShortfall93=0;S.capitalRestorationPeakShortfall93=0;let restricted=new Set();for(const o of(S.capitalRestorationOrders93||[])){if(o.status==='orphaned-authority')continue;let live=o.status!=='released-exposure-closed';if(live){S.capitalRestorationBufferTargetTotal93+=Math.max(0,o.bufferTarget93||0);S.capitalRestorationBufferHeldTotal93+=Math.max(0,o.bufferHeld93||0);S.capitalRestorationCurrentShortfall93+=Math.max(0,o.currentShortfall93||0)}S.capitalRestorationPeakShortfall93+=Math.max(0,o.peakShortfall93||0);if(o.restricted93)restricted.add(o.authorityId)}S.capitalRestorationRestrictedAuthorities93=restricted.size}
function reconstruct(){if(!RECOVER93)return false;let changed=false,seenO=new Map(),seenA=new Map();for(const a of(S.monetaryAuthorities55||[])){for(const m of(a.capitalRestorationMarkers93||[]))seenO.set(m.id,m);for(const x of(a.capitalRestorationActions93||[]))seenA.set(x.id,x)}for(const m of seenO.values()){if((S.capitalRestorationOrders93||[]).some(x=>x.id===m.id))continue;let o=JSON.parse(JSON.stringify(m));o.recovered=true;S.capitalRestorationOrders93.push(o);S.capitalRestorationOrdersCreated93++;let n=Number(String(o.id).replace(/\D/g,''))||0;if(n>S.capitalRestorationOrderSerial93)S.capitalRestorationOrderSerial93=n;changed=true}for(const m of seenA.values()){if((S.capitalRestorationActions93||[]).some(x=>x.id===m.id))continue;let x=JSON.parse(JSON.stringify(m));x.recovered=true;S.capitalRestorationActions93.push(x);if(x.kind93==='buffer-topup'){S.capitalRestorationBufferTopups93++;S.capitalRestorationBufferTopupAmount93+=x.amount93||0}else if(x.kind93==='buffer-deployment'){S.capitalRestorationBufferDeployments93++;S.capitalRestorationBufferDeploymentAmount93+=x.amount93||0}else if(x.kind93==='buffer-release'){S.capitalRestorationBufferReleases93++;S.capitalRestorationBufferReleaseAmount93+=x.amount93||0}let n=Number(String(x.id).replace(/\D/g,''))||0;if(n>S.capitalRestorationActionSerial93)S.capitalRestorationActionSerial93=n;changed=true}recompute();return changed}
function reconcile(){if(!ensure())return false;let changed=reconstruct();for(const a of(S.monetaryAuthorities55||[]))if(shortfall(a.id)>EPS&&!activeOrder(a.id)&&createOrder(a))changed=true;for(const o of(S.capitalRestorationOrders93||[]))if(!['released-exposure-closed','orphaned-authority'].includes(o.status)&&sync(o))changed=true;recompute();return changed}
function openOrder(o){let a=authority(o.authorityId),acts=[];for(const x of(S.capitalRestorationActions93||[]).filter(x=>x.orderId93===o.id).slice(-7))acts.push(['open '+x.id,()=>openAction(x)]);acts.push(['close',closePanel]);panel(o.id+' · CAPITAL RESTORATION',o.status.toUpperCase(),(a?a.name:'missing authority')+' · current shortfall '+(o.currentShortfall93||0).toFixed(2)+' · peak '+(o.peakShortfall93||0).toFixed(2)+' · buffer '+(o.bufferHeld93||0).toFixed(2)+' / '+(o.bufferTarget93||0).toFixed(2)+' · live post-cap exposure '+(o.liveExposure93||0).toFixed(2)+' · authority free capital '+(a?(a.capital||0).toFixed(2):'missing'),acts)}
function openAction(x){panel(x.id+' · CAPITAL RESTORATION ACTION',x.kind93.toUpperCase(),x.authorityId+' · '+(x.amount93||0).toFixed(2)+' · buffer '+(x.heldBefore93||0).toFixed(2)+'→'+(x.heldAfter93||0).toFixed(2)+' · authority free capital '+(x.capitalAfter93||0).toFixed(2)+(x.note93?' · '+x.note93:''),[['close',closePanel]])}
function openOffice(){if(!ensure())return;let acts=[];for(const o of S.capitalRestorationOrders93.slice(-10))acts.push(['open '+o.id+' · '+o.status,()=>openOrder(o)]);acts.push(['close',closePanel]);panel(S.capitalRestorationOffice93.name,'PROMPT CORRECTIVE ACTION · CRO1',S.capitalRestorationOrdersCreated93+' orders · '+S.capitalRestorationCurrentShortfall93.toFixed(2)+' current shortfall · '+S.capitalRestorationBufferHeldTotal93.toFixed(2)+' / '+S.capitalRestorationBufferTargetTotal93.toFixed(2)+' restoration buffer · '+S.capitalRestorationRestrictedAuthorities93+' restricted authorities',acts)}
function render93(){if(!ensure())return;let layer=q('#capitalRestorationLayer93');if(!layer){layer=document.createElement('div');layer.id='capitalRestorationLayer93';document.body.appendChild(layer)}layer.innerHTML='';let office=document.createElement('i');office.className='capitalRestorationOffice93';office.dataset.label='RST';office.style.left='50%';office.style.top='78%';office.onclick=openOffice;layer.appendChild(office);for(const o of S.capitalRestorationOrders93.slice(-8)){let n=document.createElement('i');n.className='capitalRestoration93 '+o.status;n.dataset.label=o.status==='capital-deficient'?'R!':o.status==='buffered-active'?'RB':'R';n.style.left=o.x+'%';n.style.top=o.y+'%';n.onclick=()=>openOrder(o);layer.appendChild(n)}let line=q('#capitalrestorationline93');if(!line){line=document.createElement('div');line.id='capitalrestorationline93';line.className='line';(q('#supervisorycapitalline92')||q('#monetaryexceptionline91')||q('#monetaryline')||q('#enforcement')).after(line)}line.textContent='capital restoration: '+S.capitalRestorationCurrentShortfall93.toFixed(2)+' shortfall · '+S.capitalRestorationBufferHeldTotal93.toFixed(2)+' / '+S.capitalRestorationBufferTargetTotal93.toFixed(2)+' buffer · '+S.capitalRestorationRestrictedAuthorities93+' restricted';let ctr=document.querySelector('#app .controls');if(ctr&&!q('#openCapitalRestoration93')){let x=document.createElement('button');x.id='openCapitalRestoration93';x.textContent='open capital restoration';x.onclick=openOffice;ctr.prepend(x)}}
renderAll=function(){R93();let changed=reconcile();render93();if(changed)save93()};let f=q('#forget');if(f)f.onclick=()=>{for(let i=2;i<=93;i++)localStorage.removeItem('nothing-state-v'+i);location.reload()};setInterval(()=>{reconcile();render93();save93()},2300);ensure();reconcile();renderAll();save93();
})();
