(()=>{
const B80=save,R80=renderAll,O=JSON.parse(localStorage.getItem('nothing-state-v80')||'null')||{},RECOVER80=!Array.isArray(O.carryMarginCalls80),K=['macroprudentialOffice80','carryMarginCalls80','carryMarginSerial80','carryMarginsIssued80','carryMarginsMet80','carryMarginsForced80','carryMarginFailures80','carryMarginPosted80','carryMarginReturned80','carryMarginForcedDomestic80','carryMarginBuild55Escalations80','carryMarginCrises80','carryMarginKeys80','lastCarryMarginTick80'];
for(const k of K)S[k]=O[k]??(/Serial|Issued|Met|Forced|Failures|Posted|Returned|Domestic|Escalations|Crises|Tick/.test(k)?0:/Keys/.test(k)?{}:/Office/.test(k)?null:[]);
function save80(){B80();let o={};for(const k of K)o[k]=S[k];localStorage.setItem('nothing-state-v80',JSON.stringify(o))}save=save80;
const q=s=>$(s),realm=id=>S.real[id],market=()=>S.fxMarkets56?.[0],fund=()=>S.stabilizationFunds58?.[0],position=id=>(S.sterilizationCarryPositions79||[]).find(x=>x.id===id),facility=id=>(S.liquidityFacilities55||[]).find(x=>x.id===id),cl=(v,a,b)=>Math.max(a,Math.min(b,v));
function trust(id,status,note){S.trustAudits=S.trustAudits||[];S.trustAuditSerial=S.trustAuditSerial||0;S.trustAudits.push({id:'TA'+(++S.trustAuditSerial),reality:id,status,created:Date.now(),note,x:10+Math.random()*80,y:12+Math.random()*68})}
function incident(id,title,sev='SEV1'){S.incidents=S.incidents||[];S.incidentSerial=S.incidentSerial||0;let ex=S.incidents.find(x=>x.reality===id&&x.title===title&&x.status==='open');if(ex)return ex;let i={id:'INC'+(++S.incidentSerial),reality:id,title,severity:sev,status:'open',started:Date.now(),owner:'macroprudential carry margin authority',x:10+Math.random()*80,y:12+Math.random()*68};S.incidents.push(i);return i}
function crisis(id,why,sev='SEV1'){let n=Date.now(),k=id+'|'+why;if(S.carryMarginKeys80[k]&&n-S.carryMarginKeys80[k]<14000)return;S.carryMarginKeys80[k]=n;S.carryMarginCrises80++;remember('CARRY MARGIN CRISIS: '+why+' made the monetary authority margin the FX trade funded by its own sterilization credit',realm(id));if(typeof place==='function'){place('cold','central bank margining the currency bet financed by its own temporary money',realm(id));place('dream','macroprudential safety consuming the cash needed to repay lender-of-last-resort credit',realm(id))}incident(id,'macroprudential carry margin crisis: '+why,sev)}
function ensure(){if(!S.sterilizationCarryOffice79||!market()||!fund())return null;if(!S.macroprudentialOffice80){S.macroprudentialOffice80={id:'MPM1',name:'Interreality Macroprudential Carry Margin Authority',status:'margining',created:Date.now(),x:50,y:96.5};remember('MACROPRUDENTIAL MARGIN MPM1: sterilization-funded FX carry acquired a central-bank margin regime',realm('A'));remember('MACROPRUDENTIAL MARGIN MPM1: sterilization-funded FX carry acquired a central-bank margin regime',realm('B'));trust('A','macroprudential-carry-margin-created','MPM1');trust('B','macroprudential-carry-margin-created','MPM1')}return S.macroprudentialOffice80}
function borrower(f){if(!f)return null;if(f.borrowerType==='dealer'){let o=(S.derivativeDealers53||[]).find(x=>x.id===f.borrowerId);return o?{obj:o,cashField:'capital',name:o.name||f.borrowerId}:null}if(f.borrowerType==='ccp'){let o=(S.clearinghouses54||[]).find(x=>x.id===f.borrowerId);return o?{obj:o,cashField:'liquidity',name:o.name||f.borrowerId}:null}if(f.borrowerType==='insurer'){let o=(S.insurers51||[]).find(x=>x.id===f.borrowerId);return o?{obj:o,cashField:'capital',name:o.name||f.borrowerId}:null}if(f.borrowerType==='treasury'){let o=(S.packageTreasuries47||[]).find(x=>x.namespaceId===f.borrowerId),n=(S.namespaces46||[]).find(x=>x.id===f.borrowerId);return o?{obj:o,cashField:'balance',name:(n?.name||f.borrowerId)+' package treasury'}:null}return null}
function cash(b){return Math.max(0,b?.obj?.[b.cashField]||0)}
function addCash(b,x){if(b)b.obj[b.cashField]=Math.max(0,(b.obj[b.cashField]||0)+x)}
function mark(p){let r=Math.max(.18,market()?.rate||p.entryRate||1),value=p.reality==='B'?(p.foreignUnits||0)*r:(p.foreignUnits||0)/r,pnl=value-(p.domesticDeployed||0);return{rate:r,value,pnl,returnPct:(p.domesticDeployed||0)>.001?pnl/p.domesticDeployed:0}}
function marginRate(p){let m=mark(p),r=.20;if(p.status==='rollover-risk')r+=.15;if(p.status==='open-permanent-money')r+=.20;if(m.returnPct<0)r+=Math.min(.20,-m.returnPct*.8);return Math.min(.55,r)}
function requirement(p){return Math.max(0,(p.domesticDeployed||0)*marginRate(p))}
function currentPosted(p){return Math.max(0,p.macroMarginPosted80||0)}
function callFor(id){return(S.carryMarginCalls80||[]).find(c=>c.id===id)||null}
function openCallForPosition(id){return(S.carryMarginCalls80||[]).find(c=>c.positionId79===id&&['open','partial'].includes(c.status))||null}
function syncMarker(c,p){if(!p)return;p.macroMarginMarkers80=p.macroMarginMarkers80||[];let snap=JSON.parse(JSON.stringify(c)),i=p.macroMarginMarkers80.findIndex(x=>x.id===c.id);if(i>=0)p.macroMarginMarkers80[i]=snap;else p.macroMarginMarkers80.push(snap);p.macroMarginLatest80=c.id;let f=facility(p.facilityId55);if(f){f.macroMarginCallIds80=f.macroMarginCallIds80||[];if(!f.macroMarginCallIds80.includes(c.id))f.macroMarginCallIds80.push(c.id)}}
function reconstruct(){if(!RECOVER80)return false;let changed=false;for(const p of(S.sterilizationCarryPositions79||[])){for(const m of(p.macroMarginMarkers80||[])){if(callFor(m.id))continue;let c=JSON.parse(JSON.stringify(m));c.recovered=true;S.carryMarginCalls80.push(c);S.carryMarginsIssued80++;S.carryMarginPosted80+=(c.paidCash||0)+(c.paidUnwind||0);if((c.paidUnwind||0)>0){S.carryMarginsForced80++;S.carryMarginForcedDomestic80+=c.paidUnwind||0}if(['met','met-forced-unwind'].includes(c.status))S.carryMarginsMet80++;if(c.status==='failed')S.carryMarginFailures80++;if(c.build55CallId80)S.carryMarginBuild55Escalations80++;let n=Number(String(c.id).replace(/\D/g,''))||0;if(n>S.carryMarginSerial80)S.carryMarginSerial80=n;changed=true}S.carryMarginReturned80+=p.macroMarginReturned80||0}return changed}
function fxUnwind(p,domestic){let m=market(),f=fund();if(!m||domestic<=.001)return 0;let value=(f?.poolRA||0)*Math.max(.18,m.rate||1)+(f?.poolRB||0),notionalRB=p.reality==='B'?domestic:domestic*Math.max(.18,m.rate||1),liq=Math.max(20,20+value),impact=Math.min(.03,notionalRB/liq*.05),sign=p.reality==='B'?-1:1,before=m.rate;m.previousRate=m.rate;m.rate=cl((m.rate||1)*(1+sign*impact),.18,4.5);m.pressure=(m.pressure||0)+sign*notionalRB*.012;m.turnover=(m.turnover||0)+notionalRB;m.lastMove=Date.now();return Math.abs(m.rate-before)}
function escalate55(c,p,remaining){let f=facility(p.facilityId55);if(!f||remaining<=.01)return null;S.monetaryCollateralCalls55=S.monetaryCollateralCalls55||[];let ex=f.macroMarginCBMC80?S.monetaryCollateralCalls55.find(x=>x.id===f.macroMarginCBMC80):S.monetaryCollateralCalls55.find(x=>x.facilityId===f.id&&x.macroprudential80&&['open','failed'].includes(x.status));if(ex){c.build55CallId80=ex.id;return ex}S.monetaryCollateralCallSerial55=S.monetaryCollateralCallSerial55||0;let amt=Math.max(.1,Math.round(remaining*10)/10),x={id:'CBMC'+(++S.monetaryCollateralCallSerial55),facilityId:f.id,authorityId:f.authorityId,reality:f.reality,borrowerType:f.borrowerType,borrowerId:f.borrowerId,borrower:f.borrower,amount:amt,status:'open',reason:'macroprudential carry margin failed after forced FX unwind',issued:Date.now(),paid:0,x:10+Math.random()*80,y:12+Math.random()*68,macroprudential80:true,carryMarginId80:c.id,positionId79:p.id};S.monetaryCollateralCalls55.push(x);S.monetaryCollateralCallsIssued55=(S.monetaryCollateralCallsIssued55||0)+1;S.carryMarginBuild55Escalations80++;c.build55CallId80=x.id;f.macroprudentialStress80=true;f.macroMarginCBMC80=x.id;remember('BUILD 55 ESCALATION '+x.id+': '+f.borrower+' failed '+c.id+' and now owes '+amt.toFixed(1)+' on the sterilization facility itself',realm(f.reality));trust(f.reality,'carry-margin-escalated-to-build55',x.id+' '+c.id);crisis(f.reality,'failed carry margin became a lender-of-last-resort collateral call','SEV1');return x}
function issueCall(p,manual=true){ensure();if(!p||!['open','rollover-risk','open-permanent-money'].includes(p.status)||openCallForPosition(p.id))return null;let req=requirement(p),posted=currentPosted(p),due=Math.max(0,req-posted);if(due<=.01){if(manual&&q('#msg'))q('#msg').textContent=p.id+' already satisfies the current macroprudential margin requirement.';return null}let m=mark(p),c={id:'MCM'+(++S.carryMarginSerial80),positionId79:p.id,facilityId55:p.facilityId55,reality:p.reality,borrower:p.borrower,status:'open',marginRate:marginRate(p),requirement:req,postedBefore:posted,amount:due,paidCash:0,paidUnwind:0,forcedUnits:0,forcedRealizedPnl:0,markRate:m.rate,returnPct:m.returnPct,issued:Date.now(),x:10+Math.random()*80,y:12+Math.random()*68};S.carryMarginCalls80.push(c);S.carryMarginsIssued80++;syncMarker(c,p);remember('CARRY MARGIN '+c.id+': '+p.borrower+' owes '+due.toFixed(2)+' '+p.domesticCode+' against '+p.id+' at '+Math.round(c.marginRate*100)+'%',realm(p.reality));trust(p.reality,'sterilization-carry-margin-issued',c.id+' '+due.toFixed(2));if(manual){q('#msg').textContent=c.id+' requires '+due.toFixed(2)+' '+p.domesticCode+'.';renderAll();save80();openMargin(c)}return c}
function meetCall(c,manual=true){if(!c||!['open','partial'].includes(c.status))return false;let p=position(c.positionId79),f=facility(c.facilityId55),b=borrower(f);if(!p||!f||!b){c.status='blocked-record';syncMarker(c,p);return false}let remaining=Math.max(0,c.amount-(c.paidCash||0)-(c.paidUnwind||0)),fromCash=Math.min(remaining,cash(b));if(fromCash>.001){addCash(b,-fromCash);c.paidCash=(c.paidCash||0)+fromCash;p.macroMarginPosted80=currentPosted(p)+fromCash;S.carryMarginPosted80+=fromCash;remaining-=fromCash}
if(remaining>.01&&(p.foreignUnits||0)>.0001){let m=mark(p),per=p.reality==='B'?m.rate:1/m.rate,maxProceeds=(p.foreignUnits||0)*per,proceeds=Math.min(remaining,maxProceeds),units=proceeds/per,oldUnits=p.foreignUnits||0,ratio=oldUnits>.0001?units/oldUnits:0,cost=(p.domesticDeployed||0)*ratio,realized=proceeds-cost;p.foreignUnits=Math.max(0,oldUnits-units);p.domesticDeployed=Math.max(0,(p.domesticDeployed||0)-cost);p.forcedRealizedPnl80=(p.forcedRealizedPnl80||0)+realized;c.paidUnwind=(c.paidUnwind||0)+proceeds;c.forcedUnits=(c.forcedUnits||0)+units;c.forcedRealizedPnl=(c.forcedRealizedPnl||0)+realized;p.macroMarginPosted80=currentPosted(p)+proceeds;S.carryMarginPosted80+=proceeds;S.carryMarginsForced80++;S.carryMarginForcedDomestic80+=proceeds;c.fxImpact80=(c.fxImpact80||0)+fxUnwind(p,proceeds);remaining-=proceeds;remember('FORCED CARRY UNWIND '+c.id+': '+p.borrower+' sold '+units.toFixed(3)+' '+p.foreignCode+' to post '+proceeds.toFixed(2)+' '+p.domesticCode+' margin',realm(p.reality));if(typeof place==='function')place('cold','macroprudential margin forcing the central-bank-funded carry trade backward through FX',realm(p.reality))}
let paid=(c.paidCash||0)+(c.paidUnwind||0);if(paid+1e-9>=c.amount){c.status=(c.paidUnwind||0)>0?'met-forced-unwind':'met';c.met=Date.now();S.carryMarginsMet80++;remember('CARRY MARGIN MET '+c.id+': '+p.borrower+' segregated '+paid.toFixed(2)+' '+p.domesticCode,realm(p.reality))}else{c.status='failed';c.failed=Date.now();S.carryMarginFailures80++;let x=escalate55(c,p,Math.max(0,c.amount-paid));c.build55CallId80=x?.id||c.build55CallId80||null}syncMarker(c,p);if(manual){q('#msg').textContent=c.id+' '+c.status.toUpperCase()+' · '+paid.toFixed(2)+' / '+c.amount.toFixed(2)+' posted.';renderAll();save80();openMargin(c)}return c.status==='met'||c.status==='met-forced-unwind'}
function releaseMargin(p){let amt=currentPosted(p);if(amt<=.001||p.macroMarginReleased80)return 0;let f=facility(p.facilityId55),b=borrower(f);if(!b)return 0;addCash(b,amt);p.macroMarginReturned80=(p.macroMarginReturned80||0)+amt;p.macroMarginPosted80=0;p.macroMarginReleased80=true;p.macroMarginReleasedAt80=Date.now();S.carryMarginReturned80+=amt;remember('CARRY MARGIN RELEASED '+p.id+': '+amt.toFixed(2)+' '+p.domesticCode+' returned after the central-bank-funded leverage ended',realm(p.reality));return amt}
function reconcile(){if(!ensure())return false;let changed=reconstruct();for(const p of(S.sterilizationCarryPositions79||[])){let f=facility(p.facilityId55),m=mark(p);p.macroMarginRequired80=requirement(p);p.macroMarginRate80=marginRate(p);p.macroMarginMark80=m.value;if((p.status==='closed'||p.status==='open-unlevered'||f?.status==='repaid')&&currentPosted(p)>.001&&!p.macroMarginReleased80){releaseMargin(p);changed=true}for(const c of(S.carryMarginCalls80||[]).filter(x=>x.positionId79===p.id&&x.build55CallId80)){let x=(S.monetaryCollateralCalls55||[]).find(z=>z.id===c.build55CallId80);if(x&&c.build55Status80!==x.status){c.build55Status80=x.status;syncMarker(c,p);changed=true}}}return changed}
function eligiblePositions(){return(S.sterilizationCarryPositions79||[]).filter(p=>['open','rollover-risk','open-permanent-money'].includes(p.status)&&!openCallForPosition(p.id)&&requirement(p)-currentPosted(p)>.01)}
function openMargin(c){let p=position(c.positionId79),f=facility(c.facilityId55),b=borrower(f),acts=[];if(['open','partial'].includes(c.status))acts.push(['meet margin / force unwind',()=>meetCall(c,true)]);if(c.build55CallId80){let x=(S.monetaryCollateralCalls55||[]).find(z=>z.id===c.build55CallId80);acts.push(['Build 55 '+c.build55CallId80+' · '+(x?.status||'missing'),()=>{if(q('#msg'))q('#msg').textContent=c.build55CallId80+' is governed by the old monetary authority controls.'}])}acts.push(['close',closePanel]);panel(c.id+' · MACROPRUDENTIAL CARRY MARGIN',c.status.toUpperCase(),c.borrower+' · '+Math.round(c.marginRate*100)+'% margin · required '+c.requirement.toFixed(2)+' · prior posted '+c.postedBefore.toFixed(2)+' · call '+c.amount.toFixed(2)+' · cash paid '+(c.paidCash||0).toFixed(2)+' · forced unwind '+(c.paidUnwind||0).toFixed(2)+' · borrower cash '+cash(b).toFixed(2)+(p?' · current carry '+p.domesticDeployed.toFixed(2)+' '+p.domesticCode+' / margin posted '+currentPosted(p).toFixed(2):'')+(c.build55CallId80?' · escalated '+c.build55CallId80+' '+(c.build55Status80||'open'):''),acts)}
function openOffice(){if(!ensure())return;let acts=[];for(const p of eligiblePositions().slice(-6))acts.push(['margin '+p.id+' · '+Math.round(marginRate(p)*100)+'%',()=>issueCall(p,true)]);for(const c of S.carryMarginCalls80.slice(-8))acts.push(['open '+c.id+' · '+c.status,()=>openMargin(c)]);acts.push(['close',closePanel]);panel(S.macroprudentialOffice80.name,'MARGINING · MPM1',S.carryMarginsIssued80+' calls · '+S.carryMarginPosted80.toFixed(2)+' cumulative posted · '+S.carryMarginsForced80+' forced unwinds · '+S.carryMarginFailures80+' failures · '+S.carryMarginBuild55Escalations80+' Build 55 escalations',acts)}
function issueInteresting(){let p=eligiblePositions().slice(-1)[0];if(!p){q('#msg').textContent='No open sterilization carry currently requires additional macroprudential margin.';return null}return issueCall(p,true)}
function render80(){if(!ensure())return;let layer=q('#macroprudentialMarginLayer80');if(!layer){layer=document.createElement('div');layer.id='macroprudentialMarginLayer80';document.body.appendChild(layer)}layer.innerHTML='';let o=document.createElement('i');o.className='macroprudentialOffice80';o.dataset.label='M%';o.style.left='50%';o.style.top='96.5%';o.onclick=openOffice;layer.appendChild(o);for(const c of S.carryMarginCalls80.filter(x=>['open','partial','failed'].includes(x.status)).slice(-8)){let e=document.createElement('i');e.className='carryMargin80 '+c.status;e.dataset.label='MC';e.style.left=c.x+'%';e.style.top=c.y+'%';e.onclick=()=>openMargin(c);layer.appendChild(e)}let line=q('#carrymarginline80');if(!line){line=document.createElement('div');line.id='carrymarginline80';line.className='line';(q('#sterilizationcarryline79')||q('#monetarysterilizationline78')||q('#fxline')||q('#enforcement')).after(line)}line.textContent='carry margin: '+S.carryMarginsIssued80+' calls · '+S.carryMarginPosted80.toFixed(1)+' posted · '+S.carryMarginsForced80+' forced unwinds · '+S.carryMarginBuild55Escalations80+' Build55 escalations';let ctr=document.querySelector('#app .controls');if(ctr&&!q('#openCarryMargin80')){let x=document.createElement('button');x.id='openCarryMargin80';x.textContent='open carry margin authority';x.onclick=openOffice;ctr.prepend(x)}if(ctr&&!q('#issueCarryMargin80')){let x=document.createElement('button');x.id='issueCarryMargin80';x.textContent='issue carry margin';x.onclick=issueInteresting;ctr.prepend(x)}}
renderAll=function(){R80();let changed=reconcile();render80();if(changed)save80()};let f=q('#forget');if(f)f.onclick=()=>{for(let i=2;i<=80;i++)localStorage.removeItem('nothing-state-v'+i);location.reload()};setInterval(()=>{reconcile();render80();save80()},2300);ensure();reconcile();renderAll();save80();
})();