(()=>{
const B65=save,R65=renderAll,O=JSON.parse(localStorage.getItem('nothing-state-v65')||'null')||{},K=['collateralRegistry65','rehypothecations65','collateralRecalls65','titleDisputes65','titleCertificates65','rehypSerial65','recallSerial65','titleDisputeSerial65','titleCertificateSerial65','rehypAdvances65','collateralRecallsFailed65','titleDisputesResolved65','seniorSweeps65','titleCrises65','titleKeys65','lastTitleTick65'];
for(const k of K)S[k]=O[k]??(/Serial|Advances|Failed|Resolved|Sweeps|Crises|Tick/.test(k)?0:/Keys/.test(k)?{}:/Registry/.test(k)?null:[]);
function save65(){B65();let o={};for(const k of K)o[k]=S[k];localStorage.setItem('nothing-state-v65',JSON.stringify(o))}save=save65;
const q=s=>$(s),realm=id=>S.real[id],fund=id=>(S.claimFunds63||[]).find(x=>x.id===id),claim=id=>(S.debtClaims62||[]).find(x=>x.id===id),bond=id=>(S.exchangeBonds62||[]).find(x=>x.id===id),asset=(k,id)=>k==='claim'?claim(id):bond(id),repo=id=>(S.repoLoans64||[]).find(x=>x.id===id),ccpById=id=>(S.clearinghouses54||[]).find(x=>x.id===id)||null,ccpByReality=id=>(S.clearinghouses54||[]).find(x=>x.reality===id&&['operating','stressed','frozen'].includes(x.status))||null,acct=id=>(S.tradeAccounts57||[]).find(x=>x.reality===id),cur=id=>(S.fxCurrencies56||[]).find(x=>x.reality===id),award=id=>[...(S.remedyAwards61||[])].reverse().find(x=>x.kind==='surviving-debt'&&x.respondent===id&&x.recognition==='recognized'&&x.status!=='satisfied')||null;
function trust(id,status,note){S.trustAudits=S.trustAudits||[];S.trustAuditSerial=S.trustAuditSerial||0;S.trustAudits.push({id:'TA'+(++S.trustAuditSerial),reality:id,status,created:Date.now(),note,x:10+Math.random()*80,y:12+Math.random()*68})}
function incident(id,title,sev='SEV1'){S.incidents=S.incidents||[];S.incidentSerial=S.incidentSerial||0;let ex=S.incidents.find(x=>x.reality===id&&x.title===title&&x.status==='open');if(ex)return ex;let i={id:'INC'+(++S.incidentSerial),reality:id,title,severity:sev,status:'open',started:Date.now(),owner:'collateral title registry',x:10+Math.random()*80,y:12+Math.random()*68};S.incidents.push(i);return i}
function crisis(id,why,sev='SEV1'){let n=Date.now(),k=id+'|'+why;if(S.titleKeys65[k]&&n-S.titleKeys65[k]<14000)return;S.titleKeys65[k]=n;S.titleCrises65++;remember('TITLE CRISIS: '+why+' made one asset answer to more than one promise',realm(id));if(typeof place==='function'){place('cold','the owner repaid the loan but the collateral was somewhere else',realm(id));place('dream','one promise wore three name tags and every name tag said senior',realm(id))}incident(id,'collateral title crisis: '+why,sev)}
function ensure(){if(!S.repoFacility64)return null;if(!S.collateralRegistry65){S.collateralRegistry65={id:'CTR1',name:'Interreality Collateral Title Registry',status:'recording',liquidity:12,defaultFund:8,created:Date.now(),x:50,y:90};remember('COLLATERAL REGISTRY CTR1: pledged claims acquired reusable title chains',realm('A'));remember('COLLATERAL REGISTRY CTR1: pledged claims acquired reusable title chains',realm('B'));trust('A','collateral-title-registry-created','CTR1');trust('B','collateral-title-registry-created','CTR1')}return S.collateralRegistry65}
function lenderOf(l){if(l?.lenderKind==='ccp'){let c=ccpById(l.lenderId);if(c)return{id:c.id,name:c.name||c.id,kind:'ccp',obj:c,reality:c.reality}}return{id:'RCF1',name:S.repoFacility64?.name||'Build 64 repo facility',kind:'facility',obj:S.repoFacility64,reality:l?.debtor||S.active}}
function downstreamFor(l){let first=lenderOf(l),other=(S.clearinghouses54||[]).find(c=>c.id!==first.id&&['operating','stressed','frozen'].includes(c.status));if(other)return{id:other.id,name:other.name||other.id,kind:'ccp',obj:other,reality:other.reality};return{id:'CTR1',name:S.collateralRegistry65.name,kind:'registry',obj:S.collateralRegistry65,reality:l.debtor}}
function liquidity(L){if(L.kind==='ccp')return Math.max(0,L.obj.liquidity||0);if(L.kind==='registry')return Math.max(0,L.obj.liquidity||0);return Math.max(0,L.obj.fallbackLiquidity||0)}
function changeLiquidity(L,d){if(L.kind==='ccp')L.obj.liquidity=Math.max(0,(L.obj.liquidity||0)+d);else if(L.kind==='registry')L.obj.liquidity=Math.max(0,(L.obj.liquidity||0)+d);else L.obj.fallbackLiquidity=Math.max(0,(L.obj.fallbackLiquidity||0)+d)}
function defaultFund(L){if(L.kind==='ccp')return Math.max(0,L.obj.defaultFund||0);if(L.kind==='registry')return Math.max(0,L.obj.defaultFund||0);return Math.max(0,L.obj.fallbackDefaultFund||0)}
function takeDefaultFund(L,n){let x=Math.min(n,defaultFund(L));if(L.kind==='ccp'){L.obj.defaultFund-=x;if(x>0)S.defaultFundUses54=(S.defaultFundUses54||0)+1}else if(L.kind==='registry')L.obj.defaultFund-=x;else L.obj.fallbackDefaultFund-=x;return x}
function takeCapital(L,n){if(n<=0)return 0;if(L.kind!=='ccp')return 0;let x=Math.min(n,Math.max(0,L.obj.capital||0));L.obj.capital-=x;if((L.obj.capital||0)<6)L.obj.status='stressed';return x}
function ratio(k,a){if(!a)return 0;let d=a.debtor,A=acct(d),res=cur(d)?.foreignReserves||0,debt=A?.externalDebt||0,r=k==='bond'?.74:({['holdout-restored']:.62,['accelerated-holdout']:.56,holdout:.48,['bound-holdout']:.42,exchanged:.69,participating:.66}[a.status]||.52);if(award(d)?.lien)r+=.05;r+=Math.min(.1,res/(debt+1)*.06);r-=Math.min(.12,(A?.arrears||0)/(debt+1)*.25);if(k==='bond'&&a.paymentInjunction63)r-=.18;if(k==='claim'&&a.ownerFund63==='FND1'&&['holdout-restored','accelerated-holdout','holdout'].includes(a.status))r+=.02;r-=Math.min(.28,S.repoShocks64?.[d]||0);if(a.titleFrozen65)r-=.12;return Math.max(.1,Math.min(.98,r))}
function baseHaircut(k,a){if(k==='bond')return a.paymentInjunction63?.45:.25;return({['holdout-restored']:.45,['accelerated-holdout']:.5,holdout:.52,['bound-holdout']:.58,exchanged:.3,participating:.35}[a.status]||.5)}
function collateralMark(k,a){let face=Math.max(0,a?.principal||0),r=ratio(k,a),h=Math.min(.82,baseHaircut(k,a)+.12);return{face,ratio:r,value:face*r,haircut:h,maxAdvance:face*r*(1-h)}}
function activeReuseForRepo(id){return S.rehypothecations65.find(x=>x.parentRepoId===id&&['active','recall-failed','title-dispute'].includes(x.status))||null}
function cert(assetKind,assetId,holder,role,priority,source){let c={id:'TCT'+(++S.titleCertificateSerial65),assetKind,assetId,holder,role,priority,source,status:'active',created:Date.now()};S.titleCertificates65.push(c);return c}
function closeCerts(source){for(const c of S.titleCertificates65.filter(x=>x.source===source&&x.status==='active')){c.status='released';c.released=Date.now()}}
function rehypothecate(parentRepoId,manual=true){ensure();let l=repo(parentRepoId);if(!l||l.status!=='active')return null;if(activeReuseForRepo(l.id)){if(manual)q('#msg').textContent=l.id+' collateral is already rehypothecated.';return activeReuseForRepo(l.id)}let a=asset(l.assetKind,l.assetId),f=fund(l.borrowerFundId);if(!a||!f||a.principal<=0)return null;let first=lenderOf(l),down=downstreamFor(l),m=collateralMark(l.assetKind,a),advance=Math.min(liquidity(down),m.maxAdvance*.85,l.principal*.9,6);if(advance<.25){if(manual)q('#msg').textContent='No downstream liquidity is available for collateral reuse.';return null}changeLiquidity(down,-advance);changeLiquidity(first,advance);let r={id:'RHY'+(++S.rehypSerial65),parentRepoId:l.id,assetKind:l.assetKind,assetId:l.assetId,debtor:l.debtor,originalFundId:l.borrowerFundId,originalFund:f.name,firstLenderId:first.id,firstLender:first.name,firstLenderKind:first.kind,downstreamLenderId:down.id,downstreamLender:down.name,downstreamKind:down.kind,principal:advance,feeRate:.012,openingMark:m.ratio,openingHaircut:m.haircut,status:'active',created:Date.now(),x:10+Math.random()*80,y:12+Math.random()*68};S.rehypothecations65.push(r);S.rehypAdvances65+=advance;l.rehypothecation65=r.id;a.rehypothecation65=r.id;cert(l.assetKind,l.assetId,f.name,'beneficial owner',3,r.id);cert(l.assetKind,l.assetId,first.name,'first repo lien',2,r.id);cert(l.assetKind,l.assetId,down.name,'rehypothecation lien',1,r.id);remember('REHYPOTHECATION '+r.id+': '+first.name+' borrowed '+advance.toFixed(2)+' from '+down.name+' against '+l.assetId+' that still belonged economically to '+f.name,realm(l.debtor));trust(l.debtor,'collateral-rehypothecated',r.id);if(typeof place==='function'){place('dream','lender borrowed against collateral it did not own',realm(l.debtor));place('cold','same asset on two balance sheets as available security',realm(l.debtor))}if(manual){q('#msg').textContent=r.id+' reused '+l.assetId+' for '+advance.toFixed(2)+' downstream funding.';renderAll();save65();openReuse(r)}return r}
function createDispute(r,kind,remaining,buyer=null){let d={id:'TDS'+(++S.titleDisputeSerial65),rehypId:r.id,parentRepoId:r.parentRepoId,assetKind:r.assetKind,assetId:r.assetId,debtor:r.debtor,kind,remaining,buyerFundId:buyer?.id||null,buyer:buyer?.name||null,status:'open',created:Date.now(),x:10+Math.random()*80,y:12+Math.random()*68};S.titleDisputes65.push(d);let a=asset(r.assetKind,r.assetId);if(a){a.titleFrozen65=d.id;let f=fund(a.ownerFund63),p=f?.positions?.find(x=>x.assetKind===r.assetKind&&x.assetId===r.assetId&&x.status==='owned');if(p)p.status=buyer?'encumbered-title':'title-frozen'}r.status='title-dispute';crisis(r.debtor,kind);return d}
function payDownstream(r,amount){let down=r.downstreamKind==='ccp'?{kind:'ccp',obj:ccpById(r.downstreamLenderId),id:r.downstreamLenderId,name:r.downstreamLender}:r.downstreamKind==='registry'?{kind:'registry',obj:S.collateralRegistry65,id:'CTR1',name:S.collateralRegistry65.name}:downstreamFor(repo(r.parentRepoId));if(!down.obj)return 0;changeLiquidity(down,amount);return amount}
function firstLenderForReuse(r){if(r.firstLenderKind==='ccp'){let c=ccpById(r.firstLenderId);if(c)return{id:c.id,name:r.firstLender,kind:'ccp',obj:c}}return lenderOf(repo(r.parentRepoId))}
function releaseReuse(r,status='recalled'){let a=asset(r.assetKind,r.assetId),l=repo(r.parentRepoId);if(a&&a.rehypothecation65===r.id)a.rehypothecation65=null;if(l&&l.rehypothecation65===r.id)l.rehypothecation65=null;if(a&&r.status!=='title-dispute')a.titleFrozen65=null;closeCerts(r.id);r.status=status;r.closed=Date.now()}
function recall(r,manual=true){if(!r||r.status!=='active')return false;let first=firstLenderForReuse(r),due=r.principal*(1+r.feeRate),cash=Math.min(due,liquidity(first));if(cash>0){changeLiquidity(first,-cash);payDownstream(r,cash)}let remain=due-cash,rec={id:'RCL'+(++S.recallSerial65),rehypId:r.id,parentRepoId:r.parentRepoId,assetId:r.assetId,debtor:r.debtor,due,paid:cash,status:remain<=.01?'recalled':'failed',created:Date.now(),x:10+Math.random()*80,y:12+Math.random()*68};S.collateralRecalls65.push(rec);if(remain<=.01){releaseReuse(r,'recalled');remember('COLLATERAL RECALL '+rec.id+': '+r.assetId+' returned clean after '+due.toFixed(2)+' downstream repayment',realm(r.debtor));if(manual){q('#msg').textContent=rec.id+' completed; '+r.assetId+' title is clean again.';renderAll();save65()}return true}r.recallRemaining65=remain;S.collateralRecallsFailed65++;createDispute(r,'collateral recall failed after original repo closed',remain);remember('FAILED COLLATERAL RECALL '+rec.id+': original repo ended but '+remain.toFixed(2)+' remained owed downstream against '+r.assetId,realm(r.debtor));if(manual){q('#msg').textContent=rec.id+' failed; the owner repaid its repo but '+r.assetId+' remains title-frozen.';renderAll();save65()}return false}
function cureDispute(d,manual=true){if(!d||d.status!=='open')return false;let r=S.rehypothecations65.find(x=>x.id===d.rehypId),first=firstLenderForReuse(r),need=d.remaining,df=takeDefaultFund(first,need),left=need-df,cap=takeCapital(first,left),paid=df+cap;if(paid>0)payDownstream(r,paid);d.remaining=Math.max(0,need-paid);if(d.remaining<=.01){d.status='resolved';d.resolved=Date.now();S.titleDisputesResolved65++;r.recallRemaining65=0;let a=asset(r.assetKind,r.assetId);if(a){a.titleFrozen65=null;let f=fund(a.ownerFund63),p=f?.positions?.find(x=>x.assetKind===r.assetKind&&x.assetId===r.assetId&&['title-frozen','encumbered-title'].includes(x.status));if(p)p.status='owned'}releaseReuse(r,'resolved-by-default-waterfall');remember('TITLE DISPUTE RESOLVED '+d.id+': '+first.name+' default resources bought back clean title to '+r.assetId,realm(r.debtor));if(manual){q('#msg').textContent=d.id+' resolved through lender default resources.';renderAll();save65();openDispute(d)}return true}crisis(r.debtor,'default resources could not recover rehypothecated collateral','SEV1');if(manual){q('#msg').textContent=d.id+' still has '+d.remaining.toFixed(2)+' unresolved senior title.';renderAll();save65();openDispute(d)}return false}
function processLiquidation(r,li){if(r.liquidationProcessed65)return false;let first=firstLenderForReuse(r),due=r.principal*(1+r.feeRate),cash=Math.min(due,liquidity(first));if(cash>0){changeLiquidity(first,-cash);payDownstream(r,cash);S.seniorSweeps65+=cash}let remain=due-cash,buyer=fund(li.buyerFundId);if(remain>0){let df=takeDefaultFund(first,remain);if(df>0){payDownstream(r,df);remain-=df}let cap=takeCapital(first,remain);if(cap>0){payDownstream(r,cap);remain-=cap}}if(remain>.01){createDispute(r,'senior rehypothecation lien survived the collateral fire sale',remain,buyer);let p=buyer?.positions?.find(x=>x.assetKind===r.assetKind&&x.assetId===r.assetId&&x.status==='owned');if(p)p.status='encumbered-title';remember('TITLE COLLISION: '+li.id+' sold '+r.assetId+' to '+(buyer?.name||li.buyer)+' but a '+remain.toFixed(2)+' senior lien survived the sale',realm(r.debtor))}else{releaseReuse(r,'paid-through-liquidation-waterfall');remember('SENIOR TITLE SWEEP: '+r.id+' took '+due.toFixed(2)+' from the first lender after '+li.id+' liquidated '+r.assetId,realm(r.debtor));if(typeof place==='function')place('cold','sale proceeds went to a creditor the buyer never negotiated with',realm(r.debtor))}r.liquidationProcessed65=li.id;return true}
function blockFrozenListings(){let changed=false;for(const d of S.titleDisputes65.filter(x=>x.status==='open'))for(const l of(S.claimListings63||[]).filter(x=>x.assetKind===d.assetKind&&x.assetId===d.assetId&&x.status==='open')){l.status='blocked-title-dispute';l.blockedBy65=d.id;changed=true;remember('LISTING BLOCKED '+l.id+': '+d.assetId+' could not be sold while '+d.id+' held senior title unresolved',realm(d.debtor))}return changed}
function reconcile(){if(!ensure())return false;let changed=blockFrozenListings();for(const r of S.rehypothecations65.filter(x=>x.status==='active')){let l=repo(r.parentRepoId);if(!l)continue;let li=[...(S.repoLiquidations64||[])].reverse().find(x=>x.loanId===l.id);if(li){if(processLiquidation(r,li))changed=true;continue}if(l.status!=='active'){recall(r,false);changed=true}}return changed}
function openDispute(d){let r=S.rehypothecations65.find(x=>x.id===d.rehypId),acts=[];if(d.status==='open')acts.push(['use lender default resources to recover title',()=>cureDispute(d,true)]);if(r)acts.push(['open '+r.id,()=>openReuse(r)]);acts.push(['close',closePanel]);panel(d.id+' · TITLE DISPUTE',d.status.toUpperCase(),d.assetId+' · '+d.kind+' · unresolved senior title '+d.remaining.toFixed(2)+(d.buyer?' · buyer '+d.buyer:''),acts)}
function openReuse(r){let l=repo(r.parentRepoId),a=asset(r.assetKind,r.assetId),d=S.titleDisputes65.find(x=>x.rehypId===r.id&&x.status==='open'),acts=[];if(r.status==='active'&&l?.status!=='active')acts.push(['recall collateral',()=>recall(r,true)]);if(d)acts.push(['open '+d.id,()=>openDispute(d)]);acts.push(['close',closePanel]);panel(r.id+' · REHYPOTHECATION',r.status.toUpperCase(),r.assetId+' · original owner '+r.originalFund+' · first lender '+r.firstLender+' · downstream '+r.downstreamLender+' · downstream principal '+r.principal.toFixed(2)+(a?.titleFrozen65?' · TITLE FROZEN':''),acts)}
function openRegistry(){if(!ensure())return;let acts=[];for(const l of(S.repoLoans64||[]).filter(x=>x.status==='active'&&!activeReuseForRepo(x.id)).slice(-8))acts.push(['reuse '+l.assetId+' from '+l.lender,()=>rehypothecate(l.id,true)]);for(const r of S.rehypothecations65.slice(-6))acts.push(['open '+r.id+' · '+r.assetId+' · '+r.status,()=>openReuse(r)]);for(const d of S.titleDisputes65.filter(x=>x.status==='open').slice(-5))acts.push(['open '+d.id+' · title dispute',()=>openDispute(d)]);acts.push(['close',closePanel]);panel(S.collateralRegistry65.name,'RECORDING · CTR1',S.rehypothecations65.filter(x=>x.status==='active').length+' active reuse chains · '+S.rehypAdvances65.toFixed(2)+' downstream advances · '+S.collateralRecallsFailed65+' failed recalls · '+S.titleDisputes65.filter(x=>x.status==='open').length+' open title disputes · '+S.seniorSweeps65.toFixed(2)+' senior sweeps',acts)}
function reuseInteresting(id=S.active,manual=true){let l=[...(S.repoLoans64||[])].reverse().find(x=>x.status==='active'&&x.debtor===id&&!activeReuseForRepo(x.id))||[...(S.repoLoans64||[])].reverse().find(x=>x.status==='active'&&!activeReuseForRepo(x.id));if(!l){if(manual)q('#msg').textContent='No active Build 64 repo is available for collateral reuse.';return null}return rehypothecate(l.id,manual)}
function render65(){if(!ensure())return;let layer=q('#titleLayer65');if(!layer){layer=document.createElement('div');layer.id='titleLayer65';document.body.appendChild(layer)}layer.innerHTML='';let e=document.createElement('i');e.className='titleRegistry65';e.dataset.label='TITLE';e.style.left='50%';e.style.top='90%';e.onclick=openRegistry;layer.appendChild(e);for(const r of S.rehypothecations65.filter(x=>['active','recall-failed','title-dispute'].includes(x.status)).slice(-8)){let x=document.createElement('i');x.className='rehyp65 '+r.status;x.dataset.label='x2';x.style.left=r.x+'%';x.style.top=r.y+'%';x.onclick=()=>openReuse(r);layer.appendChild(x)}for(const d of S.titleDisputes65.filter(x=>x.status==='open').slice(-6)){let x=document.createElement('i');x.className='titleDispute65';x.dataset.label='?';x.style.left=d.x+'%';x.style.top=d.y+'%';x.onclick=()=>openDispute(d);layer.appendChild(x)}let line=q('#titleline65');if(!line){line=document.createElement('div');line.id='titleline65';line.className='line';(q('#repoline64')||q('#claimmarketline')||q('#enforcement')).after(line)}line.textContent='collateral title: '+S.rehypothecations65.filter(x=>x.status==='active').length+' reused · '+S.rehypAdvances65.toFixed(1)+' downstream · '+S.collateralRecallsFailed65+' failed recalls · '+S.titleDisputes65.filter(x=>x.status==='open').length+' disputes · '+S.seniorSweeps65.toFixed(1)+' senior sweeps';let ctr=document.querySelector('#app .controls');if(ctr&&!q('#openTitleRegistry65')){let x=document.createElement('button');x.id='openTitleRegistry65';x.textContent='open title registry';x.onclick=openRegistry;ctr.prepend(x)}if(ctr&&!q('#reuseCollateral65')){let x=document.createElement('button');x.id='reuseCollateral65';x.textContent='rehypothecate collateral';x.onclick=()=>reuseInteresting(S.active,true);ctr.prepend(x)}}
renderAll=function(){R65();let changed=reconcile();render65();if(changed)save65()};let f=q('#forget');if(f)f.onclick=()=>{for(let i=2;i<=65;i++)localStorage.removeItem('nothing-state-v'+i);location.reload()};setInterval(()=>{reconcile();render65();save65()},2300);ensure();reconcile();renderAll();save65();
})();
