(()=>{
const B100=save,R100=renderAll,O=JSON.parse(localStorage.getItem('nothing-state-v100')||'null')||{},RECOVER100=!Array.isArray(O.conditionalityCaptures100),K=['conditionalityCaptureOffice100','conditionalityCaptures100','conditionalityCaptureSerial100','conditionalityCaptureMotions100','conditionalityCapturePassed100','conditionalityCaptureDeadlocked100','conditionalityCaptureRecoveries100','conditionalityCaptureCrises100','conditionalityCaptureKeys100','lastConditionalityCaptureTick100'];
for(const k of K)S[k]=O[k]??(k==='conditionalityCaptures100'?[]:/Serial|Motions|Passed|Deadlocked|Recoveries|Crises|Tick/.test(k)?0:/Keys/.test(k)?{}:/Office/.test(k)?null:[]);
function save100(){B100();let o={};for(const k of K)o[k]=S[k];localStorage.setItem('nothing-state-v100',JSON.stringify(o))}save=save100;
const q=s=>$(s),EPS=.0001,realm=id=>S.real[id],fund=()=>S.stabilizationFunds58?.[0],board=()=>S.fundBoards59?.[0],director=id=>(S.fundDirectors59||[]).find(d=>d.reality===id),other=id=>id==='A'?'B':'A',gar=id=>(S.governanceArbitrageRedemptions99||[]).find(a=>a.id===id),program=id=>(S.stabilizationPrograms58||[]).find(p=>p.id===id),motion=id=>(S.fundMotions59||[]).find(m=>m.id===id);
function trust(id,status,note){S.trustAudits=S.trustAudits||[];S.trustAuditSerial=S.trustAuditSerial||0;S.trustAudits.push({id:'TA'+(++S.trustAuditSerial),reality:id,status,created:Date.now(),note,x:10+Math.random()*80,y:12+Math.random()*68})}
function incident(id,title,sev='SEV2'){S.incidents=S.incidents||[];S.incidentSerial=S.incidentSerial||0;let ex=S.incidents.find(x=>x.reality===id&&x.title===title&&x.status==='open');if(ex)return ex;let i={id:'INC'+(++S.incidentSerial),reality:id,title,severity:sev,status:'open',started:Date.now(),owner:'conditionality capture register',x:10+Math.random()*80,y:12+Math.random()*68};S.incidents.push(i);return i}
function crisis(id,why,key,sev='SEV1'){let n=Date.now(),k=id+'|'+key;if(S.conditionalityCaptureKeys100[k]&&n-S.conditionalityCaptureKeys100[k]<14000)return;S.conditionalityCaptureKeys100[k]=n;S.conditionalityCaptureCrises100++;remember('CONDITIONALITY CAPTURE: '+why+' turned restitution-restored board control into borrower-recused rescue policy',realm(id));if(typeof place==='function'){place('cold','recovered creditor majority writing the other reality\'s rescue conditions',realm(id));place('dream','liquidity restitution returning as a policy veto over the borrower',realm(id))}incident(id,'conditionality capture: '+why,sev)}
function ensure(){if(!S.governanceArbitrageOffice99||!fund()||!board())return null;if(!S.conditionalityCaptureOffice100){S.conditionalityCaptureOffice100={id:'MCR1',name:'Interreality Majority Conditionality Capture Register',status:'watching-restored-majorities',created:Date.now(),x:50,y:98.35};remember('CONDITIONALITY CAPTURE MCR1: a Build 99 restored majority can sponsor a real borrower-recused Build 59 tightening motion when old surveillance supports it',realm('A'));remember('CONDITIONALITY CAPTURE MCR1: a Build 99 restored majority can sponsor a real borrower-recused Build 59 tightening motion when old surveillance supports it',realm('B'));trust('A','conditionality-capture-created','MCR1');trust('B','conditionality-capture-created','MCR1')}return S.conditionalityCaptureOffice100}
function successfulGARs(){return(S.governanceArbitrageRedemptions99||[]).filter(a=>a.crossedMajority99&&a.status==='majority-restored')}
function captureForGAR(id){return(S.conditionalityCaptures100||[]).find(c=>c.garId99===id)||null}
function targetProgram(id){return[...(S.stabilizationPrograms58||[])].filter(p=>p.reality===id&&['active','off-track','funding-shortfall'].includes(p.status)).sort((a,b)=>(b.created||0)-(a.created||0))[0]||null}
function latestSurveillance(id){return[...(S.surveillanceReports59||[])].filter(r=>r.reality===id).sort((a,b)=>(b.created||0)-(a.created||0))[0]||null}
function monetaryCondition(pid){return(S.stabilizationConditions58||[]).find(c=>c.programId===pid&&c.type==='monetary-tightening')||null}
function currentMajority(id){let b=board(),d=director(id);return!!(b&&d&&b.dominant===id&&(d.votes||0)+1e-7>=(b.majority||.6)*100)}
function openTightening(pid){return(S.fundMotions59||[]).find(m=>m.programId===pid&&m.type==='tighten-conditionality'&&['pending','deadlocked'].includes(m.status))||null}
function taxSnapshot(id){return(S.packageTreasuries47||[]).filter(t=>t.reality===id&&t.status!=='bankrupt').map(t=>({id:t.id,taxRate:t.taxRate||0}))}
function upsert(arr,id,snap){let i=arr.findIndex(x=>x.id===id);if(i>=0)arr[i]=snap;else arr.push(snap)}
function mark(c){let snap=JSON.parse(JSON.stringify(c)),a=gar(c.garId99),p=program(c.programId58),m=motion(c.motionId59),b=board();if(a){a.conditionalityCapture100=c.id;a.conditionalityCaptureMarker100=snap}if(p){p.conditionalityCaptureMarkers100=p.conditionalityCaptureMarkers100||[];upsert(p.conditionalityCaptureMarkers100,c.id,snap);p.conditionalityCaptureLatest100=c.id}if(m){m.conditionalityCapture100=c.id;m.conditionalityCaptureMarker100=snap}if(b){b.conditionalityCaptureMarkers100=b.conditionalityCaptureMarkers100||[];upsert(b.conditionalityCaptureMarkers100,c.id,snap)}}
function createCapture(a){let ex=captureForGAR(a.id);if(ex)return ex;let creditor=a.reality,target=other(creditor),c={id:'MCP'+(++S.conditionalityCaptureSerial100),garId99:a.id,positionId99:a.positionId99||null,creditorReality:creditor,targetReality:target,status:'observing-majority',programId58:null,surveillanceId59:null,surveillanceRisk100:null,motionId59:null,created:Date.now(),x:creditor==='A'?43:57,y:97.45};S.conditionalityCaptures100.push(c);remember('CONDITIONALITY CAPTURE '+c.id+': Reality '+creditor+' restored a board majority and acquired a potential borrower-recused policy path over Reality '+target,realm(target));trust(target,'conditionality-capture-position',c.id+' from '+a.id);mark(c);return c}
function createMotion(c,p,surv){let b=board();if(!b||!p||!surv)return null;S.fundMotions59=S.fundMotions59||[];S.fundMotionSerial59=S.fundMotionSerial59||0;let cond=monetaryCondition(p.id),m={id:'MOT'+(++S.fundMotionSerial59),boardId:b.id,type:'tighten-conditionality',label:'tighten program conditions',programId:p.id,targetReality:p.reality,status:'pending',threshold:b.majority,votes:{},yesWeight:0,noWeight:0,recused:[p.reality],created:Date.now(),decided:null,override:false,x:10+Math.random()*80,y:12+Math.random()*68,sourceBuild100:'conditionality-capture',sourceCapture100:c.id,sourceGAR99:c.garId99,creditorReality100:c.creditorReality};S.fundMotions59.push(m);c.motionId59=m.id;c.motionCreated100=Date.now();c.conditionBefore100=cond?.target??null;c.taxBefore100=taxSnapshot(p.reality);c.status='motion-pending';remember('CONDITIONALITY CAPTURE MOTION '+m.id+': restored-majority Reality '+c.creditorReality+' sponsored a borrower-recused tightening motion over Reality '+p.reality+' under old Build 59 governance',realm(p.reality));trust(p.reality,'conditionality-capture-motion-created',c.id+' '+m.id);crisis(p.reality,'Reality '+c.creditorReality+' converted '+c.garId99+' majority restoration into '+m.id+' over Reality '+p.reality,'motion-'+m.id);mark(c);return m}
function refresh(c){let a=gar(c.garId99);if(!a){c.status='orphaned-gar';mark(c);return c}let p=c.programId58?program(c.programId58):targetProgram(c.targetReality);if(p&&!c.programId58)c.programId58=p.id;let m=c.motionId59?motion(c.motionId59):null;if(m){let cond=monetaryCondition(m.programId);c.programId58=m.programId;c.motionStatus100=m.status;c.conditionAfter100=cond?.target??null;c.taxAfter100=taxSnapshot(c.targetReality);c.yesWeight100=m.yesWeight||0;c.noWeight100=m.noWeight||0;c.threshold100=(m.threshold||.6)*100;if(m.status==='passed'||m.status==='passed-override'){c.status='capture-passed';c.passedAt100=c.passedAt100||Date.now()}else if(m.status==='deadlocked')c.status='motion-deadlocked';else if(m.status==='rejected')c.status='motion-rejected';else c.status='motion-pending';mark(c);return c}if(!currentMajority(c.creditorReality)){c.status='majority-not-live';mark(c);return c}if(!p){c.status='awaiting-program';mark(c);return c}let existing=openTightening(p.id);if(existing){c.status='existing-tightening-open';c.programId58=p.id;mark(c);return c}let cond=monetaryCondition(p.id);if(!cond){c.status='missing-monetary-condition';mark(c);return c}let surv=latestSurveillance(p.reality);if(!surv){c.status='awaiting-surveillance';mark(c);return c}c.surveillanceId59=surv.id;c.surveillanceRisk100=surv.risk;if((surv.risk||0)<.45){c.status='risk-below-tightening';mark(c);return c}c.programId58=p.id;createMotion(c,p,surv);return c}
function reconstruct(){if(!RECOVER100)return false;let changed=false,seen=new Map(),b=board();for(const a of(S.governanceArbitrageRedemptions99||[]))if(a.conditionalityCaptureMarker100)seen.set(a.conditionalityCaptureMarker100.id,a.conditionalityCaptureMarker100);for(const p of(S.stabilizationPrograms58||[]))for(const m of(p.conditionalityCaptureMarkers100||[]))seen.set(m.id,m);for(const m of(S.fundMotions59||[]))if(m.conditionalityCaptureMarker100)seen.set(m.conditionalityCaptureMarker100.id,m.conditionalityCaptureMarker100);if(b)for(const m of(b.conditionalityCaptureMarkers100||[]))seen.set(m.id,m);for(const m of seen.values()){if(S.conditionalityCaptures100.some(c=>c.id===m.id))continue;let c=JSON.parse(JSON.stringify(m));c.recovered=true;S.conditionalityCaptures100.push(c);let n=Number(String(c.id).replace(/\D/g,''))||0;if(n>S.conditionalityCaptureSerial100)S.conditionalityCaptureSerial100=n;S.conditionalityCaptureRecoveries100++;changed=true}return changed}
function recompute(){S.conditionalityCaptureMotions100=(S.conditionalityCaptures100||[]).filter(c=>c.motionId59).length;S.conditionalityCapturePassed100=(S.conditionalityCaptures100||[]).filter(c=>c.status==='capture-passed').length;S.conditionalityCaptureDeadlocked100=(S.conditionalityCaptures100||[]).filter(c=>c.status==='motion-deadlocked').length}
function reconcile(){if(!ensure())return false;let changed=reconstruct();for(const a of successfulGARs())if(!captureForGAR(a.id)){createCapture(a);changed=true}for(const c of(S.conditionalityCaptures100||[])){let before=c.status+'|'+(c.motionId59||'');refresh(c);if(before!==c.status+'|'+(c.motionId59||''))changed=true}recompute();return changed}
function openCapture(c){refresh(c);let a=gar(c.garId99),p=program(c.programId58),m=motion(c.motionId59),acts=[];if(a)acts.push(['open governance arbitrage',()=>q('#openGovernanceArbitrage99')?.click()]);acts.push(['open fund board'+(m?' · vote '+m.id:''),()=>q('#openFundBoardButton')?.click()],['close',closePanel]);panel(c.id+' · CONDITIONALITY CAPTURE',c.status.toUpperCase(),'creditor Reality '+c.creditorReality+' → borrower Reality '+c.targetReality+' · source '+c.garId99+' · program '+(p?.id||'none')+' · surveillance '+(c.surveillanceId59||'none')+(c.surveillanceRisk100==null?'':' risk '+c.surveillanceRisk100.toFixed(2))+' · motion '+(m?.id||'none')+(m?' '+m.status:'')+' · condition '+(c.conditionBefore100==null?'—':(c.conditionBefore100*100).toFixed(1)+'%')+'→'+(c.conditionAfter100==null?'—':(c.conditionAfter100*100).toFixed(1)+'%')+(m?' · vote yes '+(m.yesWeight||0).toFixed(1)+' / no '+(m.noWeight||0).toFixed(1)+' / threshold '+((m.threshold||.6)*100).toFixed(0)+'%':''),acts)}
function openOffice(){if(!ensure())return;let acts=[];for(const c of S.conditionalityCaptures100.slice(-10))acts.push(['open '+c.id+' · '+c.status,()=>openCapture(c)]);acts.push(['open fund board',()=>q('#openFundBoardButton')?.click()],['close',closePanel]);panel(S.conditionalityCaptureOffice100.name,'BORROWER-RECUSED CAPTURE · MCR1',S.conditionalityCaptures100.length+' capture positions · '+S.conditionalityCaptureMotions100+' real Build 59 motions · '+S.conditionalityCapturePassed100+' passed · '+S.conditionalityCaptureDeadlocked100+' deadlocked · '+S.conditionalityCaptureCrises100+' crises',acts)}
function render100(){if(!ensure())return;let layer=q('#conditionalityCaptureLayer100');if(!layer){layer=document.createElement('div');layer.id='conditionalityCaptureLayer100';document.body.appendChild(layer)}layer.innerHTML='';let o=document.createElement('i');o.className='conditionalityCaptureOffice100';o.dataset.label='CAP';o.style.left='50%';o.style.top='98.35%';o.onclick=openOffice;layer.appendChild(o);for(const c of S.conditionalityCaptures100){let n=document.createElement('i');n.className='conditionalityCapture100 '+c.status;n.dataset.label=c.status==='motion-pending'?'V!':c.status==='capture-passed'?'✓':'C';n.style.left=c.x+'%';n.style.top=c.y+'%';n.onclick=()=>openCapture(c);layer.appendChild(n)}let line=q('#conditionalitycaptureline100');if(!line){line=document.createElement('div');line.id='conditionalitycaptureline100';line.className='line';(q('#governancearbitrageline99')||q('#fundgovernanceline')||q('#stabilizationline')||q('#enforcement')).after(line)}line.textContent='conditionality capture: '+S.conditionalityCaptures100.length+' positions · '+S.conditionalityCaptureMotions100+' Build 59 motions · '+S.conditionalityCapturePassed100+' passed · '+S.conditionalityCaptureDeadlocked100+' deadlocked';let ctr=document.querySelector('#app .controls');if(ctr&&!q('#openConditionalityCapture100')){let x=document.createElement('button');x.id='openConditionalityCapture100';x.textContent='open conditionality capture';x.onclick=openOffice;ctr.prepend(x)}}
renderAll=function(){R100();let changed=reconcile();render100();if(changed)save100()};let f=q('#forget');if(f)f.onclick=()=>{for(let i=2;i<=100;i++)localStorage.removeItem('nothing-state-v'+i);location.reload()};setInterval(()=>{reconcile();render100();save100()},2900);ensure();reconcile();renderAll();save100();
})();