(()=>{
const BS21=save,BR21=renderAll,O21=JSON.parse(localStorage.getItem('nothing-state-v21')||'null')||{},pick=a=>a&&a.length?a[Math.floor(Math.random()*a.length)]:null,cl=(v,a,b)=>Math.max(a,Math.min(b,v));
S.claims=O21.claims||[];S.claimSerial=O21.claimSerial||0;S.commonKnowledge=O21.commonKnowledge||0;S.falseConsensus=O21.falseConsensus||0;S.consensusRestorations=O21.consensusRestorations||0;S.consensusChallenges=O21.consensusChallenges||0;S.consensusPolls=O21.consensusPolls||0;S.consensusFractures=O21.consensusFractures||0;S.echoChambers=O21.echoChambers||0;
S.claims=S.claims.map((c,i)=>({id:c.id||'C'+(i+1),leakId:c.leakId||null,redactionId:c.redactionId||null,text:c.text||'A claim is circulating.',term:c.term||'unknown',support:c.support||1,oppose:c.oppose||1,reach:c.reach||1,status:c.status||'circulating',counterfeit:!!c.counterfeit,credibility:Number.isFinite(c.credibility)?c.credibility:.5,created:c.created||Date.now(),notes:c.notes||[],x:Number.isFinite(c.x)?c.x:10+Math.random()*80,y:Number.isFinite(c.y)?c.y:12+Math.random()*70}));
function save21(){BS21();localStorage.setItem('nothing-state-v21',JSON.stringify({claims:S.claims,claimSerial:S.claimSerial,commonKnowledge:S.commonKnowledge,falseConsensus:S.falseConsensus,consensusRestorations:S.consensusRestorations,consensusChallenges:S.consensusChallenges,consensusPolls:S.consensusPolls,consensusFractures:S.consensusFractures,echoChambers:S.echoChambers}))}save=save21;
const L=id=>S.leaks.find(l=>l.id===id),Z=id=>S.redactions.find(z=>z.id===id),pct=c=>c.support/Math.max(1,c.support+c.oppose),active=()=>S.claims.filter(c=>!['collapsed','forgotten'].includes(c.status));
function claim(l){if(!l||!['published','verified'].includes(l.status))return null;let c=S.claims.find(c=>c.leakId===l.id);if(c)return c;let base=1+Math.round((l.credibility||.5)*4)+(l.status==='verified'?2:0)+(l.shares||0);c={id:'C'+(++S.claimSerial),leakId:l.id,redactionId:l.redactionId,text:l.claim,term:l.term,support:base,oppose:1+Math.floor(Math.random()*3),reach:2+(l.shares||0),status:'circulating',counterfeit:!!l.counterfeit,credibility:l.credibility||.5,created:Date.now(),notes:['formed from '+l.id],x:10+Math.random()*80,y:12+Math.random()*70};S.claims.push(c);S.claims=S.claims.slice(-40);return c}
function restoreCommon(c){let z=Z(c.redactionId),hits=0;if(z){let r=S.transcripts.find(r=>r.id===z.transcriptId),e=r&&r.entries.find(e=>e.id===z.entryId);if(e){e.text='COMMON KNOWLEDGE: '+c.text;e.authority=Math.max(.94,e.authority||0);e.certified=true;hits++}z.authority=Math.max(.18,(z.authority||.7)-.14)}for(const r of[S.real.A,S.real.B]){remember('COMMON KNOWLEDGE: '+c.text,r);for(const p of r.places){if(p.redacted&&p.originalRedactedName&&(p.originalRedactedName||'').toLowerCase().includes((c.term||'').toLowerCase())){p.name=p.originalRedactedName;p.redacted=false;hits++}}}for(const w of S.witnesses){if((w.statement||'').includes('█')&&w.originalStatement&&(w.originalStatement||'').toLowerCase().includes((c.term||'').toLowerCase())){w.statement=w.originalStatement;w.credibility=cl((w.credibility||.5)+.05,.05,.99);hits++}}S.consensusRestorations+=hits}
function fracture(c){let rival=S.claims.find(x=>x!==c&&x.redactionId===c.redactionId&&x.status==='common'&&x.term!==c.term);if(!rival)return false;S.consensusFractures++;for(const [r,x] of [[S.real.A,c],[S.real.B,rival]]){remember('OBVIOUS TRUTH: '+x.text,r);r.timelineDrift+=3;r.disputes+=2}if(typeof place==='function'){place('dream','two truths from one black bar',S.real.A);place('dream','two truths from one black bar',S.real.B)}$('#msg').textContent='CONSENSUS FRACTURE: both realities agree that different answers are obvious.';return true}
function promote(c){if(!c||c.status==='common')return;if(c.reach<10||pct(c)<.68)return;c.status='common';S.commonKnowledge++;c.notes.push('became common knowledge at '+Math.round(pct(c)*100)+'%');let fractured=fracture(c);if(c.counterfeit){S.falseConsensus++;for(const r of[S.real.A,S.real.B]){remember('COMMON KNOWLEDGE (FALSE): '+c.text,r);r.timelineDrift+=3;r.disputes+=2}if(typeof place==='function')place('dream','everyone remembers the wrong thing',R())}else restoreCommon(c);if(/echo/i.test(c.term)){S.real.A.echoClaim+=8;S.real.B.echoClaim+=8}if(/original|larger/i.test(c.term)){S.real.A.thingClaim+=8;S.real.B.thingClaim+=8}if(/future|tomorrow|verdict/i.test(c.term)&&typeof future==='function'){for(const r of[S.real.A,S.real.B]){let f=future(undefined,r);f.text='everyone already knows: '+c.text;f.prob=.9;f.dueAt=Date.now()+6500}}if(!fractured)$('#msg').textContent=c.id+' became common knowledge. The record is adjusting to the crowd.'}
function observe(c,forced){if(!c||c.status==='collapsed')return;let l=L(c.leakId),momentum=cl((pct(c)-.5)*.9+c.reach/90,-.2,.45),trust=(l?.credibility||c.credibility||.5)-.5,believe=Math.random()<cl(.5+trust*.45+momentum,.12,.9);if(forced==='support')believe=true;if(forced==='oppose')believe=false;believe?c.support++:c.oppose++;c.reach++;if(c.reach>14&&pct(c)>.78&&Math.random()<.12){c.support+=2;S.echoChambers++;c.notes.push('repetition counted as corroboration')}if(c.reach>12&&pct(c)<.28){c.status='collapsed';c.notes.push('fell out of circulation')}promote(c)}
function endorse(c){observe(c,'support');c.support+=1;c.reach+=2;c.notes.push('user amplified claim');$('#msg').textContent='You repeated '+c.id+'. Repetition is now being counted as evidence.';openClaim(c);renderAll();save21()}
function challenge(c){S.consensusChallenges++;c.oppose+=2;c.reach+=2;c.notes.push('challenged');if(c.status==='common'&&Math.random()<.22){c.status='disputed';for(const r of[S.real.A,S.real.B]){r.timelineDrift++;r.disputes++};$('#msg').textContent='The obvious truth became discussable again.'}else $('#msg').textContent='The challenge increased the claim’s reach.';promote(c);openClaim(c);renderAll();save21()}
function poll(c){S.consensusPolls++;let term=(c.term||'').toLowerCase(),a=S.real.A.memories.some(m=>String(m).toLowerCase().includes(term)),b=S.real.B.memories.some(m=>String(m).toLowerCase().includes(term));if(a)c.support+=2;else c.oppose++;if(b)c.support+=2;else c.oppose++;c.reach+=4;c.notes.push('polled A/B: '+a+'/'+b);if(a!==b){S.consensusFractures++;S.real.A.timelineDrift++;S.real.B.timelineDrift++;$('#msg').textContent='The realities returned different poll answers.'}else $('#msg').textContent='Both realities returned the same answer. That does not prove it is true.';promote(c);openClaim(c);renderAll();save21()}
function openClaim(c){let l=L(c.leakId),buttons=[];if(c.status!=='collapsed'){buttons.push(['repeat it',()=>endorse(c)],['challenge it',()=>challenge(c)],['poll both realities',()=>poll(c)])}buttons.push(['close',closePanel]);panel(c.id+' · '+c.status+' claim',c.text,'belief '+Math.round(pct(c)*100)+'% · support '+c.support+' / oppose '+c.oppose+' · reach '+c.reach+' · source '+(l?l.source:'missing')+' · linked leak '+(l?l.id:'none'),buttons)}
function renderConsensus(){let layer=$('#consensusLayer');if(!layer){layer=document.createElement('div');layer.id='consensusLayer';document.body.appendChild(layer)}layer.innerHTML='';for(const c of S.claims.slice(-20)){let n=document.createElement('i');n.className='claim '+c.status+(c.counterfeit?' counterfeit':'');n.dataset.label=c.id+' '+Math.round(pct(c)*100)+'%';n.style.left=c.x+'%';n.style.top=c.y+'%';n.onclick=()=>openClaim(c);layer.appendChild(n)}let line=$('#consensusline');if(!line){line=document.createElement('div');line.id='consensusline';line.className='line';($('#leakline')||$('#redactionline')||$('#recordline')||$('#enforcement')).after(line)}line.textContent='consensus: '+S.claims.filter(c=>c.status==='common').length+' common truths · '+S.falseConsensus+' false · '+S.consensusChallenges+' challenges · '+S.consensusFractures+' fractures · '+S.echoChambers+' echo boosts';let ctr=document.querySelector('#app .controls');if(ctr&&!$('#consensusButton')){let b=document.createElement('button');b.id='consensusButton';b.textContent='open consensus';b.onclick=()=>{let c=[...active()].sort((a,b)=>b.reach-a.reach)[0];if(!c){let l=[...S.leaks].reverse().find(l=>['published','verified'].includes(l.status));c=l?claim(l):null}c?openClaim(c):$('#msg').textContent='Nobody agrees on enough to call it consensus.'};ctr.prepend(b)}}
renderAll=function(){BR21();for(const l of S.leaks.filter(l=>['published','verified'].includes(l.status)))claim(l);renderConsensus()};let f=$('#forget');if(f)f.onclick=()=>{for(let i=2;i<=21;i++)localStorage.removeItem('nothing-state-v'+i);location.reload()};
setInterval(()=>{for(const l of S.leaks.filter(l=>['published','verified'].includes(l.status)))claim(l);let c=pick(S.claims.filter(c=>['circulating','disputed'].includes(c.status)));if(c&&Math.random()<.34)observe(c);let common=pick(S.claims.filter(c=>c.status==='common'));if(common&&Math.random()<.025){common.support++;common.reach++;S.echoChambers++;for(const r of[S.real.A,S.real.B])if(Math.random()<.35)remember('EVERYONE KNOWS: '+common.text,r)}renderConsensus();save21()},1500);renderAll();save21();
})();
