(()=>{
const BS23=save,BR23=renderAll,O23=JSON.parse(localStorage.getItem('nothing-state-v23')||'null')||{},pick=a=>a&&a.length?a[Math.floor(Math.random()*a.length)]:null,cl=(v,a,b)=>Math.max(a,Math.min(b,v));
S.constitutions=O23.constitutions||[];S.constitutionSerial=O23.constitutionSerial||0;S.conventions=O23.conventions||0;S.ratifications=O23.ratifications||0;S.rejectedConstitutions=O23.rejectedConstitutions||0;S.amendments=O23.amendments||0;S.failedAmendments=O23.failedAmendments||0;S.constitutionalPartitions=O23.constitutionalPartitions||0;S.supremacyCrises=O23.supremacyCrises||0;S.lastSupremacyCrisis=O23.lastSupremacyCrisis||0;
S.constitutions=S.constitutions.map((c,i)=>({id:c.id||'K'+(i+1),reality:c.reality||'A',supremacy:c.supremacy||'people',status:c.status||'draft',support:c.support||0,oppose:c.oppose||0,created:c.created||Date.now(),voteAt:c.voteAt||Date.now()+12000,authority:Number.isFinite(c.authority)?c.authority:.6,articles:c.articles||[],amendments:c.amendments||0,pendingAmendment:c.pendingAmendment||null,enforced:c.enforced||0,x:Number.isFinite(c.x)?c.x:10+Math.random()*80,y:Number.isFinite(c.y)?c.y:12+Math.random()*70}));
function save23(){BS23();localStorage.setItem('nothing-state-v23',JSON.stringify({constitutions:S.constitutions,constitutionSerial:S.constitutionSerial,conventions:S.conventions,ratifications:S.ratifications,rejectedConstitutions:S.rejectedConstitutions,amendments:S.amendments,failedAmendments:S.failedAmendments,constitutionalPartitions:S.constitutionalPartitions,supremacyCrises:S.supremacyCrises,lastSupremacyCrisis:S.lastSupremacyCrisis}))}save=save23;
const active=()=>S.constitutions.filter(c=>c.status==='ratified'),forReality=id=>[...active()].reverse().find(c=>c.reality===id),mandates=id=>S.mandates.filter(m=>m.status==='active'&&(m.scope==='both'||m.scope===id));
function sourceScores(id){let r=S.real[id];return{archive:S.laws.filter(l=>l.status==='active').length*2+S.rulings.filter(q=>q.status==='binding').length+S.precedent/5,people:mandates(id).length*3+S.claims.filter(c=>c.status==='common').length*1.5,record:S.transcripts.filter(t=>t.status==='certified').length*2+S.redactions.filter(z=>z.status==='sealed').length+S.recordDivergence/5,memory:Math.min(12,(r.memories?.length||0)/2+(r.places?.length||0)/3)+Math.max(0,100-certainty(r))/15}}
function chooseSupremacy(id){let s=sourceScores(id),pairs=Object.entries(s).sort((a,b)=>b[1]-a[1]);if(Math.random()<.28)return pick(Object.keys(s));return pairs[0][0]}
function articles(src,id){let names={archive:'the archive and its enacted code',people:'the electorate and its ratified mandates',record:'the certified record',memory:'lived memory inside Reality '+id};return['ARTICLE I — '+names[src]+' is supreme.','ARTICLE II — no warrant may outrank the supreme authority.','ARTICLE III — contradictions must be preserved as evidence until resolved.','ARTICLE IV — Reality '+id+' retains the right to remember differently.']}
function convention(id=S.active){let existing=S.constitutions.find(c=>c.reality===id&&c.status==='draft');if(existing)return existing;S.conventions++;let sup=chooseSupremacy(id),c={id:'K'+(++S.constitutionSerial),reality:id,supremacy:sup,status:'draft',support:0,oppose:0,created:Date.now(),voteAt:Date.now()+9000+Math.random()*5000,authority:.55,articles:articles(sup,id),amendments:0,pendingAmendment:null,enforced:0,x:10+Math.random()*80,y:12+Math.random()*70};S.constitutions.push(c);S.constitutions=S.constitutions.slice(-24);$('#msg').textContent='Reality '+id+' convened a constitutional convention. The draft says '+sup+' is supreme.';renderConstitutions();save23();return c}
function ballot(c){let s=sourceScores(c.reality),total=Object.values(s).reduce((a,b)=>a+b,0)||1,base=.43+(s[c.supremacy]/total)*.42+(c.support-c.oppose)*.035;let old=forReality(c.reality);if(old)base-=.08;let turnout=cl(Math.round(44+Math.random()*45+S.legitimacyCrises*2),38,97),yes=0;base=cl(base,.15,.88);for(let i=0;i<turnout;i++)if(Math.random()<base)yes++;return{yes,no:turnout-yes,turnout,pct:yes/turnout}}
function ratify(c,forced=false){if(!c||c.status!=='draft')return;c.ballot=ballot(c);if(c.ballot.pct>.5){let old=forReality(c.reality);if(old)old.status='superseded';c.status='ratified';c.authority=cl(c.ballot.pct+.12,.55,.97);S.ratifications++;for(const r of[S.real[c.reality]]){remember('CONSTITUTION '+c.id+': '+c.supremacy+' is supreme',r);if(typeof place==='function')place('warm','constitutional text',r)}$('#msg').textContent='Reality '+c.reality+' ratified '+c.id+'. '+c.supremacy+' is now constitutionally supreme.';partitionCheck()}else{c.status='rejected';S.rejectedConstitutions++;S.real[c.reality].timelineDrift++;$('#msg').textContent='Reality '+c.reality+' rejected '+c.id+'. The legitimacy crisis remains unresolved.'}renderAll();save23()}
function campaign(c,yes){if(!c||c.status!=='draft')return;yes?c.support++:c.oppose++;c.voteAt+=600;$('#msg').textContent='You campaigned '+(yes?'for ':'against ')+c.id+'. The draft became harder to ignore.';openConstitution(c);save23()}
function applyConstitution(c){if(!c||c.status!=='ratified')return;let r=S.real[c.reality];if(c.supremacy==='people'){for(const m of mandates(c.reality)){m.authority=cl((m.authority||.6)+.004,.5,.99);if(m.kind==='identity'&&m.owner){if(m.owner==='echo')r.echoClaim+=.3;else r.thingClaim+=.3}}}else if(c.supremacy==='archive'){for(const l of S.laws.filter(l=>l.status==='active'))l.entrenched=Math.min(9,(l.entrenched||0)+.01);let il=S.laws.find(l=>l.status==='active'&&l.type==='identity');if(il?.data?.owner==='echo')r.echoClaim+=.25;else if(il?.data?.owner==='thing')r.thingClaim+=.25}else if(c.supremacy==='record'){for(const t of S.transcripts.filter(t=>t.status==='certified'))for(const e of t.entries||[])e.authority=cl((e.authority||.5)+.002,.2,.99);for(const z of S.redactions.filter(z=>z.status==='sealed'))z.authority=cl((z.authority||.7)+.002,.2,.99)}else{r.timelineDrift=Math.max(0,r.timelineDrift-.04);if(Math.random()<.015){let p=pick(r.places.filter(p=>p.redacted&&p.originalRedactedName));if(p){p.name=p.originalRedactedName;p.redacted=false;remember('memory restored something the record erased',r)}}}c.enforced++;if(c.reality===S.active)S.bailiffMood='obeying the constitution of Reality '+c.reality;supremacyConflict(c)}
function supremacyConflict(c){if(!c||c.status!=='ratified'||Date.now()-S.lastSupremacyCrisis<10000)return false;let conflict=null;if(c.supremacy==='people'&&S.laws.some(l=>l.status==='active')&&mandates(c.reality).some(m=>m.status==='active'))conflict='constitutional popular supremacy conflicts with archive code';if(c.supremacy==='archive'&&mandates(c.reality).some(m=>m.status==='active'&&m.authority>.7))conflict='archive supremacy conflicts with an entrenched popular mandate';if(c.supremacy==='record'&&S.claims.some(x=>x.status==='common'&&x.counterfeit))conflict='the constitution protects a record already contradicted by common knowledge';if(c.supremacy==='memory'&&S.transcripts.some(t=>t.status==='certified')&&S.recordDivergence>2)conflict='lived memory refuses the certified record';if(!conflict)return false;S.supremacyCrises++;S.lastSupremacyCrisis=Date.now();let r=S.real[c.reality];r.timelineDrift+=2;r.disputes++;remember('SUPREMACY CRISIS: '+conflict,r);if(typeof place==='function')place('cold','supremacy dispute',r);$('#msg').textContent='SUPREMACY CRISIS: '+conflict+'.';return true}
function partitionCheck(){let a=forReality('A'),b=forReality('B');if(!a||!b||a.supremacy===b.supremacy)return false;let key=a.id+'|'+b.id;if(S.lastPartitionKey===key)return true;S.lastPartitionKey=key;S.constitutionalPartitions++;for(const r of[S.real.A,S.real.B]){r.timelineDrift+=2;r.disputes++;remember('CONSTITUTIONAL PARTITION: A says '+a.supremacy+', B says '+b.supremacy,r);if(typeof place==='function')place('dream','supremacy border',r)}$('#msg').textContent='CONSTITUTIONAL PARTITION: A and B disagree about what law itself is.';return true}
function amend(c){if(!c||c.status!=='ratified'||c.pendingAmendment)return;let choices=['archive','people','record','memory'].filter(x=>x!==c.supremacy),next=pick(choices);c.pendingAmendment={supremacy:next,yes:0,no:0,voteAt:Date.now()+7000};$('#msg').textContent='Amendment proposed: Reality '+c.reality+' may replace '+c.supremacy+' supremacy with '+next+'.';openConstitution(c);save23()}
function voteAmendment(c,yes){if(!c?.pendingAmendment)return;yes?c.pendingAmendment.yes++:c.pendingAmendment.no++;resolveAmendment(c,true);openConstitution(c);save23()}
function resolveAmendment(c,forced=false){let a=c?.pendingAmendment;if(!a||(!forced&&Date.now()<a.voteAt))return;let base=.48+(a.yes-a.no)*.09+(Math.random()-.5)*.25;if(base>.5){c.supremacy=a.supremacy;c.articles=articles(c.supremacy,c.reality);c.authority=cl(c.authority+.03,.55,.99);c.amendments++;S.amendments++;remember('AMENDMENT: '+c.supremacy+' became supreme',S.real[c.reality]);$('#msg').textContent=c.id+' was amended. '+c.supremacy+' is now supreme.';partitionCheck()}else{S.failedAmendments++;c.authority=cl(c.authority+.02,.55,.99);$('#msg').textContent='The amendment failed. The existing constitution became more entrenched.'}c.pendingAmendment=null}
function openConstitution(c){let b=[];if(c.status==='draft')b.push(['campaign for ratification',()=>campaign(c,true)],['campaign against',()=>campaign(c,false)],['ratify now',()=>{ratify(c,true);closePanel()}]);if(c.status==='ratified'){if(!c.pendingAmendment)b.push(['propose amendment',()=>amend(c)]);else b.push(['vote yes on amendment',()=>voteAmendment(c,true)],['vote no on amendment',()=>voteAmendment(c,false)])}b.push(['close',closePanel]);let pending=c.pendingAmendment?' · amendment would make '+c.pendingAmendment.supremacy+' supreme':'';panel(c.id+' · '+c.status+' constitution','Reality '+c.reality+'\n\n'+c.articles.join('\n'),'supremacy '+c.supremacy+' · authority '+Math.round(c.authority*100)+'% · amendments '+c.amendments+' · enforced '+c.enforced+pending,b)}
function renderConstitutions(){let l=$('#constitutionLayer');if(!l){l=document.createElement('div');l.id='constitutionLayer';document.body.appendChild(l)}l.innerHTML='';for(const c of S.constitutions.slice(-16)){let n=document.createElement('i');n.className='constitution '+c.status+' '+c.supremacy;n.dataset.label=c.id+' '+c.reality+' '+c.supremacy;n.style.left=c.x+'%';n.style.top=c.y+'%';n.onclick=()=>openConstitution(c);l.appendChild(n)}let line=$('#constitutionline');if(!line){line=document.createElement('div');line.id='constitutionline';line.className='line';($('#civicsline')||$('#consensusline')||$('#enforcement')).after(line)}let a=forReality('A'),b=forReality('B');line.textContent='constitutions: A '+(a?a.supremacy:'none')+' · B '+(b?b.supremacy:'none')+' · '+S.ratifications+' ratified · '+S.amendments+' amendments · '+S.constitutionalPartitions+' partitions · '+S.supremacyCrises+' supremacy crises';let ctr=document.querySelector('#app .controls');if(ctr&&!$('#constitutionButton')){let x=document.createElement('button');x.id='constitutionButton';x.textContent='convene convention';x.onclick=()=>openConstitution(convention(S.active));ctr.prepend(x)}if(ctr&&!$('#charterButton')){let x=document.createElement('button');x.id='charterButton';x.textContent='open constitution';x.onclick=()=>{let c=forReality(S.active)||[...S.constitutions].reverse().find(c=>c.reality===S.active);c?openConstitution(c):openConstitution(convention(S.active))};ctr.prepend(x)}}
renderAll=function(){BR23();for(const c of active())applyConstitution(c);for(const c of S.constitutions)resolveAmendment(c,false);partitionCheck();renderConstitutions()};let f=$('#forget');if(f)f.onclick=()=>{for(let i=2;i<=23;i++)localStorage.removeItem('nothing-state-v'+i);location.reload()};
setInterval(()=>{for(const id of['A','B'])if(!forReality(id)&&!S.constitutions.some(c=>c.reality===id&&c.status==='draft')&&(S.legitimacyCrises>0||S.sovereigntySplits>0)&&Math.random()<.02)convention(id);for(const c of S.constitutions.filter(c=>c.status==='draft'&&Date.now()>=c.voteAt))ratify(c,false);for(const c of active()){if(Math.random()<.28)applyConstitution(c);if(!c.pendingAmendment&&c.authority>.72&&Math.random()<.004)amend(c)}for(const c of S.constitutions)resolveAmendment(c,false);renderConstitutions();save23()},1500);renderAll();save23();
})();
