(()=>{
const B84=save,R84=renderAll,O=JSON.parse(localStorage.getItem('nothing-state-v84')||'null')||{},RECOVER84=!Array.isArray(O.crossFacilityNets84),K=['collateralNettingOffice84','crossFacilityNets84','crossFacilityNettingSerial84','crossFacilityNettingAudits84','crossFacilityNettingSafe84','crossFacilityNettingShortfalls84','crossFacilityNettingShortfallAmount84','crossFacilityNettingCalls84','crossFacilityNettingCallAmount84','crossFacilityNettingCrises84','crossFacilityNettingKeys84','lastCrossFacilityNettingTick84'];
for(const k of K)S[k]=O[k]??(/Serial|Audits|Safe|Shortfalls|Amount|Calls|Crises|Tick/.test(k)?0:/Keys/.test(k)?{}:/Office/.test(k)?null:[]);
function save84(){B84();let o={};for(const k of K)o[k]=S[k];localStorage.setItem('nothing-state-v84',JSON.stringify(o))}save=save84;
const q=s=>$(s),realm=id=>S.real[id],position=id=>(S.sterilizationCarryPositions79||[]).find(x=>x.id===id),facility=id=>(S.liquidityFacilities55||[]).find(x=>x.id===id),cl=(v,a,b)=>Math.max(a,Math.min(b,v));
function trust(id,status,note){S.trustAudits=S.trustAudits||[];S.trustAuditSerial=S.trustAuditSerial||0;S.trustAudits.push({id:'TA'+(++S.trustAuditSerial),reality:id,status,created:Date.now(),note,x:10+Math.random()*80,y:12+Math.random()*68})}
function incident(id,title,sev='SEV1'){S.incidents=S.incidents||[];S.incidentSerial=S.incidentSerial||0;let ex=S.incidents.find(x=>x.reality===id&&x.title===title&&x.status==='open');if(ex)return ex;let i={id:'INC'+(++S.incidentSerial),reality:id,title,severity:sev,status:'open',started:Date.now(),owner:'cross-facility collateral netting office',x:10+Math.random()*80,y:12+Math.random()*68};S.incidents.push(i);return i}
function crisis(id,why,sev='SEV1'){let n=Date.now(),k=id+'|'+why;if(S.crossFacilityNettingKeys84[k]&&n-S.crossFacilityNettingKeys84[k]<14000)return;S.crossFacilityNettingKeys84[k]=n;S.crossFacilityNettingCrises84++;remember('COLLATERAL NETTING CRISIS: '+why+' revealed several individually safe public loans sharing one insufficient collateral pool',realm(id));if(typeof place==='function'){place('cold','each central-bank loan looked safe until the collateral was counted only once',realm(id));place('dream','refinancing fragments discovering they all owned the same borrowing base',realm(id))}incident(id,'cross-facility collateral netting crisis: '+why,sev)}
function ensure(){if(!S.fundingNovationOffice83||!S.marginRefinanceOffice82)return null;if(!S.collateralNettingOffice84){S.collateralNettingOffice84={id:'CFN1',name:'Interreality Cross-Facility Collateral Netting Office',status:'netting',created:Date.now(),x:50,y:88};remember('COLLATERAL NETTING CFN1: funding novation acquired a stack-wide borrowing base',realm('A'));remember('COLLATERAL NETTING CFN1: funding novation acquired a stack-wide borrowing base',realm('B'));trust('A','cross-facility-collateral-netting-created','CFN1');trust('B','cross-facility-collateral-netting-created','CFN1')}return S.collateralNettingOffice84}
function grade(type,id,def='BBB'){let rs=(S.creditRatings52||[]).filter(r=>r.subjectType===type&&r.subjectId===id).sort((a,b)=>(b.published||0)-(a.published||0));return rs[0]?.grade||def}
function haircut(g){return{AAA:.04,AA:.07,A:.1,BBB:.18,BB:.32,B:.48,CCC:.68,D:.9}[g]??.25}
function borrower(f){if(!f)return null;if(f.borrowerType==='dealer'){let o=(S.derivativeDealers53||[]).find(x=>x.id===f.borrowerId);return o?{obj:o,type:'dealer',id:f.borrowerId,name:o.name||f.borrowerId}:null}if(f.borrowerType==='ccp'){let o=(S.clearinghouses54||[]).find(x=>x.id===f.borrowerId);return o?{obj:o,type:'ccp',id:f.borrowerId,name:o.name||f.borrowerId}:null}if(f.borrowerType==='insurer'){let o=(S.insurers51||[]).find(x=>x.id===f.borrowerId);return o?{obj:o,type:'insurer',id:f.borrowerId,name:o.name||f.borrowerId}:null}if(f.borrowerType==='treasury'){let o=(S.packageTreasuries47||[]).find(x=>x.namespaceId===f.borrowerId),n=(S.namespaces46||[]).find(x=>x.id===f.borrowerId);return o?{obj:o,type:'treasury',id:f.borrowerId,name:(n?.name||f.borrowerId)+' package treasury'}:null}return null}
function collateral(b){let g=grade(b.type,b.id,b.type==='ccp'?'A':'BBB'),face=0;if(b.type==='dealer')face=Math.max(2,(b.obj.collateral||0)+(b.obj.capital||0)*.35);else if(b.type==='ccp')face=Math.max(4,(b.obj.defaultFund||0)+(b.obj.guaranteeFund||0));else if(b.type==='insurer'){let prem=(S.riskPolicies51||[]).filter(p=>p.insurerId===b.id&&p.status==='active').reduce((n,p)=>n+(p.premium||0),0);face=Math.max(4,prem+(b.obj.reserves||0))}else face=Math.max(3,(b.obj.balance||0)+5);let h=haircut(g);return{grade:g,face,haircut:h,lendable:face*(1-h),type:b.type==='dealer'?'derivative collateral and margin receivables':b.type==='ccp'?'settlement receivables and default-fund claim':b.type==='insurer'?'premium receivables':'future dependency-tax receivables'}}
function liveCarry(p){return p&&['open','rollover-risk','open-permanent-money'].includes(p.status)}
function chainFacilities(p){let seen=new Set(),xs=[];for(const f of(S.liquidityFacilities55||[])){if(f.status!=='active'||(f.principal||0)<=.01)continue;let linked=f.id===p.facilityId55||f.id===p.fundingOriginFacility83||f.carryPosition79===p.id||f.carryPosition79Novated83===p.id||(f.marginRefinance82&&f.positionId79===p.id);if(!linked||seen.has(f.id))continue;seen.add(f.id);xs.push(f)}return xs.sort((a,b)=>(a.issued||0)-(b.issued||0)||String(a.id).localeCompare(String(b.id)))}
function unresolvedCoverage(f){return(S.monetaryCollateralCalls55||[]).filter(c=>c.facilityId===f.id&&['open','failed','forborne'].includes(c.status)).reduce((n,c)=>n+Math.max(0,(c.amount||0)-(c.paid||0)),0)}
function signature(p,fs,col){return p.id+'|'+col.grade+'|'+col.lendable.toFixed(6)+'|'+fs.map(f=>f.id+':'+(f.principal||0).toFixed(6)).join(',')}
function issueCall(p,f,r,a,need){let amt=Math.round(Math.max(0,need)*10000)/10000;if(amt<=.0001)return null;S.monetaryCollateralCalls55=S.monetaryCollateralCalls55||[];S.monetaryCollateralCallSerial55=S.monetaryCollateralCallSerial55||0;let c={id:'CBMC'+(++S.monetaryCollateralCallSerial55),facilityId:f.id,authorityId:f.authorityId,reality:f.reality,borrowerType:f.borrowerType,borrowerId:f.borrowerId,borrower:f.borrower,amount:amt,status:'open',reason:'cross-facility collateral netting: aggregate carry-funding debt exceeds the collateral pool counted once',issued:Date.now(),paid:0,x:10+Math.random()*80,y:12+Math.random()*68,crossFacilityNetting84:true,nettingId84:r.id,positionId79:p.id,aggregateExposure84:r.exposure,aggregateLendable84:r.lendable,allocatedCollateral84:a.allocated,allocatedShortfall84:a.shortfall};S.monetaryCollateralCalls55.push(c);S.monetaryCollateralCallsIssued55=(S.monetaryCollateralCallsIssued55||0)+1;S.crossFacilityNettingCalls84++;S.crossFacilityNettingCallAmount84+=amt;return c}
function marker(r,p,fs){let snap=JSON.parse(JSON.stringify(r));p.crossFacilityNettingSignature84=r.signature84;p.crossFacilityNettingLatest84=r.id;for(const f of fs){f.crossFacilityNettingMarkers84=f.crossFacilityNettingMarkers84||[];f.crossFacilityNettingMarkers84.push(snap);f.crossFacilityNettingId84=r.id}}
function audit(p,manual=false){if(!liveCarry(p))return null;let fs=chainFacilities(p);if(fs.length<2)return null;let b=borrower(fs[0]);if(!b)return null;let col=collateral(b),sig=signature(p,fs,col);if(p.crossFacilityNettingSignature84===sig)return null;let exposure=fs.reduce((n,f)=>n+Math.max(0,f.principal||0),0),lendable=Math.max(0,col.lendable),shortfall=Math.max(0,exposure-lendable),r={id:'CFN'+(++S.crossFacilityNettingSerial84),positionId79:p.id,reality:p.reality,borrower:p.borrower||b.name,borrowerType:fs[0].borrowerType,borrowerId:fs[0].borrowerId,status:shortfall>.01?'shortfall-open':'safe',grade:col.grade,collateralFace:col.face,haircut:col.haircut,lendable,exposure,shortfall,facilityCount:fs.length,allocations:[],aggregateExistingCoverage:0,residualUncovered84:0,signature84:sig,callsIssued84:0,callAmount84:0,created:Date.now(),x:10+Math.random()*80,y:12+Math.random()*68};
let remainingAlloc=Math.min(exposure,lendable),remainingPrincipal=exposure;
for(let i=0;i<fs.length;i++){let f=fs[i],principal=Math.max(0,f.principal||0),allocated=i===fs.length-1?Math.min(principal,remainingAlloc):Math.min(principal,remainingPrincipal>0?remainingAlloc*(principal/remainingPrincipal):0),sh=Math.max(0,principal-allocated),covered=unresolvedCoverage(f),a={facilityId55:f.id,principal,allocated,shortfall:sh,existingCoverage:covered,newCallAmount:0,newCallId55:null};r.aggregateExistingCoverage+=covered;f.crossFacilityAllocatedCollateral84=allocated;f.crossFacilityShortfall84=sh;f.crossFacilityExposure84=exposure;f.crossFacilityLendable84=lendable;f.aggregateUndercollateralized84=sh>.01;remainingAlloc=Math.max(0,remainingAlloc-allocated);remainingPrincipal=Math.max(0,remainingPrincipal-principal);r.allocations.push(a)}
let residual=Math.max(0,shortfall-r.aggregateExistingCoverage);r.residualUncovered84=residual;
for(const a of r.allocations){if(residual<=.0001)break;let localGap=Math.max(0,a.shortfall-a.existingCoverage),need=Math.min(residual,localGap);if(need<=.0001)continue;let f=facility(a.facilityId55),c=f?issueCall(p,f,r,a,need):null;if(c){a.newCallAmount=c.amount;a.newCallId55=c.id;r.callsIssued84++;r.callAmount84+=c.amount;residual=Math.max(0,residual-c.amount)}}
r.residualUncoveredAfterCalls84=residual;
S.crossFacilityNets84.push(r);S.crossFacilityNettingAudits84++;if(shortfall>.01){S.crossFacilityNettingShortfalls84++;S.crossFacilityNettingShortfallAmount84+=shortfall;remember('CROSS-FACILITY SHORTFALL '+r.id+': '+r.borrower+' owes '+exposure.toFixed(2)+' across '+fs.length+' public facilities against '+lendable.toFixed(2)+' current collateral counted once',realm(p.reality));trust(p.reality,'cross-facility-collateral-shortfall',r.id+' '+shortfall.toFixed(2));crisis(p.reality,'aggregate public carry funding exceeded current lendable collateral by '+shortfall.toFixed(2),'SEV1')}else{S.crossFacilityNettingSafe84++;remember('CROSS-FACILITY NETTING '+r.id+': '+r.borrower+' stack '+exposure.toFixed(2)+' remained inside '+lendable.toFixed(2)+' current lendable collateral',realm(p.reality));trust(p.reality,'cross-facility-collateral-safe',r.id+' '+exposure.toFixed(2))}
marker(r,p,fs);if(manual){q('#msg').textContent=r.id+' '+r.status.toUpperCase()+' · exposure '+exposure.toFixed(2)+' / lendable '+lendable.toFixed(2)+'.';renderAll();save84();openNet(r)}return r}
function reconstruct(){if(!RECOVER84)return false;let changed=false,seen=new Set();for(const f of(S.liquidityFacilities55||[])){for(const m of(f.crossFacilityNettingMarkers84||[])){if(seen.has(m.id)||(S.crossFacilityNets84||[]).some(x=>x.id===m.id))continue;seen.add(m.id);let r=JSON.parse(JSON.stringify(m));r.recovered=true;S.crossFacilityNets84.push(r);S.crossFacilityNettingAudits84++;if(r.status==='safe')S.crossFacilityNettingSafe84++;else{S.crossFacilityNettingShortfalls84++;S.crossFacilityNettingShortfallAmount84+=r.shortfall||0}S.crossFacilityNettingCalls84+=r.callsIssued84||0;S.crossFacilityNettingCallAmount84+=r.callAmount84||0;let n=Number(String(r.id).replace(/\D/g,''))||0;if(n>S.crossFacilityNettingSerial84)S.crossFacilityNettingSerial84=n;let p=position(r.positionId79);if(p){p.crossFacilityNettingSignature84=r.signature84;p.crossFacilityNettingLatest84=r.id}changed=true}}return changed}
function reconcile(){if(!ensure())return false;let changed=reconstruct();for(const p of(S.sterilizationCarryPositions79||[]).filter(liveCarry)){let r=audit(p,false);if(r)changed=true}return changed}
function openNet(r){let acts=[];for(const a of r.allocations||[]){let f=facility(a.facilityId55);if(f)acts.push([a.facilityId55+' · short '+a.shortfall.toFixed(2)+(a.newCallId55?' · '+a.newCallId55:''),()=>panel(a.facilityId55+' · NETTED COLLATERAL',f.status.toUpperCase(),'principal '+a.principal.toFixed(2)+' · allocated collateral '+a.allocated.toFixed(2)+' · allocated shortfall '+a.shortfall.toFixed(2)+' · prior unresolved call coverage '+a.existingCoverage.toFixed(2)+' · new call '+a.newCallAmount.toFixed(2),[['close',closePanel]])])}acts.push(['close',closePanel]);panel(r.id+' · CROSS-FACILITY COLLATERAL NETTING',r.status.toUpperCase(),r.borrower+' · '+r.facilityCount+' active facilities · exposure '+r.exposure.toFixed(2)+' · current '+r.grade+' lendable collateral '+r.lendable.toFixed(2)+' · aggregate shortfall '+r.shortfall.toFixed(2)+' · '+r.callsIssued84+' new Build55 calls / '+r.callAmount84.toFixed(2),acts)}
function openOffice(){if(!ensure())return;let acts=[];for(const p of(S.sterilizationCarryPositions79||[]).filter(liveCarry)){let fs=chainFacilities(p);if(fs.length>=2)acts.push(['audit '+p.id+' · '+fs.length+' facilities',()=>{p.crossFacilityNettingSignature84=null;audit(p,true)}])}for(const r of S.crossFacilityNets84.slice(-8))acts.push(['open '+r.id+' · '+r.status,()=>openNet(r)]);acts.push(['close',closePanel]);panel(S.collateralNettingOffice84.name,'NETTING · CFN1',S.crossFacilityNettingAudits84+' audits · '+S.crossFacilityNettingShortfalls84+' shortfalls / '+S.crossFacilityNettingShortfallAmount84.toFixed(2)+' · '+S.crossFacilityNettingCalls84+' Build55 calls / '+S.crossFacilityNettingCallAmount84.toFixed(2),acts)}
function auditInteresting(){let p=(S.sterilizationCarryPositions79||[]).filter(liveCarry).find(p=>chainFacilities(p).length>=2);if(!p){q('#msg').textContent='No live carry currently has multiple active public funding facilities to net.';return null}p.crossFacilityNettingSignature84=null;return audit(p,true)}
function render84(){if(!ensure())return;let layer=q('#crossFacilityNettingLayer84');if(!layer){layer=document.createElement('div');layer.id='crossFacilityNettingLayer84';document.body.appendChild(layer)}layer.innerHTML='';let o=document.createElement('i');o.className='crossFacilityNettingOffice84';o.dataset.label='ΣC';o.style.left='50%';o.style.top='88%';o.onclick=openOffice;layer.appendChild(o);for(const r of S.crossFacilityNets84.filter(x=>x.status!=='safe').slice(-8)){let e=document.createElement('i');e.className='crossFacilityNetting84 '+r.status;e.dataset.label='Σ!';e.style.left=r.x+'%';e.style.top=r.y+'%';e.onclick=()=>openNet(r);layer.appendChild(e)}let line=q('#crossfacilitynettingline84');if(!line){line=document.createElement('div');line.id='crossfacilitynettingline84';line.className='line';(q('#fundingnovationline83')||q('#marginrefinanceline82')||q('#monetaryline')||q('#enforcement')).after(line)}line.textContent='collateral netting: '+S.crossFacilityNettingAudits84+' audits · '+S.crossFacilityNettingShortfallAmount84.toFixed(1)+' aggregate shortfall · '+S.crossFacilityNettingCalls84+' Build55 calls';let ctr=document.querySelector('#app .controls');if(ctr&&!q('#openCrossFacilityNetting84')){let x=document.createElement('button');x.id='openCrossFacilityNetting84';x.textContent='open collateral netting';x.onclick=openOffice;ctr.prepend(x)}if(ctr&&!q('#auditCrossFacilityNetting84')){let x=document.createElement('button');x.id='auditCrossFacilityNetting84';x.textContent='audit funding-chain collateral';x.onclick=auditInteresting;ctr.prepend(x)}}
renderAll=function(){R84();let changed=reconcile();render84();if(changed)save84()};let f=q('#forget');if(f)f.onclick=()=>{for(let i=2;i<=84;i++)localStorage.removeItem('nothing-state-v'+i);location.reload()};setInterval(()=>{reconcile();render84();save84()},2300);ensure();reconcile();renderAll();save84();
})();