(()=>{
const B88=save,R88=renderAll,O=JSON.parse(localStorage.getItem('nothing-state-v88')||'null')||{},RECOVER88=!Array.isArray(O.interestDustWriteoffs88),K=['deMinimisInterestOffice88','interestDustWriteoffs88','interestDustSerial88','interestDustFacilityWriteoffs88','interestDustClaimWriteoffs88','interestDustAmount88','interestDustCasesFinalized88','interestDustBlocked88','interestDustCrises88','interestDustKeys88','lastInterestDustTick88'];
for(const k of K)S[k]=O[k]??(k==='interestDustWriteoffs88'?[]:/Serial|FacilityWriteoffs|ClaimWriteoffs|Amount|Finalized|Blocked|Crises|Tick/.test(k)?0:/Keys/.test(k)?{}:/Office/.test(k)?null:[]);
function save88(){B88();let o={};for(const k of K)o[k]=S[k];localStorage.setItem('nothing-state-v88',JSON.stringify(o))}save=save88;
const q=s=>$(s),realm=id=>S.real[id],facility=id=>(S.liquidityFacilities55||[]).find(x=>x.id===id),authority=id=>(S.monetaryAuthorities55||[]).find(x=>x.id===id),claim=id=>(S.residualInterestClaims87||[]).find(x=>x.id===id);
function trust(id,status,note){S.trustAudits=S.trustAudits||[];S.trustAuditSerial=S.trustAuditSerial||0;S.trustAudits.push({id:'TA'+(++S.trustAuditSerial),reality:id,status,created:Date.now(),note,x:10+Math.random()*80,y:12+Math.random()*68})}
function incident(id,title,sev='SEV2'){S.incidents=S.incidents||[];S.incidentSerial=S.incidentSerial||0;let ex=S.incidents.find(x=>x.reality===id&&x.title===title&&x.status==='open');if(ex)return ex;let i={id:'INC'+(++S.incidentSerial),reality:id,title,severity:sev,status:'open',started:Date.now(),owner:'de minimis interest finality office',x:10+Math.random()*80,y:12+Math.random()*68};S.incidents.push(i);return i}
function crisis(id,why){let n=Date.now(),k=id+'|'+why;if(S.interestDustKeys88[k]&&n-S.interestDustKeys88[k]<14000)return;S.interestDustKeys88[k]=n;S.interestDustCrises88++;remember('DE MINIMIS INTEREST FINALITY: '+why+' was formally written off instead of surviving as accounting dust',realm(id));if(typeof place==='function'){place('cold','a central bank needing legal finality for less than one hundredth of a credit',realm(id));place('dream','an interest ghost small enough to disappear only after paperwork',realm(id))}incident(id,'de minimis interest finality: '+why)}
function ensure(){if(!S.residualInterestOffice87||!S.postDefaultCashSweepOffice86)return null;if(!S.deMinimisInterestOffice88){S.deMinimisInterestOffice88={id:'DMO1',name:'Interreality De Minimis Interest Finality Office',status:'rounding',created:Date.now(),x:50,y:80};remember('DE MINIMIS FINALITY DMO1: residual interest acquired explicit sub-cent write-offs',realm('A'));remember('DE MINIMIS FINALITY DMO1: residual interest acquired explicit sub-cent write-offs',realm('B'));trust('A','de-minimis-interest-finality-created','DMO1');trust('B','de-minimis-interest-finality-created','DMO1')}return S.deMinimisInterestOffice88}
function linkedCaseForFacility(f){return(S.fundingCrossDefaults85||[]).find(c=>c.status==='liquidated-deficiency'&&(c.facilityIds85||[]).includes(f.id))||null}
function upsert(arr,id,snap){let i=arr.findIndex(x=>x.id===id);if(i>=0)arr[i]=snap;else arr.push(snap)}
function markWriteoff(w,c,f,r){let snap=JSON.parse(JSON.stringify(w));c.interestDustMarkers88=c.interestDustMarkers88||[];upsert(c.interestDustMarkers88,w.id,snap);c.interestDustLatest88=w.id;if(f){f.interestDustMarkers88=f.interestDustMarkers88||[];upsert(f.interestDustMarkers88,w.id,snap);f.interestDustLatest88=w.id}if(r){r.interestDustWriteoff88=w.id;r.interestDustWrittenOff88=(r.interestDustWrittenOff88||0)+w.amount88}}
function update87ClaimMarkers(r,c,f){let snap=JSON.parse(JSON.stringify(r));c.residualInterestMarkers87=c.residualInterestMarkers87||[];upsert(c.residualInterestMarkers87,r.id,snap);if(f){f.residualInterestMarkers87=f.residualInterestMarkers87||[];upsert(f.residualInterestMarkers87,r.id,snap)}}
function current87Outstanding(c){return(S.residualInterestClaims87||[]).filter(r=>r.crossDefaultId85===c.id).reduce((n,r)=>n+Math.max(0,r.outstanding87||0),0)}
function syncCase(c){let old=c.residualInterestCured87,amt=current87Outstanding(c);c.residualInterestOutstanding87=amt;if(amt<=.0001){c.residualInterestCured87=true;c.residualInterestCuredAt87=c.residualInterestCuredAt87||Date.now();if(!old)S.interestDustCasesFinalized88++}return amt}
function writeFacilityDust(f,manual=false){if(!f||!['active','monetized'].includes(f.status)||(f.principal||0)>.01||(f.interestAccrued||0)<=0||(f.interestAccrued||0)>.01||f.residualInterestClaim87||f.interestDustWriteoff88)return null;let c=linkedCaseForFacility(f);if(!c)return null;let a=authority(f.authorityId);if(!a){S.interestDustBlocked88++;crisis(c.reality,'facility '+f.id+' had tiny residual interest but its authority record was missing');return null}let amt=Math.max(0,f.interestAccrued||0),w={id:'RIW'+(++S.interestDustSerial88),kind88:'facility-interest-dust',crossDefaultId85:c.id,facilityId55:f.id,authorityId:f.authorityId,reality:f.reality,borrowerType:f.borrowerType,borrowerId:f.borrowerId,borrower:f.borrower,amount88:amt,status:'written-off',created:Date.now(),x:10+Math.random()*80,y:12+Math.random()*68};f.interestAccrued=0;f.principal=0;f.status='repaid';f.repaid=Date.now();f.repaidByDustWriteoff88=true;f.interestDustWriteoff88=w.id;f.interestDustWrittenOff88=amt;f.crossDefaultDeficiency85=0;f.cashSweepRemaining86=0;a.residualInterestForegone88=(a.residualInterestForegone88||0)+amt;S.interestDustWriteoffs88.push(w);S.interestDustFacilityWriteoffs88++;S.interestDustAmount88+=amt;markWriteoff(w,c,f,null);let fs=(c.facilityIds85||[]).map(facility).filter(Boolean),oldDebt=fs.reduce((n,x)=>n+Math.max(0,x.principal||0)+Math.max(0,x.interestAccrued||0),0);if(fs.length&&oldDebt<=.01){c.cashSweepOutstanding86=0;c.cashSweepCured86=true;c.cashSweepCuredAt86=c.cashSweepCuredAt86||Date.now()}syncCase(c);remember('INTEREST DUST '+w.id+': '+amt.toFixed(4)+' on '+f.id+' was formally written off and the monetary facility closed',realm(c.reality));trust(c.reality,'de-minimis-facility-interest-written-off',w.id+' '+amt.toFixed(4));if(manual){q('#msg').textContent=w.id+' wrote off '+amt.toFixed(4)+' facility interest dust.';renderAll();save88();openWriteoff(w)}return w}
function writeClaimDust(r,manual=false){if(!r||!(r.outstanding87>0&&r.outstanding87<=.01)||r.interestDustWriteoff88)return null;let c=(S.fundingCrossDefaults85||[]).find(x=>x.id===r.crossDefaultId85);if(!c)return null;let f=facility(r.facilityId55),a=authority(r.authorityId);if(!a){S.interestDustBlocked88++;crisis(c.reality,'claim '+r.id+' had tiny residual interest but its authority record was missing');return null}let amt=Math.max(0,r.outstanding87||0),pre=r.status,w={id:'RIW'+(++S.interestDustSerial88),kind88:'claim-interest-dust',crossDefaultId85:c.id,claimId87:r.id,facilityId55:r.facilityId55,authorityId:r.authorityId,reality:r.reality,borrowerType:r.borrowerType,borrowerId:r.borrowerId,borrower:r.borrower,amount88:amt,status:'written-off',preClaimStatus87:pre,created:Date.now(),x:10+Math.random()*80,y:12+Math.random()*68};r.preDustStatus88=pre;r.outstanding87=0;r.status='paid-with-dust-writeoff88';r.dustFinalizedAt88=Date.now();a.residualInterestForegone88=(a.residualInterestForegone88||0)+amt;S.interestDustWriteoffs88.push(w);S.interestDustClaimWriteoffs88++;S.interestDustAmount88+=amt;markWriteoff(w,c,f,r);update87ClaimMarkers(r,c,f);syncCase(c);remember('INTEREST DUST '+w.id+': '+amt.toFixed(4)+' remaining on '+r.id+' was explicitly written off instead of silently disappearing under the 0.01 finality tolerance',realm(c.reality));trust(c.reality,'de-minimis-claim-interest-written-off',w.id+' '+amt.toFixed(4));if(manual){q('#msg').textContent=w.id+' wrote off '+amt.toFixed(4)+' claim dust.';renderAll();save88();openWriteoff(w)}return w}
function reconstruct(){if(!RECOVER88)return false;let changed=false,seen=new Map();for(const c of(S.fundingCrossDefaults85||[]))for(const m of(c.interestDustMarkers88||[]))seen.set(m.id,m);for(const f of(S.liquidityFacilities55||[]))for(const m of(f.interestDustMarkers88||[]))seen.set(m.id,m);for(const m of seen.values()){if((S.interestDustWriteoffs88||[]).some(x=>x.id===m.id))continue;let w=JSON.parse(JSON.stringify(m));w.recovered=true;S.interestDustWriteoffs88.push(w);S.interestDustAmount88+=w.amount88||0;if(w.kind88==='facility-interest-dust')S.interestDustFacilityWriteoffs88++;else S.interestDustClaimWriteoffs88++;let n=Number(String(w.id).replace(/\D/g,''))||0;if(n>S.interestDustSerial88)S.interestDustSerial88=n;changed=true}let finalized=0;for(const c of(S.fundingCrossDefaults85||[])){if(current87Outstanding(c)<=.0001&&((S.residualInterestClaims87||[]).some(r=>r.crossDefaultId85===c.id)||(c.interestDustMarkers88||[]).length)){c.residualInterestOutstanding87=0;c.residualInterestCured87=true;finalized++}}S.interestDustCasesFinalized88=finalized;return changed}
function reconcile(){if(!ensure())return false;let changed=reconstruct();for(const f of(S.liquidityFacilities55||[])){let w=writeFacilityDust(f,false);if(w)changed=true}for(const r of(S.residualInterestClaims87||[])){let w=writeClaimDust(r,false);if(w)changed=true}return changed}
function openWriteoff(w){panel(w.id+' · DE MINIMIS INTEREST FINALITY',w.status.toUpperCase(),w.borrower+' · '+w.kind88+' · '+w.amount88.toFixed(4)+' foregone interest · source '+(w.claimId87||w.facilityId55),[['close',closePanel]])}
function openOffice(){if(!ensure())return;let acts=[];for(const w of S.interestDustWriteoffs88.slice(-10))acts.push(['open '+w.id+' · '+w.amount88.toFixed(4),()=>openWriteoff(w)]);acts.push(['close',closePanel]);panel(S.deMinimisInterestOffice88.name,'ROUNDING · DMO1',S.interestDustWriteoffs88.length+' write-offs · '+S.interestDustFacilityWriteoffs88+' facility dust · '+S.interestDustClaimWriteoffs88+' claim dust · '+S.interestDustAmount88.toFixed(4)+' foregone interest',acts)}
function render88(){if(!ensure())return;let layer=q('#deMinimisInterestLayer88');if(!layer){layer=document.createElement('div');layer.id='deMinimisInterestLayer88';document.body.appendChild(layer)}layer.innerHTML='';let o=document.createElement('i');o.className='deMinimisInterestOffice88';o.dataset.label='≈0';o.style.left='50%';o.style.top='80%';o.onclick=openOffice;layer.appendChild(o);for(const w of S.interestDustWriteoffs88.slice(-8)){let e=document.createElement('i');e.className='interestDust88 '+w.kind88;e.dataset.label='ε';e.style.left=w.x+'%';e.style.top=w.y+'%';e.onclick=()=>openWriteoff(w);layer.appendChild(e)}let line=q('#deminimisinterestline88');if(!line){line=document.createElement('div');line.id='deminimisinterestline88';line.className='line';(q('#residualinterestline87')||q('#postdefaultcashsweepline86')||q('#monetaryline')||q('#enforcement')).after(line)}line.textContent='de minimis interest: '+S.interestDustWriteoffs88.length+' write-offs · '+S.interestDustAmount88.toFixed(3)+' foregone';let ctr=document.querySelector('#app .controls');if(ctr&&!q('#openDeMinimisInterest88')){let x=document.createElement('button');x.id='openDeMinimisInterest88';x.textContent='open de minimis finality';x.onclick=openOffice;ctr.prepend(x)}}
renderAll=function(){R88();let changed=reconcile();render88();if(changed)save88()};let f=q('#forget');if(f)f.onclick=()=>{for(let i=2;i<=88;i++)localStorage.removeItem('nothing-state-v'+i);location.reload()};setInterval(()=>{reconcile();render88();save88()},2300);ensure();reconcile();renderAll();save88();
})();