(()=>{
const BS45=save,BR45=renderAll,O45=JSON.parse(localStorage.getItem('nothing-state-v45')||'null')||{},cl=(v,a,b)=>Math.max(a,Math.min(b,v)),pick=a=>a&&a.length?a[Math.floor(Math.random()*a.length)]:null;
const NODES45=['traveler','bailiff','archive','court','administration'];
S.packages45=O45.packages45||[];
S.sboms45=O45.sboms45||[];
S.advisories45=O45.advisories45||[];
S.packageIncidents45=O45.packageIncidents45||[];
S.registry45=O45.registry45||{A:{generation:1},B:{generation:1}};
S.packageSerial45=O45.packageSerial45||0;
S.sbomSerial45=O45.sbomSerial45||0;
S.advisorySerial45=O45.advisorySerial45||0;
S.packageIncidentSerial45=O45.packageIncidentSerial45||0;
S.packagesPublished45=O45.packagesPublished45||0;
S.sbomsGenerated45=O45.sbomsGenerated45||0;
S.vulnerabilitiesDisclosed45=O45.vulnerabilitiesDisclosed45||0;
S.vulnerableArtifacts45=O45.vulnerableArtifacts45||0;
S.packagePatches45=O45.packagePatches45||0;
S.dependencyConfusions45=O45.dependencyConfusions45||0;
S.transitiveCompromises45=O45.transitiveCompromises45||0;
S.packageYanks45=O45.packageYanks45||0;
S.maintainerCompromises45=O45.maintainerCompromises45||0;
S.sbomDrifts45=O45.sbomDrifts45||0;
S.dependencyCrises45=O45.dependencyCrises45||0;
S.lastDependencyCrisis45=O45.lastDependencyCrisis45||0;
S.dependencyKeys45=O45.dependencyKeys45||{};
S.scannedArtifacts45=O45.scannedArtifacts45||{};
S.packageExploitKeys45=O45.packageExploitKeys45||{};
S.packages45=S.packages45.map((p,i)=>Object.assign({id:p.id||'PKG'+(i+1),reality:p.reality||'A',name:p.name||'unnamed',version:p.version||'1.0.0',maintainer:p.maintainer||'unknown maintainer',registry:p.registry||('registry/'+(p.reality||'A')),status:p.status||'active',dependencies:p.dependencies||[],rootId:p.rootId||null,integrity:p.integrity||'00000000',published:p.published||Date.now(),patchedFrom:p.patchedFrom||null,foreignOf:p.foreignOf||null,downloads:p.downloads||0,compromisedAt:p.compromisedAt||null,x:Number.isFinite(p.x)?p.x:10+Math.random()*80,y:Number.isFinite(p.y)?p.y:12+Math.random()*68},p));
S.sboms45=S.sboms45.map((s,i)=>Object.assign({id:s.id||'SBOM'+(i+1),artifactId:s.artifactId||null,reality:s.reality||'A',components:s.components||[],digest:s.digest||'00000000',status:s.status||'current',generated:s.generated||Date.now(),vulnerable:s.vulnerable||[],x:Number.isFinite(s.x)?s.x:10+Math.random()*80,y:Number.isFinite(s.y)?s.y:12+Math.random()*68},s));
S.advisories45=S.advisories45.map((a,i)=>Object.assign({id:a.id||'ADV'+(i+1),reality:a.reality||'A',packageId:a.packageId||null,name:a.name||'unknown',version:a.version||'0',severity:a.severity||'medium',status:a.status||'open',summary:a.summary||'dependency behavior under review',disclosed:a.disclosed||Date.now(),patchedPackageId:a.patchedPackageId||null,affectedArtifacts:a.affectedArtifacts||[],exploits:a.exploits||0,x:Number.isFinite(a.x)?a.x:10+Math.random()*80,y:Number.isFinite(a.y)?a.y:12+Math.random()*68},a));
function save45(){BS45();localStorage.setItem('nothing-state-v45',JSON.stringify({packages45:S.packages45,sboms45:S.sboms45,advisories45:S.advisories45,packageIncidents45:S.packageIncidents45,registry45:S.registry45,packageSerial45:S.packageSerial45,sbomSerial45:S.sbomSerial45,advisorySerial45:S.advisorySerial45,packageIncidentSerial45:S.packageIncidentSerial45,packagesPublished45:S.packagesPublished45,sbomsGenerated45:S.sbomsGenerated45,vulnerabilitiesDisclosed45:S.vulnerabilitiesDisclosed45,vulnerableArtifacts45:S.vulnerableArtifacts45,packagePatches45:S.packagePatches45,dependencyConfusions45:S.dependencyConfusions45,transitiveCompromises45:S.transitiveCompromises45,packageYanks45:S.packageYanks45,maintainerCompromises45:S.maintainerCompromises45,sbomDrifts45:S.sbomDrifts45,dependencyCrises45:S.dependencyCrises45,lastDependencyCrisis45:S.lastDependencyCrisis45,dependencyKeys45:S.dependencyKeys45,scannedArtifacts45:S.scannedArtifacts45,packageExploitKeys45:S.packageExploitKeys45}))}save=save45;
const realm=id=>S.real[id],artifact=id=>(S.buildArtifacts44||[]).find(a=>a.id===id),pkg=id=>S.packages45.find(p=>p.id===id),sbomFor=id=>[...S.sboms45].reverse().find(s=>s.artifactId===id&&s.status==='current'),activePackages=(id,name)=>S.packages45.filter(p=>p.reality===id&&p.name===name&&['active','compromised-release'].includes(p.status)),advisory=id=>S.advisories45.find(a=>a.id===id),node=(id,name)=>S.replica43?.[id]?.nodes?.[name];
function hash45(s){let h=2166136261>>>0;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)>>>0}return h.toString(16).padStart(8,'0')}
function rootFor(id){let accepted=S.trustPolicies?.[id]?.acceptedRoots||[];return [...(S.trustRoots||[])].filter(r=>accepted.includes(r.id)&&r.status==='active').sort((a,b)=>(b.strength||0)-(a.strength||0))[0]||null}
function publishPackage(id,name,version,dependencies=[],opts={}){let r=rootFor(id),p={id:'PKG'+(++S.packageSerial45),reality:id,name,version,maintainer:opts.maintainer||((id==='A'?'archive':'court')+' package maintainers'),registry:opts.registry||('registry/'+id),status:'active',dependencies:[...dependencies],rootId:r?.id||null,integrity:hash45([id,name,version,JSON.stringify(dependencies),opts.foreignOf||'',Date.now()].join('|')),published:Date.now(),patchedFrom:opts.patchedFrom||null,foreignOf:opts.foreignOf||null,downloads:0,compromisedAt:null,x:10+Math.random()*80,y:12+Math.random()*68};S.packages45.push(p);S.packagesPublished45++;remember('PACKAGE PUBLISHED '+p.id+': '+p.name+'@'+p.version+' entered '+p.registry,realm(id));return p}
function ensureRegistry(){for(const id of ['A','B']){let defs=id==='A'?[
['rift-core','1.0.0',[]],['archive-codec','1.2.0',['rift-core']],['quorum-client','2.0.0',['rift-core']],['identity-parser','1.1.0',['archive-codec']],['runtime-policy','3.0.0',['quorum-client','identity-parser']]
:[
['rift-core','1.0.1',[]],['archive-codec','1.2.1',['rift-core']],['quorum-client','2.0.1',['rift-core']],['identity-parser','1.1.1',['archive-codec']],['runtime-policy','3.0.1',['quorum-client','identity-parser']
];for(const [n,v,d] of defs)if(!S.packages45.some(p=>p.reality===id&&p.name===n&&p.version===v))publishPackage(id,n,v,d)}}
function versionScore(v){return String(v).split('.').reduce((n,x,i)=>n+(parseInt(x)||0)*Math.pow(100,2-i),0)}
function resolvePackage(id,name,allowForeign=true){let own=activePackages(id,name);let foreign=allowForeign?S.packages45.filter(p=>p.reality!==id&&p.name===name&&p.status==='active'&&p.foreignOf===name):[];return [...own,...foreign].sort((a,b)=>versionScore(b.version)-versionScore(a.version))[0]||null}
function dependencyNamesForArtifact(a){let h=parseInt(hash45((a.sourceRef||'')+'|'+(a.depLock||'')).slice(-2),16),base=['runtime-policy','quorum-client'];if(h%2===0)base.push('archive-codec');if(h%3===0)base.push('identity-parser');return [...new Set(base)]}
function resolveTree(id,names,seen=new Set()){let out=[];for(const name of names){let p=resolvePackage(id,name,true);if(!p||seen.has(p.id))continue;seen.add(p.id);out.push(p);p.downloads++;if(p.dependencies?.length)out.push(...resolveTree(id,p.dependencies,seen))}return out}
function generateSBOM(a,force=false){if(!a)return null;let current=sbomFor(a.id);if(current&&!force)return current;if(current)current.status='superseded';let tree=resolveTree(a.reality,dependencyNamesForArtifact(a)),components=tree.map(p=>p.id),s={id:'SBOM'+(++S.sbomSerial45),artifactId:a.id,reality:a.reality,components,digest:hash45(a.artifactHash+'|'+components.join('|')),status:'current',generated:Date.now(),vulnerable:[],x:10+Math.random()*80,y:12+Math.random()*68};S.sboms45.push(s);S.sboms45=S.sboms45.slice(-120);S.sbomsGenerated45++;scanSBOM(s,false);remember('SBOM '+s.id+': '+a.id+' contains '+tree.map(p=>p.name+'@'+p.version).join(', '),realm(a.reality));return s}
function ensureSBOMs(){ensureRegistry();for(const a of(S.buildArtifacts44||[])){if(!sbomFor(a.id))generateSBOM(a)}}
function affectedAdvisories(s){return S.advisories45.filter(a=>a.status!=='withdrawn'&&s.components.includes(a.packageId))}
function scanSBOM(s,announce=true){if(!s)return[];let xs=affectedAdvisories(s);s.vulnerable=xs.map(a=>a.id);let a=artifact(s.artifactId);for(const adv of xs)if(!adv.affectedArtifacts.includes(s.artifactId))adv.affectedArtifacts.push(s.artifactId);if(xs.length){if(!S.scannedArtifacts45[s.artifactId]){S.scannedArtifacts45[s.artifactId]=1;S.vulnerableArtifacts45++;remember('VULNERABLE ARTIFACT: '+s.artifactId+' has '+xs.map(a=>a.id).join(', ')+' despite valid provenance',realm(s.reality));if(typeof place==='function')place('cold','signed binary with an accurate vulnerable SBOM',realm(s.reality))}if(a&&a.status==='built')a.status='known-vulnerable'}else if(a?.status==='known-vulnerable')a.status='built';if(announce)$('#msg').textContent=xs.length?s.id+' found '+xs.length+' open advisories in '+s.artifactId+'.':s.id+' found no known vulnerable packages.';return xs}
function scanReality(id=S.active){ensureSBOMs();let ss=S.sboms45.filter(s=>s.reality===id&&s.status==='current'),hits=0;for(const s of ss)hits+=scanSBOM(s,false).length;$('#msg').textContent='SBOM scan: '+ss.length+' artifacts, '+hits+' advisory matches in Reality '+id+'.';renderAll();save45();openDependencies(id)}
function choosePackage(id){let used=new Set(S.sboms45.filter(s=>s.reality===id&&s.status==='current').flatMap(s=>s.components));let xs=S.packages45.filter(p=>p.reality===id&&p.status==='active'&&used.has(p.id)&&!S.advisories45.some(a=>a.packageId===p.id&&a.status!=='withdrawn'));return pick(xs)}
function discloseVulnerability(id=S.active,manual=true){ensureSBOMs();let p=choosePackage(id);if(!p){if(manual)$('#msg').textContent='No undisclosed active dependency is currently in use.';return null}let severity=pick(['medium','high','high','critical']),a={id:'ADV'+(++S.advisorySerial45),reality:id,packageId:p.id,name:p.name,version:p.version,severity,status:'open',summary:severity==='critical'?'crafted trust metadata can change execution semantics':'package behavior diverges under institutional runtime edge cases',disclosed:Date.now(),patchedPackageId:null,affectedArtifacts:[],exploits:0,x:10+Math.random()*80,y:12+Math.random()*68};S.advisories45.push(a);S.vulnerabilitiesDisclosed45++;for(const s of S.sboms45.filter(s=>s.status==='current'&&s.components.includes(p.id)))scanSBOM(s,false);remember('VULNERABILITY '+a.id+': '+p.name+'@'+p.version+' disclosed as '+severity,realm(id));if(typeof place==='function'){place('cold','advisory published after binary deployment',realm(id));place('dream','known bad package inside trusted artifact',realm(id))}openPackageIncident(id,'known vulnerable dependency '+p.name+'@'+p.version,severity==='critical'?'SEV1':'SEV2');if(manual){$('#msg').textContent=a.id+' disclosed: '+p.name+'@'+p.version+' is '+severity+'. Provenance remains valid.';renderAll();save45();openAdvisory(a)}return a}
function bumpPatch(v){let x=String(v).split('.').map(n=>parseInt(n)||0);while(x.length<3)x.push(0);x[2]++;return x.join('.')}
function patchPackage(a){if(!a||a.status!=='open')return;let old=pkg(a.packageId);if(!old)return;let np=publishPackage(old.reality,old.name,bumpPatch(old.version),old.dependencies,{maintainer:old.maintainer,patchedFrom:old.id});a.patchedPackageId=np.id;a.status='patched-available';S.packagePatches45++;remember('PATCH AVAILABLE '+a.id+': '+np.name+'@'+np.version+' fixes '+old.id,realm(old.reality));if(typeof place==='function')place('warm','patched package not yet deployed',realm(old.reality));$('#msg').textContent=np.name+'@'+np.version+' exists. Deployed artifacts still contain '+old.version+'.';renderAll();save45();openAdvisory(a)}
function activeReplicaArtifacts(id){return [...new Set(Object.values(S.replicaArtifacts44?.[id]||{}))].map(artifact).filter(Boolean)}
function signDerivedArtifact(a){let r=rootFor(a.reality);if(!r)return;S.attestationSerial44=S.attestationSerial44||0;S.provenance44=S.provenance44||[];S.provenance44.push({id:'AT'+(++S.attestationSerial44),artifactId:a.id,reality:a.reality,builderId:a.builderId,sourceRef:a.sourceRef,recipeHash:a.recipeHash,artifactHash:a.artifactHash,rootId:r.id,status:'attested',created:Date.now()});S.trustAudits=S.trustAudits||[];S.trustAuditSerial=S.trustAuditSerial||0;S.trustAudits.push({id:'TA'+(++S.trustAuditSerial),reality:a.reality,remediationId:null,credentialId:null,certificateId:null,rootId:r.id,status:'dependency-remediation-attested',created:Date.now(),note:a.id+' dependency rebuild',x:10+Math.random()*80,y:12+Math.random()*68})}
function deriveArtifact(old,components,reason){let a={...old,id:'BIN'+(++S.artifactSerial44),depLock:(old.depLock||'lock')+'|pkg45-'+(++S.registry45[old.reality].generation),recipeHash:hash45(old.recipeHash+'|'+components.join('|')+'|'+reason),artifactHash:hash45(old.artifactHash+'|'+components.join('|')+'|'+reason+'|'+Date.now()),status:'built',builtAt:Date.now(),reproducedFrom:old.id,x:10+Math.random()*80,y:12+Math.random()*68};S.buildArtifacts44.push(a);S.artifactsBuilt44=(S.artifactsBuilt44||0)+1;signDerivedArtifact(a);let s={id:'SBOM'+(++S.sbomSerial45),artifactId:a.id,reality:a.reality,components:[...components],digest:hash45(a.artifactHash+'|'+components.join('|')),status:'current',generated:Date.now(),vulnerable:[],x:10+Math.random()*80,y:12+Math.random()*68};S.sboms45.push(s);S.sbomsGenerated45++;scanSBOM(s,false);return a}
function rebuildAffected(a){if(!a||!a.patchedPackageId)return;let old=pkg(a.packageId),replacement=pkg(a.patchedPackageId),id=a.reality,count=0;for(const oldArt of activeReplicaArtifacts(id)){let s=sbomFor(oldArt.id);if(!s||!s.components.includes(old.id))continue;let comps=s.components.map(x=>x===old.id?replacement.id:x),na=deriveArtifact(oldArt,comps,'patch-'+a.id);for(const name of NODES45)if(S.replicaArtifacts44?.[id]?.[name]===oldArt.id)S.replicaArtifacts44[id][name]=na.id;count++}a.status='live-remediated';a.remediatedAt=Date.now();remember('DEPENDENCY REMEDIATION '+a.id+': '+count+' live artifacts rebuilt with '+replacement.name+'@'+replacement.version,realm(id));if(typeof place==='function')place('warm','same source rebuilt around a patched transitive dependency',realm(id));$('#msg').textContent=a.id+' remediated '+count+' active artifacts. Old binaries remain in history.';renderAll();save45();openAdvisory(a)}
function yankPackage(p){if(!p||!['active','compromised-release'].includes(p.status))return;p.status='yanked';S.packageYanks45++;remember('PACKAGE YANKED '+p.id+': '+p.name+'@'+p.version+' removed from new resolution but remains inside existing artifacts',realm(p.reality));if(typeof place==='function')place('cold','yanked package still running in production',realm(p.reality));$('#msg').textContent=p.name+'@'+p.version+' was yanked. Existing SBOMs still contain it.';renderAll();save45();openPackage(p)}
function confuseDependency(id=S.active){ensureRegistry();let other=id==='A'?'B':'A',name=pick(['archive-codec','identity-parser','rift-core','quorum-client']),v='99.'+(S.dependencyConfusions45+1)+'.0',fp=publishPackage(other,name,v,[],{registry:'public/interreality',maintainer:'unclaimed namespace',foreignOf:name});S.dependencyConfusions45++;let touched=0;for(const oldArt of activeReplicaArtifacts(id)){let s=sbomFor(oldArt.id);if(!s)continue;let target=s.components.find(pid=>pkg(pid)?.name===name);if(!target)continue;let comps=s.components.map(x=>x===target?fp.id:x),na=deriveArtifact(oldArt,comps,'dependency-confusion-'+fp.id);for(const n of NODES45)if(S.replicaArtifacts44?.[id]?.[n]===oldArt.id)S.replicaArtifacts44[id][n]=na.id;touched++}remember('DEPENDENCY CONFUSION: Reality '+id+' resolved '+name+' to '+fp.id+' from '+other+' because '+v+' looked newer',realm(id));if(typeof place==='function'){place('cold','foreign package won by version number',realm(id));place('dream','same package name different sovereign registry',realm(id))}openPackageIncident(id,'dependency confusion selected '+name+'@'+v+' from Reality '+other,'SEV1');dependencyCrisis(id,'confusion');$('#msg').textContent='DEPENDENCY CONFUSION: '+touched+' live artifacts now contain '+name+'@'+v+' from '+other+'.';renderAll();save45();openPackage(fp)}
function compromiseMaintainer(p){if(!p)return;p.compromisedAt=Date.now();S.maintainerCompromises45++;let evil=publishPackage(p.reality,p.name,bumpPatch(p.version),p.dependencies,{maintainer:p.maintainer});evil.status='compromised-release';evil.compromisedAt=Date.now();remember('MAINTAINER COMPROMISE: '+p.maintainer+' published '+evil.name+'@'+evil.version+' with valid package identity',realm(p.reality));if(typeof place==='function')place('cold','trusted maintainer published hostile patch',realm(p.reality));openPackageIncident(p.reality,'trusted maintainer published compromised '+evil.name,'SEV1');dependencyCrisis(p.reality,'maintainer-compromise');$('#msg').textContent=evil.id+' is a compromised release signed by the expected maintainer identity.';renderAll();save45();openPackage(evil)}
function exploitAdvisory(a){if(!a||!['open','patched-available'].includes(a.status))return false;let affected=[];for(const id of ['A','B'])for(const name of NODES45){let aid=S.replicaArtifacts44?.[id]?.[name],s=sbomFor(aid);if(s?.components.includes(a.packageId))affected.push({id,name,aid})}if(!affected.length)return false;let t=pick(affected),k=a.id+'|'+t.id+'|'+t.name+'|'+t.aid;if(S.packageExploitKeys45[k])return false;S.packageExploitKeys45[k]=1;a.exploits++;S.transitiveCompromises45++;let n=node(t.id,t.name);if(n){n.state=n.state||{};n.state.exceptions=(n.state.exceptions||0)+1;n.stateHash=hash45(JSON.stringify(n.state)+'|exploit|'+a.id+'|'+t.aid);n.status='dependency-compromised'}remember('TRANSITIVE EXPLOIT '+a.id+': '+t.name+' executed vulnerable '+a.name+'@'+a.version+' from '+t.aid,realm(t.id));if(typeof place==='function'){place('cold','transitive dependency became execution authority',realm(t.id));place('dream','valid binary changed state through known package flaw',realm(t.id))}openPackageIncident(t.id,'vulnerable dependency altered '+t.name+' replica state','SEV1');dependencyCrisis(t.id,'transitive-exploit');return true}
function openPackageIncident(id,title,severity='SEV2'){let existing=S.packageIncidents45.find(x=>x.reality===id&&x.title===title&&x.status==='open');if(existing)return existing;let x={id:'PINC'+(++S.packageIncidentSerial45),reality:id,title,severity,status:'open',created:Date.now(),x:10+Math.random()*80,y:12+Math.random()*68};S.packageIncidents45.push(x);S.provenanceIncidents44=(S.provenanceIncidents44||0)+1;S.incidents=S.incidents||[];S.incidentSerial=S.incidentSerial||0;S.incidents.push({id:'INC'+(++S.incidentSerial),reality:id,title,severity,status:'open',alertIds:[],started:Date.now(),acknowledged:null,resolved:null,postmortem:null,owner:'dependency response',x:x.x,y:x.y});return x}
function dependencyCrisis(id,reason){if(Date.now()-S.lastDependencyCrisis45<8000)return false;let key=id+'|'+reason+'|'+Math.floor(Date.now()/20000);if(S.dependencyKeys45[key])return false;S.dependencyKeys45[key]=1;S.dependencyCrises45++;S.lastDependencyCrisis45=Date.now();for(const rid of ['A','B']){realm(rid).disputes=(realm(rid).disputes||0)+1;remember('DEPENDENCY CRISIS: transitive package selection became authority over executed reality',realm(rid))}realm(id).timelineDrift=(realm(id).timelineDrift||0)+1;if(typeof place==='function'){place('cold','one-line dependency beneath constitutional machinery',realm(id));place('dream','software bill of materials became a chain of command',realm(id))}S.bailiffMood='asking who elected the transitive dependency';return true}
function openPackage(p){let users=S.sboms45.filter(s=>s.status==='current'&&s.components.includes(p.id)),b=[];if(['active','compromised-release'].includes(p.status))b.push(['yank this version',()=>yankPackage(p)],['compromise maintainer',()=>compromiseMaintainer(p)]);for(const s of users.slice(0,3))b.push(['open '+s.id,()=>openSBOM(s)]);b.push(['close',closePanel]);panel(p.name+'@'+p.version,p.id+' · '+p.registry+'\nmaintainer '+p.maintainer,'status '+p.status+' · integrity '+p.integrity+' · '+users.length+' SBOMs · deps '+(p.dependencies.join(', ')||'none'),b)}
function openSBOM(s){let a=artifact(s.artifactId),b=[];for(const pid of s.components.slice(0,8)){let p=pkg(pid);if(p)b.push([p.name+'@'+p.version,()=>openPackage(p)])}for(const aid of s.vulnerable||[]){let x=advisory(aid);if(x)b.push(['open '+x.id,()=>openAdvisory(x)])}b.push(['rescan',()=>{scanSBOM(s);renderAll();save45();openSBOM(s)}],['close',closePanel]);panel(s.id+' · SBOM',s.artifactId+' · digest '+s.digest,(a?.status||'unknown artifact')+' · '+s.components.length+' components · '+s.vulnerable.length+' open advisories',b)}
function openAdvisory(a){let p=pkg(a.packageId),b=[];if(a.status==='open')b.push(['publish patched package',()=>patchPackage(a)]);if(a.patchedPackageId&&!['live-remediated','withdrawn'].includes(a.status))b.push(['rebuild affected live artifacts',()=>rebuildAffected(a)]);if(['open','patched-available'].includes(a.status))b.push(['trigger exploit',()=>{exploitAdvisory(a);renderAll();save45();openAdvisory(a)}]);if(p)b.push(['open vulnerable package',()=>openPackage(p)]);b.push(['close',closePanel]);panel(a.id+' · '+a.severity.toUpperCase(),a.name+'@'+a.version+' · '+a.status,a.summary+'\n'+a.affectedArtifacts.length+' affected artifacts · '+a.exploits+' observed exploits'+(a.patchedPackageId?'\npatch '+pkg(a.patchedPackageId)?.name+'@'+pkg(a.patchedPackageId)?.version:''),b)}
function openDependencies(id=S.active){ensureSBOMs();let used=new Set(S.sboms45.filter(s=>s.reality===id&&s.status==='current').flatMap(s=>s.components)),ps=S.packages45.filter(p=>used.has(p.id)),as=[...S.advisories45].reverse().filter(a=>a.reality===id).slice(0,4),b=[['scan active SBOMs',()=>scanReality(id)],['disclose dependency vulnerability',()=>discloseVulnerability(id)],['simulate dependency confusion',()=>confuseDependency(id)]];for(const a of as)b.push(['open '+a.id,()=>openAdvisory(a)]);for(const p of ps.slice(0,5))b.push([p.name+'@'+p.version,()=>openPackage(p)]);b.push(['close',closePanel]);panel('DEPENDENCIES · Reality '+id,ps.length+' resolved package versions · '+S.sboms45.filter(s=>s.reality===id&&s.status==='current').length+' SBOMs',S.vulnerabilitiesDisclosed45+' advisories · '+S.vulnerableArtifacts45+' vulnerable artifacts · '+S.dependencyConfusions45+' confusions · '+S.transitiveCompromises45+' exploits · '+S.dependencyCrises45+' crises',b)}
function autonomous(){ensureSBOMs();if(Math.random()<.003)discloseVulnerability(pick(['A','B']),false);let xs=S.advisories45.filter(a=>['open','patched-available'].includes(a.status)&&(a.severity==='critical'||a.severity==='high'));if(xs.length&&Math.random()<.008)exploitAdvisory(pick(xs))}
function renderDependencies(){ensureSBOMs();let layer=$('#dependencyLayer');if(!layer){layer=document.createElement('div');layer.id='dependencyLayer';document.body.appendChild(layer)}layer.innerHTML='';for(const p of S.packages45.filter(p=>['active','compromised-release','yanked'].includes(p.status)).slice(-24)){let n=document.createElement('i');n.className='packageNode '+p.status+(p.foreignOf?' foreign':'');n.dataset.label=p.name.slice(0,3).toUpperCase();n.style.left=p.x+'%';n.style.top=p.y+'%';n.onclick=()=>openPackage(p);layer.appendChild(n)}for(const a of S.advisories45.filter(a=>a.status!=='withdrawn').slice(-10)){let n=document.createElement('i');n.className='advisoryNode '+a.severity;n.dataset.label=a.id;n.style.left=a.x+'%';n.style.top=a.y+'%';n.onclick=()=>openAdvisory(a);layer.appendChild(n)}let line=$('#dependencyline');if(!line){line=document.createElement('div');line.id='dependencyline';line.className='line';($('#supplyline')||$('#replicaline')||$('#quorumline')||$('#enforcement')).after(line)}let id=S.active,activeSboms=S.sboms45.filter(s=>s.reality===id&&s.status==='current'),vuln=activeSboms.filter(s=>s.vulnerable.length).length;line.textContent='dependencies: '+activeSboms.length+' SBOMs · '+vuln+' vulnerable · '+S.vulnerabilitiesDisclosed45+' advisories · '+S.dependencyConfusions45+' confusion · '+S.transitiveCompromises45+' exploits · '+S.dependencyCrises45+' crises';let ctr=document.querySelector('#app .controls');if(ctr&&!$('#openDependenciesButton')){let b=document.createElement('button');b.id='openDependenciesButton';b.textContent='open dependencies';b.onclick=()=>openDependencies(S.active);ctr.prepend(b)}if(ctr&&!$('#scanSBOMButton')){let b=document.createElement('button');b.id='scanSBOMButton';b.textContent='scan SBOM';b.onclick=()=>scanReality(S.active);ctr.prepend(b)}}
renderAll=function(){BR45();renderDependencies()};let f=$('#forget');if(f)f.onclick=()=>{for(let i=2;i<=45;i++)localStorage.removeItem('nothing-state-v'+i);location.reload()};
setInterval(()=>{autonomous();renderDependencies();save45()},2200);ensureRegistry();ensureSBOMs();renderAll();save45();
})();