(()=>{
const BS36=save,BR36=renderAll,O36=JSON.parse(localStorage.getItem('nothing-state-v36')||'null')||{},cl=(v,a,b)=>Math.max(a,Math.min(b,v));
const COHORTS=[
  {id:'traveler',label:'traveler',weight:12},
  {id:'larger',label:'larger being',weight:13},
  {id:'smaller',label:'smaller being',weight:13},
  {id:'bailiff',label:'bailiff',weight:12},
  {id:'archive',label:'archive',weight:10},
  {id:'courts',label:'courts',weight:15},
  {id:'agencies',label:'agencies',weight:25}
];
S.rollouts=O36.rollouts||[];S.rolloutSerial=O36.rolloutSerial||0;S.runtimeReality=O36.runtimeReality||{A:{stableHead:null,cohorts:{}},B:{stableHead:null,cohorts:{}}};S.deploymentsStarted=O36.deploymentsStarted||0;S.deploymentsCompleted=O36.deploymentsCompleted||0;S.deploymentsPaused=O36.deploymentsPaused||0;S.deploymentsRolledBack=O36.deploymentsRolledBack||0;S.forcedDeployments=O36.forcedDeployments||0;S.canaryFailures=O36.canaryFailures||0;S.rollbackRefusals=O36.rollbackRefusals||0;S.partialDeploymentCrises=O36.partialDeploymentCrises||0;S.knownBadPromotions=O36.knownBadPromotions||0;S.rolloutObservations=O36.rolloutObservations||0;S.lastDeploymentCrisis=O36.lastDeploymentCrisis||0;S.deploymentKeys=O36.deploymentKeys||{};
for(const id of['A','B']){S.runtimeReality[id]=Object.assign({stableHead:null,cohorts:{}},S.runtimeReality[id]||{});for(const c of COHORTS)if(!(c.id in S.runtimeReality[id].cohorts))S.runtimeReality[id].cohorts[c.id]=S.runtimeReality[id].stableHead||null}
S.rollouts=S.rollouts.map((d,i)=>({id:d.id||'D'+(i+1),reality:d.reality||'A',commitId:d.commitId||null,fromHead:d.fromHead||null,status:d.status||'canary',percent:Number.isFinite(d.percent)?d.percent:0,exposed:d.exposed||[],previous:d.previous||{},signals:d.signals||{good:0,bad:0,last:null},created:d.created||Date.now(),nextAt:d.nextAt||Date.now()+6000,pausedAt:d.pausedAt||null,completedAt:d.completedAt||null,forced:!!d.forced,rollbackAttempts:d.rollbackAttempts||0,x:Number.isFinite(d.x)?d.x:10+Math.random()*80,y:Number.isFinite(d.y)?d.y:12+Math.random()*68}));
function save36(){BS36();localStorage.setItem('nothing-state-v36',JSON.stringify({rollouts:S.rollouts,rolloutSerial:S.rolloutSerial,runtimeReality:S.runtimeReality,deploymentsStarted:S.deploymentsStarted,deploymentsCompleted:S.deploymentsCompleted,deploymentsPaused:S.deploymentsPaused,deploymentsRolledBack:S.deploymentsRolledBack,forcedDeployments:S.forcedDeployments,canaryFailures:S.canaryFailures,rollbackRefusals:S.rollbackRefusals,partialDeploymentCrises:S.partialDeploymentCrises,knownBadPromotions:S.knownBadPromotions,rolloutObservations:S.rolloutObservations,lastDeploymentCrisis:S.lastDeploymentCrisis,deploymentKeys:S.deploymentKeys}))}save=save36;
const realm=id=>S.real[id],commit=id=>(S.realityCommits||[]).find(c=>c.id===id),branch=id=>S.realityBranches?.[id]||{head:null,name:'reality/'+id},validated=id=>S.realityDeployments?.[id]?.head||null,runtime=id=>S.runtimeReality[id],cohort=id=>COHORTS.find(c=>c.id===id),activeRollout=id=>[...S.rollouts].reverse().find(d=>d.reality===id&&['canary','rolling','paused'].includes(d.status));
function currentPercent(d){return COHORTS.filter(c=>d.exposed.includes(c.id)).reduce((n,c)=>n+c.weight,0)}
function initializeRuntime(id){let rt=runtime(id);if(rt.stableHead)return;let seed=validated(id)||branch(id).head||null;rt.stableHead=seed;for(const c of COHORTS)if(!rt.cohorts[c.id])rt.cohorts[c.id]=seed}
function rolloutCandidate(id){let v=validated(id);if(v)return v;let h=branch(id).head,c=commit(h);if(c?.ciStatus==='passed'||c?.ciStatus==='overridden')return h;return null}
function productionVersions(id){let rt=runtime(id),m={};for(const c of COHORTS){let v=rt.cohorts[c.id]||'∅';(m[v]||(m[v]=[])).push(c.id)}return m}
function effectForCohort(d,cid,enter=true){let c=commit(d.commitId),r=realm(d.reality);if(!c)return;let sign=enter?1:-1;if(c.kind==='constitution'&&['courts','bailiff','agencies'].includes(cid)){let k=[...(S.constitutions||[])].reverse().find(k=>k.reality===d.reality&&k.status==='ratified'&&k.supremacy===c.payload?.supremacy);if(k)k.authority=cl((k.authority||.6)+.008*sign,.3,.99)}
else if(c.kind==='office'&&['agencies','bailiff'].includes(cid)){let o=(S.offices||[]).find(o=>o.reality===d.reality&&o.title===c.payload?.title&&o.holder===c.payload?.holder);if(o)o.authority=cl((o.authority||.5)+.01*sign,.2,.99)}
else if(c.kind==='agency'&&cid==='agencies'){let a=(S.agencies||[]).find(a=>a.reality===d.reality&&a.status==='active'&&a.jurisdiction===c.payload?.jurisdiction);if(a)a.expertise=cl((a.expertise||.5)+.015*sign,.1,.99)}
else if(c.kind==='citizenship'&&['traveler','bailiff','archive'].includes(cid)){let x=[...(S.citizenships||[])].reverse().find(x=>x.reality===d.reality&&['active','disputed'].includes(x.status));if(x)x.authority=cl((x.authority||.5)+.008*sign,.2,.99)}
else if(c.kind==='build32'&&['archive','agencies'].includes(cid)){let h=[...(S.missingBuildHypotheses||[])].reverse().find(h=>h.reality===d.reality&&h.theory===c.payload?.theory&&h.status!=='rejected');if(h)h.confidence=cl((h.confidence||.5)+.01*sign,.2,.99)}
if(enter)remember('RUNTIME EXPOSURE '+d.id+': '+cohort(cid).label+' began running '+d.commitId,r);else remember('RUNTIME ROLLBACK '+d.id+': '+cohort(cid).label+' returned from '+d.commitId,r)}
function expose(d,cid){if(!d||d.exposed.includes(cid))return;let rt=runtime(d.reality);d.previous[cid]=rt.cohorts[cid]||d.fromHead||null;rt.cohorts[cid]=d.commitId;d.exposed.push(cid);d.percent=currentPercent(d);effectForCohort(d,cid,true)}
function healthRisk(d,cid){let c=commit(d.commitId),r=realm(d.reality),risk=.08;risk+=Math.min(.26,(r.timelineDrift||0)*.012);risk+=Math.min(.14,(r.disputes||0)*.008);if(c?.ciStatus==='overridden')risk+=.16;if((S.versionControlCrises||0)>0)risk+=.05;if((S.ciCrises||0)>0)risk+=.04;if(cid==='bailiff')risk+=Math.min(.12,(S.selfContempt||0)*.03+(S.circuitSplits||0)*.02);if(cid==='archive')risk+=Math.min(.12,(S.historyGapCrises||0)*.04+(S.recordDivergence||0)*.01);if(cid==='agencies')risk+=Math.min(.16,(S.administrationCrises||0)*.04+((S.agencies||[]).filter(a=>a.reality===d.reality&&a.autonomy>.75).length)*.02);if(cid==='courts')risk+=Math.min(.14,(S.circuitSplits||0)*.035+(S.selfInvalidations||0)*.04);if(cid==='traveler')risk+=Math.min(.14,(S.statelessEvents||0)*.025+(S.citizenshipCrises||0)*.03);if(cid==='larger'||cid==='smaller')risk+=Math.min(.1,(r.identityFlips||0)*.025+(r.timelineDrift||0)*.006);return cl(risk,.04,.72)}
function observe(d,automatic=false){if(!d||!['canary','rolling','paused'].includes(d.status)||!d.exposed.length)return null;let cid=d.exposed[Math.floor(Math.random()*d.exposed.length)],risk=healthRisk(d,cid),bad=Math.random()<risk;S.rolloutObservations++;d.signals.last={cohort:cid,bad,at:Date.now(),risk};if(bad){d.signals.bad++;S.canaryFailures++;remember('DEPLOYMENT SIGNAL '+d.id+': '+cohort(cid).label+' reported a production regression on '+d.commitId,realm(d.reality));if(typeof place==='function')place('cold','incident visible only to '+cohort(cid).label,realm(d.reality));if(d.status!=='paused'){d.status='paused';d.pausedAt=Date.now();S.deploymentsPaused++}S.bailiffMood='asking which production version is legally real';$('#msg').textContent=d.id+' PAUSED: '+cohort(cid).label+' reported that '+d.commitId+' behaves differently in production.';deploymentCrisis(d,'bad-signal')}else{d.signals.good++;remember('DEPLOYMENT SIGNAL '+d.id+': '+cohort(cid).label+' remained stable on '+d.commitId,realm(d.reality));$('#msg').textContent=d.id+' observation passed for '+cohort(cid).label+'.'}renderAll();save36();if(!automatic)openRollout(d);return !bad}
function startDeployment(id=S.active,forced=false,manual=true){initializeRuntime(id);let existing=activeRollout(id);if(existing){openRollout(existing);return existing}let cid=rolloutCandidate(id);if(!cid){$('#msg').textContent='Reality '+id+' has no validated commit available for production.';return null}let rt=runtime(id);if(rt.stableHead===cid&&Object.values(rt.cohorts).every(x=>x===cid)){ $('#msg').textContent=cid+' is already running everywhere in Reality '+id+'.';return null}let first=Math.random()<.55?'traveler':(Math.random()<.5?'bailiff':'archive'),d={id:'D'+(++S.rolloutSerial),reality:id,commitId:cid,fromHead:rt.stableHead||null,status:'canary',percent:0,exposed:[],previous:{},signals:{good:0,bad:0,last:null},created:Date.now(),nextAt:Date.now()+5000+Math.random()*3500,pausedAt:null,completedAt:null,forced:!!forced,rollbackAttempts:0,x:10+Math.random()*80,y:12+Math.random()*68};S.rollouts.push(d);S.rollouts=S.rollouts.slice(-28);S.deploymentsStarted++;expose(d,first);d.percent=currentPercent(d);remember('DEPLOYMENT '+d.id+': '+d.commitId+' entered production through '+cohort(first).label,realm(id));if(typeof place==='function')place('dream','canary running a newer reality',realm(id));$('#msg').textContent=d.id+' began: '+cohort(first).label+' is the canary for '+d.commitId+'.';renderAll();save36();if(manual)openRollout(d);return d}
function nextCohorts(d){return COHORTS.filter(c=>!d.exposed.includes(c.id)).sort((a,b)=>a.weight-b.weight)}
function advance(d,automatic=false){if(!d||!['canary','rolling'].includes(d.status))return;if(d.signals.bad>d.signals.good+1&&!d.forced){d.status='paused';d.pausedAt=Date.now();S.deploymentsPaused++;$('#msg').textContent=d.id+' refused to advance because production evidence is worse than CI evidence.';return openRollout(d)}let left=nextCohorts(d);if(!left.length)return complete(d);let count=d.percent<20?1:d.percent<55?2:left.length,chosen=left.slice(0,count);for(const c of chosen)expose(d,c.id);d.status='rolling';d.nextAt=Date.now()+5200+Math.random()*5200;$('#msg').textContent=d.id+' advanced to '+d.percent+'%: '+chosen.map(c=>c.label).join(', ')+' now run '+d.commitId+'.';if(d.percent>=100)complete(d);else if(Math.random()<.5)observe(d,true);renderAll();save36();if(!automatic)openRollout(d)}
function complete(d){if(!d||d.status==='deployed')return;let rt=runtime(d.reality);for(const c of COHORTS){rt.cohorts[c.id]=d.commitId;if(!d.exposed.includes(c.id))d.exposed.push(c.id)}d.percent=100;d.status=d.forced?'forced':'deployed';d.completedAt=Date.now();rt.stableHead=d.commitId;S.deploymentsCompleted++;if(d.forced)S.forcedDeployments++;remember((d.forced?'FORCED PRODUCTION ':'PRODUCTION ')+d.id+': '+d.commitId+' became runtime reality for every cohort',realm(d.reality));if(typeof place==='function')place(d.forced?'cold':'warm',d.forced?'release promoted despite warning':'all institutions briefly ran the same version',realm(d.reality));$('#msg').textContent=d.id+' completed. '+d.commitId+' is now the production head of Reality '+d.reality+'.';renderAll();save36()}
function forceDeployment(d){if(!d||!['canary','rolling','paused'].includes(d.status))return;d.forced=true;if(d.signals.bad>0){S.knownBadPromotions++;remember('KNOWN-BAD PROMOTION: '+d.commitId+' was forced to 100% after production failures',realm(d.reality));if(typeof place==='function')place('cold','known bad release with executive approval',realm(d.reality));realm(d.reality).timelineDrift=(realm(d.reality).timelineDrift||0)+1}for(const c of COHORTS)if(!d.exposed.includes(c.id))expose(d,c.id);complete(d);deploymentCrisis(d,'forced')}
function resume(d){if(!d||d.status!=='paused')return;d.status='rolling';d.pausedAt=null;d.nextAt=Date.now()+3500;remember('DEPLOYMENT RESUMED '+d.id+': production warnings were acknowledged but not resolved',realm(d.reality));$('#msg').textContent=d.id+' resumed at '+d.percent+'%.';openRollout(d);save36()}
function rollbackRefusalChance(d,cid){let p=.04;if(cid==='agencies'){let autos=(S.agencies||[]).filter(a=>a.reality===d.reality&&a.status==='active').map(a=>a.autonomy||0);p+=autos.length?Math.max(...autos)*.28:0}if(cid==='courts')p+=Math.min(.18,(S.judicialOpinions||0)*.008+(S.circuitSplits||0)*.03);if(cid==='archive')p+=Math.min(.14,(S.precedent||0)*.005+(S.build32Adoptions||0)*.025);if(cid==='bailiff')p+=Math.min(.12,(S.selfContempt||0)*.03);return cl(p,.03,.48)}
function rollback(d,automatic=false){if(!d||!['canary','rolling','paused','forced','deployed','rollback-partial'].includes(d.status))return;let rt=runtime(d.reality),refused=[];d.rollbackAttempts++;for(const cid of [...d.exposed]){let previous=d.previous[cid]??d.fromHead??rt.stableHead??null;if(Math.random()<rollbackRefusalChance(d,cid)&&d.exposed.length>1){refused.push(cid);continue}rt.cohorts[cid]=previous;effectForCohort(d,cid,false)}if(refused.length){S.rollbackRefusals+=refused.length;d.status='rollback-partial';remember('ROLLBACK REFUSED '+d.id+': '+refused.map(x=>cohort(x).label).join(', ')+' kept running '+d.commitId,realm(d.reality));if(typeof place==='function')place('cold','rollback refused by '+refused.map(x=>cohort(x).label).join(' and '),realm(d.reality));S.bailiffMood='checking which institutions accepted the rollback';$('#msg').textContent=d.id+' rollback was PARTIAL. '+refused.map(x=>cohort(x).label).join(', ')+' kept '+d.commitId+'.';deploymentCrisis(d,'rollback-refused')}else{d.status='rolled-back';S.deploymentsRolledBack++;let vals=Object.values(rt.cohorts),same=vals.length&&vals.every(x=>x===vals[0]);if(same)rt.stableHead=vals[0]||d.fromHead||null;remember('ROLLBACK COMPLETE '+d.id+': production returned from '+d.commitId,realm(d.reality));if(typeof place==='function')place('dream','rollback that remembers the release it removed',realm(d.reality));$('#msg').textContent=d.id+' rolled back. The deployment remains in history.'}renderAll();save36();if(!automatic)openRollout(d)}
function deploymentCrisis(d,reason){if(Date.now()-S.lastDeploymentCrisis<6500)return false;let versions=productionVersions(d.reality),keys=Object.keys(versions),key=d.reality+'|'+d.id+'|'+reason+'|'+keys.sort().join(',');if(S.deploymentKeys[key])return false;if(keys.length<2&&reason!=='forced')return false;S.deploymentKeys[key]=1;S.partialDeploymentCrises++;S.lastDeploymentCrisis=Date.now();for(const r of[S.real.A,S.real.B]){r.disputes=(r.disputes||0)+1;remember('PRODUCTION VERSION CRISIS: institutions are running different validated histories at the same time',r)}realm(d.reality).timelineDrift=(realm(d.reality).timelineDrift||0)+1;if(typeof place==='function'){place('dream','production contains more than one reality version',realm(d.reality));place('cold','same country different runtime',realm(d.reality))}S.bailiffMood='asking production which version of reality it serves';$('#msg').textContent='PRODUCTION VERSION CRISIS: Reality '+d.reality+' is running '+keys.length+' runtime versions at once.';return true}
function openRollout(d){let b=[];if(['canary','rolling'].includes(d.status))b.push(['observe canary',()=>observe(d,false)],['advance rollout',()=>advance(d,false)],['pause rollout',()=>{d.status='paused';d.pausedAt=Date.now();S.deploymentsPaused++;$('#msg').textContent=d.id+' paused manually at '+d.percent+'%.';openRollout(d);save36()}]);if(d.status==='paused')b.push(['observe production',()=>observe(d,false)],['resume rollout',()=>resume(d)]);if(['canary','rolling','paused','forced','deployed','rollback-partial'].includes(d.status))b.push(['rollback',()=>rollback(d,false)]);if(['canary','rolling','paused'].includes(d.status))b.push(['force 100%',()=>forceDeployment(d)]);b.push(['close',closePanel]);let versions=productionVersions(d.reality),dist=Object.entries(versions).map(([v,cs])=>(v==='null'?'∅':v)+': '+cs.map(x=>cohort(x).label).join(', ')).join(' | ');panel(d.id+' · '+d.status+' · '+d.percent+'%',(d.fromHead||'∅')+' → '+d.commitId+'\nReality '+d.reality+' progressive production rollout','good '+d.signals.good+' · bad '+d.signals.bad+' · runtime '+dist,b)}
function openProduction(){let id=S.active,rt=runtime(id),a=activeRollout(id),versions=productionVersions(id),b=[['deploy validated reality',()=>startDeployment(id,false)]];if(a)b.push(['open '+a.id,()=>openRollout(a)]);for(const d of [...S.rollouts].reverse().filter(d=>d.reality===id).slice(0,3))if(!a||d.id!==a.id)b.push(['open '+d.id,()=>openRollout(d)]);b.push(['close',closePanel]);let dist=Object.entries(versions).map(([v,cs])=>(v==='null'?'∅':v)+' → '+cs.join(', ')).join('\n');panel('PRODUCTION · Reality '+id,'stable '+(rt.stableHead||'∅')+' · validated '+(validated(id)||'∅')+' · branch HEAD '+(branch(id).head||'∅')+'\n\n'+dist,'deployments '+S.deploymentsStarted+' · completed '+S.deploymentsCompleted+' · rollbacks '+S.deploymentsRolledBack+' · canary failures '+S.canaryFailures+' · rollback refusals '+S.rollbackRefusals+' · production crises '+S.partialDeploymentCrises,b)}
function autoDeploy(){for(const id of['A','B']){initializeRuntime(id);let a=activeRollout(id);if(a){if(['canary','rolling'].includes(a.status)&&Date.now()>=a.nextAt){if(Math.random()<.28)observe(a,true);else advance(a,true)}else if(a.status==='paused'&&Date.now()-a.pausedAt>12000)deploymentCrisis(a,'paused-too-long');continue}let v=rolloutCandidate(id),rt=runtime(id);if(v&&v!==rt.stableHead&&Math.random()<.012){startDeployment(id,false,false);return}}}
function renderProduction(){for(const id of['A','B'])initializeRuntime(id);let l=$('#deploymentLayer');if(!l){l=document.createElement('div');l.id='deploymentLayer';document.body.appendChild(l)}l.innerHTML='';for(const d of S.rollouts.slice(-16)){let n=document.createElement('i');n.className='deployment '+d.status;n.dataset.label=d.id+' '+d.percent+'%';n.style.left=d.x+'%';n.style.top=d.y+'%';n.style.setProperty('--pct',d.percent+'%');n.onclick=()=>openRollout(d);l.appendChild(n)}let badge=$('#productionBadge');if(!badge){badge=document.createElement('div');badge.id='productionBadge';document.body.appendChild(badge)}let id=S.active,rt=runtime(id),versions=productionVersions(id),count=Object.keys(versions).length,a=activeRollout(id);badge.className=count>1?'split':a?'rolling':'stable';badge.textContent=count>1?'PROD ×'+count:a?('DEPLOY '+a.percent+'%'):'PROD STABLE';badge.onclick=openProduction;let line=$('#deploymentline');if(!line){line=document.createElement('div');line.id='deploymentline';line.className='line';($('#ciline')||$('#versionline')||$('#enforcement')).after(line)}line.textContent='production: stable '+(rt.stableHead||'∅')+' · validated '+(validated(id)||'∅')+' · '+count+' runtime version'+(count===1?'':'s')+' · '+S.deploymentsCompleted+' deployed · '+S.canaryFailures+' canary failures · '+S.deploymentsRolledBack+' rollbacks · '+S.rollbackRefusals+' rollback refusals · '+S.partialDeploymentCrises+' production crises';let ctr=document.querySelector('#app .controls');if(ctr&&!$('#deployRealityButton')){let b=document.createElement('button');b.id='deployRealityButton';b.textContent='deploy validated reality';b.onclick=()=>startDeployment(S.active,false);ctr.prepend(b)}if(ctr&&!$('#productionButton')){let b=document.createElement('button');b.id='productionButton';b.textContent='open production';b.onclick=openProduction;ctr.prepend(b)}}
renderAll=function(){BR36();renderProduction()};let f=$('#forget');if(f)f.onclick=()=>{for(let i=2;i<=36;i++)localStorage.removeItem('nothing-state-v'+i);location.reload()};
setInterval(()=>{autoDeploy();renderProduction();save36()},1900);renderAll();save36();
})();
