(()=>{
const BS53=save,BR53=renderAll,O53=JSON.parse(localStorage.getItem('nothing-state-v53')||'null')||{},cl=(v,a,b)=>Math.max(a,Math.min(b,v)),pick=a=>a&&a.length?a[Math.floor(Math.random()*a.length)]:null;
S.derivativeDealers53=O53.derivativeDealers53||[];
S.creditSwaps53=O53.creditSwaps53||[];
S.softwarePools53=O53.softwarePools53||[];
S.tranches53=O53.tranches53||[];
S.derivativeSettlements53=O53.derivativeSettlements53||[];
S.collateralChains53=O53.collateralChains53||[];
S.derivativeDealerSerial53=O53.derivativeDealerSerial53||0;
S.creditSwapSerial53=O53.creditSwapSerial53||0;
S.softwarePoolSerial53=O53.softwarePoolSerial53||0;
S.trancheSerial53=O53.trancheSerial53||0;
S.derivativeSettlementSerial53=O53.derivativeSettlementSerial53||0;
S.collateralChainSerial53=O53.collateralChainSerial53||0;
S.swapsWritten53=O53.swapsWritten53||0;
S.nakedSwaps53=O53.nakedSwaps53||0;
S.swapPremiums53=O53.swapPremiums53||0;
S.swapPayouts53=O53.swapPayouts53||0;
S.swapFailures53=O53.swapFailures53||0;
S.securitizations53=O53.securitizations53||0;
S.syntheticPools53=O53.syntheticPools53||0;
S.tranchesIssued53=O53.tranchesIssued53||0;
S.trancheLosses53=O53.trancheLosses53||0;
S.rehypothecations53=O53.rehypothecations53||0;
S.syntheticNotional53=O53.syntheticNotional53||0;
S.derivativeContagions53=O53.derivativeContagions53||0;
S.derivativeCrises53=O53.derivativeCrises53||0;
S.lastDerivativeCrisis53=O53.lastDerivativeCrisis53||0;
S.derivativeKeys53=O53.derivativeKeys53||{};
S.observedBondDefaults53=O53.observedBondDefaults53||{};
S.lastDerivativeTick53=O53.lastDerivativeTick53||Date.now();
function save53(){BS53();localStorage.setItem('nothing-state-v53',JSON.stringify({derivativeDealers53:S.derivativeDealers53,creditSwaps53:S.creditSwaps53,softwarePools53:S.softwarePools53,tranches53:S.tranches53,derivativeSettlements53:S.derivativeSettlements53,collateralChains53:S.collateralChains53,derivativeDealerSerial53:S.derivativeDealerSerial53,creditSwapSerial53:S.creditSwapSerial53,softwarePoolSerial53:S.softwarePoolSerial53,trancheSerial53:S.trancheSerial53,derivativeSettlementSerial53:S.derivativeSettlementSerial53,collateralChainSerial53:S.collateralChainSerial53,swapsWritten53:S.swapsWritten53,nakedSwaps53:S.nakedSwaps53,swapPremiums53:S.swapPremiums53,swapPayouts53:S.swapPayouts53,swapFailures53:S.swapFailures53,securitizations53:S.securitizations53,syntheticPools53:S.syntheticPools53,tranchesIssued53:S.tranchesIssued53,trancheLosses53:S.trancheLosses53,rehypothecations53:S.rehypothecations53,syntheticNotional53:S.syntheticNotional53,derivativeContagions53:S.derivativeContagions53,derivativeCrises53:S.derivativeCrises53,lastDerivativeCrisis53:S.lastDerivativeCrisis53,derivativeKeys53:S.derivativeKeys53,observedBondDefaults53:S.observedBondDefaults53,lastDerivativeTick53:S.lastDerivativeTick53}))}save=save53;
const realm=id=>S.real[id],bond=id=>(S.softwareBonds52||[]).find(b=>b.id===id),dealer=id=>S.derivativeDealers53.find(d=>d.id===id),pool=id=>S.softwarePools53.find(p=>p.id===id),treasury=id=>(S.packageTreasuries47||[]).find(t=>t.namespaceId===id),insurer=id=>(S.insurers51||[]).find(i=>i.id===id);
function ensureDealers(){for(const id of ['A','B']){let defs=[[id+' Archive Clearing House',46,.82],[id+' Continuity Derivatives Desk',34,.68],[id+' Mutual Hedge Exchange',28,.74]];for(const [name,capital,discipline] of defs)if(!S.derivativeDealers53.some(d=>d.reality===id&&d.name===name))S.derivativeDealers53.push({id:'DLR'+(++S.derivativeDealerSerial53),reality:id,name,status:'solvent',capital,collateral:capital*.3,discipline,swapsSold:0,swapsBought:0,premiums:0,payouts:0,losses:0,rehypothecated:0,created:Date.now(),x:10+Math.random()*80,y:12+Math.random()*68})}}
function holder(ref){if(!ref)return null;let [type,id]=ref.split(':');if(type==='dealer'){let d=dealer(id);return d?{type,id,name:d.name,reality:d.reality,obj:d}:null}if(type==='treasury'){let t=treasury(id),n=(S.namespaces46||[]).find(n=>n.id===id);return t&&n?{type,id,name:n.name+' treasury',reality:n.reality,obj:t}:null}if(type==='insurer'){let i=insurer(id);return i?{type,id,name:i.name,reality:i.reality,obj:i}:null}return null}
function cash(h){if(!h)return 0;return h.type==='treasury'?(h.obj.balance||0):h.type==='insurer'?(h.obj.capital||0):(h.obj.capital||0)}
function addCash(h,v){if(!h)return;if(h.type==='treasury')h.obj.balance=Math.max(0,(h.obj.balance||0)+v);else h.obj.capital=Math.max(0,(h.obj.capital||0)+v)}
function activeBonds(id){return (S.softwareBonds52||[]).filter(b=>b.reality===id&&['active','default'].includes(b.status))}
function currentRating52(b){let rs=(S.creditRatings52||[]).filter(r=>r.subjectType===b.subjectType&&r.subjectId===b.subjectId);if(!rs.length)return'BBB';let des=rs.filter(r=>r.designated);return (des.length?des:rs).sort((a,b)=>b.published-a.published)[0]?.grade||'BBB'}
function protectionBuyer(id,avoid=null){let hs=[];for(const n of (S.namespaces46||[]).filter(n=>n.reality===id)){let t=treasury(n.id);if(t&&t.balance>2)hs.push({ref:'treasury:'+n.id,cash:t.balance})}for(const i of (S.insurers51||[]).filter(i=>i.reality===id&&['solvent','guaranteed','rating-restricted'].includes(i.status)&&i.capital>3))hs.push({ref:'insurer:'+i.id,cash:i.capital});for(const d of S.derivativeDealers53.filter(d=>d.reality===id&&d.status==='solvent'&&d.id!==avoid&&d.capital>3))hs.push({ref:'dealer:'+d.id,cash:d.capital});hs.sort((a,b)=>b.cash-a.cash);return hs[0]?.ref||null}
function riskPremium53(b,naked){let g=currentRating52(b),risk={AAA:.012,AA:.018,A:.026,BBB:.04,BB:.065,B:.095,CCC:.15,D:.26}[g]||.05;return risk*(naked?1.25:1)}
function openIncident53(id,title,severity='SEV2'){S.incidents=S.incidents||[];let ex=S.incidents.find(i=>i.reality===id&&i.title===title&&i.status==='open');if(ex)return ex;S.incidentSerial=S.incidentSerial||0;let x={id:'INC'+(++S.incidentSerial),reality:id,title,severity,status:'open',alertIds:[],started:Date.now(),acknowledged:null,resolved:null,postmortem:null,owner:'software derivatives market',x:10+Math.random()*80,y:12+Math.random()*68};S.incidents.push(x);return x}
function trustRecord53(id,status,note){let accepted=S.trustPolicies?.[id]?.acceptedRoots||[],r=[...(S.trustRoots||[])].filter(x=>accepted.includes(x.id)&&x.status==='active').sort((a,b)=>(b.strength||0)-(a.strength||0))[0];S.trustAudits=S.trustAudits||[];S.trustAuditSerial=S.trustAuditSerial||0;S.trustAudits.push({id:'TA'+(++S.trustAuditSerial),reality:id,remediationId:null,credentialId:null,certificateId:null,rootId:r?.id||null,status,created:Date.now(),note,x:10+Math.random()*80,y:12+Math.random()*68})}
function crisis53(id,why){let now=Date.now(),key=id+'|'+why;if(S.derivativeKeys53[key]&&now-S.derivativeKeys53[key]<18000)return;S.derivativeKeys53[key]=now;S.derivativeCrises53++;S.lastDerivativeCrisis53=now;remember('DERIVATIVES CRISIS: '+why+' turned one software obligation into multiple financial realities',realm(id));if(typeof place==='function'){place('cold','one default with more claims than debt',realm(id));place('dream','software risk copied into contracts that never funded software',realm(id))}S.bailiffMood='asking how one bond default created losses larger than the bond';openIncident53(id,'software derivatives contagion: '+why,why.includes('cascade')?'SEV1':'SEV2')}
function writeSwap(b,naked=false,manual=true){ensureDealers();if(!b||b.status==='default'){if(manual)$('#msg').textContent='Protection cannot be written after the referenced bond has already defaulted.';return null}let seller=pick(S.derivativeDealers53.filter(d=>d.reality===b.reality&&d.status==='solvent'));if(!seller)return null;let buyerRef=protectionBuyer(b.reality,seller.id),buyer=holder(buyerRef);if(!buyer)return null;let base=Math.max(2,b.principal||8),notional=Math.round(base*(naked?(1.1+Math.random()*.9):(.65+Math.random()*.35))*10)/10,premiumRate=riskPremium53(b,naked),premium=Math.max(.2,Math.round(notional*premiumRate*10)/10),collateral=Math.round(notional*(.12+(1-seller.discipline)*.12)*10)/10,pay=Math.min(cash(buyer),premium);addCash(buyer,-pay);seller.capital+=pay;seller.premiums+=pay;let s={id:'CDS'+(++S.creditSwapSerial53),reality:b.reality,bondId:b.id,buyerRef,buyer:buyer.name,sellerId:seller.id,seller:seller.name,status:'active',naked,notional,premiumRate,premium,premiumPaid:pay,collateral,recovery:.4,created:Date.now(),lastPremium:Date.now(),expires:Date.now()+120000,settled:null,x:10+Math.random()*80,y:12+Math.random()*68};S.creditSwaps53.push(s);S.swapsWritten53++;seller.swapsSold++;if(naked){S.nakedSwaps53++;S.syntheticNotional53+=notional}remember((naked?'NAKED ':'')+'CREDIT SWAP '+s.id+': '+buyer.name+' bought '+notional.toFixed(1)+' protection on '+b.id+' from '+seller.name,realm(b.reality));trustRecord53(b.reality,'software-credit-derivative',s.id+' references '+b.id+(naked?' naked':''));if(typeof place==='function')place(naked?'cold':'warm',naked?'default insurance without owning the bond':'credit protection on software bond',realm(b.reality));checkSyntheticLeverage(b.reality);if(manual){$('#msg').textContent=s.id+' written on '+b.id+(naked?' without owning the bond.':'.');renderAll();save53();openSwap(s)}return s}
function collectPremium(s){if(!s||s.status!=='active')return;let buyer=holder(s.buyerRef),seller=dealer(s.sellerId);if(!buyer||!seller||seller.status!=='solvent')return;let due=Math.max(.1,s.premium*.35),pay=Math.min(cash(buyer),due);addCash(buyer,-pay);seller.capital+=pay;seller.premiums+=pay;s.premiumPaid+=pay;S.swapPremiums53+=pay;s.lastPremium=Date.now()}
function settleSwap(s){if(!s||s.status!=='active')return;let b=bond(s.bondId),seller=dealer(s.sellerId),buyer=holder(s.buyerRef);if(!b||b.status!=='default'||!seller||!buyer)return;let due=Math.max(0,s.notional*(1-s.recovery)),paid=Math.min(due,Math.max(0,seller.capital));seller.capital-=paid;seller.payouts+=paid;seller.losses+=Math.max(0,due-paid);addCash(buyer,paid);s.status=paid>=due?'settled':'failed';s.settled=Date.now();s.payout=paid;S.swapPayouts53+=paid;if(paid<due)S.swapFailures53++;let x={id:'DST'+(++S.derivativeSettlementSerial53),reality:s.reality,swapId:s.id,bondId:s.bondId,due,paid,status:s.status,created:Date.now(),x:10+Math.random()*80,y:12+Math.random()*68};S.derivativeSettlements53.push(x);remember('CDS SETTLEMENT '+x.id+': '+s.id+' owed '+due.toFixed(1)+' and paid '+paid.toFixed(1)+' after '+b.id+' defaulted',realm(s.reality));if(typeof place==='function')place(paid<due?'cold':'warm',paid<due?'hedge failed when the hedge counterparty failed':'software default paid someone who never ran the software',realm(s.reality));if(seller.capital<1&&seller.status==='solvent')failDealer(seller,'swap payout');if(s.naked||paid<due)crisis53(s.reality,paid<due?'counterparty cascade after bond default':'naked protection amplified bond default')}
function failDealer(d,reason){if(!d||d.status==='default')return;d.status='default';remember('DERIVATIVES DEALER DEFAULT: '+d.name+' failed after '+reason,realm(d.reality));if(typeof place==='function')place('cold','clearing dealer failed while hedges were still active',realm(d.reality));for(const s of S.creditSwaps53.filter(s=>s.sellerId===d.id&&s.status==='active')){s.status='counterparty-default';S.swapFailures53++}unwindCollateral(d);crisis53(d.reality,'dealer cascade')}
function rehypothecate(id=S.active,manual=true){ensureDealers();let ds=S.derivativeDealers53.filter(d=>d.reality===id&&d.status==='solvent'&&d.collateral>2);if(ds.length<2){if(manual)$('#msg').textContent='At least two solvent dealers with collateral are required.';return null}let from=pick(ds),to=pick(ds.filter(d=>d.id!==from.id)),amt=Math.round(Math.min(from.collateral*.35,3+Math.random()*5)*10)/10;if(amt<=0)return null;let c={id:'COL'+(++S.collateralChainSerial53),reality:id,fromDealerId:from.id,toDealerId:to.id,amount:amt,status:'reused',created:Date.now(),x:10+Math.random()*80,y:12+Math.random()*68};S.collateralChains53.push(c);from.rehypothecated+=amt;to.capital+=amt;S.rehypothecations53++;remember('COLLATERAL REUSE '+c.id+': '+from.name+' let '+to.name+' count '+amt.toFixed(1)+' of the same collateral again',realm(id));if(typeof place==='function')place('dream','same collateral backing more than one promise',realm(id));if(manual){$('#msg').textContent=c.id+' reused '+amt.toFixed(1)+' collateral credits.';renderAll();save53();openCollateral(c)}return c}
function unwindCollateral(d){for(const c of S.collateralChains53.filter(c=>c.fromDealerId===d.id&&c.status==='reused')){let to=dealer(c.toDealerId);c.status='called';c.called=Date.now();if(to){to.capital-=c.amount;S.derivativeContagions53++;remember('COLLATERAL RECALL '+c.id+': '+to.name+' lost '+c.amount.toFixed(1)+' when '+d.name+' failed',realm(d.reality));if(to.capital<1&&to.status==='solvent')failDealer(to,'rehypothecated collateral recall')}}}
function poolLossWaterfall(p,loss,reason){let order={equity:0,mezz:1,senior:2},ts=S.tranches53.filter(t=>t.poolId===p.id).sort((a,b)=>order[a.level]-order[b.level]);let remaining=loss;for(const t of ts){if(remaining<=0)break;let hit=Math.min(t.remaining,remaining);t.remaining-=hit;t.loss+=hit;remaining-=hit;S.trancheLosses53+=hit;if(t.loss>0&&t.level==='equity')t.rating='D';else if(t.loss>0&&t.level==='mezz')t.rating='CCC';else if(t.loss>0)t.rating='B';if(t.remaining<=0)t.status='wiped'}p.loss=(p.loss||0)+loss;p.status=remaining>0?'exhausted':'impaired';remember('TRANCHE WATERFALL '+p.id+': '+loss.toFixed(1)+' loss from '+reason+' consumed '+ts.filter(t=>t.loss>0).map(t=>t.level).join(' → '),realm(p.reality));if(typeof place==='function')place('cold','AAA tranche learning what correlation means',realm(p.reality));if(ts.some(t=>t.level==='senior'&&t.loss>0))crisis53(p.reality,'senior tranche loss')}
function securitize(id=S.active,synthetic=false,manual=true){let refs=synthetic?S.creditSwaps53.filter(s=>s.reality===id&&s.status==='active').slice(-5):(S.softwareBonds52||[]).filter(b=>b.reality===id&&b.status==='active').slice(-5);if(refs.length<2){if(manual)$('#msg').textContent=synthetic?'At least two active swaps are required for a synthetic pool.':'Issue at least two active Build 52 bonds before securitizing them.';return null}let notional=refs.reduce((n,x)=>n+(synthetic?x.notional:(x.principal||0)),0),p={id:'POOL'+(++S.softwarePoolSerial53),reality:id,type:synthetic?'synthetic':'cash',referenceIds:refs.map(x=>x.id),notional,loss:0,status:'active',created:Date.now(),x:10+Math.random()*80,y:12+Math.random()*68};S.softwarePools53.push(p);S.securitizations53++;if(synthetic)S.syntheticPools53++;let specs=[['senior',.65,'AAA'],['mezz',.23,'BBB'],['equity',.12,'BB']];for(const [level,share,rating] of specs){let amount=Math.round(notional*share*10)/10;S.tranches53.push({id:'TR'+(++S.trancheSerial53),poolId:p.id,reality:id,level,notional:amount,remaining:amount,loss:0,rating,status:'active',created:Date.now(),x:p.x+(Math.random()-.5)*5,y:p.y+(Math.random()-.5)*5});S.tranchesIssued53++}remember((synthetic?'SYNTHETIC ':'')+'SOFTWARE SECURITIZATION '+p.id+': '+refs.length+' '+(synthetic?'credit swaps':'software bonds')+' became three tranches',realm(id));trustRecord53(id,'software-securitization',p.id+' '+p.type+' '+refs.map(x=>x.id).join(','));if(typeof place==='function'){place('warm',synthetic?'synthetic tranche referencing software defaults':'software bonds bundled into tranches',realm(id));place('dream','diversification made from packages sharing the same reality',realm(id))}if(manual){$('#msg').textContent=p.id+' issued senior, mezzanine, and equity tranches.';renderAll();save53();openPool(p)}return p}
function settlePoolsForBond(b){for(const p of S.softwarePools53.filter(p=>p.type==='cash'&&p.status!=='exhausted'&&p.referenceIds.includes(b.id))){let key=p.id+'|'+b.id;if(S.derivativeKeys53[key])continue;S.derivativeKeys53[key]=Date.now();poolLossWaterfall(p,(b.principal||8)*.6,b.id+' default')}}
function settleSyntheticPoolsForSwap(s){for(const p of S.softwarePools53.filter(p=>p.type==='synthetic'&&p.status!=='exhausted'&&p.referenceIds.includes(s.id))){let key=p.id+'|'+s.id+'|settled';if(S.derivativeKeys53[key])continue;S.derivativeKeys53[key]=Date.now();let loss=s.notional*(1-s.recovery);poolLossWaterfall(p,loss,s.id+' reference default')}}
function observeDefaults(){for(const b of (S.softwareBonds52||[]).filter(b=>b.status==='default')){if(!S.observedBondDefaults53[b.id]){S.observedBondDefaults53[b.id]=Date.now();remember('DERIVATIVE CREDIT EVENT: '+b.id+' default is now propagating through swaps and tranches',realm(b.reality));settlePoolsForBond(b)}for(const s of S.creditSwaps53.filter(s=>s.bondId===b.id&&s.status==='active')){settleSwap(s);settleSyntheticPoolsForSwap(s)}}}
function underlyingDebt(id){return (S.softwareBonds52||[]).filter(b=>b.reality===id&&b.status==='active').reduce((n,b)=>n+(b.principal||0),0)}
function grossDerivativeNotional(id){return S.creditSwaps53.filter(s=>s.reality===id&&['active','settled','failed'].includes(s.status)).reduce((n,s)=>n+s.notional,0)+S.softwarePools53.filter(p=>p.reality===id&&p.type==='synthetic').reduce((n,p)=>n+p.notional,0)}
function checkSyntheticLeverage(id){let debt=underlyingDebt(id),gross=grossDerivativeNotional(id);if(debt>0&&gross>debt*2.5)crisis53(id,'synthetic claims exceed underlying software debt')}
function stressMarket(id=S.active){let bs=(S.softwareBonds52||[]).filter(b=>b.reality===id&&b.status==='active');if(!bs.length){$('#msg').textContent='There is no active Build 52 bond to stress.';return}let b=pick(bs);for(let i=0;i<3;i++)writeSwap(b,true,false);rehypothecate(id,false);checkSyntheticLeverage(id);remember('DERIVATIVES STRESS: market created multiple synthetic claims on '+b.id,realm(id));$('#msg').textContent='Three naked swaps were written on '+b.id+' and dealer collateral was reused.';renderAll();save53()}
function openSwap(s){let b=bond(s.bondId),d=dealer(s.sellerId),buyer=holder(s.buyerRef),acts=[];if(s.status==='active'&&b?.status==='default')acts.push(['settle default',()=>{settleSwap(s);renderAll();save53();openSwap(s)}]);if(s.status==='active')acts.push(['collect premium',()=>{collectPremium(s);renderAll();save53();openSwap(s)}]);acts.push(['close',closePanel]);panel(s.id+' · '+(s.naked?'NAKED CDS':'CREDIT SWAP'),s.status+' · '+s.bondId,'buyer '+(buyer?.name||s.buyer)+' · seller '+(d?.name||s.seller)+' · notional '+s.notional.toFixed(1)+' · premium '+s.premium.toFixed(1)+' · collateral '+s.collateral.toFixed(1)+(s.payout!=null?' · payout '+s.payout.toFixed(1):''),acts)}
function openDealer(d){let ss=S.creditSwaps53.filter(s=>s.sellerId===d.id),acts=[];for(const s of ss.slice(-5))acts.push(['open '+s.id,()=>openSwap(s)]);if(d.status==='solvent')acts.push(['reuse collateral',()=>rehypothecate(d.reality)]);acts.push(['close',closePanel]);panel(d.name+' · '+d.status.toUpperCase(),d.id+' · derivatives dealer','capital '+d.capital.toFixed(1)+' · collateral '+d.collateral.toFixed(1)+' · reused '+d.rehypothecated.toFixed(1)+' · '+ss.filter(s=>s.status==='active').length+' active swaps · payouts '+d.payouts.toFixed(1),acts)}
function openPool(p){let ts=S.tranches53.filter(t=>t.poolId===p.id),acts=ts.map(t=>['open '+t.id+' '+t.level,()=>openTranche(t)]);acts.push(['close',closePanel]);panel(p.id+' · '+p.type.toUpperCase()+' POOL',p.status+' · '+p.referenceIds.length+' references','notional '+p.notional.toFixed(1)+' · loss '+(p.loss||0).toFixed(1)+'\n'+ts.map(t=>t.level+' '+t.rating+' '+t.remaining.toFixed(1)+'/'+t.notional.toFixed(1)).join(' · '),acts)}
function openTranche(t){let p=pool(t.poolId);panel(t.id+' · '+t.level.toUpperCase()+' · '+t.rating,t.status+' · '+p?.id,'remaining '+t.remaining.toFixed(1)+' of '+t.notional.toFixed(1)+' · realized loss '+t.loss.toFixed(1),[['open pool',()=>openPool(p)],['close',closePanel]])}
function openCollateral(c){let a=dealer(c.fromDealerId),b=dealer(c.toDealerId);panel(c.id+' · COLLATERAL REUSE',c.status,(a?.name||c.fromDealerId)+' → '+(b?.name||c.toDealerId)+' · '+c.amount.toFixed(1)+' credits counted again',[['close',closePanel]])}
function openDerivatives(id=S.active){ensureDealers();let bs=(S.softwareBonds52||[]).filter(b=>b.reality===id&&b.status==='active'),acts=[['stress derivatives market',()=>stressMarket(id)],['securitize active bonds',()=>securitize(id,false)],['securitize active swaps',()=>securitize(id,true)],['rehypothecate collateral',()=>rehypothecate(id)]];for(const b of bs.slice(-4)){acts.push(['hedge '+b.id,()=>writeSwap(b,false)],['naked swap on '+b.id,()=>writeSwap(b,true)])}for(const d of S.derivativeDealers53.filter(d=>d.reality===id))acts.push([d.name,()=>openDealer(d)]);for(const p of S.softwarePools53.filter(p=>p.reality===id).slice(-4))acts.push(['open '+p.id,()=>openPool(p)]);acts.push(['close',closePanel]);let debt=underlyingDebt(id),gross=grossDerivativeNotional(id);panel('SOFTWARE DERIVATIVES · Reality '+id,S.creditSwaps53.filter(s=>s.reality===id&&s.status==='active').length+' active swaps · '+S.softwarePools53.filter(p=>p.reality===id).length+' pools','underlying debt '+debt.toFixed(1)+' · derivative notional '+gross.toFixed(1)+' · '+S.nakedSwaps53+' naked swaps · '+S.rehypothecations53+' collateral reuses · '+S.swapFailures53+' failed hedges · '+S.derivativeCrises53+' crises',acts)}
function autonomous(){ensureDealers();let now=Date.now();if(now-S.lastDerivativeTick53<1900)return;S.lastDerivativeTick53=now;observeDefaults();for(const s of S.creditSwaps53.filter(s=>s.status==='active')){if(s.expires<=now){s.status='expired';continue}if(now-s.lastPremium>12000){collectPremium(s);break}}if(Math.random()<.002){let id=pick(['A','B']),bs=(S.softwareBonds52||[]).filter(b=>b.reality===id&&b.status==='active');if(bs.length)writeSwap(pick(bs),Math.random()<.45,false)}if(Math.random()<.0015)rehypothecate(pick(['A','B']),false);for(const id of ['A','B'])checkSyntheticLeverage(id)}
function renderDerivatives(){ensureDealers();let layer=$('#derivativesLayer');if(!layer){layer=document.createElement('div');layer.id='derivativesLayer';document.body.appendChild(layer)}layer.innerHTML='';for(const d of S.derivativeDealers53){let e=document.createElement('i');e.className='derivativeDealer '+d.status;e.dataset.label=d.id;e.style.left=d.x+'%';e.style.top=d.y+'%';e.onclick=()=>openDealer(d);layer.appendChild(e)}for(const s of S.creditSwaps53.filter(s=>['active','failed','counterparty-default'].includes(s.status)).slice(-16)){let e=document.createElement('i');e.className='creditSwap '+s.status+(s.naked?' naked':'');e.dataset.label=s.id.replace('CDS','S');e.style.left=s.x+'%';e.style.top=s.y+'%';e.onclick=()=>openSwap(s);layer.appendChild(e)}for(const p of S.softwarePools53.slice(-10)){let e=document.createElement('i');e.className='softwarePool '+p.type+' '+p.status;e.dataset.label=p.id.replace('POOL','P');e.style.left=p.x+'%';e.style.top=p.y+'%';e.onclick=()=>openPool(p);layer.appendChild(e)}for(const c of S.collateralChains53.filter(c=>c.status==='reused').slice(-10)){let e=document.createElement('i');e.className='collateralReuse';e.dataset.label='↻';e.style.left=c.x+'%';e.style.top=c.y+'%';e.onclick=()=>openCollateral(c);layer.appendChild(e)}let line=$('#derivativesline');if(!line){line=document.createElement('div');line.id='derivativesline';line.className='line';($('#capitalline')||$('#insuranceline')||$('#standardsline')||$('#enforcement')).after(line)}let id=S.active,debt=underlyingDebt(id),gross=grossDerivativeNotional(id),active=S.creditSwaps53.filter(s=>s.reality===id&&s.status==='active').length;line.textContent='software derivatives: '+active+' swaps · '+gross.toFixed(1)+' notional / '+debt.toFixed(1)+' debt · '+S.softwarePools53.filter(p=>p.reality===id).length+' pools · '+S.rehypothecations53+' collateral reuses · '+S.swapFailures53+' failed hedges · '+S.derivativeCrises53+' crises';let ctr=document.querySelector('#app .controls');if(ctr&&!$('#openDerivativesButton')){let x=document.createElement('button');x.id='openDerivativesButton';x.textContent='open derivatives market';x.onclick=()=>openDerivatives(S.active);ctr.prepend(x)}if(ctr&&!$('#hedgeBondButton')){let x=document.createElement('button');x.id='hedgeBondButton';x.textContent='hedge software bond';x.onclick=()=>{let bs=(S.softwareBonds52||[]).filter(b=>b.reality===S.active&&b.status==='active');if(!bs.length)$('#msg').textContent='Issue a Build 52 bond first.';else writeSwap(bs.sort((a,b)=>(b.coupon||0)-(a.coupon||0))[0],false)};ctr.prepend(x)}}
renderAll=function(){BR53();renderDerivatives()};let f=$('#forget');if(f)f.onclick=()=>{for(let i=2;i<=53;i++)localStorage.removeItem('nothing-state-v'+i);location.reload()};
setInterval(()=>{autonomous();renderDerivatives();save53()},2200);ensureDealers();observeDefaults();renderAll();save53();
})();
