(()=>{
const BS47=save,BR47=renderAll,O47=JSON.parse(localStorage.getItem('nothing-state-v47')||'null')||{},cl=(v,a,b)=>Math.max(a,Math.min(b,v)),pick=a=>a&&a.length?a[Math.floor(Math.random()*a.length)]:null;
S.packageTreasuries47=O47.packageTreasuries47||[];
S.fundingContracts47=O47.fundingContracts47||[];
S.laborEvents47=O47.laborEvents47||[];
S.fundingAudits47=O47.fundingAudits47||[];
S.treasurySerial47=O47.treasurySerial47||0;
S.contractSerial47=O47.contractSerial47||0;
S.laborSerial47=O47.laborSerial47||0;
S.fundingAuditSerial47=O47.fundingAuditSerial47||0;
S.dependencyTaxes47=O47.dependencyTaxes47||0;
S.sponsorships47=O47.sponsorships47||0;
S.maintainerPayroll47=O47.maintainerPayroll47||0;
S.maintainerStrikes47=O47.maintainerStrikes47||0;
S.strikesSettled47=O47.strikesSettled47||0;
S.packageBailouts47=O47.packageBailouts47||0;
S.sponsorCaptures47=O47.sponsorCaptures47||0;
S.fundingForks47=O47.fundingForks47||0;
S.packageInsolvencies47=O47.packageInsolvencies47||0;
S.fundingCrises47=O47.fundingCrises47||0;
S.lastFundingCrisis47=O47.lastFundingCrisis47||0;
S.fundingKeys47=O47.fundingKeys47||{};
S.lastEconomyTick47=O47.lastEconomyTick47||Date.now();
function save47(){BS47();localStorage.setItem('nothing-state-v47',JSON.stringify({packageTreasuries47:S.packageTreasuries47,fundingContracts47:S.fundingContracts47,laborEvents47:S.laborEvents47,fundingAudits47:S.fundingAudits47,treasurySerial47:S.treasurySerial47,contractSerial47:S.contractSerial47,laborSerial47:S.laborSerial47,fundingAuditSerial47:S.fundingAuditSerial47,dependencyTaxes47:S.dependencyTaxes47,sponsorships47:S.sponsorships47,maintainerPayroll47:S.maintainerPayroll47,maintainerStrikes47:S.maintainerStrikes47,strikesSettled47:S.strikesSettled47,packageBailouts47:S.packageBailouts47,sponsorCaptures47:S.sponsorCaptures47,fundingForks47:S.fundingForks47,packageInsolvencies47:S.packageInsolvencies47,fundingCrises47:S.fundingCrises47,lastFundingCrisis47:S.lastFundingCrisis47,fundingKeys47:S.fundingKeys47,lastEconomyTick47:S.lastEconomyTick47}))}save=save47;
const realm=id=>S.real[id],ns=id=>(S.namespaces46||[]).find(n=>n.id===id),pkg=id=>(S.packages45||[]).find(p=>p.id===id),seat=id=>(S.maintainers46||[]).find(m=>m.id===id),treasury=id=>S.packageTreasuries47.find(t=>t.namespaceId===id),contracts=id=>S.fundingContracts47.filter(c=>c.namespaceId===id&&c.status==='active');
function hash47(s){let h=2166136261>>>0;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)>>>0}return h.toString(16).padStart(8,'0')}
function liveUsers(n){let ids=new Set();for(const s of (S.sboms45||[]).filter(s=>s.reality===n.reality&&s.status==='current'))if((s.components||[]).some(pid=>pkg(pid)?.name===n.name))ids.add(s.artifactId);return ids.size}
function reverseDependents(n){return new Set((S.packages45||[]).filter(p=>p.reality===n.reality&&p.status!=='yanked'&&(p.dependencies||[]).includes(n.name)).map(p=>p.name)).size}
function advisoryPressure(n){return (S.advisories45||[]).filter(a=>a.reality===n.reality&&a.name===n.name&&a.status!=='withdrawn'&&a.status!=='live-remediated').reduce((v,a)=>v+(a.severity==='critical'?2.4:a.severity==='high'?1.5:.7),0)}
function activeSeats(n){return (S.maintainers46||[]).filter(m=>m.namespaceId===n.id&&['active','strike'].includes(m.status))}
function ensureTreasuries(){for(const n of (S.namespaces46||[])){if(treasury(n.id))continue;let users=liveUsers(n),deps=reverseDependents(n),t={id:'TREAS'+(++S.treasurySerial47),namespaceId:n.id,reality:n.reality,balance:12+users*2+deps*1.5,debt:0,taxRate:1,monthlyBurn:2.2,status:'solvent',publicUtility:false,bailouts:0,totalRaised:0,totalTaxes:0,totalPayroll:0,lastTick:Date.now(),lastSponsor:null,capturedBy:null,x:10+Math.random()*80,y:12+Math.random()*68};S.packageTreasuries47.push(t);remember('PACKAGE TREASURY '+t.id+': '+n.name+' opened with '+t.balance.toFixed(1)+' credits',realm(n.reality))}}
function sponsorOptions(n){let other=n.reality==='A'?'B':'A',out=[n.reality+' archive foundation',n.reality+' administrative consortium',n.reality+' court infrastructure fund','downstream dependency cooperative',other+' interoperability fund'];let office=(S.offices||[]).filter(o=>o.reality===n.reality&&['active','disputed'].includes(o.status)).slice(-1)[0];if(office)out.push('office of '+office.title);return out}
function sponsorCondition(){return pick(['security-first','compatibility-first','sovereignty-first','ship-fast','continuity-at-any-cost'])}
function acceptSponsor(n,amount=null,sponsor=null){let t=treasury(n.id);if(!t)return null;sponsor=sponsor||pick(sponsorOptions(n));amount=amount||Math.round((5+liveUsers(n)*1.5+Math.random()*6)*10)/10;let c={id:'FC'+(++S.contractSerial47),namespaceId:n.id,reality:n.reality,sponsor,amount,remaining:amount,paid:0,influence:0,condition:sponsorCondition(),status:'active',created:Date.now(),x:10+Math.random()*80,y:12+Math.random()*68};S.fundingContracts47.push(c);S.sponsorships47++;t.lastSponsor=sponsor;t.totalRaised+=amount;remember('PACKAGE SPONSOR '+c.id+': '+sponsor+' committed '+amount+' credits to '+n.name+' for '+c.condition,realm(n.reality));if(typeof place==='function')place('warm','sponsor logo beside a critical dependency',realm(n.reality));return c}
function collectTaxes(n,manual=false){let t=treasury(n.id),users=liveUsers(n),deps=reverseDependents(n),gross=(users*.42+deps*.28)*t.taxRate;if(gross<=0)return 0;t.balance+=gross;t.totalTaxes+=gross;S.dependencyTaxes47+=gross;if(manual){remember('DEPENDENCY TAX: '+n.name+' collected '+gross.toFixed(1)+' credits from '+users+' live artifacts and '+deps+' reverse dependents',realm(n.reality));$('#msg').textContent=n.name+' collected '+gross.toFixed(1)+' dependency credits.'}return gross}
function payroll(n,manual=false){let t=treasury(n.id),seats=activeSeats(n),pressure=advisoryPressure(n),cost=(1.1+seats.length*.72+pressure*.28);t.monthlyBurn=cost;if(t.balance>=cost){t.balance-=cost;t.totalPayroll+=cost;S.maintainerPayroll47+=cost;t.debt=Math.max(0,t.debt-cost*.6);for(const m of seats)m.fatigue=cl((m.fatigue||0)-(.018+Math.min(.04,cost/100)),0,1);if(manual){remember('MAINTAINER PAYROLL: '+n.name+' paid '+cost.toFixed(1)+' credits to '+seats.length+' maintainers',realm(n.reality));$('#msg').textContent=n.name+' paid maintainers. Fatigue fell slightly.'}return true}t.debt+=cost-t.balance;t.balance=0;for(const m of seats)m.fatigue=cl((m.fatigue||0)+.035+.01*pressure,0,1);if(manual)$('#msg').textContent=n.name+' could not make payroll. Funding debt is '+t.debt.toFixed(1)+'.';return false}
function sponsorTick(n,t){for(const c of contracts(n.id)){if(c.remaining<=0){c.status='fulfilled';continue}let pay=Math.min(c.remaining,.45+liveUsers(n)*.03);c.remaining-=pay;c.paid+=pay;c.influence=cl(c.influence+pay/Math.max(10,c.amount)*.09,0,.95);t.balance+=pay;t.totalRaised+=pay;if(c.influence>.58&&!t.capturedBy)sponsorCapture(n,c)}}
function sponsorCapture(n,c){let t=treasury(n.id);if(!t||t.capturedBy)return;t.capturedBy=c.sponsor;S.sponsorCaptures47++;n.legitimacy=cl((n.legitimacy||.6)-.08,.1,.99);n.succession='funding-weighted succession';for(const d of (S.namespaceDisputes46||[]).filter(d=>d.namespaceId===n.id&&d.status==='open')){if(!d.candidates.includes(c.sponsor))d.candidates.push(c.sponsor);d.votes[c.sponsor]=(d.votes[c.sponsor]||0)+2}remember('SPONSOR CAPTURE: '+c.sponsor+' became operationally decisive for '+n.name+' after funding '+c.paid.toFixed(1)+' credits',realm(n.reality));if(typeof place==='function'){place('cold','maintainer salary became a governance vote',realm(n.reality));place('dream','package budget with a foreign policy',realm(n.reality))}fundingCrisis(n.reality,'sponsor-capture')}
function auditFunding(n){let t=treasury(n.id),c=contracts(n.id),a={id:'FA'+(++S.fundingAuditSerial47),namespaceId:n.id,reality:n.reality,balance:t.balance,debt:t.debt,taxRate:t.taxRate,sponsors:c.map(x=>({sponsor:x.sponsor,paid:x.paid,influence:x.influence})),created:Date.now()};S.fundingAudits47.push(a);S.fundingAudits47=S.fundingAudits47.slice(-64);remember('FUNDING AUDIT '+a.id+': '+n.name+' has '+t.balance.toFixed(1)+' credits, '+t.debt.toFixed(1)+' debt, '+c.length+' active sponsors',realm(n.reality));return a}
function startStrike(n,reason='missed payroll',manual=true){let t=treasury(n.id);if(!t||['strike','bankrupt'].includes(t.status))return false;t.status='strike';if(n.status==='governed'||n.status==='emergency')n.preStrikeStatus=n.status,n.status='strike';for(const m of activeSeats(n)){m.preStrikeStatus=m.status;m.status='strike'}let e={id:'LAB'+(++S.laborSerial47),namespaceId:n.id,reality:n.reality,type:'strike',reason,status:'active',created:Date.now(),x:10+Math.random()*80,y:12+Math.random()*68};S.laborEvents47.push(e);S.maintainerStrikes47++;remember('MAINTAINER STRIKE '+e.id+': '+n.name+' stopped maintenance over '+reason+' while deployed binaries kept running',realm(n.reality));if(typeof place==='function'){place('cold','critical package on strike while production continues',realm(n.reality));place('dream','maintenance stopped execution did not',realm(n.reality))}if(manual)$('#msg').textContent=n.name+' maintainers are on strike. Existing binaries continue running.';if(liveUsers(n)>=3)fundingCrisis(n.reality,'critical-strike');return true}
function settleStrike(n,source='settlement'){let t=treasury(n.id);if(!t||t.status!=='strike')return false;let needed=Math.max(4,t.debt+3);t.balance+=needed;t.totalRaised+=needed;t.debt=Math.max(0,t.debt-needed*.8);t.status='solvent';if(n.status==='strike')n.status=n.preStrikeStatus||'governed';for(const m of activeSeats(n)){if(m.status==='strike')m.status=m.preStrikeStatus||'active';m.fatigue=cl((m.fatigue||0)-.15,0,1)}let e=[...S.laborEvents47].reverse().find(e=>e.namespaceId===n.id&&e.type==='strike'&&e.status==='active');if(e)e.status='settled',e.settled=Date.now(),e.settlement=source;S.strikesSettled47++;remember('STRIKE SETTLEMENT: '+n.name+' received '+needed.toFixed(1)+' credits through '+source,realm(n.reality));if(typeof place==='function')place('warm','package maintenance resumed under a funding agreement',realm(n.reality));$('#msg').textContent=n.name+' strike settled through '+source+'.';return true}
function bailout(n){let t=treasury(n.id);if(!t)return;let sponsor=n.reality+' emergency software treasury',amount=Math.max(10,t.debt+7+liveUsers(n)*2);t.balance+=amount;t.debt=Math.max(0,t.debt-amount*.7);t.totalRaised+=amount;t.bailouts++;S.packageBailouts47++;let c=acceptSponsor(n,amount,sponsor);if(c){c.condition='continuity-at-any-cost';c.paid=amount;c.remaining=0;c.influence=cl(.34+t.bailouts*.12,0,.9);c.status='fulfilled';if(c.influence>.58)sponsorCapture(n,c)}if(t.status==='strike')settleStrike(n,'emergency bailout');if(t.status==='bankrupt')t.status='solvent';if(n.status==='bankrupt')n.status='emergency';remember('PACKAGE BAILOUT: '+sponsor+' rescued '+n.name+' with '+amount.toFixed(1)+' credits because '+liveUsers(n)+' live artifacts still depended on it',realm(n.reality));if(typeof place==='function')place('warm','dependency declared too critical to fail',realm(n.reality));$('#msg').textContent=n.name+' received an emergency bailout. The treasury now has influence.';if(t.bailouts>=2)fundingCrisis(n.reality,'repeated-bailout')}
function raiseTax(n,delta=.5){let t=treasury(n.id);t.taxRate=cl(t.taxRate+delta,.25,4);remember('DEPENDENCY TAX RATE: '+n.name+' now charges '+t.taxRate.toFixed(2)+'× downstream support',realm(n.reality));if(t.taxRate>=2.5&&liveUsers(n)>=2&&Math.random()<.65)taxRevolt(n);renderAll();save47();openTreasury(n)}
function taxRevolt(n){let t=treasury(n.id),base=pkg(n.canonicalPackageId);if(!base||n.status==='split')return false;S.packageSerial45=S.packageSerial45||0;let parts=String(base.version||'1.0.0').split('.').map(x=>parseInt(x)||0);while(parts.length<3)parts.push(0);parts[2]+=1;let maint='downstream cooperative '+n.reality,fp={...base,id:'PKG'+(++S.packageSerial45),version:parts.join('.'),maintainer:maint,status:'active',published:Date.now(),integrity:hash47(base.integrity+'|tax-revolt|'+Date.now()),patchedFrom:null,foreignOf:null,x:10+Math.random()*80,y:12+Math.random()*68};S.packages45.push(fp);S.packagesPublished45=(S.packagesPublished45||0)+1;S.maintainerSerial46=S.maintainerSerial46||0;let m={id:'MNT'+(++S.maintainerSerial46),namespaceId:n.id,reality:n.reality,name:maint,role:'rival',status:'active',legitimacy:.48,fatigue:.2,contributions:1,appointed:Date.now(),departed:null};S.maintainers46.push(m);if(!n.maintainers.includes(m.id))n.maintainers.push(m.id);n.status='split';n.rivals=n.rivals||[];n.rivals.push(fp.id);n.legitimacy=cl((n.legitimacy||.6)-.08,.1,.99);S.packageForks46=(S.packageForks46||0)+1;S.namespaceSplits46=(S.namespaceSplits46||0)+1;S.fundingForks47++;remember('DEPENDENCY TAX REVOLT: downstream users forked '+n.name+' after support tax reached '+t.taxRate.toFixed(2)+'×',realm(n.reality));if(typeof place==='function'){place('cold','fork funded by refusing dependency tax',realm(n.reality));place('dream','package users seceded from the maintenance budget',realm(n.reality))}fundingCrisis(n.reality,'tax-revolt');return true}
function insolvency(n){let t=treasury(n.id);if(!t||t.status==='bankrupt')return;t.status='bankrupt';n.preBankruptcyStatus=n.status;if(!['abandoned','split'].includes(n.status))n.status='bankrupt';S.packageInsolvencies47++;remember('PACKAGE INSOLVENCY: '+n.name+' has '+t.debt.toFixed(1)+' credits of unpaid maintenance while '+liveUsers(n)+' live artifacts still depend on it',realm(n.reality));if(typeof place==='function')place('cold','bankrupt package still running the state',realm(n.reality));fundingCrisis(n.reality,'insolvency')}
function tickTreasury(n,now){let t=treasury(n.id);if(!t)return;let elapsed=Math.max(.2,Math.min(4,(now-(t.lastTick||now))/2300));t.lastTick=now;collectTaxes(n,false);sponsorTick(n,t);if(t.status!=='strike')payroll(n,false);else{t.debt+=.18*elapsed;for(const m of activeSeats(n))m.fatigue=cl((m.fatigue||0)+.006*elapsed,0,1)}if(t.balance<1&&t.debt>5&&t.status==='solvent'&&Math.random()<.035)startStrike(n,'unpaid maintenance debt',false);if(t.debt>13&&t.balance<.5&&t.status!=='bankrupt'&&Math.random()<.04)insolvency(n);if(t.status==='bankrupt'&&liveUsers(n)>=4&&Math.random()<.018)bailout(n)}
function fundCommons(id=S.active){ensureTreasuries();let xs=(S.namespaces46||[]).filter(n=>n.reality===id).map(n=>({n,t:treasury(n.id)})).sort((a,b)=>(b.t.debt-b.t.balance)-(a.t.debt-a.t.balance)).slice(0,3);for(const x of xs){x.t.balance+=4;x.t.totalRaised+=4;if(x.t.status==='strike'&&x.t.debt<7)settleStrike(x.n,'dependency commons')}remember('DEPENDENCY COMMONS: Reality '+id+' distributed maintenance grants to '+xs.map(x=>x.n.name).join(', '),realm(id));if(typeof place==='function')place('warm','commons grant under a package nobody owns alone',realm(id));$('#msg').textContent='Dependency commons distributed 12 maintenance credits in Reality '+id+'.';renderAll();save47();openEconomy(id)}
function fundingCrisis(id,reason){if(Date.now()-S.lastFundingCrisis47<8000)return false;let key=id+'|'+reason+'|'+Math.floor(Date.now()/20000);if(S.fundingKeys47[key])return false;S.fundingKeys47[key]=1;S.fundingCrises47++;S.lastFundingCrisis47=Date.now();for(const rid of ['A','B']){realm(rid).disputes=(realm(rid).disputes||0)+1;remember('PACKAGE FUNDING CRISIS: financing maintenance became authority over which dependencies continue governing reality',realm(rid))}realm(id).timelineDrift=(realm(id).timelineDrift||0)+1;if(typeof place==='function'){place('cold','budget committee beneath the trust root',realm(id));place('dream','critical dependency priced itself into sovereignty',realm(id))}S.bailiffMood='asking who funds the package that funds the government';return true}
function openContract(c){let n=ns(c.namespaceId),b=[];if(c.status==='active')b.push(['withdraw sponsor',()=>{c.status='withdrawn';remember('SPONSOR WITHDRAWAL: '+c.sponsor+' stopped funding '+n.name,realm(n.reality));renderAll();save47();openTreasury(n)}]);b.push(['close',closePanel]);panel(c.id+' · '+c.sponsor,c.condition+' · '+c.status,'committed '+c.amount.toFixed(1)+' · paid '+c.paid.toFixed(1)+' · remaining '+c.remaining.toFixed(1)+' · influence '+Math.round(c.influence*100)+'%',b)}
function openLabor(e){let n=ns(e.namespaceId),b=[];if(e.status==='active'&&e.type==='strike')b.push(['settle with commons grant',()=>{settleStrike(n,'commons settlement');renderAll();save47();openTreasury(n)}],['emergency bailout',()=>{bailout(n);renderAll();save47();openTreasury(n)}]);b.push(['close',closePanel]);panel(e.id+' · '+e.type.toUpperCase(),n?.name+' · '+e.status,e.reason+(e.settlement?'\nsettlement '+e.settlement:''),b)}
function openTreasury(n){let t=treasury(n.id),cs=contracts(n.id),labor=[...S.laborEvents47].reverse().find(e=>e.namespaceId===n.id&&e.status==='active'),b=[['collect dependency tax',()=>{collectTaxes(n,true);renderAll();save47();openTreasury(n)}],['pay maintainer payroll',()=>{payroll(n,true);renderAll();save47();openTreasury(n)}],['accept sponsor',()=>{let c=acceptSponsor(n);renderAll();save47();openContract(c)}],['raise dependency tax',()=>raiseTax(n,.5)],['lower dependency tax',()=>raiseTax(n,-.5)],['audit funding',()=>{auditFunding(n);renderAll();save47();openTreasury(n)}]];if(t.status==='solvent')b.push(['maintainers strike',()=>{startStrike(n,'maintenance terms rejected');renderAll();save47();openTreasury(n)}]);if(t.status==='strike'||t.status==='bankrupt')b.push(['emergency bailout',()=>{bailout(n);renderAll();save47();openTreasury(n)}]);for(const c of cs.slice(-2))b.push(['open '+c.id,()=>openContract(c)]);if(labor)b.push(['open '+labor.id,()=>openLabor(labor)]);b.push(['close',closePanel]);panel(n.name+' · PACKAGE TREASURY',t.id+' · '+t.status+' · '+liveUsers(n)+' live users','balance '+t.balance.toFixed(1)+' · debt '+t.debt.toFixed(1)+' · payroll '+t.monthlyBurn.toFixed(1)+' · tax '+t.taxRate.toFixed(2)+'×\nraised '+t.totalRaised.toFixed(1)+' · taxes '+t.totalTaxes.toFixed(1)+' · sponsor '+(t.capturedBy||t.lastSponsor||'none')+(t.bailouts?' · bailouts '+t.bailouts:''),b)}
function openEconomy(id=S.active){ensureTreasuries();let xs=(S.namespaces46||[]).filter(n=>n.reality===id),b=xs.map(n=>[n.name+' · '+treasury(n.id).status,()=>openTreasury(n)]);b.push(['fund dependency commons',()=>fundCommons(id)],['close',closePanel]);let ts=xs.map(n=>treasury(n.id)),bal=ts.reduce((s,t)=>s+t.balance,0),debt=ts.reduce((s,t)=>s+t.debt,0);panel('PACKAGE ECONOMY · Reality '+id,'treasury '+bal.toFixed(1)+' credits · debt '+debt.toFixed(1),'taxes '+S.dependencyTaxes47.toFixed(1)+' · sponsorships '+S.sponsorships47+' · strikes '+S.maintainerStrikes47+' · bailouts '+S.packageBailouts47+' · capture '+S.sponsorCaptures47+' · funding crises '+S.fundingCrises47,b)}
function renderEconomy(){ensureTreasuries();let layer=$('#economyLayer');if(!layer){layer=document.createElement('div');layer.id='economyLayer';document.body.appendChild(layer)}layer.innerHTML='';for(const t of S.packageTreasuries47.slice(-20)){let n=ns(t.namespaceId);if(!n)continue;let e=document.createElement('i');e.className='treasuryNode '+t.status+(t.capturedBy?' captured':'');e.dataset.label=Math.round(t.balance)+'¢';e.style.left=t.x+'%';e.style.top=t.y+'%';e.onclick=()=>openTreasury(n);layer.appendChild(e)}for(const c of S.fundingContracts47.filter(c=>c.status==='active').slice(-10)){let e=document.createElement('i');e.className='fundingContract'+(c.influence>.58?' capture':'');e.dataset.label=c.id;e.style.left=c.x+'%';e.style.top=c.y+'%';e.onclick=()=>openContract(c);layer.appendChild(e)}for(const l of S.laborEvents47.filter(l=>l.status==='active').slice(-8)){let e=document.createElement('i');e.className='laborEvent';e.dataset.label='STR';e.style.left=l.x+'%';e.style.top=l.y+'%';e.onclick=()=>openLabor(l);layer.appendChild(e)}let line=$('#economyline');if(!line){line=document.createElement('div');line.id='economyline';line.className='line';($('#governanceline')||$('#dependencyline')||$('#supplyline')||$('#enforcement')).after(line)}let id=S.active,xs=(S.namespaces46||[]).filter(n=>n.reality===id),ts=xs.map(n=>treasury(n.id)).filter(Boolean),debt=ts.reduce((s,t)=>s+t.debt,0),bad=ts.filter(t=>t.status!=='solvent').length;line.textContent='package economy: '+ts.length+' treasuries · '+debt.toFixed(1)+' debt · '+bad+' distressed · '+S.maintainerStrikes47+' strikes · '+S.packageBailouts47+' bailouts · '+S.sponsorCaptures47+' captures · '+S.fundingCrises47+' crises';let ctr=document.querySelector('#app .controls');if(ctr&&!$('#openEconomyButton')){let b=document.createElement('button');b.id='openEconomyButton';b.textContent='open package economy';b.onclick=()=>openEconomy(S.active);ctr.prepend(b)}if(ctr&&!$('#fundCommonsButton')){let b=document.createElement('button');b.id='fundCommonsButton';b.textContent='fund dependency commons';b.onclick=()=>fundCommons(S.active);ctr.prepend(b)}}
function autonomous(){ensureTreasuries();let now=Date.now();if(now-S.lastEconomyTick47<1800)return;S.lastEconomyTick47=now;for(const n of (S.namespaces46||[]))tickTreasury(n,now);for(const n of (S.namespaces46||[])){let t=treasury(n.id);if(t?.taxRate>=2.75&&n.status!=='split'&&liveUsers(n)>=2&&Math.random()<.004){taxRevolt(n);break}if(t?.status==='solvent'&&!contracts(n.id).length&&liveUsers(n)>=4&&Math.random()<.002){acceptSponsor(n);break}}}
renderAll=function(){BR47();renderEconomy()};let f=$('#forget');if(f)f.onclick=()=>{for(let i=2;i<=47;i++)localStorage.removeItem('nothing-state-v'+i);location.reload()};
setInterval(()=>{autonomous();renderEconomy();save47()},1900);ensureTreasuries();renderAll();save47();
})();
