(()=>{
const B85=save,R85=renderAll,O=JSON.parse(localStorage.getItem('nothing-state-v85')||'null')||{},RECOVER85=!Array.isArray(O.fundingCrossDefaults85),K=['fundingCrossDefaultOffice85','fundingCrossDefaults85','fundingCrossDefaultSerial85','fundingCrossDefaultsTriggered85','fundingCrossDefaultsResolved85','fundingCrossDefaultMarginSeized85','fundingCrossDefaultCarryProceeds85','fundingCrossDefaultPrincipalRetired85','fundingCrossDefaultInterestPaid85','fundingCrossDefaultDeficiency85','fundingCrossDefaultEquityResidual85','fundingCrossDefaultCallsCured85','fundingCrossDefaultCrises85','fundingCrossDefaultKeys85','lastFundingCrossDefaultTick85'];
for(const k of K)S[k]=O[k]??(/Serial|Triggered|Resolved|Seized|Proceeds|Retired|Paid|Deficiency|Residual|Cured|Crises|Tick/.test(k)?0:/Keys/.test(k)?{}:/Office/.test(k)?null:[]);
function save85(){B85();let o={};for(const k of K)o[k]=S[k];localStorage.setItem('nothing-state-v85',JSON.stringify(o))}save=save85;
const q=s=>$(s),realm=id=>S.real[id],position=id=>(S.sterilizationCarryPositions79||[]).find(x=>x.id===id),facility=id=>(S.liquidityFacilities55||[]).find(x=>x.id===id),authority=id=>(S.monetaryAuthorities55||[]).find(x=>x.id===id),cl=(v,a,b)=>Math.max(a,Math.min(b,v));
function trust(id,status,note){S.trustAudits=S.trustAudits||[];S.trustAuditSerial=S.trustAuditSerial||0;S.trustAudits.push({id:'TA'+(++S.trustAuditSerial),reality:id,status,created:Date.now(),note,x:10+Math.random()*80,y:12+Math.random()*68})}
function incident(id,title,sev='SEV1'){S.incidents=S.incidents||[];S.incidentSerial=S.incidentSerial||0;let ex=S.incidents.find(x=>x.reality===id&&x.title===title&&x.status==='open');if(ex)return ex;let i={id:'INC'+(++S.incidentSerial),reality:id,title,severity:sev,status:'open',started:Date.now(),owner:'funding-chain cross-default office',x:10+Math.random()*80,y:12+Math.random()*68};S.incidents.push(i);return i}
function crisis(id,why,sev='SEV1'){let n=Date.now(),k=id+'|'+why;if(S.fundingCrossDefaultKeys85[k]&&n-S.fundingCrossDefaultKeys85[k]<14000)return;S.fundingCrossDefaultKeys85[k]=n;S.fundingCrossDefaultCrises85++;remember('FUNDING CROSS-DEFAULT CRISIS: '+why+' turned a failed netting call into a chain-wide liquidation event',realm(id));if(typeof place==='function'){place('cold','one failed central-bank collateral call accelerating every public loan funding the same carry',realm(id));place('dream','the carry margin and FX position becoming a bankruptcy estate for their own funding chain',realm(id))}incident(id,'funding-chain cross-default crisis: '+why,sev)}
function ensure(){if(!S.collateralNettingOffice84||!S.fundingNovationOffice83)return null;if(!S.fundingCrossDefaultOffice85){S.fundingCrossDefaultOffice85={id:'XDO1',name:'Interreality Funding-Chain Cross-Default Office',status:'accelerating',created:Date.now(),x:50,y:86};remember('FUNDING CROSS-DEFAULT XDO1: failed aggregate collateral calls acquired chain-wide acceleration',realm('A'));remember('FUNDING CROSS-DEFAULT XDO1: failed aggregate collateral calls acquired chain-wide acceleration',realm('B'));trust('A','funding-chain-cross-default-created','XDO1');trust('B','funding-chain-cross-default-created','XDO1')}return S.fundingCrossDefaultOffice85}
function borrower(f){if(!f)return null;if(f.borrowerType==='dealer'){let o=(S.derivativeDealers53||[]).find(x=>x.id===f.borrowerId);return o?{obj:o,cashField:'capital'}:null}if(f.borrowerType==='ccp'){let o=(S.clearinghouses54||[]).find(x=>x.id===f.borrowerId);return o?{obj:o,cashField:'liquidity'}:null}if(f.borrowerType==='insurer'){let o=(S.insurers51||[]).find(x=>x.id===f.borrowerId);return o?{obj:o,cashField:'capital'}:null}if(f.borrowerType==='treasury'){let o=(S.packageTreasuries47||[]).find(x=>x.namespaceId===f.borrowerId);return o?{obj:o,cashField:'balance'}:null}return null}
function cash(b){return Math.max(0,b?.obj?.[b.cashField]||0)}
function addCash(b,x){if(b)b.obj[b.cashField]=Math.max(0,(b.obj[b.cashField]||0)+x)}
function liveBeforeDefault(p){return p&&['open','rollover-risk','open-permanent-money'].includes(p.status)}
function chainFacilities(p){let seen=new Set(),xs=[];for(const f of(S.liquidityFacilities55||[])){if(f.status!=='active'||(f.principal||0)<=.01)continue;let linked=f.id===p.facilityId55||f.id===p.fundingOriginFacility83||f.carryPosition79===p.id||f.carryPosition79Novated83===p.id||(f.marginRefinance82&&f.positionId79===p.id);if(linked&&!seen.has(f.id)){seen.add(f.id);xs.push(f)}}return xs.sort((a,b)=>(a.issued||0)-(b.issued||0)||String(a.id).localeCompare(String(b.id)))}
function market(){return S.fxMarkets56?.[0]||null}
function fund(){return S.stabilizationFunds58?.[0]||null}
function mark(p){let r=Math.max(.18,market()?.rate||p.entryRate||1),value=p.reality==='B'?(p.foreignUnits||0)*r:(p.foreignUnits||0)/r,pnl=value-(p.domesticDeployed||0);return{rate:r,value,pnl}}
function fxCloseMove(p,notionalRB){let m=market(),f=fund();if(!m||notionalRB<=.001)return 0;let value=(f?.poolRA||0)*Math.max(.18,m.rate||1)+(f?.poolRB||0),liq=Math.max(20,20+value),impact=Math.min(.035,notionalRB/liq*.055),buyRA=p.reality==='B',sign=(buyRA?1:-1)*-1,before=m.rate;m.previousRate=m.rate;m.rate=cl((m.rate||1)*(1+sign*impact),.18,4.5);m.pressure=(m.pressure||0)+sign*notionalRB*.014;m.turnover=(m.turnover||0)+notionalRB;m.lastMove=Date.now();let move=Math.abs(m.rate-before);S.sterilizationCarryFXImpulse79=(S.sterilizationCarryFXImpulse79||0)+move;return move}
function caseForPosition(id){return(S.fundingCrossDefaults85||[]).find(x=>x.positionId79===id&&['triggered','liquidated-deficiency'].includes(x.status))||null}
function triggerCallForPosition(p){return(S.monetaryCollateralCalls55||[]).filter(c=>c.crossFacilityNetting84&&c.positionId79===p.id&&['failed','forborne'].includes(c.status)).sort((a,b)=>(a.failed||a.forborne||a.issued||0)-(b.failed||b.forborne||b.issued||0))[0]||null}
function freezeMarginCalls(p){let n=0;for(const c of(S.carryMarginCalls80||[]).filter(c=>c.positionId79===p.id&&['open','partial'].includes(c.status))){c.preCrossDefaultStatus85=c.status;c.status='frozen-cross-default85';c.frozenCrossDefault85=true;n++}return n}
function marker(r,p,fs){let snap=JSON.parse(JSON.stringify(r));p.fundingCrossDefaultMarkers85=p.fundingCrossDefaultMarkers85||[];let i=p.fundingCrossDefaultMarkers85.findIndex(x=>x.id===r.id);if(i>=0)p.fundingCrossDefaultMarkers85[i]=snap;else p.fundingCrossDefaultMarkers85.push(snap);p.fundingCrossDefaultLatest85=r.id;for(const f of fs){f.fundingCrossDefaultMarkers85=f.fundingCrossDefaultMarkers85||[];let j=f.fundingCrossDefaultMarkers85.findIndex(x=>x.id===r.id);if(j>=0)f.fundingCrossDefaultMarkers85[j]=snap;else f.fundingCrossDefaultMarkers85.push(snap);f.fundingCrossDefault85=r.id}}
function trigger(p,c){if(!liveBeforeDefault(p)||caseForPosition(p.id))return null;let fs=chainFacilities(p);if(!fs.length)return null;let margin=Math.max(0,p.macroMarginPosted80||0),m=mark(p),r={id:'XDF'+(++S.fundingCrossDefaultSerial85),positionId79:p.id,reality:p.reality,borrower:p.borrower,triggerCallId55:c.id,triggerCallStatus85:c.status,triggerNettingId84:c.nettingId84||null,status:'triggered',facilityIds85:fs.map(f=>f.id),exposureAtTrigger85:fs.reduce((n,f)=>n+Math.max(0,f.principal||0),0),interestAtTrigger85:fs.reduce((n,f)=>n+Math.max(0,f.interestAccrued||0),0),marginEstate85:margin,carryMarkAtTrigger85:m.value,carryRateAtTrigger85:m.rate,marginFrozenCalls85:0,created:Date.now(),x:10+Math.random()*80,y:12+Math.random()*68};p.preCrossDefaultStatus85=p.status;p.status='cross-default85';p.fundingCrossDefault85=r.id;p.crossDefaultMarginSequestered85=margin;p.macroMarginPosted80=0;p.macroMarginReleased80=false;r.marginFrozenCalls85=freezeMarginCalls(p);for(const f of fs){f.crossDefault85=r.id;f.crossDefaultPosition85=p.id;f.crossDefaultTriggeredBy85=c.id;f.crossDefaultPreMaturity85=f.matures;f.macroMarginPosted80=0}S.fundingCrossDefaults85.push(r);S.fundingCrossDefaultsTriggered85++;S.fundingCrossDefaultMarginSeized85+=margin;marker(r,p,fs);remember('FUNDING CROSS-DEFAULT '+r.id+': '+c.id+' '+c.status+' froze '+fs.length+' public facilities and sequestered '+margin.toFixed(2)+' carry margin',realm(p.reality));trust(p.reality,'funding-chain-cross-default-triggered',r.id+' '+c.id);crisis(p.reality,'a Build 84 collateral call '+c.status+' and accelerated the entire carry funding chain','SEV1');return r}
function applyCallCure(f,amount,r){let rem=amount;for(const c of(S.monetaryCollateralCalls55||[]).filter(c=>c.facilityId===f.id&&['open','failed','forborne'].includes(c.status)).sort((a,b)=>(a.issued||0)-(b.issued||0))){if(rem<=.0001)break;let due=Math.max(0,(c.amount||0)-(c.paid||0)-(c.paidCrossDefault85||0));let x=Math.min(rem,due);if(x<=.0001)continue;c.paidCrossDefault85=(c.paidCrossDefault85||0)+x;rem-=x;if(x+1e-9>=due){c.preCrossDefaultStatus85=c.status;c.status='met';c.met=Date.now();c.metByCrossDefault85=true;S.monetaryCollateralCallsMet55=(S.monetaryCollateralCallsMet55||0)+1;S.fundingCrossDefaultCallsCured85++;r.callsCured85=(r.callsCured85||0)+1}}}
function retirePrincipal(f,amount,r){let a=authority(f.authorityId),acct=(S.reserveAccounts55||[]).find(x=>x.borrowerType===f.borrowerType&&x.borrowerId===f.borrowerId),x=Math.min(Math.max(0,f.principal||0),Math.max(0,amount));if(x<=.0001)return 0;f.principal=Math.max(0,(f.principal||0)-x);if(a){a.monetaryBase=Math.max(0,(a.monetaryBase||0)-x);a.outstandingCredit=Math.max(0,(a.outstandingCredit||0)-x)}if(acct)acct.balance=Math.max(0,(acct.balance||0)-x);S.reservesExtinguished55=(S.reservesExtinguished55||0)+x;applyCallCure(f,x,r);if(f.principal<=.01&&Math.max(0,f.interestAccrued||0)<=.01){f.principal=0;f.interestAccrued=0;f.status='repaid';f.repaid=Date.now();f.repaidByCrossDefault85=true}return x}
function payInterest(f,amount){let a=authority(f.authorityId),x=Math.min(Math.max(0,f.interestAccrued||0),Math.max(0,amount));if(x<=.0001)return 0;f.interestAccrued=Math.max(0,(f.interestAccrued||0)-x);if(a)a.capital=(a.capital||0)+x;if(f.principal<=.01&&f.interestAccrued<=.01){f.principal=0;f.interestAccrued=0;f.status='repaid';f.repaid=Date.now();f.repaidByCrossDefault85=true}return x}
function resolve(r,manual=false){if(!r||r.status!=='triggered')return null;let p=position(r.positionId79),fs=(r.facilityIds85||[]).map(facility).filter(f=>f&&f.status==='active'&&(f.principal||0)>.01);if(!p)return null;let m=mark(p),proceeds=Math.max(0,m.value),notionalRB=p.reality==='B'?proceeds:proceeds*m.rate,exitMove=fxCloseMove(p,notionalRB),pool=Math.max(0,r.marginEstate85||0)+proceeds,totalPrincipal=fs.reduce((n,f)=>n+Math.max(0,f.principal||0),0),principalPool=Math.min(pool,totalPrincipal),alloc=[],remaining=principalPool,remainingPrincipal=totalPrincipal;
for(let i=0;i<fs.length;i++){let f=fs[i],base=Math.max(0,f.principal||0),share=i===fs.length-1?remaining:(remainingPrincipal>0?principalPool*(base/totalPrincipal):0),x=retirePrincipal(f,Math.min(base,share),r);remaining=Math.max(0,remaining-x);remainingPrincipal=Math.max(0,remainingPrincipal-base);alloc.push({facilityId55:f.id,principalBefore85:base,principalPaid85:x})}
pool=Math.max(0,pool-principalPool);let interestPaid=0;for(const f of fs){if(pool<=.0001)break;let x=payInterest(f,pool);interestPaid+=x;pool-=x}
let deficiency=fs.reduce((n,f)=>n+Math.max(0,f.principal||0)+Math.max(0,f.interestAccrued||0),0),principalDef=fs.reduce((n,f)=>n+Math.max(0,f.principal||0),0),b=borrower(fs[0]||facility(p.facilityId55));if(pool>.0001&&b)addCash(b,pool);
r.status=deficiency>.01?'liquidated-deficiency':'resolved-paid';r.resolved=Date.now();r.carryProceeds85=proceeds;r.exitRate85=m.rate;r.exitImpact85=exitMove;r.principalRetired85=principalPool-remaining;r.interestPaid85=interestPaid;r.deficiency85=deficiency;r.principalDeficiency85=principalDef;r.equityResidual85=pool;r.allocations85=alloc;r.marginEstateUsed85=Math.min(Math.max(0,r.marginEstate85||0),r.principalRetired85+interestPaid);S.fundingCrossDefaultsResolved85++;S.fundingCrossDefaultCarryProceeds85+=proceeds;S.fundingCrossDefaultPrincipalRetired85+=r.principalRetired85;S.fundingCrossDefaultInterestPaid85+=interestPaid;S.fundingCrossDefaultDeficiency85+=deficiency;S.fundingCrossDefaultEquityResidual85+=pool;
let oldBasis=p.domesticDeployed||0;p.exitImpact79=exitMove;p.rateAfterClose79=market()?.rate||m.rate;p.realizedPnl=proceeds-oldBasis;p.exitRate=m.rate;p.closed=Date.now();p.closedByCrossDefault85=true;p.crossDefaultOutcome85=r.status;p.crossDefaultDeficiency85=deficiency;p.status='closed';S.sterilizationCarryClosed79=(S.sterilizationCarryClosed79||0)+1;S.sterilizationCarryRealizedPnl79=(S.sterilizationCarryRealizedPnl79||0)+p.realizedPnl;for(const f of(r.facilityIds85||[]).map(facility).filter(Boolean)){if(f.carryPosition79===p.id){f.carryStatus79='closed';f.carryClosedAt79=p.closed;f.carryRealizedPnl79=p.realizedPnl;f.carryExitImpact79=exitMove;f.carryRateAfterClose79=p.rateAfterClose79}if(f.status==='active'&&(f.principal||0)>.01){f.crossDefaultDeficiency85=f.principal||0;f.crossDefaultAccelerated85=true;f.matures=Date.now()}}
for(const c of(S.carryMarginCalls80||[]).filter(c=>c.positionId79===p.id&&c.status==='frozen-cross-default85')){c.status='cancelled-cross-default85';c.cancelledCrossDefault85=r.id}
marker(r,p,(r.facilityIds85||[]).map(facility).filter(Boolean));remember('CROSS-DEFAULT LIQUIDATION '+r.id+': margin plus FX liquidation retired '+r.principalRetired85.toFixed(2)+' public principal and left '+deficiency.toFixed(2)+' deficiency',realm(p.reality));trust(p.reality,'funding-chain-cross-default-resolved',r.id+' '+r.status);if(deficiency>.01)crisis(p.reality,'cross-default liquidation exhausted the carry estate with '+deficiency.toFixed(2)+' public debt still outstanding','SEV1');if(manual){q('#msg').textContent=r.id+' '+r.status.toUpperCase()+' · principal retired '+r.principalRetired85.toFixed(2)+' · deficiency '+deficiency.toFixed(2)+'.';renderAll();save85();openCase(r)}return r}
function reconstruct(){if(!RECOVER85)return false;let changed=false,seen=new Set();for(const f of(S.liquidityFacilities55||[])){for(const m of(f.fundingCrossDefaultMarkers85||[])){if(seen.has(m.id)||(S.fundingCrossDefaults85||[]).some(x=>x.id===m.id))continue;seen.add(m.id);let r=JSON.parse(JSON.stringify(m));r.recovered=true;S.fundingCrossDefaults85.push(r);S.fundingCrossDefaultsTriggered85++;S.fundingCrossDefaultMarginSeized85+=r.marginEstate85||0;if(r.status!=='triggered'){S.fundingCrossDefaultsResolved85++;S.fundingCrossDefaultCarryProceeds85+=r.carryProceeds85||0;S.fundingCrossDefaultPrincipalRetired85+=r.principalRetired85||0;S.fundingCrossDefaultInterestPaid85+=r.interestPaid85||0;S.fundingCrossDefaultDeficiency85+=r.deficiency85||0;S.fundingCrossDefaultEquityResidual85+=r.equityResidual85||0;S.fundingCrossDefaultCallsCured85+=r.callsCured85||0}let n=Number(String(r.id).replace(/\D/g,''))||0;if(n>S.fundingCrossDefaultSerial85)S.fundingCrossDefaultSerial85=n;changed=true}}return changed}
function reconcile(){if(!ensure())return false;let changed=reconstruct();for(const p of(S.sterilizationCarryPositions79||[]).filter(liveBeforeDefault)){if(caseForPosition(p.id))continue;let c=triggerCallForPosition(p);if(c){trigger(p,c);changed=true}}return changed}
function openCase(r){let acts=[];if(r.status==='triggered')acts.push(['liquidate carry estate',()=>resolve(r,true)]);for(const id of r.facilityIds85||[]){let f=facility(id);if(f)acts.push([id+' · '+f.status+' · '+(f.principal||0).toFixed(2),()=>panel(id+' · CROSS-DEFAULT FUNDING',f.status.toUpperCase(),f.borrower+' · principal '+(f.principal||0).toFixed(2)+' · interest '+(f.interestAccrued||0).toFixed(3)+(f.crossDefaultDeficiency85?' · deficiency '+f.crossDefaultDeficiency85.toFixed(2):''),[['close',closePanel]])])}acts.push(['close',closePanel]);panel(r.id+' · FUNDING-CHAIN CROSS-DEFAULT',r.status.toUpperCase(),r.borrower+' · trigger '+r.triggerCallId55+' '+r.triggerCallStatus85+' · facilities '+(r.facilityIds85||[]).length+' · margin estate '+(r.marginEstate85||0).toFixed(2)+' · carry proceeds '+(r.carryProceeds85||0).toFixed(2)+' · principal retired '+(r.principalRetired85||0).toFixed(2)+' · deficiency '+(r.deficiency85||0).toFixed(2),acts)}
function openOffice(){if(!ensure())return;let acts=[];for(const r of S.fundingCrossDefaults85.slice(-8))acts.push(['open '+r.id+' · '+r.status,()=>openCase(r)]);acts.push(['close',closePanel]);panel(S.fundingCrossDefaultOffice85.name,'ACCELERATING · XDO1',S.fundingCrossDefaultsTriggered85+' cross-defaults · '+S.fundingCrossDefaultsResolved85+' resolved · '+S.fundingCrossDefaultMarginSeized85.toFixed(2)+' margin sequestered · '+S.fundingCrossDefaultPrincipalRetired85.toFixed(2)+' principal retired · '+S.fundingCrossDefaultDeficiency85.toFixed(2)+' deficiency',acts)}
function render85(){if(!ensure())return;let layer=q('#fundingCrossDefaultLayer85');if(!layer){layer=document.createElement('div');layer.id='fundingCrossDefaultLayer85';document.body.appendChild(layer)}layer.innerHTML='';let o=document.createElement('i');o.className='fundingCrossDefaultOffice85';o.dataset.label='XD';o.style.left='50%';o.style.top='86%';o.onclick=openOffice;layer.appendChild(o);for(const r of S.fundingCrossDefaults85.filter(x=>x.status!=='resolved-paid').slice(-8)){let e=document.createElement('i');e.className='fundingCrossDefault85 '+r.status;e.dataset.label='X!';e.style.left=r.x+'%';e.style.top=r.y+'%';e.onclick=()=>openCase(r);layer.appendChild(e)}let line=q('#fundingcrossdefaultline85');if(!line){line=document.createElement('div');line.id='fundingcrossdefaultline85';line.className='line';(q('#crossfacilitynettingline84')||q('#fundingnovationline83')||q('#monetaryline')||q('#enforcement')).after(line)}line.textContent='funding cross-default: '+S.fundingCrossDefaultsTriggered85+' events · '+S.fundingCrossDefaultPrincipalRetired85.toFixed(1)+' principal retired · '+S.fundingCrossDefaultDeficiency85.toFixed(1)+' deficiency';let ctr=document.querySelector('#app .controls');if(ctr&&!q('#openFundingCrossDefault85')){let x=document.createElement('button');x.id='openFundingCrossDefault85';x.textContent='open funding cross-default';x.onclick=openOffice;ctr.prepend(x)}}
renderAll=function(){R85();let changed=reconcile();render85();if(changed)save85()};let f=q('#forget');if(f)f.onclick=()=>{for(let i=2;i<=85;i++)localStorage.removeItem('nothing-state-v'+i);location.reload()};setInterval(()=>{reconcile();render85();save85()},2300);ensure();reconcile();renderAll();save85();
})();