(()=>{
const B83=save,R83=renderAll,O=JSON.parse(localStorage.getItem('nothing-state-v83')||'null')||{},RECOVER83=!Array.isArray(O.fundingNovations83),K=['fundingNovationOffice83','fundingNovations83','fundingNovationSerial83','fundingNovationsExecuted83','fundingNovationMarginRecalled83','fundingNovationRecallShortfall83','fundingNovationMarkersMoved83','fundingNovationContinuations83','fundingNovationCrises83','fundingNovationKeys83','lastFundingNovationTick83'];
for(const k of K)S[k]=O[k]??(/Serial|Executed|Recalled|Shortfall|Moved|Continuations|Crises|Tick/.test(k)?0:/Keys/.test(k)?{}:/Office/.test(k)?null:[]);
function save83(){B83();let o={};for(const k of K)o[k]=S[k];localStorage.setItem('nothing-state-v83',JSON.stringify(o))}save=save83;
const q=s=>$(s),realm=id=>S.real[id],position=id=>(S.sterilizationCarryPositions79||[]).find(x=>x.id===id),facility=id=>(S.liquidityFacilities55||[]).find(x=>x.id===id),cl=(v,a,b)=>Math.max(a,Math.min(b,v));
function trust(id,status,note){S.trustAudits=S.trustAudits||[];S.trustAuditSerial=S.trustAuditSerial||0;S.trustAudits.push({id:'TA'+(++S.trustAuditSerial),reality:id,status,created:Date.now(),note,x:10+Math.random()*80,y:12+Math.random()*68})}
function incident(id,title,sev='SEV1'){S.incidents=S.incidents||[];S.incidentSerial=S.incidentSerial||0;let ex=S.incidents.find(x=>x.reality===id&&x.title===title&&x.status==='open');if(ex)return ex;let i={id:'INC'+(++S.incidentSerial),reality:id,title,severity:sev,status:'open',started:Date.now(),owner:'carry funding novation office',x:10+Math.random()*80,y:12+Math.random()*68};S.incidents.push(i);return i}
function crisis(id,why,sev='SEV1'){let n=Date.now(),k=id+'|'+why;if(S.fundingNovationKeys83[k]&&n-S.fundingNovationKeys83[k]<14000)return;S.fundingNovationKeys83[k]=n;S.fundingNovationCrises83++;remember('FUNDING NOVATION CRISIS: '+why+' made the FX carry outlive the facility that originally funded it',realm(id));if(typeof place==='function'){place('cold','carry funding surviving by moving from a repaid sterilization loan into its refinancing descendants',realm(id));place('dream','the loan died but the leverage contract found another public balance sheet to inhabit',realm(id))}incident(id,'carry funding novation crisis: '+why,sev)}
function ensure(){if(!S.marginRefinanceOffice82||!S.sterilizationCarryOffice79)return null;if(!S.fundingNovationOffice83){S.fundingNovationOffice83={id:'FNO1',name:'Interreality Carry Funding Novation Office',status:'novating',created:Date.now(),x:50,y:90};remember('FUNDING NOVATION FNO1: margin refinancing acquired a transferable funding anchor',realm('A'));remember('FUNDING NOVATION FNO1: margin refinancing acquired a transferable funding anchor',realm('B'));trust('A','carry-funding-novation-created','FNO1');trust('B','carry-funding-novation-created','FNO1')}return S.fundingNovationOffice83}
function borrower(f){if(!f)return null;if(f.borrowerType==='dealer'){let o=(S.derivativeDealers53||[]).find(x=>x.id===f.borrowerId);return o?{obj:o,cashField:'capital'}:null}if(f.borrowerType==='ccp'){let o=(S.clearinghouses54||[]).find(x=>x.id===f.borrowerId);return o?{obj:o,cashField:'liquidity'}:null}if(f.borrowerType==='insurer'){let o=(S.insurers51||[]).find(x=>x.id===f.borrowerId);return o?{obj:o,cashField:'capital'}:null}if(f.borrowerType==='treasury'){let o=(S.packageTreasuries47||[]).find(x=>x.namespaceId===f.borrowerId);return o?{obj:o,cashField:'balance'}:null}return null}
function cash(b){return Math.max(0,b?.obj?.[b.cashField]||0)}
function addCash(b,x){if(b)b.obj[b.cashField]=Math.max(0,(b.obj[b.cashField]||0)+x)}
function mark(p){let r=Math.max(.18,S.fxMarkets56?.[0]?.rate||p.entryRate||1),value=p.reality==='B'?(p.foreignUnits||0)*r:(p.foreignUnits||0)/r,pnl=value-(p.domesticDeployed||0);return{rate:r,value,pnl,returnPct:(p.domesticDeployed||0)>.001?pnl/p.domesticDeployed:0}}
function marginRate(p){let m=mark(p),r=.20;if(p.status==='rollover-risk')r+=.15;if(p.status==='open-permanent-money')r+=.20;if(m.returnPct<0)r+=Math.min(.20,-m.returnPct*.8);return Math.min(.55,r)}
function requirement(p){return Math.max(0,(p.domesticDeployed||0)*marginRate(p))}
function liveCarry(p){return p&&['open','rollover-risk','open-permanent-money'].includes(p.status)}
function candidates(p){return(S.liquidityFacilities55||[]).filter(f=>f.marginRefinance82&&f.positionId79===p.id&&['active','monetized'].includes(f.status)&&(f.principal||0)>.01).sort((a,b)=>{let ra=a.status==='active'?0:1,rb=b.status==='active'?0:1;return ra-rb||(a.issued||0)-(b.issued||0)||String(a.id).localeCompare(String(b.id))})}
function copyCarryMarker(p,from,to,r){for(const f of(S.liquidityFacilities55||[])){if(f.id===to.id)continue;if(f.carryPosition79===p.id){f.carryPosition79Novated83=p.id;f.carryNovatedTo83=to.id;delete f.carryPosition79;S.fundingNovationMarkersMoved83++}}to.carryPosition79=p.id;to.sterilizationId78=p.sterilizationId78||to.sterilizationId78;to.sourceRebalance77=p.sourceRebalance77||to.sourceRebalance77;to.carryDomestic79=p.domesticDeployed||0;to.carryForeignUnits79=p.foreignUnits||0;to.carryEntryRate79=p.entryRate||1;to.carryOpenedAt79=p.opened||to.issued||Date.now();to.carryStatus79=p.status;to.carryDomesticCode79=p.domesticCode;to.carryForeignCode79=p.foreignCode;to.carryEntryImpact79=p.entryImpact79||0;to.carryExitImpact79=p.exitImpact79||0;to.carryRolloverRecorded79=!!p.rolloverRecorded79;to.carryPermanentMoneyRecorded79=!!p.permanentMoneyRecorded79;to.carryLossEvent79=!!p.lossEvent79;to.fundingNovation83=r.id;to.fundingOriginFacility83=p.fundingOriginFacility83||from?.id||p.facilityId55;if(from){from.carryPosition79Novated83=p.id;from.carryNovatedTo83=to.id}return true}
function recallReleased(p,to,r){if(!p.macroMarginReleased80)return 0;let b=borrower(to),need=Math.max(0,requirement(p)-Math.max(0,p.macroMarginPosted80||0)),historical=Math.max(0,p.macroMarginReturned80||0),x=Math.min(need,historical,cash(b));r.releasedMarginDetected83=historical;r.marginRequirement83=requirement(p);if(x>.001){addCash(b,-x);p.macroMarginPosted80=Math.max(0,p.macroMarginPosted80||0)+x;to.macroMarginPosted80=p.macroMarginPosted80;S.carryMarginPosted80=(S.carryMarginPosted80||0)+x;S.fundingNovationMarginRecalled83+=x;r.marginRecalled83=x;remember('NOVATION MARGIN RECALL '+r.id+': '+p.borrower+' returned '+x.toFixed(2)+' of prematurely released carry margin to the live funding chain',realm(p.reality))}p.macroMarginReleased80=false;to.macroMarginReleased80=false;r.marginRecallShortfall83=Math.max(0,need-x);if(r.marginRecallShortfall83>.01){S.fundingNovationRecallShortfall83+=r.marginRecallShortfall83;crisis(p.reality,'funding novation found released margin that could not be fully recalled','SEV2')}return x}
function marker(r,p,to){let snap=JSON.parse(JSON.stringify(r));p.fundingNovationMarkers83=p.fundingNovationMarkers83||[];p.fundingNovationMarkers83.push(snap);p.fundingNovationLatest83=r.id;to.fundingNovationMarkers83=to.fundingNovationMarkers83||[];to.fundingNovationMarkers83.push(snap)}
function reconstruct(){if(!RECOVER83)return false;let changed=false,seen=new Set();for(const f of(S.liquidityFacilities55||[])){for(const m of(f.fundingNovationMarkers83||[])){if(seen.has(m.id)||(S.fundingNovations83||[]).some(x=>x.id===m.id))continue;seen.add(m.id);let r=JSON.parse(JSON.stringify(m));r.recovered=true;S.fundingNovations83.push(r);S.fundingNovationsExecuted83++;S.fundingNovationMarginRecalled83+=r.marginRecalled83||0;S.fundingNovationRecallShortfall83+=r.marginRecallShortfall83||0;if(r.toFacility55)S.fundingNovationContinuations83++;let n=Number(String(r.id).replace(/\D/g,''))||0;if(n>S.fundingNovationSerial83)S.fundingNovationSerial83=n;let p=position(r.positionId79),to=facility(r.toFacility55);if(p&&to&&liveCarry(p)&&(!facility(p.facilityId55)||facility(p.facilityId55)?.status==='repaid'))p.facilityId55=to.id;changed=true}}return changed}
function novate(p,to,manual=false){if(!liveCarry(p)||!to)return null;let from=facility(p.facilityId55);if(from?.id===to.id)return null;let r={id:'FNV'+(++S.fundingNovationSerial83),positionId79:p.id,fromFacility55:from?.id||p.facilityId55||null,toFacility55:to.id,reality:p.reality,borrower:p.borrower,fromStatus:from?.status||'missing',toStatus:to.status,marginBefore83:Math.max(0,p.macroMarginPosted80||0),marginRecalled83:0,marginRecallShortfall83:0,created:Date.now(),x:10+Math.random()*80,y:12+Math.random()*68};p.fundingOriginFacility83=p.fundingOriginFacility83||from?.id||p.facilityId55;p.facilityId55=to.id;p.fundingCurrentFacility83=to.id;p.fundingNovationIds83=p.fundingNovationIds83||[];p.fundingNovationIds83.push(r.id);copyCarryMarker(p,from,to,r);recallReleased(p,to,r);r.marginAfter83=Math.max(0,p.macroMarginPosted80||0);r.borrowerCashAfter83=cash(borrower(to));S.fundingNovations83.push(r);S.fundingNovationsExecuted83++;S.fundingNovationContinuations83++;marker(r,p,to);remember('FUNDING NOVATION '+r.id+': '+p.id+' moved from '+(r.fromFacility55||'missing')+' to '+to.id+' while the FX carry remained '+p.status,realm(p.reality));trust(p.reality,'carry-funding-novated',r.id+' '+(r.fromFacility55||'missing')+'→'+to.id);if(typeof place==='function'){place('cold','repaid public loan replaced as the legal funding anchor by its refinancing descendant',realm(p.reality));place('dream','carry leverage surviving the death of its original loan through funding novation',realm(p.reality))}if(manual){q('#msg').textContent=r.id+' moved '+p.id+' funding to '+to.id+'.';renderAll();save83();openNovation(r)}return r}
function reconcile(){if(!ensure())return false;let changed=reconstruct();for(const p of(S.sterilizationCarryPositions79||[]).filter(liveCarry)){let cur=facility(p.facilityId55);if(cur&&['active','monetized'].includes(cur.status))continue;let to=candidates(p)[0];if(to){novate(p,to,false);changed=true}}return changed}
function openNovation(r){let p=position(r.positionId79),to=facility(r.toFacility55),acts=[];if(to)acts.push(['open '+to.id+' funding anchor',()=>panel(to.id+' · NOVATED FUNDING',to.status.toUpperCase(),to.borrower+' · principal '+(to.principal||0).toFixed(2)+' · '+(to.marginRefinance82?'Build 82 margin refinancing':'public facility')+' · carry '+r.positionId79,[['close',closePanel]])]);acts.push(['close',closePanel]);panel(r.id+' · FUNDING NOVATION',r.toStatus.toUpperCase(),r.borrower+' · '+(r.fromFacility55||'missing')+' → '+r.toFacility55+' · carry remained '+(p?.status||'missing')+' · posted margin '+r.marginBefore83.toFixed(2)+'→'+r.marginAfter83.toFixed(2)+' · recalled '+(r.marginRecalled83||0).toFixed(2)+' · recall shortfall '+(r.marginRecallShortfall83||0).toFixed(2),acts)}
function openOffice(){if(!ensure())return;let acts=[];for(const p of(S.sterilizationCarryPositions79||[]).filter(liveCarry)){let cur=facility(p.facilityId55),to=(!cur||!['active','monetized'].includes(cur.status))?candidates(p)[0]:null;if(to)acts.push(['novate '+p.id+' to '+to.id,()=>novate(p,to,true)])}for(const r of S.fundingNovations83.slice(-8))acts.push(['open '+r.id+' · '+r.fromFacility55+'→'+r.toFacility55,()=>openNovation(r)]);acts.push(['close',closePanel]);panel(S.fundingNovationOffice83.name,'NOVATING · FNO1',S.fundingNovationsExecuted83+' novations · '+S.fundingNovationContinuations83+' funding continuations · '+S.fundingNovationMarginRecalled83.toFixed(2)+' margin recalled · '+S.fundingNovationRecallShortfall83.toFixed(2)+' recall shortfall',acts)}
function render83(){if(!ensure())return;let layer=q('#fundingNovationLayer83');if(!layer){layer=document.createElement('div');layer.id='fundingNovationLayer83';document.body.appendChild(layer)}layer.innerHTML='';let o=document.createElement('i');o.className='fundingNovationOffice83';o.dataset.label='NV';o.style.left='50%';o.style.top='90%';o.onclick=openOffice;layer.appendChild(o);for(const r of S.fundingNovations83.slice(-8)){let e=document.createElement('i');e.className='fundingNovation83';e.dataset.label='⇢';e.style.left=r.x+'%';e.style.top=r.y+'%';e.onclick=()=>openNovation(r);layer.appendChild(e)}let line=q('#fundingnovationline83');if(!line){line=document.createElement('div');line.id='fundingnovationline83';line.className='line';(q('#marginrefinanceline82')||q('#marginsetoffline81')||q('#carrymarginline80')||q('#enforcement')).after(line)}line.textContent='funding novation: '+S.fundingNovationsExecuted83+' transfers · '+S.fundingNovationMarginRecalled83.toFixed(1)+' margin recalled · '+S.fundingNovationRecallShortfall83.toFixed(1)+' recall gap';let ctr=document.querySelector('#app .controls');if(ctr&&!q('#openFundingNovation83')){let x=document.createElement('button');x.id='openFundingNovation83';x.textContent='open funding novation';x.onclick=openOffice;ctr.prepend(x)}}
renderAll=function(){let changed=reconcile();R83();render83();if(changed)save83()};let f=q('#forget');if(f)f.onclick=()=>{for(let i=2;i<=83;i++)localStorage.removeItem('nothing-state-v'+i);location.reload()};setInterval(()=>{reconcile();render83();save83()},2300);ensure();reconcile();renderAll();save83();
})();