(()=>{
const BS59=save,BR59=renderAll,O59=JSON.parse(localStorage.getItem('nothing-state-v59')||'null')||{},cl=(v,a,b)=>Math.max(a,Math.min(b,v));
S.fundBoards59=O59.fundBoards59||[];
S.fundDirectors59=O59.fundDirectors59||[];
S.fundMotions59=O59.fundMotions59||[];
S.surveillanceReports59=O59.surveillanceReports59||[];
S.quotaReviews59=O59.quotaReviews59||[];
S.fundBoardSerial59=O59.fundBoardSerial59||0;
S.fundDirectorSerial59=O59.fundDirectorSerial59||0;
S.fundMotionSerial59=O59.fundMotionSerial59||0;
S.surveillanceSerial59=O59.surveillanceSerial59||0;
S.quotaReviewSerial59=O59.quotaReviewSerial59||0;
S.boardVotes59=O59.boardVotes59||0;
S.boardDeadlocks59=O59.boardDeadlocks59||0;
S.boardOverrides59=O59.boardOverrides59||0;
S.quotaSubscriptions59=O59.quotaSubscriptions59||0;
S.quotaReviewsDone59=O59.quotaReviewsDone59||0;
S.surveillanceMissions59=O59.surveillanceMissions59||0;
S.boardConditionalityChanges59=O59.boardConditionalityChanges59||0;
S.boardTranches59=O59.boardTranches59||0;
S.governanceCrises59=O59.governanceCrises59||0;
S.lastGovernanceCrisis59=O59.lastGovernanceCrisis59||0;
S.governanceKeys59=O59.governanceKeys59||{};
S.lastGovernanceTick59=O59.lastGovernanceTick59||Date.now();
function save59(){BS59();localStorage.setItem('nothing-state-v59',JSON.stringify({fundBoards59:S.fundBoards59,fundDirectors59:S.fundDirectors59,fundMotions59:S.fundMotions59,surveillanceReports59:S.surveillanceReports59,quotaReviews59:S.quotaReviews59,fundBoardSerial59:S.fundBoardSerial59,fundDirectorSerial59:S.fundDirectorSerial59,fundMotionSerial59:S.fundMotionSerial59,surveillanceSerial59:S.surveillanceSerial59,quotaReviewSerial59:S.quotaReviewSerial59,boardVotes59:S.boardVotes59,boardDeadlocks59:S.boardDeadlocks59,boardOverrides59:S.boardOverrides59,quotaSubscriptions59:S.quotaSubscriptions59,quotaReviewsDone59:S.quotaReviewsDone59,surveillanceMissions59:S.surveillanceMissions59,boardConditionalityChanges59:S.boardConditionalityChanges59,boardTranches59:S.boardTranches59,governanceCrises59:S.governanceCrises59,lastGovernanceCrisis59:S.lastGovernanceCrisis59,governanceKeys59:S.governanceKeys59,lastGovernanceTick59:S.lastGovernanceTick59}))}save=save59;
const realm=id=>S.real[id],fund=()=>S.stabilizationFunds58?.[0],quota=id=>(S.stabilizationQuotas58||[]).find(q=>q.reality===id),cur=id=>(S.fxCurrencies56||[]).find(c=>c.reality===id),acct=id=>(S.tradeAccounts57||[]).find(a=>a.reality===id),bank=id=>(S.monetaryAuthorities55||[]).find(a=>a.reality===id),program=id=>(S.stabilizationPrograms58||[]).find(p=>p.id===id),other=id=>id==='A'?'B':'A',foreign=id=>'R'+other(id);
function trust59(id,status,note){let accepted=S.trustPolicies?.[id]?.acceptedRoots||[],r=[...(S.trustRoots||[])].filter(x=>accepted.includes(x.id)&&x.status==='active').sort((a,b)=>(b.strength||0)-(a.strength||0))[0];S.trustAudits=S.trustAudits||[];S.trustAuditSerial=S.trustAuditSerial||0;S.trustAudits.push({id:'TA'+(++S.trustAuditSerial),reality:id,remediationId:null,credentialId:null,certificateId:null,rootId:r?.id||null,status,created:Date.now(),note,x:10+Math.random()*80,y:12+Math.random()*68})}
function incident59(id,title,severity='SEV2'){S.incidents=S.incidents||[];let ex=S.incidents.find(i=>i.reality===id&&i.title===title&&i.status==='open');if(ex)return ex;S.incidentSerial=S.incidentSerial||0;let x={id:'INC'+(++S.incidentSerial),reality:id,title,severity,status:'open',alertIds:[],started:Date.now(),acknowledged:null,resolved:null,postmortem:null,owner:'stabilization fund board',x:10+Math.random()*80,y:12+Math.random()*68};S.incidents.push(x);return x}
function ensureBoard(){if(!fund())return null;let b=S.fundBoards59[0];if(!b){b={id:'ISFB'+(++S.fundBoardSerial59),fundId:fund().id,name:'Interreality Stabilization Fund Board',status:'operating',majority:.6,chair:'stabilization staff chair',chairPower:0,deadlocks:0,dominant:null,created:Date.now(),x:50,y:34};S.fundBoards59.push(b);for(const id of ['A','B'])S.fundDirectors59.push({id:'DIR'+(++S.fundDirectorSerial59),boardId:b.id,reality:id,name:'Reality '+id+' executive director',votes:quota(id)?.votes??50,status:'active',created:Date.now(),x:id==='A'?41:59,y:36});remember('STABILIZATION BOARD '+b.id+': quota votes became authority over rescue policy',realm('A'));remember('STABILIZATION BOARD '+b.id+': quota votes became authority over rescue policy',realm('B'));trust59('A','interreality-stabilization-board-created',b.id+' quota-weighted board');trust59('B','interreality-stabilization-board-created',b.id+' quota-weighted board')}recalcDirectors(false);return b}
function board(){return ensureBoard()}
function director(id){return S.fundDirectors59.find(d=>d.reality===id)}
function activePrograms(id){return (S.stabilizationPrograms58||[]).filter(p=>p.reality===id&&['active','off-track','funding-shortfall'].includes(p.status))}
function exposure(id){return (S.stabilizationPrograms58||[]).filter(p=>p.reality===id).reduce((n,p)=>n+(p.disbursed||0),0)}
function scoreQuota(id){let q=quota(id),c=cur(id),a=acct(id),contrib=(q?.contributedRA||0)+(q?.contributedRB||0),exports=Math.max(0,a?.exports||0),borrow=exposure(id),rdr=q?.rdr||0;return Math.max(2,(q?.quota||10)+contrib*.35+(c?.foreignReserves||0)*.16+exports*.025-rdr*.08-borrow*.18)}
function recalcDirectors(record=true){let a=scoreQuota('A'),b=scoreQuota('B'),total=a+b||1,va=100*a/total,vb=100*b/total;for(const [id,v] of [['A',va],['B',vb]]){let q=quota(id),d=director(id);if(q)q.votes=v;if(d)d.votes=v}let bd=S.fundBoards59[0];if(bd){let next=va>=60?'A':vb>=60?'B':null;if(next!==bd.dominant){bd.dominant=next;if(next){remember('CREDITOR MAJORITY: Reality '+next+' crossed 60% of stabilization-board votes',realm(next));if(typeof place==='function')place('cold','reserve contribution became a unilateral policy vote',realm(next));governanceCrisis(next,'quota majority can govern the other reality') }} }if(record)return{A:va,B:vb};return{A:va,B:vb}}
function quotaReview(manual=true){ensureBoard();let before={A:quota('A')?.votes||50,B:quota('B')?.votes||50},after=recalcDirectors(true),r={id:'QR'+(++S.quotaReviewSerial59),before,after,scoreA:scoreQuota('A'),scoreB:scoreQuota('B'),created:Date.now(),x:10+Math.random()*80,y:12+Math.random()*68};S.quotaReviews59.push(r);S.quotaReviewsDone59++;remember('QUOTA REVIEW '+r.id+': A '+before.A.toFixed(1)+'→'+after.A.toFixed(1)+' votes · B '+before.B.toFixed(1)+'→'+after.B.toFixed(1),realm('A'));trust59('A','stabilization-quota-review',r.id+' A '+after.A.toFixed(1)+' B '+after.B.toFixed(1));trust59('B','stabilization-quota-review',r.id+' A '+after.A.toFixed(1)+' B '+after.B.toFixed(1));if(manual){$('#msg').textContent=r.id+' reset board votes to A '+after.A.toFixed(1)+' / B '+after.B.toFixed(1)+'.';renderAll();save59();openBoard()}return r}
function subscribeQuota(id,amount=2,manual=true){ensureBoard();let c=cur(id),q=quota(id),f=fund();if(!c||!q||!f||c.foreignReserves<amount){if(manual)$('#msg').textContent='Reality '+id+' lacks enough foreign reserves to subscribe more quota.';return false}c.foreignReserves-=amount;q.quota=(q.quota||10)+amount;if(foreign(id)==='RA'){f.poolRA+=amount;q.contributedRA=(q.contributedRA||0)+amount}else{f.poolRB+=amount;q.contributedRB=(q.contributedRB||0)+amount}S.quotaSubscriptions59+=amount;remember('QUOTA SUBSCRIPTION: Reality '+id+' transferred '+amount.toFixed(1)+' '+foreign(id)+' into the fund to buy a larger institutional share',realm(id));if(typeof place==='function')place('warm','foreign reserves converted into governance weight',realm(id));quotaReview(false);if(manual){$('#msg').textContent='Reality '+id+' subscribed '+amount.toFixed(1)+' '+foreign(id)+' of additional quota.';renderAll();save59();openBoard()}return true}
function surveillance(id,manual=true){ensureBoard();let a=acct(id),c=cur(id),m=bank(id),distressed=(S.packageTreasuries47||[]).filter(t=>t.reality===id&&['strike','bankrupt'].includes(t.status)).length,total=(S.packageTreasuries47||[]).filter(t=>t.reality===id).length||1;let deficit=Math.max(0,-(a?.currentAccount||0)),debt=a?.externalDebt||0,arrears=a?.arrears||0,reserves=c?.foreignReserves||0,risk=cl(deficit/30+debt/45+arrears/20+Math.max(0,5-reserves)/12+(1-(m?.credibility??.7))*.18+(distressed/total)*.16,0,1),recommendation=risk>.67?'tighten and restructure':risk>.4?'hold conditions':'release cautiously';let r={id:'SURV'+(++S.surveillanceSerial59),reality:id,risk,currentAccount:a?.currentAccount||0,externalDebt:debt,arrears,reserves,monetaryCredibility:m?.credibility??.7,distressedPackages:distressed,recommendation,created:Date.now(),x:10+Math.random()*80,y:12+Math.random()*68};S.surveillanceReports59.push(r);S.surveillanceMissions59++;remember('SURVEILLANCE '+r.id+': Reality '+id+' risk '+risk.toFixed(2)+' · '+recommendation,realm(id));if(typeof place==='function')place('dream','technical staff report becoming a voting instruction',realm(id));if(manual){$('#msg').textContent=r.id+' rates Reality '+id+' risk '+risk.toFixed(2)+' · '+recommendation+'.';renderAll();save59();openSurveillance(r)}return r}
function latestSurveillance(id){return [...S.surveillanceReports59].reverse().find(r=>r.reality===id)||surveillance(id,false)}
function motionLabel(type){return({'tighten-conditionality':'tighten program conditions','soften-conditionality':'soften program conditions','release-tranche':'release reserve tranche','ratify-waiver':'ratify failed-review waiver','suspend-program':'suspend stabilization program'})[type]||type}
function createMotion(type,p,manual=true){ensureBoard();let target=p?.reality||null,m={id:'MOT'+(++S.fundMotionSerial59),boardId:board().id,type,label:motionLabel(type),programId:p?.id||null,targetReality:target,status:'pending',threshold:board().majority,votes:{},yesWeight:0,noWeight:0,recused:target?[target]:[],created:Date.now(),decided:null,override:false,x:10+Math.random()*80,y:12+Math.random()*68};S.fundMotions59.push(m);remember('BOARD MOTION '+m.id+': '+m.label+(target?' for Reality '+target:''),realm(target||'A'));if(manual){renderAll();save59();openMotion(m)}return m}
function votePreference(d,m){if(m.recused.includes(d.reality))return'recused';let id=m.targetReality,r=latestSurveillance(id||d.reality),risk=r?.risk||.5;if(m.type==='tighten-conditionality')return risk>=.45?'yes':'no';if(m.type==='soften-conditionality')return risk<.42?'yes':'no';if(m.type==='release-tranche'){let a=acct(id),c=cur(id);return ((c?.foreignReserves||0)<3||(a?.arrears||0)>4||risk>.7)?'yes':'no'}if(m.type==='ratify-waiver')return risk>.62?'yes':'no';if(m.type==='suspend-program')return risk<.3?'no':'yes';return'no'}
function voteMotion(m,manual=true){if(!m||!['pending','deadlocked'].includes(m.status))return m;recalcDirectors(false);m.votes={};m.yesWeight=0;m.noWeight=0;for(const d of S.fundDirectors59.filter(d=>d.status==='active')){let v=votePreference(d,m);m.votes[d.reality]=v;if(v==='yes')m.yesWeight+=d.votes;if(v==='no')m.noWeight+=d.votes}S.boardVotes59++;let need=m.threshold*100;if(m.yesWeight+1e-9>=need){m.status='passed';m.decided=Date.now();applyMotion(m)}else if(m.noWeight>100-need+1e-9){m.status='rejected';m.decided=Date.now()}else{m.status='deadlocked';m.decided=Date.now();board().deadlocks++;S.boardDeadlocks59++;remember('BOARD DEADLOCK '+m.id+': '+m.yesWeight.toFixed(1)+' yes / '+m.noWeight.toFixed(1)+' no could not reach '+need.toFixed(0)+'%',realm(m.targetReality||'A'));if(typeof place==='function')place('cold','equal sovereignty unable to authorize the rescue',realm(m.targetReality||'A'));if(board().deadlocks>=2)governanceCrisis(m.targetReality||'A','quota board repeatedly deadlocked')}if(manual){$('#msg').textContent=m.id+' '+m.status.toUpperCase()+' · yes '+m.yesWeight.toFixed(1)+' / no '+m.noWeight.toFixed(1)+'.';renderAll();save59();openMotion(m)}return m}
function poolFor(code){let f=fund();return code==='RA'?f.poolRA:f.poolRB}
function addPool(code,v){let f=fund();if(code==='RA')f.poolRA=Math.max(0,f.poolRA+v);else f.poolRB=Math.max(0,f.poolRB+v)}
function applyMotion(m){let p=program(m.programId);if(!p)return;if(m.type==='tighten-conditionality'){let c=(S.stabilizationConditions58||[]).find(c=>c.programId===p.id&&c.type==='monetary-tightening');if(c)c.target=cl((c.target||.08)+.03,.02,.3);for(const t of (S.packageTreasuries47||[]).filter(t=>t.reality===p.reality&&t.status!=='bankrupt'))t.taxRate=cl((t.taxRate||1)+.1,.25,4);p.boardTightened59=(p.boardTightened59||0)+1;S.boardConditionalityChanges59++;remember('BOARD CONDITIONALITY '+m.id+': quota vote tightened Reality '+p.reality+' rescue terms',realm(p.reality));if(typeof place==='function')place('cold','foreign creditor vote raised the domestic policy hurdle',realm(p.reality))}
if(m.type==='soften-conditionality'){let c=(S.stabilizationConditions58||[]).find(c=>c.programId===p.id&&c.type==='monetary-tightening');if(c)c.target=cl((c.target||.08)-.02,.02,.3);p.boardSoftened59=(p.boardSoftened59||0)+1;S.boardConditionalityChanges59++;remember('BOARD CONDITIONALITY '+m.id+': quota vote softened Reality '+p.reality+' rescue terms',realm(p.reality))}
if(m.type==='release-tranche'){let x=Math.min(3,p.remaining||0,poolFor(p.currency));if(x>0){addPool(p.currency,-x);let c=cur(p.reality);if(c)c.foreignReserves+=x;p.disbursed=(p.disbursed||0)+x;p.remaining=Math.max(0,(p.remaining||0)-x);S.stabilizationDisbursements58=(S.stabilizationDisbursements58||0)+x;S.boardTranches59+=x;remember('BOARD TRANCHE '+m.id+': directors released '+x.toFixed(1)+' '+p.currency+' to Reality '+p.reality,realm(p.reality));trust59(p.reality,'stabilization-board-tranche',m.id+' '+x.toFixed(1)+' '+p.currency)}}
if(m.type==='ratify-waiver'){let r=[...(S.stabilizationReviews58||[])].reverse().find(r=>r.programId===p.id&&r.status==='waived');if(r)r.boardRatified59=m.id;remember('WAIVER RATIFIED '+m.id+': board accepted a tranche released despite failed conditions',realm(p.reality))}
if(m.type==='suspend-program'){p.status='board-suspended';remember('PROGRAM SUSPENDED '+m.id+': stabilization board stopped further reserve access for Reality '+p.reality,realm(p.reality));if(typeof place==='function')place('cold','rescue agreement suspended by creditor vote',realm(p.reality))}
trust59(p.reality,'stabilization-board-decision',m.id+' '+m.label+' '+m.status)}
function chairOverride(m,manual=true){if(!m||!['deadlocked','pending'].includes(m.status))return false;m.status='passed-override';m.override=true;m.decided=Date.now();board().chairPower++;S.boardOverrides59++;fund().independence=cl((fund().independence||.78)-.045,0,1);fund().credibility=cl((fund().credibility||.8)-.02,0,1);applyMotion(m);remember('SYSTEMIC NECESSITY OVERRIDE '+m.id+': staff chair executed '+m.label+' after quota voting failed',realm(m.targetReality||'A'));if(typeof place==='function'){place('dream','unelected chair became the missing majority',realm(m.targetReality||'A'));place('cold','emergency governance replacing quota consent',realm(m.targetReality||'A'))}governanceCrisis(m.targetReality||'A','staff chair overrode member voting');if(manual){$('#msg').textContent=m.id+' executed through SYSTEMIC NECESSITY OVERRIDE.';renderAll();save59();openMotion(m)}return true}
function governanceCrisis(id,kind){let now=Date.now(),k=id+'|'+kind;if(S.governanceKeys59[k]&&now-S.governanceKeys59[k]<14000)return;S.governanceKeys59[k]=now;S.governanceCrises59++;S.lastGovernanceCrisis59=now;remember('FUND GOVERNANCE CRISIS: '+kind+' made rescue voting another source of authority over software policy',realm(id));if(typeof place==='function'){place('cold','quota share becoming policy jurisdiction',realm(id));place('dream','creditor majority governing a borrower that cannot vote',realm(id))}let b=$('#bailiff');if(b)b.textContent='asking whether reserve contributions are money, votes, or sovereignty';incident59(id,'stabilization governance crisis: '+kind,kind.includes('majority')||kind.includes('override')?'SEV1':'SEV2')}
function openSurveillance(r){panel(r.id+' · SURVEILLANCE','Reality '+r.reality+' · risk '+r.risk.toFixed(2), 'current account '+r.currentAccount.toFixed(1)+' · external debt '+r.externalDebt.toFixed(1)+' · arrears '+r.arrears.toFixed(1)+' · reserves '+r.reserves.toFixed(1)+' · monetary credibility '+r.monetaryCredibility.toFixed(2)+' · '+r.recommendation,[['open fund board',openBoard],['close',closePanel]])}
function openMotion(m){let p=program(m.programId),acts=[];if(['pending','deadlocked'].includes(m.status))acts.push(['call board vote',()=>voteMotion(m,true)]);if(m.status==='deadlocked')acts.push(['chair systemic override',()=>chairOverride(m,true)]);if(p)acts.push(['open program governance',()=>openProgramGovernance(p)]);acts.push(['close',closePanel]);let rec=m.recused.length?' · recused '+m.recused.join(','):'';panel(m.id+' · '+m.label.toUpperCase(),m.status.toUpperCase()+(m.override?' · OVERRIDE':''),'yes '+m.yesWeight.toFixed(1)+' · no '+m.noWeight.toFixed(1)+' · threshold '+(m.threshold*100).toFixed(0)+'%'+rec+' · votes '+Object.entries(m.votes).map(([k,v])=>k+':'+v).join(' '),acts)}
function openProgramGovernance(p){let acts=[['surveil borrower',()=>surveillance(p.reality,true)],['motion: tighten conditions',()=>createMotion('tighten-conditionality',p,true)],['motion: soften conditions',()=>createMotion('soften-conditionality',p,true)],['motion: release tranche',()=>createMotion('release-tranche',p,true)],['motion: suspend program',()=>createMotion('suspend-program',p,true)]];let wr=[...(S.stabilizationReviews58||[])].reverse().find(r=>r.programId===p.id&&r.status==='waived');if(wr&&!wr.boardRatified59)acts.push(['motion: ratify waiver',()=>createMotion('ratify-waiver',p,true)]);for(const m of S.fundMotions59.filter(m=>m.programId===p.id).slice(-4))acts.push(['open '+m.id+' · '+m.status,()=>openMotion(m)]);acts.push(['close',closePanel]);let c=(S.stabilizationConditions58||[]).find(c=>c.programId===p.id&&c.type==='monetary-tightening');panel(p.id+' · BOARD GOVERNANCE','Reality '+p.reality+' · '+p.status,'quota A '+(quota('A')?.votes||0).toFixed(1)+' / B '+(quota('B')?.votes||0).toFixed(1)+' · borrower recused from own program · monetary condition '+((c?.target||0)*100).toFixed(1)+'% · remaining '+(p.remaining||0).toFixed(1)+' '+p.currency,acts)}
function openBoard(){ensureBoard();recalcDirectors(false);let b=board(),qa=quota('A'),qb=quota('B'),acts=[['run quota review',()=>quotaReview(true)],['surveillance mission A',()=>surveillance('A',true)],['surveillance mission B',()=>surveillance('B',true)],['A subscribe 2 quota',()=>subscribeQuota('A',2,true)],['B subscribe 2 quota',()=>subscribeQuota('B',2,true)]];for(const p of (S.stabilizationPrograms58||[]).filter(p=>['active','off-track','funding-shortfall','board-suspended'].includes(p.status)).slice(-4))acts.push(['govern '+p.id+' · '+p.reality,()=>openProgramGovernance(p)]);for(const m of S.fundMotions59.slice(-4))acts.push(['open '+m.id+' · '+m.status,()=>openMotion(m)]);acts.push(['close',closePanel]);panel(b.name+' · '+b.status.toUpperCase(),'quota-weighted rescue government','A '+(qa?.votes||0).toFixed(1)+'% · B '+(qb?.votes||0).toFixed(1)+'% · threshold '+(b.majority*100).toFixed(0)+'% · dominant '+(b.dominant?'Reality '+b.dominant:'none')+' · deadlocks '+b.deadlocks+' · chair overrides '+b.chairPower+' · fund independence '+(fund()?.independence||0).toFixed(2),acts)}
function autonomous(){ensureBoard();let now=Date.now();if(now-S.lastGovernanceTick59<2200)return;S.lastGovernanceTick59=now;recalcDirectors(false);for(const p of (S.stabilizationPrograms58||[]).filter(p=>p.status==='off-track')){let open=S.fundMotions59.some(m=>m.programId===p.id&&['pending','deadlocked'].includes(m.status));if(!open&&Math.random()<.006){let m=createMotion('release-tranche',p,false);voteMotion(m,false);break}}if(Math.random()<.0015)surveillance(Math.random()<.5?'A':'B',false)}
function renderGovernance59(){ensureBoard();let layer=$('#fundGovernanceLayer');if(!layer){layer=document.createElement('div');layer.id='fundGovernanceLayer';document.body.appendChild(layer)}layer.innerHTML='';let b=board(),be=document.createElement('i');be.className='fundBoard '+(b.dominant?'dominant':'');be.dataset.label='BOARD';be.style.left=b.x+'%';be.style.top=b.y+'%';be.onclick=openBoard;layer.appendChild(be);for(const d of S.fundDirectors59){let e=document.createElement('i');e.className='fundDirector'+(b.dominant===d.reality?' dominant':'');e.dataset.label=d.reality+' '+d.votes.toFixed(0)+'%';e.style.left=d.x+'%';e.style.top=d.y+'%';e.onclick=openBoard;layer.appendChild(e)}for(const m of S.fundMotions59.filter(m=>['pending','deadlocked'].includes(m.status)).slice(-8)){let e=document.createElement('i');e.className='fundMotion '+m.status;e.dataset.label=m.status==='deadlocked'?'⊘':'V';e.style.left=m.x+'%';e.style.top=m.y+'%';e.onclick=()=>openMotion(m);layer.appendChild(e)}for(const r of S.surveillanceReports59.slice(-8)){let e=document.createElement('i');e.className='surveillance '+(r.risk>.67?'high':r.risk>.4?'medium':'low');e.dataset.label='S'+r.reality;e.style.left=r.x+'%';e.style.top=r.y+'%';e.onclick=()=>openSurveillance(r);layer.appendChild(e)}let line=$('#fundgovernanceline');if(!line){line=document.createElement('div');line.id='fundgovernanceline';line.className='line';($('#stabilizationline')||$('#tradeline')||$('#fxline')||$('#enforcement')).after(line)}line.textContent='fund governance: A '+(quota('A')?.votes||0).toFixed(1)+'% / B '+(quota('B')?.votes||0).toFixed(1)+'% · '+(b.dominant?'dominant R'+b.dominant:'no majority')+' · '+S.boardDeadlocks59+' deadlocks · '+S.boardOverrides59+' chair overrides · '+S.surveillanceMissions59+' surveillance missions · '+S.governanceCrises59+' crises';let ctr=document.querySelector('#app .controls');if(ctr&&!$('#openFundBoardButton')){let x=document.createElement('button');x.id='openFundBoardButton';x.textContent='open fund board';x.onclick=openBoard;ctr.prepend(x)}if(ctr&&!$('#runSurveillanceButton')){let x=document.createElement('button');x.id='runSurveillanceButton';x.textContent='run stabilization surveillance';x.onclick=()=>surveillance(S.active,true);ctr.prepend(x)}}
renderAll=function(){BR59();renderGovernance59()};let f=$('#forget');if(f)f.onclick=()=>{for(let i=2;i<=59;i++)localStorage.removeItem('nothing-state-v'+i);location.reload()};
setInterval(()=>{autonomous();renderGovernance59();save59()},2400);ensureBoard();renderAll();save59();
})();