(()=>{
const BS56=save,BR56=renderAll,O56=JSON.parse(localStorage.getItem('nothing-state-v56')||'null')||{},cl=(v,a,b)=>Math.max(a,Math.min(b,v)),pick=a=>a&&a.length?a[Math.floor(Math.random()*a.length)]:null;
S.fxCurrencies56=O56.fxCurrencies56||[];
S.fxMarkets56=O56.fxMarkets56||[];
S.fxInterventions56=O56.fxInterventions56||[];
S.fxAttacks56=O56.fxAttacks56||[];
S.fxFlows56=O56.fxFlows56||[];
S.fxReserveTransfers56=O56.fxReserveTransfers56||[];
S.fxCurrencySerial56=O56.fxCurrencySerial56||0;
S.fxMarketSerial56=O56.fxMarketSerial56||0;
S.fxInterventionSerial56=O56.fxInterventionSerial56||0;
S.fxAttackSerial56=O56.fxAttackSerial56||0;
S.fxFlowSerial56=O56.fxFlowSerial56||0;
S.fxReserveTransferSerial56=O56.fxReserveTransferSerial56||0;
S.fxInterventionsMade56=O56.fxInterventionsMade56||0;
S.fxPegBreaks56=O56.fxPegBreaks56||0;
S.fxDevaluations56=O56.fxDevaluations56||0;
S.fxCapitalControls56=O56.fxCapitalControls56||0;
S.fxReserveAdoptions56=O56.fxReserveAdoptions56||0;
S.fxSpeculativeAttacks56=O56.fxSpeculativeAttacks56||0;
S.fxReserveExhaustions56=O56.fxReserveExhaustions56||0;
S.fxCrises56=O56.fxCrises56||0;
S.lastFxCrisis56=O56.lastFxCrisis56||0;
S.fxKeys56=O56.fxKeys56||{};
S.lastFxTick56=O56.lastFxTick56||Date.now();
function save56(){BS56();localStorage.setItem('nothing-state-v56',JSON.stringify({fxCurrencies56:S.fxCurrencies56,fxMarkets56:S.fxMarkets56,fxInterventions56:S.fxInterventions56,fxAttacks56:S.fxAttacks56,fxFlows56:S.fxFlows56,fxReserveTransfers56:S.fxReserveTransfers56,fxCurrencySerial56:S.fxCurrencySerial56,fxMarketSerial56:S.fxMarketSerial56,fxInterventionSerial56:S.fxInterventionSerial56,fxAttackSerial56:S.fxAttackSerial56,fxFlowSerial56:S.fxFlowSerial56,fxReserveTransferSerial56:S.fxReserveTransferSerial56,fxInterventionsMade56:S.fxInterventionsMade56,fxPegBreaks56:S.fxPegBreaks56,fxDevaluations56:S.fxDevaluations56,fxCapitalControls56:S.fxCapitalControls56,fxReserveAdoptions56:S.fxReserveAdoptions56,fxSpeculativeAttacks56:S.fxSpeculativeAttacks56,fxReserveExhaustions56:S.fxReserveExhaustions56,fxCrises56:S.fxCrises56,lastFxCrisis56:S.lastFxCrisis56,fxKeys56:S.fxKeys56,lastFxTick56:S.lastFxTick56}))}save=save56;
const realm=id=>S.real[id],bank=id=>(S.monetaryAuthorities55||[]).find(a=>a.reality===id),currency=id=>S.fxCurrencies56.find(c=>c.reality===id),market=()=>S.fxMarkets56[0];
function trust56(id,status,note){let accepted=S.trustPolicies?.[id]?.acceptedRoots||[],r=[...(S.trustRoots||[])].filter(x=>accepted.includes(x.id)&&x.status==='active').sort((a,b)=>(b.strength||0)-(a.strength||0))[0];S.trustAudits=S.trustAudits||[];S.trustAuditSerial=S.trustAuditSerial||0;S.trustAudits.push({id:'TA'+(++S.trustAuditSerial),reality:id,remediationId:null,credentialId:null,certificateId:null,rootId:r?.id||null,status,created:Date.now(),note,x:10+Math.random()*80,y:12+Math.random()*68})}
function incident56(id,title,severity='SEV2'){S.incidents=S.incidents||[];let ex=S.incidents.find(i=>i.reality===id&&i.title===title&&i.status==='open');if(ex)return ex;S.incidentSerial=S.incidentSerial||0;let x={id:'INC'+(++S.incidentSerial),reality:id,title,severity,status:'open',alertIds:[],started:Date.now(),acknowledged:null,resolved:null,postmortem:null,owner:'interreality foreign exchange market',x:10+Math.random()*80,y:12+Math.random()*68};S.incidents.push(x);return x}
function ensureFX(){for(const id of ['A','B'])if(!currency(id)){let other=id==='A'?'B':'A',a=bank(id);S.fxCurrencies56.push({id:'FXC'+(++S.fxCurrencySerial56),reality:id,code:'R'+id,name:'Reality '+id+' settlement reserve',status:'floating',peg:null,pegBand:.035,foreignReserveCode:'R'+other,foreignReserves:12,capitalControls:false,controlStrength:0,reserveShare:0,interventions:0,devaluations:0,created:Date.now(),x:id==='A'?34:66,y:9})}if(!market()){S.fxMarkets56.push({id:'FXM'+(++S.fxMarketSerial56),pair:'RA/RB',rate:1,previousRate:1,fundamental:1,pressure:0,volatility:.015,turnover:0,reserveCurrency:null,lastMove:Date.now(),created:Date.now(),x:50,y:15});remember('FX MARKET: Reality A and Reality B settlement reserves acquired an exchange rate',realm('A'));remember('FX MARKET: Reality A and Reality B settlement reserves acquired an exchange rate',realm('B'));trust56('A','interreality-fx-market-created','RA/RB market established');trust56('B','interreality-fx-market-created','RA/RB market established')}}
function strength(id){let a=bank(id),c=currency(id);if(!a)return 1;let base=1+(a.credibility||.7)*.55+(a.independence||.7)*.25+(a.discountRate||.05)*1.2+(a.capital||0)*.008-(a.badAssets||0)*.012-(a.monetaryBase||0)*.004-(a.status==='negative-equity'?.28:0);if(c?.capitalControls)base-=.05*c.controlStrength;return cl(base,.3,2.2)}
function fundamentalRate(){return cl(strength('A')/Math.max(.2,strength('B')),.35,2.8)}
function fxCrisis(id,kind,severity='SEV2'){let now=Date.now(),k=id+'|'+kind;if(S.fxKeys56[k]&&now-S.fxKeys56[k]<12000)return;S.fxKeys56[k]=now;S.fxCrises56++;S.lastFxCrisis56=now;remember('FX CRISIS: '+kind+' turned the exchange rate into another source of institutional authority',realm(id));if(typeof place==='function'){place('cold','foreign reserves defending a promise about money',realm(id));place('dream','exchange rate translating one reality into another',realm(id))}let b=$('#bailiff');if(b)b.textContent='asking whether the currency is weak because people fled it or people fled because it was weak';incident56(id,'interreality currency crisis: '+kind,severity)}
function updateReserveShare(){let a=currency('A'),b=currency('B'),m=market();let total=Math.max(.01,a.foreignReserves+b.foreignReserves);a.reserveShare=b.foreignReserves/total;b.reserveShare=a.foreignReserves/total;let next=a.reserveShare>b.reserveShare+.18?'A':b.reserveShare>a.reserveShare+.18?'B':null;if(next!==m.reserveCurrency){m.reserveCurrency=next;if(next){S.fxReserveAdoptions56++;remember('RESERVE CURRENCY: Reality '+next+' settlement reserve became the larger foreign reserve asset across the rift',realm(next));if(typeof place==='function')place('warm','other reality holding this currency as reserves',realm(next));trust56(next,'interreality-reserve-currency',m.id+' reserve currency R'+next)}}}
function recordFlow(from,to,amount,reason){let x={id:'FLOW'+(++S.fxFlowSerial56),from,to,amount,reason,created:Date.now(),x:10+Math.random()*80,y:12+Math.random()*68};S.fxFlows56.push(x);S.fxFlows56=S.fxFlows56.slice(-80);return x}
function moveMarket(force=0){ensureFX();let m=market(),f=fundamentalRate();m.previousRate=m.rate;m.fundamental=f;let a=currency('A'),b=currency('B'),control=.5*((a.capitalControls?a.controlStrength:0)+(b.capitalControls?b.controlStrength:0));let natural=(f-m.rate)*.08+(Math.random()-.5)*m.volatility*(1-control*.6),p=(m.pressure||0)*.025;let next=m.rate+natural+p+force;m.pressure*=.83;m.rate=cl(next,.18,4.5);m.turnover+=Math.abs(m.rate-m.previousRate)*40;m.lastMove=Date.now();for(const c of [a,b])if(c.peg){let diff=(m.rate-c.peg)/c.peg;if(Math.abs(diff)>c.pegBand*1.8&&c.foreignReserves<2.5)breakPeg(c,'reserves exhausted defending peg');else if(Math.abs(diff)>c.pegBand*3)fxCrisis(c.reality,'exchange rate moved outside declared peg band')}updateReserveShare();return m.rate}
function setPeg(id,target=null){ensureFX();let c=currency(id),m=market();c.status='pegged';c.peg=target||m.rate;c.pegBand=.03;remember('CURRENCY PEG: Reality '+id+' promised to hold RA/RB near '+c.peg.toFixed(3),realm(id));trust56(id,'interreality-currency-peg','R'+id+' peg '+c.peg.toFixed(4));if(typeof place==='function')place('warm','exchange rate turned into a public promise',realm(id));renderAll();save56();openCurrency(c)}
function floatCurrency(c){if(!c)return;c.status='floating';c.peg=null;remember('FLOAT: Reality '+c.reality+' stopped promising a fixed interreality exchange rate',realm(c.reality));renderAll();save56();openCurrency(c)}
function defendPeg(c,manual=true){if(!c?.peg)return null;let m=market(),target=c.peg,diff=(m.rate-target)/target;if(Math.abs(diff)<c.pegBand*.4){if(manual)$('#msg').textContent='The peg is already close to target.';return null}let weakA=m.rate<target,need=Math.min(c.foreignReserves,Math.max(.5,Math.abs(diff)*18));if(need<=.01){breakPeg(c,'no foreign reserves left');return null}c.foreignReserves-=need;c.interventions++;S.fxInterventionsMade56++;let force=0;if(c.reality==='A')force=weakA?need*.012:-need*.012;else force=weakA?-need*.012:need*.012;let x={id:'FXI'+(++S.fxInterventionSerial56),reality:c.reality,currency:c.code,amount:need,rateBefore:m.rate,target,force,status:'executed',created:Date.now(),x:10+Math.random()*80,y:12+Math.random()*68};S.fxInterventions56.push(x);recordFlow(c.reality,c.reality==='A'?'B':'A',need,'peg defense reserve sale');moveMarket(force);x.rateAfter=m.rate;remember('FX INTERVENTION '+x.id+': Reality '+c.reality+' spent '+need.toFixed(1)+' '+c.foreignReserveCode+' reserves defending '+target.toFixed(3),realm(c.reality));if(typeof place==='function')place('cold','foreign reserves burned to defend an exchange-rate promise',realm(c.reality));if(c.foreignReserves<2.5){S.fxReserveExhaustions56++;fxCrisis(c.reality,'peg defense nearly exhausted foreign reserves','SEV1')}if(manual){$('#msg').textContent=x.id+' spent '+need.toFixed(1)+' foreign reserves; '+c.foreignReserves.toFixed(1)+' remain.';renderAll();save56();openCurrency(c)}return x}
function breakPeg(c,reason){if(!c?.peg)return;let old=c.peg,pre=market().rate;c.status='floating';c.peg=null;S.fxPegBreaks56++;let jump=c.reality==='A'?-Math.max(.04,Math.abs(pre-old)*.45):Math.max(.04,Math.abs(pre-old)*.45);moveMarket(jump);remember('PEG BROKE: Reality '+c.reality+' abandoned '+old.toFixed(3)+' after '+reason,realm(c.reality));if(typeof place==='function'){place('cold','exchange-rate promise outlived the reserves defending it',realm(c.reality));place('dream','floating currency after institutional promise failed',realm(c.reality))}fxCrisis(c.reality,'currency peg broke','SEV1')}
function devalue(c){if(!c?.peg)return;let old=c.peg,f=fundamentalRate(),next=c.reality==='A'?Math.min(old*.9,f):Math.max(old*1.1,f);c.peg=cl(next,.2,4.5);c.devaluations++;S.fxDevaluations56++;remember('DEVALUATION: Reality '+c.reality+' changed its peg from '+old.toFixed(3)+' to '+c.peg.toFixed(3),realm(c.reality));if(typeof place==='function')place('cold','same currency new official value',realm(c.reality));fxCrisis(c.reality,'official exchange rate changed by decree');renderAll();save56();openCurrency(c)}
function toggleControls(c){c.capitalControls=!c.capitalControls;c.controlStrength=c.capitalControls?.65:0;S.fxCapitalControls56++;remember('CAPITAL CONTROLS: Reality '+c.reality+' '+(c.capitalControls?'restricted':'reopened')+' conversion of settlement reserves across the rift',realm(c.reality));if(typeof place==='function')place(c.capitalControls?'cold':'warm',c.capitalControls?'currency can cross border only with permission':'capital controls lifted',realm(c.reality));renderAll();save56();openCurrency(c)}
function reserveSwapLine(id,amount=4){let c=currency(id),o=currency(id==='A'?'B':'A'),m=market(),a=bank(id),oa=bank(o.reality);if(!c||!o||!a||!oa)return null;let received,reciprocal;if(id==='A'){received=amount;reciprocal=amount/Math.max(.1,m.rate);c.foreignReserves+=received;o.foreignReserves+=reciprocal;oa.monetaryBase=(oa.monetaryBase||0)+received;a.monetaryBase=(a.monetaryBase||0)+reciprocal}else{received=amount;reciprocal=amount*Math.max(.1,m.rate);c.foreignReserves+=received;o.foreignReserves+=reciprocal;oa.monetaryBase=(oa.monetaryBase||0)+received;a.monetaryBase=(a.monetaryBase||0)+reciprocal}let r={id:'FXR'+(++S.fxReserveTransferSerial56),from:id,to:o.reality,amount:received,reciprocal,rate:m.rate,type:'central-bank-swap-line',created:Date.now(),x:10+Math.random()*80,y:12+Math.random()*68};S.fxReserveTransfers56.push(r);remember('RESERVE SWAP LINE '+r.id+': Reality '+id+' obtained '+received.toFixed(1)+' '+c.foreignReserveCode+' while both monetary authorities created reciprocal reserves',realm(id));if(typeof place==='function')place('warm','foreign reserves created by reciprocal central-bank promise',realm(id));trust56(id,'interreality-reserve-swap-line',r.id+' '+received.toFixed(1)+' '+c.foreignReserveCode);updateReserveShare();renderAll();save56();openCurrency(c);return r}
function speculativeAttack(c,manual=true){if(!c?.peg){if(manual)$('#msg').textContent='A speculative attack needs a declared peg to attack.';return null}let m=market(),f=fundamentalRate(),mis=Math.abs(c.peg-f)/Math.max(.2,c.peg),size=Math.round((4+mis*30+(12-c.foreignReserves)*.35)*10)/10,controls=c.capitalControls?1-c.controlStrength*.7:1,effective=Math.max(1,size*controls),direction=c.reality==='A'?-1:1;m.pressure+=direction*effective*.08;let x={id:'ATK'+(++S.fxAttackSerial56),reality:c.reality,currency:c.code,size,effective,status:'active',peg:c.peg,fundamental:f,reservesBefore:c.foreignReserves,created:Date.now(),x:10+Math.random()*80,y:12+Math.random()*68};S.fxAttacks56.push(x);S.fxSpeculativeAttacks56++;remember('SPECULATIVE ATTACK '+x.id+': '+effective.toFixed(1)+' credits sold against Reality '+c.reality+' peg',realm(c.reality));if(typeof place==='function')place('cold','market testing whether the peg has enough reserves behind it',realm(c.reality));moveMarket();if(Math.abs(m.rate-c.peg)/c.peg>c.pegBand)defendPeg(c,false);x.rateAfter=m.rate;x.reservesAfter=c.foreignReserves;x.status=c.peg?'defended':'peg-broken';if(!c.peg||c.foreignReserves<2.5)fxCrisis(c.reality,'speculative attack exhausted peg defense','SEV1');if(manual){$('#msg').textContent=x.id+' attacked '+x.currency+'; '+c.foreignReserves.toFixed(1)+' foreign reserves remain.';renderAll();save56();openAttack(x)}return x}
function adoptForeignReserve(id,amount=5){let c=currency(id),other=currency(id==='A'?'B':'A'),a=bank(id),m=market();if(!c||!other||!a||!m)return;let cost=Math.max(.5,amount),domesticCost=id==='A'?cost/Math.max(.1,m.rate):cost*Math.max(.1,m.rate);c.foreignReserves+=cost;a.monetaryBase=(a.monetaryBase||0)+domesticCost;S.fxReserveAdoptions56++;remember('FOREIGN RESERVE PURCHASE: Reality '+id+' issued '+domesticCost.toFixed(1)+' '+c.code+' to accumulate '+cost.toFixed(1)+' '+c.foreignReserveCode,realm(id));if(typeof place==='function')place('warm','monetary authority holding the other reality\'s money',realm(id));trust56(id,'interreality-reserve-accumulation',c.code+' holds '+c.foreignReserves.toFixed(1)+' '+c.foreignReserveCode);updateReserveShare();renderAll();save56();openCurrency(c)}
function openCurrency(c){let m=market(),acts=[];if(c.peg){acts.push(['defend peg',()=>defendPeg(c)],['devalue official rate',()=>devalue(c)],['abandon peg',()=>floatCurrency(c)],['simulate speculative attack',()=>speculativeAttack(c)])}else acts.push(['peg to current rate',()=>setPeg(c.reality,m.rate)]);acts.push([c.capitalControls?'lift capital controls':'impose capital controls',()=>toggleControls(c)],['accumulate foreign reserves',()=>adoptForeignReserve(c.reality)],['open bilateral reserve swap line',()=>reserveSwapLine(c.reality,4)],['close',closePanel]);panel(c.name+' · '+c.status.toUpperCase(),c.code+' · foreign reserves '+c.foreignReserves.toFixed(1)+' '+c.foreignReserveCode,'RA/RB '+m.rate.toFixed(3)+' · fundamental '+m.fundamental.toFixed(3)+(c.peg?' · peg '+c.peg.toFixed(3)+' ±'+(c.pegBand*100).toFixed(1)+'%':'')+' · reserve share '+(c.reserveShare*100).toFixed(0)+'% · controls '+(c.capitalControls?'ON':'off'),acts)}
function openAttack(x){let c=currency(x.reality);panel(x.id+' · SPECULATIVE ATTACK',x.status+' · '+x.currency,'size '+x.size.toFixed(1)+' · effective '+x.effective.toFixed(1)+' · peg '+x.peg.toFixed(3)+' · fundamental '+x.fundamental.toFixed(3)+' · reserves '+x.reservesBefore.toFixed(1)+' → '+(x.reservesAfter??c?.foreignReserves??0).toFixed(1),[['open currency',()=>openCurrency(c)],['close',closePanel]])}
function openFX(){ensureFX();let m=market(),a=currency('A'),b=currency('B'),acts=[['move market',()=>{moveMarket();renderAll();save56();openFX()}],['open Reality A reserve',()=>openCurrency(a)],['open Reality B reserve',()=>openCurrency(b)]];if(a.peg)acts.push(['attack A peg',()=>speculativeAttack(a)]);if(b.peg)acts.push(['attack B peg',()=>speculativeAttack(b)]);for(const x of S.fxAttacks56.slice(-3))acts.push(['open '+x.id,()=>openAttack(x)]);acts.push(['close',closePanel]);panel('INTERREALITY FX MARKET · RA/RB',m.rate.toFixed(4)+' B-reserves per A-reserve','fundamental '+m.fundamental.toFixed(4)+' · pressure '+m.pressure.toFixed(2)+' · turnover '+m.turnover.toFixed(1)+' · reserve currency '+(m.reserveCurrency?'R'+m.reserveCurrency:'none')+' · '+S.fxPegBreaks56+' peg breaks · '+S.fxCrises56+' crises',acts)}
function stressCurrency(id=S.active){let c=currency(id);if(!c)return;if(!c.peg)setPeg(id,market().rate);let a=bank(id);if(a){a.monetaryBase=(a.monetaryBase||0)+18;a.badAssets=(a.badAssets||0)+8;a.credibility=cl((a.credibility||.7)-.08,0,1)}speculativeAttack(c,true)}
function autonomous(){ensureFX();let now=Date.now();if(now-S.lastFxTick56<1700)return;S.lastFxTick56=now;moveMarket();for(const c of S.fxCurrencies56){if(c.peg&&Math.abs(market().rate-c.peg)/c.peg>c.pegBand*.75&&Math.random()<.12)defendPeg(c,false);if(c.peg&&Math.abs(c.peg-fundamentalRate())/c.peg>.12&&Math.random()<.004)speculativeAttack(c,false)}if(Math.random()<.0015){let c=pick(S.fxCurrencies56);adoptForeignReserve(c.reality,2)}}
function renderFX(){ensureFX();let layer=$('#fxLayer');if(!layer){layer=document.createElement('div');layer.id='fxLayer';document.body.appendChild(layer)}layer.innerHTML='';for(const c of S.fxCurrencies56){let e=document.createElement('i');e.className='fxCurrency '+c.status+(c.capitalControls?' controlled':'');e.dataset.label=c.code;e.style.left=c.x+'%';e.style.top=c.y+'%';e.onclick=()=>openCurrency(c);layer.appendChild(e)}let m=market(),mid=document.createElement('i');mid.className='fxMarket'+(m.reserveCurrency?' reserve-'+m.reserveCurrency:'');mid.dataset.label=m.rate.toFixed(2);mid.style.left=m.x+'%';mid.style.top=m.y+'%';mid.onclick=openFX;layer.appendChild(mid);for(const x of S.fxAttacks56.filter(x=>x.status!=='expired').slice(-8)){let e=document.createElement('i');e.className='fxAttack '+x.status;e.dataset.label='⇄';e.style.left=x.x+'%';e.style.top=x.y+'%';e.onclick=()=>openAttack(x);layer.appendChild(e)}let line=$('#fxline');if(!line){line=document.createElement('div');line.id='fxline';line.className='line';($('#monetaryline')||$('#clearingline')||$('#derivativesline')||$('#enforcement')).after(line)}let c=currency(S.active),other=currency(S.active==='A'?'B':'A');line.textContent='interreality FX: RA/RB '+m.rate.toFixed(3)+' · fundamental '+m.fundamental.toFixed(3)+' · R'+S.active+' foreign reserves '+c.foreignReserves.toFixed(1)+' '+c.foreignReserveCode+' · '+(c.peg?'PEG '+c.peg.toFixed(3):'floating')+' · reserve currency '+(m.reserveCurrency?'R'+m.reserveCurrency:'none')+' · '+S.fxCrises56+' crises';let ctr=document.querySelector('#app .controls');if(ctr&&!$('#openFXButton')){let x=document.createElement('button');x.id='openFXButton';x.textContent='open FX market';x.onclick=openFX;ctr.prepend(x)}if(ctr&&!$('#stressCurrencyButton')){let x=document.createElement('button');x.id='stressCurrencyButton';x.textContent='stress settlement currency';x.onclick=()=>stressCurrency(S.active);ctr.prepend(x)}}
renderAll=function(){BR56();renderFX()};let f=$('#forget');if(f)f.onclick=()=>{for(let i=2;i<=56;i++)localStorage.removeItem('nothing-state-v'+i);location.reload()};
setInterval(()=>{autonomous();renderFX();save56()},2100);ensureFX();moveMarket();renderAll();save56();
})();
