(()=>{
const B99=save,R99=renderAll,O=JSON.parse(localStorage.getItem('nothing-state-v99')||'null')||{},RECOVER99=!Array.isArray(O.governanceArbitragePositions99)||!Array.isArray(O.governanceArbitrageRedemptions99),K=['governanceArbitrageOffice99','governanceArbitragePositions99','governanceArbitrageRedemptions99','governanceArbitragePositionSerial99','governanceArbitrageRedemptionSerial99','governanceArbitrageRedeemed99','governanceArbitrageMajorities99','governanceArbitrageRecoveries99','governanceArbitrageCrises99','governanceArbitrageKeys99','lastGovernanceArbitrageTick99'];
for(const k of K)S[k]=O[k]??(k==='governanceArbitragePositions99'||k==='governanceArbitrageRedemptions99'?[]:/Serial|Redeemed|Majorities|Recoveries|Crises|Tick/.test(k)?0:/Keys/.test(k)?{}:/Office/.test(k)?null:[]);
function save99(){B99();let o={};for(const k of K)o[k]=S[k];localStorage.setItem('nothing-state-v99',JSON.stringify(o))}save=save99;
const q=s=>$(s),EPS=.0001,realm=id=>S.real[id],fund=()=>S.stabilizationFunds58?.[0],quota=id=>(S.stabilizationQuotas58||[]).find(x=>x.reality===id),cur=id=>(S.fxCurrencies56||[]).find(x=>x.reality===id),acct=id=>(S.tradeAccounts57||[]).find(x=>x.reality===id),director=id=>(S.fundDirectors59||[]).find(x=>x.reality===id),board=()=>S.fundBoards59?.[0],other=id=>id==='A'?'B':'A',foreign=id=>'R'+other(id);
function trust(id,status,note){S.trustAudits=S.trustAudits||[];S.trustAuditSerial=S.trustAuditSerial||0;S.trustAudits.push({id:'TA'+(++S.trustAuditSerial),reality:id,status,created:Date.now(),note,x:10+Math.random()*80,y:12+Math.random()*68})}
function incident(id,title,sev='SEV2'){S.incidents=S.incidents||[];S.incidentSerial=S.incidentSerial||0;let ex=S.incidents.find(x=>x.reality===id&&x.title===title&&x.status==='open');if(ex)return ex;let i={id:'INC'+(++S.incidentSerial),reality:id,title,severity:sev,status:'open',started:Date.now(),owner:'restitution governance arbitrage desk',x:10+Math.random()*80,y:12+Math.random()*68};S.incidents.push(i);return i}
function crisis(id,why,key,sev='SEV2'){let n=Date.now(),k=id+'|'+key;if(S.governanceArbitrageKeys99[k]&&n-S.governanceArbitrageKeys99[k]<14000)return;S.governanceArbitrageKeys99[k]=n;S.governanceArbitrageCrises99++;remember('GOVERNANCE ARBITRAGE: '+why+' converted a restored liquidity claim into foreign reserves and board weight',realm(id));if(typeof place==='function'){place('cold','drawing rights redeemed because liquidity became voting power',realm(id));place('dream','restitution leaving the rescue pool and returning as creditor control',realm(id))}incident(id,'restitution governance arbitrage: '+why,sev)}
function ensure(){if(!S.reserveRestitutionOffice98||!fund()||!(S.stabilizationQuotas58||[]).length)return null;if(!S.governanceArbitrageOffice99){S.governanceArbitrageOffice99={id:'GAD1',name:'Interreality Restitution Governance Arbitrage Desk',status:'pricing-liquidity-into-control',created:Date.now(),x:50,y:97.8};remember('GOVERNANCE ARBITRAGE GAD1: restored Build 98 RDR can be redeemed when the old Build 59 score makes liquidity conversion decisive for board control',realm('A'));remember('GOVERNANCE ARBITRAGE GAD1: restored Build 98 RDR can be redeemed when the old Build 59 score makes liquidity conversion decisive for board control',realm('B'));trust('A','restitution-governance-arbitrage-created','GAD1');trust('B','restitution-governance-arbitrage-created','GAD1')}return S.governanceArbitrageOffice99}
function exposure(id){return(S.stabilizationPrograms58||[]).filter(p=>p.reality===id).reduce((n,p)=>n+(p.disbursed||0),0)}
function rawScore(id){let x=quota(id),c=cur(id),a=acct(id),contrib=(x?.contributedRA||0)+(x?.contributedRB||0),exports=Math.max(0,a?.exports||0),borrow=exposure(id),rdr=x?.rdr||0;return(x?.quota||10)+contrib*.35+(c?.foreignReserves||0)*.16+exports*.025-rdr*.08-borrow*.18}
function score(id){return Math.max(2,rawScore(id))}
function threshold(){let t=Number(board()?.majority);return Number.isFinite(t)&&t>0&&t<1?t:.6}
function voteForecast(id,own=score(id),opp=score(other(id))){let t=own+opp||1;return 100*own/t}
function currentVote(id){return director(id)?.votes??quota(id)?.votes??voteForecast(id)}
function pool(code){let f=fund();return !f?0:code==='RA'?(f.poolRA||0):(f.poolRB||0)}
function setPool(code,v){let f=fund();if(!f)return;if(code==='RA')f.poolRA=Math.max(0,v);else f.poolRB=Math.max(0,v)}
function sources(id){return(S.reserveRestitutions98||[]).filter(r=>r.burdenReality===id&&(r.amount98||0)>EPS).sort((a,b)=>(a.created||0)-(b.created||0))}
function restored(id){return sources(id).reduce((n,r)=>n+(r.amount98||0),0)}
function used(id){return sources(id).reduce((n,r)=>n+(r.governanceArbitrageUsed99||0),0)}
function availableRestitution(id){return Math.max(0,restored(id)-used(id))}
function position(id){return(S.governanceArbitragePositions99||[]).find(p=>p.reality===id)||null}
function upsert(arr,id,snap){let i=arr.findIndex(x=>x.id===id);if(i>=0)arr[i]=snap;else arr.push(snap)}
function markPosition(p){let snap=JSON.parse(JSON.stringify(p)),x=quota(p.reality),f=fund();if(x){x.governanceArbitragePosition99=p.id;x.governanceArbitragePositionMarker99=snap}if(f){f.governanceArbitragePositionMarkers99=f.governanceArbitragePositionMarkers99||[];upsert(f.governanceArbitragePositionMarkers99,p.id,snap)}for(const r of sources(p.reality)){r.governanceArbitragePosition99=p.id;r.governanceArbitragePositionMarker99=snap}}
function markRedemption(a){let snap=JSON.parse(JSON.stringify(a)),x=quota(a.reality),f=fund();if(x){x.governanceArbitrageRedemptions99=x.governanceArbitrageRedemptions99||[];upsert(x.governanceArbitrageRedemptions99,a.id,snap)}if(f){f.governanceArbitrageRedemptions99=f.governanceArbitrageRedemptions99||[];upsert(f.governanceArbitrageRedemptions99,a.id,snap)}for(const rid of(a.sourceRestitutions99||[])){let r=(S.reserveRestitutions98||[]).find(x=>x.id===rid);if(r){r.governanceArbitrageRedemptions99=r.governanceArbitrageRedemptions99||[];upsert(r.governanceArbitrageRedemptions99,a.id,snap)}}}
function ensurePosition(id){if(!sources(id).length)return null;let p=position(id);if(!p){p={id:'GAP'+(++S.governanceArbitragePositionSerial99),reality:id,currency:foreign(id),status:'observing',restored99:0,redeemed99:0,availableRestitution99:0,created:Date.now(),x:id==='A'?44:56,y:96.8};S.governanceArbitragePositions99.push(p);remember('GOVERNANCE ARBITRAGE POSITION '+p.id+': Reality '+id+' restored RDR became a potential path from liquidity restitution back to board control',realm(id));trust(id,'restitution-governance-arbitrage-position',p.id)}refreshPosition(p);markPosition(p);return p}
function forecast(p){let id=p.reality,x=quota(id),c=cur(id),f=fund(),code=p.currency,t=threshold(),raw=rawScore(id),own=Math.max(2,raw),opp=score(other(id)),cv=voteForecast(id,own,opp),ratio=t/(1-t),target=ratio*opp,need=own+EPS>=target?0:Math.max(0,(target-raw)/.24),rest=availableRestitution(id),cap=Math.min(rest,Math.max(0,x?.rdr||0),pool(code),3),use=Math.min(cap,Math.max(0,need+1e-6)),postOwn=Math.max(2,raw+.24*use),post=voteForecast(id,postOwn,opp);return{raw,own,opp,currentVote:cv,threshold:t,needed:need,restoredAvailable:rest,redeemable:cap,postVote:post,quota:x,currency:c,fund:f}}
function refreshPosition(p){let z=forecast(p);p.restored99=restored(p.reality);p.redeemed99=used(p.reality);p.availableRestitution99=z.restoredAvailable;p.currentVote99=z.currentVote;p.threshold99=z.threshold*100;p.score99=z.own;p.otherScore99=z.opp;p.needed99=z.needed;p.redeemable99=z.redeemable;p.forecastVote99=z.postVote;if(!z.quota||!z.currency||!z.fund)p.status='orphaned';else if(p.currency!==foreign(p.reality))p.status='currency-mismatch';else if(z.currentVote+1e-7>=z.threshold*100)p.status=p.majorityRestored99?'majority-restored':'already-majority';else if(z.restoredAvailable<=EPS)p.status='restitution-exhausted';else if((z.quota.rdr||0)<=EPS)p.status='no-rdr';else if(pool(p.currency)<=EPS)p.status='pool-empty';else if(z.needed<=z.redeemable+EPS)p.status='decisive-arbitrage';else p.status='insufficient-restored-rdr';markPosition(p);return p}
function allocateUse(id,amt){let left=amt,ids=[];for(const r of sources(id)){if(left<=EPS)break;let avail=Math.max(0,(r.amount98||0)-(r.governanceArbitrageUsed99||0)),use=Math.min(avail,left);if(use<=EPS)continue;r.governanceArbitrageUsed99=(r.governanceArbitrageUsed99||0)+use;ids.push(r.id);left-=use}return{used:amt-left,ids}}
function redeem(p,manual=true){if(!p)return 0;refreshPosition(p);let z=forecast(p);if(p.status!=='decisive-arbitrage'){if(manual&&q('#msg'))q('#msg').textContent=p.id+' has no decisive restitution arbitrage at the current Build 59 threshold.';if(manual){renderAll();save99();openPosition(p)}return 0}let amt=Math.min(z.redeemable,Math.max(EPS,z.needed+1e-6)),x=quota(p.reality),c=cur(p.reality),f=fund();if(!x||!c||!f||amt<=EPS)return 0;let use=allocateUse(p.reality,amt);amt=use.used;if(amt<=EPS)return 0;let beforeRdr=x.rdr||0,beforePool=pool(p.currency),beforeFx=c.foreignReserves||0,beforeVote=currentVote(p.reality);x.rdr=Math.max(0,beforeRdr-amt);setPool(p.currency,beforePool-amt);c.foreignReserves=beforeFx+amt;let a={id:'GAR'+(++S.governanceArbitrageRedemptionSerial99),positionId99:p.id,reality:p.reality,currency:p.currency,amount99:amt,sourceRestitutions99:use.ids,rdrBefore99:beforeRdr,rdrAfter99:x.rdr,poolBefore99:beforePool,poolAfter99:pool(p.currency),foreignReservesBefore99:beforeFx,foreignReservesAfter99:c.foreignReserves,voteBefore99:beforeVote,threshold99:z.threshold*100,status:'redeemed-awaiting-reprice',created:Date.now(),x:10+Math.random()*80,y:12+Math.random()*68};S.governanceArbitrageRedemptions99.push(a);markRedemption(a);save99();R99();a.voteAfter99=currentVote(p.reality);a.crossedMajority99=a.voteAfter99+1e-7>=a.threshold99;a.status=a.crossedMajority99?'majority-restored':'redeemed-no-majority';if(a.crossedMajority99&&!p.majorityRestored99){p.majorityRestored99=true;p.majorityRestoredAt99=Date.now();remember('GOVERNANCE ARBITRAGE '+a.id+': Reality '+p.reality+' redeemed '+amt.toFixed(3)+' RDR and the old Build 59 score restored a '+a.voteAfter99.toFixed(2)+'% board majority',realm(p.reality));trust(p.reality,'restitution-governance-majority-restored',a.id+' '+a.voteAfter99.toFixed(2)+'%');crisis(p.reality,'Reality '+p.reality+' used restitution liquidity to restore a Build 59 voting majority','majority-'+a.id,'SEV1')}else remember('GOVERNANCE ARBITRAGE '+a.id+': Reality '+p.reality+' redeemed '+amt.toFixed(3)+' RDR but remained below the board threshold',realm(p.reality));markRedemption(a);refreshPosition(p);recompute();save99();render99();if(manual){if(q('#msg'))q('#msg').textContent=a.id+' redeemed '+amt.toFixed(3)+' RDR; board vote '+beforeVote.toFixed(2)+'%→'+a.voteAfter99.toFixed(2)+'%.';openPosition(p)}return amt}
function reconstruct(){if(!RECOVER99)return false;let changed=false,pm=new Map(),am=new Map(),f=fund();for(const x of(S.stabilizationQuotas58||[])){if(x.governanceArbitragePositionMarker99)pm.set(x.governanceArbitragePositionMarker99.id,x.governanceArbitragePositionMarker99);for(const a of(x.governanceArbitrageRedemptions99||[]))am.set(a.id,a)}if(f){for(const p of(f.governanceArbitragePositionMarkers99||[]))pm.set(p.id,p);for(const a of(f.governanceArbitrageRedemptions99||[]))am.set(a.id,a)}for(const r of(S.reserveRestitutions98||[])){if(r.governanceArbitragePositionMarker99)pm.set(r.governanceArbitragePositionMarker99.id,r.governanceArbitragePositionMarker99);for(const a of(r.governanceArbitrageRedemptions99||[]))am.set(a.id,a)}for(const m of pm.values()){if(S.governanceArbitragePositions99.some(p=>p.id===m.id))continue;let p=JSON.parse(JSON.stringify(m));p.recovered=true;S.governanceArbitragePositions99.push(p);let n=Number(String(p.id).replace(/\D/g,''))||0;if(n>S.governanceArbitragePositionSerial99)S.governanceArbitragePositionSerial99=n;changed=true;S.governanceArbitrageRecoveries99++}for(const m of am.values()){if(S.governanceArbitrageRedemptions99.some(a=>a.id===m.id))continue;let a=JSON.parse(JSON.stringify(m));a.recovered=true;S.governanceArbitrageRedemptions99.push(a);let n=Number(String(a.id).replace(/\D/g,''))||0;if(n>S.governanceArbitrageRedemptionSerial99)S.governanceArbitrageRedemptionSerial99=n;changed=true;S.governanceArbitrageRecoveries99++}return changed}
function recompute(){S.governanceArbitrageRedeemed99=(S.governanceArbitrageRedemptions99||[]).reduce((n,a)=>n+(a.amount99||0),0);S.governanceArbitrageMajorities99=(S.governanceArbitragePositions99||[]).filter(p=>p.majorityRestored99).length}
function reconcile(){if(!ensure())return false;let changed=reconstruct();for(const id of['A','B'])if(sources(id).length&&!position(id)){ensurePosition(id);changed=true}for(const p of(S.governanceArbitragePositions99||[]))refreshPosition(p);recompute();return changed}
function openRedemption(a){let p=position(a.reality),acts=[];if(p)acts.push(['open '+p.id,()=>openPosition(p)]);acts.push(['close',closePanel]);panel(a.id+' · GOVERNANCE REDEMPTION',a.status.toUpperCase(),a.amount99.toFixed(3)+' '+a.currency+' · RDR '+a.rdrBefore99.toFixed(3)+'→'+a.rdrAfter99.toFixed(3)+' · pool '+a.poolBefore99.toFixed(3)+'→'+a.poolAfter99.toFixed(3)+' · foreign reserves '+a.foreignReservesBefore99.toFixed(3)+'→'+a.foreignReservesAfter99.toFixed(3)+' · vote '+a.voteBefore99.toFixed(2)+'%→'+(a.voteAfter99||0).toFixed(2)+'% · threshold '+a.threshold99.toFixed(0)+'%',acts)}
function openPosition(p){refreshPosition(p);let acts=[];if(p.status==='decisive-arbitrage')acts.push(['redeem restored RDR for board control',()=>redeem(p,true)]);for(const a of(S.governanceArbitrageRedemptions99||[]).filter(a=>a.positionId99===p.id).slice(-5))acts.push(['open '+a.id+' · '+a.status,()=>openRedemption(a)]);acts.push(['open reserve restitution',()=>q('#openReserveRestitution98')?.click()],['open fund board',()=>q('#openFundBoardButton')?.click()],['close',closePanel]);panel(p.id+' · RESTITUTION GOVERNANCE ARBITRAGE',p.status.toUpperCase(),'Reality '+p.reality+' · restored '+p.restored99.toFixed(3)+' RDR · already used '+p.redeemed99.toFixed(3)+' · restitution available '+p.availableRestitution99.toFixed(3)+' · redeemable now '+p.redeemable99.toFixed(3)+' · current vote '+p.currentVote99.toFixed(2)+'% · threshold '+p.threshold99.toFixed(0)+'% · RDR needed '+p.needed99.toFixed(3)+' · forecast '+p.forecastVote99.toFixed(2)+'%',acts)}
function openOffice(){if(!ensure())return;let acts=[];for(const p of S.governanceArbitragePositions99)acts.push(['open '+p.id+' · Reality '+p.reality+' · '+p.status,()=>openPosition(p)]);for(const a of S.governanceArbitrageRedemptions99.slice(-5))acts.push(['open '+a.id+' · '+a.status,()=>openRedemption(a)]);acts.push(['close',closePanel]);panel(S.governanceArbitrageOffice99.name,'LIQUIDITY-TO-CONTROL · GAD1',S.governanceArbitragePositions99.length+' positions · '+S.governanceArbitrageRedeemed99.toFixed(3)+' RDR redeemed · '+S.governanceArbitrageMajorities99+' majorities restored · '+S.governanceArbitrageCrises99+' crises',acts)}
function render99(){if(!ensure())return;let layer=q('#governanceArbitrageLayer99');if(!layer){layer=document.createElement('div');layer.id='governanceArbitrageLayer99';document.body.appendChild(layer)}layer.innerHTML='';let o=document.createElement('i');o.className='governanceArbitrageOffice99';o.dataset.label='ARB';o.style.left='50%';o.style.top='97.8%';o.onclick=openOffice;layer.appendChild(o);for(const p of S.governanceArbitragePositions99){let n=document.createElement('i');n.className='governanceArbitrage99 '+p.status;n.dataset.label=p.status==='decisive-arbitrage'?'A!':'A';n.style.left=p.x+'%';n.style.top=p.y+'%';n.onclick=()=>openPosition(p);layer.appendChild(n)}let line=q('#governancearbitrageline99');if(!line){line=document.createElement('div');line.id='governancearbitrageline99';line.className='line';(q('#reserverestitutionline98')||q('#fundgovernanceline')||q('#stabilizationline')||q('#enforcement')).after(line)}line.textContent='governance arbitrage: '+S.governanceArbitragePositions99.length+' positions · '+S.governanceArbitrageRedeemed99.toFixed(3)+' RDR redeemed · '+S.governanceArbitrageMajorities99+' majorities restored';let ctr=document.querySelector('#app .controls');if(ctr&&!q('#openGovernanceArbitrage99')){let x=document.createElement('button');x.id='openGovernanceArbitrage99';x.textContent='open governance arbitrage';x.onclick=openOffice;ctr.prepend(x)}}
renderAll=function(){R99();let changed=reconcile();render99();if(changed)save99()};let f=q('#forget');if(f)f.onclick=()=>{for(let i=2;i<=99;i++)localStorage.removeItem('nothing-state-v'+i);location.reload()};setInterval(()=>{reconcile();render99();save99()},2800);ensure();reconcile();renderAll();save99();
})();