(()=>{
const BS46=save,BR46=renderAll,O46=JSON.parse(localStorage.getItem('nothing-state-v46')||'null')||{},cl=(v,a,b)=>Math.max(a,Math.min(b,v)),pick=a=>a&&a.length?a[Math.floor(Math.random()*a.length)]:null;
const CORE46=['runtime-policy','quorum-client','identity-parser','archive-codec','rift-core'];
S.namespaces46=O46.namespaces46||[];
S.maintainers46=O46.maintainers46||[];
S.namespaceDisputes46=O46.namespaceDisputes46||[];
S.governanceVotes46=O46.governanceVotes46||[];
S.namespaceSerial46=O46.namespaceSerial46||0;
S.maintainerSerial46=O46.maintainerSerial46||0;
S.namespaceDisputeSerial46=O46.namespaceDisputeSerial46||0;
S.governanceVoteSerial46=O46.governanceVoteSerial46||0;
S.namespaceTransfers46=O46.namespaceTransfers46||0;
S.namespaceAbandonments46=O46.namespaceAbandonments46||0;
S.emergencyTakeovers46=O46.emergencyTakeovers46||0;
S.packageForks46=O46.packageForks46||0;
S.maintainerElections46=O46.maintainerElections46||0;
S.canonicalizations46=O46.canonicalizations46||0;
S.governanceRebuilds46=O46.governanceRebuilds46||0;
S.namespaceSplits46=O46.namespaceSplits46||0;
S.governanceCrises46=O46.governanceCrises46||0;
S.lastGovernanceCrisis46=O46.lastGovernanceCrisis46||0;
S.governanceKeys46=O46.governanceKeys46||{};
S.namespaces46=S.namespaces46.map((n,i)=>Object.assign({id:n.id||'NS'+(i+1),reality:n.reality||'A',name:n.name||'unnamed',owner:n.owner||'unknown maintainer',previousOwner:n.previousOwner||null,maintainers:n.maintainers||[n.owner||'unknown maintainer'],canonicalPackageId:n.canonicalPackageId||null,status:n.status||'governed',succession:n.succession||'dependency-vote',legitimacy:Number.isFinite(n.legitimacy)?n.legitimacy:.62,generation:n.generation||1,stewardSince:n.stewardSince||Date.now(),abandonedAt:n.abandonedAt||null,emergencyCount:n.emergencyCount||0,forks:n.forks||[],activity:n.activity||0,x:Number.isFinite(n.x)?n.x:10+Math.random()*80,y:Number.isFinite(n.y)?n.y:12+Math.random()*68},n));
S.maintainers46=S.maintainers46.map((m,i)=>Object.assign({id:m.id||'M46'+(i+1),reality:m.reality||'A',namespaceId:m.namespaceId||null,name:m.name||'unknown',role:m.role||'lead',status:m.status||'active',legitimacy:Number.isFinite(m.legitimacy)?m.legitimacy:.6,fatigue:Number.isFinite(m.fatigue)?m.fatigue:.12,contributions:m.contributions||0,appointed:m.appointed||Date.now(),departed:m.departed||null},m));
S.namespaceDisputes46=S.namespaceDisputes46.map((d,i)=>Object.assign({id:d.id||'ND'+(i+1),reality:d.reality||'A',namespaceId:d.namespaceId||null,status:d.status||'open',reason:d.reason||'succession',candidates:d.candidates||[],votes:d.votes||{},winner:d.winner||null,created:d.created||Date.now(),resolved:d.resolved||null,x:Number.isFinite(d.x)?d.x:10+Math.random()*80,y:Number.isFinite(d.y)?d.y:12+Math.random()*68},d));
function save46(){BS46();localStorage.setItem('nothing-state-v46',JSON.stringify({namespaces46:S.namespaces46,maintainers46:S.maintainers46,namespaceDisputes46:S.namespaceDisputes46,governanceVotes46:S.governanceVotes46,namespaceSerial46:S.namespaceSerial46,maintainerSerial46:S.maintainerSerial46,namespaceDisputeSerial46:S.namespaceDisputeSerial46,governanceVoteSerial46:S.governanceVoteSerial46,namespaceTransfers46:S.namespaceTransfers46,namespaceAbandonments46:S.namespaceAbandonments46,emergencyTakeovers46:S.emergencyTakeovers46,packageForks46:S.packageForks46,maintainerElections46:S.maintainerElections46,canonicalizations46:S.canonicalizations46,governanceRebuilds46:S.governanceRebuilds46,namespaceSplits46:S.namespaceSplits46,governanceCrises46:S.governanceCrises46,lastGovernanceCrisis46:S.lastGovernanceCrisis46,governanceKeys46:S.governanceKeys46}))}save=save46;
const realm=id=>S.real[id],pkg=id=>(S.packages45||[]).find(p=>p.id===id),ns=id=>S.namespaces46.find(n=>n.id===id),maint=id=>S.maintainers46.find(m=>m.id===id),dispute=id=>S.namespaceDisputes46.find(d=>d.id===id),artifact=id=>(S.buildArtifacts44||[]).find(a=>a.id===id),sbomFor=id=>[...(S.sboms45||[])].reverse().find(s=>s.artifactId===id&&s.status==='current');
function hash46(s){let h=2166136261>>>0;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)>>>0}return h.toString(16).padStart(8,'0')}
function vscore(v){return String(v||'0').split('.').reduce((n,x,i)=>n+(parseInt(x)||0)*Math.pow(100,2-i),0)}
function bump(v,major=false){let x=String(v||'0.0.0').split('.').map(n=>parseInt(n)||0);while(x.length<3)x.push(0);if(major){x[0]++;x[1]=0;x[2]=0}else{x[2]++}return x.join('.')}
function activeRoot(id){let accepted=S.trustPolicies?.[id]?.acceptedRoots||[];return [...(S.trustRoots||[])].filter(r=>accepted.includes(r.id)&&r.status==='active').sort((a,b)=>(b.strength||0)-(a.strength||0))[0]||null}
function packagesFor(id,name){return (S.packages45||[]).filter(p=>p.reality===id&&p.name===name)}
function latestPackage(id,name){return packagesFor(id,name).filter(p=>['active','compromised-release'].includes(p.status)).sort((a,b)=>vscore(b.version)-vscore(a.version))[0]||packagesFor(id,name).sort((a,b)=>vscore(b.version)-vscore(a.version))[0]||null}
function seatFor(namespaceId,name){return S.maintainers46.find(m=>m.namespaceId===namespaceId&&m.name===name&&m.status==='active')}
function addSeat(n,name,role='co-maintainer',leg=.58){if(seatFor(n.id,name))return seatFor(n.id,name);let m={id:'M46'+(++S.maintainerSerial46),reality:n.reality,namespaceId:n.id,name,role,status:'active',legitimacy:leg,fatigue:.08,contributions:0,appointed:Date.now(),departed:null};S.maintainers46.push(m);if(!n.maintainers.includes(name))n.maintainers.push(name);return m}
function ensureNamespaces(){for(const id of ['A','B'])for(const name of CORE46){if(S.namespaces46.some(n=>n.reality===id&&n.name===name))continue;let p=latestPackage(id,name);if(!p)continue;let n={id:'NS'+(++S.namespaceSerial46),reality:id,name,owner:p.maintainer||'unknown maintainer',previousOwner:null,maintainers:[p.maintainer||'unknown maintainer'],canonicalPackageId:p.id,status:'governed',succession:'dependency-vote',legitimacy:.62,generation:1,stewardSince:Date.now(),abandonedAt:null,emergencyCount:0,forks:[],activity:0,x:10+Math.random()*80,y:12+Math.random()*68};S.namespaces46.push(n);addSeat(n,n.owner,'lead',.64);remember('PACKAGE NAMESPACE '+n.id+': '+n.name+' became a governed name under '+n.owner,realm(id))}}
function usedBy(id,name){let set=new Set();for(const s of(S.sboms45||[]).filter(s=>s.reality===id&&s.status==='current'))if(s.components.some(pid=>pkg(pid)?.name===name))set.add(s.artifactId);return set.size}
function reverseDependents(id,name){return [...new Set((S.packages45||[]).filter(p=>p.reality===id&&p.dependencies?.includes(name)&&p.status!=='yanked').map(p=>p.name))]}
function candidatePackage(n,candidate){return packagesFor(n.reality,n.name).filter(p=>p.maintainer===candidate&&['active','compromised-release','disputed-release'].includes(p.status)).sort((a,b)=>vscore(b.version)-vscore(a.version))[0]||null}
function publishSuccessor(n,owner,opts={}){let old=pkg(n.canonicalPackageId)||latestPackage(n.reality,n.name),version=bump(old?.version||'1.0.0',!!opts.major),root=activeRoot(n.reality);S.packageSerial45=S.packageSerial45||0;let p={id:'PKG'+(++S.packageSerial45),reality:n.reality,name:n.name,version,maintainer:owner,registry:'registry/'+n.reality,status:'active',dependencies:[...(old?.dependencies||[])],rootId:root?.id||null,integrity:hash46([n.reality,n.name,version,owner,Date.now()].join('|')),published:Date.now(),patchedFrom:old?.id||null,foreignOf:null,downloads:0,compromisedAt:null,x:10+Math.random()*80,y:12+Math.random()*68};S.packages45.push(p);S.packagesPublished45=(S.packagesPublished45||0)+1;remember('SUCCESSOR RELEASE '+p.id+': '+owner+' published '+n.name+'@'+version+' under namespace '+n.id,realm(n.reality));return p}
function openDispute(n,reason='succession',extra=[]){let existing=[...S.namespaceDisputes46].reverse().find(d=>d.namespaceId===n.id&&d.status==='open');if(existing)return existing;let candidates=[...new Set([...(n.maintainers||[]),...extra,'dependency coalition','registry emergency custodian'].filter(Boolean))].slice(0,5),d={id:'ND'+(++S.namespaceDisputeSerial46),reality:n.reality,namespaceId:n.id,status:'open',reason,candidates,votes:{},winner:null,created:Date.now(),resolved:null,x:10+Math.random()*80,y:12+Math.random()*68};S.namespaceDisputes46.push(d);n.status='disputed';remember('NAMESPACE DISPUTE '+d.id+': '+n.name+' has no uncontested successor',realm(n.reality));if(typeof place==='function')place('cold','package name with two governments',realm(n.reality));return d}
function abandon(n,manual=true){if(!n||n.status==='abandoned')return;let lead=seatFor(n.id,n.owner);if(lead){lead.status='missing';lead.departed=Date.now()}n.previousOwner=n.owner;n.owner='nobody';n.status='abandoned';n.abandonedAt=Date.now();S.namespaceAbandonments46++;remember('NAMESPACE ABANDONED '+n.id+': '+n.name+' still runs in production after its maintainer disappeared',realm(n.reality));if(typeof place==='function'){place('cold','orphaned package still running the state',realm(n.reality));place('dream','namespace waiting for inheritance papers',realm(n.reality))}openDispute(n,'maintainer-abandoned',n.previousOwner?[n.previousOwner]:[]);governanceCrisis(n.reality,'abandonment');if(manual){$('#msg').textContent=n.name+' is abandoned. Existing binaries still depend on it.';renderAll();save46();openNamespace(n)}}
function recruit(n){let names=['archive release clerk','court software steward','career package administrator','traveler maintainer','dependency coalition'];let who=pick(names.filter(x=>!n.maintainers.includes(x)))||('co-maintainer '+(n.maintainers.length+1));addSeat(n,who,'co-maintainer',.55+Math.random()*.12);n.legitimacy=cl(n.legitimacy+.025,.1,.99);remember('CO-MAINTAINER ADDED: '+who+' joined '+n.name,realm(n.reality));$('#msg').textContent=who+' can now inherit '+n.name+' if the lead maintainer disappears.';renderAll();save46();openNamespace(n)}
function voteDispute(d){if(!d||d.status!=='open')return;let n=ns(d.namespaceId),dependents=reverseDependents(d.reality,n.name),production=usedBy(d.reality,n.name),electors=[...dependents];for(let i=0;i<Math.max(1,production);i++)electors.push('production-'+(i+1));let tally={};for(const c of d.candidates)tally[c]=0;for(const e of electors){let scored=d.candidates.map(c=>({c,s:parseInt(hash46(e+'|'+c+'|'+n.generation).slice(-4),16)+(c===n.previousOwner?1800:0)+(c==='dependency coalition'?production*900:0)})).sort((a,b)=>b.s-a.s),choice=scored[0]?.c||d.candidates[0];tally[choice]=(tally[choice]||0)+1;S.governanceVotes46.push({id:'GV'+(++S.governanceVoteSerial46),disputeId:d.id,elector:e,choice,created:Date.now()})}d.votes=tally;S.maintainerElections46++;let winner=Object.entries(tally).sort((a,b)=>b[1]-a[1])[0]?.[0];if(winner){d.winner=winner;remember('DEPENDENCY VOTE '+d.id+': downstream software selected '+winner+' to inherit '+n.name,realm(d.reality));if(typeof place==='function')place('dream','dependency graph acting as electorate',realm(d.reality));transferNamespace(n,winner,d)}renderAll();save46();openDisputePanel(d)}
function transferNamespace(n,winner,d=null,emergency=false){if(!n||!winner)return;let old=n.owner==='nobody'?(n.previousOwner||'nobody'):n.owner;n.previousOwner=old;n.owner=winner;n.status=emergency?'emergency':'governed';n.generation++;n.stewardSince=Date.now();n.abandonedAt=null;n.legitimacy=cl((n.legitimacy||.5)+(emergency?.01:.045),.1,.99);if(!n.maintainers.includes(winner))n.maintainers.push(winner);addSeat(n,winner,emergency?'emergency lead':'lead',emergency?.48:.65);let p=candidatePackage(n,winner)||publishSuccessor(n,winner,{major:false});n.canonicalPackageId=p.id;S.namespaceTransfers46++;if(emergency){S.emergencyTakeovers46++;n.emergencyCount++;}if(d){d.status='resolved';d.resolved=Date.now();d.winner=winner}remember((emergency?'EMERGENCY NAMESPACE TAKEOVER: ':'NAMESPACE SUCCESSION: ')+winner+' now controls '+n.name+' after '+old,realm(n.reality));if(typeof place==='function')place(emergency?'cold':'warm',emergency?'temporary package maintainer with production authority':'package succession accepted by dependents',realm(n.reality));$('#msg').textContent=winner+' now controls '+n.name+'. Existing binaries still contain older lineage until rebuilt.'}
function emergencyTakeover(n){if(!n)return;let activeCritical=(S.advisories45||[]).some(a=>a.reality===n.reality&&a.name===n.name&&a.severity==='critical'&&a.status!=='withdrawn'),who=activeCritical?'security incident custodian':'registry emergency custodian';let d=openDispute(n,'emergency-maintenance',[who]);transferNamespace(n,who,d,true);governanceCrisis(n.reality,'emergency-takeover');renderAll();save46();openNamespace(n)}
function forkNamespace(n){if(!n)return;let owner='community fork '+(S.packageForks46+1),p=publishSuccessor(n,owner,{major:true});n.forks.push(p.id);S.packageForks46++;let d=openDispute(n,'canonical-fork',[owner,n.owner]);d.candidates=[...new Set([n.owner,owner,'dependency coalition'])];remember('CANONICAL FORK '+p.id+': '+owner+' claims '+n.name+' is the real continuation',realm(n.reality));if(typeof place==='function'){place('cold','same package name two lineages',realm(n.reality));place('dream','fork demanding the canonical name back',realm(n.reality))}governanceCrisis(n.reality,'canonical-fork');$('#msg').textContent=p.id+' forked '+n.name+' under the same canonical package name.';renderAll();save46();openDisputePanel(d)}
function keepBoth(d){if(!d||d.status!=='open')return;let n=ns(d.namespaceId);d.status='split';d.resolved=Date.now();n.status='split';S.namespaceSplits46++;remember('NAMESPACE SPLIT '+d.id+': rival maintainers remain canonical for '+n.name,realm(n.reality));if(typeof place==='function'){place('cold','registry returning two canonical answers',realm(n.reality));place('dream','same package identity different governments',realm(n.reality))}governanceCrisis(n.reality,'split');renderAll();save46();openNamespace(n)}
function chooseCandidate(d,c){if(!d||d.status!=='open')return;let n=ns(d.namespaceId),p=candidatePackage(n,c);if(!p&&c!==n.owner)p=publishSuccessor(n,c);transferNamespace(n,c,d,false);if(p)n.canonicalPackageId=p.id;for(const x of packagesFor(n.reality,n.name)){if(x.id===n.canonicalPackageId)continue;if(['active','compromised-release'].includes(x.status)&&x.maintainer!==c&&x.published>=(d.created||0))x.status='disputed-release'}S.canonicalizations46++;remember('CANONICALIZATION '+d.id+': registry recognizes '+c+' lineage for '+n.name,realm(n.reality));renderAll();save46();openNamespace(n)}
function signRebuild(a){let r=activeRoot(a.reality);if(!r)return;S.attestationSerial44=S.attestationSerial44||0;S.provenance44=S.provenance44||[];S.provenance44.push({id:'AT'+(++S.attestationSerial44),artifactId:a.id,reality:a.reality,builderId:a.builderId,sourceRef:a.sourceRef,recipeHash:a.recipeHash,artifactHash:a.artifactHash,rootId:r.id,status:'attested',created:Date.now()});S.trustAudits=S.trustAudits||[];S.trustAuditSerial=S.trustAuditSerial||0;S.trustAudits.push({id:'TA'+(++S.trustAuditSerial),reality:a.reality,remediationId:null,credentialId:null,certificateId:null,rootId:r.id,status:'namespace-governance-attested',created:Date.now(),note:a.id+' canonical namespace '+a.depLock,x:10+Math.random()*80,y:12+Math.random()*68})}
function rebuildCanonical(n){let target=pkg(n.canonicalPackageId);if(!n||!target){$('#msg').textContent='No canonical package lineage is available to rebuild.';return}let touched=0,assign=S.replicaArtifacts44?.[n.reality]||{};for(const [nodeName,aid] of Object.entries(assign)){let old=artifact(aid),s=sbomFor(aid);if(!old||!s)continue;let found=s.components.some(pid=>pkg(pid)?.name===n.name&&pid!==target.id);if(!found)continue;let comps=s.components.map(pid=>pkg(pid)?.name===n.name?target.id:pid);S.artifactSerial44=S.artifactSerial44||0;S.registry45=S.registry45||{A:{generation:1},B:{generation:1}};S.registry45[n.reality]=S.registry45[n.reality]||{generation:1};let gen=++S.registry45[n.reality].generation,a={...old,id:'BIN'+(++S.artifactSerial44),depLock:(old.depLock||'lock')+'|ns46-'+n.id+'-'+n.generation+'-'+gen,recipeHash:hash46((old.recipeHash||'')+'|'+comps.join('|')+'|'+n.id),artifactHash:hash46((old.artifactHash||'')+'|'+comps.join('|')+'|'+n.id+'|'+Date.now()+'|'+nodeName),status:'built',builtAt:Date.now(),reproducedFrom:old.id,x:10+Math.random()*80,y:12+Math.random()*68};S.buildArtifacts44.push(a);S.artifactsBuilt44=(S.artifactsBuilt44||0)+1;signRebuild(a);S.sbomSerial45=S.sbomSerial45||0;let sb={id:'SBOM'+(++S.sbomSerial45),artifactId:a.id,reality:n.reality,components:comps,digest:hash46(a.artifactHash+'|'+comps.join('|')),status:'current',generated:Date.now(),vulnerable:[],x:10+Math.random()*80,y:12+Math.random()*68};S.sboms45.push(sb);s.status='superseded';assign[nodeName]=a.id;touched++}S.governanceRebuilds46+=touched;remember('CANONICAL REBUILD '+n.id+': '+touched+' live replicas rebuilt onto '+target.name+'@'+target.version+' under '+n.owner,realm(n.reality));if(typeof place==='function')place('warm','production rebuilt onto a governance decision',realm(n.reality));$('#msg').textContent=touched+' live replicas rebuilt onto the canonical '+n.name+' lineage. Old artifacts remain historical.';renderAll();save46();openNamespace(n)}
function governanceCrisis(id,reason){if(Date.now()-S.lastGovernanceCrisis46<8000)return false;let key=id+'|'+reason+'|'+Math.floor(Date.now()/20000);if(S.governanceKeys46[key])return false;S.governanceKeys46[key]=1;S.governanceCrises46++;S.lastGovernanceCrisis46=Date.now();for(const rid of ['A','B']){realm(rid).disputes=(realm(rid).disputes||0)+1;remember('PACKAGE GOVERNANCE CRISIS: namespace succession became authority over which code can become reality',realm(rid))}realm(id).timelineDrift=(realm(id).timelineDrift||0)+1;if(typeof place==='function'){place('cold','maintainer key holding constitutional office',realm(id));place('dream','package registry acting like a succession court',realm(id))}S.bailiffMood='asking the package registry who inherited the namespace';return true}
function fatigueTick(){for(const n of S.namespaces46){let lead=seatFor(n.id,n.owner);if(!lead||n.status!=='governed')continue;let pressure=Math.min(.025,usedBy(n.reality,n.name)*.0015+(S.advisories45||[]).filter(a=>a.name===n.name&&a.status!=='withdrawn').length*.004);lead.fatigue=cl(lead.fatigue+pressure*(.15+Math.random()),0,1);n.activity++;if(lead.fatigue>.9&&Math.random()<.004)abandon(n,false)}}
function autonomous(){ensureNamespaces();fatigueTick();for(const n of S.namespaces46){if((n.status==='abandoned'||n.status==='disputed')&&Math.random()<.004){let d=openDispute(n,'autonomous-succession');if(d&&d.status==='open')voteDispute(d);break}if(n.status==='split'&&usedBy(n.reality,n.name)>=3&&Math.random()<.003){governanceCrisis(n.reality,'persistent-split');break}}}
function openMaintainer(m){let n=ns(m.namespaceId),b=[];if(m.status==='active'&&m.role==='lead')b.push(['resign maintainer',()=>{m.status='resigned';m.departed=Date.now();abandon(n);}],['close',closePanel]);else b.push(['close',closePanel]);panel(m.name+' · '+m.role,m.id+' · '+m.status,'legitimacy '+Math.round(m.legitimacy*100)+'% · fatigue '+Math.round(m.fatigue*100)+'% · contributions '+m.contributions,b)}
function openDisputePanel(d){let n=ns(d.namespaceId),b=[];if(d.status==='open'){b.push(['let dependencies vote',()=>voteDispute(d)]);for(const c of d.candidates.slice(0,4))b.push(['recognize '+c,()=>chooseCandidate(d,c)]);b.push(['keep both canonical',()=>keepBoth(d)])}b.push(['close',closePanel]);let tally=Object.entries(d.votes||{}).map(([k,v])=>k+': '+v).join('\n')||'no votes yet';panel(d.id+' · '+d.status.toUpperCase(),n?.name+' · '+d.reason,'candidates: '+d.candidates.join(', ')+'\n'+tally+(d.winner?'\nwinner '+d.winner:''),b)}
function openNamespace(n){let p=pkg(n.canonicalPackageId),seats=S.maintainers46.filter(m=>m.namespaceId===n.id&&m.status==='active'),d=[...S.namespaceDisputes46].reverse().find(x=>x.namespaceId===n.id&&x.status==='open'),b=[];if(n.status==='governed')b.push(['add co-maintainer',()=>recruit(n)],['maintainer disappears',()=>abandon(n)],['fork canonical package',()=>forkNamespace(n)]);if(['abandoned','disputed'].includes(n.status))b.push(['open succession case',()=>openDisputePanel(openDispute(n))],['emergency registry takeover',()=>emergencyTakeover(n)]);if(n.status==='split')b.push(['open new canonicalization case',()=>openDisputePanel(openDispute(n,'resolve-split',n.maintainers))]);if(p)b.push(['rebuild production onto canonical',()=>rebuildCanonical(n)]);for(const m of seats.slice(0,3))b.push(['open '+m.name,()=>openMaintainer(m)]);if(d)b.push(['open '+d.id,()=>openDisputePanel(d)]);b.push(['close',closePanel]);panel(n.name+' · '+n.status.toUpperCase(),n.id+' · owner '+n.owner+' · generation '+n.generation,'canonical '+(p?p.id+' '+p.version:'none')+' · legitimacy '+Math.round(n.legitimacy*100)+'% · '+usedBy(n.reality,n.name)+' live artifact users\nmaintainers '+(seats.map(m=>m.name).join(', ')||'none')+' · succession '+n.succession,b)}
function openGovernance(id=S.active){ensureNamespaces();let xs=S.namespaces46.filter(n=>n.reality===id),open=S.namespaceDisputes46.filter(d=>d.reality===id&&d.status==='open'),b=[];for(const n of xs)b.push([n.name+' · '+n.status,()=>openNamespace(n)]);for(const d of open.slice(-3))b.push(['open '+d.id,()=>openDisputePanel(d)]);b.push(['audit namespace succession',()=>{for(const n of xs)if(n.status==='abandoned')openDispute(n,'audit');$('#msg').textContent='Registry audit found '+xs.filter(n=>n.status!=='governed').length+' namespaces without ordinary governance.';renderAll();save46();openGovernance(id)}],['close',closePanel]);panel('PACKAGE GOVERNANCE · Reality '+id,xs.length+' namespaces · '+open.length+' open succession cases',S.namespaceTransfers46+' transfers · '+S.namespaceAbandonments46+' abandoned · '+S.packageForks46+' forks · '+S.namespaceSplits46+' splits · '+S.governanceRebuilds46+' replica rebuilds · '+S.governanceCrises46+' crises',b)}
function renderGovernance(){ensureNamespaces();let layer=$('#governanceLayer');if(!layer){layer=document.createElement('div');layer.id='governanceLayer';document.body.appendChild(layer)}layer.innerHTML='';for(const n of S.namespaces46.slice(-18)){let e=document.createElement('i');e.className='namespaceNode '+n.status;e.dataset.label=n.name.slice(0,3).toUpperCase();e.style.left=n.x+'%';e.style.top=n.y+'%';e.onclick=()=>openNamespace(n);layer.appendChild(e)}for(const d of S.namespaceDisputes46.filter(d=>['open','split'].includes(d.status)).slice(-8)){let e=document.createElement('i');e.className='namespaceDispute '+d.status;e.dataset.label=d.id;e.style.left=d.x+'%';e.style.top=d.y+'%';e.onclick=()=>openDisputePanel(d);layer.appendChild(e)}let line=$('#governanceline');if(!line){line=document.createElement('div');line.id='governanceline';line.className='line';($('#dependencyline')||$('#supplyline')||$('#replicaline')||$('#enforcement')).after(line)}let id=S.active,xs=S.namespaces46.filter(n=>n.reality===id),unstable=xs.filter(n=>n.status!=='governed').length;line.textContent='package governance: '+xs.length+' namespaces · '+unstable+' unstable · '+S.namespaceTransfers46+' successions · '+S.packageForks46+' forks · '+S.namespaceSplits46+' splits · '+S.governanceCrises46+' crises';let ctr=document.querySelector('#app .controls');if(ctr&&!$('#openGovernanceButton')){let b=document.createElement('button');b.id='openGovernanceButton';b.textContent='open package governance';b.onclick=()=>openGovernance(S.active);ctr.prepend(b)}}
renderAll=function(){BR46();renderGovernance()};let f=$('#forget');if(f)f.onclick=()=>{for(let i=2;i<=46;i++)localStorage.removeItem('nothing-state-v'+i);location.reload()};
setInterval(()=>{autonomous();renderGovernance();save46()},2300);ensureNamespaces();renderAll();save46();
})();
