(()=>{
const BS51=save,BR51=renderAll,O51=JSON.parse(localStorage.getItem('nothing-state-v51')||'null')||{},cl=(v,a,b)=>Math.max(a,Math.min(b,v)),pick=a=>a&&a.length?a[Math.floor(Math.random()*a.length)]:null;
S.insurers51=O51.insurers51||[];
S.riskPolicies51=O51.riskPolicies51||[];
S.riskClaims51=O51.riskClaims51||[];
S.riskAudits51=O51.riskAudits51||[];
S.insurerSerial51=O51.insurerSerial51||0;
S.policySerial51=O51.policySerial51||0;
S.claimSerial51=O51.claimSerial51||0;
S.riskAuditSerial51=O51.riskAuditSerial51||0;
S.policiesWritten51=O51.policiesWritten51||0;
S.premiumsPaid51=O51.premiumsPaid51||0;
S.claimsFiled51=O51.claimsFiled51||0;
S.claimsPaid51=O51.claimsPaid51||0;
S.claimsDenied51=O51.claimsDenied51||0;
S.coverageFailures51=O51.coverageFailures51||0;
S.insurerFailures51=O51.insurerFailures51||0;
S.publicReinsurance51=O51.publicReinsurance51||0;
S.captivePolicies51=O51.captivePolicies51||0;
S.riskStandardPressure51=O51.riskStandardPressure51||0;
S.systemicRiskEvents51=O51.systemicRiskEvents51||0;
S.insuranceCrises51=O51.insuranceCrises51||0;
S.lastInsuranceCrisis51=O51.lastInsuranceCrisis51||0;
S.insuranceKeys51=O51.insuranceKeys51||{};
S.lastInsuranceTick51=O51.lastInsuranceTick51||Date.now();
function save51(){BS51();localStorage.setItem('nothing-state-v51',JSON.stringify({insurers51:S.insurers51,riskPolicies51:S.riskPolicies51,riskClaims51:S.riskClaims51,riskAudits51:S.riskAudits51,insurerSerial51:S.insurerSerial51,policySerial51:S.policySerial51,claimSerial51:S.claimSerial51,riskAuditSerial51:S.riskAuditSerial51,policiesWritten51:S.policiesWritten51,premiumsPaid51:S.premiumsPaid51,claimsFiled51:S.claimsFiled51,claimsPaid51:S.claimsPaid51,claimsDenied51:S.claimsDenied51,coverageFailures51:S.coverageFailures51,insurerFailures51:S.insurerFailures51,publicReinsurance51:S.publicReinsurance51,captivePolicies51:S.captivePolicies51,riskStandardPressure51:S.riskStandardPressure51,systemicRiskEvents51:S.systemicRiskEvents51,insuranceCrises51:S.insuranceCrises51,lastInsuranceCrisis51:S.lastInsuranceCrisis51,insuranceKeys51:S.insuranceKeys51,lastInsuranceTick51:S.lastInsuranceTick51}))}save=save51;
const realm=id=>S.real[id],ns=id=>(S.namespaces46||[]).find(n=>n.id===id),pkg=id=>(S.packages45||[]).find(p=>p.id===id),contract=id=>(S.vendorContracts48||[]).find(c=>c.id===id),vendor=id=>(S.vendorProfiles48||[]).find(v=>v.id===id),treasury=id=>(S.packageTreasuries47||[]).find(t=>t.namespaceId===id),standard=id=>(S.standards50||[]).find(s=>s.id===id);
function hash51(s){let h=2166136261>>>0;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)>>>0}return h.toString(16).padStart(8,'0')}
function ensureInsurers(){for(const id of ['A','B']){let defs=[[id+' Mutual Risk Pool','public',48],[id+' Continuity Underwriters','private',34],[id+' Archive Indemnity Exchange','mutual',28]];for(const [name,type,capital] of defs)if(!S.insurers51.some(x=>x.reality===id&&x.name===name))S.insurers51.push({id:'INS'+(++S.insurerSerial51),reality:id,name,type,status:'solvent',capital,reserves:capital*.35,riskAppetite:.58+Math.random()*.2,credibility:.68,policies:0,claimsPaid:0,claimsDenied:0,failures:0,capturedBy:null,created:Date.now(),x:10+Math.random()*80,y:12+Math.random()*68})}}
const insurer=id=>S.insurers51.find(x=>x.id===id), policiesFor=id=>S.riskPolicies51.filter(p=>p.insurerId===id&&p.status==='active'), activePolicyForContract=id=>[...S.riskPolicies51].reverse().find(p=>p.contractId===id&&p.status==='active');
function currentCerts(v,id){let now=Date.now();return (S.certifications50||[]).filter(c=>c.vendorId===v.id&&c.reality===id&&['certified','provisional'].includes(c.status)&&c.expires>now&&standard(c.standardId)?.status==='ratified')}
function unresolvedFindings(c){return (S.complianceFindings49||[]).filter(f=>f.contractId===c.id&&!['verified','closed'].includes(f.status)).length}
function vulnerableExposure(c){let n=ns(c.namespaceId);if(!n)return 0;let ids=new Set((S.sboms45||[]).filter(s=>s.reality===c.reality&&s.status==='current'&&(s.components||[]).some(pid=>pkg(pid)?.name===n.name)).flatMap(s=>s.vulnerable||[]));return ids.size}
function riskScore(c){let v=vendor(c.vendorId),t=treasury(c.namespaceId),certs=v?currentCerts(v,c.reality):[],score=.18+(c.breaches||0)*.12+(c.lockIn||0)*.25+unresolvedFindings(c)*.08+vulnerableExposure(c)*.06+(c.soleSource?.08:0)+(t?.status==='strike'?.09:0)+(t?.status==='bankrupt'?.16:0);if(!certs.length)score+=.16;else score-=Math.min(.12,certs.length*.05);if(v?.status==='debarred')score+=.3;return cl(score,.05,.96)}
function exclusionsFor(c){let xs=[];let p=(S.procurements48||[]).find(p=>p.id===c.procurementId);if(p?.capturedBy===c.vendor)xs.push('vendor-authored procurement criteria');if(c.soleSource)xs.push('sole-source continuity decision');if(vulnerableExposure(c))xs.push('known vulnerable transitive dependency');let certs=currentCerts(vendor(c.vendorId)||{},c.reality);if(certs.some(x=>x.mode==='self'))xs.push('self-certified compliance');if((c.lockIn||0)>.6)xs.push('vendor lock-in migration cost');return xs}
function policyPremium(c,ins){let risk=riskScore(c),base=2.2+(c.value||8)*.08+risk*8,capacity=Math.max(.7,20/Math.max(20,ins.capital));return Math.round(base*capacity*10)/10}
function underwrite(c,insId=null,captive=false,manual=true){if(!c||!['active','stayed'].includes(c.status))return null;ensureInsurers();if(activePolicyForContract(c.id))return activePolicyForContract(c.id);let v=vendor(c.vendorId),ins=captive?null:(insId?insurer(insId):pick(S.insurers51.filter(x=>x.reality===c.reality&&x.status==='solvent')));if(captive&&v){ins={id:'CAP-'+v.id,name:v.name+' Captive Indemnity',reality:c.reality,type:'captive',status:'solvent',capital:Math.max(8,(c.value||8)*1.2),reserves:3,riskAppetite:.98,credibility:.42,policies:0,claimsPaid:0,claimsDenied:0,failures:0,capturedBy:v.name,created:Date.now(),x:10+Math.random()*80,y:12+Math.random()*68};S.insurers51.push(ins);S.captivePolicies51++}if(!ins)return null;let risk=riskScore(c),premium=policyPremium(c,ins),coverage=Math.round(Math.max(6,(c.value||8)*(1.25+risk))*10)/10,deductible=Math.round((1+risk*3)*10)/10,exclusions=exclusionsFor(c),p={id:'POL'+(++S.policySerial51),reality:c.reality,contractId:c.id,namespaceId:c.namespaceId,vendorId:c.vendorId,vendor:c.vendor,insurerId:ins.id,insurer:ins.name,status:'active',risk,premium,coverage,deductible,exclusions,paidPremium:0,claims:0,paidClaims:0,created:Date.now(),expires:Date.now()+90000,captive:ins.type==='captive',x:10+Math.random()*80,y:12+Math.random()*68};S.riskPolicies51.push(p);S.policiesWritten51++;ins.policies++;remember('RISK POLICY '+p.id+': '+ins.name+' insured '+c.id+' at '+Math.round(risk*100)+'% modeled risk',realm(c.reality));if(typeof place==='function')place('warm',p.captive?'vendor insured by its own captive':'insurance certificate beside software contract',realm(c.reality));chargePremium(p,false);if(manual){$('#msg').textContent=p.id+' written for '+c.id+' by '+ins.name+'.';renderAll();save51();openPolicy(p)}return p}
function chargePremium(p,manual=true){if(!p||p.status!=='active')return false;let t=treasury(p.namespaceId),ins=insurer(p.insurerId),due=Math.max(.4,p.premium-p.paidPremium);if(!t||!ins)return false;let pay=Math.min(t.balance,due);t.balance-=pay;ins.capital+=pay;ins.reserves+=pay*.35;p.paidPremium+=pay;S.premiumsPaid51+=pay;if(pay<due){remember('INSURANCE PREMIUM SHORTFALL '+p.id+': package treasury could not fully fund coverage',realm(p.reality));if(p.paidPremium<p.premium*.45)p.status='lapsed'}if(manual){$('#msg').textContent=p.id+' collected '+pay.toFixed(1)+' premium credits.';renderAll();save51();openPolicy(p)}return pay>=due}
function lossReasons(c){let out=[];if((c.breaches||0)>0)out.push('contract breach');if(vulnerableExposure(c)>0)out.push('dependency vulnerability');if((S.procurementProtests49||[]).some(x=>x.contractId===c.id&&x.status==='sustained'))out.push('sustained procurement protest');if((S.complianceFindings49||[]).some(f=>f.contractId===c.id&&['open','stayed','self-certified'].includes(f.status)))out.push('unresolved oversight finding');let n=ns(c.namespaceId);if(n&&(S.replicaRounds43||[]).some(r=>r.reality===c.reality&&r.status==='divergent'))out.push('replicated state divergence');return out}
function fileClaim(p,reason=null,manual=true){if(!p||p.status!=='active')return null;let c=contract(p.contractId);if(!c)return null;reason=reason||pick(lossReasons(c))||'operational loss after compliant deployment';let amount=Math.round(Math.min(p.coverage,Math.max(3,(c.value||8)*(.35+p.risk*.5)))*10)/10,excluded=p.exclusions.some(x=>reason.includes('vulnerability')&&x.includes('vulnerable')||reason.includes('procurement')&&x.includes('procurement')||reason.includes('self-cert')&&x.includes('self-certified')),x={id:'CLM'+(++S.claimSerial51),policyId:p.id,reality:p.reality,contractId:p.contractId,namespaceId:p.namespaceId,vendorId:p.vendorId,insurerId:p.insurerId,reason,amount,status:'filed',excluded,decision:null,paid:0,filed:Date.now(),decided:null,x:10+Math.random()*80,y:12+Math.random()*68};S.riskClaims51.push(x);S.claimsFiled51++;p.claims++;remember('SOFTWARE CLAIM '+x.id+': '+reason+' under '+p.id+' for '+amount+' credits',realm(p.reality));if(typeof place==='function')place('cold','insurance claim filed after certified software failed',realm(p.reality));if(manual){$('#msg').textContent=x.id+' filed for '+reason+'.';renderAll();save51();openClaim(x)}return x}
function decideClaim(x,force=null,manual=true){if(!x||x.status!=='filed')return;let p=S.riskPolicies51.find(p=>p.id===x.policyId),ins=insurer(x.insurerId),t=treasury(x.namespaceId);if(!p||!ins||!t)return;let deny=force==='deny'||(force!=='pay'&&(x.excluded||Math.random()<.12+(ins.capital<10?.18:0)));if(deny){x.status='denied';x.decision=x.excluded?'policy exclusion':'coverage interpretation';x.decided=Date.now();ins.claimsDenied++;S.claimsDenied51++;remember('CLAIM DENIED '+x.id+': '+x.decision+' left package treasury holding the loss',realm(x.reality));if(typeof place==='function')place('cold','insured failure excluded by policy wording',realm(x.reality));insuranceCrisis(x.reality,'claim-denial')}else{let payout=Math.max(0,Math.min(x.amount-p.deductible,p.coverage-p.paidClaims,ins.capital));x.status=payout>0?'paid':'unfunded';x.decision=payout>0?'covered loss':'insurer lacked capital';x.paid=payout;x.decided=Date.now();if(payout>0){ins.capital-=payout;ins.claimsPaid+=payout;t.balance+=payout;p.paidClaims+=payout;S.claimsPaid51++;remember('CLAIM PAID '+x.id+': '+ins.name+' transferred '+payout.toFixed(1)+' credits to package treasury',realm(x.reality));if(typeof place==='function')place('warm','insurance payout keeping package maintenance alive',realm(x.reality))}else{S.coverageFailures51++;remember('COVERAGE FAILURE '+x.id+': valid policy could not fund its promised loss',realm(x.reality));insuranceCrisis(x.reality,'coverage-failure')}}if(ins.capital<3&&ins.status==='solvent')failInsurer(ins);if(manual){$('#msg').textContent=x.id+' '+x.status.toUpperCase()+'.';renderAll();save51();openClaim(x)}}
function failInsurer(ins){ins.status='insolvent';ins.failures++;S.insurerFailures51++;for(const p of policiesFor(ins.id))p.status='orphaned';remember('INSURER FAILURE '+ins.id+': '+ins.name+' became insolvent while '+policiesFor(ins.id).length+' policies depended on it',realm(ins.reality));if(typeof place==='function'){place('cold','insurer failed while insured packages kept running',realm(ins.reality));place('dream','risk transferred to an institution that also failed',realm(ins.reality))}insuranceCrisis(ins.reality,'insurer-failure')}
function reinsure(ins){if(!ins||ins.status!=='insolvent')return;let amount=18+ins.policies*2;ins.capital+=amount;ins.reserves+=amount*.25;ins.status='guaranteed';S.publicReinsurance51++;for(const p of S.riskPolicies51.filter(p=>p.insurerId===ins.id&&p.status==='orphaned'))p.status='active';remember('PUBLIC REINSURANCE: Reality '+ins.reality+' guaranteed '+ins.name+' with '+amount+' credits because too many package contracts depended on it',realm(ins.reality));if(typeof place==='function')place('warm','software insurer declared too interconnected to fail',realm(ins.reality));if(ins.policies>=3)insuranceCrisis(ins.reality,'public-guarantee');renderAll();save51();openInsurer(ins)}
function pushRiskStandard(id){let b=(S.standardsBodies50||[]).find(b=>b.reality===id),ss=(S.standards50||[]).filter(s=>s.reality===id&&s.status==='ratified');if(!ss.length){$('#msg').textContent='No ratified standard exists for the underwriter to pressure.';return}let s=pick(ss),key=pick(Object.keys(s.requirements||{}));if(!key)return;s.version++;s.amendments=(s.amendments||0)+1;s.requirements[key]=cl((s.requirements[key]||.5)+.04,.3,.92);for(const c of (S.certifications50||[]).filter(c=>c.standardId===s.id&&['certified','provisional'].includes(c.status)&&c.version<s.version))c.status='stale';S.riskStandardPressure51++;if(b){b.independence=cl((b.independence||.7)-.025,0,1);b.credibility=cl((b.credibility||.7)-.01,0,1)}for(const p of (S.procurements48||[]).filter(p=>p.reality===id&&['bidding','evaluating'].includes(p.status))){p.requiredStandards50=p.requiredStandards50||[];if(!p.requiredStandards50.includes(s.id))p.requiredStandards50.push(s.id);for(const bid of (S.bids48||[]).filter(x=>x.procurementId===p.id&&['submitted','noncompliant'].includes(x.status))){let ok=(S.certifications50||[]).some(c=>c.standardId===s.id&&c.vendorId===bid.vendorId&&['certified','provisional'].includes(c.status)&&c.version===s.version&&c.expires>Date.now());if(!ok){bid.status='noncompliant';bid.noncompliant50=true}}}remember('ACTUARIAL STANDARD PRESSURE: insurers pushed '+s.id+' v'+s.version+' '+key+' threshold higher after pricing software losses',realm(id));if(typeof place==='function'){place('cold','insurance table rewriting technical standard',realm(id));place('dream','premium model became procurement law',realm(id))}insuranceCrisis(id,'underwriter-rulemaking');renderAll();save51()}
function systemicCheck(ins){let active=policiesFor(ins.id),critical=new Set(active.map(p=>p.namespaceId));if(critical.size>=3&&ins.capital<18){let key=ins.id+'|'+critical.size;if(!S.insuranceKeys51[key]){S.insuranceKeys51[key]=1;S.systemicRiskEvents51++;remember('SYSTEMIC SOFTWARE RISK: '+ins.name+' insures '+critical.size+' package namespaces with only '+ins.capital.toFixed(1)+' capital',realm(ins.reality));if(typeof place==='function')place('cold','one insurer behind several independent dependencies',realm(ins.reality));insuranceCrisis(ins.reality,'systemic-concentration')}}}
function insuranceCrisis(id,reason){if(Date.now()-S.lastInsuranceCrisis51<7000)return false;let key=id+'|'+reason+'|'+Math.floor(Date.now()/20000);if(S.insuranceKeys51[key])return false;S.insuranceKeys51[key]=1;S.insuranceCrises51++;S.lastInsuranceCrisis51=Date.now();for(const rid of ['A','B']){realm(rid).disputes=(realm(rid).disputes||0)+1;remember('INSURANCE CRISIS: pricing software loss became authority over which risks institutions were willing to make real',realm(rid))}if(typeof place==='function'){place('cold','actuarial table beneath software sovereignty',realm(id));place('dream','compliant code insured against being wrong',realm(id))}S.bailiffMood='asking whether a certificate is still valid when the insurer refuses the claim';return true}
function auditRisk(id){let ins=S.insurers51.filter(i=>i.reality===id),ps=S.riskPolicies51.filter(p=>p.reality===id),a={id:'RA'+(++S.riskAuditSerial51),reality:id,capital:ins.reduce((n,i)=>n+i.capital,0),activePolicies:ps.filter(p=>p.status==='active').length,orphaned:ps.filter(p=>p.status==='orphaned').length,claims:S.riskClaims51.filter(c=>c.reality===id).length,denied:S.riskClaims51.filter(c=>c.reality===id&&c.status==='denied').length,created:Date.now()};S.riskAudits51.push(a);S.riskAudits51=S.riskAudits51.slice(-64);remember('RISK AUDIT '+a.id+': '+a.activePolicies+' active policies backed by '+a.capital.toFixed(1)+' capital',realm(id));return a}
function openClaim(x){let p=S.riskPolicies51.find(p=>p.id===x.policyId),b=[];if(x.status==='filed')b.push(['pay claim',()=>decideClaim(x,'pay')],['deny claim',()=>decideClaim(x,'deny')],['let adjuster decide',()=>decideClaim(x)]);if(p)b.push(['open '+p.id,()=>openPolicy(p)]);b.push(['close',closePanel]);panel(x.id+' · '+x.status.toUpperCase(),x.reason+' · '+x.amount+' credits','decision '+(x.decision||'pending')+' · paid '+x.paid.toFixed(1)+(x.excluded?' · exclusion implicated':''),b)}
function openPolicy(p){let c=contract(p.contractId),ins=insurer(p.insurerId),b=[];if(p.status==='active'){b.push(['collect premium',()=>chargePremium(p)],['file software-loss claim',()=>fileClaim(p)]);for(const r of lossReasons(c).slice(0,3))b.push(['claim: '+r,()=>fileClaim(p,r)])}if(ins)b.push(['open '+ins.name,()=>openInsurer(ins)]);for(const x of [...S.riskClaims51].reverse().filter(x=>x.policyId===p.id).slice(0,3))b.push(['open '+x.id,()=>openClaim(x)]);b.push(['close',closePanel]);panel(p.id+' · '+p.status.toUpperCase(),p.vendor+' · '+p.insurer,'risk '+Math.round(p.risk*100)+'% · premium '+p.premium+' · coverage '+p.coverage+' · deductible '+p.deductible+'\nexclusions '+(p.exclusions.join('; ')||'none')+' · paid claims '+p.paidClaims.toFixed(1),b)}
function openInsurer(ins){let ps=policiesFor(ins.id),b=[];if(ins.status==='insolvent')b.push(['public reinsurance guarantee',()=>reinsure(ins)]);for(const p of ps.slice(-4))b.push(['open '+p.id,()=>openPolicy(p)]);b.push(['close',closePanel]);panel(ins.name+' · '+ins.status.toUpperCase(),ins.id+' · '+ins.type,'capital '+ins.capital.toFixed(1)+' · reserves '+ins.reserves.toFixed(1)+' · '+ps.length+' active policies · paid '+ins.claimsPaid.toFixed(1)+' · denied '+ins.claimsDenied,b)}
function openRiskMarket(id=S.active){ensureInsurers();let cs=(S.vendorContracts48||[]).filter(c=>c.reality===id&&['active','stayed'].includes(c.status)),b=[['audit software risk',()=>{auditRisk(id);renderAll();save51();openRiskMarket(id)}],['push stricter standard from risk model',()=>pushRiskStandard(id)]];for(const c of cs.slice(-5)){let p=activePolicyForContract(c.id);b.push([p?'open '+p.id:'insure '+c.id,()=>p?openPolicy(p):underwrite(c)])}for(const ins of S.insurers51.filter(i=>i.reality===id))b.push([ins.name,()=>openInsurer(ins)]);b.push(['close',closePanel]);let ins=S.insurers51.filter(i=>i.reality===id),capital=ins.reduce((n,i)=>n+i.capital,0),active=S.riskPolicies51.filter(p=>p.reality===id&&p.status==='active').length;panel('SOFTWARE RISK MARKET · Reality '+id,active+' active policies · '+capital.toFixed(1)+' insurer capital',S.policiesWritten51+' policies · '+S.claimsFiled51+' claims · '+S.claimsPaid51+' paid · '+S.claimsDenied51+' denied · '+S.insurerFailures51+' insurer failures · '+S.publicReinsurance51+' guarantees · '+S.insuranceCrises51+' crises',b)}
function insureCritical(id=S.active){let cs=(S.vendorContracts48||[]).filter(c=>c.reality===id&&['active','stayed'].includes(c.status)&&!activePolicyForContract(c.id)).sort((a,b)=>riskScore(b)-riskScore(a));if(!cs.length){$('#msg').textContent='No uninsured active contract is available.';return}underwrite(cs[0])}
function autonomous(){ensureInsurers();let now=Date.now();if(now-S.lastInsuranceTick51<1800)return;S.lastInsuranceTick51=now;for(const p of S.riskPolicies51.filter(p=>p.status==='active')){if(p.expires<=now){p.status='expired';continue}let c=contract(p.contractId);if(c&&lossReasons(c).length&&Math.random()<.0025&&!S.riskClaims51.some(x=>x.policyId===p.id&&x.status==='filed')){let x=fileClaim(p,null,false);if(x&&Math.random()<.45)decideClaim(x,null,false);break}}for(const ins of S.insurers51)systemicCheck(ins);if(Math.random()<.002){let id=pick(['A','B']),cs=(S.vendorContracts48||[]).filter(c=>c.reality===id&&c.status==='active'&&!activePolicyForContract(c.id));if(cs.length)underwrite(pick(cs),null,false,false)}}
function renderInsurance(){ensureInsurers();let layer=$('#insuranceLayer');if(!layer){layer=document.createElement('div');layer.id='insuranceLayer';document.body.appendChild(layer)}layer.innerHTML='';for(const ins of S.insurers51.slice(-12)){let e=document.createElement('i');e.className='insurerNode '+ins.status+(ins.type==='captive'?' captive':'');e.dataset.label=ins.id;e.style.left=ins.x+'%';e.style.top=ins.y+'%';e.onclick=()=>openInsurer(ins);layer.appendChild(e)}for(const p of S.riskPolicies51.filter(p=>['active','orphaned','lapsed'].includes(p.status)).slice(-14)){let e=document.createElement('i');e.className='policyNode '+p.status+(p.captive?' captive':'');e.dataset.label=p.id.replace('POL','P');e.style.left=p.x+'%';e.style.top=p.y+'%';e.onclick=()=>openPolicy(p);layer.appendChild(e)}for(const c of S.riskClaims51.filter(c=>['filed','denied','unfunded'].includes(c.status)).slice(-10)){let e=document.createElement('i');e.className='claimNode '+c.status;e.dataset.label=c.id.replace('CLM','C');e.style.left=c.x+'%';e.style.top=c.y+'%';e.onclick=()=>openClaim(c);layer.appendChild(e)}let line=$('#insuranceline');if(!line){line=document.createElement('div');line.id='insuranceline';line.className='line';($('#standardsline')||$('#oversightline')||$('#procurementline')||$('#enforcement')).after(line)}let id=S.active,ins=S.insurers51.filter(i=>i.reality===id),active=S.riskPolicies51.filter(p=>p.reality===id&&p.status==='active').length,failed=ins.filter(i=>i.status==='insolvent').length;line.textContent='software risk: '+active+' policies · '+ins.reduce((n,i)=>n+i.capital,0).toFixed(1)+' capital · '+S.claimsFiled51+' claims · '+S.claimsDenied51+' denied · '+failed+' failed insurers · '+S.insuranceCrises51+' crises';let ctr=document.querySelector('#app .controls');if(ctr&&!$('#openRiskMarketButton')){let x=document.createElement('button');x.id='openRiskMarketButton';x.textContent='open risk market';x.onclick=()=>openRiskMarket(S.active);ctr.prepend(x)}if(ctr&&!$('#insureCriticalButton')){let x=document.createElement('button');x.id='insureCriticalButton';x.textContent='insure critical contract';x.onclick=()=>insureCritical(S.active);ctr.prepend(x)}}
renderAll=function(){BR51();renderInsurance()};let f=$('#forget');if(f)f.onclick=()=>{for(let i=2;i<=51;i++)localStorage.removeItem('nothing-state-v'+i);location.reload()};
setInterval(()=>{autonomous();renderInsurance();save51()},2100);ensureInsurers();renderAll();save51();
})();
