(()=>{
const B89=save,R89=renderAll,O=JSON.parse(localStorage.getItem('nothing-state-v89')||'null')||{},RECOVER89=!Array.isArray(O.interestMaterialityEvents89),K=['interestMaterialityOffice89','interestMaterialityEvents89','interestMaterialitySerial89','interestMaterialityCaseEvents89','interestMaterialityAuthorityEvents89','interestMaterialityPenaltyTranches89','interestMaterialityCrises89','interestMaterialityKeys89','lastInterestMaterialityTick89'];
for(const k of K)S[k]=O[k]??(k==='interestMaterialityEvents89'?[]:/Serial|CaseEvents|AuthorityEvents|PenaltyTranches|Crises|Tick/.test(k)?0:/Keys/.test(k)?{}:/Office/.test(k)?null:[]);
function save89(){B89();let o={};for(const k of K)o[k]=S[k];localStorage.setItem('nothing-state-v89',JSON.stringify(o))}save=save89;
const q=s=>$(s),realm=id=>S.real[id],authority=id=>(S.monetaryAuthorities55||[]).find(x=>x.id===id);
function trust(id,status,note){S.trustAudits=S.trustAudits||[];S.trustAuditSerial=S.trustAuditSerial||0;S.trustAudits.push({id:'TA'+(++S.trustAuditSerial),reality:id,status,created:Date.now(),note,x:10+Math.random()*80,y:12+Math.random()*68})}
function incident(id,title,sev='SEV2'){S.incidents=S.incidents||[];S.incidentSerial=S.incidentSerial||0;let ex=S.incidents.find(x=>x.reality===id&&x.title===title&&x.status==='open');if(ex)return ex;let i={id:'INC'+(++S.incidentSerial),reality:id,title,severity:sev,status:'open',started:Date.now(),owner:'interest materiality aggregation office',x:10+Math.random()*80,y:12+Math.random()*68};S.incidents.push(i);return i}
function crisis(id,why,key){let n=Date.now(),k=id+'|'+key;if(S.interestMaterialityKeys89[k]&&n-S.interestMaterialityKeys89[k]<14000)return;S.interestMaterialityKeys89[k]=n;S.interestMaterialityCrises89++;remember('INTEREST MATERIALITY CRISIS: '+why+' turned individually de minimis write-offs into a reportable governance event',realm(id));if(typeof place==='function'){place('cold','a hundredth of a credit becoming material only after it happened enough times',realm(id));place('dream','rounding errors forming a constituency',realm(id))}incident(id,'interest materiality aggregation: '+why,'SEV2')}
function ensure(){if(!S.deMinimisInterestOffice88||!S.residualInterestOffice87)return null;if(!S.interestMaterialityOffice89){S.interestMaterialityOffice89={id:'IMO1',name:'Interreality Interest Materiality Aggregation Office',status:'aggregating',caseThreshold89:.05,authorityThreshold89:.10,created:Date.now(),x:50,y:78};remember('INTEREST MATERIALITY IMO1: de minimis write-offs acquired aggregate materiality tests',realm('A'));remember('INTEREST MATERIALITY IMO1: de minimis write-offs acquired aggregate materiality tests',realm('B'));trust('A','interest-materiality-office-created','IMO1');trust('B','interest-materiality-office-created','IMO1')}return S.interestMaterialityOffice89}
function writeoffs(){return(S.interestDustWriteoffs88||[]).filter(w=>w&&w.status==='written-off'&&(w.amount88||0)>0)}
function caseTotal(id){return writeoffs().filter(w=>w.crossDefaultId85===id).reduce((n,w)=>n+Math.max(0,w.amount88||0),0)}
function authorityTotal(id){return writeoffs().filter(w=>w.authorityId===id).reduce((n,w)=>n+Math.max(0,w.amount88||0),0)}
function upsert(arr,id,snap){let i=arr.findIndex(x=>x.id===id);if(i>=0)arr[i]=snap;else arr.push(snap)}
function marker(e,c,a){let snap=JSON.parse(JSON.stringify(e));if(c){c.interestMaterialityMarkers89=c.interestMaterialityMarkers89||[];upsert(c.interestMaterialityMarkers89,e.id,snap);c.interestMaterialityLatest89=e.id}if(a){a.interestMaterialityMarkers89=a.interestMaterialityMarkers89||[];upsert(a.interestMaterialityMarkers89,e.id,snap);a.interestMaterialityLatest89=e.id}}
function event(kind,data){let e={id:'IMR'+(++S.interestMaterialitySerial89),kind89:kind,status:'material',created:Date.now(),x:10+Math.random()*80,y:12+Math.random()*68,...data};S.interestMaterialityEvents89.push(e);if(kind==='case-materiality')S.interestMaterialityCaseEvents89++;else{S.interestMaterialityAuthorityEvents89++;S.interestMaterialityPenaltyTranches89++}return e}
function reviewCase(c){let total=caseTotal(c.id);c.interestDustAggregate89=total;if(total+1e-9<.05||c.interestMaterialityCase89)return null;let ids=writeoffs().filter(w=>w.crossDefaultId85===c.id).map(w=>w.id),e=event('case-materiality',{crossDefaultId85:c.id,reality:c.reality,borrower:c.borrower,authorityIds89:[...new Set(writeoffs().filter(w=>w.crossDefaultId85===c.id).map(w=>w.authorityId).filter(Boolean))],aggregate89:total,threshold89:.05,writeoffCount89:ids.length,writeoffIds88:ids});c.interestMaterialityCase89=e.id;c.interestMaterial89=true;c.interestMaterialAt89=Date.now();marker(e,c,null);remember('INTEREST MATERIALITY '+e.id+': '+c.id+' accumulated '+total.toFixed(4)+' of individually de minimis interest write-offs',realm(c.reality));trust(c.reality,'interest-writeoff-case-material',e.id+' '+total.toFixed(4));crisis(c.reality,c.id+' crossed the 0.05 case materiality threshold','case-'+c.id);return e}
function reviewAuthority(a){let total=authorityTotal(a.id),target=Math.floor((total+1e-9)/.10),done=Math.max(0,a.interestMaterialityTranches89||0);a.interestDustAggregate89=total;if(target<=done)return[];let out=[];for(let tranche=done+1;tranche<=target;tranche++){let cutoff=tranche*.10,ids=writeoffs().filter(w=>w.authorityId===a.id).map(w=>w.id),e=event('authority-materiality',{authorityId:a.id,reality:a.reality,authorityName89:a.name,tranche89:tranche,threshold89:cutoff,aggregate89:total,writeoffCount89:ids.length,writeoffIds88:ids,independenceBefore89:a.independence,credibilityBefore89:a.credibility,emergencyMandateBefore89:a.emergencyMandate||0});a.independence=Math.max(0,(a.independence||0)-.01);a.credibility=Math.max(0,(a.credibility||0)-.015);a.emergencyMandate=(a.emergencyMandate||0)+1;a.interestMaterialityTranches89=tranche;a.interestMaterialityLast89=e.id;e.independenceAfter89=a.independence;e.credibilityAfter89=a.credibility;e.emergencyMandateAfter89=a.emergencyMandate;marker(e,null,a);out.push(e);remember('AUTHORITY MATERIALITY '+e.id+': '+a.name+' crossed cumulative foregone-interest tranche '+cutoff.toFixed(2)+' after '+ids.length+' de minimis write-offs',realm(a.reality));trust(a.reality,'interest-writeoff-authority-material',e.id+' tranche '+tranche);crisis(a.reality,a.name+' accumulated '+cutoff.toFixed(2)+' of foregone interest through de minimis finality','authority-'+a.id+'-'+tranche)}return out}
function reconstruct(){if(!RECOVER89)return false;let changed=false,seen=new Map();for(const c of(S.fundingCrossDefaults85||[]))for(const m of(c.interestMaterialityMarkers89||[]))seen.set(m.id,m);for(const a of(S.monetaryAuthorities55||[]))for(const m of(a.interestMaterialityMarkers89||[]))seen.set(m.id,m);for(const m of seen.values()){if((S.interestMaterialityEvents89||[]).some(x=>x.id===m.id))continue;let e=JSON.parse(JSON.stringify(m));e.recovered=true;S.interestMaterialityEvents89.push(e);if(e.kind89==='case-materiality')S.interestMaterialityCaseEvents89++;else{S.interestMaterialityAuthorityEvents89++;S.interestMaterialityPenaltyTranches89++}let n=Number(String(e.id).replace(/\D/g,''))||0;if(n>S.interestMaterialitySerial89)S.interestMaterialitySerial89=n;changed=true}return changed}
function reconcile(){if(!ensure())return false;let changed=reconstruct();for(const c of(S.fundingCrossDefaults85||[]).filter(c=>c.status==='liquidated-deficiency'))if(reviewCase(c))changed=true;for(const a of(S.monetaryAuthorities55||[])){let xs=reviewAuthority(a);if(xs.length)changed=true}return changed}
function openEvent(e){let detail=e.kind89==='case-materiality'?(e.borrower+' · '+e.crossDefaultId85+' · aggregate '+e.aggregate89.toFixed(4)+' · threshold '+e.threshold89.toFixed(2)+' · '+e.writeoffCount89+' write-offs'):(e.authorityName89+' · tranche '+e.tranche89+' · aggregate '+e.aggregate89.toFixed(4)+' · independence '+Math.round(e.independenceBefore89*100)+'→'+Math.round(e.independenceAfter89*100)+'% · credibility '+Math.round(e.credibilityBefore89*100)+'→'+Math.round(e.credibilityAfter89*100)+'%');panel(e.id+' · INTEREST MATERIALITY',e.kind89.toUpperCase(),detail,[['close',closePanel]])}
function openOffice(){if(!ensure())return;let acts=[];for(const e of S.interestMaterialityEvents89.slice(-10))acts.push(['open '+e.id+' · '+e.kind89,()=>openEvent(e)]);acts.push(['close',closePanel]);panel(S.interestMaterialityOffice89.name,'AGGREGATING · IMO1',S.interestMaterialityCaseEvents89+' case materiality events · '+S.interestMaterialityAuthorityEvents89+' authority tranches · '+S.interestMaterialityPenaltyTranches89+' governance penalties',acts)}
function render89(){if(!ensure())return;let layer=q('#interestMaterialityLayer89');if(!layer){layer=document.createElement('div');layer.id='interestMaterialityLayer89';document.body.appendChild(layer)}layer.innerHTML='';let o=document.createElement('i');o.className='interestMaterialityOffice89';o.dataset.label='Σ';o.style.left='50%';o.style.top='78%';o.onclick=openOffice;layer.appendChild(o);for(const e of S.interestMaterialityEvents89.slice(-8)){let n=document.createElement('i');n.className='interestMateriality89 '+e.kind89;n.dataset.label=e.kind89==='case-materiality'?'Σ':'Σ!';n.style.left=e.x+'%';n.style.top=e.y+'%';n.onclick=()=>openEvent(e);layer.appendChild(n)}let line=q('#interestmaterialityline89');if(!line){line=document.createElement('div');line.id='interestmaterialityline89';line.className='line';(q('#deminimisinterestline88')||q('#residualinterestline87')||q('#monetaryline')||q('#enforcement')).after(line)}line.textContent='interest materiality: '+S.interestMaterialityCaseEvents89+' case reviews · '+S.interestMaterialityAuthorityEvents89+' authority tranches';let ctr=document.querySelector('#app .controls');if(ctr&&!q('#openInterestMateriality89')){let x=document.createElement('button');x.id='openInterestMateriality89';x.textContent='open interest materiality';x.onclick=openOffice;ctr.prepend(x)}}
renderAll=function(){R89();let changed=reconcile();render89();if(changed)save89()};let f=q('#forget');if(f)f.onclick=()=>{for(let i=2;i<=89;i++)localStorage.removeItem('nothing-state-v'+i);location.reload()};setInterval(()=>{reconcile();render89();save89()},2300);ensure();reconcile();renderAll();save89();
})();