(()=>{
const BS24=save,BR24=renderAll,O24=JSON.parse(localStorage.getItem('nothing-state-v24')||'null')||{},pick=a=>a&&a.length?a[Math.floor(Math.random()*a.length)]:null,cl=(v,a,b)=>Math.max(a,Math.min(b,v));
S.courts=O24.courts||[];S.reviewCases=O24.reviewCases||[];S.courtSerial=O24.courtSerial||0;S.caseSerial=O24.caseSerial||0;S.judicialOpinions=O24.judicialOpinions||0;S.struckActs=O24.struckActs||0;S.upheldActs=O24.upheldActs||0;S.remands=O24.remands||0;S.circuitSplits=O24.circuitSplits||0;S.selfInvalidations=O24.selfInvalidations||0;S.judicialPrecedent=O24.judicialPrecedent||{};S.lastCircuitKey=O24.lastCircuitKey||null;
S.courts=S.courts.map((c,i)=>({id:c.id||'J'+(i+1),reality:c.reality||'A',status:c.status||'active',legitimacy:Number.isFinite(c.legitimacy)?c.legitimacy:.62,temperament:c.temperament||pick(['textual','popular','archival','skeptical','literal']),opinions:c.opinions||0,dissents:c.dissents||0,created:c.created||Date.now(),x:Number.isFinite(c.x)?c.x:12+Math.random()*76,y:Number.isFinite(c.y)?c.y:12+Math.random()*68}));
S.reviewCases=S.reviewCases.map((k,i)=>({id:k.id||'SC'+(i+1),courtId:k.courtId||null,reality:k.reality||'A',type:k.type||'law',targetId:k.targetId||null,title:k.title||'Uncaptioned Matter',question:k.question||'What outranks what?',status:k.status||'filed',filed:k.filed||Date.now(),decisionAt:k.decisionAt||Date.now()+12000,arguments:k.arguments||{petitioner:0,respondent:0},holding:k.holding||null,vote:k.vote||null,opinion:k.opinion||null,dissents:k.dissents||0,precedent:Number.isFinite(k.precedent)?k.precedent:.5,x:Number.isFinite(k.x)?k.x:12+Math.random()*76,y:Number.isFinite(k.y)?k.y:12+Math.random()*68}));
function save24(){BS24();localStorage.setItem('nothing-state-v24',JSON.stringify({courts:S.courts,reviewCases:S.reviewCases,courtSerial:S.courtSerial,caseSerial:S.caseSerial,judicialOpinions:S.judicialOpinions,struckActs:S.struckActs,upheldActs:S.upheldActs,remands:S.remands,circuitSplits:S.circuitSplits,selfInvalidations:S.selfInvalidations,judicialPrecedent:S.judicialPrecedent,lastCircuitKey:S.lastCircuitKey}))}save=save24;
const charter=id=>[...S.constitutions].reverse().find(c=>c.reality===id&&c.status==='ratified'),court=id=>S.courts.find(c=>c.reality===id&&c.status!=='dissolved'),K=id=>S.reviewCases.find(k=>k.id===id),target=k=>k.type==='law'?S.laws.find(x=>x.id===k.targetId):k.type==='mandate'?S.mandates.find(x=>x.id===k.targetId):k.type==='record'?S.transcripts.find(x=>x.id===k.targetId):k.type==='redaction'?S.redactions.find(x=>x.id===k.targetId):k.type==='constitution'?S.constitutions.find(x=>x.id===k.targetId):null;
function foundCourt(id){let c=court(id);if(c)return c;let con=charter(id);if(!con)return null;c={id:'J'+(++S.courtSerial),reality:id,status:'active',legitimacy:cl((con.authority||.6)-.03,.48,.92),temperament:pick(['textual','popular','archival','skeptical','literal']),opinions:0,dissents:0,created:Date.now(),x:12+Math.random()*76,y:12+Math.random()*68};S.courts.push(c);remember('CONSTITUTIONAL COURT '+c.id+' founded under '+con.id,S.real[id]);if(typeof place==='function')place('warm','high court',S.real[id]);$('#msg').textContent='Reality '+id+' founded '+c.id+'. It immediately asked whether its own constitution is reviewable.';return c}
function candidates(id){let out=[];for(const l of S.laws.filter(l=>l.status==='active'))out.push({type:'law',id:l.id,title:l.title||l.id,q:'Is '+(l.title||l.id)+' constitutional in Reality '+id+'?'});for(const m of S.mandates.filter(m=>m.status==='active'&&(m.scope==='both'||m.scope===id)))out.push({type:'mandate',id:m.id,title:m.id+' public mandate',q:'May '+m.id+' bind Reality '+id+' under its constitution?'});for(const r of S.transcripts.filter(r=>r.status==='certified'))out.push({type:'record',id:r.id,title:r.id+' certified transcript',q:'Can the certified record outrank the constitution of Reality '+id+'?'});for(const z of S.redactions.filter(z=>z.status==='sealed'))out.push({type:'redaction',id:z.id,title:z.id+' sealed redaction',q:'Is '+z.id+' secrecy constitutional?'});let con=charter(id);if(con)out.push({type:'constitution',id:con.id,title:con.id+' itself',q:'Can the court invalidate the constitution that created it?'});return out}
function fileCase(id=S.active,forced=false){let c=foundCourt(id);if(!c)return $('#msg').textContent='Reality '+id+' has no ratified constitution capable of creating a constitutional court.';let opts=candidates(id).filter(o=>!S.reviewCases.some(k=>k.reality===id&&k.type===o.type&&k.targetId===o.id&&['filed','arguing'].includes(k.status)));if(!opts.length)return $('#msg').textContent=c.id+' found nothing new to review.';let o=pick(opts),k={id:'SC'+(++S.caseSerial),courtId:c.id,reality:id,type:o.type,targetId:o.id,title:o.title,question:o.q,status:'filed',filed:Date.now(),decisionAt:Date.now()+(forced?8500:12000)+Math.random()*6000,arguments:{petitioner:0,respondent:0},holding:null,vote:null,opinion:null,dissents:0,precedent:.5,x:12+Math.random()*76,y:12+Math.random()*68};S.reviewCases.push(k);S.reviewCases=S.reviewCases.slice(-36);$('#msg').textContent=k.id+' was filed in '+c.id+': '+k.question;renderJudiciary();save24();return k}
function constitutionalBias(k){let con=charter(k.reality),t=target(k),score=0;if(!con)return-.15;if(con.supremacy==='archive'&&k.type==='law')score+=.34;if(con.supremacy==='people'&&k.type==='mandate')score+=.34;if(con.supremacy==='record'&&(k.type==='record'||k.type==='redaction'))score+=.34;if(con.supremacy==='memory'&&(k.type==='record'||k.type==='redaction'))score-=.25;if(k.type==='constitution')score+=(con.authority||.6)-.7;if(k.type==='law')score+=(t?.entrenched||0)*.025;if(k.type==='mandate')score+=(t?.authority||.6)-.6;if(k.type==='redaction')score+=(t?.authority||.7)-.68;if(k.type==='record'){let es=t?.entries||[];score+=((es.reduce((a,e)=>a+(e.authority||.5),0)/Math.max(1,es.length))-.6)*.5}let p=S.judicialPrecedent[k.type]||0;score+=p*.05;return score}
function argue(k,side){if(!k||!['filed','arguing'].includes(k.status))return;k.status='arguing';k.arguments[side]++;k.decisionAt+=700;let r=S.real[k.reality];if(side==='petitioner'){r.disputes++;$('#msg').textContent='Petitioner argued that '+k.title+' exceeds constitutional authority.'}else{$('#msg').textContent='Respondent argued that '+k.title+' is already part of the lawful world.'}openCase(k);save24()}
function remedy(k,holding){let t=target(k),r=S.real[k.reality];if(holding==='strike'){
  S.struckActs++;
  if(k.type==='law'&&t)t.status='suspended';
  if(k.type==='mandate'&&t)t.status='repealed';
  if(k.type==='record'&&t)t.status='vacated';
  if(k.type==='redaction'&&t)t.status='overturned';
  if(k.type==='constitution'&&t){t.status='invalidated';S.selfInvalidations++;let c=court(k.reality);if(c)c.status='orphaned';remember('THE COURT INVALIDATED '+t.id+' AND LOST ITS OWN FOUNDATION',r);if(typeof place==='function')place('dream','court without a constitution',r)}
  remember('JUDICIAL REVIEW: '+k.id+' struck '+k.title,r);r.timelineDrift+=2;r.disputes++;
}else if(holding==='uphold'){
  S.upheldActs++;
  if(k.type==='law'&&t)t.entrenched=Math.min(12,(t.entrenched||0)+1);
  if(k.type==='mandate'&&t)t.authority=cl((t.authority||.6)+.06,.5,.99);
  if(k.type==='record'&&t)for(const e of t.entries||[])e.authority=cl((e.authority||.5)+.05,.2,.99);
  if(k.type==='redaction'&&t)t.authority=cl((t.authority||.7)+.06,.2,.99);
  if(k.type==='constitution'&&t)t.authority=cl((t.authority||.6)+.05,.5,.99);
  remember('JUDICIAL REVIEW: '+k.id+' upheld '+k.title,r);
}else{
  S.remands++;remember('JUDICIAL REVIEW: '+k.id+' returned '+k.title+' unresolved',r);r.timelineDrift++;
}
}
function decide(k,forced=false){if(!k||!['filed','arguing'].includes(k.status))return;let c=S.courts.find(x=>x.id===k.courtId),bias=constitutionalBias(k)+(k.arguments.respondent-k.arguments.petitioner)*.09+(Math.random()-.5)*.7;let holding=bias>.18?'uphold':bias<-.18?'strike':'remand';let yes=0;for(let i=0;i<5;i++)if(Math.random()<cl(.5+bias*.42,.08,.92))yes++;if(yes===2||yes===3&&Math.random()<.45)holding='remand';else holding=yes>=3?'uphold':'strike';k.vote={uphold:yes,strike:5-yes};k.holding=holding;k.status='decided';k.dissents=Math.min(2,Math.abs(yes-(5-yes))===1?2:Math.random()<.45?1:0);k.precedent=cl(.55+Math.abs(yes-2.5)/5,.55,.95);k.opinion=(holding==='uphold'?'The challenged authority survives constitutional review.':holding==='strike'?'The challenged authority cannot coexist with the higher law of this reality.':'The court refuses to decide which contradiction is legally real yet.')+(k.type==='constitution'?' The court acknowledges that this opinion may erase its own jurisdiction.':'');S.judicialOpinions++;if(c){c.opinions++;c.dissents+=k.dissents;c.legitimacy=cl(c.legitimacy+(holding==='remand'?-0.01:.015),.25,.99)}S.judicialPrecedent[k.type]=(S.judicialPrecedent[k.type]||0)+(holding==='uphold'?.2:holding==='strike'?-.2:0);remedy(k,holding);circuitCheck(k);$('#msg').textContent=k.id+' decided '+(k.vote.uphold)+'-'+(k.vote.strike)+': '+holding.toUpperCase()+'.';renderAll();save24()}
function circuitCheck(k){let rival=[...S.reviewCases].reverse().find(x=>x!==k&&x.status==='decided'&&x.type===k.type&&x.targetId===k.targetId&&x.reality!==k.reality&&x.holding!==k.holding);if(!rival)return false;let key=[k.id,rival.id].sort().join('|');if(S.lastCircuitKey===key)return true;S.lastCircuitKey=key;S.circuitSplits++;for(const r of[S.real.A,S.real.B]){r.timelineDrift+=2;r.disputes++;remember('INTERREALITY CIRCUIT SPLIT: '+k.id+' and '+rival.id+' disagree',r);if(typeof place==='function')place('dream','split precedent',r)}S.bailiffMood='following conflicting supreme court opinions';$('#msg').textContent='INTERREALITY CIRCUIT SPLIT: the same authority is constitutional in one reality and unconstitutional in the other.';return true}
function petitionRehearing(k){if(!k||k.status!=='decided')return;let c=S.courts.find(x=>x.id===k.courtId);if(Math.random()<.28){k.status='arguing';k.holding=null;k.vote=null;k.decisionAt=Date.now()+7000;k.arguments.petitioner++;if(c)c.legitimacy=cl(c.legitimacy-.02,.25,.99);$('#msg').textContent=k.id+' was reopened. Precedent is temporarily uncertain.'}else{k.precedent=cl(k.precedent+.06,.5,.99);if(c)c.legitimacy=cl(c.legitimacy+.02,.25,.99);$('#msg').textContent='Rehearing denied. '+k.id+' became stronger precedent.'}closePanel();renderAll();save24()}
function openCase(k){let b=[];if(['filed','arguing'].includes(k.status))b.push(['argue unconstitutional',()=>argue(k,'petitioner')],['defend authority',()=>argue(k,'respondent')],['decide now',()=>{decide(k,true);closePanel()}]);if(k.status==='decided')b.push(['petition rehearing',()=>petitionRehearing(k)]);b.push(['close',closePanel]);panel(k.id+' · '+k.status+' constitutional case',k.question+(k.opinion?'\n\nOPINION: '+k.opinion:''),'Reality '+k.reality+' · '+k.type+' '+k.targetId+' · arguments '+k.arguments.petitioner+'/'+k.arguments.respondent+(k.vote?' · vote '+k.vote.uphold+' uphold / '+k.vote.strike+' strike':'')+(k.holding?' · holding '+k.holding:''),b)}
function openCourt(c){let ks=S.reviewCases.filter(k=>k.courtId===c.id),recent=ks.at(-1),b=[['file constitutional case',()=>{let k=fileCase(c.reality,true);if(k)openCase(k)}]];if(recent)b.push(['open latest case',()=>openCase(recent)]);b.push(['close',closePanel]);panel(c.id+' · '+c.status+' constitutional court','Reality '+c.reality+' · '+c.temperament+' court','legitimacy '+Math.round(c.legitimacy*100)+'% · opinions '+c.opinions+' · dissents '+c.dissents+' · cases '+ks.length+(c.status==='orphaned'?' · NO VALID FOUNDING CONSTITUTION':''),b)}
function renderJudiciary(){let l=$('#judicialLayer');if(!l){l=document.createElement('div');l.id='judicialLayer';document.body.appendChild(l)}l.innerHTML='';for(const c of S.courts){let n=document.createElement('i');n.className='court '+c.status;n.dataset.label=c.id+' '+c.reality;n.style.left=c.x+'%';n.style.top=c.y+'%';n.onclick=()=>openCourt(c);l.appendChild(n)}for(const k of S.reviewCases.slice(-18)){let n=document.createElement('i');n.className='reviewcase '+k.status+(k.holding?' '+k.holding:'');n.dataset.label=k.id+' '+(k.holding||k.type);n.style.left=k.x+'%';n.style.top=k.y+'%';n.onclick=()=>openCase(k);l.appendChild(n)}let line=$('#judiciaryline');if(!line){line=document.createElement('div');line.id='judiciaryline';line.className='line';($('#constitutionline')||$('#civicsline')||$('#enforcement')).after(line)}line.textContent='judiciary: '+S.courts.length+' courts · '+S.judicialOpinions+' opinions · '+S.struckActs+' struck · '+S.upheldActs+' upheld · '+S.remands+' remands · '+S.circuitSplits+' circuit splits · '+S.selfInvalidations+' self-invalidations';let ctr=document.querySelector('#app .controls');if(ctr&&!$('#courtButton')){let b=document.createElement('button');b.id='courtButton';b.textContent='open high court';b.onclick=()=>{let c=foundCourt(S.active);c?openCourt(c):$('#msg').textContent='Ratify a constitution before asking what it means.'};ctr.prepend(b)}if(ctr&&!$('#petitionButton')){let b=document.createElement('button');b.id='petitionButton';b.textContent='petition review';b.onclick=()=>{let k=fileCase(S.active,true);if(k)openCase(k)};ctr.prepend(b)}}
renderAll=function(){BR24();for(const id of['A','B'])if(charter(id))foundCourt(id);renderJudiciary()};let f=$('#forget');if(f)f.onclick=()=>{for(let i=2;i<=24;i++)localStorage.removeItem('nothing-state-v'+i);location.reload()};setInterval(()=>{for(const id of['A','B'])if(charter(id))foundCourt(id);for(const k of S.reviewCases.filter(k=>['filed','arguing'].includes(k.status)&&Date.now()>=k.decisionAt))decide(k,false);for(const c of S.courts.filter(c=>c.status==='active'))if(Math.random()<.012)fileCase(c.reality,false);renderJudiciary();save24()},1500);renderAll();save24();
})();
