(()=>{
const BS20=save,BR20=renderAll,O20=JSON.parse(localStorage.getItem('nothing-state-v20')||'null')||{},pick=a=>a&&a.length?a[Math.floor(Math.random()*a.length)]:null,cl=(v,a,b)=>Math.max(a,Math.min(b,v));
S.leaks=O20.leaks||[];S.leakSerial=O20.leakSerial||0;S.publications=O20.publications||0;S.suppressions=O20.suppressions||0;S.verifiedLeaks=O20.verifiedLeaks||0;S.falseLeaks=O20.falseLeaks||0;S.leakRestorations=O20.leakRestorations||0;S.leakHeat=O20.leakHeat||0;S.documentDumps=O20.documentDumps||0;
S.leaks=S.leaks.map((l,i)=>({id:l.id||'K'+(i+1),redactionId:l.redactionId||null,term:l.term||'unknown',claim:l.claim||'A missing fact is circulating.',source:l.source||'anonymous clerk',status:l.status||'whisper',credibility:Number.isFinite(l.credibility)?l.credibility:.5,counterfeit:!!l.counterfeit,created:l.created||Date.now(),checks:l.checks||0,shares:l.shares||0,x:Number.isFinite(l.x)?l.x:10+Math.random()*80,y:Number.isFinite(l.y)?l.y:12+Math.random()*70}));
function save20(){BS20();localStorage.setItem('nothing-state-v20',JSON.stringify({leaks:S.leaks,leakSerial:S.leakSerial,publications:S.publications,suppressions:S.suppressions,verifiedLeaks:S.verifiedLeaks,falseLeaks:S.falseLeaks,leakRestorations:S.leakRestorations,leakHeat:S.leakHeat,documentDumps:S.documentDumps}))}save=save20;
const Z=id=>S.redactions.find(z=>z.id===id),REC=z=>{let r=S.transcripts.find(r=>r.id===z.transcriptId);return r&&r.entries.find(e=>e.id===z.entryId)},activeLeaks=()=>S.leaks.filter(l=>!['suppressed','discredited'].includes(l.status));
function fakeTerm(real){let a=['archive','witness','original','verdict','memory','future','echo','door','jury','nobody'].filter(x=>x.toLowerCase()!==(real||'').toLowerCase());return pick(a)||'unknown'}
function spawn(z,forced=false){if(!z||z.status==='overturned')return null;if(!forced&&S.leaks.some(l=>l.redactionId===z.id&&['whisper','published','verified'].includes(l.status)&&Date.now()-l.created<16000))return null;let counterfeit=Math.random()<.22,term=counterfeit?fakeTerm(z.term):z.term,sources=['other reality','dead letter','protected witness','anonymous clerk','nobody'],source=pick(sources),credibility=cl((source==='other reality'?.69:source==='protected witness'?.66:source==='dead letter'?.55:source==='nobody'?.34:.58)+(Math.random()-.5)*.18,.12,.91),l={id:'K'+(++S.leakSerial),redactionId:z.id,term,claim:'The redacted word was “'+term+'”.',source,status:'whisper',credibility,counterfeit,created:Date.now(),checks:0,shares:0,x:10+Math.random()*80,y:12+Math.random()*70};S.leaks.push(l);S.leaks=S.leaks.slice(-44);S.leakHeat+=source==='nobody'?2:1;$('#msg').textContent=l.id+' appeared from '+source+'. Nobody filed it.';renderLeaks();save20();return l}
function restore(l){let z=Z(l.redactionId);if(!z)return 0;let e=REC(z),hits=0;if(e&&e.preRedactionText){e.text=e.preRedactionText;e.applied=false;hits++}for(const r of[S.real.A,S.real.B]){for(const p of r.places){if(p.redacted&&p.originalRedactedName&&(p.originalRedactedName||'').toLowerCase().includes(z.term.toLowerCase())){p.name=p.originalRedactedName;p.redacted=false;hits++}}for(const f of r.futures){if((f.text||'').includes('█')&&Math.random()<.28){f.text='leaked reconstruction: '+l.claim;f.prob=cl(f.prob+.07,.1,.97);hits++}}remember('LEAKED FACT: '+l.claim,r)}for(const w of S.witnesses){if((w.statement||'').includes('█')&&w.originalStatement&&(w.originalStatement||'').toLowerCase().includes(z.term.toLowerCase())){w.statement=w.originalStatement;w.credibility=cl((w.credibility||.5)+.08,.05,.99);hits++}}z.authority=Math.max(.25,(z.authority||.7)-.08);S.leakRestorations+=hits;return hits}
function contaminateTrial(l){let t=[...S.trials].reverse().find(t=>['hearing','deliberating'].includes(t.status));if(!t)return;t.evidence.push({id:'eLeak'+Date.now()+Math.random(),type:'unauthorized leak',text:l.claim+' — '+l.source,side:l.counterfeit?'prosecution':Math.random()<.5?'defense':'prosecution',weight:.7+l.credibility*1.1});t.evidence=t.evidence.slice(-14);t.notes.push(l.id+' entered the case without being admitted');}
function publish(l,auto=false){if(!l||['published','verified'].includes(l.status))return;l.status='published';l.shares++;S.publications++;S.leakHeat+=2;let hits=0;if(l.counterfeit){S.falseLeaks++;S.redactionDrift+=2;for(const r of[S.real.A,S.real.B]){remember('UNVERIFIED LEAK: '+l.claim,r);r.timelineDrift+=2;r.disputes++}if(typeof place==='function')place('dream','counterfeit disclosure',R())}else hits=restore(l);contaminateTrial(l);$('#msg').textContent=l.counterfeit?'A counterfeit leak is becoming part of the story.':l.id+' restored '+hits+' fragments the record had erased.';if(!auto)openLeak(l);renderAll();save20()}
function verify(l){if(!l||['verified','discredited','suppressed'].includes(l.status))return;l.checks++;let correct=l.counterfeit?Math.random()<.78:Math.random()<.74;if(l.source==='other reality'&&!l.counterfeit)correct=Math.random()<.86;if(l.source==='nobody'&&!l.counterfeit)correct=Math.random()<.62;if(correct){if(l.counterfeit){l.status='discredited';l.credibility=.08;S.falseLeaks++;$('#msg').textContent='Reality '+other()+' could not corroborate '+l.id+'.'}else{l.status='verified';l.credibility=cl(l.credibility+.22,.1,.99);S.verifiedLeaks++;if(!l.shares){l.shares=1;S.publications++;S.leakHeat+=2;contaminateTrial(l)}restore(l);$('#msg').textContent='Reality '+other()+' corroborated '+l.id+'.'}}else{if(l.counterfeit){l.status='verified';l.credibility=cl(l.credibility+.18,.1,.96);S.verifiedLeaks++;S.falseLeaks++;if(!l.shares){l.shares=1;S.publications++;S.leakHeat+=2;contaminateTrial(l)}for(const r of[S.real.A,S.real.B]){remember('FALSELY VERIFIED LEAK: '+l.claim,r);r.timelineDrift+=2;r.disputes++}$('#msg').textContent='The counterfeit was corroborated anyway.'}else{l.credibility=cl(l.credibility+(Math.random()<.5?-.12:.08),.08,.96);S.recordDivergence++;$('#msg').textContent='Verification produced another contradiction.'}}renderAll();save20()}
function suppress(l){if(!l||l.status==='suppressed')return;l.status='suppressed';S.suppressions++;S.leakHeat=Math.max(0,S.leakHeat-1);let z=Z(l.redactionId);if(z){z.authority=cl((z.authority||.7)+.07,.1,.99);z.status='sealed'}$('#msg').textContent=l.id+' was suppressed.';if(Math.random()<.3&&z){S.leakHeat+=3;spawn(z,true);spawn(z,true);$('#msg').textContent+=' The suppression produced more copies.'}closePanel();renderAll();save20()}
function dump(){let pool=S.leaks.filter(l=>l.status==='whisper');if(!pool.length)return;S.documentDumps++;S.leakHeat+=3;for(const l of pool.slice(-Math.min(4,pool.length)))publish(l,true);for(const r of[S.real.A,S.real.B])remember('DOCUMENT DUMP '+S.documentDumps+' crossed the rift',r);$('#msg').textContent='A document dump crossed both realities before anyone could redact it.';renderAll();save20()}
function openLeak(l){let z=Z(l.redactionId),buttons=[];if(l.status==='whisper')buttons.push(['publish leak',()=>publish(l)],['verify in other reality',()=>verify(l)]);else if(l.status==='published')buttons.push(['verify in other reality',()=>verify(l)]);if(!['suppressed','discredited'].includes(l.status))buttons.push(['suppress',()=>suppress(l)]);buttons.push(['close',closePanel]);panel(l.id+' · '+l.status+' leak',l.claim,'source '+l.source+' · credibility '+Math.round(l.credibility*100)+'% · checks '+l.checks+' · shares '+l.shares+' · linked redaction '+(z?z.id:'missing'),buttons)}
function renderLeaks(){let layer=$('#leakLayer');if(!layer){layer=document.createElement('div');layer.id='leakLayer';document.body.appendChild(layer)}layer.innerHTML='';for(const l of S.leaks.slice(-22)){let n=document.createElement('i');n.className='leak '+l.status+(l.counterfeit?' counterfeit':'');n.dataset.label=l.id+' '+l.source;n.style.left=l.x+'%';n.style.top=l.y+'%';n.onclick=()=>openLeak(l);layer.appendChild(n)}let line=$('#leakline');if(!line){line=document.createElement('div');line.id='leakline';line.className='line';($('#redactionline')||$('#recordline')||$('#testimonyline')||$('#courtline')||$('#enforcement')).after(line)}line.textContent='leaks: '+activeLeaks().length+' circulating · '+S.publications+' published · '+S.verifiedLeaks+' verified · '+S.falseLeaks+' false · '+S.leakRestorations+' restored fragments · heat '+S.leakHeat;let c=document.querySelector('#app .controls');if(c&&!$('#leakButton')){let b=document.createElement('button');b.id='leakButton';b.textContent='open leak';b.onclick=()=>{let l=[...S.leaks].reverse().find(l=>!['suppressed','discredited'].includes(l.status));if(!l){let z=pick(S.redactions.filter(z=>z.status!=='overturned'));l=z?spawn(z,true):null}l?openLeak(l):$('#msg').textContent='Nothing is leaking yet.'};c.prepend(b)}}
renderAll=function(){BR20();renderLeaks()};let f=$('#forget');if(f)f.onclick=()=>{for(let i=2;i<=20;i++)localStorage.removeItem('nothing-state-v'+i);location.reload()};
setInterval(()=>{let z=pick(S.redactions.filter(z=>z.status==='sealed'||z.status==='active'));if(z&&Math.random()<.025)spawn(z,false);if(S.leakHeat>8&&Math.random()<.035)dump();for(const l of S.leaks.filter(l=>l.status==='whisper'&&Math.random()<.018))publish(l,true);renderLeaks();save20()},1500);renderAll();save20();
})();