(()=>{
const B75=save,R75=renderAll,O=JSON.parse(localStorage.getItem('nothing-state-v75')||'null')||{},K=['lossQuotaOffice75','lossQuotaCredits75','lossQuotaShifts75','lossQuotaSerial75','lossQuotaShiftSerial75','lossQuotaBooked75','lossQuotaAmount75','lossQuotaMajorities75','lossQuotaCrises75','lossQuotaKeys75','lastLossQuotaTick75'];
for(const k of K)S[k]=O[k]??(/Serial|Booked|Amount|Majorities|Crises|Tick/.test(k)?0:/Keys/.test(k)?{}:/Office/.test(k)?null:[]);
function save75(){B75();let o={};for(const k of K)o[k]=S[k];localStorage.setItem('nothing-state-v75',JSON.stringify(o))}save=save75;
const q=s=>$(s),realm=id=>S.real[id],fund58=()=>S.stabilizationFunds58?.[0],board59=()=>S.fundBoards59?.[0],quota=id=>(S.stabilizationQuotas58||[]).find(x=>x.reality===id),director=id=>(S.fundDirectors59||[]).find(x=>x.reality===id),cur=id=>(S.fxCurrencies56||[]).find(x=>x.reality===id),acct=id=>(S.tradeAccounts57||[]).find(x=>x.reality===id);
function trust(id,status,note){S.trustAudits=S.trustAudits||[];S.trustAuditSerial=S.trustAuditSerial||0;S.trustAudits.push({id:'TA'+(++S.trustAuditSerial),reality:id,status,created:Date.now(),note,x:10+Math.random()*80,y:12+Math.random()*68})}
function incident(id,title,sev='SEV1'){S.incidents=S.incidents||[];S.incidentSerial=S.incidentSerial||0;let ex=S.incidents.find(x=>x.reality===id&&x.title===title&&x.status==='open');if(ex)return ex;let i={id:'INC'+(++S.incidentSerial),reality:id,title,severity:sev,status:'open',started:Date.now(),owner:'loss quota register',x:10+Math.random()*80,y:12+Math.random()*68};S.incidents.push(i);return i}
function crisis(id,why,sev='SEV1'){let n=Date.now(),k=id+'|'+why;if(S.lossQuotaKeys75[k]&&n-S.lossQuotaKeys75[k]<14000)return;S.lossQuotaKeys75[k]=n;S.lossQuotaCrises75++;remember('LOSS QUOTA CRISIS: '+why+' converted absorbed stabilization losses into governance rights',realm(id));if(typeof place==='function'){place('cold','reserve loss turning into a board seat fraction',realm(id));place('dream','the bailout bought votes only after the money was already gone',realm(id))}incident(id,'loss quota crisis: '+why,sev)}
function ensure(){if(!S.multilateralRecapOffice74||!fund58()||!board59())return null;if(!S.lossQuotaOffice75){S.lossQuotaOffice75={id:'LQR1',name:'Interreality Loss Quota Register',status:'booking',created:Date.now(),x:50,y:99.99};remember('LOSS QUOTA REGISTER LQR1: stabilization reserve losses became involuntary paid-in governance capital',realm('A'));remember('LOSS QUOTA REGISTER LQR1: stabilization reserve losses became involuntary paid-in governance capital',realm('B'));trust('A','loss-quota-register-created','LQR1');trust('B','loss-quota-register-created','LQR1')}return S.lossQuotaOffice75}
function exposure(id){return(S.stabilizationPrograms58||[]).filter(p=>p.reality===id).reduce((n,p)=>n+(p.disbursed||0),0)}
function score(id){let z=quota(id),c=cur(id),a=acct(id),contrib=(z?.contributedRA||0)+(z?.contributedRB||0),exports=Math.max(0,a?.exports||0),borrow=exposure(id),rdr=z?.rdr||0;return Math.max(2,(z?.quota||10)+contrib*.35+(c?.foreignReserves||0)*.16+exports*.025-rdr*.08-borrow*.18)}
function refreshVotes(){let a=score('A'),b=score('B'),total=a+b||1,out={A:100*a/total,B:100*b/total};for(const id of ['A','B']){let z=quota(id),d=director(id);if(z)z.votes=out[id];if(d)d.votes=out[id]}return out}
function creditForTransfer(id){return(S.lossQuotaCredits75||[]).find(x=>x.transferId74===id)||null}
function book(t,manual=false){if(!t||(t.amount||0)<=.001||!['A','B'].includes(t.burdenReality)||!['A','B'].includes(t.reality))return null;let existing=creditForTransfer(t.id);if(existing)return existing;if(t.lossQuotaCredit75){let amt=Math.max(0,t.lossQuotaBooked75||t.amount||0),recovered={id:t.lossQuotaCredit75,transferId74:t.id,recapId74:t.recapId74,receivershipId73:t.receivershipId73,targetReality:t.reality,burdenReality:t.burdenReality,amount:amt,status:'recovered-from-transfer-marker',created:t.lossQuotaBookedAt75||t.created||Date.now(),x:t.x||10+Math.random()*80,y:t.y||12+Math.random()*68};S.lossQuotaCredits75.push(recovered);S.lossQuotaBooked75++;S.lossQuotaAmount75+=amt;let n=Number(String(t.lossQuotaCredit75).replace(/\D/g,''))||0;if(n>S.lossQuotaSerial75)S.lossQuotaSerial75=n;return recovered}
let z=quota(t.burdenReality);if(!z)return null;let beforeVotes=refreshVotes(),beforeQuota=z.quota||10,amt=Math.max(0,t.amount||0);z.quota=beforeQuota+amt;let afterVotes=refreshVotes(),c={id:'LQC'+(++S.lossQuotaSerial75),transferId74:t.id,recapId74:t.recapId74,receivershipId73:t.receivershipId73,targetReality:t.reality,burdenReality:t.burdenReality,amount:amt,quotaBefore:beforeQuota,quotaAfter:z.quota,votesBefore:beforeVotes[t.burdenReality],votesAfter:afterVotes[t.burdenReality],targetVotesAfter:afterVotes[t.reality],poolRef:t.currency,status:'booked',created:Date.now(),x:10+Math.random()*80,y:12+Math.random()*68};S.lossQuotaCredits75.push(c);S.lossQuotaBooked75++;S.lossQuotaAmount75+=amt;t.lossQuotaCredit75=c.id;t.lossQuotaBooked75=amt;t.lossQuotaBookedAt75=c.created;
let sh={id:'LQS'+(++S.lossQuotaShiftSerial75),creditId75:c.id,transferId74:t.id,burdenReality:t.burdenReality,targetReality:t.reality,before:beforeVotes,after:afterVotes,created:Date.now(),x:10+Math.random()*80,y:12+Math.random()*68};S.lossQuotaShifts75.push(sh);
remember('LOSS QUOTA '+c.id+': Reality '+t.burdenReality+' converted '+amt.toFixed(2)+' of absorbed '+t.currency+' reserve loss into quota '+beforeQuota.toFixed(2)+'→'+z.quota.toFixed(2),realm(t.burdenReality));trust(t.burdenReality,'stabilization-loss-converted-to-quota',c.id+' '+amt.toFixed(2)+' '+t.currency);
if(beforeVotes[t.burdenReality]<60&&afterVotes[t.burdenReality]>=60){S.lossQuotaMajorities75++;c.createdMajority75=true;remember('LOSS-BORN MAJORITY '+c.id+': Reality '+t.burdenReality+' crossed 60% of stabilization-board voting power after absorbing recapitalization losses',realm(t.burdenReality));if(typeof place==='function'){place('cold','creditor majority assembled from bailout losses instead of new cash',realm(t.burdenReality));place('dream','one member able to approve the next bailout because it paid for the last one',realm(t.burdenReality))}crisis(t.burdenReality,'absorbed bailout losses created unilateral stabilization-board control','SEV1')}
if(manual){renderAll();save75();openCredit(c)}return c}
function reconcile(){if(!ensure())return false;let changed=false;for(const t of(S.multilateralRecapTransfers74||[])){let before=S.lossQuotaCredits75.length,had=!!creditForTransfer(t.id);book(t,false);if(!had&&S.lossQuotaCredits75.length>before)changed=true}return changed}
function openCredit(c){let t=(S.multilateralRecapTransfers74||[]).find(x=>x.id===c.transferId74),acts=[['close',closePanel]];panel(c.id+' · LOSS QUOTA CREDIT',c.status.toUpperCase(),'Reality '+c.burdenReality+' absorbed '+c.amount.toFixed(2)+' '+(t?.currency||c.poolRef||'reserve')+' for Reality '+c.targetReality+' · quota '+(c.quotaBefore??0).toFixed(2)+' → '+(c.quotaAfter??0).toFixed(2)+' · votes '+(c.votesBefore??0).toFixed(1)+'% → '+(c.votesAfter??0).toFixed(1)+'%'+(c.createdMajority75?' · CREATED 60% MAJORITY':''),acts)}
function openShift(s){panel(s.id+' · VOTE SHIFT','LOSS-QUOTA REPRICING','Reality '+s.burdenReality+' '+s.before[s.burdenReality].toFixed(1)+'% → '+s.after[s.burdenReality].toFixed(1)+'% · Reality '+s.targetReality+' '+s.before[s.targetReality].toFixed(1)+'% → '+s.after[s.targetReality].toFixed(1)+'%',[['close',closePanel]])}
function openOffice(){if(!ensure())return;let v=refreshVotes(),acts=[];for(const t of(S.multilateralRecapTransfers74||[]).filter(t=>!creditForTransfer(t.id)).slice(-6))acts.push(['book '+t.id+' · '+t.amount.toFixed(2),()=>book(t,true)]);for(const c of S.lossQuotaCredits75.slice(-8))acts.push(['open '+c.id+' · R'+c.burdenReality+' +'+c.amount.toFixed(2),()=>openCredit(c)]);for(const s of S.lossQuotaShifts75.slice(-5))acts.push(['open '+s.id+' · vote shift',()=>openShift(s)]);acts.push(['close',closePanel]);panel(S.lossQuotaOffice75.name,'BOOKING · LQR1',S.lossQuotaBooked75+' loss credits · '+S.lossQuotaAmount75.toFixed(2)+' quota created from losses · A '+v.A.toFixed(1)+'% / B '+v.B.toFixed(1)+'% · '+S.lossQuotaMajorities75+' loss-born majorities',acts)}
function render75(){if(!ensure())return;let layer=q('#lossQuotaLayer75');if(!layer){layer=document.createElement('div');layer.id='lossQuotaLayer75';document.body.appendChild(layer)}layer.innerHTML='';let o=document.createElement('i');o.className='lossQuotaOffice75';o.dataset.label='LQ';o.style.left='50%';o.style.top='99.99%';o.onclick=openOffice;layer.appendChild(o);for(const c of S.lossQuotaCredits75.slice(-8)){let e=document.createElement('i');e.className='lossQuotaCredit75'+(c.createdMajority75?' majority':'');e.dataset.label='Q+';e.style.left=c.x+'%';e.style.top=c.y+'%';e.onclick=()=>openCredit(c);layer.appendChild(e)}for(const s of S.lossQuotaShifts75.slice(-6)){let e=document.createElement('i');e.className='lossQuotaShift75';e.dataset.label='V';e.style.left=s.x+'%';e.style.top=s.y+'%';e.onclick=()=>openShift(s);layer.appendChild(e)}let v=refreshVotes(),line=q('#lossquotaline75');if(!line){line=document.createElement('div');line.id='lossquotaline75';line.className='line';(q('#multilateralrecapline74')||q('#fundgovernanceline')||q('#stabilizationline')||q('#enforcement')).after(line)}line.textContent='loss quota: '+S.lossQuotaAmount75.toFixed(1)+' absorbed reserve loss → quota · A '+v.A.toFixed(1)+'% / B '+v.B.toFixed(1)+'% · '+S.lossQuotaMajorities75+' loss-born majorities';let ctr=document.querySelector('#app .controls');if(ctr&&!q('#openLossQuota75')){let x=document.createElement('button');x.id='openLossQuota75';x.textContent='open loss quota register';x.onclick=openOffice;ctr.prepend(x)}}
renderAll=function(){R75();let changed=reconcile();render75();if(changed)save75()};let f=q('#forget');if(f)f.onclick=()=>{for(let i=2;i<=75;i++)localStorage.removeItem('nothing-state-v'+i);location.reload()};setInterval(()=>{reconcile();render75();save75()},2300);ensure();reconcile();renderAll();save75();
})();