(()=>{
const B81=save,R81=renderAll,O=JSON.parse(localStorage.getItem('nothing-state-v81')||'null')||{},RECOVER81=!Array.isArray(O.marginSetoffs81),K=['marginSetoffOffice81','marginSetoffs81','marginSetoffSerial81','marginSetoffsExecuted81','marginSetoffAmount81','marginSetoffPrincipalRetired81','marginSetoffInterestPaid81','marginSetoffCallsCured81','marginSetoffCallsReopened81','marginSetoffMarginDepleted81','marginSetoffCrises81','marginSetoffKeys81','lastMarginSetoffTick81'];
for(const k of K)S[k]=O[k]??(/Serial|Executed|Amount|Retired|Paid|Cured|Reopened|Depleted|Crises|Tick/.test(k)?0:/Keys/.test(k)?{}:/Office/.test(k)?null:[]);
function save81(){B81();let o={};for(const k of K)o[k]=S[k];localStorage.setItem('nothing-state-v81',JSON.stringify(o))}save=save81;
const q=s=>$(s),realm=id=>S.real[id],position=id=>(S.sterilizationCarryPositions79||[]).find(x=>x.id===id),facility=id=>(S.liquidityFacilities55||[]).find(x=>x.id===id),authority=id=>(S.monetaryAuthorities55||[]).find(x=>x.id===id),cl=(v,a,b)=>Math.max(a,Math.min(b,v));
function trust(id,status,note){S.trustAudits=S.trustAudits||[];S.trustAuditSerial=S.trustAuditSerial||0;S.trustAudits.push({id:'TA'+(++S.trustAuditSerial),reality:id,status,created:Date.now(),note,x:10+Math.random()*80,y:12+Math.random()*68})}
function incident(id,title,sev='SEV1'){S.incidents=S.incidents||[];S.incidentSerial=S.incidentSerial||0;let ex=S.incidents.find(x=>x.reality===id&&x.title===title&&x.status==='open');if(ex)return ex;let i={id:'INC'+(++S.incidentSerial),reality:id,title,severity:sev,status:'open',started:Date.now(),owner:'segregated margin setoff office',x:10+Math.random()*80,y:12+Math.random()*68};S.incidents.push(i);return i}
function crisis(id,why,sev='SEV1'){let n=Date.now(),k=id+'|'+why;if(S.marginSetoffKeys81[k]&&n-S.marginSetoffKeys81[k]<14000)return;S.marginSetoffKeys81[k]=n;S.marginSetoffCrises81++;remember('MARGIN SETOFF CRISIS: '+why+' let public credit consume the margin protecting its own funded FX carry',realm(id));if(typeof place==='function'){place('cold','central bank seizing segregated carry margin to repay the loan that funded the carry',realm(id));place('dream','risk buffer extinguishing public money and immediately needing to be rebuilt',realm(id))}incident(id,'segregated carry margin setoff crisis: '+why,sev)}
function ensure(){if(!S.macroprudentialOffice80)return null;if(!S.marginSetoffOffice81){S.marginSetoffOffice81={id:'SMO1',name:'Interreality Segregated Margin Setoff Office',status:'offsetting',created:Date.now(),x:50,y:94};remember('MARGIN SETOFF SMO1: segregated carry margin acquired a public setoff right',realm('A'));remember('MARGIN SETOFF SMO1: segregated carry margin acquired a public setoff right',realm('B'));trust('A','segregated-margin-setoff-created','SMO1');trust('B','segregated-margin-setoff-created','SMO1')}return S.marginSetoffOffice81}
function posted(p){return Math.max(0,p?.macroMarginPosted80||0)}
function linkedCall(f){if(!f)return null;let calls=S.monetaryCollateralCalls55||[],id=f.macroMarginCBMC80;if(id){let c=calls.find(x=>x.id===id&&['open','failed'].includes(x.status));if(c)return c}return calls.find(x=>x.facilityId===f.id&&x.macroprudential80&&['open','failed'].includes(x.status))||null}
function eligible(p){let f=facility(p?.facilityId55);if(!p||!f||f.status!=='active'||posted(p)<=.01)return false;let near=(f.matures||0)-Date.now()<=15000,stressed=['rollover-risk','open-permanent-money'].includes(p.status);return stressed||near||!!linkedCall(f)}
function markerRecord(r,p,f){p.marginSetoffMarkers81=p.marginSetoffMarkers81||[];p.marginSetoffMarkers81.push(JSON.parse(JSON.stringify(r)));p.marginSetoffLatest81=r.id;f.marginSetoffMarkers81=f.marginSetoffMarkers81||[];f.marginSetoffMarkers81.push(JSON.parse(JSON.stringify(r)));f.macroMarginPosted80=posted(p)}
function reconstruct(){if(!RECOVER81)return false;let changed=false,seen=new Set();for(const f of(S.liquidityFacilities55||[])){for(const m of(f.marginSetoffMarkers81||[])){if(seen.has(m.id)||(S.marginSetoffs81||[]).some(x=>x.id===m.id))continue;seen.add(m.id);let r=JSON.parse(JSON.stringify(m));r.recovered=true;S.marginSetoffs81.push(r);S.marginSetoffsExecuted81++;S.marginSetoffAmount81+=r.amount||0;S.marginSetoffPrincipalRetired81+=r.principalPaid||0;S.marginSetoffInterestPaid81+=r.interestPaid||0;if(r.callCured81)S.marginSetoffCallsCured81++;if(r.callReopened81)S.marginSetoffCallsReopened81++;if(r.marginDepleted81)S.marginSetoffMarginDepleted81++;let n=Number(String(r.id).replace(/\D/g,''))||0;if(n>S.marginSetoffSerial81)S.marginSetoffSerial81=n;changed=true}}return changed}
function applyCallSetoff(c,amount,r){if(!c||amount<=.001)return 0;let already=Math.max(0,c.setoffPaid81||0),prior=Math.max(0,c.paid||0),orig=c.originalAmount81??c.amount??0;if(c.originalAmount81==null)c.originalAmount81=orig;let remaining=Math.max(0,orig-prior-already),x=Math.min(amount,remaining);if(x<=.001)return 0;c.setoffPaid81=already+x;let newRemaining=Math.max(0,orig-prior-c.setoffPaid81);c.amount=newRemaining;c.paid=0;c.setoffLast81=Date.now();if(newRemaining<=.01){c.amount=0;if(c.status!=='met'){c.status='met';c.met=Date.now();c.metBySetoff81=true;S.monetaryCollateralCallsMet55=(S.monetaryCollateralCallsMet55||0)+1;r.callCured81=true;S.marginSetoffCallsCured81++}}else{if(c.status==='failed'){r.callReopened81=true;S.marginSetoffCallsReopened81++}c.status='open';c.reopenedBySetoff81=true}return x}
function setoff(p,manual=true){ensure();if(!eligible(p)){if(manual&&q('#msg'))q('#msg').textContent='No stressed posted carry margin is currently eligible for setoff.';return null}let f=facility(p.facilityId55),a=authority(f.authorityId);if(!a)return null;let acct=(S.reserveAccounts55||[]).find(x=>x.borrowerType===f.borrowerType&&x.borrowerId===f.borrowerId),available=posted(p),due=Math.max(0,(f.principal||0)+(f.interestAccrued||0)),pay=Math.min(available,due);if(pay<=.001)return null;let principalPaid=Math.min(Math.max(0,f.principal||0),pay);f.principal=Math.max(0,(f.principal||0)-principalPaid);let interestPaid=Math.min(Math.max(0,f.interestAccrued||0),pay-principalPaid);f.interestAccrued=Math.max(0,(f.interestAccrued||0)-interestPaid);a.capital=(a.capital||0)+interestPaid;a.monetaryBase=Math.max(0,(a.monetaryBase||0)-principalPaid);a.outstandingCredit=Math.max(0,(a.outstandingCredit||0)-principalPaid);if(acct)acct.balance=Math.max(0,(acct.balance||0)-principalPaid);S.reservesExtinguished55=(S.reservesExtinguished55||0)+principalPaid;p.macroMarginPosted80=Math.max(0,available-pay);f.macroMarginPosted80=p.macroMarginPosted80;
let c=linkedCall(f),r={id:'MSX'+(++S.marginSetoffSerial81),positionId79:p.id,facilityId55:f.id,authorityId:f.authorityId,reality:f.reality,borrower:f.borrower,amount:pay,principalPaid,interestPaid,marginBefore:available,marginAfter:p.macroMarginPosted80,facilityPrincipalBefore:(f.principal||0)+principalPaid,facilityPrincipalAfter:f.principal||0,monetaryBaseAfter:a.monetaryBase,outstandingCreditAfter:a.outstandingCredit,callId55:c?.id||null,callCured81:false,callReopened81:false,marginDepleted81:p.macroMarginPosted80<=.01,created:Date.now(),x:10+Math.random()*80,y:12+Math.random()*68};if(c)applyCallSetoff(c,pay,r);if(f.principal<=.01&&f.interestAccrued<=.01){f.principal=0;f.interestAccrued=0;f.status='repaid';f.repaid=Date.now();f.repaidBySetoff81=true}S.marginSetoffs81.push(r);S.marginSetoffsExecuted81++;S.marginSetoffAmount81+=pay;S.marginSetoffPrincipalRetired81+=principalPaid;S.marginSetoffInterestPaid81+=interestPaid;if(r.marginDepleted81)S.marginSetoffMarginDepleted81++;markerRecord(r,p,f);remember('MARGIN SETOFF '+r.id+': '+f.borrower+' segregated margin '+pay.toFixed(2)+' extinguished '+principalPaid.toFixed(2)+' of '+f.id+' principal',realm(f.reality));trust(f.reality,'segregated-margin-setoff',r.id+' '+pay.toFixed(2));if(p.status!=='closed'&&p.status!=='open-unlevered'&&p.macroMarginPosted80<=.01)crisis(f.reality,'setoff depleted the carry margin while the FX position remained economically alive','SEV1');if(manual){q('#msg').textContent=r.id+' seized '+pay.toFixed(2)+' margin; '+(f.principal||0).toFixed(2)+' facility principal remains.';renderAll();save81();openSetoff(r)}return r}
function reconcile(){if(!ensure())return false;return reconstruct()}
function openSetoff(r){let p=position(r.positionId79),f=facility(r.facilityId55),acts=[['close',closePanel]];panel(r.id+' · SEGREGATED MARGIN SETOFF','EXECUTED',r.borrower+' · seized '+r.amount.toFixed(2)+' · principal retired '+r.principalPaid.toFixed(2)+' · interest '+r.interestPaid.toFixed(2)+' · posted margin '+r.marginBefore.toFixed(2)+'→'+r.marginAfter.toFixed(2)+' · facility '+r.facilityPrincipalBefore.toFixed(2)+'→'+r.facilityPrincipalAfter.toFixed(2)+(r.callId55?' · '+r.callId55+(r.callCured81?' CURED':r.callReopened81?' REOPENED':' REDUCED'):'')+(p?' · carry '+p.status:'')+(f?.status==='repaid'?' · FACILITY REPAID':''),acts)}
function openOffice(){if(!ensure())return;let acts=[];for(const p of(S.sterilizationCarryPositions79||[]).filter(eligible).slice(-6))acts.push(['set off '+p.id+' margin '+posted(p).toFixed(2),()=>setoff(p,true)]);for(const r of S.marginSetoffs81.slice(-8))acts.push(['open '+r.id+' · '+r.amount.toFixed(2),()=>openSetoff(r)]);acts.push(['close',closePanel]);panel(S.marginSetoffOffice81.name,'OFFSETTING · SMO1',S.marginSetoffsExecuted81+' setoffs · '+S.marginSetoffAmount81.toFixed(2)+' margin seized · '+S.marginSetoffPrincipalRetired81.toFixed(2)+' principal retired · '+S.marginSetoffCallsCured81+' Build55 calls cured · '+S.marginSetoffCallsReopened81+' calls reopened',acts)}
function executeInteresting(){let p=(S.sterilizationCarryPositions79||[]).filter(eligible).slice(-1)[0];if(!p){q('#msg').textContent='No stressed posted carry margin is eligible for public setoff.';return null}return setoff(p,true)}
function render81(){if(!ensure())return;let layer=q('#marginSetoffLayer81');if(!layer){layer=document.createElement('div');layer.id='marginSetoffLayer81';document.body.appendChild(layer)}layer.innerHTML='';let o=document.createElement('i');o.className='marginSetoffOffice81';o.dataset.label='SO';o.style.left='50%';o.style.top='94%';o.onclick=openOffice;layer.appendChild(o);for(const r of S.marginSetoffs81.slice(-8)){let e=document.createElement('i');e.className='marginSetoff81';e.dataset.label='↘';e.style.left=r.x+'%';e.style.top=r.y+'%';e.onclick=()=>openSetoff(r);layer.appendChild(e)}let line=q('#marginsetoffline81');if(!line){line=document.createElement('div');line.id='marginsetoffline81';line.className='line';(q('#carrymarginline80')||q('#sterilizationcarryline79')||q('#monetaryline')||q('#enforcement')).after(line)}line.textContent='margin setoff: '+S.marginSetoffsExecuted81+' seizures · '+S.marginSetoffPrincipalRetired81.toFixed(1)+' principal retired · '+S.marginSetoffCallsCured81+' calls cured · '+S.marginSetoffMarginDepleted81+' buffers depleted';let ctr=document.querySelector('#app .controls');if(ctr&&!q('#openMarginSetoff81')){let x=document.createElement('button');x.id='openMarginSetoff81';x.textContent='open margin setoff office';x.onclick=openOffice;ctr.prepend(x)}if(ctr&&!q('#executeMarginSetoff81')){let x=document.createElement('button');x.id='executeMarginSetoff81';x.textContent='set off posted carry margin';x.onclick=executeInteresting;ctr.prepend(x)}}
renderAll=function(){R81();let changed=reconcile();render81();if(changed)save81()};let f=q('#forget');if(f)f.onclick=()=>{for(let i=2;i<=81;i++)localStorage.removeItem('nothing-state-v'+i);location.reload()};setInterval(()=>{reconcile();render81();save81()},2300);ensure();reconcile();renderAll();save81();
})();