(()=>{
const B90=save,R90=renderAll,O=JSON.parse(localStorage.getItem('nothing-state-v90')||'null')||{},RECOVER90=!Array.isArray(O.monetaryRemediationEvents90),K=['monetaryRemediationOffice90','monetaryRemediationEvents90','monetaryRemediationSerial90','monetaryRemediationOrders90','monetaryRemediationReimpositions90','monetaryRemediationAuthorities90','monetaryRemediationCrises90','monetaryRemediationKeys90','lastMonetaryRemediationTick90'];
for(const k of K)S[k]=O[k]??(k==='monetaryRemediationEvents90'?[]:/Serial|Orders|Reimpositions|Authorities|Crises|Tick/.test(k)?0:/Keys/.test(k)?{}:/Office/.test(k)?null:[]);
function save90(){B90();let o={};for(const k of K)o[k]=S[k];localStorage.setItem('nothing-state-v90',JSON.stringify(o))}save=save90;
const q=s=>$(s),realm=id=>S.real[id],cl=(v,a,b)=>Math.max(a,Math.min(b,v)),GRADES=['AAA','AA','A','BBB','BB','B','CCC','D'];
function trust(id,status,note){S.trustAudits=S.trustAudits||[];S.trustAuditSerial=S.trustAuditSerial||0;S.trustAudits.push({id:'TA'+(++S.trustAuditSerial),reality:id,status,created:Date.now(),note,x:10+Math.random()*80,y:12+Math.random()*68})}
function incident(id,title,sev='SEV2'){S.incidents=S.incidents||[];S.incidentSerial=S.incidentSerial||0;let ex=S.incidents.find(x=>x.reality===id&&x.title===title&&x.status==='open');if(ex)return ex;let i={id:'INC'+(++S.incidentSerial),reality:id,title,severity:sev,status:'open',started:Date.now(),owner:'monetary supervisory remediation office',x:10+Math.random()*80,y:12+Math.random()*68};S.incidents.push(i);return i}
function crisis(id,why,key){let n=Date.now(),k=id+'|'+key;if(S.monetaryRemediationKeys90[k]&&n-S.monetaryRemediationKeys90[k]<14000)return;S.monetaryRemediationKeys90[k]=n;S.monetaryRemediationCrises90++;remember('MONETARY REMEDIATION: '+why+' converted foregone-interest governance damage into binding lender-of-last-resort policy',realm(id));if(typeof place==='function'){place('cold','central bank lost discretion one hundredth of foregone interest at a time',realm(id));place('dream','the lender of last resort being supervised by its rounding errors',realm(id))}incident(id,'monetary supervisory remediation: '+why,'SEV2')}
function ensure(){if(!S.interestMaterialityOffice89||!S.deMinimisInterestOffice88)return null;if(!S.monetaryRemediationOffice90){S.monetaryRemediationOffice90={id:'MRO1',name:'Interreality Monetary Supervisory Remediation Office',status:'supervising',created:Date.now(),x:50,y:76};remember('MONETARY REMEDIATION MRO1: repeated interest materiality acquired binding rate and collateral policy',realm('A'));remember('MONETARY REMEDIATION MRO1: repeated interest materiality acquired binding rate and collateral policy',realm('B'));trust('A','monetary-supervisory-remediation-created','MRO1');trust('B','monetary-supervisory-remediation-created','MRO1')}return S.monetaryRemediationOffice90}
function stageFor(a){let t=Math.max(0,a?.interestMaterialityTranches89||0);return t>=4?3:t>=3?2:t>=2?1:0}
function policy(stage){return stage===1?{rate:.075,floor:'A',tranches:2}:stage===2?{rate:.095,floor:'AA',tranches:3}:stage===3?{rate:.12,floor:'AAA',tranches:4}:null}
function gradeIndex(g){let i=GRADES.indexOf(g);return i<0?GRADES.length:i}
function tighterFloor(current,required){return gradeIndex(current)<=gradeIndex(required)?current:required}
function policyDrift(a,p){return (a.discountRate||0)+1e-9<p.rate||gradeIndex(a.collateralFloor)>gradeIndex(p.floor)}
function applyPolicy(a,p){let before={discountRate90:a.discountRate,collateralFloor90:a.collateralFloor};a.discountRate=Math.max(a.discountRate||0,p.rate);a.collateralFloor=tighterFloor(a.collateralFloor,p.floor);return{before,after:{discountRate90:a.discountRate,collateralFloor90:a.collateralFloor}}}
function upsert(arr,id,snap){let i=arr.findIndex(x=>x.id===id);if(i>=0)arr[i]=snap;else arr.push(snap)}
function marker(e,a){a.monetaryRemediationMarkers90=a.monetaryRemediationMarkers90||[];upsert(a.monetaryRemediationMarkers90,e.id,JSON.parse(JSON.stringify(e)));a.monetaryRemediationLatest90=e.id}
function makeEvent(kind,a,data={}){let e={id:'MSR'+(++S.monetaryRemediationSerial90),kind90:kind,status:'binding',authorityId:a.id,reality:a.reality,authorityName90:a.name,created:Date.now(),x:10+Math.random()*80,y:12+Math.random()*68,...data};S.monetaryRemediationEvents90.push(e);if(kind==='remediation-order')S.monetaryRemediationOrders90++;else S.monetaryRemediationReimpositions90++;marker(e,a);return e}
function installStage(a,stage){let p=policy(stage);if(!p)return null;let changes=applyPolicy(a,p),e=makeEvent('remediation-order',a,{stage90:stage,sourceTranches89:a.interestMaterialityTranches89||0,triggerTranche89:p.tranches,requiredDiscountRate90:p.rate,requiredCollateralFloor90:p.floor,...changes});let first=!(a.supervisoryStage90>0);a.supervisoryStage90=stage;a.supervisoryOrder90=e.id;a.supervisoryMinRate90=p.rate;a.supervisoryFloor90=p.floor;a.supervisedSince90=a.supervisedSince90||Date.now();a.supervisoryStatus90=stage===3?'severe-remediation':stage===2?'heightened-remediation':'remediation';if(first)S.monetaryRemediationAuthorities90++;remember('SUPERVISORY ORDER '+e.id+': '+a.name+' stage '+stage+' requires discount rate at least '+(p.rate*100).toFixed(1)+'% and '+p.floor+'-or-better collateral after '+p.tranches+' materiality tranches',realm(a.reality));trust(a.reality,'monetary-remediation-order',e.id+' stage '+stage);crisis(a.reality,a.name+' entered stage '+stage+' supervisory remediation','order-'+a.id+'-'+stage);return e}
function reimpose(a){let stage=Math.max(0,a.supervisoryStage90||0),p=policy(stage);if(!p||!policyDrift(a,p))return null;let changes=applyPolicy(a,p),e=makeEvent('policy-reimposition',a,{stage90:stage,sourceTranches89:a.interestMaterialityTranches89||0,requiredDiscountRate90:p.rate,requiredCollateralFloor90:p.floor,...changes});a.supervisoryMinRate90=p.rate;a.supervisoryFloor90=p.floor;a.supervisoryReimpositions90=(a.supervisoryReimpositions90||0)+1;remember('SUPERVISORY REIMPOSITION '+e.id+': '+a.name+' attempted policy below stage '+stage+' minima; rate/floor restored to '+(a.discountRate*100).toFixed(1)+'% / '+a.collateralFloor,realm(a.reality));trust(a.reality,'monetary-remediation-policy-reimposed',e.id+' stage '+stage);return e}
function reviewAuthority(a){let target=stageFor(a),current=Math.max(0,a.supervisoryStage90||0),changed=false;if(target>current){for(let s=current+1;s<=target;s++){installStage(a,s);changed=true}}if(reimpose(a))changed=true;return changed}
function reconstruct(){if(!RECOVER90)return false;let changed=false,seen=new Map();for(const a of(S.monetaryAuthorities55||[]))for(const m of(a.monetaryRemediationMarkers90||[]))seen.set(m.id,m);for(const m of seen.values()){if((S.monetaryRemediationEvents90||[]).some(x=>x.id===m.id))continue;let e=JSON.parse(JSON.stringify(m));e.recovered=true;S.monetaryRemediationEvents90.push(e);if(e.kind90==='remediation-order')S.monetaryRemediationOrders90++;else S.monetaryRemediationReimpositions90++;let n=Number(String(e.id).replace(/\D/g,''))||0;if(n>S.monetaryRemediationSerial90)S.monetaryRemediationSerial90=n;changed=true}S.monetaryRemediationAuthorities90=(S.monetaryAuthorities55||[]).filter(a=>(a.supervisoryStage90||0)>0).length;return changed}
function reconcile(){if(!ensure())return false;let changed=reconstruct();for(const a of(S.monetaryAuthorities55||[]))if(reviewAuthority(a))changed=true;return changed}
function openEvent(e){let detail=e.kind90==='remediation-order'?'stage '+e.stage90+' · materiality tranches '+e.sourceTranches89+' · required rate '+(e.requiredDiscountRate90*100).toFixed(1)+'% · floor '+e.requiredCollateralFloor90+' · actual '+(e.after.discountRate90*100).toFixed(1)+'% / '+e.after.collateralFloor90:'stage '+e.stage90+' · attempted '+(e.before.discountRate90*100).toFixed(1)+'% / '+e.before.collateralFloor90+' · restored '+(e.after.discountRate90*100).toFixed(1)+'% / '+e.after.collateralFloor90;panel(e.id+' · MONETARY REMEDIATION',e.kind90.toUpperCase(),e.authorityName90+' · '+detail,[['close',closePanel]])}
function openOffice(){if(!ensure())return;let acts=[];for(const e of S.monetaryRemediationEvents90.slice(-10))acts.push(['open '+e.id+' · '+e.kind90,()=>openEvent(e)]);acts.push(['close',closePanel]);panel(S.monetaryRemediationOffice90.name,'SUPERVISING · MRO1',S.monetaryRemediationAuthorities90+' supervised authorities · '+S.monetaryRemediationOrders90+' orders · '+S.monetaryRemediationReimpositions90+' policy reimpositions',acts)}
function render90(){if(!ensure())return;let layer=q('#monetaryRemediationLayer90');if(!layer){layer=document.createElement('div');layer.id='monetaryRemediationLayer90';document.body.appendChild(layer)}layer.innerHTML='';let o=document.createElement('i');o.className='monetaryRemediationOffice90';o.dataset.label='SUP';o.style.left='50%';o.style.top='76%';o.onclick=openOffice;layer.appendChild(o);for(const e of S.monetaryRemediationEvents90.slice(-8)){let n=document.createElement('i');n.className='monetaryRemediation90 '+e.kind90;n.dataset.label=e.kind90==='remediation-order'?'R!':'↺';n.style.left=e.x+'%';n.style.top=e.y+'%';n.onclick=()=>openEvent(e);layer.appendChild(n)}let line=q('#monetaryremediationline90');if(!line){line=document.createElement('div');line.id='monetaryremediationline90';line.className='line';(q('#interestmaterialityline89')||q('#deminimisinterestline88')||q('#monetaryline')||q('#enforcement')).after(line)}line.textContent='monetary remediation: '+S.monetaryRemediationAuthorities90+' supervised · '+S.monetaryRemediationOrders90+' orders · '+S.monetaryRemediationReimpositions90+' reimpositions';let ctr=document.querySelector('#app .controls');if(ctr&&!q('#openMonetaryRemediation90')){let x=document.createElement('button');x.id='openMonetaryRemediation90';x.textContent='open monetary remediation';x.onclick=openOffice;ctr.prepend(x)}}
renderAll=function(){R90();let changed=reconcile();render90();if(changed)save90()};let f=q('#forget');if(f)f.onclick=()=>{for(let i=2;i<=90;i++)localStorage.removeItem('nothing-state-v'+i);location.reload()};setInterval(()=>{reconcile();render90();save90()},2300);ensure();reconcile();renderAll();save90();
})();