(()=>{
const B78=save,R78=renderAll,O=JSON.parse(localStorage.getItem('nothing-state-v78')||'null')||{},RECOVER78=!Array.isArray(O.monetarySterilizations78),K=['monetarySterilizationOffice78','monetarySterilizations78','monetarySterilizationSerial78','monetarySterilizationRequests78','monetarySterilizationFacilities78','monetarySterilizationTarget78','monetarySterilizationIssued78','monetarySterilizationShortfall78','monetarySterilizationOverrides78','monetarySterilizationBlocks78','monetarySterilizationPegConstrained78','monetarySterilizationFXAmplification78','monetarySterilizationCrises78','monetarySterilizationKeys78','lastMonetarySterilizationTick78'];
for(const k of K)S[k]=O[k]??(/Serial|Requests|Facilities|Target|Issued|Shortfall|Overrides|Blocks|Constrained|Amplification|Crises|Tick/.test(k)?0:/Keys/.test(k)?{}:/Office/.test(k)?null:[]);
function save78(){B78();let o={};for(const k of K)o[k]=S[k];localStorage.setItem('nothing-state-v78',JSON.stringify(o))}save=save78;
const q=s=>$(s),realm=id=>S.real[id],trade=id=>(S.reserveRebalances77||[]).find(x=>x.id===id),bank=id=>(S.monetaryAuthorities55||[]).find(x=>x.reality===id),market=()=>S.fxMarkets56?.[0],fund=()=>S.stabilizationFunds58?.[0],cl=(v,a,b)=>Math.max(a,Math.min(b,v)),GR=['AAA','AA','A','BBB','BB','B','CCC','D'];
function trust(id,status,note){S.trustAudits=S.trustAudits||[];S.trustAuditSerial=S.trustAuditSerial||0;S.trustAudits.push({id:'TA'+(++S.trustAuditSerial),reality:id,status,created:Date.now(),note,x:10+Math.random()*80,y:12+Math.random()*68})}
function incident(id,title,sev='SEV1'){S.incidents=S.incidents||[];S.incidentSerial=S.incidentSerial||0;let ex=S.incidents.find(x=>x.reality===id&&x.title===title&&x.status==='open');if(ex)return ex;let i={id:'INC'+(++S.incidentSerial),reality:id,title,severity:sev,status:'open',started:Date.now(),owner:'monetary sterilization desk',x:10+Math.random()*80,y:12+Math.random()*68};S.incidents.push(i);return i}
function crisis(id,why,sev='SEV1'){let n=Date.now(),k=id+'|'+why;if(S.monetarySterilizationKeys78[k]&&n-S.monetarySterilizationKeys78[k]<14000)return;S.monetarySterilizationKeys78[k]=n;S.monetarySterilizationCrises78++;remember('STERILIZATION CRISIS: '+why+' made the central bank recreate liquidity after stabilization FX destroyed it',realm(id));if(typeof place==='function'){place('cold','central bank lending back the money the stabilization fund just retired',realm(id));place('dream','FX tightening sterilized with collateralized software credit',realm(id))}incident(id,'monetary sterilization crisis: '+why,sev)}
function ensure(){if(!S.reserveRebalanceOffice77||!market()||!fund())return null;if(!S.monetarySterilizationOffice78){S.monetarySterilizationOffice78={id:'MSD1',name:'Interreality Monetary Sterilization Desk',status:'offsetting',created:Date.now(),x:50,y:99.998};remember('MONETARY STERILIZATION MSD1: stabilization FX contraction acquired a collateralized liquidity offset',realm('A'));remember('MONETARY STERILIZATION MSD1: stabilization FX contraction acquired a collateralized liquidity offset',realm('B'));trust('A','monetary-sterilization-desk-created','MSD1');trust('B','monetary-sterilization-desk-created','MSD1')}return S.monetarySterilizationOffice78}
function grade(type,id,def='BBB'){let rs=(S.creditRatings52||[]).filter(r=>r.subjectType===type&&r.subjectId===id).sort((a,b)=>(b.published||0)-(a.published||0));return rs[0]?.grade||def}
function haircut(g){return{AAA:.04,AA:.07,A:.1,BBB:.18,BB:.32,B:.48,CCC:.68,D:.9}[g]??.25}
function eligible(a,g){let gi=GR.indexOf(g),fi=GR.indexOf(a?.collateralFloor||'BBB');return gi>=0&&fi>=0&&gi<=fi}
function activeDebt(type,id){return(S.liquidityFacilities55||[]).filter(f=>f.borrowerType===type&&f.borrowerId===id&&f.status==='active').reduce((n,f)=>n+Math.max(0,f.principal||0),0)}
function borrowerRows(reality){
 let out=[];
 for(const d of(S.derivativeDealers53||[]).filter(x=>x.reality===reality&&x.status==='solvent'&&(x.capital||0)>0)){let g=grade('dealer',d.id,'BBB'),face=Math.max(2,(d.collateral||0)+(d.capital||0)*.35);out.push({type:'dealer',id:d.id,name:d.name||d.id,obj:d,grade:g,face,cashField:'capital'})}
 for(const c of(S.clearinghouses54||[]).filter(x=>x.reality===reality&&x.status==='operating')){let g=grade('ccp',c.id,'A'),face=Math.max(4,(c.defaultFund||0)+(c.guaranteeFund||0));out.push({type:'ccp',id:c.id,name:c.name||c.id,obj:c,grade:g,face,cashField:'liquidity'})}
 for(const i of(S.insurers51||[]).filter(x=>x.reality===reality&&x.status!=='insolvent'&&(x.capital||0)>=8)){let g=grade('insurer',i.id,'BBB'),prem=(S.riskPolicies51||[]).filter(p=>p.insurerId===i.id&&p.status==='active').reduce((n,p)=>n+(p.premium||0),0),face=Math.max(4,prem+(i.reserves||0));out.push({type:'insurer',id:i.id,name:i.name||i.id,obj:i,grade:g,face,cashField:'capital'})}
 for(const tr of(S.packageTreasuries47||[])){let ns=(S.namespaces46||[]).find(n=>n.id===tr.namespaceId);if(!ns||ns.reality!==reality||tr.status==='bankrupt'||(tr.balance||0)<4)continue;let g=grade('treasury',tr.namespaceId,'BBB'),face=Math.max(3,(tr.balance||0)+5);out.push({type:'treasury',id:tr.namespaceId,name:(ns.name||tr.namespaceId)+' package treasury',obj:tr,grade:g,face,cashField:'balance'})}
 let a=bank(reality);for(const b of out){b.haircut=haircut(b.grade);b.lendable=b.face*(1-b.haircut);b.available=Math.max(0,b.lendable-activeDebt(b.type,b.id));b.eligible=eligible(a,b.grade)}return out.filter(b=>b.eligible&&b.available>.01).sort((x,y)=>y.available-x.available)
}
function accountFor(a,b){S.reserveAccounts55=S.reserveAccounts55||[];let x=S.reserveAccounts55.find(r=>r.borrowerType===b.type&&r.borrowerId===b.id);if(x)return x;S.reserveAccountSerial55=S.reserveAccountSerial55||0;x={id:'RA'+(++S.reserveAccountSerial55),authorityId:a.id,reality:a.reality,borrowerType:b.type,borrowerId:b.id,holder:b.name,balance:0,created:Date.now(),x:10+Math.random()*80,y:12+Math.random()*68};S.reserveAccounts55.push(x);return x}
function addCash(b,x){if(b.cashField==='liquidity')b.obj.liquidity=Math.max(0,(b.obj.liquidity||0)+x);else if(b.cashField==='balance')b.obj.balance=Math.max(0,(b.obj.balance||0)+x);else b.obj.capital=Math.max(0,(b.obj.capital||0)+x)}
function policyRatio(t){return(t.pegStress77?.length||0)>.0?.4:.8}
function recByTrade(id){return(S.monetarySterilizations78||[]).find(x=>x.rebalanceId77===id)||null}
function facilityRows(r){return(S.liquidityFacilities55||[]).filter(f=>f.sterilization78&&f.sterilizationId78===r.id)}
function reconstruct(){if(!RECOVER78)return false;let changed=false,seen=new Set();for(const f of(S.liquidityFacilities55||[]).filter(f=>f.sterilization78&&f.sterilizationId78)){if(seen.has(f.sterilizationId78))continue;seen.add(f.sterilizationId78);if((S.monetarySterilizations78||[]).some(r=>r.id===f.sterilizationId78))continue;let fs=(S.liquidityFacilities55||[]).filter(x=>x.sterilization78&&x.sterilizationId78===f.sterilizationId78),issued=fs.reduce((n,x)=>n+(x.sterilizationIssued78||x.originalPrincipal78||x.principal||0),0),t=trade(f.sourceRebalance77),ratio=f.sterilizationPolicyRatio78??policyRatio(t||{}),target=f.sterilizationTarget78??Math.max(0,(t?.sellAmount||0)*ratio),r={id:f.sterilizationId78,rebalanceId77:f.sourceRebalance77,reality:f.reality,baseRetired:t?.sellAmount||f.sourceBaseRetired78||0,policyRatio:ratio,target,issued,shortfall:Math.max(0,target-issued),status:issued+1e-9>=target?'implemented':'partial-collateral',facilityIds:fs.map(x=>x.id),override:!!f.sterilizationOverride78,countedShortfall78:Math.max(0,target-issued),blockCounted78:false,created:f.issued||Date.now(),x:f.x||10+Math.random()*80,y:f.y||12+Math.random()*68,recovered:true};S.monetarySterilizations78.push(r);S.monetarySterilizationRequests78++;S.monetarySterilizationFacilities78+=fs.length;S.monetarySterilizationTarget78+=target;S.monetarySterilizationIssued78+=issued;S.monetarySterilizationShortfall78+=r.shortfall;if(r.override)S.monetarySterilizationOverrides78++;if(ratio<.8)S.monetarySterilizationPegConstrained78++;let n=Number(String(r.id).replace(/\D/g,''))||0;if(n>S.monetarySterilizationSerial78)S.monetarySterilizationSerial78=n;changed=true}return changed}
function request(t,manual=true){ensure();if(!t)return null;let ex=recByTrade(t.id);if(ex)return ex;let ratio=policyRatio(t),target=Math.max(0,(t.sellAmount||0)*ratio),r={id:'MSO'+(++S.monetarySterilizationSerial78),rebalanceId77:t.id,reality:t.issuerReality,baseRetired:Math.max(0,t.sellAmount||0),policyRatio:ratio,target,issued:0,shortfall:target,status:'pending',facilityIds:[],override:false,countedShortfall78:0,blockCounted78:false,created:Date.now(),x:10+Math.random()*80,y:12+Math.random()*68};S.monetarySterilizations78.push(r);S.monetarySterilizationRequests78++;S.monetarySterilizationTarget78+=target;if(ratio<.8)S.monetarySterilizationPegConstrained78++;t.sterilizationId78=r.id;t.sterilizationTarget78=target;t.sterilizationPolicyRatio78=ratio;remember('STERILIZATION REQUEST '+r.id+': Reality '+r.reality+' targeted '+target.toFixed(2)+' of '+r.baseRetired.toFixed(2)+' monetary-base contraction after '+t.id,realm(r.reality));if(manual){q('#msg').textContent=r.id+' targets '+Math.round(ratio*100)+'% of '+t.id+' monetary tightening.';renderAll();save78();openSterilization(r)}return r}
function issueFacility(r,a,b,amount,override){let acct=accountFor(a,b);S.liquidityFacilities55=S.liquidityFacilities55||[];S.liquidityFacilitySerial55=S.liquidityFacilitySerial55||0;let f={id:'LF'+(++S.liquidityFacilitySerial55),authorityId:a.id,reality:r.reality,borrowerType:b.type,borrowerId:b.id,borrower:b.name,status:'active',conditionAtIssue:'solvent',principal:amount,rate:(a.discountRate??.055)+.005,interestAccrued:0,collateralType:b.type==='dealer'?'derivative collateral and margin receivables':b.type==='ccp'?'settlement receivables and default-fund claim':b.type==='insurer'?'premium receivables':'future dependency-tax receivables',collateralRef:b.id,collateralGrade:b.grade,collateralFace:b.face,haircut:b.haircut,collateralValue:b.lendable,undercollateralized:false,override:false,issued:Date.now(),matures:Date.now()+90000,lastAccrual:Date.now(),x:10+Math.random()*80,y:12+Math.random()*68,sterilization78:true,sterilizationId78:r.id,sourceRebalance77:r.rebalanceId77,sourceBaseRetired78:r.baseRetired,sterilizationPolicyRatio78:r.policyRatio,sterilizationTarget78:r.target,sterilizationIssued78:amount,originalPrincipal78:amount,sterilizationOverride78:!!override};S.liquidityFacilities55.push(f);acct.balance=(acct.balance||0)+amount;addCash(b,amount);a.monetaryBase=(a.monetaryBase||0)+amount;a.outstandingCredit=(a.outstandingCredit||0)+amount;S.reservesIssued55=(S.reservesIssued55||0)+amount;S.monetarySterilizationFacilities78++;r.facilityIds.push(f.id);return f}
function fxAmplify(r,issued){let t=trade(r.rebalanceId77),m=market(),f=fund();if(!t||!m||issued<=.001)return 0;let value=(f?.poolRA||0)*Math.max(.18,m.rate||1)+(f?.poolRB||0),liq=Math.max(20,20+value),impact=Math.min(.04,issued/liq*.06),sign=t.sellCode==='RB'?1:-1,before=m.rate;m.previousRate=m.rate;m.rate=cl((m.rate||1)*(1+sign*impact),.18,4.5);m.pressure=(m.pressure||0)+sign*issued*.012;m.turnover=(m.turnover||0)+issued*.2;m.lastMove=Date.now();let move=Math.abs(m.rate-before);S.monetarySterilizationFXAmplification78+=move;r.fxRateBefore78=before;r.fxRateAfter78=m.rate;r.fxAmplification78=move;return move}
function execute(r,override=false,manual=true){if(!r||!['pending','partial-collateral','blocked-negative-equity','blocked-collateral'].includes(r.status))return 0;let a=bank(r.reality);if(!a){r.status='blocked-record';return 0}if(a.status==='negative-equity'&&!override){r.status='blocked-negative-equity';if(!r.blockCounted78){S.monetarySterilizationBlocks78++;r.blockCounted78=true}crisis(r.reality,'negative-equity monetary authority refused to recreate liquidity after FX rebalancing','SEV1');if(manual){q('#msg').textContent=r.id+' is blocked by negative-equity monetary status.';renderAll();save78();openSterilization(r)}return 0}if(a.status==='negative-equity'&&override&&!r.override){r.override=true;S.monetarySterilizationOverrides78++;a.independence=cl((a.independence??.82)-.04,0,1);a.credibility=cl((a.credibility??.76)-.03,0,1);crisis(r.reality,'emergency override sterilized FX tightening through a negative-equity authority','SEV1')}
let need=Math.max(0,r.target-r.issued),issued=0,borrowers=borrowerRows(r.reality);for(const b of borrowers){if(need<=.001)break;let amt=Math.min(need,b.available);if(amt<=.001)continue;issueFacility(r,a,b,amt,override);issued+=amt;need-=amt}r.issued+=issued;r.shortfall=Math.max(0,r.target-r.issued);S.monetarySterilizationIssued78+=issued;let prevShort=r.countedShortfall78||0;S.monetarySterilizationShortfall78=Math.max(0,(S.monetarySterilizationShortfall78||0)+r.shortfall-prevShort);r.countedShortfall78=r.shortfall;if(r.shortfall>.001){if(issued<=.001){r.status='blocked-collateral';if(!r.blockCounted78){S.monetarySterilizationBlocks78++;r.blockCounted78=true}}else r.status='partial-collateral';crisis(r.reality,'eligible collateral could not fully sterilize the Build 77 monetary contraction','SEV2')}else{r.shortfall=0;r.status='implemented';r.completed=Date.now()}let t=trade(r.rebalanceId77);if(t){t.sterilizationIssued78=r.issued;t.sterilizationStatus78=r.status;t.sterilizationFacilityIds78=[...r.facilityIds]}if(issued>0){fxAmplify(r,issued);remember('STERILIZATION '+r.id+': '+a.name+' reissued '+issued.toFixed(2)+' settlement reserves against eligible collateral after '+r.rebalanceId77,realm(r.reality));if(typeof place==='function'){place('warm','temporary collateralized liquidity replacing money retired by stabilization FX',realm(r.reality));place('cold','central bank neutralizing its own reserve-redemption tightening',realm(r.reality))}trust(r.reality,'stabilization-fx-sterilized',r.id+' '+issued.toFixed(2))}if(manual){q('#msg').textContent=r.id+' issued '+issued.toFixed(2)+' reserves; '+r.shortfall.toFixed(2)+' of the sterilization target remains.';renderAll();save78();openSterilization(r)}return issued}
function reconcile(){if(!ensure())return false;let changed=reconstruct();for(const t of(S.reserveRebalances77||[])){if(t.status!=='executed'&&t.status!=='partial-liquidity')continue;if(!recByTrade(t.id)&&t.sterilizationId78){let fs=(S.liquidityFacilities55||[]).filter(f=>f.sterilization78&&f.sourceRebalance77===t.id);if(fs.length)changed=reconstruct()||changed} }return changed}
function eligibleTrades(){return(S.reserveRebalances77||[]).filter(t=>['executed','partial-liquidity'].includes(t.status)&&!recByTrade(t.id))}
function openFacility78(f){panel(f.id+' · BUILD 55 STERILIZATION FACILITY',f.status.toUpperCase(),f.borrower+' · principal '+(f.principal||0).toFixed(2)+' · '+f.collateralGrade+' '+f.collateralType+' · collateral value '+(f.collateralValue||0).toFixed(2)+' · rate '+((f.rate||0)*100).toFixed(2)+'% · source '+f.sourceRebalance77,[['close',closePanel]])}
function openSterilization(r){let a=bank(r.reality),acts=[];if(['pending','partial-collateral','blocked-collateral'].includes(r.status))acts.push(['issue collateralized sterilization',()=>execute(r,false,true)]);if(r.status==='blocked-negative-equity')acts.push(['emergency negative-equity override',()=>execute(r,true,true)]);for(const f of facilityRows(r).slice(-5))acts.push(['open '+f.id+' · '+f.borrower,()=>openFacility78(f)]);acts.push(['close',closePanel]);panel(r.id+' · MONETARY STERILIZATION',r.status.toUpperCase(),r.reality+' · source '+r.rebalanceId77+' · base retired '+r.baseRetired.toFixed(2)+' · policy '+Math.round(r.policyRatio*100)+'% · target '+r.target.toFixed(2)+' · issued '+r.issued.toFixed(2)+' · shortfall '+r.shortfall.toFixed(2)+' · authority base '+(a?.monetaryBase||0).toFixed(2)+(r.fxRateAfter78?' · RA/RB '+r.fxRateBefore78.toFixed(4)+'→'+r.fxRateAfter78.toFixed(4):'')+(r.override?' · EMERGENCY OVERRIDE':''),acts)}
function openOffice(){if(!ensure())return;let acts=[];for(const t of eligibleTrades().slice(-6))acts.push(['request sterilization for '+t.id,()=>request(t,true)]);for(const r of S.monetarySterilizations78.slice(-8))acts.push(['open '+r.id+' · '+r.status,()=>openSterilization(r)]);acts.push(['close',closePanel]);panel(S.monetarySterilizationOffice78.name,'OFFSETTING · MSD1',S.monetarySterilizationRequests78+' requests · '+S.monetarySterilizationIssued78.toFixed(2)+' reserves reissued · '+S.monetarySterilizationFacilities78+' Build 55 facilities · '+S.monetarySterilizationBlocks78+' blocks · '+S.monetarySterilizationOverrides78+' overrides',acts)}
function requestInteresting(){let t=eligibleTrades().slice(-1)[0];if(!t){q('#msg').textContent='No unsterilized Build 77 FX contraction is available.';return null}return request(t,true)}
function render78(){if(!ensure())return;let layer=q('#monetarySterilizationLayer78');if(!layer){layer=document.createElement('div');layer.id='monetarySterilizationLayer78';document.body.appendChild(layer)}layer.innerHTML='';let o=document.createElement('i');o.className='monetarySterilizationOffice78';o.dataset.label='ST';o.style.left='50%';o.style.top='99.998%';o.onclick=openOffice;layer.appendChild(o);for(const r of S.monetarySterilizations78.filter(x=>x.status!=='implemented').slice(-8)){let e=document.createElement('i');e.className='monetarySterilization78 '+r.status;e.dataset.label='M+';e.style.left=r.x+'%';e.style.top=r.y+'%';e.onclick=()=>openSterilization(r);layer.appendChild(e)}let line=q('#monetarysterilizationline78');if(!line){line=document.createElement('div');line.id='monetarysterilizationline78';line.className='line';(q('#reserverebalanceline77')||q('#monetaryline')||q('#fxline')||q('#enforcement')).after(line)}line.textContent='sterilization: '+S.monetarySterilizationIssued78.toFixed(1)+' reserves reissued · '+S.monetarySterilizationFacilities78+' facilities · '+S.monetarySterilizationBlocks78+' blocks · '+S.monetarySterilizationPegConstrained78+' peg-constrained';let ctr=document.querySelector('#app .controls');if(ctr&&!q('#openMonetarySterilization78')){let x=document.createElement('button');x.id='openMonetarySterilization78';x.textContent='open monetary sterilization';x.onclick=openOffice;ctr.prepend(x)}if(ctr&&!q('#requestMonetarySterilization78')){let x=document.createElement('button');x.id='requestMonetarySterilization78';x.textContent='sterilize FX contraction';x.onclick=requestInteresting;ctr.prepend(x)}}
renderAll=function(){R78();let changed=reconcile();render78();if(changed)save78()};let f=q('#forget');if(f)f.onclick=()=>{for(let i=2;i<=78;i++)localStorage.removeItem('nothing-state-v'+i);location.reload()};setInterval(()=>{reconcile();render78();save78()},2300);ensure();reconcile();renderAll();save78();
})();