(()=>{
const BS55=save,BR55=renderAll,O55=JSON.parse(localStorage.getItem('nothing-state-v55')||'null')||{},cl=(v,a,b)=>Math.max(a,Math.min(b,v)),pick=a=>a&&a.length?a[Math.floor(Math.random()*a.length)]:null;
const GRADES55=['AAA','AA','A','BBB','BB','B','CCC','D'];
S.monetaryAuthorities55=O55.monetaryAuthorities55||[];
S.reserveAccounts55=O55.reserveAccounts55||[];
S.liquidityFacilities55=O55.liquidityFacilities55||[];
S.monetaryCollateralCalls55=O55.monetaryCollateralCalls55||[];
S.makeGoodPayments55=O55.makeGoodPayments55||[];
S.monetaryAudits55=O55.monetaryAudits55||[];
S.monetaryAuthoritySerial55=O55.monetaryAuthoritySerial55||0;
S.reserveAccountSerial55=O55.reserveAccountSerial55||0;
S.liquidityFacilitySerial55=O55.liquidityFacilitySerial55||0;
S.monetaryCollateralCallSerial55=O55.monetaryCollateralCallSerial55||0;
S.makeGoodSerial55=O55.makeGoodSerial55||0;
S.monetaryAuditSerial55=O55.monetaryAuditSerial55||0;
S.reservesIssued55=O55.reservesIssued55||0;
S.reservesExtinguished55=O55.reservesExtinguished55||0;
S.emergencyLoans55=O55.emergencyLoans55||0;
S.insolventLoans55=O55.insolventLoans55||0;
S.monetaryCollateralCallsIssued55=O55.monetaryCollateralCallsIssued55||0;
S.monetaryCollateralCallsMet55=O55.monetaryCollateralCallsMet55||0;
S.collateralForbearance55=O55.collateralForbearance55||0;
S.collateralMonetizations55=O55.collateralMonetizations55||0;
S.makeGoods55=O55.makeGoods55||0;
S.negativeEquityAuthorities55=O55.negativeEquityAuthorities55||0;
S.monetaryCrises55=O55.monetaryCrises55||0;
S.lastMonetaryCrisis55=O55.lastMonetaryCrisis55||0;
S.monetaryKeys55=O55.monetaryKeys55||{};
S.lastMonetaryTick55=O55.lastMonetaryTick55||Date.now();
function save55(){BS55();localStorage.setItem('nothing-state-v55',JSON.stringify({monetaryAuthorities55:S.monetaryAuthorities55,reserveAccounts55:S.reserveAccounts55,liquidityFacilities55:S.liquidityFacilities55,monetaryCollateralCalls55:S.monetaryCollateralCalls55,makeGoodPayments55:S.makeGoodPayments55,monetaryAudits55:S.monetaryAudits55,monetaryAuthoritySerial55:S.monetaryAuthoritySerial55,reserveAccountSerial55:S.reserveAccountSerial55,liquidityFacilitySerial55:S.liquidityFacilitySerial55,monetaryCollateralCallSerial55:S.monetaryCollateralCallSerial55,makeGoodSerial55:S.makeGoodSerial55,monetaryAuditSerial55:S.monetaryAuditSerial55,reservesIssued55:S.reservesIssued55,reservesExtinguished55:S.reservesExtinguished55,emergencyLoans55:S.emergencyLoans55,insolventLoans55:S.insolventLoans55,monetaryCollateralCallsIssued55:S.monetaryCollateralCallsIssued55,monetaryCollateralCallsMet55:S.monetaryCollateralCallsMet55,collateralForbearance55:S.collateralForbearance55,collateralMonetizations55:S.collateralMonetizations55,makeGoods55:S.makeGoods55,negativeEquityAuthorities55:S.negativeEquityAuthorities55,monetaryCrises55:S.monetaryCrises55,lastMonetaryCrisis55:S.lastMonetaryCrisis55,monetaryKeys55:S.monetaryKeys55,lastMonetaryTick55:S.lastMonetaryTick55}))}save=save55;
const realm=id=>S.real[id],ccp=id=>(S.clearinghouses54||[]).find(x=>x.id===id),insurer=id=>(S.insurers51||[]).find(x=>x.id===id),treasury=id=>(S.packageTreasuries47||[]).find(x=>x.namespaceId===id),dealer=id=>(S.derivativeDealers53||[]).find(x=>x.id===id),ns=id=>(S.namespaces46||[]).find(n=>n.id===id),bond=id=>(S.softwareBonds52||[]).find(b=>b.id===id),authority=id=>S.monetaryAuthorities55.find(a=>a.id===id);
function trust55(id,status,note){let accepted=S.trustPolicies?.[id]?.acceptedRoots||[],r=[...(S.trustRoots||[])].filter(x=>accepted.includes(x.id)&&x.status==='active').sort((a,b)=>(b.strength||0)-(a.strength||0))[0];S.trustAudits=S.trustAudits||[];S.trustAuditSerial=S.trustAuditSerial||0;S.trustAudits.push({id:'TA'+(++S.trustAuditSerial),reality:id,remediationId:null,credentialId:null,certificateId:null,rootId:r?.id||null,status,created:Date.now(),note,x:10+Math.random()*80,y:12+Math.random()*68})}
function incident55(id,title,severity='SEV2'){S.incidents=S.incidents||[];let ex=S.incidents.find(i=>i.reality===id&&i.title===title&&i.status==='open');if(ex)return ex;S.incidentSerial=S.incidentSerial||0;let x={id:'INC'+(++S.incidentSerial),reality:id,title,severity,status:'open',alertIds:[],started:Date.now(),acknowledged:null,resolved:null,postmortem:null,owner:'settlement reserve authority',x:10+Math.random()*80,y:12+Math.random()*68};S.incidents.push(x);return x}
function ensureAuthorities(){for(const id of ['A','B'])if(!S.monetaryAuthorities55.some(a=>a.reality===id)){let a={id:'MA'+(++S.monetaryAuthoritySerial55),reality:id,name:'Reality '+id+' Settlement Reserve Authority',status:'operating',discountRate:.055,collateralFloor:'BBB',monetaryBase:0,outstandingCredit:0,capital:14,badAssets:0,independence:.82,credibility:.76,emergencyMandate:0,rateMoves:0,created:Date.now(),x:46+Math.random()*8,y:7+Math.random()*10};S.monetaryAuthorities55.push(a);remember('MONETARY AUTHORITY '+a.id+': Reality '+id+' created a lender of last resort for settlement infrastructure',realm(id));trust55(id,'software-monetary-authority-created',a.id+' '+a.name)}}
const bank=id=>{ensureAuthorities();return S.monetaryAuthorities55.find(a=>a.reality===id)};
function borrower(type,id){if(type==='ccp'){let o=ccp(id);return o?{type,id,reality:o.reality,name:o.name,obj:o}:null}if(type==='insurer'){let o=insurer(id);return o?{type,id,reality:o.reality,name:o.name,obj:o}:null}if(type==='treasury'){let o=treasury(id),n=ns(id);return o&&n?{type,id,reality:n.reality,name:n.name+' package treasury',obj:o}:null}if(type==='dealer'){let o=dealer(id);return o?{type,id,reality:o.reality,name:o.name,obj:o}:null}return null}
function borrowerCash(b){if(!b)return 0;if(b.type==='ccp')return b.obj.liquidity||0;if(b.type==='treasury')return b.obj.balance||0;return b.obj.capital||0}
function addBorrowerCash(b,v){if(!b)return;if(b.type==='ccp')b.obj.liquidity=Math.max(0,(b.obj.liquidity||0)+v);else if(b.type==='treasury')b.obj.balance=Math.max(0,(b.obj.balance||0)+v);else b.obj.capital=Math.max(0,(b.obj.capital||0)+v)}
function debtOf(b){if(!b)return 0;if(b.type==='treasury')return (b.obj.debt||0)+(b.obj.capitalDebt52||0)+(S.softwareBonds52||[]).filter(x=>x.subjectType==='treasury'&&x.subjectId===b.id&&x.status==='active').reduce((n,x)=>n+(x.principal||0),0);if(b.type==='insurer')return (b.obj.debt52||0)+(S.softwareBonds52||[]).filter(x=>x.subjectType==='insurer'&&x.subjectId===b.id&&x.status==='active').reduce((n,x)=>n+(x.principal||0),0);return S.liquidityFacilities55.filter(f=>f.borrowerType===b.type&&f.borrowerId===b.id&&f.status==='active').reduce((n,f)=>n+f.principal,0)}
function makeGoodForCycle(id){return S.makeGoodPayments55.filter(x=>x.cycleId===id).reduce((n,x)=>n+x.amount,0)}
function ccpArrears(id){return (S.settlementCycles54||[]).filter(c=>c.ccpId===id&&c.shortfall>0).reduce((n,c)=>n+Math.max(0,c.shortfall-makeGoodForCycle(c.id)),0)}
function liveUsers55(n){let ids=new Set();for(const sb of (S.sboms45||[]).filter(x=>x.reality===n.reality&&x.status==='current'))if((sb.components||[]).some(pid=>(S.packages45||[]).find(p=>p.id===pid)?.name===n.name))ids.add(sb.artifactId);return ids.size}
function conditionOf(b){if(!b)return'unknown';if(b.type==='ccp'){let arrears=ccpArrears(b.id),assets=(b.obj.capital||0)+(b.obj.defaultFund||0)+(b.obj.guaranteeFund||0);if(b.obj.status==='failed'&&arrears>assets)return'insolvent';if(arrears>assets*.8)return'insolvent';if((b.obj.liquidity||0)<Math.max(4,arrears)||['failed','frozen','stressed'].includes(b.obj.status))return'illiquid';return'solvent'}if(b.type==='insurer'){if(b.obj.status==='insolvent'||(b.obj.capital||0)<=0)return'insolvent';let d=debtOf(b);if(d>(b.obj.capital||0)*1.8)return'insolvent';if((b.obj.capital||0)<8||b.obj.status==='rating-restricted')return'illiquid';return'solvent'}if(b.type==='treasury'){if(b.obj.status==='bankrupt')return'insolvent';let n=ns(b.id),capacity=(b.obj.balance||0)+(n?liveUsers55(n)*5:0)+8;if(debtOf(b)>capacity*1.4)return'insolvent';if((b.obj.balance||0)<4||b.obj.status==='strike')return'illiquid';return'solvent'}if(b.type==='dealer'){if(b.obj.status==='default'||(b.obj.capital||0)<=0)return'insolvent';if((b.obj.capital||0)+(b.obj.collateral||0)<5)return'illiquid';return'solvent'}return'unknown'}
function ratingOf(b){let rs=(S.creditRatings52||[]).filter(r=>r.subjectType===b.type&&r.subjectId===b.id).sort((a,b)=>b.published-a.published);if(rs.length)return rs[0].grade;if(b.type==='ccp')return b.obj.status==='operating'?'A':b.obj.status==='stressed'?'BBB':'BB';if(b.type==='dealer')return b.obj.status==='solvent'?'BBB':'CCC';return'BBB'}
function haircut55(g){return {AAA:.04,AA:.07,A:.1,BBB:.18,BB:.32,B:.48,CCC:.68,D:.9}[g]??.25}
function floorIndex(g){return GRADES55.indexOf(g)}
function eligibleGrade(a,g){return floorIndex(g)>=0&&floorIndex(g)<=floorIndex(a.collateralFloor)}
function collateralAsset(b){let g=ratingOf(b),face=0,type='institutional receivable',ref=b.id;if(b.type==='ccp'){face=Math.max(4,(b.obj.defaultFund||0)+(b.obj.guaranteeFund||0)+Math.max(0,(S.settlementQueue54||[]).filter(q=>q.ccpId===b.id&&!q.final).reduce((n,q)=>n+(q.amount-q.settled),0)));type='settlement receivables and default-fund claim'}else if(b.type==='insurer'){face=Math.max(4,(S.riskPolicies51||[]).filter(p=>p.insurerId===b.id&&p.status==='active').reduce((n,p)=>n+(p.premium||0),0)+(b.obj.reserves||0));type='premium receivables'}else if(b.type==='treasury'){let n=ns(b.id);face=Math.max(3,(b.obj.balance||0)+(n?liveUsers55(n)*6:0));type='future dependency-tax receivables'}else if(b.type==='dealer'){face=Math.max(2,(b.obj.collateral||0)+(b.obj.capital||0)*.35);type='derivative collateral and margin receivables'}return{type,ref,grade:g,face,haircut:haircut55(g),lendable:face*(1-haircut55(g))}}
function accountFor(b){let x=S.reserveAccounts55.find(a=>a.borrowerType===b.type&&a.borrowerId===b.id);if(x)return x;x={id:'RA'+(++S.reserveAccountSerial55),authorityId:bank(b.reality).id,reality:b.reality,borrowerType:b.type,borrowerId:b.id,holder:b.name,balance:0,created:Date.now(),x:10+Math.random()*80,y:12+Math.random()*68};S.reserveAccounts55.push(x);return x}
function monetaryCrisis(id,kind){let now=Date.now(),k=id+'|'+kind;if(S.monetaryKeys55[k]&&now-S.monetaryKeys55[k]<15000)return;S.monetaryKeys55[k]=now;S.monetaryCrises55++;S.lastMonetaryCrisis55=now;remember('MONETARY CRISIS: '+kind+' made public settlement money another source of institutional authority',realm(id));if(typeof place==='function'){place('cold','settlement credits backed by emergency exception',realm(id));place('dream','central bank balance sheet holding software failure',realm(id))}let b=$('#bailiff');if(b)b.textContent='asking whether the money is good because the authority accepted the collateral';incident55(id,'software monetary crisis: '+kind,kind.includes('negative')||kind.includes('insolvent')?'SEV1':'SEV2')}
function evaluateAuthority(a){let active=S.liquidityFacilities55.filter(f=>f.authorityId===a.id&&f.status==='active'),bad=active.reduce((n,f)=>n+Math.max(0,f.principal-f.collateralValue),0)+S.liquidityFacilities55.filter(f=>f.authorityId===a.id&&f.status==='monetized').reduce((n,f)=>n+Math.max(0,f.principal-f.collateralValue),0);a.outstandingCredit=active.reduce((n,f)=>n+f.principal,0);a.badAssets=bad;if(a.badAssets>a.capital&&a.status!=='negative-equity'){a.status='negative-equity';S.negativeEquityAuthorities55++;remember('MONETARY NEGATIVE EQUITY: '+a.name+' kept issuing reserves after bad collateral exceeded its capital',realm(a.reality));if(typeof place==='function')place('cold','central bank with negative equity still issuing reserves',realm(a.reality));monetaryCrisis(a.reality,'negative-equity monetary authority')}if(a.badAssets<=a.capital*.75&&a.status==='negative-equity')a.status='operating';a.credibility=cl(a.credibility-(a.badAssets>0?a.badAssets/Math.max(50,a.monetaryBase+50)*.002:0),0,1)}
function extendFacility(b,amount=null,override=false,manual=true){ensureAuthorities();if(!b)return null;let a=bank(b.reality),cond=conditionOf(b),col=collateralAsset(b);amount=amount??Math.max(4,Math.min(18,(b.type==='ccp'?Math.max(6,ccpArrears(b.id)+4):Math.max(5,8-borrowerCash(b)))));amount=Math.round(amount*10)/10;let eligible=eligibleGrade(a,col.grade),collateralValue=col.lendable;if((cond==='insolvent'||!eligible||collateralValue+1e-9<amount)&&!override){if(manual){$('#msg').textContent=b.name+' is '+cond+' with '+col.grade+' collateral worth '+collateralValue.toFixed(1)+' after haircut. Ordinary lender-of-last-resort rules refuse the loan.';renderAll();save55();openBorrower(b)}return null}let emergency=cond!=='solvent'||!eligible||collateralValue<amount,acct=accountFor(b),rate=a.discountRate+(cond==='illiquid' ? .025 : cond==='insolvent' ? .09 : .01)+(!eligible ? .025 : 0),f={id:'LF'+(++S.liquidityFacilitySerial55),authorityId:a.id,reality:b.reality,borrowerType:b.type,borrowerId:b.id,borrower:b.name,status:'active',conditionAtIssue:cond,principal:amount,rate,interestAccrued:0,collateralType:col.type,collateralRef:col.ref,collateralGrade:col.grade,collateralFace:col.face,haircut:col.haircut,collateralValue,undercollateralized:collateralValue+1e-9<amount,override:!!override,issued:Date.now(),matures:Date.now()+90000,lastAccrual:Date.now(),x:10+Math.random()*80,y:12+Math.random()*68};S.liquidityFacilities55.push(f);acct.balance+=amount;addBorrowerCash(b,amount);a.monetaryBase+=amount;a.outstandingCredit+=amount;S.reservesIssued55+=amount;if(emergency)S.emergencyLoans55++;if(cond==='insolvent'){S.insolventLoans55++;a.independence=cl(a.independence-.05,0,1);a.credibility=cl(a.credibility-.035,0,1);remember('SOLVENCY OVERRIDE '+f.id+': '+a.name+' called '+b.name+' liquid enough to fund despite insolvency signals',realm(b.reality));if(typeof place==='function')place('cold','insolvent institution called illiquid by policy',realm(b.reality));monetaryCrisis(b.reality,'insolvent borrower funded as liquidity problem')}if(!eligible||f.undercollateralized){a.badAssets+=Math.max(0,amount-collateralValue);remember('BAD COLLATERAL '+f.id+': '+a.name+' created reserves against '+col.grade+' '+col.type,realm(b.reality));if(typeof place==='function')place('cold','liquidity created against collateral the rule rejected',realm(b.reality))}if(b.type==='ccp'&&['failed','frozen','stressed'].includes(b.obj.status)){b.obj.status='operating';b.obj.monetaryBridge55=(b.obj.monetaryBridge55||0)+amount;remember('CCP REOPENED '+b.id+': central-bank reserves restored settlement operations without rewriting prior shortfalls',realm(b.reality))}trust55(b.reality,'software-lender-of-last-resort-facility',f.id+' '+b.name+' '+amount+' reserves against '+col.grade+' '+col.type);evaluateAuthority(a);if(manual){$('#msg').textContent=f.id+' created '+amount.toFixed(1)+' settlement reserves for '+b.name+'.';renderAll();save55();openFacility(f)}return f}
function revalueFacility(f,manual=true){if(!f||!['active','monetized'].includes(f.status))return;let b=borrower(f.borrowerType,f.borrowerId),a=authority(f.authorityId);if(!b||!a)return;let col=collateralAsset(b);f.collateralGrade=col.grade;f.collateralFace=col.face;f.haircut=col.haircut;f.collateralValue=col.lendable;f.undercollateralized=f.collateralValue+1e-9<f.principal;if(f.status==='active'&&f.undercollateralized&&!S.monetaryCollateralCalls55.some(c=>c.facilityId===f.id&&c.status==='open')){let amt=Math.round((f.principal-f.collateralValue)*10)/10,c={id:'CBMC'+(++S.monetaryCollateralCallSerial55),facilityId:f.id,authorityId:a.id,reality:f.reality,borrowerType:f.borrowerType,borrowerId:f.borrowerId,borrower:f.borrower,amount:amt,status:'open',reason:'haircut widened after collateral revaluation to '+col.grade,issued:Date.now(),paid:0,x:10+Math.random()*80,y:12+Math.random()*68};S.monetaryCollateralCalls55.push(c);S.monetaryCollateralCallsIssued55++;remember('CENTRAL BANK COLLATERAL CALL '+c.id+': '+f.borrower+' owes '+amt.toFixed(1)+' after '+col.grade+' revaluation',realm(f.reality));if(typeof place==='function')place('cold','lender of last resort issuing its own margin call',realm(f.reality))}evaluateAuthority(a);if(manual){renderAll();save55();openFacility(f)}}
function repayFacility(f,amount=null,manual=true){if(!f||f.status!=='active')return false;let b=borrower(f.borrowerType,f.borrowerId),a=authority(f.authorityId),acct=S.reserveAccounts55.find(x=>x.borrowerType===f.borrowerType&&x.borrowerId===f.borrowerId),due=f.principal+f.interestAccrued,pay=Math.min(amount??due,borrowerCash(b));if(pay<=0)return false;addBorrowerCash(b,-pay);let principalPay=Math.min(f.principal,pay);f.principal-=principalPay;let interestPay=Math.min(f.interestAccrued,pay-principalPay);f.interestAccrued-=interestPay;a.capital+=interestPay;a.monetaryBase=Math.max(0,a.monetaryBase-principalPay);a.outstandingCredit=Math.max(0,a.outstandingCredit-principalPay);if(acct)acct.balance=Math.max(0,acct.balance-principalPay);S.reservesExtinguished55+=principalPay;if(f.principal<=.01&&f.interestAccrued<=.01){f.principal=0;f.interestAccrued=0;f.status='repaid';f.repaid=Date.now();remember('RESERVES EXTINGUISHED '+f.id+': '+f.borrower+' repaid lender-of-last-resort credit',realm(f.reality))}evaluateAuthority(a);if(manual){$('#msg').textContent=f.id+' repaid '+pay.toFixed(1)+' credits; '+f.principal.toFixed(1)+' principal remains.';renderAll();save55();openFacility(f)}return true}
function meetMonetaryCall(c,manual=true){if(!c||c.status!=='open')return false;let f=S.liquidityFacilities55.find(f=>f.id===c.facilityId),b=borrower(c.borrowerType,c.borrowerId);if(!f||!b)return false;let pay=Math.min(c.amount,borrowerCash(b));if(pay>0){repayFacility(f,pay,false);c.paid=pay}if(pay+1e-9>=c.amount){c.status='met';c.met=Date.now();S.monetaryCollateralCallsMet55++;remember('CENTRAL BANK COLLATERAL CALL MET '+c.id+': '+c.borrower+' returned '+pay.toFixed(1)+' reserves',realm(c.reality))}else{c.status='failed';c.failed=Date.now();remember('CENTRAL BANK COLLATERAL CALL FAILED '+c.id+': '+c.borrower+' could not return enough reserves',realm(c.reality));monetaryCrisis(c.reality,'lender-of-last-resort collateral call failed')}if(manual){renderAll();save55();openMonetaryCall(c)}return c.status==='met'}
function forbearCall(c,manual=true){if(!c||!['open','failed'].includes(c.status))return;c.status='forborne';c.forborne=Date.now();S.collateralForbearance55++;let f=S.liquidityFacilities55.find(f=>f.id===c.facilityId),a=authority(c.authorityId);if(f)f.forborne=true;if(a){a.independence=cl(a.independence-.04,0,1);a.credibility=cl(a.credibility-.03,0,1)}remember('MONETARY FORBEARANCE '+c.id+': collateral shortfall was waived so emergency liquidity could remain outstanding',realm(c.reality));if(typeof place==='function')place('dream','bad collateral kept good by policy decision',realm(c.reality));monetaryCrisis(c.reality,'collateral forbearance');if(manual){renderAll();save55();openMonetaryCall(c)}}
function monetizeFacility(f,manual=true){if(!f||f.status!=='active')return;let a=authority(f.authorityId);f.status='monetized';f.monetized=Date.now();a.outstandingCredit=Math.max(0,a.outstandingCredit-f.principal);S.collateralMonetizations55++;remember('COLLATERAL MONETIZED '+f.id+': '+a.name+' converted emergency credit into a permanent holding of '+f.collateralType,realm(f.reality));if(typeof place==='function'){place('warm','central bank holding the collateral nobody else wanted',realm(f.reality));place('cold','emergency loan became permanent money',realm(f.reality))}trust55(f.reality,'software-collateral-monetized',f.id+' '+f.collateralType+' '+f.principal);evaluateAuthority(a);monetaryCrisis(f.reality,'emergency credit became permanent money');if(manual){renderAll();save55();openFacility(f)}}
function makeGoodCycle(cy,manual=true){if(!cy||cy.shortfall<=0)return null;let c=ccp(cy.ccpId),b=c?borrower('ccp',c.id):null;if(!b)return null;let already=makeGoodForCycle(cy.id),need=Math.max(0,cy.shortfall-already);if(need<=.01){if(manual)$('#msg').textContent=cy.id+' has already been economically made good.';return null}let f=extendFacility(b,need,true,false);if(!f){f=extendFacility(b,need,true,true,false)}if(!f)return null;let pay=Math.min(need,borrowerCash(b));addBorrowerCash(b,-pay);let acct=S.reserveAccounts55.find(x=>x.borrowerType==='ccp'&&x.borrowerId===b.id);if(acct)acct.balance=Math.max(0,acct.balance-pay);let m={id:'MGP'+(++S.makeGoodSerial55),reality:cy.reality,cycleId:cy.id,ccpId:cy.ccpId,facilityId:f.id,amount:pay,created:Date.now(),x:10+Math.random()*80,y:12+Math.random()*68};S.makeGoodPayments55.push(m);S.makeGoods55++;cy.makeGood55=(cy.makeGood55||0)+pay;if(cy.makeGood55+0.01>=cy.shortfall)cy.economicArrearsCured55=true;let remaining=pay;for(const q of (S.settlementQueue54||[]).filter(q=>cy.itemIds?.includes(q.id)&&q.status==='final-with-shortfall')){let gap=Math.max(0,q.amount-q.settled-(q.makeGood55||0)),x=Math.min(remaining,gap);q.makeGood55=(q.makeGood55||0)+x;remaining-=x;if(remaining<=.01)break}remember('SETTLEMENT MAKE-GOOD '+m.id+': '+pay.toFixed(1)+' newly issued reserves paid arrears after '+cy.id+' was already final',realm(cy.reality));if(typeof place==='function'){place('warm','money arrived after settlement was declared final',realm(cy.reality));place('dream','finality came before payment',realm(cy.reality))}trust55(cy.reality,'software-settlement-make-good',m.id+' '+cy.id+' '+pay);if(manual){$('#msg').textContent=cy.id+' received '+pay.toFixed(1)+' reserves after finality; original shortfall remains in its historical record.';renderAll();save55();openCycle55(cy)}return m}
function moveRate(a,delta){a.discountRate=cl(a.discountRate+delta,.005,.3);a.rateMoves++;remember('DISCOUNT RATE: '+a.name+' moved lender-of-last-resort rate to '+(a.discountRate*100).toFixed(1)+'%',realm(a.reality));renderAll();save55();openAuthority(a)}
function moveFloor(a,dir){let i=floorIndex(a.collateralFloor);i=cl(i+dir,0,GRADES55.length-2);a.collateralFloor=GRADES55[i];remember('COLLATERAL POLICY: '+a.name+' now accepts '+a.collateralFloor+' or better',realm(a.reality));if(dir>0){a.emergencyMandate++;a.independence=cl(a.independence-.015,0,1)}renderAll();save55();openAuthority(a)}
function auditMoney(id=S.active){let a=bank(id);for(const f of S.liquidityFacilities55.filter(f=>f.authorityId===a.id&&['active','monetized'].includes(f.status)))revalueFacility(f,false);evaluateAuthority(a);let x={id:'MAUD'+(++S.monetaryAuditSerial55),reality:id,authorityId:a.id,base:a.monetaryBase,credit:a.outstandingCredit,badAssets:a.badAssets,capital:a.capital,credibility:a.credibility,created:Date.now()};S.monetaryAudits55.push(x);S.monetaryAudits55=S.monetaryAudits55.slice(-80);remember('MONETARY AUDIT '+x.id+': base '+x.base.toFixed(1)+' · credit '+x.credit.toFixed(1)+' · bad assets '+x.badAssets.toFixed(1),realm(id));renderAll();save55();openAuthority(a);return x}
function criticalBorrowers(id){let xs=[];for(const c of (S.clearinghouses54||[]).filter(c=>c.reality===id))xs.push(borrower('ccp',c.id));for(const i of (S.insurers51||[]).filter(i=>i.reality===id&&['solvent','rating-restricted','insolvent','guaranteed'].includes(i.status)))xs.push(borrower('insurer',i.id));for(const n of (S.namespaces46||[]).filter(n=>n.reality===id))if(treasury(n.id))xs.push(borrower('treasury',n.id));for(const d of (S.derivativeDealers53||[]).filter(d=>d.reality===id))xs.push(borrower('dealer',d.id));return xs.filter(Boolean).sort((a,b)=>{let rank={insolvent:0,illiquid:1,solvent:2,unknown:3};return rank[conditionOf(a)]-rank[conditionOf(b)]||borrowerCash(a)-borrowerCash(b)})}
function openMonetaryCall(c){let f=S.liquidityFacilities55.find(f=>f.id===c.facilityId),acts=[];if(c.status==='open')acts.push(['meet collateral call',()=>meetMonetaryCall(c,true)],['forbear collateral call',()=>forbearCall(c,true)]);if(c.status==='failed')acts.push(['forbear failed call',()=>forbearCall(c,true)]);if(f)acts.push(['open '+f.id,()=>openFacility(f)]);acts.push(['close',closePanel]);panel(c.id+' · CENTRAL BANK COLLATERAL CALL',c.status+' · '+c.reason,c.borrower+' owes '+c.amount.toFixed(1)+' · paid '+(c.paid||0).toFixed(1),acts)}
function openFacility(f){let b=borrower(f.borrowerType,f.borrowerId),acts=[];if(f.status==='active')acts.push(['revalue collateral',()=>revalueFacility(f,true)],['repay facility',()=>repayFacility(f,null,true)],['monetize collateral',()=>monetizeFacility(f,true)]);for(const c of S.monetaryCollateralCalls55.filter(c=>c.facilityId===f.id&&['open','failed','forborne'].includes(c.status)).slice(-2))acts.push(['open '+c.id,()=>openMonetaryCall(c)]);acts.push(['close',closePanel]);panel(f.id+' · '+f.status.toUpperCase(),f.borrower+' · '+f.conditionAtIssue,'principal '+f.principal.toFixed(1)+' · rate '+(f.rate*100).toFixed(1)+'% · collateral '+f.collateralGrade+' '+f.collateralType+' · face '+f.collateralFace.toFixed(1)+' · haircut '+(f.haircut*100).toFixed(0)+'% · lendable '+f.collateralValue.toFixed(1)+(f.undercollateralized?' · UNDERCOLLATERALIZED':'')+' · borrower cash '+(b?borrowerCash(b).toFixed(1):'n/a'),acts)}
function openCycle55(cy){let acts=[];if(cy.shortfall>makeGoodForCycle(cy.id)+.01)acts.push(['make good unpaid settlement',()=>makeGoodCycle(cy,true)]);acts.push(['close',closePanel]);panel(cy.id+' · '+cy.status.toUpperCase(),'Build 54 settlement cycle','historical shortfall '+cy.shortfall.toFixed(1)+' · made good later '+makeGoodForCycle(cy.id).toFixed(1)+(cy.economicArrearsCured55?' · ARREARS ECONOMICALLY CURED':''),acts)}
function openBorrower(b){let a=bank(b.reality),col=collateralAsset(b),cond=conditionOf(b),acts=[['lend under ordinary rules',()=>extendFacility(b,null,false,true)],['lend anyway / solvency override',()=>extendFacility(b,null,true,true)]];for(const f of S.liquidityFacilities55.filter(f=>f.borrowerType===b.type&&f.borrowerId===b.id).slice(-3))acts.push(['open '+f.id,()=>openFacility(f)]);if(b.type==='ccp')for(const cy of (S.settlementCycles54||[]).filter(c=>c.ccpId===b.id&&c.shortfall>0).slice(-3))acts.push(['arrears '+cy.id,()=>openCycle55(cy)]);acts.push(['close',closePanel]);panel(b.name+' · '+cond.toUpperCase(),b.type+' · reserves '+(S.reserveAccounts55.find(x=>x.borrowerType===b.type&&x.borrowerId===b.id)?.balance||0).toFixed(1),'cash/liquidity '+borrowerCash(b).toFixed(1)+' · debt '+debtOf(b).toFixed(1)+' · collateral '+col.grade+' '+col.type+' · '+col.face.toFixed(1)+' face / '+col.lendable.toFixed(1)+' after haircut · authority floor '+a.collateralFloor,acts)}
function openAuthority(a){evaluateAuthority(a);let xs=criticalBorrowers(a.reality),acts=[['audit monetary balance sheet',()=>auditMoney(a.reality)],['raise discount rate',()=>moveRate(a,.01)],['lower discount rate',()=>moveRate(a,-.01)],['loosen collateral floor',()=>moveFloor(a,1)],['tighten collateral floor',()=>moveFloor(a,-1)]];for(const b of xs.slice(0,7))acts.push([b.name+' · '+conditionOf(b),()=>openBorrower(b)]);for(const f of S.liquidityFacilities55.filter(f=>f.authorityId===a.id&&['active','monetized'].includes(f.status)).slice(-4))acts.push(['open '+f.id,()=>openFacility(f)]);for(const cy of (S.settlementCycles54||[]).filter(c=>c.reality===a.reality&&c.shortfall>makeGoodForCycle(c.id)+.01).slice(-3))acts.push(['make good '+cy.id,()=>makeGoodCycle(cy,true)]);acts.push(['close',closePanel]);panel(a.name+' · '+a.status.toUpperCase(),a.id+' · lender of last resort','base '+a.monetaryBase.toFixed(1)+' · outstanding credit '+a.outstandingCredit.toFixed(1)+' · capital '+a.capital.toFixed(1)+' · bad assets '+a.badAssets.toFixed(1)+' · rate '+(a.discountRate*100).toFixed(1)+'% · floor '+a.collateralFloor+' · independence '+Math.round(a.independence*100)+'% · credibility '+Math.round(a.credibility*100)+'%',acts)}
function openMonetary(id=S.active){openAuthority(bank(id))}
function provideReserves(id=S.active){let xs=criticalBorrowers(id),b=xs.find(x=>conditionOf(x)==='illiquid')||xs.find(x=>x.type==='ccp'&&['failed','frozen','stressed'].includes(x.obj.status))||xs[0];if(!b){$('#msg').textContent='No eligible infrastructure exists for settlement-reserve lending.';return}let f=extendFacility(b,null,false,true);if(!f)openBorrower(b)}
function accrue(){let now=Date.now();for(const f of S.liquidityFacilities55.filter(f=>f.status==='active')){let dt=Math.max(0,now-(f.lastAccrual||now));if(dt>0){f.interestAccrued+=(f.principal*f.rate)*(dt/60000)/30;f.lastAccrual=now}if(now>=f.matures){let b=borrower(f.borrowerType,f.borrowerId);if(borrowerCash(b)>=f.principal*.75)repayFacility(f,null,false);else{f.matures=now+60000;let a=authority(f.authorityId);if(a){a.independence=cl(a.independence-.01,0,1);a.credibility=cl(a.credibility-.008,0,1)}remember('EVERGREEN FACILITY '+f.id+': emergency liquidity matured and was extended because repayment would destabilize '+f.borrower,realm(f.reality));if(typeof place==='function')place('dream','temporary emergency liquidity that keeps renewing itself',realm(f.reality))}}}}
function autonomous(){ensureAuthorities();let now=Date.now();if(now-S.lastMonetaryTick55<1900)return;S.lastMonetaryTick55=now;accrue();for(const a of S.monetaryAuthorities55){evaluateAuthority(a);let stressed=criticalBorrowers(a.reality).filter(b=>conditionOf(b)==='illiquid');if(stressed.length&&Math.random()<.003){extendFacility(pick(stressed),null,false,false);break}let fs=S.liquidityFacilities55.filter(f=>f.authorityId===a.id&&f.status==='active');if(fs.length&&Math.random()<.018)revalueFacility(pick(fs),false)}}
function renderMonetary(){ensureAuthorities();let layer=$('#monetaryLayer');if(!layer){layer=document.createElement('div');layer.id='monetaryLayer';document.body.appendChild(layer)}layer.innerHTML='';for(const a of S.monetaryAuthorities55){let e=document.createElement('i');e.className='monetaryAuthority '+a.status;e.dataset.label=a.id;e.style.left=a.x+'%';e.style.top=a.y+'%';e.onclick=()=>openAuthority(a);layer.appendChild(e)}for(const f of S.liquidityFacilities55.filter(f=>['active','monetized'].includes(f.status)).slice(-16)){let e=document.createElement('i');e.className='liquidityFacility '+f.status+(f.undercollateralized?' bad':'');e.dataset.label=f.id.replace('LF','L');e.style.left=f.x+'%';e.style.top=f.y+'%';e.onclick=()=>openFacility(f);layer.appendChild(e)}for(const c of S.monetaryCollateralCalls55.filter(c=>['open','failed'].includes(c.status)).slice(-10)){let e=document.createElement('i');e.className='monetaryCall '+c.status;e.dataset.label='CB!';e.style.left=c.x+'%';e.style.top=c.y+'%';e.onclick=()=>openMonetaryCall(c);layer.appendChild(e)}for(const m of S.makeGoodPayments55.slice(-8)){let e=document.createElement('i');e.className='makeGood';e.dataset.label='+';e.style.left=m.x+'%';e.style.top=m.y+'%';let cy=(S.settlementCycles54||[]).find(c=>c.id===m.cycleId);e.onclick=()=>cy&&openCycle55(cy);layer.appendChild(e)}let line=$('#monetaryline');if(!line){line=document.createElement('div');line.id='monetaryline';line.className='line';($('#clearingline')||$('#derivativesline')||$('#capitalline')||$('#enforcement')).after(line)}let a=bank(S.active),calls=S.monetaryCollateralCalls55.filter(c=>c.reality===S.active&&c.status==='open').length;line.textContent='settlement money: base '+a.monetaryBase.toFixed(1)+' · credit '+a.outstandingCredit.toFixed(1)+' · bad assets '+a.badAssets.toFixed(1)+' · '+calls+' collateral calls · '+S.makeGoods55+' make-goods · '+S.monetaryCrises55+' crises';let ctr=document.querySelector('#app .controls');if(ctr&&!$('#openMonetaryButton')){let x=document.createElement('button');x.id='openMonetaryButton';x.textContent='open monetary authority';x.onclick=()=>openMonetary(S.active);ctr.prepend(x)}if(ctr&&!$('#provideReservesButton')){let x=document.createElement('button');x.id='provideReservesButton';x.textContent='provide settlement reserves';x.onclick=()=>provideReserves(S.active);ctr.prepend(x)}}
renderAll=function(){BR55();renderMonetary()};let f=$('#forget');if(f)f.onclick=()=>{for(let i=2;i<=55;i++)localStorage.removeItem('nothing-state-v'+i);location.reload()};
setInterval(()=>{autonomous();renderMonetary();save55()},2200);ensureAuthorities();renderAll();save55();
})();
