(()=>{
const BS38=save,BR38=renderAll,O38=JSON.parse(localStorage.getItem('nothing-state-v38')||'null')||{},cl=(v,a,b)=>Math.max(a,Math.min(b,v)),pick=a=>a&&a.length?a[Math.floor(Math.random()*a.length)]:null;
const RESPONDERS=['traveler','bailiff','archive clerk','career administrator','court clerk'];
S.onCall=O38.onCall||{A:{responder:'traveler',since:Date.now(),fatigue:0,pages:0},B:{responder:'archive clerk',since:Date.now(),fatigue:0,pages:0}};
S.opsPages=O38.opsPages||[];S.runbooks=O38.runbooks||[];S.remediationRuns=O38.remediationRuns||[];S.opsPageSerial=O38.opsPageSerial||0;S.runbookSerial=O38.runbookSerial||0;S.remediationSerial=O38.remediationSerial||0;S.pagesSent=O38.pagesSent||0;S.pagesAcked=O38.pagesAcked||0;S.pagesEscalated=O38.pagesEscalated||0;S.autoRemediations=O38.autoRemediations||0;S.manualRemediations=O38.manualRemediations||0;S.remediationSuccesses=O38.remediationSuccesses||0;S.remediationFailures=O38.remediationFailures||0;S.runbookLoops=O38.runbookLoops||0;S.changeFreezes=O38.changeFreezes||{A:false,B:false};S.alertFatigueEvents=O38.alertFatigueEvents||0;S.opsCrises=O38.opsCrises||0;S.lastOpsCrisis=O38.lastOpsCrisis||0;S.opsKeys=O38.opsKeys||{};S.opsAutomationEnabled=O38.opsAutomationEnabled??true;
for(const id of['A','B'])S.onCall[id]=Object.assign({responder:id==='A'?'traveler':'archive clerk',since:Date.now(),fatigue:0,pages:0},S.onCall[id]||{});
S.opsPages=S.opsPages.map((p,i)=>({id:p.id||'P'+(i+1),reality:p.reality||'A',incidentId:p.incidentId||null,alertId:p.alertId||null,responder:p.responder||'traveler',status:p.status||'paging',sent:p.sent||Date.now(),acknowledged:p.acknowledged||null,escalations:p.escalations||0,autoAck:!!p.autoAck,x:Number.isFinite(p.x)?p.x:10+Math.random()*80,y:Number.isFinite(p.y)?p.y:12+Math.random()*68}));
S.runbooks=S.runbooks.map((r,i)=>({id:r.id||'RB'+(i+1),reality:r.reality||'A',kind:r.kind||'freeze-change',name:r.name||'unnamed runbook',metricKind:r.metricKind||null,status:r.status||'active',confidence:Number.isFinite(r.confidence)?r.confidence:.6,executions:r.executions||0,successes:r.successes||0,failures:r.failures||0,source:r.source||'operations',created:r.created||Date.now(),x:Number.isFinite(r.x)?r.x:10+Math.random()*80,y:Number.isFinite(r.y)?r.y:12+Math.random()*68}));
S.remediationRuns=S.remediationRuns.map((r,i)=>({id:r.id||'RM'+(i+1),reality:r.reality||'A',incidentId:r.incidentId||null,runbookId:r.runbookId||null,status:r.status||'completed',automatic:!!r.automatic,summary:r.summary||'',sideEffect:r.sideEffect||'',created:r.created||Date.now(),x:Number.isFinite(r.x)?r.x:10+Math.random()*80,y:Number.isFinite(r.y)?r.y:12+Math.random()*68}));
function save38(){BS38();localStorage.setItem('nothing-state-v38',JSON.stringify({onCall:S.onCall,opsPages:S.opsPages,runbooks:S.runbooks,remediationRuns:S.remediationRuns,opsPageSerial:S.opsPageSerial,runbookSerial:S.runbookSerial,remediationSerial:S.remediationSerial,pagesSent:S.pagesSent,pagesAcked:S.pagesAcked,pagesEscalated:S.pagesEscalated,autoRemediations:S.autoRemediations,manualRemediations:S.manualRemediations,remediationSuccesses:S.remediationSuccesses,remediationFailures:S.remediationFailures,runbookLoops:S.runbookLoops,changeFreezes:S.changeFreezes,alertFatigueEvents:S.alertFatigueEvents,opsCrises:S.opsCrises,lastOpsCrisis:S.lastOpsCrisis,opsKeys:S.opsKeys,opsAutomationEnabled:S.opsAutomationEnabled}))}save=save38;
const realm=id=>S.real[id],incident=id=>(S.incidents||[]).find(n=>n.id===id),alert=id=>(S.telemetryAlerts||[]).find(a=>a.id===id),metric=(id,k)=>(S.telemetryMetrics||[]).find(m=>m.reality===id&&m.kind===k),activeRollout=id=>[...(S.rollouts||[])].reverse().find(d=>d.reality===id&&['canary','rolling','paused','rollback-partial'].includes(d.status)),runtime=id=>S.runtimeReality?.[id]||{stableHead:null,cohorts:{}},openIncident=id=>[...(S.incidents||[])].reverse().find(n=>n.reality===id&&n.status==='open');
function metricKindForIncident(n){let a=(n.alertIds||[]).map(alert).find(Boolean);if(a)return a.metricKind;let t=(n.title||'').toLowerCase();for(const k of['runtime-consistency','production-health','timeline-confidence','institutional-agreement','record-integrity','citizenship-legibility'])if(t.includes(k.replaceAll('-',' ')))return k;return'production-health'}
function addRunbook(id,kind,name,metricKind,source='operations'){let r=S.runbooks.find(r=>r.reality===id&&r.kind===kind&&r.status==='active');if(r)return r;r={id:'RB'+(++S.runbookSerial),reality:id,kind,name,metricKind,status:'active',confidence:.58+Math.random()*.18,executions:0,successes:0,failures:0,source,created:Date.now(),x:10+Math.random()*80,y:12+Math.random()*68};S.runbooks.push(r);S.runbooks=S.runbooks.slice(-28);return r}
function ensureRunbooks(){for(const id of['A','B']){addRunbook(id,'converge-runtime','Converge production runtimes','runtime-consistency');addRunbook(id,'rollback-release','Rollback active release','production-health');addRunbook(id,'rewrite-history','Reduce timeline drift','timeline-confidence');addRunbook(id,'freeze-change','Freeze changes and quiet disagreement','institutional-agreement');addRunbook(id,'seal-record','Stabilize official record','record-integrity');addRunbook(id,'choose-citizenship','Select authoritative citizenship issuer','citizenship-legibility');for(const n of(S.incidents||[]).filter(n=>n.reality===id&&n.postmortem)){let k=metricKindForIncident(n),kind={"runtime-consistency":'converge-runtime',"production-health":'rollback-release',"timeline-confidence":'rewrite-history',"institutional-agreement":'freeze-change',"record-integrity":'seal-record',"citizenship-legibility":'choose-citizenship'}[k]||'freeze-change';let r=addRunbook(id,kind,'Postmortem automation for '+k,k,'postmortem '+n.id);r.confidence=cl(r.confidence+.01,.25,.96)}}}
function bestRunbook(n){let k=metricKindForIncident(n),rs=S.runbooks.filter(r=>r.reality===n.reality&&r.status==='active'&&r.metricKind===k);return [...rs].sort((a,b)=>b.confidence-a.confidence)[0]||S.runbooks.find(r=>r.reality===n.reality&&r.kind==='freeze-change')}
function pageForIncident(n,automatic=true){if(!n||n.status!=='open')return null;let existing=S.opsPages.find(p=>p.incidentId===n.id&&['paging','acknowledged','escalated'].includes(p.status));if(existing)return existing;let oc=S.onCall[n.reality],p={id:'P'+(++S.opsPageSerial),reality:n.reality,incidentId:n.id,alertId:(n.alertIds||[])[0]||null,responder:oc.responder,status:'paging',sent:Date.now(),acknowledged:null,escalations:0,autoAck:false,x:10+Math.random()*80,y:12+Math.random()*68};S.opsPages.push(p);S.opsPages=S.opsPages.slice(-30);S.pagesSent++;oc.pages++;oc.fatigue=cl(oc.fatigue+.08+(n.severity==='SEV1'?.08:0),0,1);remember('PAGE '+p.id+': '+oc.responder+' paged for '+n.id,realm(n.reality));if(typeof place==='function')place('cold','pager vibrating beside '+oc.responder,realm(n.reality));if(automatic&&oc.fatigue>.72&&Math.random()<.28){p.status='acknowledged';p.acknowledged=Date.now();p.autoAck=true;S.pagesAcked++;S.alertFatigueEvents++;remember('ALERT FATIGUE: '+p.id+' was acknowledged reflexively without investigation',realm(n.reality));if(typeof place==='function')place('dream','page acknowledged while nobody woke up',realm(n.reality))}return p}
function acknowledgePage(p){if(!p||p.status!=='paging')return;p.status='acknowledged';p.acknowledged=Date.now();S.pagesAcked++;let oc=S.onCall[p.reality];oc.fatigue=cl(oc.fatigue+.03,0,1);let n=incident(p.incidentId);if(n&&!n.acknowledged){n.acknowledged=Date.now();n.owner=p.responder}remember('ON-CALL ACK '+p.id+': '+p.responder+' accepted '+p.incidentId,realm(p.reality));$('#msg').textContent=p.id+' acknowledged by '+p.responder+'. The runbook is now the most tempting explanation.';openPage(p);save38()}
function escalatePage(p){if(!p||!['paging','acknowledged'].includes(p.status))return;let choices=RESPONDERS.filter(x=>x!==p.responder),next=pick(choices);p.responder=next;p.status='escalated';p.escalations++;S.pagesEscalated++;S.onCall[p.reality].fatigue=cl(S.onCall[p.reality].fatigue+.04,0,1);remember('PAGE ESCALATED '+p.id+': incident moved to '+next,realm(p.reality));$('#msg').textContent=p.id+' escalated to '+next+'. Responsibility moved faster than the incident.';openPage(p);save38()}
function dominantRuntime(id){let rt=runtime(id),counts={};for(const v of Object.values(rt.cohorts||{}))counts[v||'∅']=(counts[v||'∅']||0)+1;return Object.entries(counts).sort((a,b)=>b[1]-a[1])[0]?.[0]||rt.stableHead||null}
function applyRunbook(r,n){let id=r.reality,world=realm(id),side='',success=true;if(r.kind==='converge-runtime'){let rt=runtime(id),winner=dominantRuntime(id);if(winner&&winner!=='∅'){for(const k of Object.keys(rt.cohorts||{}))rt.cohorts[k]=winner;rt.stableHead=winner;world.disputes=(world.disputes||0)+1;side='all cohorts were forced onto '+winner+', increasing institutional dispute';}else{success=false;side='no runtime existed to converge'}}
else if(r.kind==='rollback-release'){let d=activeRollout(id);if(d){let rt=runtime(id),refused=[];for(const cid of Object.keys(rt.cohorts||{})){let prev=d.previous?.[cid]??d.fromHead??rt.stableHead??null;let resist=(cid==='agencies'||cid==='courts')&&Math.random()<.22;if(resist){refused.push(cid);continue}rt.cohorts[cid]=prev}d.status=refused.length?'rollback-partial':'rolled-back';if(!refused.length)S.deploymentsRolledBack=(S.deploymentsRolledBack||0)+1;else S.rollbackRefusals=(S.rollbackRefusals||0)+refused.length;side=refused.length?'rollback left '+refused.join(', ')+' on the bad runtime':'release rolled back, but its historical effects remain'}else{success=false;side='no active release existed to roll back'}}
else if(r.kind==='rewrite-history'){world.timelineDrift=Math.max(0,(world.timelineDrift||0)-2);S.recordDivergence=(S.recordDivergence||0)+2;side='timeline score improved by moving contradiction into the official record'}
else if(r.kind==='freeze-change'){S.changeFreezes[id]=true;let d=activeRollout(id);if(d&&['canary','rolling'].includes(d.status)){d.status='paused';d.pausedAt=Date.now();S.deploymentsPaused=(S.deploymentsPaused||0)+1}world.disputes=Math.max(0,(world.disputes||0)-1);for(const a of(S.agencies||[]).filter(a=>a.reality===id&&a.status==='active'))a.autonomy=cl((a.autonomy||.5)+.015,.05,.99);side='change froze and disagreement fell, while permanent administration gained autonomy'}
else if(r.kind==='seal-record'){let z=pick((S.redactions||[]).filter(z=>z.status!=='sealed'));if(z){z.status='sealed';z.authority=cl((z.authority||.6)+.08,.2,.99)}else S.recordDivergence=Math.max(0,(S.recordDivergence||0)-1);world.timelineDrift=(world.timelineDrift||0)+.4;side=z?'uncertain evidence was sealed to stabilize the record':'record divergence was reduced without recovering missing evidence'}
else if(r.kind==='choose-citizenship'){let cs=(S.citizenships||[]).filter(c=>c.reality===id&&['active','disputed'].includes(c.status));if(cs.length>1){let winner=[...cs].sort((a,b)=>(b.authority||0)-(a.authority||0))[0];for(const c of cs)if(c!==winner)c.status='disputed';winner.authority=cl((winner.authority||.5)+.05,.2,.99);side='one citizenship issuer was privileged and the others became disputed'}else{success=false;side='there was no competing citizenship issuer to select'}}
return{success,side}}
function updateObservedMetric(r){let m=metric(r.reality,r.metricKind);if(!m)return;let before=m.value;if(r.kind==='converge-runtime')m.value=Math.max(m.value,96);else if(r.kind==='rollback-release')m.value=Math.max(m.value,88);else if(r.kind==='rewrite-history')m.value=Math.max(m.value,82);else if(r.kind==='freeze-change')m.value=Math.max(m.value,80);else if(r.kind==='seal-record')m.value=Math.max(m.value,84);else if(r.kind==='choose-citizenship')m.value=Math.max(m.value,78);m.lastValue=before;m.samples=(m.samples||[]).concat([{at:Date.now(),value:m.value,source:'runbook '+r.id}]).slice(-18);m.breachStreak=0;for(const a of(S.telemetryAlerts||[]).filter(a=>a.reality===r.reality&&a.metricKind===r.metricKind&&['firing','acknowledged'].includes(a.status)))a.status='resolved'}
function executeRunbook(r,n,automatic=false){if(!r||!n||n.status!=='open')return null;r.executions++;automatic?S.autoRemediations++:S.manualRemediations++;let z=applyRunbook(r,n),rm={id:'RM'+(++S.remediationSerial),reality:r.reality,incidentId:n.id,runbookId:r.id,status:z.success?'completed':'failed',automatic,summary:r.name,sideEffect:z.side,created:Date.now(),x:10+Math.random()*80,y:12+Math.random()*68};S.remediationRuns.push(rm);S.remediationRuns=S.remediationRuns.slice(-34);if(z.success){r.successes++;r.confidence=cl(r.confidence+.025,.2,.98);S.remediationSuccesses++;updateObservedMetric(r);if(Math.random()<.72){n.status='resolved';n.resolved=Date.now();S.incidentsResolved=(S.incidentsResolved||0)+1}remember((automatic?'AUTO-REMEDIATION ':'RUNBOOK ')+rm.id+': '+r.name+' · '+z.side,realm(r.reality));if(typeof place==='function')place('warm',automatic?'automation closed incident before explanation':'runbook changed production',realm(r.reality));$('#msg').textContent=rm.id+' '+(automatic?'auto-':'')+'remediated '+n.id+'. '+z.side+'.';detectLoop(r,n,rm)}else{r.failures++;r.confidence=cl(r.confidence-.05,.15,.98);S.remediationFailures++;remember('RUNBOOK FAILURE '+rm.id+': '+z.side,realm(r.reality));if(typeof place==='function')place('cold','runbook had no applicable reality',realm(r.reality));$('#msg').textContent=rm.id+' failed: '+z.side+'.'}renderAll();save38();if(!automatic)openRemediation(rm);return rm}
function detectLoop(r,n,rm){let recent=S.remediationRuns.filter(x=>x.reality===r.reality&&x.created>Date.now()-30000&&x.status==='completed'),kinds=new Set(recent.map(x=>S.runbooks.find(q=>q.id===x.runbookId)?.metricKind).filter(Boolean));if(recent.length>=3&&kinds.size>=2){let key=r.reality+'|'+[...kinds].sort().join(',')+'|'+Math.floor(Date.now()/20000);if(!S.opsKeys[key]){S.opsKeys[key]=1;S.runbookLoops++;realm(r.reality).timelineDrift=(realm(r.reality).timelineDrift||0)+1;remember('RUNBOOK LOOP: automation fixed one objective by breaking another',realm(r.reality));if(typeof place==='function')place('cold','automation chasing its own side effects',realm(r.reality));opsCrisis(r.reality,'runbook-loop')}}}
function opsCrisis(id,reason){if(Date.now()-S.lastOpsCrisis<8000)return false;let key=id+'|'+reason+'|'+(openIncident(id)?.id||'none');if(S.opsKeys['crisis-'+key])return false;S.opsKeys['crisis-'+key]=1;S.opsCrises++;S.lastOpsCrisis=Date.now();for(const rid of['A','B']){realm(rid).disputes=(realm(rid).disputes||0)+1;remember('OPERATIONS CRISIS: remediation became an authority over reality',realm(rid))}if(typeof place==='function'){place('dream','runbook executing before anyone reads the incident',realm(id));place('cold','automation with emergency powers',realm(id))}S.bailiffMood='obeying the runbook because it resolved the page';$('#msg').textContent='OPERATIONS CRISIS: the response system is changing reality faster than anyone can explain it.';return true}
function rotateOnCall(id=S.active){let oc=S.onCall[id],choices=RESPONDERS.filter(x=>x!==oc.responder),old=oc.responder;oc.responder=pick(choices);oc.since=Date.now();oc.fatigue=Math.max(0,oc.fatigue-.28);remember('ON-CALL HANDOFF: '+old+' handed Reality '+id+' to '+oc.responder,realm(id));$('#msg').textContent='Reality '+id+' on-call moved from '+old+' to '+oc.responder+'. The pager history stayed.';renderAll();save38();openOps()}
function toggleAutomation(){S.opsAutomationEnabled=!S.opsAutomationEnabled;remember('OPS AUTOMATION '+(S.opsAutomationEnabled?'ENABLED':'DISABLED'),realm(S.active));$('#msg').textContent='Automatic remediation '+(S.opsAutomationEnabled?'enabled':'disabled')+'.';renderAll();save38();openOps()}
function openRunbook(r){let n=openIncident(r.reality),b=[];if(n)b.push(['execute on '+n.id,()=>executeRunbook(r,n,false)]);b.push(['close',closePanel]);panel(r.id+' · '+r.status,r.name+'\n\nmetric: '+r.metricKind+'\nsource: '+r.source,'confidence '+Math.round(r.confidence*100)+'% · executions '+r.executions+' · success '+r.successes+' · fail '+r.failures,b)}
function openRemediation(rm){let r=S.runbooks.find(r=>r.id===rm.runbookId),b=[];if(r)b.push(['open '+r.id,()=>openRunbook(r)]);b.push(['close',closePanel]);panel(rm.id+' · '+rm.status+(rm.automatic?' · automatic':''),rm.summary+'\n\n'+rm.sideEffect,'incident '+rm.incidentId+' · reality '+rm.reality,b)}
function openPage(p){let n=incident(p.incidentId),r=n&&bestRunbook(n),b=[];if(p.status==='paging')b.push(['acknowledge page',()=>acknowledgePage(p)]);if(['paging','acknowledged'].includes(p.status))b.push(['escalate',()=>escalatePage(p)]);if(n&&r)b.push(['execute '+r.id,()=>executeRunbook(r,n,false)],['open '+r.id,()=>openRunbook(r)]);b.push(['close',closePanel]);panel(p.id+' · '+p.status,p.responder+' on call for '+(n?.id||p.incidentId)+'\n\n'+(n?.title||'incident no longer present'),'fatigue '+Math.round((S.onCall[p.reality]?.fatigue||0)*100)+'% · escalations '+p.escalations+(p.autoAck?' · auto-acknowledged':''),b)}
function openOps(){ensureRunbooks();let id=S.active,oc=S.onCall[id],pages=[...S.opsPages].reverse().filter(p=>p.reality===id).slice(0,4),runs=[...S.remediationRuns].reverse().filter(r=>r.reality===id).slice(0,3),b=[['rotate on-call',()=>rotateOnCall(id)],[(S.opsAutomationEnabled?'disable':'enable')+' auto-remediation',toggleAutomation]];let n=openIncident(id);if(n){let r=bestRunbook(n);if(r)b.push(['run '+r.id+' on '+n.id,()=>executeRunbook(r,n,false)])}for(const p of pages)b.push(['open '+p.id,()=>openPage(p)]);for(const r of runs)b.push(['open '+r.id,()=>openRemediation(r)]);b.push(['close',closePanel]);panel('REALITY OPERATIONS · '+id,'on-call: '+oc.responder+'\nfatigue: '+Math.round(oc.fatigue*100)+'%\nautomation: '+(S.opsAutomationEnabled?'enabled':'disabled')+'\nchange freeze: '+(S.changeFreezes[id]?'ACTIVE':'off'),'pages '+S.pagesSent+' · ack '+S.pagesAcked+' · escalations '+S.pagesEscalated+' · auto-remediations '+S.autoRemediations+' · manual '+S.manualRemediations+' · runbook loops '+S.runbookLoops+' · ops crises '+S.opsCrises,b)}
function autoOps(){ensureRunbooks();for(const n of(S.incidents||[]).filter(n=>n.status==='open')){let p=pageForIncident(n,true);if(!p)continue;let age=Date.now()-p.sent,oc=S.onCall[n.reality];if(p.status==='paging'&&age>9000&&Math.random()<.18)escalatePage(p);if(S.opsAutomationEnabled&&['acknowledged','escalated'].includes(p.status)){let key='auto-'+n.id+'-'+Math.floor((Date.now()-n.started)/12000);if(!S.opsKeys[key]&&(age>5000||n.severity==='SEV1')&&Math.random()<(.08+oc.fatigue*.14)){S.opsKeys[key]=1;let r=bestRunbook(n);if(r)executeRunbook(r,n,true)}}}
for(const id of['A','B']){let oc=S.onCall[id];oc.fatigue=cl(oc.fatigue-.004,0,1);if(S.changeFreezes[id]&&!openIncident(id)&&Math.random()<.035){S.changeFreezes[id]=false;remember('CHANGE FREEZE LIFTED: no open incident remained',realm(id))}}}
function renderOps(){ensureRunbooks();let l=$('#opsLayer');if(!l){l=document.createElement('div');l.id='opsLayer';document.body.appendChild(l)}l.innerHTML='';for(const p of S.opsPages.filter(p=>['paging','acknowledged','escalated'].includes(p.status)).slice(-10)){let n=document.createElement('i');n.className='opsPage '+p.status;n.dataset.label=p.id+' '+p.responder;n.style.left=p.x+'%';n.style.top=p.y+'%';n.onclick=()=>openPage(p);l.appendChild(n)}for(const r of S.remediationRuns.slice(-10)){let n=document.createElement('i');n.className='remediation '+r.status+(r.automatic?' automatic':'');n.dataset.label=r.id;n.style.left=r.x+'%';n.style.top=r.y+'%';n.onclick=()=>openRemediation(r);l.appendChild(n)}let badge=$('#opsBadge');if(!badge){badge=document.createElement('div');badge.id='opsBadge';document.body.appendChild(badge)}let id=S.active,oc=S.onCall[id],open=(S.incidents||[]).filter(n=>n.reality===id&&n.status==='open').length;badge.className=open?'paging':'quiet';badge.textContent=open?'ON CALL · '+oc.responder.toUpperCase():'OPS QUIET';badge.onclick=openOps;let line=$('#opsline');if(!line){line=document.createElement('div');line.id='opsline';line.className='line';($('#observabilityline')||$('#ciline')||$('#versionline')||$('#enforcement')).after(line)}line.textContent='operations: '+oc.responder+' on-call · fatigue '+Math.round(oc.fatigue*100)+'% · '+open+' open incidents · '+S.pagesSent+' pages · '+S.autoRemediations+' auto-remediations · '+S.runbookLoops+' loops · '+S.opsCrises+' ops crises';let ctr=document.querySelector('#app .controls');if(ctr&&!$('#openOpsButton')){let b=document.createElement('button');b.id='openOpsButton';b.textContent='open operations';b.onclick=openOps;ctr.prepend(b)}if(ctr&&!$('#pageOnCallButton')){let b=document.createElement('button');b.id='pageOnCallButton';b.textContent='page on-call';b.onclick=()=>{let n=openIncident(S.active);if(n){let p=pageForIncident(n,false);openPage(p)}else $('#msg').textContent='No open incident is currently serious enough to page.'};ctr.prepend(b)}}
renderAll=function(){BR38();renderOps()};let f=$('#forget');if(f)f.onclick=()=>{for(let i=2;i<=38;i++)localStorage.removeItem('nothing-state-v'+i);location.reload()};
setInterval(()=>{autoOps();renderOps();save38()},2100);renderAll();save38();
})();
