(()=>{
const BS49=save,BR49=renderAll,O49=JSON.parse(localStorage.getItem('nothing-state-v49')||'null')||{},cl=(v,a,b)=>Math.max(a,Math.min(b,v)),pick=a=>a&&a.length?a[Math.floor(Math.random()*a.length)]:null;
S.oversightOffices49=O49.oversightOffices49||[];
S.procurementProtests49=O49.procurementProtests49||[];
S.complianceFindings49=O49.complianceFindings49||[];
S.correctiveOrders49=O49.correctiveOrders49||[];
S.conflictDisclosures49=O49.conflictDisclosures49||[];
S.oversightAudits49=O49.oversightAudits49||[];
S.oversightOfficeSerial49=O49.oversightOfficeSerial49||0;
S.protestSerial49=O49.protestSerial49||0;
S.findingSerial49=O49.findingSerial49||0;
S.correctiveOrderSerial49=O49.correctiveOrderSerial49||0;
S.conflictSerial49=O49.conflictSerial49||0;
S.oversightAuditSerial49=O49.oversightAuditSerial49||0;
S.protestsFiled49=O49.protestsFiled49||0;
S.protestsSustained49=O49.protestsSustained49||0;
S.protestsDenied49=O49.protestsDenied49||0;
S.contractStays49=O49.contractStays49||0;
S.contractRescissions49=O49.contractRescissions49||0;
S.oversightDebarments49=O49.oversightDebarments49||0;
S.selfAttestations49=O49.selfAttestations49||0;
S.conflictsFound49=O49.conflictsFound49||0;
S.auditorCaptures49=O49.auditorCaptures49||0;
S.oversightCrises49=O49.oversightCrises49||0;
S.lastOversightCrisis49=O49.lastOversightCrisis49||0;
S.oversightKeys49=O49.oversightKeys49||{};
S.lastOversightTick49=O49.lastOversightTick49||Date.now();
function save49(){BS49();localStorage.setItem('nothing-state-v49',JSON.stringify({oversightOffices49:S.oversightOffices49,procurementProtests49:S.procurementProtests49,complianceFindings49:S.complianceFindings49,correctiveOrders49:S.correctiveOrders49,conflictDisclosures49:S.conflictDisclosures49,oversightAudits49:S.oversightAudits49,oversightOfficeSerial49:S.oversightOfficeSerial49,protestSerial49:S.protestSerial49,findingSerial49:S.findingSerial49,correctiveOrderSerial49:S.correctiveOrderSerial49,conflictSerial49:S.conflictSerial49,oversightAuditSerial49:S.oversightAuditSerial49,protestsFiled49:S.protestsFiled49,protestsSustained49:S.protestsSustained49,protestsDenied49:S.protestsDenied49,contractStays49:S.contractStays49,contractRescissions49:S.contractRescissions49,oversightDebarments49:S.oversightDebarments49,selfAttestations49:S.selfAttestations49,conflictsFound49:S.conflictsFound49,auditorCaptures49:S.auditorCaptures49,oversightCrises49:S.oversightCrises49,lastOversightCrisis49:S.lastOversightCrisis49,oversightKeys49:S.oversightKeys49,lastOversightTick49:S.lastOversightTick49}))}save=save49;
const realm=id=>S.real[id],rfp=id=>(S.procurements48||[]).find(p=>p.id===id),contract=id=>(S.vendorContracts48||[]).find(c=>c.id===id),vendor=id=>(S.vendorProfiles48||[]).find(v=>v.id===id),bid=id=>(S.bids48||[]).find(b=>b.id===id),treasury=id=>(S.packageTreasuries47||[]).find(t=>t.namespaceId===id),maintainer=id=>(S.maintainers46||[]).find(m=>m.id===id);
function ensureOffices(){for(const id of ['A','B'])if(!S.oversightOffices49.some(o=>o.reality===id)){S.oversightOffices49.push({id:'IG'+(++S.oversightOfficeSerial49),reality:id,name:'Office of Package Procurement Integrity',status:'independent',independence:.78,credibility:.68,backlog:0,capturedBy:null,findings:0,protests:0,selfAttestations:0,created:Date.now(),x:12+Math.random()*76,y:12+Math.random()*68});remember('OVERSIGHT OFFICE: Reality '+id+' created an inspector for package procurement',realm(id))}}
const office=id=>S.oversightOffices49.find(o=>o.reality===id);
function activeRoot(id){let accepted=S.trustPolicies?.[id]?.acceptedRoots||[];return [...(S.trustRoots||[])].filter(r=>accepted.includes(r.id)&&r.status==='active').sort((a,b)=>(b.strength||0)-(a.strength||0))[0]||null}
function trustRecord(id,status,note){let r=activeRoot(id);S.trustAudits=S.trustAudits||[];S.trustAuditSerial=S.trustAuditSerial||0;S.trustAudits.push({id:'TA'+(++S.trustAuditSerial),reality:id,remediationId:null,credentialId:null,certificateId:null,rootId:r?.id||null,status,created:Date.now(),note,x:10+Math.random()*80,y:12+Math.random()*68})}
function openIncident(id,title,severity='SEV2'){S.incidents=S.incidents||[];let ex=S.incidents.find(i=>i.reality===id&&i.title===title&&i.status==='open');if(ex)return ex;S.incidentSerial=S.incidentSerial||0;let i={id:'INC'+(++S.incidentSerial),reality:id,title,severity,status:'open',alertIds:[],started:Date.now(),acknowledged:null,resolved:null,postmortem:null,owner:'procurement oversight',x:10+Math.random()*80,y:12+Math.random()*68};S.incidents.push(i);return i}
function latestContractFor(p){return p?.contractId?contract(p.contractId):[...(S.vendorContracts48||[])].reverse().find(c=>c.procurementId===p?.id)}
function losingBids(p){return (S.bids48||[]).filter(b=>b.procurementId===p.id&&b.status==='lost')}
function conflictSignals(p,c){let out=[];if(!p)return out;let winner=c?.vendor||bid(p.winnerBidId)?.vendor;if(p.capturedBy&&winner===p.capturedBy)out.push('winner wrote evaluation criteria');if(c?.soleSource)out.push('competition bypassed by sole-source award');if(c?.renewals>=2)out.push('contract repeatedly renewed without rebid');if((c?.lockIn||0)>.55)out.push('vendor lock-in materially limits corrective competition');if(c?.breaches>0)out.push('awardee has unresolved performance breaches');let t=treasury(p.namespaceId);if(t?.capturedBy&&winner&&winner.includes(t.capturedBy))out.push('winning vendor is affiliated with package sponsor');let v=vendor(c?.vendorId||bid(p.winnerBidId)?.vendorId);if(v?.status==='debarred')out.push('debarred vendor remains associated with award');return out}
function discloseConflicts(p){if(!p)return[];let c=latestContractFor(p),signals=conflictSignals(p,c),made=[];for(const text of signals){let key=p.id+'|'+text;if(S.conflictDisclosures49.some(d=>d.key===key))continue;let d={id:'COI'+(++S.conflictSerial49),key,procurementId:p.id,contractId:c?.id||null,reality:p.reality,subject:c?.vendor||bid(p.winnerBidId)?.vendor||'unknown',issue:text,status:'disclosed',created:Date.now(),x:10+Math.random()*80,y:12+Math.random()*68};S.conflictDisclosures49.push(d);S.conflictsFound49++;made.push(d);remember('CONFLICT DISCLOSURE '+d.id+': '+text+' in '+p.id,realm(p.reality));if(typeof place==='function')place('cold','conflict-of-interest form filed after award',realm(p.reality))}return made}
function makeFinding(p,issue,severity='material',source='audit'){let c=latestContractFor(p),existing=S.complianceFindings49.find(f=>f.procurementId===p.id&&f.issue===issue&&['open','stayed','self-certified'].includes(f.status));if(existing)return existing;let f={id:'FND'+(++S.findingSerial49),procurementId:p.id,contractId:c?.id||null,reality:p.reality,vendorId:c?.vendorId||bid(p.winnerBidId)?.vendorId||null,issue,severity,status:'open',source,created:Date.now(),resolved:null,resolution:null,selfAttested:false,x:10+Math.random()*80,y:12+Math.random()*68};S.complianceFindings49.push(f);let o=office(p.reality);if(o){o.findings++;o.backlog++;o.credibility=cl(o.credibility+.01,0,1)}remember('OVERSIGHT FINDING '+f.id+': '+issue+' in '+p.id,realm(p.reality));trustRecord(p.reality,'procurement-oversight-finding',f.id+' '+p.id+' '+issue);if(severity==='critical')openIncident(p.reality,'procurement oversight found '+issue,'SEV1');return f}
function auditProcurement(p,manual=true){if(!p)return null;ensureOffices();let c=latestContractFor(p),o=office(p.reality),signals=conflictSignals(p,c),findings=[];discloseConflicts(p);for(const s of signals){let sev=s.includes('criteria')||s.includes('debarred')?'critical':s.includes('sole-source')||s.includes('lock-in')?'material':'minor';findings.push(makeFinding(p,s,sev,'inspector audit'))}if(!signals.length&&c&&c.performance<.48)findings.push(makeFinding(p,'contract performance below awarded representation','material','performance audit'));let a={id:'IGA'+(++S.oversightAuditSerial49),reality:p.reality,procurementId:p.id,contractId:c?.id||null,officeId:o?.id||null,signals:[...signals],findingIds:findings.map(f=>f.id),status:findings.length?'exceptions':'clean',created:Date.now()};S.oversightAudits49.push(a);S.oversightAudits49=S.oversightAudits49.slice(-80);if(o)o.backlog=Math.max(0,o.backlog-1);remember('PROCUREMENT AUDIT '+a.id+': '+p.id+' '+a.status+' with '+findings.length+' findings',realm(p.reality));if(!findings.length&&o){o.credibility=cl(o.credibility+.005,0,1);trustRecord(p.reality,'procurement-oversight-clean',a.id+' '+p.id)}if(manual){$('#msg').textContent=a.id+' completed: '+findings.length+' findings on '+p.id+'.';renderAll();save49();openAudit(a)}return a}
function fileProtest(p,protester=null,manual=true){if(!p||!p.winnerBidId)return null;ensureOffices();let losers=losingBids(p),lb=protester?losers.find(b=>b.vendor===protester||b.vendorId===protester):pick(losers),c=latestContractFor(p);if(!lb){if(manual)$('#msg').textContent='No losing bidder is available to protest this award.';return null}let existing=S.procurementProtests49.find(x=>x.procurementId===p.id&&x.protesterBidId===lb.id&&x.status==='open');if(existing)return existing;let grounds=conflictSignals(p,c),g=pick(grounds.length?grounds:['evaluation record does not explain why the winner was superior','award price and technical score were weighted inconsistently']),x={id:'PRT'+(++S.protestSerial49),procurementId:p.id,contractId:c?.id||null,reality:p.reality,protesterBidId:lb.id,protester:lb.vendor,ground:g,status:'open',filed:Date.now(),decision:null,decided:null,x:10+Math.random()*80,y:12+Math.random()*68};S.procurementProtests49.push(x);S.protestsFiled49++;let o=office(p.reality);if(o){o.protests++;o.backlog++}remember('BID PROTEST '+x.id+': '+lb.vendor+' challenged '+p.id+' over '+g,realm(p.reality));if(typeof place==='function')place('cold','losing bidder waiting outside procurement office',realm(p.reality));if(manual){$('#msg').textContent=x.id+' filed by '+lb.vendor+'.';renderAll();save49();openProtest(x)}return x}
function decideProtest(x,forced=null,manual=true){if(!x||x.status!=='open')return;let p=rfp(x.procurementId),c=contract(x.contractId),o=office(x.reality),signals=conflictSignals(p,c),risk=(signals.length*.18)+(p?.capturedBy ? .12 : 0)+(c?.soleSource ? .18 : 0)+(c?.breaches||0)*.08+(1-(o?.independence||.7))*.18;let sustain=forced==='sustain'||(forced!=='deny'&&Math.random()<cl(.28+risk,.15,.94));x.status=sustain?'sustained':'denied';x.decision=sustain?'award process materially defective':'award record sufficient';x.decided=Date.now();if(o)o.backlog=Math.max(0,o.backlog-1);if(sustain){S.protestsSustained49++;if(c&&['active','stayed'].includes(c.status)){c.preOversightStatus=c.status;c.status='stayed';S.contractStays49++}if(p)p.status='protested';let f=makeFinding(p,'sustained bid protest: '+x.ground,'critical','bid protest');if(f)f.status='stayed';remember('PROTEST SUSTAINED '+x.id+': contract '+(c?.id||'none')+' stayed, deployed code unchanged',realm(x.reality));if(typeof place==='function'){place('cold','contract stayed binary still running',realm(x.reality));place('dream','successful protest against code already deployed',realm(x.reality))}openIncident(x.reality,'sustained procurement protest left vendor code in production','SEV2')}else{S.protestsDenied49++;remember('PROTEST DENIED '+x.id+': award survives challenge',realm(x.reality));if(o)o.credibility=cl(o.credibility+(signals.length?-.015:.01),0,1)}if(manual){$('#msg').textContent=x.id+' '+x.status.toUpperCase()+'.';renderAll();save49();openProtest(x)}}
function orderFor(f,type){let existing=S.correctiveOrders49.find(o=>o.findingId===f.id&&o.type===type&&o.status==='open');if(existing)return existing;let o={id:'CAO'+(++S.correctiveOrderSerial49),findingId:f.id,procurementId:f.procurementId,contractId:f.contractId,reality:f.reality,type,status:'open',created:Date.now(),completed:null,x:10+Math.random()*80,y:12+Math.random()*68};S.correctiveOrders49.push(o);remember('CORRECTIVE ORDER '+o.id+': '+type+' for '+f.id,realm(f.reality));trustRecord(f.reality,'procurement-corrective-order',o.id+' '+type);return o}
function stayContract(f){let c=contract(f.contractId);if(c&&c.status!=='stayed'){c.preOversightStatus=c.status;c.status='stayed';S.contractStays49++}f.status='stayed';orderFor(f,'stay contract pending correction');remember('CONTRACT STAY: '+(c?.id||'unknown')+' cannot receive new authority, but installed artifacts remain',realm(f.reality));if(typeof place==='function')place('cold','legal stay above running vendor binary',realm(f.reality));renderAll();save49();openFinding(f)}
function rescindAward(f){let p=rfp(f.procurementId),c=contract(f.contractId),v=vendor(f.vendorId);if(c){c.status='rescinded';c.rescinded=Date.now();S.contractRescissions49++}if(p){p.status='rescinded';p.rescinded=Date.now()}let m=c?maintainer(c.maintainerId):null;if(m&&m.status==='active')m.status='disputed';f.status='open';orderFor(f,'rescind award and rebid');remember('AWARD RESCINDED: '+(c?.id||'unknown')+' lost legal authority; delivered package code remains historical and may remain deployed',realm(f.reality));if(v)v.lockIn=cl((v.lockIn||0)+.05,0,1);if(typeof place==='function'){place('cold','rescinded contract still inside production',realm(f.reality));place('dream','vendor no longer eligible to deliver what it already delivered',realm(f.reality))}renderAll();save49();openFinding(f)}
function debarVendor(f){let v=vendor(f.vendorId),c=contract(f.contractId);if(v){v.status='debarred';v.debarredAt=Date.now();S.oversightDebarments49++}if(c&&c.status!=='rescinded')c.status='rescinded';orderFor(f,'debar vendor');remember('OVERSIGHT DEBARMENT: '+(v?.name||'vendor')+' barred from future procurement while existing binaries remain operative',realm(f.reality));if(typeof place==='function')place('cold','debarred vendor still inside production SBOM',realm(f.reality));trustRecord(f.reality,'procurement-vendor-debarred',f.id+' '+(v?.name||''));renderAll();save49();openFinding(f)}
function vendorSelfAttest(f){if(!f||!['open','stayed'].includes(f.status))return;let c=contract(f.contractId),v=vendor(f.vendorId),o=office(f.reality);f.status='self-certified';f.selfAttested=true;f.resolved=Date.now();f.resolution='vendor self-attestation accepted';S.selfAttestations49++;if(c&&c.status==='stayed')c.status=c.preOversightStatus||'active';if(o){o.selfAttestations++;o.independence=cl(o.independence-.07,0,1);o.credibility=cl(o.credibility-.035,0,1);if(o.selfAttestations>=3&&!o.capturedBy){o.capturedBy=v?.name||c?.vendor||'regulated vendor';o.status='captured';S.auditorCaptures49++;oversightCrisis(f.reality,'self-certification-capture')}}remember('SELF-CERTIFIED COMPLIANCE '+f.id+': '+(v?.name||c?.vendor||'vendor')+' supplied the evidence used to close its own finding',realm(f.reality));if(typeof place==='function'){place('cold','vendor auditing its own corrective action',realm(f.reality));place('dream','compliance achieved by certification',realm(f.reality))}renderAll();save49();openFinding(f)}
function independentClose(f){if(!f||!['open','stayed','self-certified'].includes(f.status))return;let c=contract(f.contractId),o=office(f.reality);f.status='resolved';f.resolved=Date.now();f.resolution='independent verification';if(c&&c.status==='stayed')c.status=c.preOversightStatus||'active';if(o){o.credibility=cl(o.credibility+.025,0,1);o.independence=cl(o.independence+.012,0,1);o.backlog=Math.max(0,o.backlog-1)}for(const x of S.correctiveOrders49.filter(x=>x.findingId===f.id&&x.status==='open'))x.status='completed',x.completed=Date.now();remember('FINDING RESOLVED '+f.id+': independent verification accepted correction',realm(f.reality));trustRecord(f.reality,'procurement-finding-resolved',f.id+' independently verified');renderAll();save49();openFinding(f)}
function captureInspector(id=S.active){ensureOffices();let o=office(id),cs=(S.vendorContracts48||[]).filter(c=>c.reality===id&&['active','stayed'].includes(c.status));let c=pick(cs),v=vendor(c?.vendorId);if(!o||!c)return;o.capturedBy=v?.name||c.vendor;o.status='captured';o.independence=cl(o.independence-.28,.05,1);o.credibility=cl(o.credibility-.12,.05,1);S.auditorCaptures49++;remember('OVERSIGHT CAPTURE: '+o.name+' became dependent on '+o.capturedBy+' for technical expertise',realm(id));if(typeof place==='function'){place('cold','inspector using vendor compliance spreadsheet',realm(id));place('dream','watchdog dependent on the system it watches',realm(id))}oversightCrisis(id,'captured-inspector');renderAll();save49();openOffice(o)}
function recuseInspector(o){if(!o||!o.capturedBy)return;o.capturedBy=null;o.status='independent';o.independence=cl(o.independence+.18,0,1);remember('OVERSIGHT RECUSAL: '+o.name+' removed its captured review team, prior decisions remain',realm(o.reality));if(typeof place==='function')place('warm','new inspector reading old captured findings',realm(o.reality));renderAll();save49();openOffice(o)}
function oversightCrisis(id,reason){if(Date.now()-S.lastOversightCrisis49<7000)return false;let key=id+'|'+reason+'|'+Math.floor(Date.now()/20000);if(S.oversightKeys49[key])return false;S.oversightKeys49[key]=1;S.oversightCrises49++;S.lastOversightCrisis49=Date.now();for(const rid of ['A','B']){realm(rid).disputes=(realm(rid).disputes||0)+1;remember('OVERSIGHT CRISIS: compliance review became authority over which vendor is allowed to define reality',realm(rid))}realm(id).timelineDrift=(realm(id).timelineDrift||0)+1;if(typeof place==='function'){place('cold','watchdog became another source of permission',realm(id));place('dream','compliance finding with production consequences',realm(id))}S.bailiffMood='asking whether the auditor or the contract decides what is compliant';return true}
function openOffice(o){let ps=[...(S.procurements48||[])].filter(p=>p.reality===o.reality&&p.winnerBidId).reverse().slice(0,5),open=S.complianceFindings49.filter(f=>f.reality===o.reality&&['open','stayed','self-certified'].includes(f.status)),b=[['audit latest procurement',()=>{let p=ps[0];if(p)auditProcurement(p);else $('#msg').textContent='No awarded procurement is available to audit.'}],['file protest on latest award',()=>{let p=ps[0];if(p)fileProtest(p);else $('#msg').textContent='No awarded procurement is available to protest.'}],['capture inspector',()=>captureInspector(o.reality)]];if(o.capturedBy)b.push(['recuse captured inspector',()=>recuseInspector(o)]);for(const f of open.slice(-4))b.push(['open '+f.id,()=>openFinding(f)]);for(const p of ps.slice(0,3))b.push(['audit '+p.id,()=>auditProcurement(p)]);b.push(['close',closePanel]);panel(o.name+' · '+o.status.toUpperCase(),o.id+' · Reality '+o.reality,'independence '+Math.round(o.independence*100)+'% · credibility '+Math.round(o.credibility*100)+'% · backlog '+o.backlog+' · findings '+o.findings+' · protests '+o.protests+(o.capturedBy?'\ncaptured by '+o.capturedBy:''),b)}
function openAudit(a){let p=rfp(a.procurementId),b=[];for(const id of a.findingIds){let f=S.complianceFindings49.find(f=>f.id===id);if(f)b.push(['open '+f.id,()=>openFinding(f)])}if(p)b.push(['file bid protest',()=>fileProtest(p)]);b.push(['close',closePanel]);panel(a.id+' · '+a.status.toUpperCase(),a.procurementId+' · '+(a.contractId||'no contract'),(a.signals.join('\n')||'no material exception detected'),b)}
function openProtest(x){let b=[];if(x.status==='open')b.push(['sustain protest',()=>decideProtest(x,'sustain')],['deny protest',()=>decideProtest(x,'deny')],['let inspector decide',()=>decideProtest(x)]);let p=rfp(x.procurementId);if(p)b.push(['audit award',()=>auditProcurement(p)]);b.push(['close',closePanel]);panel(x.id+' · '+x.status.toUpperCase(),x.protester+' vs '+x.procurementId,x.ground+(x.decision?'\n'+x.decision:''),b)}
function openFinding(f){let c=contract(f.contractId),v=vendor(f.vendorId),b=[];if(['open','stayed'].includes(f.status))b.push(['stay contract',()=>stayContract(f)],['rescind award',()=>rescindAward(f)],['debar vendor',()=>debarVendor(f)],['accept vendor self-attestation',()=>vendorSelfAttest(f)],['independently verify correction',()=>independentClose(f)]);else if(f.status==='self-certified')b.push(['reopen for independent review',()=>{f.status='open';f.resolved=null;f.resolution=null;renderAll();save49();openFinding(f)}],['independently verify anyway',()=>independentClose(f)]);b.push(['close',closePanel]);panel(f.id+' · '+f.severity.toUpperCase(),(v?.name||c?.vendor||'vendor')+' · '+f.status,f.issue+(f.resolution?'\nresolution: '+f.resolution:'')+(c?'\ncontract '+c.id+' '+c.status:''),b)}
function openOversight(id=S.active){ensureOffices();let o=office(id),ps=[...(S.procurements48||[])].filter(p=>p.reality===id&&p.winnerBidId).reverse(),open=S.complianceFindings49.filter(f=>f.reality===id&&['open','stayed','self-certified'].includes(f.status)),protests=S.procurementProtests49.filter(p=>p.reality===id&&p.status==='open'),b=[['open inspector general',()=>openOffice(o)]];if(ps[0])b.push(['audit '+ps[0].id,()=>auditProcurement(ps[0])],['file protest',()=>fileProtest(ps[0])]);for(const p of protests.slice(-3))b.push(['open '+p.id,()=>openProtest(p)]);for(const f of open.slice(-3))b.push(['open '+f.id,()=>openFinding(f)]);b.push(['close',closePanel]);panel('PROCUREMENT OVERSIGHT · Reality '+id,o.name+' · '+o.status,open.length+' unresolved findings · '+protests.length+' open protests · '+S.protestsSustained49+' sustained · '+S.contractStays49+' stays · '+S.oversightDebarments49+' oversight debarments · '+S.selfAttestations49+' self-attestations · '+S.oversightCrises49+' crises',b)}
function auditLatest(id=S.active,manual=true){ensureOffices();let p=[...(S.procurements48||[])].filter(p=>p.reality===id&&p.winnerBidId).reverse()[0];if(!p){if(manual)$('#msg').textContent='No awarded procurement exists yet.';return null}return auditProcurement(p,manual)}
function autonomous(){ensureOffices();let now=Date.now();if(now-S.lastOversightTick49<1800)return;S.lastOversightTick49=now;for(const o of S.oversightOffices49){o.backlog+=(S.vendorContracts48||[]).filter(c=>c.reality===o.reality&&c.status==='active'&&((c.lockIn||0)>.55||c.soleSource||c.breaches>0)).length*.002;if(o.capturedBy)o.independence=cl(o.independence-.0007,.05,1);else o.independence=cl(o.independence+.00025,0,1)}if(Math.random()<.004){let id=pick(['A','B']),p=[...(S.procurements48||[])].filter(p=>p.reality===id&&p.winnerBidId).reverse()[0];if(p)auditProcurement(p,false)}if(Math.random()<.0025){let p=pick((S.procurements48||[]).filter(p=>p.winnerBidId&&losingBids(p).length));if(p)fileProtest(p,null,false)}for(const x of S.procurementProtests49.filter(x=>x.status==='open'))if(Date.now()-x.filed>12000&&Math.random()<.01){decideProtest(x,null,false);break}}
function renderOversight(){ensureOffices();let layer=$('#oversightLayer');if(!layer){layer=document.createElement('div');layer.id='oversightLayer';document.body.appendChild(layer)}layer.innerHTML='';for(const o of S.oversightOffices49){let e=document.createElement('i');e.className='oversightOffice '+o.status;e.dataset.label=o.id;e.style.left=o.x+'%';e.style.top=o.y+'%';e.onclick=()=>openOffice(o);layer.appendChild(e)}for(const p of S.procurementProtests49.filter(p=>p.status==='open').slice(-10)){let e=document.createElement('i');e.className='protestNode';e.dataset.label=p.id;e.style.left=p.x+'%';e.style.top=p.y+'%';e.onclick=()=>openProtest(p);layer.appendChild(e)}for(const f of S.complianceFindings49.filter(f=>['open','stayed','self-certified'].includes(f.status)).slice(-12)){let e=document.createElement('i');e.className='findingNode '+f.severity+' '+f.status;e.dataset.label=f.id;e.style.left=f.x+'%';e.style.top=f.y+'%';e.onclick=()=>openFinding(f);layer.appendChild(e)}let line=$('#oversightline');if(!line){line=document.createElement('div');line.id='oversightline';line.className='line';($('#procurementline')||$('#economyline')||$('#governanceline')||$('#enforcement')).after(line)}let id=S.active,o=office(id),open=S.complianceFindings49.filter(f=>f.reality===id&&['open','stayed','self-certified'].includes(f.status)).length,protests=S.procurementProtests49.filter(p=>p.reality===id&&p.status==='open').length;line.textContent='oversight: '+Math.round((o?.independence||0)*100)+'% independent · '+open+' findings · '+protests+' protests · '+S.contractStays49+' stays · '+S.selfAttestations49+' self-certified · '+S.oversightCrises49+' crises';let ctr=document.querySelector('#app .controls');if(ctr&&!$('#openOversightButton')){let b=document.createElement('button');b.id='openOversightButton';b.textContent='open oversight';b.onclick=()=>openOversight(S.active);ctr.prepend(b)}if(ctr&&!$('#auditProcurementButton')){let b=document.createElement('button');b.id='auditProcurementButton';b.textContent='audit procurement';b.onclick=()=>auditLatest(S.active,true);ctr.prepend(b)}}
renderAll=function(){BR49();renderOversight()};let f=$('#forget');if(f)f.onclick=()=>{for(let i=2;i<=49;i++)localStorage.removeItem('nothing-state-v'+i);location.reload()};
setInterval(()=>{autonomous();renderOversight();save49()},2050);ensureOffices();renderAll();save49();
})();
