(()=>{
const B86=save,R86=renderAll,O=JSON.parse(localStorage.getItem('nothing-state-v86')||'null')||{},RECOVER86=!Array.isArray(O.postDefaultCashSweeps86),K=['postDefaultCashSweepOffice86','postDefaultCashSweeps86','postDefaultCashSweepSerial86','postDefaultCashSweepEvents86','postDefaultCashSweepAmount86','postDefaultCashSweepPrincipal86','postDefaultCashSweepInterest86','postDefaultCashSweepCallsCured86','postDefaultCashSweepCasesCured86','postDefaultCashSweepBlocked86','postDefaultCashSweepCrises86','postDefaultCashSweepKeys86','lastPostDefaultCashSweepTick86'];
for(const k of K)S[k]=O[k]??(/Serial|Events|Amount|Principal|Interest|Cured|Blocked|Crises|Tick/.test(k)?0:/Keys/.test(k)?{}:/Office/.test(k)?null:[]);
function save86(){B86();let o={};for(const k of K)o[k]=S[k];localStorage.setItem('nothing-state-v86',JSON.stringify(o))}save=save86;
const q=s=>$(s),realm=id=>S.real[id],facility=id=>(S.liquidityFacilities55||[]).find(x=>x.id===id),authority=id=>(S.monetaryAuthorities55||[]).find(x=>x.id===id),cl=(v,a,b)=>Math.max(a,Math.min(b,v));
function trust(id,status,note){S.trustAudits=S.trustAudits||[];S.trustAuditSerial=S.trustAuditSerial||0;S.trustAudits.push({id:'TA'+(++S.trustAuditSerial),reality:id,status,created:Date.now(),note,x:10+Math.random()*80,y:12+Math.random()*68})}
function incident(id,title,sev='SEV1'){S.incidents=S.incidents||[];S.incidentSerial=S.incidentSerial||0;let ex=S.incidents.find(x=>x.reality===id&&x.title===title&&x.status==='open');if(ex)return ex;let i={id:'INC'+(++S.incidentSerial),reality:id,title,severity:sev,status:'open',started:Date.now(),owner:'post-default cash sweep office',x:10+Math.random()*80,y:12+Math.random()*68};S.incidents.push(i);return i}
function crisis(id,why,sev='SEV1'){let n=Date.now(),k=id+'|'+why;if(S.postDefaultCashSweepKeys86[k]&&n-S.postDefaultCashSweepKeys86[k]<14000)return;S.postDefaultCashSweepKeys86[k]=n;S.postDefaultCashSweepCrises86++;remember('POST-DEFAULT CASH-SWEEP CRISIS: '+why+' turned later borrower liquidity into repayment of surviving cross-default public debt',realm(id));if(typeof place==='function'){place('cold','borrower survived liquidation but its future cash belonged to the central bank first',realm(id));place('dream','evergreened emergency loans becoming a floating lien on later liquidity',realm(id))}incident(id,'post-default cash sweep crisis: '+why,sev)}
function ensure(){if(!S.fundingCrossDefaultOffice85)return null;if(!S.postDefaultCashSweepOffice86){S.postDefaultCashSweepOffice86={id:'CSO1',name:'Interreality Post-Default Cash Sweep Office',status:'sweeping',created:Date.now(),x:50,y:84};remember('POST-DEFAULT CASH SWEEP CSO1: cross-default deficiency acquired a floating claim on later borrower cash',realm('A'));remember('POST-DEFAULT CASH SWEEP CSO1: cross-default deficiency acquired a floating claim on later borrower cash',realm('B'));trust('A','post-default-cash-sweep-created','CSO1');trust('B','post-default-cash-sweep-created','CSO1')}return S.postDefaultCashSweepOffice86}
function borrower(f){if(!f)return null;if(f.borrowerType==='dealer'){let o=(S.derivativeDealers53||[]).find(x=>x.id===f.borrowerId);return o?{obj:o,cashField:'capital',name:o.name||f.borrowerId}:null}if(f.borrowerType==='ccp'){let o=(S.clearinghouses54||[]).find(x=>x.id===f.borrowerId);return o?{obj:o,cashField:'liquidity',name:o.name||f.borrowerId}:null}if(f.borrowerType==='insurer'){let o=(S.insurers51||[]).find(x=>x.id===f.borrowerId);return o?{obj:o,cashField:'capital',name:o.name||f.borrowerId}:null}if(f.borrowerType==='treasury'){let o=(S.packageTreasuries47||[]).find(x=>x.namespaceId===f.borrowerId),n=(S.namespaces46||[]).find(x=>x.id===f.borrowerId);return o?{obj:o,cashField:'balance',name:(n?.name||f.borrowerId)+' package treasury'}:null}return null}
function cash(b){return Math.max(0,b?.obj?.[b.cashField]||0)}
function addCash(b,x){if(b)b.obj[b.cashField]=Math.max(0,(b.obj[b.cashField]||0)+x)}
function liveCase(c){return c&&c.status==='liquidated-deficiency'&&(c.deficiency85||0)>.01}
function debtFacilities(c){return(c.facilityIds85||[]).map(facility).filter(f=>f&&['active','monetized'].includes(f.status)&&((f.principal||0)>.01||(f.interestAccrued||0)>.01))}
function principalOutstanding(fs){return fs.reduce((n,f)=>n+Math.max(0,f.principal||0),0)}
function dueOutstanding(fs){return fs.reduce((n,f)=>n+Math.max(0,f.principal||0)+Math.max(0,f.interestAccrued||0),0)}
function operatingFloor(c,fs){if((c.cashSweepOperatingFloor86||0)>.001)return c.cashSweepOperatingFloor86;let base=Math.max(0,c.deficiency85||principalOutstanding(fs));c.cashSweepOperatingFloor86=cl(base*.10,.10,.50);return c.cashSweepOperatingFloor86}
function callDue(c){return Math.max(0,(c.amount||0)-(c.paid||0)-(c.setoffPaid81||0)-(c.paidCrossDefault85||0)-(c.paidCashSweep86||0))}
function cureCalls(f,amount,r){let rem=amount;for(const c of(S.monetaryCollateralCalls55||[]).filter(c=>c.facilityId===f.id&&['open','failed','forborne'].includes(c.status)).sort((a,b)=>(a.issued||0)-(b.issued||0))){if(rem<=.0001)break;let due=callDue(c),x=Math.min(rem,due);if(x<=.0001)continue;c.paidCashSweep86=(c.paidCashSweep86||0)+x;rem-=x;if(x+1e-9>=due){c.preCashSweepStatus86=c.status;c.status='met';c.met=Date.now();c.metByCashSweep86=true;S.monetaryCollateralCallsMet55=(S.monetaryCollateralCallsMet55||0)+1;S.postDefaultCashSweepCallsCured86++;r.callsCured86=(r.callsCured86||0)+1}}}
function retirePrincipal(f,amount,r){let a=authority(f.authorityId),acct=(S.reserveAccounts55||[]).find(x=>x.borrowerType===f.borrowerType&&x.borrowerId===f.borrowerId),x=Math.min(Math.max(0,f.principal||0),Math.max(0,amount));if(!a||x<=.0001)return 0;let wasActive=f.status==='active';f.principal=Math.max(0,(f.principal||0)-x);a.monetaryBase=Math.max(0,(a.monetaryBase||0)-x);if(wasActive)a.outstandingCredit=Math.max(0,(a.outstandingCredit||0)-x);if(acct)acct.balance=Math.max(0,(acct.balance||0)-x);S.reservesExtinguished55=(S.reservesExtinguished55||0)+x;cureCalls(f,x,r);return x}
function payInterest(f,amount){let a=authority(f.authorityId),x=Math.min(Math.max(0,f.interestAccrued||0),Math.max(0,amount));if(!a||x<=.0001)return 0;f.interestAccrued=Math.max(0,(f.interestAccrued||0)-x);a.capital=(a.capital||0)+x;return x}
function closeIfPaid(f){if((f.principal||0)<=.01&&(f.interestAccrued||0)<=.01){f.principal=0;f.interestAccrued=0;f.status='repaid';f.repaid=Date.now();f.repaidByCashSweep86=true;f.crossDefaultDeficiency85=0;f.cashSweepRemaining86=0;return true}f.cashSweepRemaining86=Math.max(0,(f.principal||0)+(f.interestAccrued||0));return false}
function marker(r,c,fs){let snap=JSON.parse(JSON.stringify(r));c.cashSweepMarkers86=c.cashSweepMarkers86||[];c.cashSweepMarkers86.push(snap);c.cashSweepLatest86=r.id;for(const f of fs){f.cashSweepMarkers86=f.cashSweepMarkers86||[];f.cashSweepMarkers86.push(snap);f.cashSweepLatest86=r.id}}
function sweep(c,manual=false){if(!liveCase(c))return null;let fs=debtFacilities(c);if(!fs.length){c.cashSweepCured86=true;c.cashSweepOutstanding86=0;return null}let b=borrower(fs[0]),floor=operatingFloor(c,fs),before=cash(b),due=dueOutstanding(fs),available=Math.max(0,before-floor),amount=Math.min(available,due);if(!b||amount<=.01)return null;let valid=fs.filter(f=>authority(f.authorityId));if(!valid.length){S.postDefaultCashSweepBlocked86++;crisis(c.reality,'cash was available after cross-default but the public authority record was missing','SEV2');return null}
let r={id:'CSW'+(++S.postDefaultCashSweepSerial86),crossDefaultId85:c.id,positionId79:c.positionId79,reality:c.reality,borrower:c.borrower,status:'swept',cashBefore86:before,operatingFloor86:floor,availableCash86:available,amount:0,principalPaid86:0,interestPaid86:0,callsCured86:0,outstandingBefore86:due,outstandingAfter86:due,caseCured86:false,allocations86:[],created:Date.now(),x:10+Math.random()*80,y:12+Math.random()*68};
let principal=principalOutstanding(valid),principalBudget=Math.min(amount,principal),remaining=principalBudget,remainingPrincipal=principal;
for(let i=0;i<valid.length;i++){let f=valid[i],p0=Math.max(0,f.principal||0),share=i===valid.length-1?remaining:(remainingPrincipal>0?principalBudget*(p0/principal):0),x=retirePrincipal(f,Math.min(p0,share),r);remaining=Math.max(0,remaining-x);remainingPrincipal=Math.max(0,remainingPrincipal-p0);r.principalPaid86+=x;r.allocations86.push({facilityId55:f.id,statusBefore86:f.status,principalBefore86:p0,principalPaid86:x,interestPaid86:0,remaining86:0})}
let used=r.principalPaid86,budget=Math.max(0,amount-used);for(const a of r.allocations86){if(budget<=.0001)break;let f=facility(a.facilityId55),x=payInterest(f,budget);a.interestPaid86=x;r.interestPaid86+=x;budget-=x;used+=x}
if(used<=.0001)return null;addCash(b,-used);for(const a of r.allocations86){let f=facility(a.facilityId55);closeIfPaid(f);a.remaining86=Math.max(0,(f?.principal||0)+(f?.interestAccrued||0));a.statusAfter86=f?.status||'missing'}
r.amount=used;r.cashAfter86=cash(b);r.outstandingAfter86=dueOutstanding(debtFacilities(c));r.caseCured86=r.outstandingAfter86<=.01;if(r.caseCured86){r.status='cured-after-default';c.cashSweepCured86=true;c.cashSweepCuredAt86=Date.now();S.postDefaultCashSweepCasesCured86++}else c.cashSweepCured86=false;c.cashSweepOutstanding86=r.outstandingAfter86;c.cashSweepTotal86=(c.cashSweepTotal86||0)+used;c.cashSweepPrincipal86=(c.cashSweepPrincipal86||0)+r.principalPaid86;c.cashSweepInterest86=(c.cashSweepInterest86||0)+r.interestPaid86;
S.postDefaultCashSweeps86.push(r);S.postDefaultCashSweepEvents86++;S.postDefaultCashSweepAmount86+=used;S.postDefaultCashSweepPrincipal86+=r.principalPaid86;S.postDefaultCashSweepInterest86+=r.interestPaid86;marker(r,c,valid);remember('POST-DEFAULT CASH SWEEP '+r.id+': '+c.borrower+' later cash '+used.toFixed(2)+' retired '+r.principalPaid86.toFixed(2)+' public principal after '+c.id,realm(c.reality));trust(c.reality,'post-default-cash-sweep',r.id+' '+used.toFixed(2));if(r.caseCured86){remember('CROSS-DEFAULT DEFICIENCY CURED '+c.id+': later borrower cash finally extinguished the surviving public debt without reopening the liquidated carry',realm(c.reality));if(typeof place==='function')place('warm','dead carry stayed dead while later cash repaid the debt it left behind',realm(c.reality))}else crisis(c.reality,'later borrower cash was trapped for a still-unpaid cross-default deficiency','SEV2');if(manual){q('#msg').textContent=r.id+' swept '+used.toFixed(2)+' · '+r.outstandingAfter86.toFixed(2)+' public debt remains.';renderAll();save86();openSweep(r)}return r}
function reconstruct(){if(!RECOVER86)return false;let changed=false,seen=new Set(),records=[];for(const c of(S.fundingCrossDefaults85||[]))for(const m of(c.cashSweepMarkers86||[]))records.push(m);for(const f of(S.liquidityFacilities55||[]))for(const m of(f.cashSweepMarkers86||[]))records.push(m);records.sort((a,b)=>(a.created||0)-(b.created||0));for(const m of records){if(seen.has(m.id)||(S.postDefaultCashSweeps86||[]).some(x=>x.id===m.id))continue;seen.add(m.id);let r=JSON.parse(JSON.stringify(m));r.recovered=true;S.postDefaultCashSweeps86.push(r);S.postDefaultCashSweepEvents86++;S.postDefaultCashSweepAmount86+=r.amount||0;S.postDefaultCashSweepPrincipal86+=r.principalPaid86||0;S.postDefaultCashSweepInterest86+=r.interestPaid86||0;S.postDefaultCashSweepCallsCured86+=r.callsCured86||0;if(r.caseCured86)S.postDefaultCashSweepCasesCured86++;let n=Number(String(r.id).replace(/\D/g,''))||0;if(n>S.postDefaultCashSweepSerial86)S.postDefaultCashSweepSerial86=n;changed=true}return changed}
function reconcile(){if(!ensure())return false;let changed=reconstruct(),cases=(S.fundingCrossDefaults85||[]).filter(liveCase).sort((a,b)=>(a.resolved||a.created||0)-(b.resolved||b.created||0));for(const c of cases){let r=sweep(c,false);if(r)changed=true}return changed}
function openSweep(r){let acts=[];for(const a of r.allocations86||[]){let f=facility(a.facilityId55);if(f)acts.push([a.facilityId55+' · '+a.statusAfter86+' · '+a.remaining86.toFixed(2),()=>panel(a.facilityId55+' · CASH-SWEEP WORKOUT',f.status.toUpperCase(),f.borrower+' · principal paid '+a.principalPaid86.toFixed(2)+' · interest paid '+a.interestPaid86.toFixed(3)+' · remaining '+a.remaining86.toFixed(2),[['close',closePanel]])])}acts.push(['close',closePanel]);panel(r.id+' · POST-DEFAULT CASH SWEEP',r.status.toUpperCase(),r.borrower+' · cash '+r.cashBefore86.toFixed(2)+'→'+r.cashAfter86.toFixed(2)+' · protected floor '+r.operatingFloor86.toFixed(2)+' · swept '+r.amount.toFixed(2)+' · principal '+r.principalPaid86.toFixed(2)+' · interest '+r.interestPaid86.toFixed(3)+' · debt '+r.outstandingBefore86.toFixed(2)+'→'+r.outstandingAfter86.toFixed(2),acts)}
function openOffice(){if(!ensure())return;let acts=[];for(const c of(S.fundingCrossDefaults85||[]).filter(liveCase)){let fs=debtFacilities(c),b=borrower(fs[0]),floor=fs.length?operatingFloor(c,fs):0,avail=Math.max(0,cash(b)-floor);if(avail>.01)acts.push(['sweep '+c.id+' · '+avail.toFixed(2)+' excess cash',()=>sweep(c,true)])}for(const r of S.postDefaultCashSweeps86.slice(-8))acts.push(['open '+r.id+' · '+r.status,()=>openSweep(r)]);acts.push(['close',closePanel]);panel(S.postDefaultCashSweepOffice86.name,'SWEEPING · CSO1',S.postDefaultCashSweepEvents86+' sweeps · '+S.postDefaultCashSweepAmount86.toFixed(2)+' cash trapped · '+S.postDefaultCashSweepPrincipal86.toFixed(2)+' principal retired · '+S.postDefaultCashSweepCasesCured86+' deficiencies cured',acts)}
function render86(){if(!ensure())return;let layer=q('#postDefaultCashSweepLayer86');if(!layer){layer=document.createElement('div');layer.id='postDefaultCashSweepLayer86';document.body.appendChild(layer)}layer.innerHTML='';let o=document.createElement('i');o.className='postDefaultCashSweepOffice86';o.dataset.label='SW';o.style.left='50%';o.style.top='84%';o.onclick=openOffice;layer.appendChild(o);for(const r of S.postDefaultCashSweeps86.slice(-8)){let e=document.createElement('i');e.className='postDefaultCashSweep86 '+r.status;e.dataset.label='$↓';e.style.left=r.x+'%';e.style.top=r.y+'%';e.onclick=()=>openSweep(r);layer.appendChild(e)}let line=q('#postdefaultcashsweepline86');if(!line){line=document.createElement('div');line.id='postdefaultcashsweepline86';line.className='line';(q('#fundingcrossdefaultline85')||q('#crossfacilitynettingline84')||q('#monetaryline')||q('#enforcement')).after(line)}line.textContent='post-default cash sweep: '+S.postDefaultCashSweepEvents86+' sweeps · '+S.postDefaultCashSweepPrincipal86.toFixed(1)+' principal retired · '+S.postDefaultCashSweepCasesCured86+' cured';let ctr=document.querySelector('#app .controls');if(ctr&&!q('#openPostDefaultCashSweep86')){let x=document.createElement('button');x.id='openPostDefaultCashSweep86';x.textContent='open post-default cash sweep';x.onclick=openOffice;ctr.prepend(x)}}
renderAll=function(){R86();let changed=reconcile();render86();if(changed)save86()};let f=q('#forget');if(f)f.onclick=()=>{for(let i=2;i<=86;i++)localStorage.removeItem('nothing-state-v'+i);location.reload()};setInterval(()=>{reconcile();render86();save86()},2300);ensure();reconcile();renderAll();save86();
})();