(()=>{
const BS48=save,BR48=renderAll,O48=JSON.parse(localStorage.getItem('nothing-state-v48')||'null')||{},cl=(v,a,b)=>Math.max(a,Math.min(b,v)),pick=a=>a&&a.length?a[Math.floor(Math.random()*a.length)]:null;
S.procurements48=O48.procurements48||[];
S.bids48=O48.bids48||[];
S.vendorContracts48=O48.vendorContracts48||[];
S.vendorProfiles48=O48.vendorProfiles48||[];
S.procurementAudits48=O48.procurementAudits48||[];
S.procurementSerial48=O48.procurementSerial48||0;
S.bidSerial48=O48.bidSerial48||0;
S.vendorContractSerial48=O48.vendorContractSerial48||0;
S.vendorSerial48=O48.vendorSerial48||0;
S.procurementAuditSerial48=O48.procurementAuditSerial48||0;
S.procurementsOpened48=O48.procurementsOpened48||0;
S.competitiveAwards48=O48.competitiveAwards48||0;
S.soleSourceAwards48=O48.soleSourceAwards48||0;
S.criteriaCaptures48=O48.criteriaCaptures48||0;
S.vendorLockins48=O48.vendorLockins48||0;
S.contractBreaches48=O48.contractBreaches48||0;
S.vendorDebarments48=O48.vendorDebarments48||0;
S.procurementRebuilds48=O48.procurementRebuilds48||0;
S.procurementCrises48=O48.procurementCrises48||0;
S.lastProcurementCrisis48=O48.lastProcurementCrisis48||0;
S.procurementKeys48=O48.procurementKeys48||{};
S.lastProcurementTick48=O48.lastProcurementTick48||Date.now();
function save48(){BS48();localStorage.setItem('nothing-state-v48',JSON.stringify({procurements48:S.procurements48,bids48:S.bids48,vendorContracts48:S.vendorContracts48,vendorProfiles48:S.vendorProfiles48,procurementAudits48:S.procurementAudits48,procurementSerial48:S.procurementSerial48,bidSerial48:S.bidSerial48,vendorContractSerial48:S.vendorContractSerial48,vendorSerial48:S.vendorSerial48,procurementAuditSerial48:S.procurementAuditSerial48,procurementsOpened48:S.procurementsOpened48,competitiveAwards48:S.competitiveAwards48,soleSourceAwards48:S.soleSourceAwards48,criteriaCaptures48:S.criteriaCaptures48,vendorLockins48:S.vendorLockins48,contractBreaches48:S.contractBreaches48,vendorDebarments48:S.vendorDebarments48,procurementRebuilds48:S.procurementRebuilds48,procurementCrises48:S.procurementCrises48,lastProcurementCrisis48:S.lastProcurementCrisis48,procurementKeys48:S.procurementKeys48,lastProcurementTick48:S.lastProcurementTick48}))}save=save48;
const realm=id=>S.real[id],ns=id=>(S.namespaces46||[]).find(n=>n.id===id),pkg=id=>(S.packages45||[]).find(p=>p.id===id),treasury=id=>(S.packageTreasuries47||[]).find(t=>t.namespaceId===id),artifact=id=>(S.buildArtifacts44||[]).find(a=>a.id===id),sbomFor=id=>[...(S.sboms45||[])].reverse().find(s=>s.artifactId===id&&s.status==='current');
function hash48(s){let h=2166136261>>>0;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)>>>0}return h.toString(16).padStart(8,'0')}
function liveUsers(n){let ids=new Set();for(const s of (S.sboms45||[]).filter(s=>s.reality===n.reality&&s.status==='current'))if((s.components||[]).some(pid=>pkg(pid)?.name===n.name))ids.add(s.artifactId);return ids.size}
function maintainerName(n){let m=(S.maintainers46||[]).find(m=>m.id===n.owner);return m?.name||n.owner||'unknown maintainer'}
function activeSponsors(n){return (S.fundingContracts47||[]).filter(c=>c.namespaceId===n.id&&['active','fulfilled'].includes(c.status)).sort((a,b)=>(b.influence||0)-(a.influence||0))}
function vendorByName(name,id){let v=S.vendorProfiles48.find(v=>v.name===name&&v.reality===id);if(v)return v;v={id:'VEN'+(++S.vendorSerial48),name,reality:id,status:'eligible',security:.48+Math.random()*.4,continuity:.48+Math.random()*.4,compatibility:.48+Math.random()*.4,sovereignty:.4+Math.random()*.45,delivery:.45+Math.random()*.45,priceBias:.75+Math.random()*.7,wins:0,losses:0,breaches:0,lockIn:0,debarredAt:null,x:10+Math.random()*80,y:12+Math.random()*68};S.vendorProfiles48.push(v);return v}
function vendorOptions(n){let other=n.reality==='A'?'B':'A',names=[maintainerName(n),n.reality+' archive systems',n.reality+' administrative integrator','downstream dependency cooperative',other+' interoperability vendor'];for(const c of activeSponsors(n).slice(0,2))names.push(c.sponsor+' delivery arm');return [...new Set(names)].map(x=>vendorByName(x,n.reality)).filter(v=>v.status!=='debarred')}
function defaultCriteria(n){let pressure=(S.advisories45||[]).some(a=>a.reality===n.reality&&a.name===n.name&&['critical','high'].includes(a.severity)&&a.status!=='withdrawn');let strike=treasury(n.id)?.status==='strike';return {security:pressure?.32:.2,continuity:strike?.3:.2,compatibility:.22,sovereignty:.16,delivery:.12,price:pressure?.08:.1}}
function normalizeCriteria(c){let sum=Object.values(c).reduce((a,b)=>a+b,0)||1;for(const k of Object.keys(c))c[k]=c[k]/sum;return c}
function openProcurement(n,mode='competitive'){let existing=[...S.procurements48].reverse().find(p=>p.namespaceId===n.id&&['draft','bidding','evaluating'].includes(p.status));if(existing)return existing;let p={id:'RFP'+(++S.procurementSerial48),namespaceId:n.id,reality:n.reality,mode,status:'bidding',criteria:normalizeCriteria(defaultCriteria(n)),criteriaAuthor:'registry procurement office',requirements:['maintain '+n.name,'preserve current package identity','respond to critical advisories'],opened:Date.now(),deadline:Date.now()+45000,winnerBidId:null,contractId:null,capturedBy:null,soleSourceReason:null,x:10+Math.random()*80,y:12+Math.random()*68};S.procurements48.push(p);S.procurementsOpened48++;remember('PROCUREMENT '+p.id+': '+n.name+' opened '+mode+' maintenance procurement',realm(n.reality));if(typeof place==='function')place('warm','request for proposals beneath a package namespace',realm(n.reality));if(mode==='sole-source')soleSource(n,p);else for(const v of vendorOptions(n).slice(0,4))submitBid(p,v);return p}
function submitBid(p,v){if(!p||p.status!=='bidding'||!v||v.status==='debarred')return null;let n=ns(p.namespaceId),cost=(4+liveUsers(n)*1.3+(1-v.priceBias)*2+Math.random()*5),b={id:'BID'+(++S.bidSerial48),procurementId:p.id,namespaceId:n.id,reality:n.reality,vendorId:v.id,vendor:v.name,price:Math.max(2,Math.round(cost*10)/10),security:cl(v.security+(Math.random()-.5)*.12,0,1),continuity:cl(v.continuity+(Math.random()-.5)*.12,0,1),compatibility:cl(v.compatibility+(Math.random()-.5)*.12,0,1),sovereignty:cl(v.sovereignty+(Math.random()-.5)*.12,0,1),delivery:cl(v.delivery+(Math.random()-.5)*.12,0,1),status:'submitted',score:null,submitted:Date.now(),wroteCriteria:false,x:10+Math.random()*80,y:12+Math.random()*68};S.bids48.push(b);remember('PROCUREMENT BID '+b.id+': '+v.name+' bid '+b.price+' credits to maintain '+n.name,realm(n.reality));return b}
function bidsFor(p){return S.bids48.filter(b=>b.procurementId===p.id)}
function letVendorWriteCriteria(p,b){if(!p||!b||!['bidding','evaluating'].includes(p.status))return;let v=S.vendorProfiles48.find(v=>v.id===b.vendorId);if(!v)return;let traits={security:v.security,continuity:v.continuity,compatibility:v.compatibility,sovereignty:v.sovereignty,delivery:v.delivery};let ranked=Object.entries(traits).sort((a,b)=>b[1]-a[1]);p.criteria={security:.1,continuity:.1,compatibility:.1,sovereignty:.1,delivery:.1,price:.1};p.criteria[ranked[0][0]]=.34;p.criteria[ranked[1][0]]=.2;p.criteria.price=.06;normalizeCriteria(p.criteria);p.criteriaAuthor=v.name;b.wroteCriteria=true;p.capturedBy=v.name;S.criteriaCaptures48++;remember('RFP CAPTURE '+p.id+': '+v.name+' helped write the criteria used to score its own bid',realm(p.reality));if(typeof place==='function'){place('cold','winning vendor wrote the evaluation rubric',realm(p.reality));place('dream','best value according to vendor spreadsheet',realm(p.reality))}procurementCrisis(p.reality,'criteria-capture')}
function scoreBid(p,b){let c=p.criteria,priceScore=1-Math.min(1,b.price/20);return c.security*b.security+c.continuity*b.continuity+c.compatibility*b.compatibility+c.sovereignty*b.sovereignty+c.delivery*b.delivery+c.price*priceScore}
function evaluate(p){if(!p||!['bidding','evaluating'].includes(p.status))return null;p.status='evaluating';let bs=bidsFor(p).filter(b=>b.status==='submitted');for(const b of bs)b.score=scoreBid(p,b);bs.sort((a,b)=>b.score-a.score);if(!bs.length){$('#msg').textContent=p.id+' received no eligible bids.';return null}let win=bs[0];award(p,win,false);return win}
function soleSource(n,p=null){p=p||openProcurement(n,'sole-source');let vs=vendorOptions(n),t=treasury(n.id),preferred=vs.find(v=>v.name.includes(t?.capturedBy||'___'))||vs.sort((a,b)=>(b.continuity+b.delivery)-(a.continuity+a.delivery))[0];if(!preferred)return null;let b=submitBid({...p,status:'bidding'},preferred);if(!b){b={id:'BID'+(++S.bidSerial48),procurementId:p.id,namespaceId:n.id,reality:n.reality,vendorId:preferred.id,vendor:preferred.name,price:Math.round((8+liveUsers(n)*2)*10)/10,security:preferred.security,continuity:preferred.continuity,compatibility:preferred.compatibility,sovereignty:preferred.sovereignty,delivery:preferred.delivery,status:'submitted',score:1,submitted:Date.now(),wroteCriteria:false,x:10+Math.random()*80,y:12+Math.random()*68};S.bids48.push(b)}p.soleSourceReason=t?.status==='strike'?'maintainers on strike':t?.status==='bankrupt'?'package insolvency':'continuity emergency';award(p,b,true);return b}
function ensureVendorMaintainer(n,v){let m=(S.maintainers46||[]).find(m=>m.namespaceId===n.id&&m.vendor48===v.id&&m.status!=='resigned');if(m)return m;S.maintainerSerial46=S.maintainerSerial46||0;m={id:'MNT'+(++S.maintainerSerial46),namespaceId:n.id,reality:n.reality,name:v.name+' contractor',role:'vendor',status:'active',legitimacy:.42,fatigue:.08,contributions:0,appointed:Date.now(),departed:null,vendor48:v.id};S.maintainers46.push(m);n.maintainers=n.maintainers||[];if(!n.maintainers.includes(m.id))n.maintainers.push(m.id);return m}
function award(p,b,sole){let n=ns(p.namespaceId),v=S.vendorProfiles48.find(v=>v.id===b.vendorId),t=treasury(n.id);if(!n||!v)return;p.status='awarded';p.winnerBidId=b.id;b.status='awarded';v.wins++;for(const x of bidsFor(p))if(x.id!==b.id)x.status='lost';let m=ensureVendorMaintainer(n,v),c={id:'PC'+(++S.vendorContractSerial48),procurementId:p.id,namespaceId:n.id,reality:n.reality,vendorId:v.id,vendor:v.name,maintainerId:m.id,status:'active',value:b.price,remaining:b.price,paid:0,performance:.72,lockIn:.08+liveUsers(n)*.025,renewals:0,breaches:0,soleSource:!!sole,criteriaAuthor:p.criteriaAuthor,started:Date.now(),expires:Date.now()+60000,terms:{security:b.security,continuity:b.continuity,compatibility:b.compatibility},x:10+Math.random()*80,y:12+Math.random()*68};S.vendorContracts48.push(c);p.contractId=c.id;if(sole)S.soleSourceAwards48++;else S.competitiveAwards48++;if(t){let deposit=Math.min(t.balance,b.price*.25);t.balance-=deposit;c.paid+=deposit;c.remaining-=deposit}remember('PROCUREMENT AWARD '+p.id+': '+v.name+' received '+(sole?'SOLE-SOURCE ':'')+'contract '+c.id+' for '+n.name,realm(n.reality));if(typeof place==='function')place('warm',sole?'sole-source software contract':'competitive software contract',realm(n.reality));if(p.capturedBy===v.name){remember('CAPTURE CONFIRMED '+p.id+': vendor that wrote the criteria won the contract',realm(n.reality));procurementCrisis(n.reality,'captured-award')}renderAll();save48();openContract(c)}
function publishContractRelease(c){if(!c||c.status!=='active')return null;let n=ns(c.namespaceId),base=pkg(n.canonicalPackageId),v=S.vendorProfiles48.find(v=>v.id===c.vendorId);if(!n||!base||!v)return null;S.packageSerial45=S.packageSerial45||0;let parts=String(base.version||'1.0.0').split('.').map(x=>parseInt(x)||0);while(parts.length<3)parts.push(0);parts[2]++;let np={...base,id:'PKG'+(++S.packageSerial45),version:parts.join('.'),maintainer:v.name,status:'active',published:Date.now(),integrity:hash48(base.integrity+'|procurement|'+c.id+'|'+Date.now()),patchedFrom:base.id,foreignOf:null,x:10+Math.random()*80,y:12+Math.random()*68};S.packages45.push(np);S.packagesPublished45=(S.packagesPublished45||0)+1;n.canonicalPackageId=np.id;n.generation=(n.generation||0)+1;let m=(S.maintainers46||[]).find(m=>m.id===c.maintainerId);if(m){m.contributions=(m.contributions||0)+1;m.legitimacy=cl((m.legitimacy||.42)+.04,.1,.99)}remember('CONTRACT RELEASE '+c.id+': '+v.name+' published '+np.name+'@'+np.version+' under procurement authority',realm(n.reality));if(typeof place==='function')place('warm','contract deliverable became canonical package',realm(n.reality));return np}
function signArtifact48(a){let accepted=S.trustPolicies?.[a.reality]?.acceptedRoots||[],r=[...(S.trustRoots||[])].filter(r=>accepted.includes(r.id)&&r.status==='active').sort((a,b)=>(b.strength||0)-(a.strength||0))[0];if(!r)return;S.attestationSerial44=S.attestationSerial44||0;S.provenance44=S.provenance44||[];S.provenance44.push({id:'AT'+(++S.attestationSerial44),artifactId:a.id,reality:a.reality,builderId:a.builderId,sourceRef:a.sourceRef,recipeHash:a.recipeHash,artifactHash:a.artifactHash,rootId:r.id,status:'attested',created:Date.now()});S.trustAudits=S.trustAudits||[];S.trustAuditSerial=S.trustAuditSerial||0;S.trustAudits.push({id:'TA'+(++S.trustAuditSerial),reality:a.reality,remediationId:null,credentialId:null,certificateId:null,rootId:r.id,status:'procurement-delivery-attested',created:Date.now(),note:a.id+' vendor contract',x:10+Math.random()*80,y:12+Math.random()*68})}
function deployContract(c){let n=ns(c.namespaceId),target=pkg(n.canonicalPackageId),assign=S.replicaArtifacts44?.[n.reality]||{},touched=0;if(!target)return;for(const [nodeName,aid] of Object.entries(assign)){let old=artifact(aid),s=sbomFor(aid);if(!old||!s)continue;let hit=s.components.some(pid=>pkg(pid)?.name===n.name&&pid!==target.id);if(!hit)continue;let comps=s.components.map(pid=>pkg(pid)?.name===n.name?target.id:pid);S.artifactSerial44=S.artifactSerial44||0;let a={...old,id:'BIN'+(++S.artifactSerial44),depLock:(old.depLock||'lock')+'|pc48-'+c.id+'-'+c.renewals,recipeHash:hash48((old.recipeHash||'')+'|'+comps.join('|')+'|'+c.id),artifactHash:hash48((old.artifactHash||'')+'|'+comps.join('|')+'|'+c.id+'|'+Date.now()+'|'+nodeName),status:'built',builtAt:Date.now(),reproducedFrom:old.id,x:10+Math.random()*80,y:12+Math.random()*68};S.buildArtifacts44.push(a);S.artifactsBuilt44=(S.artifactsBuilt44||0)+1;signArtifact48(a);S.sbomSerial45=S.sbomSerial45||0;let hits=(S.advisories45||[]).filter(ad=>ad.status!=='withdrawn'&&comps.includes(ad.packageId)).map(ad=>ad.id),sb={id:'SBOM'+(++S.sbomSerial45),artifactId:a.id,reality:n.reality,components:comps,digest:hash48(a.artifactHash+'|'+comps.join('|')),status:'current',generated:Date.now(),vulnerable:hits,x:10+Math.random()*80,y:12+Math.random()*68};S.sboms45.push(sb);if(hits.length)a.status='known-vulnerable';s.status='superseded';assign[nodeName]=a.id;touched++}S.procurementRebuilds48+=touched;c.lockIn=cl(c.lockIn+touched*.08,0,1);if(c.lockIn>.72&&!c.lockInRecorded){c.lockInRecorded=true;S.vendorLockins48++;remember('VENDOR LOCK-IN '+c.id+': '+c.vendor+' now controls the deployed continuation path for '+n.name,realm(n.reality));if(typeof place==='function')place('cold','contract termination now requires rebuilding reality',realm(n.reality));procurementCrisis(n.reality,'vendor-lock-in')}$('#msg').textContent=touched+' live replicas rebuilt onto '+target.name+'@'+target.version+' delivered by '+c.vendor+'.';renderAll();save48();openContract(c)}
function breachContract(c){if(!c||c.status!=='active')return;c.breaches++;c.performance=cl(c.performance-.2,0,1);S.contractBreaches48++;let v=S.vendorProfiles48.find(v=>v.id===c.vendorId);if(v){v.breaches++;v.security=cl(v.security-.05,0,1)}remember('CONTRACT BREACH '+c.id+': '+c.vendor+' missed a package maintenance obligation',realm(c.reality));if(typeof place==='function')place('cold','vendor missed SLA while package remained canonical',realm(c.reality));if(c.breaches>=2)procurementCrisis(c.reality,'repeat-breach');renderAll();save48();openContract(c)}
function debarVendor(c){let v=S.vendorProfiles48.find(v=>v.id===c.vendorId);if(!v)return;v.status='debarred';v.debarredAt=Date.now();c.status='terminated';S.vendorDebarments48++;remember('VENDOR DEBARRED: '+v.name+' may not bid again in Reality '+c.reality+' but its delivered package remains deployed',realm(c.reality));if(typeof place==='function')place('cold','debarred vendor still inside production SBOM',realm(c.reality));$('#msg').textContent=v.name+' was debarred. Existing delivered binaries were not rolled back.';renderAll();save48()}
function renew(c){if(!c||c.status!=='active')return;c.renewals++;c.expires=Date.now()+60000;c.value=Math.round(c.value*1.12*10)/10;c.remaining+=c.value*.35;c.lockIn=cl(c.lockIn+.12,0,1);let n=ns(c.namespaceId),m=(S.maintainers46||[]).find(m=>m.id===c.maintainerId);if(m)m.legitimacy=cl((m.legitimacy||.42)+.03,.1,.99);remember('CONTRACT RENEWAL '+c.id+': '+c.vendor+' renewed without reopening competition',realm(c.reality));if(typeof place==='function')place('dream','contract renewal became package continuity',realm(c.reality));if(c.renewals>=2)procurementCrisis(c.reality,'serial-renewal');renderAll();save48();openContract(c)}
function auditProcurement(p){let bs=bidsFor(p),a={id:'PA'+(++S.procurementAuditSerial48),procurementId:p.id,reality:p.reality,criteriaAuthor:p.criteriaAuthor,capturedBy:p.capturedBy,winnerBidId:p.winnerBidId,bids:bs.map(b=>({id:b.id,vendor:b.vendor,score:b.score,price:b.price,wroteCriteria:b.wroteCriteria})),created:Date.now()};S.procurementAudits48.push(a);S.procurementAudits48=S.procurementAudits48.slice(-64);remember('PROCUREMENT AUDIT '+a.id+': '+p.id+' criteria by '+p.criteriaAuthor+', winner '+(p.winnerBidId||'none'),realm(p.reality));return a}
function procurementCrisis(id,reason){if(Date.now()-S.lastProcurementCrisis48<8000)return false;let key=id+'|'+reason+'|'+Math.floor(Date.now()/20000);if(S.procurementKeys48[key])return false;S.procurementKeys48[key]=1;S.procurementCrises48++;S.lastProcurementCrisis48=Date.now();for(const rid of ['A','B']){realm(rid).disputes=(realm(rid).disputes||0)+1;remember('PROCUREMENT CRISIS: vendor selection became authority over which package implementation can become reality',realm(rid))}realm(id).timelineDrift=(realm(id).timelineDrift||0)+1;if(typeof place==='function'){place('cold','RFP became a constitutional instrument',realm(id));place('dream','best value became source of authority',realm(id))}S.bailiffMood='asking whether the contract or the package is sovereign';return true}
function tickContracts(){let now=Date.now();for(const c of S.vendorContracts48.filter(c=>c.status==='active')){let n=ns(c.namespaceId),t=treasury(c.namespaceId),v=S.vendorProfiles48.find(v=>v.id===c.vendorId);if(!n||!v)continue;if(t&&c.remaining>0){let pay=Math.min(c.remaining,.3+liveUsers(n)*.04,t.balance);if(pay>0){t.balance-=pay;c.remaining-=pay;c.paid+=pay}}c.performance=cl(c.performance+(Math.random()-.47)*.025,0,1);c.lockIn=cl(c.lockIn+liveUsers(n)*.0007,0,1);v.lockIn=Math.max(v.lockIn,c.lockIn);if(now>c.expires&&Math.random()<.012)renew(c);if(c.performance<.32&&Math.random()<.01)breachContract(c)}}
function autonomous(){let now=Date.now();if(now-S.lastProcurementTick48<1800)return;S.lastProcurementTick48=now;tickContracts();for(const n of (S.namespaces46||[])){let t=treasury(n.id),open=S.procurements48.some(p=>p.namespaceId===n.id&&['bidding','evaluating'].includes(p.status));if(!open&&t&&['strike','bankrupt'].includes(t.status)&&Math.random()<.006){openProcurement(n,'sole-source');break}}}
function openBid(b){let p=S.procurements48.find(p=>p.id===b.procurementId),buttons=[];if(p&&p.status==='bidding'&&!p.capturedBy)buttons.push(['let this bidder draft criteria',()=>{letVendorWriteCriteria(p,b);renderAll();save48();openProcurementPanel(p)}]);buttons.push(['close',closePanel]);panel(b.id+' · '+b.vendor,'price '+b.price+' · '+b.status,'security '+Math.round(b.security*100)+' · continuity '+Math.round(b.continuity*100)+' · compatibility '+Math.round(b.compatibility*100)+' · sovereignty '+Math.round(b.sovereignty*100)+' · delivery '+Math.round(b.delivery*100)+(b.score!=null?'\nscore '+Math.round(b.score*100):''),buttons)}
function openContract(c){let n=ns(c.namespaceId),buttons=[];if(c.status==='active')buttons.push(['publish contract release',()=>{publishContractRelease(c);renderAll();save48();openContract(c)}],['deploy contract release',()=>deployContract(c)],['record contract breach',()=>breachContract(c)],['renew without rebid',()=>renew(c)],['debar vendor',()=>debarVendor(c)]);buttons.push(['close',closePanel]);panel(c.id+' · '+c.vendor,c.status+' · '+(c.soleSource?'SOLE SOURCE':'competitive')+' · '+n?.name,'value '+c.value+' · paid '+c.paid.toFixed(1)+' · remaining '+c.remaining.toFixed(1)+' · performance '+Math.round(c.performance*100)+'% · lock-in '+Math.round(c.lockIn*100)+'% · renewals '+c.renewals+' · breaches '+c.breaches,buttons)}
function openProcurementPanel(p){let n=ns(p.namespaceId),bs=bidsFor(p),buttons=[];for(const b of bs.slice(0,6))buttons.push(['open '+b.id+' · '+b.vendor,()=>openBid(b)]);if(p.status==='bidding')buttons.push(['evaluate and award',()=>evaluate(p)]);if(p.mode!=='sole-source'&&p.status==='bidding')buttons.push(['convert to sole source',()=>{p.mode='sole-source';soleSource(n,p)}]);buttons.push(['audit procurement',()=>{auditProcurement(p);renderAll();save48();openProcurementPanel(p)}]);if(p.contractId){let c=S.vendorContracts48.find(c=>c.id===p.contractId);if(c)buttons.push(['open contract '+c.id,()=>openContract(c)])}buttons.push(['close',closePanel]);let crit=Object.entries(p.criteria).map(([k,v])=>k+' '+Math.round(v*100)+'%').join(' · ');panel(p.id+' · '+p.status.toUpperCase(),n?.name+' · '+p.mode+' · criteria by '+p.criteriaAuthor,crit+'\n'+bs.length+' bids'+(p.capturedBy?' · captured by '+p.capturedBy:'')+(p.soleSourceReason?'\nsole-source reason: '+p.soleSourceReason:''),buttons)}
function openProcurementDesk(id=S.active){let nsx=(S.namespaces46||[]).filter(n=>n.reality===id),open=[...S.procurements48].reverse().filter(p=>p.reality===id).slice(0,5),active=S.vendorContracts48.filter(c=>c.reality===id&&c.status==='active'),buttons=[];for(const n of nsx.slice(0,5))buttons.push(['procure '+n.name,()=>openProcurementPanel(openProcurement(n))]);for(const p of open)buttons.push(['open '+p.id,()=>openProcurementPanel(p)]);for(const c of active.slice(-3))buttons.push(['contract '+c.id,()=>openContract(c)]);buttons.push(['close',closePanel]);panel('PROCUREMENT · Reality '+id,open.length+' recent solicitations · '+active.length+' active contracts',S.competitiveAwards48+' competitive awards · '+S.soleSourceAwards48+' sole source · '+S.criteriaCaptures48+' captured criteria · '+S.vendorLockins48+' lock-ins · '+S.vendorDebarments48+' debarments · '+S.procurementCrises48+' crises',buttons)}
function renderProcurement(){let layer=$('#procurementLayer');if(!layer){layer=document.createElement('div');layer.id='procurementLayer';document.body.appendChild(layer)}layer.innerHTML='';for(const p of S.procurements48.slice(-16)){let e=document.createElement('i');e.className='procurementNode '+p.status+(p.capturedBy?' captured':'');e.dataset.label=p.id;e.style.left=p.x+'%';e.style.top=p.y+'%';e.onclick=()=>openProcurementPanel(p);layer.appendChild(e)}for(const c of S.vendorContracts48.filter(c=>c.status==='active').slice(-12)){let e=document.createElement('i');e.className='vendorContract'+(c.soleSource?' sole':'')+(c.lockIn>.72?' locked':'');e.dataset.label=c.id;e.style.left=c.x+'%';e.style.top=c.y+'%';e.onclick=()=>openContract(c);layer.appendChild(e)}let line=$('#procurementline');if(!line){line=document.createElement('div');line.id='procurementline';line.className='line';($('#economyline')||$('#governanceline')||$('#dependencyline')||$('#enforcement')).after(line)}let id=S.active,active=S.vendorContracts48.filter(c=>c.reality===id&&c.status==='active'),sole=active.filter(c=>c.soleSource).length,locked=active.filter(c=>c.lockIn>.72).length;line.textContent='procurement: '+active.length+' contracts · '+sole+' sole-source · '+locked+' locked-in · '+S.criteriaCaptures48+' captured criteria · '+S.contractBreaches48+' breaches · '+S.procurementCrises48+' crises';let ctr=document.querySelector('#app .controls');if(ctr&&!$('#openProcurementButton')){let b=document.createElement('button');b.id='openProcurementButton';b.textContent='open procurement';b.onclick=()=>openProcurementDesk(S.active);ctr.prepend(b)}if(ctr&&!$('#procureCriticalButton')){let b=document.createElement('button');b.id='procureCriticalButton';b.textContent='procure critical package';b.onclick=()=>{let xs=(S.namespaces46||[]).filter(n=>n.reality===S.active).sort((a,b)=>liveUsers(b)-liveUsers(a));if(xs[0])openProcurementPanel(openProcurement(xs[0]))};ctr.prepend(b)}}
renderAll=function(){BR48();renderProcurement()};let f=$('#forget');if(f)f.onclick=()=>{for(let i=2;i<=48;i++)localStorage.removeItem('nothing-state-v'+i);location.reload()};
setInterval(()=>{autonomous();renderProcurement();save48()},1950);renderAll();save48();
})();
