(()=>{
const BS42=save,BR42=renderAll,O42=JSON.parse(localStorage.getItem('nothing-state-v42')||'null')||{},cl=(v,a,b)=>Math.max(a,Math.min(b,v)),pick=a=>a&&a.length?a[Math.floor(Math.random()*a.length)]:null;
const NAMES=['traveler','bailiff','archive','court','administration'];
S.consensus42=O42.consensus42||{A:null,B:null};
S.consensusProposals=O42.consensusProposals||[];
S.quorumCertificates=O42.quorumCertificates||[];
S.consensusPartitions=O42.consensusPartitions||[];
S.consensusProposalSerial=O42.consensusProposalSerial||0;
S.quorumCertificateSerial=O42.quorumCertificateSerial||0;
S.consensusPartitionSerial=O42.consensusPartitionSerial||0;
S.leaderElections42=O42.leaderElections42||0;
S.quorumCommits42=O42.quorumCommits42||0;
S.failedQuorums42=O42.failedQuorums42||0;
S.staleLeaderAttempts42=O42.staleLeaderAttempts42||0;
S.unsafeQuorums42=O42.unsafeQuorums42||0;
S.splitBrainCommits42=O42.splitBrainCommits42||0;
S.consensusCrises42=O42.consensusCrises42||0;
S.lastConsensusCrisis42=O42.lastConsensusCrisis42||0;
S.consensusKeys42=O42.consensusKeys42||{};
for(const id of ['A','B'])S.consensus42[id]=Object.assign({term:0,leader:null,previousLeader:null,leaderSince:0,committedHead:null,committedTerm:0,status:'electing',votes:{},lastElection:0,lastCommit:0},S.consensus42[id]||{});
S.consensusProposals=S.consensusProposals.map((p,i)=>({id:p.id||'QP'+(i+1),reality:p.reality||'A',term:p.term||0,leader:p.leader||null,head:p.head||'00000000',source:p.source||'current-log',status:p.status||'proposed',votes:p.votes||[],rejections:p.rejections||[],unsafe:!!p.unsafe,created:p.created||Date.now(),x:Number.isFinite(p.x)?p.x:10+Math.random()*80,y:Number.isFinite(p.y)?p.y:12+Math.random()*68}));
S.quorumCertificates=S.quorumCertificates.map((q,i)=>({id:q.id||'QC'+(i+1),proposalId:q.proposalId||null,reality:q.reality||'A',term:q.term||0,head:q.head||'00000000',leader:q.leader||null,signers:q.signers||[],status:q.status||'committed',unsafe:!!q.unsafe,created:q.created||Date.now(),x:Number.isFinite(q.x)?q.x:10+Math.random()*80,y:Number.isFinite(q.y)?q.y:12+Math.random()*68}));
S.consensusPartitions=S.consensusPartitions.map((p,i)=>({id:p.id||'NET'+(i+1),reality:p.reality||'A',status:p.status||'active',left:p.left||[],right:p.right||[],created:p.created||Date.now(),healedAt:p.healedAt||null,x:Number.isFinite(p.x)?p.x:10+Math.random()*80,y:Number.isFinite(p.y)?p.y:12+Math.random()*68}));
function save42(){BS42();localStorage.setItem('nothing-state-v42',JSON.stringify({consensus42:S.consensus42,consensusProposals:S.consensusProposals,quorumCertificates:S.quorumCertificates,consensusPartitions:S.consensusPartitions,consensusProposalSerial:S.consensusProposalSerial,quorumCertificateSerial:S.quorumCertificateSerial,consensusPartitionSerial:S.consensusPartitionSerial,leaderElections42:S.leaderElections42,quorumCommits42:S.quorumCommits42,failedQuorums42:S.failedQuorums42,staleLeaderAttempts42:S.staleLeaderAttempts42,unsafeQuorums42:S.unsafeQuorums42,splitBrainCommits42:S.splitBrainCommits42,consensusCrises42:S.consensusCrises42,lastConsensusCrisis42:S.lastConsensusCrisis42,consensusKeys42:S.consensusKeys42}))}save=save42;
const realm=id=>S.real[id],log=id=>S.transparencyLogs?.[id],witnesses=id=>(S.transparencyWitnesses||[]).filter(w=>w.reality===id),state=id=>S.consensus42[id],activePartition=id=>[...S.consensusPartitions].reverse().find(p=>p.reality===id&&p.status==='active'),activeFork=id=>[...(S.transparencyForks||[])].reverse().find(f=>f.reality===id&&f.status==='active');
function ensureNodes(){for(const id of ['A','B']){let st=state(id);if(!st.leader&&Date.now()-st.lastElection>1200)electLeader(id,true)}}
function partitionSide(id,name){let p=activePartition(id);if(!p)return'whole';if(p.left.includes(name))return'left';if(p.right.includes(name))return'right';return'isolated'}
function reachable(id,leader){let ws=witnesses(id),p=activePartition(id);if(!p)return ws;let side=partitionSide(id,leader);return ws.filter(w=>partitionSide(id,w.name)===side)}
function electionPool(id){let ws=witnesses(id);if(!ws.length)return NAMES.map(name=>({name,trust:.55,lastHead:null}));let p=activePartition(id);if(!p)return ws;let groups=[p.left,p.right].sort((a,b)=>b.length-a.length),major=groups[0];return ws.filter(w=>major.includes(w.name))}
function electLeader(id=S.active,automatic=false){let st=state(id),pool=electionPool(id);if(!pool.length)return null;st.previousLeader=st.leader;st.term=(st.term||0)+1;let sorted=[...pool].sort((a,b)=>(b.trust||.5)-(a.trust||.5)+(Math.random()-.5)*.16),candidate=sorted[0],reach=reachable(id,candidate.name),votes=reach.filter(w=>Math.random()<(.86+(w.trust||.5)*.08)).map(w=>w.name);st.votes={term:st.term,candidate:candidate.name,votes};st.lastElection=Date.now();S.leaderElections42++;if(votes.length>=3){st.leader=candidate.name;st.leaderSince=Date.now();st.status='leader';remember('CONSENSUS LEADER: '+candidate.name+' won term '+st.term+' in Reality '+id+' with '+votes.length+'/5 votes',realm(id));if(typeof place==='function')place('warm','leader elected by witness quorum',realm(id));if(!automatic)$('#msg').textContent=candidate.name+' became consensus leader for term '+st.term+'.'}else{st.leader=null;st.status='no-quorum';S.failedQuorums42++;remember('LEADER ELECTION FAILED: term '+st.term+' could not reach quorum in Reality '+id,realm(id));if(typeof place==='function')place('cold','election without a majority network',realm(id));if(!automatic)$('#msg').textContent='Leader election failed: only '+votes.length+' witnesses could agree.'}renderAll();save42();return st.leader}
function headForProposal(id,leader){let f=activeFork(id),w=witnesses(id).find(w=>w.name===leader),l=log(id);if(f&&w?.side==='alternate')return f.alternateHead;return l?.head||'00000000'}
function canVote(w,p){if(!w)return false;let st=state(p.reality);if(p.term<st.term)return false;let part=activePartition(p.reality);if(part&&partitionSide(p.reality,w.name)!==partitionSide(p.reality,p.leader))return false;let f=activeFork(p.reality);let expected=f?(w.side==='alternate'?f.alternateHead:f.canonicalHead):(log(p.reality)?.head||p.head);return expected===p.head}
function proposeHead(id=S.active,opts={}){let st=state(id);if(!st.leader&&!electLeader(id,true))return null;let leader=opts.leader||st.leader,term=opts.term??st.term,head=opts.head||headForProposal(id,leader),p={id:'QP'+(++S.consensusProposalSerial),reality:id,term,leader,head,source:opts.source||'current-log',status:'proposed',votes:[],rejections:[],unsafe:!!opts.unsafe,created:Date.now(),x:10+Math.random()*80,y:12+Math.random()*68};S.consensusProposals.push(p);S.consensusProposals=S.consensusProposals.slice(-42);let ws=witnesses(id);for(const w of ws){if(canVote(w,p))p.votes.push(w.name);else p.rejections.push(w.name)}if(p.votes.length>=3)return commitProposal(p,false);p.status='no-quorum';S.failedQuorums42++;remember('QUORUM FAILED '+p.id+': '+p.leader+' proposed '+p.head+' but received '+p.votes.length+'/5 votes',realm(id));if(typeof place==='function')place('cold','proposed history without quorum',realm(id));$('#msg').textContent=p.id+' failed: '+p.votes.length+'/5 witnesses accepted '+p.head+'.';renderAll();save42();return p}
function conflictingCertificate(id,head,term,unsafe=false){return [...S.quorumCertificates].reverse().find(q=>q.reality===id&&['committed','conflicting'].includes(q.status)&&q.head!==head&&(q.term===term||unsafe||q.unsafe))}
function commitProposal(p,unsafe=false){let st=state(p.reality),needed=unsafe?2:3;if(p.votes.length<needed)return p;p.status='committed';p.unsafe=!!unsafe;let q={id:'QC'+(++S.quorumCertificateSerial),proposalId:p.id,reality:p.reality,term:p.term,head:p.head,leader:p.leader,signers:[...p.votes],status:'committed',unsafe:!!unsafe,created:Date.now(),x:10+Math.random()*80,y:12+Math.random()*68};S.quorumCertificates.push(q);S.quorumCertificates=S.quorumCertificates.slice(-42);S.quorumCommits42++;if(unsafe)S.unsafeQuorums42++;let conflict=conflictingCertificate(p.reality,p.head,p.term,unsafe);if(conflict){q.status='conflicting';conflict.status='conflicting';S.splitBrainCommits42++;splitBrain(p.reality,q,conflict)}else{st.committedHead=p.head;st.committedTerm=p.term;st.lastCommit=Date.now();st.status='committed';let l=log(p.reality);if(l)l.quorumHead=p.head;let op=(S.trustRoots||[]).find(r=>r.id===l?.operatorRootId);if(op&&op.status==='active')op.strength=cl((op.strength||.55)+.012,.1,.99);remember('QUORUM COMMIT '+q.id+': '+p.head+' became consensus-final in Reality '+p.reality+' with '+q.signers.join(', '),realm(p.reality));if(typeof place==='function')place('warm','history with a quorum certificate',realm(p.reality));$('#msg').textContent=q.id+' committed '+p.head+' with '+q.signers.length+'/5 witnesses.'}renderAll();save42();return q}
function unsafeCommit(id=S.active){let st=state(id),p=activePartition(id);if(!p){$('#msg').textContent='Emergency quorum requires a partition or stale-leader condition.';return}let stale=st.previousLeader||pick(p.right)||pick(p.left);if(!stale)return;S.staleLeaderAttempts42++;let term=Math.max(0,st.term-1),head=headForProposal(id,stale),qp={id:'QP'+(++S.consensusProposalSerial),reality:id,term,leader:stale,head,source:'emergency-stale-leader',status:'proposed',votes:[],rejections:[],unsafe:true,created:Date.now(),x:10+Math.random()*80,y:12+Math.random()*68};S.consensusProposals.push(qp);let side=partitionSide(id,stale),local=witnesses(id).filter(w=>partitionSide(id,w.name)===side);qp.votes=local.slice(0,2).map(w=>w.name);qp.rejections=witnesses(id).filter(w=>!qp.votes.includes(w.name)).map(w=>w.name);remember('STALE LEADER '+stale+' attempted emergency commit in old term '+term+' with '+qp.votes.length+' signatures',realm(id));if(typeof place==='function')place('cold','stale leader holding an emergency quorum',realm(id));return commitProposal(qp,true)}
function splitBrain(id,a,b){let st=state(id);st.status='split-brain';realm(id).timelineDrift=(realm(id).timelineDrift||0)+1.5;realm(id).disputes=(realm(id).disputes||0)+2;remember('SPLIT-BRAIN CONSENSUS: '+a.id+' and '+b.id+' both claim finality for different heads',realm(id));if(typeof place==='function'){place('cold','two quorum certificates one history',realm(id));place('dream','majority that disagrees with another majority',realm(id))}let l=log(id);if(l)l.status='consensus-split';S.bailiffMood='asking which majority was the majority';openConsensusIncident(id,'conflicting quorum certificates for one reality','SEV1');consensusCrisis(id,'split-brain')}
function openConsensusIncident(id,title,severity='SEV2'){S.incidents=S.incidents||[];let x=S.incidents.find(n=>n.reality===id&&n.status==='open'&&n.title===title);if(x)return x;S.incidentSerial=S.incidentSerial||0;x={id:'INC'+(++S.incidentSerial),reality:id,title,severity,status:'open',alertIds:[],started:Date.now(),acknowledged:null,resolved:null,postmortem:null,owner:'consensus review',x:10+Math.random()*80,y:12+Math.random()*68};S.incidents.push(x);remember('CONSENSUS INCIDENT '+x.id+': '+title,realm(id));return x}
function createPartition(id=S.active,automatic=false){if(activePartition(id))return activePartition(id);let names=witnesses(id).map(w=>w.name);if(names.length<5)names=[...NAMES];names.sort(()=>Math.random()-.5);let p={id:'NET'+(++S.consensusPartitionSerial),reality:id,status:'active',left:names.slice(0,3),right:names.slice(3),created:Date.now(),healedAt:null,x:10+Math.random()*80,y:12+Math.random()*68};S.consensusPartitions.push(p);let st=state(id);st.previousLeader=st.leader;st.leader=null;st.status='partitioned';remember('NETWORK PARTITION '+p.id+': '+p.left.join(', ')+' cannot reach '+p.right.join(', '),realm(id));if(typeof place==='function'){place('cold','witness network split in two',realm(id));place('dream','leader heartbeat stopped at partition boundary',realm(id))}if(!automatic)$('#msg').textContent=p.id+' split the witness network 3/2. A new election will only see one side.';electLeader(id,true);renderAll();save42();return p}
function healPartition(p=activePartition(S.active)){if(!p)return;p.status='healed';p.healedAt=Date.now();remember('NETWORK HEALED '+p.id+': witnesses can compare consensus histories again',realm(p.reality));if(typeof place==='function')place('warm','partition healed with incompatible journals',realm(p.reality));let st=state(p.reality);st.leader=null;st.status='electing';electLeader(p.reality,true);let cs=S.quorumCertificates.filter(q=>q.reality===p.reality&&['committed','conflicting'].includes(q.status)),heads=[...new Set(cs.map(q=>q.head))];if(heads.length>1){openConsensusIncident(p.reality,'healed network discovered multiple committed histories','SEV1');consensusCrisis(p.reality,'healed-conflict')}$('#msg').textContent=p.id+' healed. The network can communicate again; committed contradictions remain committed.';renderAll();save42();openConsensus(p.reality)}
function consensusCrisis(id,reason){if(Date.now()-S.lastConsensusCrisis42<8000)return false;let key=id+'|'+reason+'|'+Math.floor(Date.now()/20000);if(S.consensusKeys42[key])return false;S.consensusKeys42[key]=1;S.consensusCrises42++;S.lastConsensusCrisis42=Date.now();for(const rid of ['A','B']){realm(rid).disputes=(realm(rid).disputes||0)+1;remember('CONSENSUS CRISIS: quorum certificates became a source of authority instead of evidence of agreement',realm(rid))}if(typeof place==='function'){place('cold','finality with two final answers',realm(id));place('dream','consensus protocol arguing about consensus',realm(id))}return true}
function autonomous(){for(const id of ['A','B']){let st=state(id),l=log(id);if(!st.leader&&Date.now()-st.lastElection>9000)electLeader(id,true);if(st.leader&&l?.head&&l.head!==st.committedHead&&!activePartition(id)&&Math.random()<.025)proposeHead(id,{source:'automatic-log-head'});let risk=(activeFork(id)?.004:0)+(S.transparencyCrises?Math.min(.004,S.transparencyCrises*.0005):0);if(!activePartition(id)&&Math.random()<risk)createPartition(id,true)}}
function openProposal(p){let b=[];if(p.status==='no-quorum'&&p.votes.length>=2)b.push(['accept emergency quorum',()=>commitProposal(p,true)]);b.push(['close',closePanel]);panel(p.id+' · '+p.status.toUpperCase(),'term '+p.term+' · leader '+p.leader+' · head '+p.head+'\n\nvotes '+p.votes.join(', ')+'\nrejected '+p.rejections.join(', '),(p.unsafe?'UNSAFE · ':'')+p.source,b)}
function openCertificate(q){let b=[['close',closePanel]];panel(q.id+' · '+q.status.toUpperCase(),'Reality '+q.reality+' · term '+q.term+' · '+q.head+'\n\nleader '+q.leader+'\nsigners '+q.signers.join(', '),(q.unsafe?'emergency quorum · ':'')+'quorum certificate',b)}
function openPartition(p){let b=[];if(p.status==='active')b.push(['heal network',()=>healPartition(p)],['stale leader emergency commit',()=>unsafeCommit(p.reality)]);b.push(['close',closePanel]);panel(p.id+' · '+p.status.toUpperCase(),'left: '+p.left.join(', ')+'\nright: '+p.right.join(', '),'network partition · created '+new Date(p.created).toLocaleTimeString(),b)}
function openConsensus(id=S.active){let st=state(id),p=activePartition(id),recent=[...S.quorumCertificates].reverse().filter(q=>q.reality===id).slice(0,4),b=[['elect leader',()=>electLeader(id)],['propose current head',()=>proposeHead(id)]];if(p)b.push(['open '+p.id,()=>openPartition(p)],['heal partition',()=>healPartition(p)],['emergency stale-leader commit',()=>unsafeCommit(id)]);else b.push(['partition witness network',()=>createPartition(id)]);for(const q of recent)b.push(['open '+q.id,()=>openCertificate(q)]);b.push(['close',closePanel]);panel('QUORUM · Reality '+id,'term '+st.term+' · leader '+(st.leader||'none')+'\ncommitted '+(st.committedHead||'none')+'\nobserved '+(log(id)?.head||'none'),(p?'PARTITIONED · ':'')+S.quorumCommits42+' commits · '+S.failedQuorums42+' failed · '+S.unsafeQuorums42+' unsafe · '+S.splitBrainCommits42+' split-brain',b)}
function renderQuorum(){ensureNodes();let layer=$('#quorumLayer');if(!layer){layer=document.createElement('div');layer.id='quorumLayer';document.body.appendChild(layer)}layer.innerHTML='';for(const q of S.quorumCertificates.slice(-18)){let n=document.createElement('i');n.className='quorumCertificate '+q.status+(q.unsafe?' unsafe':'');n.dataset.label=q.id;n.style.left=q.x+'%';n.style.top=q.y+'%';n.onclick=()=>openCertificate(q);layer.appendChild(n)}for(const p of S.consensusPartitions.filter(p=>p.status==='active')){let n=document.createElement('i');n.className='quorumPartition';n.dataset.label=p.id;n.style.left=p.x+'%';n.style.top=p.y+'%';n.onclick=()=>openPartition(p);layer.appendChild(n)}let line=$('#quorumline');if(!line){line=document.createElement('div');line.id='quorumline';line.className='line';($('#transparencyline')||$('#trustline')||$('#accessline')||$('#enforcement')).after(line)}let id=S.active,st=state(id),l=log(id),p=activePartition(id);line.textContent='quorum: term '+st.term+' · leader '+(st.leader||'none')+' · observed '+(l?.head||'none')+' · committed '+(st.committedHead||'none')+' · '+S.quorumCommits42+' commits · '+S.unsafeQuorums42+' unsafe · '+S.splitBrainCommits42+' split-brain'+(p?' · PARTITIONED':'');let ctr=document.querySelector('#app .controls');if(ctr&&!$('#openQuorumButton')){let b=document.createElement('button');b.id='openQuorumButton';b.textContent='open quorum';b.onclick=()=>openConsensus(S.active);ctr.prepend(b)}if(ctr&&!$('#commitQuorumButton')){let b=document.createElement('button');b.id='commitQuorumButton';b.textContent='commit observed head';b.onclick=()=>proposeHead(S.active);ctr.prepend(b)}}
renderAll=function(){BR42();renderQuorum()};let f=$('#forget');if(f)f.onclick=()=>{for(let i=2;i<=42;i++)localStorage.removeItem('nothing-state-v'+i);location.reload()};
setInterval(()=>{autonomous();renderQuorum();save42()},1850);ensureNodes();renderAll();save42();
})();
