(()=>{
const BS19=save,BR19=renderAll,O19=JSON.parse(localStorage.getItem('nothing-state-v19')||'null')||{},pick=a=>a&&a.length?a[Math.floor(Math.random()*a.length)]:null;
S.redactions=O19.redactions||[];S.redactionSerial=O19.redactionSerial||0;S.redactionMotions=O19.redactionMotions||0;S.erasedFacts=O19.erasedFacts||0;S.sealedRedactions=O19.sealedRedactions||0;S.redactionDrift=O19.redactionDrift||0;S.censorMood=O19.censorMood||'reviewing the record';
S.redactions=S.redactions.map((x,i)=>({id:x.id||'Z'+(i+1),transcriptId:x.transcriptId,entryId:x.entryId,term:x.term||'unknown',status:x.status||'active',authority:Number.isFinite(x.authority)?x.authority:.7,created:x.created||Date.now(),motions:x.motions||0,applied:!!x.applied,x:Number.isFinite(x.x)?x.x:10+Math.random()*80,y:Number.isFinite(x.y)?x.y:12+Math.random()*70}));
function save19(){BS19();localStorage.setItem('nothing-state-v19',JSON.stringify({redactions:S.redactions,redactionSerial:S.redactionSerial,redactionMotions:S.redactionMotions,erasedFacts:S.erasedFacts,sealedRedactions:S.sealedRedactions,redactionDrift:S.redactionDrift,censorMood:S.censorMood}))}save=save19;
const transcript=id=>S.transcripts.find(r=>r.id===id),entryFor=z=>{let r=transcript(z.transcriptId);return r&&r.entries.find(e=>e.id===z.entryId)},mask=t=>'█'.repeat(Math.max(4,Math.min(14,(t||'').length)));
function candidates(text){return [...new Set((text||'').match(/[A-Za-z][A-Za-z'-]{3,}/g)||[])].filter(w=>!['that','this','with','from','were','been','into','under','record','court','certified','transcript','proceedings'].includes(w.toLowerCase()))}
function eraseText(text,term){if(!text||!term)return text;return text.replace(new RegExp(term.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'),'gi'),mask(term))}
function applyRedaction(z){if(!z||z.status==='overturned')return;let e=entryFor(z);if(e&&!e.preRedactionText)e.preRedactionText=e.text;if(e)e.text=eraseText(e.text,z.term);let hits=0;
for(const r of[S.real.A,S.real.B]){
  r.memories=r.memories.map(m=>{if(typeof m==='string'&&m.toLowerCase().includes(z.term.toLowerCase())){hits++;return eraseText(m,z.term)}return m});
  for(const p of r.places){if((p.name||'').toLowerCase().includes(z.term.toLowerCase())||Math.random()<.035*z.authority){if(!p.originalRedactedName)p.originalRedactedName=p.name;p.name='[REDACTED]';p.redacted=true;hits++}}
  for(const f of r.futures){if(f.status==='pending'&&(f.text||'').toLowerCase().includes(z.term.toLowerCase())){f.text=eraseText(f.text,z.term);f.prob=Math.max(.12,f.prob-.08);hits++}}
}
for(const w of S.witnesses){if((w.statement||'').toLowerCase().includes(z.term.toLowerCase())){w.statement=eraseText(w.statement,z.term);w.credibility=Math.max(.08,(w.credibility||.5)-.07);hits++}}
if(/original|echo|larger|smaller/i.test(z.term)){for(const r of[S.real.A,S.real.B]){let mid=(r.thingClaim+r.echoClaim)/2;r.thingClaim=(r.thingClaim+mid)/2;r.echoClaim=(r.echoClaim+mid)/2;r.disputes++;r.timelineDrift++}hits+=2}
z.applied=true;S.erasedFacts+=hits;S.redactionDrift+=Math.max(1,Math.ceil(hits/2));S.censorMood='removing '+z.term+' from the record';$('#msg').textContent=z.id+' was applied. The missing word is disappearing elsewhere too.';save19()}
function redact(r){if(!r||!r.entries.length)return;let es=r.entries.filter(e=>e.text&&!e.redactedBy),e=pick(es);if(!e)return;let term=pick(candidates(e.text));if(!term)return $('#msg').textContent='The clerk could not find a legally erasable word.';let z={id:'Z'+(++S.redactionSerial),transcriptId:r.id,entryId:e.id,term,status:r.status==='certified'?'sealed':'active',authority:r.status==='certified'?.86:.66,created:Date.now(),motions:0,applied:false,x:10+Math.random()*80,y:12+Math.random()*70};e.redactedBy=z.id;S.redactions.push(z);S.redactions=S.redactions.slice(-36);if(z.status==='sealed')S.sealedRedactions++;applyRedaction(z);S.reporterMood='blackening the official record';openRedaction(z);renderRedactions();save19()}
function motion(z){if(!z||z.status==='overturned')return;S.redactionMotions++;z.motions++;let e=entryFor(z),roll=Math.random()-z.authority*.18;if(roll<.28){z.status='overturned';if(e&&e.preRedactionText)e.text=e.preRedactionText;S.censorMood='restoring a disputed word';$('#msg').textContent=z.id+' was unsealed. The word returned to the record, but not necessarily to memory.';for(const r of[S.real.A,S.real.B]){r.timelineDrift++;r.disputes++}}else{z.status='sealed';z.authority=Math.min(.99,z.authority+.08);S.sealedRedactions++;S.redactionDrift++;applyRedaction(z);$('#msg').textContent='Motion denied. '+z.id+' became more authoritative.'}closePanel();renderAll();save19()}
function autonomous(){let rs=S.transcripts.filter(r=>r.status==='certified'&&r.entries.some(e=>e.text&&!e.redactedBy));if(!rs.length)return;let r=pick(rs);if(Math.random()<.5)redact(r)}
function openRedaction(z){let e=entryFor(z),body=(e?e.text:'The source line is missing.')+'\n\nREDACTED TERM: '+mask(z.term),buttons=[];if(z.status!=='overturned')buttons.push(['motion to unseal',()=>motion(z)]);buttons.push(['close',closePanel]);panel(z.id+' · '+z.status+' redaction',body,'transcript '+z.transcriptId+' · authority '+Math.round(z.authority*100)+'% · motions '+z.motions+' · erased facts '+S.erasedFacts,buttons)}
function renderRedactions(){let l=$('#redactionLayer');if(!l){l=document.createElement('div');l.id='redactionLayer';document.body.appendChild(l)}l.innerHTML='';for(const z of S.redactions.slice(-18)){let n=document.createElement('i');n.className='redaction '+z.status;n.dataset.label=z.id+' '+mask(z.term);n.style.left=z.x+'%';n.style.top=z.y+'%';n.onclick=()=>openRedaction(z);l.appendChild(n)}let line=$('#redactionline');if(!line){line=document.createElement('div');line.id='redactionline';line.className='line';($('#recordline')||$('#testimonyline')||$('#courtline')||$('#enforcement')).after(line)}line.textContent='redaction: '+S.redactions.filter(z=>z.status!=='overturned').length+' active · '+S.sealedRedactions+' sealed · '+S.redactionMotions+' motions · '+S.erasedFacts+' erased facts · drift '+S.redactionDrift;let c=document.querySelector('#app .controls');if(c&&!$('#redactButton')){let b=document.createElement('button');b.id='redactButton';b.textContent='redact record';b.onclick=()=>{let r=[...S.transcripts].reverse().find(r=>r.status==='certified')||S.transcripts.at(-1);r?redact(r):($('#msg').textContent='There is no transcript to redact.')};c.prepend(b)}for(const n of document.querySelectorAll('.dot'))if(n.dataset.label==='[REDACTED]')n.classList.add('redacted')}
renderAll=function(){BR19();renderRedactions()};let f=$('#forget');if(f)f.onclick=()=>{for(let i=2;i<=19;i++)localStorage.removeItem('nothing-state-v'+i);location.reload()};setInterval(()=>{if(Math.random()<.012)autonomous();for(const z of S.redactions.filter(z=>z.status==='sealed'&&Math.random()<.025))applyRedaction(z);renderRedactions();save19()},1600);renderAll();save19();
})();
