(()=>{
const BS61=save,BR61=renderAll,O61=JSON.parse(localStorage.getItem('nothing-state-v61')||'null')||{},cl=(v,a,b)=>Math.max(a,Math.min(b,v));
S.remedyOffice61=O61.remedyOffice61||null;
S.remedyAwards61=O61.remedyAwards61||[];
S.remedyExecutions61=O61.remedyExecutions61||[];
S.remedyRecognitions61=O61.remedyRecognitions61||[];
S.remedySerial61=O61.remedySerial61||0;
S.remedyExecutionSerial61=O61.remedyExecutionSerial61||0;
S.remedyRecognitionSerial61=O61.remedyRecognitionSerial61||0;
S.remedyAwardsIssued61=O61.remedyAwardsIssued61||0;
S.remedyAwardsRecognized61=O61.remedyAwardsRecognized61||0;
S.remedyAwardsSatisfied61=O61.remedyAwardsSatisfied61||0;
S.remedyAwardsRefused61=O61.remedyAwardsRefused61||0;
S.remedyGarnishments61=O61.remedyGarnishments61||0;
S.remedyPaid61=O61.remedyPaid61||0;
S.remedyCrises61=O61.remedyCrises61||0;
S.remedyKeys61=O61.remedyKeys61||{};
S.lastRemedyTick61=O61.lastRemedyTick61||Date.now();
function save61(){BS61();localStorage.setItem('nothing-state-v61',JSON.stringify({remedyOffice61:S.remedyOffice61,remedyAwards61:S.remedyAwards61,remedyExecutions61:S.remedyExecutions61,remedyRecognitions61:S.remedyRecognitions61,remedySerial61:S.remedySerial61,remedyExecutionSerial61:S.remedyExecutionSerial61,remedyRecognitionSerial61:S.remedyRecognitionSerial61,remedyAwardsIssued61:S.remedyAwardsIssued61,remedyAwardsRecognized61:S.remedyAwardsRecognized61,remedyAwardsSatisfied61:S.remedyAwardsSatisfied61,remedyAwardsRefused61:S.remedyAwardsRefused61,remedyGarnishments61:S.remedyGarnishments61,remedyPaid61:S.remedyPaid61,remedyCrises61:S.remedyCrises61,remedyKeys61:S.remedyKeys61,lastRemedyTick61:S.lastRemedyTick61}))}save=save61;
const realm=id=>S.real[id],other=id=>id==='A'?'B':'A',treaty61=()=>S.treaties60?.[0],fund61=()=>S.stabilizationFunds58?.[0],currency61=id=>(S.fxCurrencies56||[]).find(c=>c.reality===id),acct61=id=>(S.tradeAccounts57||[]).find(a=>a.reality===id),motion61=id=>(S.fundMotions59||[]).find(m=>m.id===id),withdrawal61=id=>(S.treatyWithdrawals60||[]).find(w=>w.id===id),foreignCode=id=>id==='A'?'RB':'RA';
function trust61(id,status,note){let accepted=S.trustPolicies?.[id]?.acceptedRoots||[],r=[...(S.trustRoots||[])].filter(x=>accepted.includes(x.id)&&x.status==='active').sort((a,b)=>(b.strength||0)-(a.strength||0))[0];S.trustAudits=S.trustAudits||[];S.trustAuditSerial=S.trustAuditSerial||0;S.trustAudits.push({id:'TA'+(++S.trustAuditSerial),reality:id,remediationId:null,credentialId:null,certificateId:null,rootId:r?.id||null,status,created:Date.now(),note,x:10+Math.random()*80,y:12+Math.random()*68})}
function incident61(id,title,severity='SEV2'){S.incidents=S.incidents||[];let ex=S.incidents.find(i=>i.reality===id&&i.title===title&&i.status==='open');if(ex)return ex;S.incidentSerial=S.incidentSerial||0;let x={id:'INC'+(++S.incidentSerial),reality:id,title,severity,status:'open',alertIds:[],started:Date.now(),acknowledged:null,resolved:null,postmortem:null,owner:'interreality remedies office',x:10+Math.random()*80,y:12+Math.random()*68};S.incidents.push(x);return x}
function remedyCrisis(id,kind,severity='SEV2'){let now=Date.now(),k=id+'|'+kind;if(S.remedyKeys61[k]&&now-S.remedyKeys61[k]<14000)return;S.remedyKeys61[k]=now;S.remedyCrises61++;remember('REMEDY CRISIS: '+kind+' turned a treaty judgment into a claim on future liquidity',realm(id));if(typeof place==='function'){place('cold','judgment paid without reversing the decision',realm(id));place('dream','law became a lien on money that did not exist yet',realm(id))}let b=$('#bailiff');if(b)b.textContent='serving a judgment on assets that arrived after the case ended';incident61(id,'treaty remedy crisis: '+kind,severity)}
function ensureOffice(){if(!treaty61())return null;if(!S.remedyOffice61){S.remedyOffice61={id:'IRO1',name:'Interreality Recognition and Remedies Office',status:'operating',rule:'operational finality survives; monetary remedies remain available',created:Date.now(),x:50,y:58};remember('REMEDIES OFFICE IRO1: treaty invalidity acquired compensation, recognition, and execution without acquiring time travel',realm('A'));remember('REMEDIES OFFICE IRO1: treaty invalidity acquired compensation, recognition, and execution without acquiring time travel',realm('B'));trust61('A','interreality-remedies-office-created','IRO1 recognizes treaty awards after operational finality');trust61('B','interreality-remedies-office-created','IRO1 recognizes treaty awards after operational finality')}return S.remedyOffice61}
function latestUltra(id=S.active){return [...(S.treatyCases60||[])].filter(c=>c.claimant===id&&c.decision==='ultra-vires'&&!S.remedyAwards61.some(a=>a.sourceCaseId===c.id)).sort((a,b)=>(b.decided||b.created)-(a.decided||a.created))[0]||null}
function latestCompletedWithdrawal(id=S.active){return [...(S.treatyWithdrawals60||[])].filter(w=>w.reality===id&&w.status==='completed'&&!S.remedyAwards61.some(a=>a.sourceWithdrawalId===w.id)).sort((a,b)=>(b.completed||b.created)-(a.completed||a.created))[0]||null}
function estimateCaseAward(c){let m=motion61(c?.motionId),p=(S.stabilizationPrograms58||[]).find(p=>p.id===m?.programId);if(m?.type==='release-tranche')return Math.max(1,Math.min(3,p?.disbursed||3));if(m?.type==='tighten-conditionality'||m?.type==='soften-conditionality')return 2;if(m?.override)return 2.5;return 1.5}
function issueCaseAward(id=S.active,manual=true){ensureOffice();let c=latestUltra(id);if(!c){if(manual)$('#msg').textContent='No unremedied ultra-vires treaty judgment exists for Reality '+id+'.';return null}let amount=estimateCaseAward(c),a={id:'AWD'+(++S.remedySerial61),kind:'treaty-restitution',claimant:id,respondent:'fund',sourceCaseId:c.id,sourceMotionId:c.motionId,sourceWithdrawalId:null,currency:foreignCode(id),amount,paid:0,status:'issued',recognition:'pending',immunity:'not-applicable',lien:false,baselineReserves:null,created:Date.now(),x:10+Math.random()*80,y:12+Math.random()*68};S.remedyAwards61.push(a);S.remedyAwardsIssued61++;c.remedyAward61=a.id;remember('RESTITUTION AWARD '+a.id+': '+c.id+' converted ultra-vires invalidity into '+amount.toFixed(1)+' '+a.currency+' of compensation without undoing '+c.motionId,realm(id));trust61(id,'treaty-restitution-award',a.id+' from '+c.id+' amount '+amount.toFixed(1)+' '+a.currency);if(typeof place==='function')place('dream','invalid decision survived beside a valid compensation order',realm(id));if(manual){$('#msg').textContent=a.id+' issued for '+amount.toFixed(1)+' '+a.currency+'. The original board act still stands.';renderAll();save61();openAward(a)}return a}
function issueDebtAward(id=S.active,manual=true){ensureOffice();let w=latestCompletedWithdrawal(id),acct=acct61(id);if(!w||!(acct?.externalDebt>0)){if(manual)$('#msg').textContent='Reality '+id+' has no completed treaty withdrawal with surviving external debt available for registration.';return null}let amount=Math.max(0,acct.externalDebt||w.externalDebtAfter||0),a={id:'AWD'+(++S.remedySerial61),kind:'surviving-debt',claimant:other(id),respondent:id,sourceCaseId:null,sourceMotionId:null,sourceWithdrawalId:w.id,currency:foreignCode(id),amount,paid:0,status:'issued',recognition:'pending',immunity:'reserve-stock-protected',lien:false,baselineReserves:currency61(id)?.foreignReserves||0,created:Date.now(),x:10+Math.random()*80,y:12+Math.random()*68};S.remedyAwards61.push(a);S.remedyAwardsIssued61++;w.remedyAward61=a.id;remember('SURVIVING DEBT AWARD '+a.id+': Article VII withdrawal ended membership but registered '+amount.toFixed(1)+' of Reality '+id+' external debt for post-withdrawal enforcement',realm(id));if(typeof place==='function')place('cold','left the institution but the creditor kept an address',realm(id));remedyCrisis(id,'withdrawal became a post-membership debt docket');if(manual){$('#msg').textContent=a.id+' registered '+amount.toFixed(1)+' of surviving debt. Existing reserve stock remains immune unless separately waived.';renderAll();save61();openAward(a)}return a}
function recognizeAward(a,manual=true){ensureOffice();if(!a||a.recognition==='recognized')return a;if(a.status==='satisfied')return a;let reason='';if(a.kind==='treaty-restitution'){a.recognition='recognized';reason='tribunal ultra-vires judgment is final for remedial purposes'}else{let w=withdrawal61(a.sourceWithdrawalId),art=(S.treatyArticles60||[]).find(x=>x.key==='withdrawal');if(w?.status==='completed'&&art?.status==='active'){a.recognition='recognized';a.lien=true;reason='Article VII preserves accrued obligations after withdrawal'}else{a.recognition='refused';reason='no surviving Article VII basis';S.remedyAwardsRefused61++}}
let r={id:'REC'+(++S.remedyRecognitionSerial61),awardId:a.id,result:a.recognition,reason,created:Date.now(),x:10+Math.random()*80,y:12+Math.random()*68};S.remedyRecognitions61.push(r);if(a.recognition==='recognized'){S.remedyAwardsRecognized61++;remember('RECOGNITION '+r.id+': '+a.id+' recognized because '+reason,realm(a.respondent==='fund'?a.claimant:a.respondent));trust61(a.claimant,'treaty-award-recognized',a.id+' '+reason);if(a.kind==='surviving-debt'){remedyCrisis(a.respondent,'jurisdiction followed accrued debt beyond treaty membership');if(typeof place==='function')place('dream','treaty exit with a court order attached',realm(a.respondent))}}else remember('RECOGNITION REFUSED '+r.id+': '+a.id+' · '+reason,realm(a.respondent==='fund'?a.claimant:a.respondent));if(manual){$('#msg').textContent=a.id+' recognition '+a.recognition.toUpperCase()+'. '+reason+'.';renderAll();save61();openAward(a)}return a}
function fundPool(a){let f=fund61();if(!f)return 0;return a.currency==='RA'?(f.poolRA||0):(f.poolRB||0)}
function changeFundPool(a,delta){let f=fund61();if(!f)return;if(a.currency==='RA')f.poolRA=Math.max(0,(f.poolRA||0)+delta);else f.poolRB=Math.max(0,(f.poolRB||0)+delta)}
function recordExecution(a,amount,mode,note){if(amount<=0)return null;let e={id:'EXE'+(++S.remedyExecutionSerial61),awardId:a.id,amount,mode,note,created:Date.now(),x:10+Math.random()*80,y:12+Math.random()*68};S.remedyExecutions61.push(e);a.paid=cl((a.paid||0)+amount,0,a.amount);S.remedyPaid61+=amount;if(a.paid+1e-9>=a.amount){a.status='satisfied';a.lien=false;S.remedyAwardsSatisfied61++;remember('AWARD SATISFIED '+a.id+': '+a.amount.toFixed(1)+' paid while the underlying history remained unchanged',realm(a.respondent==='fund'?a.claimant:a.respondent));if(typeof place==='function')place('warm','compensation completed after causality had already moved on',realm(a.respondent==='fund'?a.claimant:a.respondent))}else a.status='partially-satisfied';return e}
function executeAward(a,manual=true){ensureOffice();if(!a)return null;if(a.recognition!=='recognized'){if(manual)$('#msg').textContent=a.id+' must be recognized before execution.';return null}if(a.status==='satisfied'){if(manual)openAward(a);return null}let due=Math.max(0,a.amount-(a.paid||0)),paid=0,note='';if(a.kind==='treaty-restitution'){paid=Math.min(due,fundPool(a));if(paid>0){changeFundPool(a,-paid);let c=currency61(a.claimant);if(c)c.foreignReserves=(c.foreignReserves||0)+paid;note='fund reserve pool paid restitution into claimant foreign reserves';recordExecution(a,paid,'fund-restitution',note)}else note='fund pool lacks reserves; award remains unpaid'}else{note='existing sovereign reserve stock is immune; recognized award attaches only to later foreign-reserve inflows';a.lien=true;a.baselineReserves=currency61(a.respondent)?.foreignReserves||a.baselineReserves||0;remedyCrisis(a.respondent,'sovereign immunity protected today\'s reserves but not tomorrow\'s inflows')}
if(manual){$('#msg').textContent=paid>0?a.id+' executed '+paid.toFixed(1)+' '+a.currency+'. The original treaty decision was not rolled back.':a.id+' remains enforceable. '+note+'.';renderAll();save61();openAward(a)}return paid}
function waiveImmunity(a,manual=true){if(!a||a.kind!=='surviving-debt'||a.recognition!=='recognized')return false;let c=currency61(a.respondent),acct=acct61(a.respondent),due=Math.max(0,a.amount-(a.paid||0)),available=c?.foreignReserves||0,paid=Math.min(due,available);a.immunity='waived';if(paid>0){c.foreignReserves=Math.max(0,available-paid);if(acct)acct.externalDebt=Math.max(0,(acct.externalDebt||0)-paid);recordExecution(a,paid,'immunity-waiver','respondent waived reserve immunity and allowed immediate attachment');S.remedyGarnishments61++;remember('IMMUNITY WAIVER '+a.id+': Reality '+a.respondent+' allowed '+paid.toFixed(1)+' '+a.currency+' of reserves to satisfy surviving debt',realm(a.respondent))}if(manual){$('#msg').textContent=paid>0?'Reality '+a.respondent+' waived immunity; '+paid.toFixed(1)+' '+a.currency+' attached.':'Immunity was waived, but no attachable reserves are available.';renderAll();save61();openAward(a)}return paid>0}
function garnishFutureInflows(a){if(!a||a.kind!=='surviving-debt'||a.recognition!=='recognized'||!a.lien||a.status==='satisfied')return 0;let c=currency61(a.respondent),acct=acct61(a.respondent);if(!c)return 0;let now=c.foreignReserves||0,base=a.baselineReserves??now;if(now<=base+.01){a.baselineReserves=now;return 0}let inflow=now-base,due=Math.max(0,a.amount-(a.paid||0)),take=Math.min(due,inflow*.35);a.baselineReserves=now-take;if(take<=.01)return 0;c.foreignReserves=Math.max(0,now-take);if(acct)acct.externalDebt=Math.max(0,(acct.externalDebt||0)-take);recordExecution(a,take,'future-inflow-garnishment','recognized post-withdrawal lien captured thirty-five percent of new foreign-reserve inflow');S.remedyGarnishments61++;remember('RESERVE GARNISHMENT '+a.id+': '+take.toFixed(2)+' '+a.currency+' attached from a new post-withdrawal reserve inflow',realm(a.respondent));if(typeof place==='function')place('cold','future reserve inflow arrived already owing the past',realm(a.respondent));remedyCrisis(a.respondent,'old debt attached itself to new reserves','SEV1');return take}
function reconcileRemedies(){ensureOffice();for(const a of S.remedyAwards61){if(a.kind==='surviving-debt'&&a.recognition==='recognized'&&a.lien)garnishFutureInflows(a)}}
function openExecution(e){let a=S.remedyAwards61.find(a=>a.id===e.awardId);panel(e.id+' · EXECUTION',e.mode.toUpperCase(),e.amount.toFixed(2)+' transferred · '+e.note,[['open '+e.awardId,()=>openAward(a)],['close',closePanel]])}
function openAward(a){let src=a.sourceCaseId?'case '+a.sourceCaseId:a.sourceWithdrawalId?'withdrawal '+a.sourceWithdrawalId:'',acts=[];if(a.recognition==='pending')acts.push(['seek recognition',()=>recognizeAward(a,true)]);if(a.recognition==='recognized'&&a.status!=='satisfied')acts.push(['execute award',()=>executeAward(a,true)]);if(a.kind==='surviving-debt'&&a.recognition==='recognized'&&a.status!=='satisfied'&&a.immunity!=='waived')acts.push(['waive reserve immunity',()=>waiveImmunity(a,true)]);for(const e of S.remedyExecutions61.filter(e=>e.awardId===a.id).slice(-3))acts.push(['open '+e.id+' · '+e.amount.toFixed(2),()=>openExecution(e)]);acts.push(['open remedies office',openOffice],['close',closePanel]);panel(a.id+' · '+a.kind.toUpperCase(),a.status.toUpperCase()+' · '+a.recognition.toUpperCase(),src+' · claimant '+a.claimant+' · respondent '+a.respondent+' · '+(a.paid||0).toFixed(2)+' / '+a.amount.toFixed(2)+' '+a.currency+' paid · immunity '+a.immunity+(a.lien?' · future-inflow lien active':''),acts)}
function openOffice(){ensureOffice();let o=S.remedyOffice61,acts=[['petition from latest ultra-vires judgment',()=>issueCaseAward(S.active,true)],['register surviving debt after withdrawal',()=>issueDebtAward(S.active,true)]];for(const a of S.remedyAwards61.slice(-6))acts.push(['open '+a.id+' · '+a.kind+' · '+a.status,()=>openAward(a)]);acts.push(['close',closePanel]);panel(o.name,o.status.toUpperCase()+' · '+o.id,S.remedyAwards61.length+' awards · '+S.remedyAwardsRecognized61+' recognized · '+S.remedyAwardsSatisfied61+' satisfied · '+S.remedyGarnishments61+' garnishments · '+S.remedyPaid61.toFixed(1)+' paid · '+S.remedyCrises61+' crises',acts)}
function autonomous(){ensureOffice();let now=Date.now();if(now-S.lastRemedyTick61<2100)return;S.lastRemedyTick61=now;reconcileRemedies();let c=latestUltra(S.active);if(c&&Math.random()<.0012)issueCaseAward(S.active,false);let w=latestCompletedWithdrawal(S.active);if(w&&Math.random()<.001)issueDebtAward(S.active,false);let p=S.remedyAwards61.find(a=>a.recognition==='pending');if(p&&Math.random()<.0015)recognizeAward(p,false)}
function renderRemedies(){ensureOffice();let layer=$('#remedyLayer');if(!layer){layer=document.createElement('div');layer.id='remedyLayer';document.body.appendChild(layer)}layer.innerHTML='';let o=S.remedyOffice61,oe=document.createElement('i');oe.className='remedyOffice';oe.dataset.label='REMEDY';oe.style.left=o.x+'%';oe.style.top=o.y+'%';oe.onclick=openOffice;layer.appendChild(oe);for(const a of S.remedyAwards61.slice(-10)){let e=document.createElement('i');e.className='remedyAward '+a.kind+' '+a.status+(a.recognition==='recognized'?' recognized':'');e.dataset.label=a.kind==='surviving-debt'?'LIEN':'§$';e.style.left=a.x+'%';e.style.top=a.y+'%';e.onclick=()=>openAward(a);layer.appendChild(e)}for(const e0 of S.remedyExecutions61.slice(-8)){let e=document.createElement('i');e.className='remedyExecution '+e0.mode;e.dataset.label='$';e.style.left=e0.x+'%';e.style.top=e0.y+'%';e.onclick=()=>openExecution(e0);layer.appendChild(e)}let line=$('#remedyline');if(!line){line=document.createElement('div');line.id='remedyline';line.className='line';($('#treatyline')||$('#fundgovernanceline')||$('#stabilizationline')||$('#enforcement')).after(line)}line.textContent='treaty remedies: '+S.remedyAwards61.length+' awards · '+S.remedyAwardsRecognized61+' recognized · '+S.remedyAwardsSatisfied61+' satisfied · '+S.remedyGarnishments61+' future-inflow garnishments · '+S.remedyPaid61.toFixed(1)+' paid · '+S.remedyCrises61+' crises';let ctr=document.querySelector('#app .controls');if(ctr&&!$('#openRemediesButton')){let x=document.createElement('button');x.id='openRemediesButton';x.textContent='open remedies office';x.onclick=openOffice;ctr.prepend(x)}if(ctr&&!$('#petitionRemedyButton')){let x=document.createElement('button');x.id='petitionRemedyButton';x.textContent='petition for treaty remedy';x.onclick=()=>issueCaseAward(S.active,true);ctr.prepend(x)}}
renderAll=function(){BR61();reconcileRemedies();renderRemedies()};let f=$('#forget');if(f)f.onclick=()=>{for(let i=2;i<=61;i++)localStorage.removeItem('nothing-state-v'+i);location.reload()};
setInterval(()=>{autonomous();renderRemedies();save61()},2300);ensureOffice();reconcileRemedies();renderAll();save61();
})();
