(()=>{
const B76=save,R76=renderAll,O=JSON.parse(localStorage.getItem('nothing-state-v76')||'null')||{},K=['replenishmentOffice76','replenishmentAssessments76','replenishmentPayments76','replenishmentSerial76','replenishmentPaymentSerial76','replenishmentRequests76','replenishmentVotes76','replenishmentPaid76','replenishmentArrears76','replenishmentMajorityReversals76','replenishmentTargetMajorities76','replenishmentReserveStress76','replenishmentCrises76','replenishmentKeys76','lastReplenishmentTick76'];
for(const k of K)S[k]=O[k]??(/Serial|Requests|Votes|Paid|Arrears|Reversals|Majorities|Stress|Crises|Tick/.test(k)?0:/Keys/.test(k)?{}:/Office/.test(k)?null:[]);
function save76(){B76();let o={};for(const k of K)o[k]=S[k];localStorage.setItem('nothing-state-v76',JSON.stringify(o))}save=save76;
const q=s=>$(s),realm=id=>S.real[id],fund58=()=>S.stabilizationFunds58?.[0],board59=()=>S.fundBoards59?.[0],quota=id=>(S.stabilizationQuotas58||[]).find(x=>x.reality===id),director=id=>(S.fundDirectors59||[]).find(x=>x.reality===id),cur=id=>(S.fxCurrencies56||[]).find(x=>x.reality===id),acct=id=>(S.tradeAccounts57||[]).find(x=>x.reality===id),foreign=id=>'R'+(id==='A'?'B':'A');
function trust(id,status,note){S.trustAudits=S.trustAudits||[];S.trustAuditSerial=S.trustAuditSerial||0;S.trustAudits.push({id:'TA'+(++S.trustAuditSerial),reality:id,status,created:Date.now(),note,x:10+Math.random()*80,y:12+Math.random()*68})}
function incident(id,title,sev='SEV1'){S.incidents=S.incidents||[];S.incidentSerial=S.incidentSerial||0;let ex=S.incidents.find(x=>x.reality===id&&x.title===title&&x.status==='open');if(ex)return ex;let i={id:'INC'+(++S.incidentSerial),reality:id,title,severity:sev,status:'open',started:Date.now(),owner:'stabilization replenishment assessment office',x:10+Math.random()*80,y:12+Math.random()*68};S.incidents.push(i);return i}
function crisis(id,why,sev='SEV1'){let n=Date.now(),k=id+'|'+why;if(S.replenishmentKeys76[k]&&n-S.replenishmentKeys76[k]<14000)return;S.replenishmentKeys76[k]=n;S.replenishmentCrises76++;remember('REPLENISHMENT CRISIS: '+why+' turned creditor control into a compulsory reserve subscription',realm(id));if(typeof place==='function'){place('cold','majority creditor ordering the bailout target to refill the institution',realm(id));place('dream','forced reserve payment buying back the votes that imposed it',realm(id))}incident(id,'stabilization replenishment crisis: '+why,sev)}
function ensure(){if(!S.lossQuotaOffice75||!fund58()||!board59())return null;if(!S.replenishmentOffice76){S.replenishmentOffice76={id:'SRA1',name:'Interreality Stabilization Replenishment Authority',status:'assessing',created:Date.now(),x:50,y:99.993};remember('REPLENISHMENT SRA1: loss-born stabilization majorities acquired compulsory capital-call authority',realm('A'));remember('REPLENISHMENT SRA1: loss-born stabilization majorities acquired compulsory capital-call authority',realm('B'));trust('A','stabilization-replenishment-authority-created','SRA1');trust('B','stabilization-replenishment-authority-created','SRA1')}return S.replenishmentOffice76}
function exposure(id){return(S.stabilizationPrograms58||[]).filter(p=>p.reality===id).reduce((n,p)=>n+(p.disbursed||0),0)}
function score(id){let z=quota(id),c=cur(id),a=acct(id),contrib=(z?.contributedRA||0)+(z?.contributedRB||0),exports=Math.max(0,a?.exports||0),borrow=exposure(id),rdr=z?.rdr||0;return Math.max(2,(z?.quota||10)+contrib*.35+(c?.foreignReserves||0)*.16+exports*.025-rdr*.08-borrow*.18)}
function refreshVotes(){let a=score('A'),b=score('B'),total=a+b||1,out={A:100*a/total,B:100*b/total};for(const id of ['A','B']){let z=quota(id),d=director(id);if(z)z.votes=out[id];if(d)d.votes=out[id]}return out}
function threshold(){return(board59()?.majority||.6)*100}
function creditById(id){return(S.lossQuotaCredits75||[]).find(x=>x.id===id)||null}
function assessmentByCredit(id){return(S.replenishmentAssessments76||[]).find(x=>x.creditId75===id)||null}
function motionFor(a){return(S.fundMotions59||[]).find(x=>x.id===a.motionId59)||null}
function poolCodeForTarget(id){return foreign(id)}
function addPool(code,x){let f=fund58();if(!f)return;if(code==='RA')f.poolRA=(f.poolRA||0)+x;else f.poolRB=(f.poolRB||0)+x}
function addContribution(id,code,x){let z=quota(id);if(!z)return;if(code==='RA')z.contributedRA=(z.contributedRA||0)+x;else z.contributedRB=(z.contributedRB||0)+x;z.quota=(z.quota||10)+x}
function recoverFromMarker(c){if(!c?.assessmentId76||assessmentByCredit(c.id))return null;let a={id:c.assessmentId76,creditId75:c.id,transferId74:c.transferId74,targetReality:c.targetReality,creditorReality:c.burdenReality,currency:c.assessmentCurrency76||poolCodeForTarget(c.targetReality),amount:c.assessmentAmount76||c.amount||0,paid:c.assessmentPaid76||0,outstanding:Math.max(0,(c.assessmentAmount76||c.amount||0)-(c.assessmentPaid76||0)),status:c.assessmentStatus76||((c.assessmentPaid76||0)>0?'arrears':'pending-vote'),motionId59:c.assessmentMotionId59||null,created:c.assessmentCreated76||c.created||Date.now(),x:c.x||10+Math.random()*80,y:c.y||12+Math.random()*68,recovered:true};S.replenishmentAssessments76.push(a);S.replenishmentRequests76++;S.replenishmentPaid76+=a.paid;if(a.status==='arrears')S.replenishmentArrears76++;let n=Number(String(a.id).replace(/\D/g,''))||0;if(n>S.replenishmentSerial76)S.replenishmentSerial76=n;return a}
function eligibleCredits(){refreshVotes();let need=threshold();return(S.lossQuotaCredits75||[]).filter(c=>!c.assessmentId76&&!assessmentByCredit(c.id)&&(c.amount||0)>.01&&['A','B'].includes(c.burdenReality)&&['A','B'].includes(c.targetReality)&&(director(c.burdenReality)?.votes||0)+1e-9>=need)}
function makeMotion(a){let b=board59();S.fundMotions59=S.fundMotions59||[];S.fundMotionSerial59=S.fundMotionSerial59||0;let m={id:'MOT'+(++S.fundMotionSerial59),boardId:b.id,type:'reserve-replenishment76',label:'assess Reality '+a.targetReality+' to replenish stabilization reserves',programId:null,targetReality:a.targetReality,status:'pending-assessment76',threshold:b.majority||.6,votes:{},yesWeight:0,noWeight:0,recused:[a.targetReality],created:Date.now(),decided:null,override:false,replenishment76:true,assessmentId76:a.id,creditId75:a.creditId75,requested76:a.amount,x:10+Math.random()*80,y:12+Math.random()*68};S.fundMotions59.push(m);a.motionId59=m.id;let c=creditById(a.creditId75);if(c)c.assessmentMotionId59=m.id;return m}
function requestAssessment(c,manual=true){ensure();if(!c)return null;let existing=assessmentByCredit(c.id)||recoverFromMarker(c);if(existing)return existing;let votes=refreshVotes(),need=threshold(),creditor=c.burdenReality,target=c.targetReality;if((votes[creditor]||0)+1e-9<need){if(manual&&q('#msg'))q('#msg').textContent='Reality '+creditor+' no longer has the '+need.toFixed(0)+'% votes required to impose this assessment.';return null}let a={id:'SRA'+(++S.replenishmentSerial76),creditId75:c.id,transferId74:c.transferId74,targetReality:target,creditorReality:creditor,currency:poolCodeForTarget(target),amount:Math.max(0,c.amount||0),paid:0,outstanding:Math.max(0,c.amount||0),status:'pending-vote',created:Date.now(),x:10+Math.random()*80,y:12+Math.random()*68};S.replenishmentAssessments76.push(a);S.replenishmentRequests76++;c.assessmentId76=a.id;c.assessmentAmount76=a.amount;c.assessmentCurrency76=a.currency;c.assessmentCreated76=a.created;c.assessmentStatus76=a.status;let m=makeMotion(a);remember('REPLENISHMENT ASSESSMENT '+a.id+': Reality '+creditor+' used '+votes[creditor].toFixed(1)+'% loss-born voting power to assess Reality '+target+' '+a.amount.toFixed(2)+' '+a.currency,realm(target));trust(target,'stabilization-replenishment-assessed',a.id+' '+a.amount.toFixed(2)+' '+a.currency);if(manual){q('#msg').textContent=a.id+' sent '+m.id+' to the stabilization board. Reality '+target+' is recused.';renderAll();save76();openAssessment(a)}return a}
function voteAssessment(a,manual=true){if(!a||!['pending-vote','deadlocked'].includes(a.status))return null;let m=motionFor(a),votes=refreshVotes(),need=threshold();if(!m)return null;m.votes={};m.yesWeight=0;m.noWeight=0;for(const d of(S.fundDirectors59||[]).filter(x=>x.status==='active')){let v=d.reality===a.targetReality?'recused':d.reality===a.creditorReality?'yes':'no';m.votes[d.reality]=v;if(v==='yes')m.yesWeight+=d.votes||0;if(v==='no')m.noWeight+=d.votes||0}S.boardVotes59=(S.boardVotes59||0)+1;S.replenishmentVotes76++;if(m.yesWeight+1e-9>=need){m.status='passed-assessment76';m.decided=Date.now();a.status='approved';let c=creditById(a.creditId75);if(c)c.assessmentStatus76=a.status;collectAssessment(a,false)}else if(m.noWeight>100-need+1e-9){m.status='rejected-assessment76';m.decided=Date.now();a.status='rejected';let c=creditById(a.creditId75);if(c)c.assessmentStatus76=a.status}else{m.status='deadlocked-assessment76';m.decided=Date.now();a.status='deadlocked';let c=creditById(a.creditId75);if(c)c.assessmentStatus76=a.status;S.boardDeadlocks59=(S.boardDeadlocks59||0)+1;board59().deadlocks=(board59().deadlocks||0)+1;remember('REPLENISHMENT DEADLOCK '+m.id+': creditor '+a.creditorReality+' had only '+m.yesWeight.toFixed(1)+' yes votes after quota shifted',realm(a.targetReality));crisis(a.targetReality,'the creditor majority disappeared before its replenishment assessment could pass','SEV2')}if(manual){q('#msg').textContent=m.id+' '+m.status.toUpperCase()+' · yes '+m.yesWeight.toFixed(1)+' / no '+m.noWeight.toFixed(1)+'.';renderAll();save76();openAssessment(a)}return m}
function collectAssessment(a,manual=true){if(!a||!['approved','arrears'].includes(a.status)||(a.outstanding||0)<=.001)return 0;let c=cur(a.targetReality),z=quota(a.targetReality),f=fund58();if(!c||!z||!f){a.status='blocked-record';return 0}let before=refreshVotes(),avail=Math.max(0,c.foreignReserves||0),pay=Math.min(avail,Math.max(0,a.outstanding||0));if(pay<=.001){if(a.status!=='arrears'){a.status='arrears';S.replenishmentArrears76++;let cr=creditById(a.creditId75);if(cr)cr.assessmentStatus76=a.status}crisis(a.targetReality,'mandatory replenishment assessment found no foreign reserves to seize','SEV1');if(manual){q('#msg').textContent=a.id+' is in arrears; Reality '+a.targetReality+' has no '+a.currency+' reserves available.';renderAll();save76();openAssessment(a)}return 0}c.foreignReserves=Math.max(0,avail-pay);addPool(a.currency,pay);addContribution(a.targetReality,a.currency,pay);a.paid=(a.paid||0)+pay;a.outstanding=Math.max(0,(a.outstanding||0)-pay);S.replenishmentPaid76+=pay;let after=refreshVotes(),p={id:'SRP'+(++S.replenishmentPaymentSerial76),assessmentId76:a.id,creditId75:a.creditId75,targetReality:a.targetReality,creditorReality:a.creditorReality,currency:a.currency,amount:pay,reservesBefore:avail,reservesAfter:c.foreignReserves,poolAfter:a.currency==='RA'?f.poolRA:f.poolRB,quotaAfter:z.quota,votesBefore:before,votesAfter:after,created:Date.now(),x:10+Math.random()*80,y:12+Math.random()*68};S.replenishmentPayments76.push(p);let cr=creditById(a.creditId75);if(cr){cr.assessmentPaid76=(cr.assessmentPaid76||0)+pay;cr.assessmentPaidAt76=p.created}
let need=threshold();if((before[a.creditorReality]||0)+1e-9>=need&&(after[a.creditorReality]||0)+1e-9<need){S.replenishmentMajorityReversals76++;a.reversedCreditorMajority76=true;remember('ASSESSMENT MAJORITY REVERSAL '+a.id+': Reality '+a.creditorReality+' fell '+before[a.creditorReality].toFixed(1)+'%→'+after[a.creditorReality].toFixed(1)+'% after Reality '+a.targetReality+' bought quota by paying the assessment',realm(a.targetReality));crisis(a.targetReality,'forced replenishment payment destroyed the creditor majority that imposed it','SEV1')}if((before[a.targetReality]||0)<need&&(after[a.targetReality]||0)+1e-9>=need){S.replenishmentTargetMajorities76++;a.createdTargetMajority76=true;remember('ASSESSED-MEMBER MAJORITY '+a.id+': Reality '+a.targetReality+' crossed '+need.toFixed(0)+'% after mandatory reserve payment',realm(a.targetReality))}
if(c.foreignReserves<2.5){S.replenishmentReserveStress76++;a.reserveStress76=true;crisis(a.targetReality,'mandatory quota assessment exhausted the target reality foreign reserves','SEV1')}
if(a.outstanding<=.001){a.outstanding=0;a.status='paid';a.paidAt=Date.now();let m=motionFor(a);if(m&&m.status==='passed-assessment76')m.status='implemented-assessment76'}else{if(a.status!=='arrears')S.replenishmentArrears76++;a.status='arrears'}if(cr){cr.assessmentStatus76=a.status;cr.assessmentPaid76=a.paid}
remember('REPLENISHMENT PAYMENT '+p.id+': Reality '+a.targetReality+' transferred '+pay.toFixed(2)+' '+a.currency+' reserves into the fund and received equal quota',realm(a.targetReality));if(typeof place==='function'){place('cold','foreign reserves seized by the institution and returned as voting capital',realm(a.targetReality));place('dream','debtor paying an assessment that makes the creditor less dominant',realm(a.targetReality))}trust(a.targetReality,'stabilization-replenishment-paid',p.id+' '+pay.toFixed(2)+' '+a.currency);if(manual){q('#msg').textContent=p.id+' collected '+pay.toFixed(2)+' '+a.currency+'; '+a.outstanding.toFixed(2)+' remains.';renderAll();save76();openAssessment(a)}return pay}
function reconcile(){if(!ensure())return false;let changed=false;for(const c of(S.lossQuotaCredits75||[])){let before=S.replenishmentAssessments76.length,a=recoverFromMarker(c);if(a&&S.replenishmentAssessments76.length>before)changed=true}return changed}
function openPayment(p){panel(p.id+' · REPLENISHMENT PAYMENT',p.amount.toFixed(2)+' '+p.currency,'Reality '+p.targetReality+' reserves '+p.reservesBefore.toFixed(2)+' → '+p.reservesAfter.toFixed(2)+' · pool '+p.poolAfter.toFixed(2)+' · target quota '+p.quotaAfter.toFixed(2)+' · creditor votes '+p.votesBefore[p.creditorReality].toFixed(1)+'% → '+p.votesAfter[p.creditorReality].toFixed(1)+'%',[['close',closePanel]])}
function openAssessment(a){let m=motionFor(a),c=cur(a.targetReality),z=quota(a.targetReality),acts=[];if(a.status==='pending-vote'||a.status==='deadlocked')acts.push(['vote replenishment assessment',()=>voteAssessment(a,true)]);if(a.status==='arrears'||a.status==='approved')acts.push(['collect available reserves',()=>collectAssessment(a,true)]);for(const p of S.replenishmentPayments76.filter(p=>p.assessmentId76===a.id).slice(-4))acts.push(['open '+p.id,()=>openPayment(p)]);acts.push(['close',closePanel]);panel(a.id+' · REPLENISHMENT ASSESSMENT',a.status.toUpperCase(),'creditor Reality '+a.creditorReality+' → target Reality '+a.targetReality+' · '+a.amount.toFixed(2)+' '+a.currency+' assessed · '+(a.paid||0).toFixed(2)+' paid · '+(a.outstanding||0).toFixed(2)+' outstanding · target reserves '+(c?.foreignReserves||0).toFixed(2)+' · target quota '+(z?.quota||0).toFixed(2)+' · motion '+(m?.id||'missing')+' '+(m?.status||'missing')+(a.reversedCreditorMajority76?' · CREDITOR MAJORITY REVERSED':''),acts)}
function openOffice(){if(!ensure())return;let votes=refreshVotes(),acts=[];for(const c of eligibleCredits().slice(-6))acts.push(['assess '+c.id+' · R'+c.targetReality+' '+c.amount.toFixed(2),()=>requestAssessment(c,true)]);for(const a of S.replenishmentAssessments76.slice(-8))acts.push(['open '+a.id+' · '+a.status,()=>openAssessment(a)]);for(const p of S.replenishmentPayments76.slice(-5))acts.push(['open '+p.id+' · '+p.amount.toFixed(2)+' '+p.currency,()=>openPayment(p)]);acts.push(['close',closePanel]);panel(S.replenishmentOffice76.name,'ASSESSING · SRA1',S.replenishmentRequests76+' assessments · '+S.replenishmentPaid76.toFixed(2)+' reserves replenished · '+S.replenishmentArrears76+' arrears · '+S.replenishmentMajorityReversals76+' creditor-majority reversals · votes A '+votes.A.toFixed(1)+'% / B '+votes.B.toFixed(1)+'%',acts)}
function requestInteresting(){let c=eligibleCredits()[0];if(!c){q('#msg').textContent='No unassessed loss-quota credit is backed by a current 60% creditor majority.';return null}return requestAssessment(c,true)}
function render76(){if(!ensure())return;let layer=q('#replenishmentLayer76');if(!layer){layer=document.createElement('div');layer.id='replenishmentLayer76';document.body.appendChild(layer)}layer.innerHTML='';let o=document.createElement('i');o.className='replenishmentOffice76';o.dataset.label='CALL';o.style.left='50%';o.style.top='99.994%';o.onclick=openOffice;layer.appendChild(o);for(const a of S.replenishmentAssessments76.filter(x=>!['paid','rejected'].includes(x.status)).slice(-8)){let e=document.createElement('i');e.className='replenishmentAssessment76 '+a.status;e.dataset.label='A$';e.style.left=a.x+'%';e.style.top=a.y+'%';e.onclick=()=>openAssessment(a);layer.appendChild(e)}for(const p of S.replenishmentPayments76.slice(-6)){let e=document.createElement('i');e.className='replenishmentPayment76';e.dataset.label='↑';e.style.left=p.x+'%';e.style.top=p.y+'%';e.onclick=()=>openPayment(p);layer.appendChild(e)}let v=refreshVotes(),line=q('#replenishmentline76');if(!line){line=document.createElement('div');line.id='replenishmentline76';line.className='line';(q('#lossquotaline75')||q('#fundgovernanceline')||q('#stabilizationline')||q('#enforcement')).after(line)}line.textContent='replenishment: '+S.replenishmentPaid76.toFixed(1)+' reserves paid · '+S.replenishmentArrears76+' arrears · '+S.replenishmentMajorityReversals76+' majority reversals · A '+v.A.toFixed(1)+'% / B '+v.B.toFixed(1)+'%';let ctr=document.querySelector('#app .controls');if(ctr&&!q('#openReplenishment76')){let x=document.createElement('button');x.id='openReplenishment76';x.textContent='open replenishment assessments';x.onclick=openOffice;ctr.prepend(x)}if(ctr&&!q('#requestReplenishment76')){let x=document.createElement('button');x.id='requestReplenishment76';x.textContent='issue reserve assessment';x.onclick=requestInteresting;ctr.prepend(x)}}
renderAll=function(){R76();let changed=reconcile();render76();if(changed)save76()};let f=q('#forget');if(f)f.onclick=()=>{for(let i=2;i<=76;i++)localStorage.removeItem('nothing-state-v'+i);location.reload()};setInterval(()=>{reconcile();render76();save76()},2300);ensure();reconcile();renderAll();save76();
})();