(()=>{
const B98=save,R98=renderAll,O=JSON.parse(localStorage.getItem('nothing-state-v98')||'null')||{},RECOVER98=!Array.isArray(O.reserveRestitutions98),K=['reserveRestitutionOffice98','reserveRestitutions98','reserveRestitutionSerial98','reserveRestitutionAmount98','reserveRestitutionRecoveries98','reserveRestitutionCrises98','reserveRestitutionKeys98','lastReserveRestitutionTick98'];
for(const k of K)S[k]=O[k]??(k==='reserveRestitutions98'?[]:/Serial|Amount|Recoveries|Crises|Tick/.test(k)?0:/Keys/.test(k)?{}:/Office/.test(k)?null:[]);
function save98(){B98();let o={};for(const k of K)o[k]=S[k];localStorage.setItem('nothing-state-v98',JSON.stringify(o))}save=save98;
const q=s=>$(s),EPS=.0001,realm=id=>S.real[id],fund58=()=>S.stabilizationFunds58?.[0],quota58=id=>(S.stabilizationQuotas58||[]).find(q=>q.reality===id),payment97=id=>(S.preferredRecoupmentPayments97||[]).find(p=>p.id===id),claim97=id=>(S.preferredRecoupmentClaims97||[]).find(c=>c.id===id),other=id=>id==='A'?'B':'A';
function trust(id,status,note){S.trustAudits=S.trustAudits||[];S.trustAuditSerial=S.trustAuditSerial||0;S.trustAudits.push({id:'TA'+(++S.trustAuditSerial),reality:id,status,created:Date.now(),note,x:10+Math.random()*80,y:12+Math.random()*68})}
function incident(id,title,sev='SEV2'){S.incidents=S.incidents||[];S.incidentSerial=S.incidentSerial||0;let ex=S.incidents.find(x=>x.reality===id&&x.title===title&&x.status==='open');if(ex)return ex;let i={id:'INC'+(++S.incidentSerial),reality:id,title,severity:sev,status:'open',started:Date.now(),owner:'reserve restitution register',x:10+Math.random()*80,y:12+Math.random()*68};S.incidents.push(i);return i}
function crisis(id,why,key,sev='SEV2'){let n=Date.now(),k=id+'|'+key;if(S.reserveRestitutionKeys98[k]&&n-S.reserveRestitutionKeys98[k]<14000)return;S.reserveRestitutionKeys98[k]=n;S.reserveRestitutionCrises98++;remember('RESERVE RESTITUTION: '+why+' turned repaid recapitalization into a restored drawing-right claim on the stabilization pool',realm(id));if(typeof place==='function'){place('cold','repaid bailout reserve reappearing as a creditor drawing right',realm(id));place('dream','the rescue pool refilled and immediately owing the old loss-bearer a claim on it',realm(id))}incident(id,'reserve restitution: '+why,sev)}
function ensure(){if(!S.preferredRecoupmentOffice97||!fund58()||!(S.stabilizationQuotas58||[]).length)return null;if(!S.reserveRestitutionOffice98){S.reserveRestitutionOffice98={id:'RRR1',name:'Interreality Reserve Restitution Register',status:'restoring-drawing-rights',created:Date.now(),x:50,y:97.2};remember('RESERVE RESTITUTION RRR1: repayment of Build 96 recapitalization began restoring RDR to the reality whose pooled reserve asset bore the rescue',realm('A'));remember('RESERVE RESTITUTION RRR1: repayment of Build 96 recapitalization began restoring RDR to the reality whose pooled reserve asset bore the rescue',realm('B'));trust('A','reserve-restitution-created','RRR1');trust('B','reserve-restitution-created','RRR1')}return S.reserveRestitutionOffice98}
function restitutionForPayment(id){return(S.reserveRestitutions98||[]).find(r=>r.paymentId97===id)||null}
function rdrForPayment(id){return(S.drawingRights58||[]).find(d=>d.sourcePayment97===id&&d.sourceBuild98==='reserve-restitution')||null}
function upsert(arr,id,snap){let i=arr.findIndex(x=>x.id===id);if(i>=0)arr[i]=snap;else arr.push(snap)}
function mark(r,p,qr,f,d){let snap=JSON.parse(JSON.stringify(r));if(p){p.reserveRestitution98=r.id;p.reserveRestitutionMarker98=snap}if(qr){qr.reserveRestitutionMarkers98=qr.reserveRestitutionMarkers98||[];upsert(qr.reserveRestitutionMarkers98,r.id,snap);qr.reserveRestitutionLatest98=r.id}if(f){f.reserveRestitutionMarkers98=f.reserveRestitutionMarkers98||[];upsert(f.reserveRestitutionMarkers98,r.id,snap);f.reserveRestitutionLatest98=r.id}if(d){d.reserveRestitution98=r.id;d.reserveRestitutionMarker98=snap}}
function createRestitution(p){if(!p||(p.amount97||0)<=EPS)return null;let ex=restitutionForPayment(p.id);if(ex)return ex;let f=fund58(),recipient=p.burdenReality||other(p.reality),qr=quota58(recipient);if(!f||!qr)return null;let amount=Math.max(0,p.amount97||0),before=Math.max(0,qr.rdr||0);S.drawingRights58=S.drawingRights58||[];S.drawingRightSerial58=S.drawingRightSerial58||0;S.drawingRightsAllocated58=S.drawingRightsAllocated58||0;let d={id:'RDR'+(++S.drawingRightSerial58),reality:recipient,amount,created:Date.now(),status:'allocated',sourceBuild98:'reserve-restitution',sourcePayment97:p.id,sourceClaim97:p.claimId97,sourceTransfer96:p.transferId96,sourceRecap96:p.recapId96,currencyRecovered97:p.currency,x:10+Math.random()*80,y:12+Math.random()*68};S.drawingRights58.push(d);qr.rdr=before+amount;S.drawingRightsAllocated58+=amount;let r={id:'RRA'+(++S.reserveRestitutionSerial98),paymentId97:p.id,claimId97:p.claimId97,transferId96:p.transferId96,recapId96:p.recapId96,authorityId:p.authorityId,targetReality:p.reality,burdenReality:recipient,currency:p.currency,amount98:amount,rdrId58:d.id,rdrBefore98:before,rdrAfter98:qr.rdr,status:'allocated',created:Date.now(),x:p.x||10+Math.random()*80,y:p.y||12+Math.random()*68};S.reserveRestitutions98.push(r);mark(r,p,qr,f,d);remember('RESERVE RESTITUTION '+r.id+': '+amount.toFixed(2)+' RDR restored to Reality '+recipient+' after '+p.id+' returned '+amount.toFixed(2)+' '+p.currency+' to the stabilization pool',realm(recipient));trust(recipient,'reserve-restitution-rdr-allocated',r.id+' '+d.id+' '+amount.toFixed(2));crisis(recipient,'Reality '+recipient+' regained '+amount.toFixed(2)+' RDR after bearing the reserve asset used by '+r.recapId96,'allocation-'+r.id);recompute();return r}
function reconstruct(){if(!RECOVER98)return false;let changed=false,seen=new Map(),f=fund58();for(const p of(S.preferredRecoupmentPayments97||[]))if(p.reserveRestitutionMarker98)seen.set(p.reserveRestitutionMarker98.id,p.reserveRestitutionMarker98);for(const qr of(S.stabilizationQuotas58||[]))for(const m of(qr.reserveRestitutionMarkers98||[]))seen.set(m.id,m);if(f)for(const m of(f.reserveRestitutionMarkers98||[]))seen.set(m.id,m);for(const d of(S.drawingRights58||[]))if(d.reserveRestitutionMarker98)seen.set(d.reserveRestitutionMarker98.id,d.reserveRestitutionMarker98);for(const m of seen.values()){if(S.reserveRestitutions98.some(r=>r.id===m.id))continue;let r=JSON.parse(JSON.stringify(m));r.recovered=true;S.reserveRestitutions98.push(r);let n=Number(String(r.id).replace(/\D/g,''))||0;if(n>S.reserveRestitutionSerial98)S.reserveRestitutionSerial98=n;changed=true;S.reserveRestitutionRecoveries98++}recompute();return changed}
function reconcile(){if(!ensure())return false;let changed=reconstruct();for(const p of(S.preferredRecoupmentPayments97||[])){if((p.amount97||0)<=EPS||restitutionForPayment(p.id)||p.reserveRestitution98||rdrForPayment(p.id))continue;if(createRestitution(p))changed=true}recompute();return changed}
function recompute(){S.reserveRestitutionAmount98=(S.reserveRestitutions98||[]).reduce((n,r)=>n+(r.amount98||0),0)}
function currentVotes(id){return(S.fundDirectors59||[]).find(d=>d.reality===id)?.votes??(quota58(id)?.votes||0)}
function openRestitution(r){let p=payment97(r.paymentId97),c=claim97(r.claimId97),qr=quota58(r.burdenReality),d=(S.drawingRights58||[]).find(x=>x.id===r.rdrId58),acts=[];if(c)acts.push(['open '+c.id+' preference',()=>q('#openPreferredRecoupment97')?.click()]);acts.push(['close',closePanel]);panel(r.id+' · RESERVE RESTITUTION',r.status.toUpperCase(),r.paymentId97+' · '+(r.amount98||0).toFixed(2)+' RDR → Reality '+r.burdenReality+' · Build 58 '+(d?.id||r.rdrId58)+' · member RDR '+(qr?.rdr||0).toFixed(2)+' · current board vote '+currentVotes(r.burdenReality).toFixed(2)+'% · recovered currency '+r.currency+' · source '+(p?.claimId97||r.claimId97),acts)}
function openOffice(){if(!ensure())return;let acts=[];for(const r of S.reserveRestitutions98.slice(-10))acts.push(['open '+r.id+' · '+r.amount98.toFixed(2)+' RDR',()=>openRestitution(r)]);acts.push(['open stabilization fund',()=>q('#openStabilizationButton')?.click()],['open fund board',()=>q('#openFundBoardButton')?.click()],['close',closePanel]);let qa=quota58('A'),qb=quota58('B');panel(S.reserveRestitutionOffice98.name,'DRAWING-RIGHT RESTITUTION · RRR1',S.reserveRestitutions98.length+' allocations · '+S.reserveRestitutionAmount98.toFixed(2)+' RDR restored · member RDR A '+(qa?.rdr||0).toFixed(2)+' / B '+(qb?.rdr||0).toFixed(2)+' · old Build 59 scoring will price those outstanding RDR claims into future vote recalculation',acts)}
function render98(){if(!ensure())return;let layer=q('#reserveRestitutionLayer98');if(!layer){layer=document.createElement('div');layer.id='reserveRestitutionLayer98';document.body.appendChild(layer)}layer.innerHTML='';let o=document.createElement('i');o.className='reserveRestitutionOffice98';o.dataset.label='RDR';o.style.left='50%';o.style.top='97.2%';o.onclick=openOffice;layer.appendChild(o);for(const r of S.reserveRestitutions98.slice(-8)){let n=document.createElement('i');n.className='reserveRestitution98';n.dataset.label='R+';n.style.left=r.x+'%';n.style.top=r.y+'%';n.onclick=()=>openRestitution(r);layer.appendChild(n)}let line=q('#reserverestitutionline98');if(!line){line=document.createElement('div');line.id='reserverestitutionline98';line.className='line';(q('#preferredrecoupmentline97')||q('#supervisoryrecapline96')||q('#stabilizationline')||q('#enforcement')).after(line)}let qa=quota58('A'),qb=quota58('B');line.textContent='reserve restitution: '+S.reserveRestitutions98.length+' allocations · '+S.reserveRestitutionAmount98.toFixed(2)+' RDR restored · RDR A '+(qa?.rdr||0).toFixed(2)+' / B '+(qb?.rdr||0).toFixed(2);let ctr=document.querySelector('#app .controls');if(ctr&&!q('#openReserveRestitution98')){let x=document.createElement('button');x.id='openReserveRestitution98';x.textContent='open reserve restitution';x.onclick=openOffice;ctr.prepend(x)}}
renderAll=function(){R98();let changed=reconcile();render98();if(changed)save98()};let f=q('#forget');if(f)f.onclick=()=>{for(let i=2;i<=98;i++)localStorage.removeItem('nothing-state-v'+i);location.reload()};setInterval(()=>{reconcile();render98();save98()},2700);ensure();reconcile();renderAll();save98();
})();