(()=>{
const B87=save,R87=renderAll,O=JSON.parse(localStorage.getItem('nothing-state-v87')||'null')||{},RECOVER87=!Array.isArray(O.residualInterestClaims87),K=['residualInterestOffice87','residualInterestClaims87','residualInterestPayments87','residualInterestClaimSerial87','residualInterestPaymentSerial87','residualInterestClaimsCreated87','residualInterestCrystallized87','residualInterestCollected87','residualInterestCasesCured87','residualInterestBlocked87','residualInterestCrises87','residualInterestKeys87','lastResidualInterestTick87'];
for(const k of K)S[k]=O[k]??(/Serial|Created|Crystallized|Collected|Cured|Blocked|Crises|Tick/.test(k)?0:/Keys/.test(k)?{}:/Office/.test(k)?null:[]);
function save87(){B87();let o={};for(const k of K)o[k]=S[k];localStorage.setItem('nothing-state-v87',JSON.stringify(o))}save=save87;
const q=s=>$(s),realm=id=>S.real[id],facility=id=>(S.liquidityFacilities55||[]).find(x=>x.id===id),authority=id=>(S.monetaryAuthorities55||[]).find(x=>x.id===id),cl=(v,a,b)=>Math.max(a,Math.min(b,v));
function trust(id,status,note){S.trustAudits=S.trustAudits||[];S.trustAuditSerial=S.trustAuditSerial||0;S.trustAudits.push({id:'TA'+(++S.trustAuditSerial),reality:id,status,created:Date.now(),note,x:10+Math.random()*80,y:12+Math.random()*68})}
function incident(id,title,sev='SEV1'){S.incidents=S.incidents||[];S.incidentSerial=S.incidentSerial||0;let ex=S.incidents.find(x=>x.reality===id&&x.title===title&&x.status==='open');if(ex)return ex;let i={id:'INC'+(++S.incidentSerial),reality:id,title,severity:sev,status:'open',started:Date.now(),owner:'residual interest claims office',x:10+Math.random()*80,y:12+Math.random()*68};S.incidents.push(i);return i}
function crisis(id,why,sev='SEV1'){let n=Date.now(),k=id+'|'+why;if(S.residualInterestKeys87[k]&&n-S.residualInterestKeys87[k]<14000)return;S.residualInterestKeys87[k]=n;S.residualInterestCrises87++;remember('RESIDUAL INTEREST CRISIS: '+why+' left a non-monetary claim after the public-money principal was gone',realm(id));if(typeof place==='function'){place('cold','central-bank loan principal died before its interest bill did',realm(id));place('dream','a repaid monetary facility leaving a debt-shaped ghost behind',realm(id))}incident(id,'residual-interest claim crisis: '+why,sev)}
function ensure(){if(!S.postDefaultCashSweepOffice86||!S.fundingCrossDefaultOffice85)return null;if(!S.residualInterestOffice87){S.residualInterestOffice87={id:'RIO1',name:'Interreality Residual Interest Claims Office',status:'crystallizing',created:Date.now(),x:50,y:82};remember('RESIDUAL INTEREST RIO1: principal-zero monetary facilities acquired separate post-default interest claims',realm('A'));remember('RESIDUAL INTEREST RIO1: principal-zero monetary facilities acquired separate post-default interest claims',realm('B'));trust('A','residual-interest-office-created','RIO1');trust('B','residual-interest-office-created','RIO1')}return S.residualInterestOffice87}
function borrowerFrom(f){if(!f)return null;if(f.borrowerType==='dealer'){let o=(S.derivativeDealers53||[]).find(x=>x.id===f.borrowerId);return o?{obj:o,cashField:'capital',name:o.name||f.borrowerId}:null}if(f.borrowerType==='ccp'){let o=(S.clearinghouses54||[]).find(x=>x.id===f.borrowerId);return o?{obj:o,cashField:'liquidity',name:o.name||f.borrowerId}:null}if(f.borrowerType==='insurer'){let o=(S.insurers51||[]).find(x=>x.id===f.borrowerId);return o?{obj:o,cashField:'capital',name:o.name||f.borrowerId}:null}if(f.borrowerType==='treasury'){let o=(S.packageTreasuries47||[]).find(x=>x.namespaceId===f.borrowerId),n=(S.namespaces46||[]).find(x=>x.id===f.borrowerId);return o?{obj:o,cashField:'balance',name:(n?.name||f.borrowerId)+' package treasury'}:null}return null}
function cash(b){return Math.max(0,b?.obj?.[b.cashField]||0)}
function addCash(b,x){if(b)b.obj[b.cashField]=Math.max(0,(b.obj[b.cashField]||0)+x)}
function caseById(id){return(S.fundingCrossDefaults85||[]).find(x=>x.id===id)}
function linkedCaseForFacility(f){return(S.fundingCrossDefaults85||[]).find(c=>c.status==='liquidated-deficiency'&&(c.facilityIds85||[]).includes(f.id))||null}
function floorFor(c){if((c?.cashSweepOperatingFloor86||0)>.001)return c.cashSweepOperatingFloor86;let base=Math.max(0,c?.deficiency85||0);return cl(base*.10,.10,.50)}
function claimById(id){return(S.residualInterestClaims87||[]).find(x=>x.id===id)}
function dueClaims(c){return(S.residualInterestClaims87||[]).filter(x=>x.crossDefaultId85===c.id&&['due','partial'].includes(x.status)&&x.outstanding87>.01)}
function upsertMarker(arr,key,snap){let i=arr.findIndex(x=>x.id===key);if(i>=0)arr[i]=snap;else arr.push(snap)}
function markClaim(claim,c,f){let snap=JSON.parse(JSON.stringify(claim));c.residualInterestMarkers87=c.residualInterestMarkers87||[];upsertMarker(c.residualInterestMarkers87,claim.id,snap);c.residualInterestLatest87=claim.id;f.residualInterestMarkers87=f.residualInterestMarkers87||[];upsertMarker(f.residualInterestMarkers87,claim.id,snap);f.residualInterestClaim87=claim.id}
function crystallize(f,manual=false){if(!f||!['active','monetized'].includes(f.status)||(f.principal||0)>.01||(f.interestAccrued||0)<=.01||f.residualInterestClaim87)return null;let c=linkedCaseForFacility(f);if(!c)return null;let a=authority(f.authorityId);if(!a){S.residualInterestBlocked87++;crisis(c.reality,'principal was gone but the authority record needed to own the residual interest was missing','SEV2');return null}let amt=Math.max(0,f.interestAccrued||0),r={id:'RIC'+(++S.residualInterestClaimSerial87),crossDefaultId85:c.id,positionId79:c.positionId79,facilityId55:f.id,authorityId:f.authorityId,reality:f.reality,borrowerType:f.borrowerType,borrowerId:f.borrowerId,borrower:f.borrower,original87:amt,paid87:0,outstanding87:amt,status:'due',created:Date.now(),x:10+Math.random()*80,y:12+Math.random()*68};f.interestAccrued=0;f.principal=0;f.status='repaid';f.repaid=Date.now();f.repaidPrincipalOnly87=true;f.residualInterestCrystallized87=amt;f.crossDefaultDeficiency85=0;f.cashSweepRemaining86=0;S.residualInterestClaims87.push(r);S.residualInterestClaimsCreated87++;S.residualInterestCrystallized87+=amt;c.residualInterestOutstanding87=(c.residualInterestOutstanding87||0)+amt;c.residualInterestCured87=false;markClaim(r,c,f);remember('RESIDUAL INTEREST '+r.id+': '+amt.toFixed(3)+' interest detached from principal-zero '+f.id+' after '+c.id,realm(c.reality));trust(c.reality,'residual-interest-crystallized',r.id+' '+amt.toFixed(3));if(typeof place==='function')place('dream','monetary principal repaid while its interest survived as a separate claim',realm(c.reality));if(manual){q('#msg').textContent=r.id+' crystallized '+amt.toFixed(3)+' residual interest.';renderAll();save87();openClaim(r)}return r}
function payClaims(c,manual=false){let cs=dueClaims(c);if(!cs.length){if((c.residualInterestOutstanding87||0)<=.01)c.residualInterestCured87=true;return null}let f0=facility(cs[0].facilityId55),b=borrowerFrom(f0),floor=floorFor(c),before=cash(b),due=cs.reduce((n,x)=>n+x.outstanding87,0),available=Math.max(0,before-floor),amount=Math.min(available,due);if(!b||amount<=.01)return null;if(cs.some(x=>!authority(x.authorityId))){S.residualInterestBlocked87++;crisis(c.reality,'later cash existed but a residual-interest authority record was missing','SEV2');return null}let p={id:'RIP'+(++S.residualInterestPaymentSerial87),crossDefaultId85:c.id,reality:c.reality,borrower:c.borrower,cashBefore87:before,operatingFloor87:floor,availableCash87:available,amount87:0,allocations87:[],created:Date.now(),x:10+Math.random()*80,y:12+Math.random()*68},remaining=amount,total=due;
for(let i=0;i<cs.length;i++){let r=cs[i],share=i===cs.length-1?remaining:(total>0?amount*(r.outstanding87/total):0),x=Math.min(r.outstanding87,share),a=authority(r.authorityId);if(x<=.0001)continue;r.paid87+=x;r.outstanding87=Math.max(0,r.outstanding87-x);r.status=r.outstanding87<=.01?'paid':'partial';if(r.status==='paid')r.paidAt87=Date.now();a.capital=(a.capital||0)+x;remaining=Math.max(0,remaining-x);p.amount87+=x;p.allocations87.push({claimId87:r.id,facilityId55:r.facilityId55,paid87:x,outstanding87:r.outstanding87,status87:r.status});let f=facility(r.facilityId55);if(f)markClaim(r,c,f)}
if(p.amount87<=.0001)return null;addCash(b,-p.amount87);p.cashAfter87=cash(b);p.outstandingAfter87=dueClaims(c).reduce((n,x)=>n+x.outstanding87,0);S.residualInterestPayments87.push(p);S.residualInterestCollected87+=p.amount87;c.residualInterestOutstanding87=p.outstandingAfter87;c.residualInterestCollected87=(c.residualInterestCollected87||0)+p.amount87;if(p.outstandingAfter87<=.01){c.residualInterestCured87=true;c.residualInterestCuredAt87=Date.now();S.residualInterestCasesCured87++;remember('RESIDUAL INTEREST CURED '+c.id+': later borrower cash paid the final interest left after monetary principal was already gone',realm(c.reality));if(typeof place==='function')place('warm','the last debt ghost paid without recreating monetary credit',realm(c.reality))}else crisis(c.reality,'later borrower cash partially paid residual interest but '+p.outstandingAfter87.toFixed(3)+' remains','SEV2');if(manual){q('#msg').textContent=p.id+' paid '+p.amount87.toFixed(3)+' residual interest; '+p.outstandingAfter87.toFixed(3)+' remains.';renderAll();save87();openPayment(p)}return p}
function reconstruct(){if(!RECOVER87)return false;let changed=false,seen=new Map();for(const c of(S.fundingCrossDefaults85||[]))for(const m of(c.residualInterestMarkers87||[]))seen.set(m.id,m);for(const f of(S.liquidityFacilities55||[]))for(const m of(f.residualInterestMarkers87||[]))seen.set(m.id,m);for(const m of seen.values()){if((S.residualInterestClaims87||[]).some(x=>x.id===m.id))continue;let r=JSON.parse(JSON.stringify(m));r.recovered=true;S.residualInterestClaims87.push(r);S.residualInterestClaimsCreated87++;S.residualInterestCrystallized87+=r.original87||0;S.residualInterestCollected87+=r.paid87||0;let n=Number(String(r.id).replace(/\D/g,''))||0;if(n>S.residualInterestClaimSerial87)S.residualInterestClaimSerial87=n;changed=true}for(const c of(S.fundingCrossDefaults85||[])){let cs=(S.residualInterestClaims87||[]).filter(x=>x.crossDefaultId85===c.id),o=cs.reduce((n,x)=>n+Math.max(0,x.outstanding87||0),0);if(cs.length){c.residualInterestOutstanding87=o;c.residualInterestCured87=o<=.01}}return changed}
function reconcile(){if(!ensure())return false;let changed=reconstruct();for(const f of(S.liquidityFacilities55||[])){let r=crystallize(f,false);if(r)changed=true}for(const c of(S.fundingCrossDefaults85||[]).filter(c=>c.status==='liquidated-deficiency')){let p=payClaims(c,false);if(p)changed=true}return changed}
function openClaim(r){let f=facility(r.facilityId55),a=authority(r.authorityId),acts=[];if(f)acts.push(['open '+f.id+' source facility',()=>panel(f.id+' · PRINCIPAL REPAID',f.status.toUpperCase(),f.borrower+' · monetary principal 0 · residual-interest claim '+r.id+' '+r.outstanding87.toFixed(3),[['close',closePanel]])]);if(a)acts.push(['open '+a.id+' authority',()=>panel(a.id+' · RESIDUAL INTEREST HOLDER',a.status?.toUpperCase?.()||'AUTHORITY','capital '+(a.capital||0).toFixed(3)+' · claim '+r.id+' outstanding '+r.outstanding87.toFixed(3),[['close',closePanel]])]);acts.push(['close',closePanel]);panel(r.id+' · RESIDUAL INTEREST',r.status.toUpperCase(),r.borrower+' · original '+r.original87.toFixed(3)+' · paid '+r.paid87.toFixed(3)+' · outstanding '+r.outstanding87.toFixed(3)+' · source '+r.facilityId55,acts)}
function openPayment(p){panel(p.id+' · RESIDUAL INTEREST PAYMENT','PAID',p.borrower+' · cash '+p.cashBefore87.toFixed(3)+'→'+p.cashAfter87.toFixed(3)+' · floor '+p.operatingFloor87.toFixed(3)+' · paid '+p.amount87.toFixed(3)+' · remaining '+p.outstandingAfter87.toFixed(3),[['close',closePanel]])}
function openOffice(){if(!ensure())return;let acts=[];for(const r of S.residualInterestClaims87.filter(x=>['due','partial'].includes(x.status)).slice(-8))acts.push(['open '+r.id+' · '+r.outstanding87.toFixed(3),()=>openClaim(r)]);for(const p of S.residualInterestPayments87.slice(-6))acts.push(['open '+p.id+' · '+p.amount87.toFixed(3),()=>openPayment(p)]);acts.push(['close',closePanel]);panel(S.residualInterestOffice87.name,'CRYSTALLIZING · RIO1',S.residualInterestClaimsCreated87+' claims · '+S.residualInterestCrystallized87.toFixed(3)+' crystallized · '+S.residualInterestCollected87.toFixed(3)+' collected · '+S.residualInterestCasesCured87+' cases cured',acts)}
function render87(){if(!ensure())return;let layer=q('#residualInterestLayer87');if(!layer){layer=document.createElement('div');layer.id='residualInterestLayer87';document.body.appendChild(layer)}layer.innerHTML='';let o=document.createElement('i');o.className='residualInterestOffice87';o.dataset.label='i$';o.style.left='50%';o.style.top='82%';o.onclick=openOffice;layer.appendChild(o);for(const r of S.residualInterestClaims87.filter(x=>x.status!=='paid').slice(-8)){let e=document.createElement('i');e.className='residualInterest87 '+r.status;e.dataset.label='i';e.style.left=r.x+'%';e.style.top=r.y+'%';e.onclick=()=>openClaim(r);layer.appendChild(e)}let line=q('#residualinterestline87');if(!line){line=document.createElement('div');line.id='residualinterestline87';line.className='line';(q('#postdefaultcashsweepline86')||q('#fundingcrossdefaultline85')||q('#monetaryline')||q('#enforcement')).after(line)}line.textContent='residual interest: '+S.residualInterestClaimsCreated87+' claims · '+S.residualInterestCrystallized87.toFixed(2)+' crystallized · '+S.residualInterestCollected87.toFixed(2)+' collected';let ctr=document.querySelector('#app .controls');if(ctr&&!q('#openResidualInterest87')){let x=document.createElement('button');x.id='openResidualInterest87';x.textContent='open residual interest';x.onclick=openOffice;ctr.prepend(x)}}
renderAll=function(){R87();let changed=reconcile();render87();if(changed)save87()};let f=q('#forget');if(f)f.onclick=()=>{for(let i=2;i<=87;i++)localStorage.removeItem('nothing-state-v'+i);location.reload()};setInterval(()=>{reconcile();render87();save87()},2300);ensure();reconcile();renderAll();save87();
})();