(()=>{
const B94=save,R94=renderAll,O=JSON.parse(localStorage.getItem('nothing-state-v94')||'null')||{},RECOVER94=!Array.isArray(O.restorationSurchargeRequirements94),K=['restorationSurchargeOffice94','restorationSurchargeRequirements94','restorationSurchargeActions94','restorationSurchargeRequirementSerial94','restorationSurchargeActionSerial94','restorationSurchargeRequirementsCreated94','restorationSurchargeTopups94','restorationSurchargeTopupAmount94','restorationSurchargeReleases94','restorationSurchargeReleaseAmount94','restorationSurchargeHeldTotal94','restorationSurchargeShortfallTotal94','restorationSurchargeAuthorities94','restorationSurchargeCrises94','restorationSurchargeKeys94','lastRestorationSurchargeTick94'];
for(const k of K)S[k]=O[k]??(k==='restorationSurchargeRequirements94'||k==='restorationSurchargeActions94'?[]:/Serial|Created|Topups|Amount|Releases|HeldTotal|ShortfallTotal|Authorities|Crises|Tick/.test(k)?0:/Keys/.test(k)?{}:/Office/.test(k)?null:[]);
function save94(){B94();let o={};for(const k of K)o[k]=S[k];localStorage.setItem('nothing-state-v94',JSON.stringify(o))}save=save94;
const q=s=>$(s),realm=id=>S.real[id],EPS=.0001;
function trust(id,status,note){S.trustAudits=S.trustAudits||[];S.trustAuditSerial=S.trustAuditSerial||0;S.trustAudits.push({id:'TA'+(++S.trustAuditSerial),reality:id,status,created:Date.now(),note,x:10+Math.random()*80,y:12+Math.random()*68})}
function incident(id,title,sev='SEV2'){S.incidents=S.incidents||[];S.incidentSerial=S.incidentSerial||0;let ex=S.incidents.find(x=>x.reality===id&&x.title===title&&x.status==='open');if(ex)return ex;let i={id:'INC'+(++S.incidentSerial),reality:id,title,severity:sev,status:'open',started:Date.now(),owner:'restoration surcharge office',x:10+Math.random()*80,y:12+Math.random()*68};S.incidents.push(i);return i}
function crisis(id,why,key,sev='SEV1'){let n=Date.now(),k=id+'|'+key;if(S.restorationSurchargeKeys94[k]&&n-S.restorationSurchargeKeys94[k]<14000)return;S.restorationSurchargeKeys94[k]=n;S.restorationSurchargeCrises94++;remember('RESTORATION SURCHARGE: '+why+' made a later emergency exception consume extra capital because an earlier supervisory breach was still being restored',realm(id));if(typeof place==='function'){place('cold','emergency lending getting more expensive after the central bank already failed its capital test',realm(id));place('dream','restoration plan charging a surcharge on the next exception before the old episode is over',realm(id))}incident(id,'restoration surcharge: '+why,sev)}
function ensure(){if(!S.capitalRestorationOffice93||!S.supervisoryCapitalOffice92)return null;if(!S.restorationSurchargeOffice94){S.restorationSurchargeOffice94={id:'RSO1',name:'Interreality Restoration Surcharge Office',status:'exception-surcharge',created:Date.now(),x:50,y:84};remember('RESTORATION SURCHARGE RSO1: later post-cap exceptions issued during a live capital-restoration episode acquired an additional 50% capital charge',realm('A'));remember('RESTORATION SURCHARGE RSO1: later post-cap exceptions issued during a live capital-restoration episode acquired an additional 50% capital charge',realm('B'));trust('A','restoration-surcharge-created','RSO1');trust('B','restoration-surcharge-created','RSO1')}return S.restorationSurchargeOffice94}
function authority(id){return(S.monetaryAuthorities55||[]).find(a=>a.id===id)}
function facility(id){return(S.liquidityFacilities55||[]).find(f=>f.id===id)}
function req92(eventId){return(S.supervisoryCapitalRequirements92||[]).find(r=>r.exceptionEvent91===eventId)}
function liveOrder93(id){return(S.capitalRestorationOrders93||[]).find(o=>o.authorityId===id&&!['released-exposure-closed','orphaned-authority'].includes(o.status))}
function registrations(){let office=ensure();if(!office)return[];return(S.monetaryExceptionEvents91||[]).filter(e=>e.kind91==='exception-registration'&&(e.created||0)>=(office.created||0)).sort((a,b)=>(a.created||0)-(b.created||0)||String(a.id).localeCompare(String(b.id)))}
function upsert(arr,id,snap){let i=arr.findIndex(x=>x.id===id);if(i>=0)arr[i]=snap;else arr.push(snap)}
function markReq(r,f,a){let snap=JSON.parse(JSON.stringify(r));if(f){f.restorationSurchargeRequirement94=r.id;f.restorationSurchargeMarker94=snap}if(a){a.restorationSurchargeMarkers94=a.restorationSurchargeMarkers94||[];upsert(a.restorationSurchargeMarkers94,r.id,snap);a.restorationSurchargeLatest94=r.id}}
function markAction(x,f,a){let snap=JSON.parse(JSON.stringify(x));if(f){f.restorationSurchargeActions94=f.restorationSurchargeActions94||[];upsert(f.restorationSurchargeActions94,x.id,snap)}if(a){a.restorationSurchargeActions94=a.restorationSurchargeActions94||[];upsert(a.restorationSurchargeActions94,x.id,snap);a.restorationSurchargeActionLatest94=x.id}}
function reqForEvent(id){return(S.restorationSurchargeRequirements94||[]).find(r=>r.exceptionEvent91===id)}
function eligible(e){if(!e||reqForEvent(e.id))return false;let r92=req92(e.id);if(!r92)return false;let o=liveOrder93(e.authorityId);if(!o||!(o.created<=(e.created||0)))return false;return true}
function action(kind,r,f,a,amount,before,after){let x={id:'RSA'+(++S.restorationSurchargeActionSerial94),kind94:kind,requirementId94:r.id,exceptionEvent91:r.exceptionEvent91,build92RequirementId:r.build92RequirementId,restorationOrderId93:r.restorationOrderId93,facilityId55:r.facilityId55,authorityId:r.authorityId,reality:r.reality,amount94:amount,heldBefore94:before,heldAfter94:after,capitalAfter94:a.capital,created:Date.now()};S.restorationSurchargeActions94.push(x);if(kind==='surcharge-topup'){S.restorationSurchargeTopups94++;S.restorationSurchargeTopupAmount94+=amount}else{S.restorationSurchargeReleases94++;S.restorationSurchargeReleaseAmount94+=amount}markAction(x,f,a);return x}
function createRequirement(e){let r92=req92(e.id),o=liveOrder93(e.authorityId),f=facility(e.facilityId55),a=authority(e.authorityId);if(!r92||!o||!f||!a)return null;let target=['active','monetized'].includes(f.status)?Math.max(0,f.principal||0)*.5:0,r={id:'RSR'+(++S.restorationSurchargeRequirementSerial94),exceptionEvent91:e.id,build92RequirementId:r92.id,restorationOrderId93:o.id,facilityId55:f.id,authorityId:a.id,reality:a.reality,exceptionNumber91:e.exceptionNumber91,supervisoryStage90:e.supervisoryStage90,originalPrincipal94:Math.max(0,f.principal||0),surchargeRate94:.5,required94:target,held94:0,shortfall94:target,status:target>EPS?'pending-surcharge':'moot-repaid-before-build94',created:Date.now(),x:10+Math.random()*80,y:12+Math.random()*68};S.restorationSurchargeRequirements94.push(r);S.restorationSurchargeRequirementsCreated94++;f.restorationSurchargeRequirement94=r.id;markReq(r,f,a);remember('RESTORATION SURCHARGE '+r.id+': '+f.id+' was issued while '+o.id+' remained live; an additional 50% of current principal must be backed by authority capital',realm(a.reality));trust(a.reality,'restoration-exception-surcharge-required',r.id+' '+f.id);if(target>EPS)crisis(a.reality,a.name+' issued '+f.id+' before '+o.id+' had ended','requirement-'+r.id);return r}
function adjust(r){let f=facility(r.facilityId55),a=authority(r.authorityId);if(!a){r.status='orphaned-authority';return false}if(!f){r.status='orphaned-facility';markReq(r,null,a);return false}let target=['active','monetized'].includes(f.status)?Math.max(0,f.principal||0)*.5:0,changed=false;r.required94=target;if((r.held94||0)+1e-9<target){let gap=target-(r.held94||0),take=Math.min(gap,Math.max(0,a.capital||0));if(take>EPS){let before=r.held94||0;a.capital=Math.max(0,(a.capital||0)-take);r.held94=before+take;action('surcharge-topup',r,f,a,take,before,r.held94);changed=true}}if((r.held94||0)>target+1e-9){let rel=(r.held94||0)-target,before=r.held94||0;r.held94=target;a.capital=(a.capital||0)+rel;action('surcharge-release',r,f,a,rel,before,r.held94);changed=true}r.shortfall94=Math.max(0,target-(r.held94||0));if(target<=EPS&&r.held94<=EPS){r.required94=0;r.held94=0;r.shortfall94=0;r.status=f.status==='repaid'?'released-repaid':'released-closed';r.releasedAt94=r.releasedAt94||Date.now()}else if(r.shortfall94>EPS){r.status='surcharge-shortfall';crisis(a.reality,a.name+' could fund only '+(r.held94||0).toFixed(2)+' of '+target.toFixed(2)+' restoration surcharge behind '+f.id,'shortfall-'+r.id)}else r.status=f.status==='monetized'?'surcharge-monetized':'surcharge-active';f.restorationSurchargeHeld94=r.held94;f.restorationSurchargeShortfall94=r.shortfall94;markReq(r,f,a);return changed}
function recompute(){let auths=new Set();S.restorationSurchargeHeldTotal94=0;S.restorationSurchargeShortfallTotal94=0;for(const a of(S.monetaryAuthorities55||[])){let rs=(S.restorationSurchargeRequirements94||[]).filter(r=>r.authorityId===a.id&&!['orphaned-authority'].includes(r.status)),held=rs.reduce((n,r)=>n+Math.max(0,r.held94||0),0),short=rs.reduce((n,r)=>n+Math.max(0,r.shortfall94||0),0);a.restorationSurchargeHeld94=held;a.restorationSurchargeShortfall94=short;if(rs.length)auths.add(a.id);S.restorationSurchargeHeldTotal94+=held;S.restorationSurchargeShortfallTotal94+=short}S.restorationSurchargeAuthorities94=auths.size}
function reconstruct(){if(!RECOVER94)return false;let changed=false,seenR=new Map(),seenA=new Map();for(const a of(S.monetaryAuthorities55||[])){for(const m of(a.restorationSurchargeMarkers94||[]))seenR.set(m.id,m);for(const x of(a.restorationSurchargeActions94||[]))seenA.set(x.id,x)}for(const f of(S.liquidityFacilities55||[])){let m=f.restorationSurchargeMarker94;if(m)seenR.set(m.id,m);for(const x of(f.restorationSurchargeActions94||[]))seenA.set(x.id,x)}for(const m of seenR.values()){if((S.restorationSurchargeRequirements94||[]).some(x=>x.id===m.id))continue;let r=JSON.parse(JSON.stringify(m));r.recovered=true;S.restorationSurchargeRequirements94.push(r);S.restorationSurchargeRequirementsCreated94++;let n=Number(String(r.id).replace(/\D/g,''))||0;if(n>S.restorationSurchargeRequirementSerial94)S.restorationSurchargeRequirementSerial94=n;changed=true}for(const m of seenA.values()){if((S.restorationSurchargeActions94||[]).some(x=>x.id===m.id))continue;let x=JSON.parse(JSON.stringify(m));x.recovered=true;S.restorationSurchargeActions94.push(x);if(x.kind94==='surcharge-topup'){S.restorationSurchargeTopups94++;S.restorationSurchargeTopupAmount94+=x.amount94||0}else{S.restorationSurchargeReleases94++;S.restorationSurchargeReleaseAmount94+=x.amount94||0}let n=Number(String(x.id).replace(/\D/g,''))||0;if(n>S.restorationSurchargeActionSerial94)S.restorationSurchargeActionSerial94=n;changed=true}recompute();return changed}
function reconcile(){if(!ensure())return false;let changed=reconstruct();for(const e of registrations())if(eligible(e)&&createRequirement(e))changed=true;for(const r of(S.restorationSurchargeRequirements94||[]))if(adjust(r))changed=true;recompute();return changed}
function openReq(r){let f=facility(r.facilityId55),a=authority(r.authorityId),acts=[];for(const x of(S.restorationSurchargeActions94||[]).filter(x=>x.requirementId94===r.id).slice(-6))acts.push(['open '+x.id,()=>openAction(x)]);acts.push(['close',closePanel]);panel(r.id+' · RESTORATION SURCHARGE',r.status.toUpperCase(),(f?f.id:'missing facility')+' · exception #'+r.exceptionNumber91+' · 50% surcharge · required '+(r.required94||0).toFixed(2)+' · held '+(r.held94||0).toFixed(2)+' · shortfall '+(r.shortfall94||0).toFixed(2)+' · authority free capital '+(a?(a.capital||0).toFixed(2):'missing'),acts)}
function openAction(x){panel(x.id+' · RESTORATION SURCHARGE ACTION',x.kind94.toUpperCase(),x.facilityId55+' · '+(x.amount94||0).toFixed(2)+' · held '+(x.heldBefore94||0).toFixed(2)+'→'+(x.heldAfter94||0).toFixed(2)+' · authority free capital '+(x.capitalAfter94||0).toFixed(2),[['close',closePanel]])}
function openOffice(){if(!ensure())return;let acts=[];for(const r of S.restorationSurchargeRequirements94.slice(-10))acts.push(['open '+r.id+' · '+r.status,()=>openReq(r)]);acts.push(['close',closePanel]);panel(S.restorationSurchargeOffice94.name,'EXCEPTION SURCHARGE · RSO1',S.restorationSurchargeRequirementsCreated94+' requirements · '+S.restorationSurchargeHeldTotal94.toFixed(2)+' capital held · '+S.restorationSurchargeShortfallTotal94.toFixed(2)+' shortfall · '+S.restorationSurchargeReleaseAmount94.toFixed(2)+' released',acts)}
function render94(){if(!ensure())return;let layer=q('#restorationSurchargeLayer94');if(!layer){layer=document.createElement('div');layer.id='restorationSurchargeLayer94';document.body.appendChild(layer)}layer.innerHTML='';let o=document.createElement('i');o.className='restorationSurchargeOffice94';o.dataset.label='SUR';o.style.left='50%';o.style.top='84%';o.onclick=openOffice;layer.appendChild(o);for(const r of S.restorationSurchargeRequirements94.slice(-8)){let n=document.createElement('i');n.className='restorationSurcharge94 '+r.status;n.dataset.label=r.status==='surcharge-shortfall'?'S!':'S';n.style.left=r.x+'%';n.style.top=r.y+'%';n.onclick=()=>openReq(r);layer.appendChild(n)}let line=q('#restorationsurchargeline94');if(!line){line=document.createElement('div');line.id='restorationsurchargeline94';line.className='line';(q('#capitalrestorationline93')||q('#supervisorycapitalline92')||q('#monetaryline')||q('#enforcement')).after(line)}line.textContent='restoration surcharge: '+S.restorationSurchargeHeldTotal94.toFixed(2)+' held · '+S.restorationSurchargeShortfallTotal94.toFixed(2)+' shortfall · '+S.restorationSurchargeRequirementsCreated94+' requirements';let ctr=document.querySelector('#app .controls');if(ctr&&!q('#openRestorationSurcharge94')){let x=document.createElement('button');x.id='openRestorationSurcharge94';x.textContent='open restoration surcharge';x.onclick=openOffice;ctr.prepend(x)}}
renderAll=function(){R94();let changed=reconcile();render94();if(changed)save94()};let f=q('#forget');if(f)f.onclick=()=>{for(let i=2;i<=94;i++)localStorage.removeItem('nothing-state-v'+i);location.reload()};setInterval(()=>{reconcile();render94();save94()},2300);ensure();reconcile();renderAll();save94();
})();