(()=>{
const BS62=save,BR62=renderAll,O62=JSON.parse(localStorage.getItem('nothing-state-v62')||'null')||{},cl=(v,a,b)=>Math.max(a,Math.min(b,v));
S.restructuringOffice62=O62.restructuringOffice62||null;
S.debtConferences62=O62.debtConferences62||[];
S.debtClaims62=O62.debtClaims62||[];
S.restructuringOffers62=O62.restructuringOffers62||[];
S.exchangeBonds62=O62.exchangeBonds62||[];
S.holdoutActions62=O62.holdoutActions62||[];
S.debtConferenceSerial62=O62.debtConferenceSerial62||0;
S.debtClaimSerial62=O62.debtClaimSerial62||0;
S.restructuringOfferSerial62=O62.restructuringOfferSerial62||0;
S.exchangeBondSerial62=O62.exchangeBondSerial62||0;
S.holdoutActionSerial62=O62.holdoutActionSerial62||0;
S.restructuringsCompleted62=O62.restructuringsCompleted62||0;
S.restructuringsFailed62=O62.restructuringsFailed62||0;
S.cacBindings62=O62.cacBindings62||0;
S.holdoutChallenges62=O62.holdoutChallenges62||0;
S.holdoutVictories62=O62.holdoutVictories62||0;
S.debtHaircuts62=O62.debtHaircuts62||0;
S.restructuringCrises62=O62.restructuringCrises62||0;
S.restructuringKeys62=O62.restructuringKeys62||{};
S.lastRestructuringTick62=O62.lastRestructuringTick62||Date.now();
function save62(){BS62();localStorage.setItem('nothing-state-v62',JSON.stringify({restructuringOffice62:S.restructuringOffice62,debtConferences62:S.debtConferences62,debtClaims62:S.debtClaims62,restructuringOffers62:S.restructuringOffers62,exchangeBonds62:S.exchangeBonds62,holdoutActions62:S.holdoutActions62,debtConferenceSerial62:S.debtConferenceSerial62,debtClaimSerial62:S.debtClaimSerial62,restructuringOfferSerial62:S.restructuringOfferSerial62,exchangeBondSerial62:S.exchangeBondSerial62,holdoutActionSerial62:S.holdoutActionSerial62,restructuringsCompleted62:S.restructuringsCompleted62,restructuringsFailed62:S.restructuringsFailed62,cacBindings62:S.cacBindings62,holdoutChallenges62:S.holdoutChallenges62,holdoutVictories62:S.holdoutVictories62,debtHaircuts62:S.debtHaircuts62,restructuringCrises62:S.restructuringCrises62,restructuringKeys62:S.restructuringKeys62,lastRestructuringTick62:S.lastRestructuringTick62}))}save=save62;
const realm=id=>S.real[id],other=id=>id==='A'?'B':'A',acct62=id=>(S.tradeAccounts57||[]).find(a=>a.reality===id),currency62=id=>(S.fxCurrencies56||[]).find(c=>c.reality===id),award62=id=>[...(S.remedyAwards61||[])].reverse().find(a=>a.kind==='surviving-debt'&&a.respondent===id&&a.recognition==='recognized'&&a.status!=='satisfied')||null,conference62=id=>[...S.debtConferences62].reverse().find(c=>c.debtor===id&&!['restructured','failed','closed'].includes(c.status))||null,claims62=c=>S.debtClaims62.filter(x=>x.conferenceId===c.id),offer62=c=>[...S.restructuringOffers62].reverse().find(o=>o.conferenceId===c.id)||null;
function trust62(id,status,note){let accepted=S.trustPolicies?.[id]?.acceptedRoots||[],r=[...(S.trustRoots||[])].filter(x=>accepted.includes(x.id)&&x.status==='active').sort((a,b)=>(b.strength||0)-(a.strength||0))[0];S.trustAudits=S.trustAudits||[];S.trustAuditSerial=S.trustAuditSerial||0;S.trustAudits.push({id:'TA'+(++S.trustAuditSerial),reality:id,remediationId:null,credentialId:null,certificateId:null,rootId:r?.id||null,status,created:Date.now(),note,x:10+Math.random()*80,y:12+Math.random()*68})}
function incident62(id,title,severity='SEV2'){S.incidents=S.incidents||[];let ex=S.incidents.find(i=>i.reality===id&&i.title===title&&i.status==='open');if(ex)return ex;S.incidentSerial=S.incidentSerial||0;let x={id:'INC'+(++S.incidentSerial),reality:id,title,severity,status:'open',alertIds:[],started:Date.now(),acknowledged:null,resolved:null,postmortem:null,owner:'sovereign debt restructuring conference',x:10+Math.random()*80,y:12+Math.random()*68};S.incidents.push(x);return x}
function restructuringCrisis(id,kind,severity='SEV2'){let now=Date.now(),k=id+'|'+kind;if(S.restructuringKeys62[k]&&now-S.restructuringKeys62[k]<14000)return;S.restructuringKeys62[k]=now;S.restructuringCrises62++;remember('RESTRUCTURING CRISIS: '+kind+' made debt ownership another constitutional problem',realm(id));if(typeof place==='function'){place('cold','creditors became a government for one balance sheet',realm(id));place('dream','minority creditor kept the old promise alive',realm(id))}let b=$('#bailiff');if(b)b.textContent='counting creditors who disagree about whether the same debt still exists';incident62(id,'sovereign restructuring crisis: '+kind,severity)}
function ensureOffice(){if(!S.remedyOffice61)return null;if(!S.restructuringOffice62){S.restructuringOffice62={id:'SDRO1',name:'Sovereign Debt Restructuring Office',status:'operating',cacThreshold:.75,created:Date.now(),x:50,y:66};remember('DEBT RESTRUCTURING OFFICE SDRO1: enforceable post-withdrawal claims became negotiable contracts',realm('A'));remember('DEBT RESTRUCTURING OFFICE SDRO1: enforceable post-withdrawal claims became negotiable contracts',realm('B'));trust62('A','sovereign-debt-restructuring-office-created','SDRO1 collective action and creditor standstills');trust62('B','sovereign-debt-restructuring-office-created','SDRO1 collective action and creditor standstills')}return S.restructuringOffice62}
function releaseStandstill(c){if(!c||!c.standstill)return;let a=(S.remedyAwards61||[]).find(a=>a.id===c.awardId);if(a&&a.standstill62===c.id){a.standstill62=null;a.lien=!!c.preAwardLien&&a.recognition==='recognized'&&a.status!=='satisfied';a.baselineReserves=currency62(c.debtor)?.foreignReserves||0}c.standstill=false;c.standstillEnded=Date.now()}
function conveneConference(id=S.active,manual=true){let office=ensureOffice();if(!office){if(manual)$('#msg').textContent='Build 61 remedies are not available yet.';return null}let existing=conference62(id);if(existing){if(manual)openConference(existing);return existing}let acct=acct62(id),a=award62(id),debt=Math.max(0,acct?.externalDebt||0);if(debt<=0){if(manual)$('#msg').textContent='Reality '+id+' has no external debt available for restructuring.';return null}let c={id:'DRC'+(++S.debtConferenceSerial62),debtor:id,creditorReality:other(id),awardId:a?.id||null,status:'convened',faceDebt:debt,currentDebt:debt,cacThreshold:office.cacThreshold,standstill:true,preAwardLien:!!a?.lien,reservesAtOpen:currency62(id)?.foreignReserves||0,created:Date.now(),x:50+(Math.random()*16-8),y:66+(Math.random()*8-4)};S.debtConferences62.push(c);let tranches=[['official',.52,'Reality '+other(id)+' official creditor'],['clearing',.25,'interreality clearing syndicate'],['archive',.23,'Archive distressed-claims desk']];for(const [kind,share,name] of tranches)S.debtClaims62.push({id:'CLM'+(++S.debtClaimSerial62),conferenceId:c.id,debtor:id,kind,holder:name,share,principal:debt*share,originalPrincipal:debt*share,status:'participating',vote:null,bound:false,created:Date.now(),x:10+Math.random()*80,y:12+Math.random()*68});if(a){a.lien=false;a.standstill62=c.id}remember('CREDITOR STANDSTILL '+c.id+': Reality '+id+' opened restructuring talks on '+debt.toFixed(1)+' of external debt and paused Build 61 future-inflow execution',realm(id));if(typeof place==='function')place('dream','enforceable judgment paused so creditors could negotiate its value',realm(id));trust62(id,'sovereign-debt-conference-opened',c.id+' face '+debt.toFixed(1));if(manual){$('#msg').textContent=c.id+' opened on '+debt.toFixed(1)+' of external debt. Build 61 execution is temporarily stayed.';renderAll();save62();openConference(c)}return c}
function draftOffer(c,profile='moderate',manual=true){if(!c||!['convened','offer-drafted'].includes(c.status))return null;let old=offer62(c);if(old&&['draft','voting'].includes(old.status)){if(manual)openOffer(old);return old}let terms=profile==='deep'?{haircut:.38,coupon:.035,maturityMonths:84}:{haircut:.22,coupon:.05,maturityMonths:60},o={id:'EXG'+(++S.restructuringOfferSerial62),conferenceId:c.id,profile,haircut:terms.haircut,coupon:terms.coupon,maturityMonths:terms.maturityMonths,cacThreshold:c.cacThreshold,status:'draft',votes:{},yesWeight:0,noWeight:0,created:Date.now(),decided:null,x:10+Math.random()*80,y:12+Math.random()*68};S.restructuringOffers62.push(o);c.status='offer-drafted';remember('DEBT EXCHANGE '+o.id+': Reality '+c.debtor+' offered a '+(o.haircut*100).toFixed(0)+'% face-value haircut with '+o.maturityMonths+'-month replacement debt',realm(c.debtor));if(manual){$('#msg').textContent=o.id+' drafted: '+(o.haircut*100).toFixed(0)+'% haircut, '+(o.coupon*100).toFixed(1)+'% coupon, '+o.maturityMonths+' months.';renderAll();save62();openOffer(o)}return o}
function votePreference(claim,o,c){let acct=acct62(c.debtor),res=currency62(c.debtor)?.foreignReserves||0,debt=acct?.externalDebt||c.currentDebt||0,distress=debt/(debt+res+1);if(claim.kind==='official')return o.haircut<=.34||distress>=.58?'yes':'no';if(claim.kind==='clearing')return o.haircut<=.27||distress>=.72?'yes':'no';return o.haircut<=.08&&distress<.45?'yes':'no'}
function applyExchange(c,o){let acct=acct62(c.debtor),a=(S.remedyAwards61||[]).find(a=>a.id===c.awardId),old=Math.max(0,acct?.externalDebt||c.currentDebt||0),newDebt=old*(1-o.haircut),haircut=old-newDebt;if(acct)acct.externalDebt=newDebt;c.currentDebt=newDebt;c.haircutAmount=haircut;c.status='restructured';c.completed=Date.now();o.status='accepted';o.decided=Date.now();for(const claim of claims62(c)){claim.newPrincipal=claim.originalPrincipal*(1-o.haircut);claim.principal=claim.newPrincipal;if(claim.vote==='yes')claim.status='exchanged';else{claim.status='bound-holdout';claim.bound=true;S.cacBindings62++}}if(a){a.amount=(a.paid||0)+newDebt;a.restructured62=c.id;if(a.amount<=a.paid+1e-9){a.status='satisfied';a.lien=false}else if((a.paid||0)>0)a.status='partially-satisfied'}let b={id:'XBD'+(++S.exchangeBondSerial62),conferenceId:c.id,offerId:o.id,debtor:c.debtor,currency:a?.currency||(c.debtor==='A'?'RB':'RA'),principal:newDebt,coupon:o.coupon,maturityMonths:o.maturityMonths,matures:Date.now()+o.maturityMonths*30*86400000,status:'outstanding',created:Date.now(),x:10+Math.random()*80,y:12+Math.random()*68};S.exchangeBonds62.push(b);S.restructuringsCompleted62++;S.debtHaircuts62+=haircut;remember('COLLECTIVE ACTION '+o.id+': '+o.yesWeight.toFixed(1)+'% of claims bound every participating creditor and cut Reality '+c.debtor+' debt by '+haircut.toFixed(1),realm(c.debtor));if(typeof place==='function'){place('cold','majority creditor vote changed the amount everyone was owed',realm(c.debtor));place('dream','old debt disappeared into a bond issued by the debtor who could not pay it',realm(c.debtor))}trust62(c.debtor,'sovereign-debt-restructured',c.id+' haircut '+haircut.toFixed(1)+' new debt '+newDebt.toFixed(1));releaseStandstill(c);restructuringCrisis(c.debtor,'collective action bound a dissenting creditor');return b}
function voteOffer(o,manual=true){let c=S.debtConferences62.find(c=>c.id===o?.conferenceId);if(!o||!c||!['draft','voting'].includes(o.status))return o;o.status='voting';c.status='voting';o.votes={};o.yesWeight=0;o.noWeight=0;for(const claim of claims62(c)){let v=votePreference(claim,o,c);claim.vote=v;o.votes[claim.id]=v;if(v==='yes')o.yesWeight+=claim.share*100;else o.noWeight+=claim.share*100}if(o.yesWeight+1e-9>=o.cacThreshold*100)applyExchange(c,o);else{o.status='failed';o.decided=Date.now();c.status='failed';c.failed=Date.now();for(const claim of claims62(c))if(claim.vote==='no')claim.status='holdout';S.restructuringsFailed62++;releaseStandstill(c);remember('FAILED DEBT EXCHANGE '+o.id+': '+o.yesWeight.toFixed(1)+'% support did not reach '+(o.cacThreshold*100).toFixed(0)+'%; old claims resumed enforcement',realm(c.debtor));if(typeof place==='function')place('cold','standstill ended before the debt changed',realm(c.debtor));restructuringCrisis(c.debtor,'creditors failed to coordinate before enforcement resumed','SEV1')}if(manual){$('#msg').textContent=o.id+' '+o.status.toUpperCase()+' · yes '+o.yesWeight.toFixed(1)+'% / no '+o.noWeight.toFixed(1)+'%.';renderAll();save62();openOffer(o)}return o}
function challengeHoldout(c,manual=true){if(!c||c.status!=='restructured')return null;let o=offer62(c),claim=claims62(c).find(x=>x.status==='bound-holdout');if(!o||!claim){if(manual)$('#msg').textContent='No dissenting bound creditor remains to challenge the exchange.';return null}let weakAggregation=o.yesWeight<80,act={id:'HLD'+(++S.holdoutActionSerial62),conferenceId:c.id,offerId:o.id,claimId:claim.id,type:'cac-challenge',status:weakAggregation?'injunction-granted':'challenge-denied',created:Date.now(),x:10+Math.random()*80,y:12+Math.random()*68};S.holdoutActions62.push(act);S.holdoutChallenges62++;if(weakAggregation){let recovery=claim.originalPrincipal-(claim.newPrincipal||claim.principal),acct=acct62(c.debtor),a=(S.remedyAwards61||[]).find(a=>a.id===c.awardId);claim.status='holdout-restored';claim.bound=false;claim.principal=claim.originalPrincipal;act.recovery=recovery;if(acct)acct.externalDebt=(acct.externalDebt||0)+recovery;c.currentDebt=(acct?.externalDebt||c.currentDebt)+0;if(a){a.amount=(a.amount||0)+recovery;if(a.recognition==='recognized'&&a.status!=='satisfied'){a.lien=true;a.baselineReserves=currency62(c.debtor)?.foreignReserves||0}}S.holdoutVictories62++;remember('HOLDOUT INJUNCTION '+act.id+': '+claim.holder+' escaped collective action and restored '+recovery.toFixed(1)+' of old face value',realm(c.debtor));if(typeof place==='function'){place('cold','one creditor recovered the contract everyone else voted away',realm(c.debtor));place('dream','seventy-seven percent was a majority until a court asked which seventy-seven percent',realm(c.debtor))}restructuringCrisis(c.debtor,'holdout creditor escaped a formally sufficient restructuring','SEV1')}else remember('HOLDOUT DENIED '+act.id+': collective-action vote remained binding against '+claim.holder,realm(c.debtor));if(manual){$('#msg').textContent=act.id+' '+act.status.toUpperCase()+(act.recovery?' · '+act.recovery.toFixed(1)+' face value restored.':'.');renderAll();save62();openHoldout(act)}return act}
function accelerateFailed(c,manual=true){if(!c||c.status!=='failed')return null;let claim=claims62(c).find(x=>x.kind==='archive'&&x.status==='holdout')||claims62(c).find(x=>x.status==='holdout')||claims62(c).find(x=>x.vote==='no');if(!claim)return null;let acct=acct62(c.debtor),penalty=Math.min(2,claim.principal*.12),a=award62(c.debtor),act={id:'HLD'+(++S.holdoutActionSerial62),conferenceId:c.id,offerId:offer62(c)?.id||null,claimId:claim.id,type:'acceleration',status:'accelerated',penalty,created:Date.now(),x:10+Math.random()*80,y:12+Math.random()*68};S.holdoutActions62.push(act);claim.status='accelerated-holdout';if(acct)acct.arrears=(acct.arrears||0)+penalty;if(a){a.lien=true;a.baselineReserves=currency62(c.debtor)?.foreignReserves||0}remember('HOLDOUT ACCELERATION '+act.id+': '+claim.holder+' converted failed restructuring talks into '+penalty.toFixed(1)+' of immediate arrears',realm(c.debtor));if(typeof place==='function')place('cold','minority creditor inherited the calendar',realm(c.debtor));restructuringCrisis(c.debtor,'failed exchange became accelerated arrears','SEV1');if(manual){$('#msg').textContent=act.id+' accelerated the holdout claim and added '+penalty.toFixed(1)+' of arrears.';renderAll();save62();openHoldout(act)}return act}
function reconcileRestructuring(){if(!ensureOffice())return;for(const c of S.debtConferences62.filter(c=>c.standstill)){let a=(S.remedyAwards61||[]).find(a=>a.id===c.awardId);if(a){a.lien=false;a.standstill62=c.id}if((acct62(c.debtor)?.externalDebt||0)<=0){c.status='closed';releaseStandstill(c)}}}
function openClaim(claim){let c=S.debtConferences62.find(c=>c.id===claim.conferenceId),acts=[['open conference',()=>openConference(c)],['close',closePanel]];panel(claim.id+' · '+claim.kind.toUpperCase(),claim.status.toUpperCase(),claim.holder+' · vote '+(claim.vote||'pending')+' · '+claim.principal.toFixed(2)+' face · '+(claim.share*100).toFixed(0)+'% voting weight'+(claim.bound?' · collectively bound':''),acts)}
function openBond(b){let c=S.debtConferences62.find(c=>c.id===b.conferenceId);panel(b.id+' · EXCHANGE BOND',b.status.toUpperCase(),'Reality '+b.debtor+' · principal '+b.principal.toFixed(2)+' '+b.currency+' · coupon '+(b.coupon*100).toFixed(1)+'% · maturity '+b.maturityMonths+' months',[['open restructuring',()=>openConference(c)],['close',closePanel]])}
function openHoldout(h){let c=S.debtConferences62.find(c=>c.id===h.conferenceId),claim=S.debtClaims62.find(x=>x.id===h.claimId);panel(h.id+' · HOLDOUT ACTION',h.status.toUpperCase(),(claim?.holder||'creditor')+' · '+h.type+(h.recovery?' · restored '+h.recovery.toFixed(2):'')+(h.penalty?' · arrears '+h.penalty.toFixed(2):''),[['open creditor claim',()=>openClaim(claim)],['open conference',()=>openConference(c)],['close',closePanel]])}
function openOffer(o){let c=S.debtConferences62.find(c=>c.id===o.conferenceId),acts=[];if(['draft','voting'].includes(o.status))acts.push(['hold creditor vote',()=>voteOffer(o,true)]);acts.push(['open conference',()=>openConference(c)],['close',closePanel]);panel(o.id+' · DEBT EXCHANGE',o.status.toUpperCase(),(o.haircut*100).toFixed(0)+'% haircut · '+(o.coupon*100).toFixed(1)+'% coupon · '+o.maturityMonths+' months · CAC '+(o.cacThreshold*100).toFixed(0)+'%'+(o.decided?' · yes '+o.yesWeight.toFixed(1)+'% / no '+o.noWeight.toFixed(1)+'%':''),acts)}
function openConference(c){let o=offer62(c),acts=[];if(c.status==='convened')acts.push(['draft moderate exchange',()=>draftOffer(c,'moderate',true)],['draft deep exchange',()=>draftOffer(c,'deep',true)]);if(o&&['draft','voting'].includes(o.status))acts.push(['open '+o.id,()=>openOffer(o)]);if(c.status==='restructured'&&claims62(c).some(x=>x.status==='bound-holdout'))acts.push(['holdout challenges collective action',()=>challengeHoldout(c,true)]);if(c.status==='failed')acts.push(['holdout accelerates claim',()=>accelerateFailed(c,true)]);for(const claim of claims62(c))acts.push(['open '+claim.id+' · '+claim.kind,()=>openClaim(claim)]);for(const b of S.exchangeBonds62.filter(b=>b.conferenceId===c.id))acts.push(['open '+b.id+' · exchange bond',()=>openBond(b)]);for(const h of S.holdoutActions62.filter(h=>h.conferenceId===c.id).slice(-3))acts.push(['open '+h.id+' · '+h.status,()=>openHoldout(h)]);acts.push(['open restructuring office',openOffice],['close',closePanel]);panel(c.id+' · CREDITOR CONFERENCE',c.status.toUpperCase()+(c.standstill?' · STANDSTILL':''),'Reality '+c.debtor+' · face debt '+c.faceDebt.toFixed(2)+' · current debt '+(acct62(c.debtor)?.externalDebt||0).toFixed(2)+' · CAC '+(c.cacThreshold*100).toFixed(0)+'%'+(c.haircutAmount?' · haircut '+c.haircutAmount.toFixed(2):''),acts)}
function openOffice(){if(!ensureOffice()){if($('#msg'))$('#msg').textContent='Build 61 remedies are not available yet.';return}let acts=[['convene Reality '+S.active+' creditor conference',()=>conveneConference(S.active,true)]];for(const c of S.debtConferences62.slice(-5))acts.push(['open '+c.id+' · Reality '+c.debtor+' · '+c.status,()=>openConference(c)]);acts.push(['close',closePanel]);panel(S.restructuringOffice62.name,S.restructuringOffice62.status.toUpperCase()+' · '+S.restructuringOffice62.id,S.debtConferences62.length+' conferences · '+S.restructuringsCompleted62+' completed · '+S.restructuringsFailed62+' failed · '+S.cacBindings62+' bound dissenters · '+S.holdoutVictories62+' holdout victories · '+S.debtHaircuts62.toFixed(1)+' debt written down · '+S.restructuringCrises62+' crises',acts)}
function autonomous(){ensureOffice();let now=Date.now();if(now-S.lastRestructuringTick62<2100)return;S.lastRestructuringTick62=now;reconcileRestructuring();let acct=acct62(S.active);if((acct?.externalDebt||0)>8&&!conference62(S.active)&&Math.random()<.0007)conveneConference(S.active,false);let c=conference62(S.active);if(c?.status==='convened'&&Math.random()<.0007)draftOffer(c,'moderate',false);let o=c&&offer62(c);if(o?.status==='draft'&&Math.random()<.0007)voteOffer(o,false)}
function renderRestructuring(){if(!ensureOffice())return;let layer=$('#restructuringLayer');if(!layer){layer=document.createElement('div');layer.id='restructuringLayer';document.body.appendChild(layer)}layer.innerHTML='';let office=S.restructuringOffice62,oe=document.createElement('i');oe.className='restructuringOffice';oe.dataset.label='DEBT';oe.style.left=office.x+'%';oe.style.top=office.y+'%';oe.onclick=openOffice;layer.appendChild(oe);for(const c of S.debtConferences62.slice(-6)){let e=document.createElement('i');e.className='debtConference '+c.status+(c.standstill?' standstill':'');e.dataset.label='CAC';e.style.left=c.x+'%';e.style.top=c.y+'%';e.onclick=()=>openConference(c);layer.appendChild(e)}for(const claim of S.debtClaims62.filter(x=>['holdout','bound-holdout','holdout-restored','accelerated-holdout'].includes(x.status)).slice(-8)){let e=document.createElement('i');e.className='debtHoldout '+claim.status;e.dataset.label='NO';e.style.left=claim.x+'%';e.style.top=claim.y+'%';e.onclick=()=>openClaim(claim);layer.appendChild(e)}for(const b of S.exchangeBonds62.slice(-6)){let e=document.createElement('i');e.className='exchangeBond';e.dataset.label='BOND';e.style.left=b.x+'%';e.style.top=b.y+'%';e.onclick=()=>openBond(b);layer.appendChild(e)}let line=$('#restructuringline');if(!line){line=document.createElement('div');line.id='restructuringline';line.className='line';($('#remedyline')||$('#treatyline')||$('#fundgovernanceline')||$('#enforcement')).after(line)}line.textContent='debt restructuring: '+S.debtConferences62.length+' conferences · '+S.restructuringsCompleted62+' exchanges · '+S.restructuringsFailed62+' failed · '+S.cacBindings62+' dissenters bound · '+S.holdoutVictories62+' holdout wins · '+S.debtHaircuts62.toFixed(1)+' written down · '+S.restructuringCrises62+' crises';let ctr=document.querySelector('#app .controls');if(ctr&&!$('#openRestructuringButton')){let x=document.createElement('button');x.id='openRestructuringButton';x.textContent='open debt restructuring';x.onclick=openOffice;ctr.prepend(x)}if(ctr&&!$('#conveneCreditorsButton')){let x=document.createElement('button');x.id='conveneCreditorsButton';x.textContent='convene creditors';x.onclick=()=>conveneConference(S.active,true);ctr.prepend(x)}}
renderAll=function(){BR62();reconcileRestructuring();renderRestructuring()};let f=$('#forget');if(f)f.onclick=()=>{for(let i=2;i<=62;i++)localStorage.removeItem('nothing-state-v'+i);location.reload()};
setInterval(()=>{autonomous();renderRestructuring();save62()},2300);ensureOffice();reconcileRestructuring();renderAll();save62();
})();
