(()=>{
const BS58=save,BR58=renderAll,O58=JSON.parse(localStorage.getItem('nothing-state-v58')||'null')||{},cl=(v,a,b)=>Math.max(a,Math.min(b,v)),pick=a=>a&&a.length?a[Math.floor(Math.random()*a.length)]:null;
S.stabilizationFunds58=O58.stabilizationFunds58||[];
S.stabilizationQuotas58=O58.stabilizationQuotas58||[];
S.stabilizationPrograms58=O58.stabilizationPrograms58||[];
S.stabilizationConditions58=O58.stabilizationConditions58||[];
S.stabilizationReviews58=O58.stabilizationReviews58||[];
S.debtRestructurings58=O58.debtRestructurings58||[];
S.drawingRights58=O58.drawingRights58||[];
S.stabilizationFundSerial58=O58.stabilizationFundSerial58||0;
S.stabilizationProgramSerial58=O58.stabilizationProgramSerial58||0;
S.stabilizationConditionSerial58=O58.stabilizationConditionSerial58||0;
S.stabilizationReviewSerial58=O58.stabilizationReviewSerial58||0;
S.debtRestructuringSerial58=O58.debtRestructuringSerial58||0;
S.drawingRightSerial58=O58.drawingRightSerial58||0;
S.stabilizationProgramsOpened58=O58.stabilizationProgramsOpened58||0;
S.stabilizationDisbursements58=O58.stabilizationDisbursements58||0;
S.stabilizationReviewsPassed58=O58.stabilizationReviewsPassed58||0;
S.stabilizationReviewsFailed58=O58.stabilizationReviewsFailed58||0;
S.stabilizationWaivers58=O58.stabilizationWaivers58||0;
S.debtRestructuringsDone58=O58.debtRestructuringsDone58||0;
S.drawingRightsAllocated58=O58.drawingRightsAllocated58||0;
S.stabilizationCrises58=O58.stabilizationCrises58||0;
S.lastStabilizationCrisis58=O58.lastStabilizationCrisis58||0;
S.stabilizationKeys58=O58.stabilizationKeys58||{};
S.lastStabilizationTick58=O58.lastStabilizationTick58||Date.now();
function save58(){BS58();localStorage.setItem('nothing-state-v58',JSON.stringify({stabilizationFunds58:S.stabilizationFunds58,stabilizationQuotas58:S.stabilizationQuotas58,stabilizationPrograms58:S.stabilizationPrograms58,stabilizationConditions58:S.stabilizationConditions58,stabilizationReviews58:S.stabilizationReviews58,debtRestructurings58:S.debtRestructurings58,drawingRights58:S.drawingRights58,stabilizationFundSerial58:S.stabilizationFundSerial58,stabilizationProgramSerial58:S.stabilizationProgramSerial58,stabilizationConditionSerial58:S.stabilizationConditionSerial58,stabilizationReviewSerial58:S.stabilizationReviewSerial58,debtRestructuringSerial58:S.debtRestructuringSerial58,drawingRightSerial58:S.drawingRightSerial58,stabilizationProgramsOpened58:S.stabilizationProgramsOpened58,stabilizationDisbursements58:S.stabilizationDisbursements58,stabilizationReviewsPassed58:S.stabilizationReviewsPassed58,stabilizationReviewsFailed58:S.stabilizationReviewsFailed58,stabilizationWaivers58:S.stabilizationWaivers58,debtRestructuringsDone58:S.debtRestructuringsDone58,drawingRightsAllocated58:S.drawingRightsAllocated58,stabilizationCrises58:S.stabilizationCrises58,lastStabilizationCrisis58:S.lastStabilizationCrisis58,stabilizationKeys58:S.stabilizationKeys58,lastStabilizationTick58:S.lastStabilizationTick58}))}save=save58;
const realm=id=>S.real[id],acct=id=>(S.tradeAccounts57||[]).find(a=>a.reality===id),cur=id=>(S.fxCurrencies56||[]).find(c=>c.reality===id),bank=id=>(S.monetaryAuthorities55||[]).find(a=>a.reality===id),other=id=>id==='A'?'B':'A',domestic=id=>'R'+id,foreign=id=>'R'+other(id),fund=()=>S.stabilizationFunds58[0],program=id=>S.stabilizationPrograms58.find(p=>p.id===id);
function trust58(id,status,note){let accepted=S.trustPolicies?.[id]?.acceptedRoots||[],r=[...(S.trustRoots||[])].filter(x=>accepted.includes(x.id)&&x.status==='active').sort((a,b)=>(b.strength||0)-(a.strength||0))[0];S.trustAudits=S.trustAudits||[];S.trustAuditSerial=S.trustAuditSerial||0;S.trustAudits.push({id:'TA'+(++S.trustAuditSerial),reality:id,remediationId:null,credentialId:null,certificateId:null,rootId:r?.id||null,status,created:Date.now(),note,x:10+Math.random()*80,y:12+Math.random()*68})}
function incident58(id,title,severity='SEV2'){S.incidents=S.incidents||[];let ex=S.incidents.find(i=>i.reality===id&&i.title===title&&i.status==='open');if(ex)return ex;S.incidentSerial=S.incidentSerial||0;let x={id:'INC'+(++S.incidentSerial),reality:id,title,severity,status:'open',alertIds:[],started:Date.now(),acknowledged:null,resolved:null,postmortem:null,owner:'interreality stabilization fund',x:10+Math.random()*80,y:12+Math.random()*68};S.incidents.push(x);return x}
function ensureFund(){if(!fund()){let ca=cur('A'),cb=cur('B'),takeRB=Math.min(6,ca?.foreignReserves||0),takeRA=Math.min(6,cb?.foreignReserves||0);if(ca)ca.foreignReserves=Math.max(0,ca.foreignReserves-takeRB);if(cb)cb.foreignReserves=Math.max(0,cb.foreignReserves-takeRA);let f={id:'ISF'+(++S.stabilizationFundSerial58),name:'Interreality Stabilization Fund',status:'operating',poolRA:takeRA,poolRB:takeRB,drawingUnit:'RDR',credibility:.8,independence:.78,conditionality:.65,programs:0,waivers:0,created:Date.now(),x:50,y:27};S.stabilizationFunds58.push(f);S.stabilizationQuotas58.push({reality:'A',quota:10,votes:50,rdr:4,contributedRA:0,contributedRB:takeRB},{reality:'B',quota:10,votes:50,rdr:4,contributedRA:takeRA,contributedRB:0});remember('STABILIZATION FUND '+f.id+': A and B pooled foreign reserves to create a lender for balance-of-payments crises',realm('A'));remember('STABILIZATION FUND '+f.id+': A and B pooled foreign reserves to create a lender for balance-of-payments crises',realm('B'));trust58('A','interreality-stabilization-fund-created',f.id+' pooled RA/RB reserves');trust58('B','interreality-stabilization-fund-created',f.id+' pooled RA/RB reserves')}}
function quota(id){ensureFund();return S.stabilizationQuotas58.find(q=>q.reality===id)}
function poolFor(code){let f=fund();return code==='RA'?f.poolRA:f.poolRB}
function addPool(code,v){let f=fund();if(code==='RA')f.poolRA=Math.max(0,f.poolRA+v);else f.poolRB=Math.max(0,f.poolRB+v)}
function reserveNeed(id){let a=acct(id),c=cur(id);if(!a||!c)return 6;return cl(5+Math.max(0,-a.currentAccount)*.3+(a.arrears||0)*.7+(a.externalDebt||0)*.22+Math.max(0,6-c.foreignReserves),5,28)}
function stabilizationCrisis(id,kind,severity='SEV2'){let now=Date.now(),k=id+'|'+kind;if(S.stabilizationKeys58[k]&&now-S.stabilizationKeys58[k]<14000)return;S.stabilizationKeys58[k]=now;S.stabilizationCrises58++;S.lastStabilizationCrisis58=now;remember('STABILIZATION CRISIS: '+kind+' made foreign-reserve rescue a source of software-policy authority',realm(id));if(typeof place==='function'){place('cold','foreign reserves arriving with software policy attached',realm(id));place('dream','balance-of-payments lender sitting inside package governance',realm(id))}let b=$('#bailiff');if(b)b.textContent='asking whether the rescue loan is financing policy or buying it';incident58(id,'interreality stabilization crisis: '+kind,severity)}
function addCondition(p,type,target,note){let c={id:'COND'+(++S.stabilizationConditionSerial58),programId:p.id,reality:p.reality,type,target,note,status:'pending',created:Date.now(),x:10+Math.random()*80,y:12+Math.random()*68};S.stabilizationConditions58.push(c);p.conditionIds.push(c.id);return c}
function applyImportCompression(id){let a=acct(id);if(a)a.compression=true;let cs=(S.tradeContracts57||[]).filter(c=>c.importerReality===id&&c.status==='active').sort((a,b)=>(a.criticality||0)-(b.criticality||0));for(const c of cs.slice(0,Math.max(1,Math.floor(cs.length/2)))){c.status='suspended';c.suspensionReason='stabilization conditionality: import compression';S.tradeSuspensions57=(S.tradeSuspensions57||0)+1}if(typeof place==='function')place('cold','dependency austerity written into rescue terms',realm(id))}
function applyMonetaryTightening(id,target){let a=bank(id);if(a)a.discountRate=Math.max(a.discountRate||0,target)}
function applyFxFlexibility(id){let c=cur(id);if(c&&c.peg){c.status='floating';c.peg=null;S.fxPegBreaks56=(S.fxPegBreaks56||0)+1;remember('PROGRAM EXCHANGE-RATE CONDITION: Reality '+id+' abandoned its peg as a stabilization condition',realm(id))}}
function applyPackageRevenueReform(id){for(const n of (S.namespaces46||[]).filter(n=>n.reality===id)){let t=(S.packageTreasuries47||[]).find(t=>t.namespaceId===n.id);if(t&&t.status!=='bankrupt')t.taxRate=cl((t.taxRate||1)+.2,.25,4)}}
function applyConditions(p){for(const c of S.stabilizationConditions58.filter(c=>c.programId===p.id)){if(c.type==='import-compression')applyImportCompression(p.reality);if(c.type==='monetary-tightening')applyMonetaryTightening(p.reality,c.target);if(c.type==='fx-flexibility')applyFxFlexibility(p.reality);if(c.type==='package-revenue-reform')applyPackageRevenueReform(p.reality)}}
function openProgram(id,manual=true){ensureFund();let existing=[...S.stabilizationPrograms58].reverse().find(p=>p.reality===id&&['active','off-track'].includes(p.status));if(existing){if(manual)openProgramPanel(existing);return existing}let a=acct(id),c=cur(id);if(!a||!c)return null;let need=reserveNeed(id),code=foreign(id),available=poolFor(code),committed=Math.min(need,Math.max(4,available*.8)),p={id:'PRG'+(++S.stabilizationProgramSerial58),reality:id,status:'active',currency:code,committed,disbursed:0,remaining:committed,rate:.045,conditionIds:[],reviewNumber:0,nextReview:Date.now()+18000,baselineCurrentAccount:a.currentAccount,baselineReserves:c.foreignReserves,baselineDebt:a.externalDebt||0,waived:false,created:Date.now(),x:10+Math.random()*80,y:12+Math.random()*68};S.stabilizationPrograms58.push(p);S.stabilizationProgramsOpened58++;fund().programs++;addCondition(p,'import-compression',true,'reduce noncritical software-support imports');addCondition(p,'monetary-tightening',Math.min(.22,(bank(id)?.discountRate||.05)+.025),'raise emergency-credit price');addCondition(p,'fx-flexibility',true,'allow exchange rate to absorb external imbalance');addCondition(p,'package-revenue-reform',true,'increase domestic dependency-support revenue');applyConditions(p);remember('STABILIZATION PROGRAM '+p.id+': Reality '+id+' accepted '+committed.toFixed(1)+' '+code+' of reserve support with software-economy conditions',realm(id));trust58(id,'interreality-stabilization-program',p.id+' '+committed.toFixed(1)+' '+code);disburse(p,Math.min(committed*.35,6),false);stabilizationCrisis(id,'foreign-reserve rescue acquired policy conditions');if(manual){$('#msg').textContent=p.id+' approved '+committed.toFixed(1)+' '+code+' with conditionality.';renderAll();save58();openProgramPanel(p)}return p}
function disburse(p,amount=null,manual=true){if(!p||!['active','off-track'].includes(p.status)||p.remaining<=.01)return 0;let c=cur(p.reality),f=fund(),pool=poolFor(p.currency),x=Math.min(amount??Math.max(2,p.committed*.25),p.remaining,pool);if(x<=.01){p.status='funding-shortfall';stabilizationCrisis(p.reality,'stabilization fund ran out of the reserve asset it promised','SEV1');return 0}addPool(p.currency,-x);c.foreignReserves+=x;p.disbursed+=x;p.remaining-=x;S.stabilizationDisbursements58+=x;remember('STABILIZATION TRANCHE '+p.id+': '+x.toFixed(1)+' '+p.currency+' restored foreign-reserve capacity for Reality '+p.reality,realm(p.reality));if(typeof place==='function')place('warm','foreign reserves arrived after policy review',realm(p.reality));if(manual){$('#msg').textContent=p.id+' disbursed '+x.toFixed(1)+' '+p.currency+'.';renderAll();save58();openProgramPanel(p)}return x}
function conditionMet(c,p){let id=p.reality;if(c.type==='import-compression')return !!acct(id)?.compression;if(c.type==='monetary-tightening')return (bank(id)?.discountRate||0)+1e-9>=c.target;if(c.type==='fx-flexibility')return !cur(id)?.peg;if(c.type==='package-revenue-reform'){let ts=(S.packageTreasuries47||[]).filter(t=>t.reality===id);return !ts.length||ts.filter(t=>(t.taxRate||1)>=1.2).length>=Math.ceil(ts.length*.6)}return false}
function reviewProgram(p,manual=true){if(!p||!['active','off-track'].includes(p.status))return null;p.reviewNumber++;let cs=S.stabilizationConditions58.filter(c=>c.programId===p.id),failed=[];for(const c of cs){let ok=conditionMet(c,p);c.status=ok?'met':'failed';c.lastReview=Date.now();if(!ok)failed.push(c)}let a=acct(p.reality),c=cur(p.reality),macroPass=(a?.currentAccount??0)>=p.baselineCurrentAccount-2 || (c?.foreignReserves||0)>=p.baselineReserves;let passed=!failed.length&&macroPass,r={id:'REV'+(++S.stabilizationReviewSerial58),programId:p.id,reality:p.reality,number:p.reviewNumber,status:passed?'passed':'failed',failedConditions:failed.map(x=>x.id),currentAccount:a?.currentAccount||0,reserves:c?.foreignReserves||0,externalDebt:a?.externalDebt||0,created:Date.now(),x:10+Math.random()*80,y:12+Math.random()*68};S.stabilizationReviews58.push(r);if(passed){S.stabilizationReviewsPassed58++;p.status='active';p.nextReview=Date.now()+18000;disburse(p,null,false);remember('PROGRAM REVIEW PASSED '+r.id+': Reality '+p.reality+' unlocked the next reserve tranche',realm(p.reality));if(p.remaining<=.01)p.status='completed'}else{S.stabilizationReviewsFailed58++;p.status='off-track';p.nextReview=Date.now()+18000;remember('PROGRAM REVIEW FAILED '+r.id+': next reserve tranche withheld from Reality '+p.reality,realm(p.reality));if(typeof place==='function')place('cold','software support waiting for a macroeconomic review',realm(p.reality));stabilizationCrisis(p.reality,'failed review withheld foreign reserves','SEV1')}if(manual){$('#msg').textContent=r.id+' '+r.status.toUpperCase()+'. '+(passed?'Next tranche released.':'Foreign-reserve tranche withheld.');renderAll();save58();openReview(r)}return r}
function waiveReview(r,manual=true){if(!r||r.status!=='failed')return;let p=program(r.programId),f=fund();r.status='waived';r.waived=Date.now();p.status='active';p.waived=true;f.waivers++;f.independence=cl(f.independence-.06,0,1);f.credibility=cl(f.credibility-.04,0,1);S.stabilizationWaivers58++;disburse(p,null,false);remember('PROGRAM WAIVER '+r.id+': reserve tranche released despite failed conditions',realm(p.reality));if(typeof place==='function')place('dream','conditionality suspended because withholding reserves became too dangerous',realm(p.reality));stabilizationCrisis(p.reality,'failed conditions waived to preserve stability');if(manual){renderAll();save58();openReview(r)}}
function restructureDebt(id,manual=true){let ds=(S.externalDebts57||[]).filter(d=>d.debtorReality===id&&['active','arrears','default'].includes(d.status));if(!ds.length){if(manual)$('#msg').textContent='No external software debt is available to restructure.';return null}let totalBefore=ds.reduce((n,d)=>n+(d.principal||0)+(d.accrued||0),0),haircut=.2,loss=0;for(const d of ds){let cut=(d.principal||0)*haircut;d.principal=Math.max(0,(d.principal||0)-cut);d.accrued*=.5;d.rate=Math.max(.035,(d.rate||.085)-.02);d.nextService=Date.now()+30000;d.status='active';d.misses=0;loss+=cut;let c=(S.tradeContracts57||[]).find(c=>c.id===d.contractId);if(c&&c.status==='suspended'&&String(c.suspensionReason||'').includes('external debt default')){c.status='active';c.suspensionReason='restructured under stabilization program'}}let r={id:'RST'+(++S.debtRestructuringSerial58),reality:id,debtIds:ds.map(d=>d.id),haircut,totalBefore,totalAfter:Math.max(0,totalBefore-loss),creditorLoss:loss,created:Date.now(),x:10+Math.random()*80,y:12+Math.random()*68};S.debtRestructurings58.push(r);S.debtRestructuringsDone58++;remember('EXTERNAL DEBT RESTRUCTURING '+r.id+': software suppliers absorbed '+loss.toFixed(1)+' foreign-currency credits of losses so Reality '+id+' could resume service',realm(id));remember('CREDITOR LOSS '+r.id+': Reality '+other(id)+' software exporters accepted restructuring losses',realm(other(id)));if(typeof place==='function'){place('warm','foreign software debt restructured without deleting the dependency',realm(id));place('cold','supplier balance sheet absorbed the rescue haircut',realm(other(id)))}trust58(id,'interreality-debt-restructuring',r.id+' '+(haircut*100).toFixed(0)+'% haircut');if(manual){$('#msg').textContent=r.id+' cut '+loss.toFixed(1)+' foreign-currency credits from external software debt.';renderAll();save58();openRestructuring(r)}return r}
function allocateDrawingRights(manual=true){ensureFund();let f=fund(),amount=4;for(const id of ['A','B']){let q=quota(id);q.rdr+=amount;let d={id:'RDR'+(++S.drawingRightSerial58),reality:id,amount,created:Date.now(),status:'allocated',x:10+Math.random()*80,y:12+Math.random()*68};S.drawingRights58.push(d);S.drawingRightsAllocated58+=amount}f.credibility=cl(f.credibility-.005,0,1);remember('RDR ALLOCATION: stabilization fund created '+amount+' reserve drawing rights for each reality',realm('A'));remember('RDR ALLOCATION: stabilization fund created '+amount+' reserve drawing rights for each reality',realm('B'));trust58('A','interreality-drawing-right-allocation',amount+' RDR');trust58('B','interreality-drawing-right-allocation',amount+' RDR');if(manual){$('#msg').textContent='The fund allocated '+amount+' RDR to each reality.';renderAll();save58();openFund()}}
function exchangeDrawingRights(id,manual=true){let q=quota(id),code=foreign(id),pool=poolFor(code),use=Math.min(q.rdr,3,pool);if(use<=.01){if(manual)$('#msg').textContent='No usable drawing rights or foreign reserve pool remain.';return 0}q.rdr-=use;addPool(code,-use);cur(id).foreignReserves+=use;remember('RDR EXCHANGE: Reality '+id+' exchanged '+use.toFixed(1)+' drawing rights for '+code+' reserves',realm(id));if(manual){$('#msg').textContent=id+' exchanged '+use.toFixed(1)+' RDR for '+code+'.';renderAll();save58();openFund()}return use}
function openReview(r){let p=program(r.programId),acts=[];if(r.status==='failed')acts.push(['waive failed review',()=>waiveReview(r,true)]);acts.push(['open program',()=>openProgramPanel(p)],['close',closePanel]);panel(r.id+' · PROGRAM REVIEW',r.status.toUpperCase()+' · review '+r.number,'current account '+r.currentAccount.toFixed(1)+' · reserves '+r.reserves.toFixed(1)+' · external debt '+r.externalDebt.toFixed(1)+' · failed conditions '+r.failedConditions.length,acts)}
function openRestructuring(r){panel(r.id+' · DEBT RESTRUCTURING',(r.haircut*100).toFixed(0)+'% principal haircut','before '+r.totalBefore.toFixed(1)+' · after '+r.totalAfter.toFixed(1)+' · creditor loss '+r.creditorLoss.toFixed(1),[['close',closePanel]])}
function openProgramPanel(p){let cs=S.stabilizationConditions58.filter(c=>c.programId===p.id),rs=S.stabilizationReviews58.filter(r=>r.programId===p.id),acts=[];if(['active','off-track'].includes(p.status))acts.push(['run program review',()=>reviewProgram(p,true)]);acts.push(['restructure external debt',()=>restructureDebt(p.reality,true)]);for(const r of rs.slice(-3))acts.push(['open '+r.id+' · '+r.status,()=>openReview(r)]);acts.push(['close',closePanel]);panel(p.id+' · STABILIZATION PROGRAM',p.status.toUpperCase()+' · Reality '+p.reality,p.disbursed.toFixed(1)+'/'+p.committed.toFixed(1)+' '+p.currency+' disbursed · '+p.remaining.toFixed(1)+' remaining · conditions '+cs.map(c=>c.type+':'+c.status).join(' · '),acts)}
function openFund(){ensureFund();let f=fund(),acts=[['allocate drawing rights',()=>allocateDrawingRights(true)],['exchange A RDR for RB',()=>exchangeDrawingRights('A',true)],['exchange B RDR for RA',()=>exchangeDrawingRights('B',true)],['open program for A',()=>openProgram('A',true)],['open program for B',()=>openProgram('B',true)]];for(const p of S.stabilizationPrograms58.slice(-4))acts.push(['open '+p.id+' · '+p.reality+' '+p.status,()=>openProgramPanel(p)]);acts.push(['close',closePanel]);panel(f.name+' · '+f.status.toUpperCase(),f.id+' · pooled lender of foreign reserves','pool RA '+f.poolRA.toFixed(1)+' · pool RB '+f.poolRB.toFixed(1)+' · credibility '+f.credibility.toFixed(2)+' · independence '+f.independence.toFixed(2)+' · '+S.stabilizationPrograms58.length+' programs · '+S.stabilizationCrises58+' crises',acts)}
function stressStabilization(id=S.active){let a=acct(id),c=cur(id);if(a){a.currentAccount=Math.min(a.currentAccount,-12);a.arrears=Math.max(a.arrears,7);a.externalDebt=Math.max(a.externalDebt,14)}if(c)c.foreignReserves=Math.min(c.foreignReserves,1.5);let p=openProgram(id,false);if(p){let cond=S.stabilizationConditions58.find(c=>c.programId===p.id&&c.type==='monetary-tightening');if(cond){let b=bank(id);if(b)b.discountRate=Math.max(.005,cond.target-.04)}reviewProgram(p,false)}renderAll();save58();openFund()}
function autonomous(){ensureFund();let now=Date.now();if(now-S.lastStabilizationTick58<2200)return;S.lastStabilizationTick58=now;for(const id of ['A','B']){let a=acct(id),c=cur(id),p=[...S.stabilizationPrograms58].reverse().find(p=>p.reality===id&&['active','off-track'].includes(p.status));if(!p&&a&&c&&(c.foreignReserves<2||(a.arrears||0)>6||(a.externalDebt||0)>18)&&Math.random()<.004){openProgram(id,false);break}if(p&&p.nextReview<=now&&Math.random()<.12){reviewProgram(p,false);break}}}
function renderStabilization(){ensureFund();let layer=$('#stabilizationLayer');if(!layer){layer=document.createElement('div');layer.id='stabilizationLayer';document.body.appendChild(layer)}layer.innerHTML='';let f=fund(),fe=document.createElement('i');fe.className='stabilizationFund '+f.status;fe.dataset.label='ISF';fe.style.left=f.x+'%';fe.style.top=f.y+'%';fe.onclick=openFund;layer.appendChild(fe);for(const p of S.stabilizationPrograms58.filter(p=>['active','off-track','funding-shortfall'].includes(p.status)).slice(-8)){let e=document.createElement('i');e.className='stabilizationProgram '+p.status;e.dataset.label=p.id;e.style.left=p.x+'%';e.style.top=p.y+'%';e.onclick=()=>openProgramPanel(p);layer.appendChild(e)}for(const r of S.stabilizationReviews58.filter(r=>['failed','waived'].includes(r.status)).slice(-8)){let e=document.createElement('i');e.className='stabilizationReview '+r.status;e.dataset.label='REV';e.style.left=r.x+'%';e.style.top=r.y+'%';e.onclick=()=>openReview(r);layer.appendChild(e)}let line=$('#stabilizationline');if(!line){line=document.createElement('div');line.id='stabilizationline';line.className='line';($('#tradeline')||$('#fxline')||$('#monetaryline')||$('#enforcement')).after(line)}let p=[...S.stabilizationPrograms58].reverse().find(p=>p.reality===S.active&&['active','off-track','funding-shortfall'].includes(p.status));line.textContent='stabilization fund: pool RA '+f.poolRA.toFixed(1)+' · RB '+f.poolRB.toFixed(1)+' · RDR A '+quota('A').rdr.toFixed(1)+' / B '+quota('B').rdr.toFixed(1)+' · '+(p?('Reality '+S.active+' '+p.status+' '+p.disbursed.toFixed(1)+'/'+p.committed.toFixed(1)):'no active '+S.active+' program')+' · '+S.stabilizationCrises58+' crises';let ctr=document.querySelector('#app .controls');if(ctr&&!$('#openStabilizationButton')){let x=document.createElement('button');x.id='openStabilizationButton';x.textContent='open stabilization fund';x.onclick=openFund;ctr.prepend(x)}if(ctr&&!$('#requestStabilizationButton')){let x=document.createElement('button');x.id='requestStabilizationButton';x.textContent='request reserve program';x.onclick=()=>openProgram(S.active,true);ctr.prepend(x)}if(ctr&&!$('#stressStabilizationButton')){let x=document.createElement('button');x.id='stressStabilizationButton';x.textContent='stress stabilization program';x.onclick=()=>stressStabilization(S.active);ctr.prepend(x)}}
renderAll=function(){BR58();renderStabilization()};let f=$('#forget');if(f)f.onclick=()=>{for(let i=2;i<=58;i++)localStorage.removeItem('nothing-state-v'+i);location.reload()};
setInterval(()=>{autonomous();renderStabilization();save58()},2400);ensureFund();renderAll();save58();
})();
