(()=>{
const BS50=save,BR50=renderAll,O50=JSON.parse(localStorage.getItem('nothing-state-v50')||'null')||{},cl=(v,a,b)=>Math.max(a,Math.min(b,v)),pick=a=>a&&a.length?a[Math.floor(Math.random()*a.length)]:null;
S.standardsBodies50=O50.standardsBodies50||[];
S.standards50=O50.standards50||[];
S.certifications50=O50.certifications50||[];
S.standardAudits50=O50.standardAudits50||[];
S.standardBodySerial50=O50.standardBodySerial50||0;
S.standardSerial50=O50.standardSerial50||0;
S.certificationSerial50=O50.certificationSerial50||0;
S.standardAuditSerial50=O50.standardAuditSerial50||0;
S.standardsRatified50=O50.standardsRatified50||0;
S.certificationsIssued50=O50.certificationsIssued50||0;
S.certificationsFailed50=O50.certificationsFailed50||0;
S.selfCertified50=O50.selfCertified50||0;
S.standardCaptures50=O50.standardCaptures50||0;
S.grandfatheredContracts50=O50.grandfatheredContracts50||0;
S.noncompliantBids50=O50.noncompliantBids50||0;
S.standardAmendments50=O50.standardAmendments50||0;
S.mutualRecognitions50=O50.mutualRecognitions50||0;
S.standardDivergences50=O50.standardDivergences50||0;
S.standardsCrises50=O50.standardsCrises50||0;
S.lastStandardsCrisis50=O50.lastStandardsCrisis50||0;
S.standardsKeys50=O50.standardsKeys50||{};
S.lastStandardsTick50=O50.lastStandardsTick50||Date.now();
function save50(){BS50();localStorage.setItem('nothing-state-v50',JSON.stringify({standardsBodies50:S.standardsBodies50,standards50:S.standards50,certifications50:S.certifications50,standardAudits50:S.standardAudits50,standardBodySerial50:S.standardBodySerial50,standardSerial50:S.standardSerial50,certificationSerial50:S.certificationSerial50,standardAuditSerial50:S.standardAuditSerial50,standardsRatified50:S.standardsRatified50,certificationsIssued50:S.certificationsIssued50,certificationsFailed50:S.certificationsFailed50,selfCertified50:S.selfCertified50,standardCaptures50:S.standardCaptures50,grandfatheredContracts50:S.grandfatheredContracts50,noncompliantBids50:S.noncompliantBids50,standardAmendments50:S.standardAmendments50,mutualRecognitions50:S.mutualRecognitions50,standardDivergences50:S.standardDivergences50,standardsCrises50:S.standardsCrises50,lastStandardsCrisis50:S.lastStandardsCrisis50,standardsKeys50:S.standardsKeys50,lastStandardsTick50:S.lastStandardsTick50}))}save=save50;
const realm=id=>S.real[id],body=id=>S.standardsBodies50.find(b=>b.reality===id),standard=id=>S.standards50.find(s=>s.id===id),vendor=id=>(S.vendorProfiles48||[]).find(v=>v.id===id),rfp=id=>(S.procurements48||[]).find(p=>p.id===id),contract=id=>(S.vendorContracts48||[]).find(c=>c.id===id),finding=id=>(S.complianceFindings49||[]).find(f=>f.id===id);
function activeRoot50(id){let accepted=S.trustPolicies?.[id]?.acceptedRoots||[];return [...(S.trustRoots||[])].filter(r=>accepted.includes(r.id)&&r.status==='active').sort((a,b)=>(b.strength||0)-(a.strength||0))[0]||null}
function trustRecord50(id,status,note){let r=activeRoot50(id);S.trustAudits=S.trustAudits||[];S.trustAuditSerial=S.trustAuditSerial||0;S.trustAudits.push({id:'TA'+(++S.trustAuditSerial),reality:id,remediationId:null,credentialId:null,certificateId:null,rootId:r?.id||null,status,created:Date.now(),note,x:10+Math.random()*80,y:12+Math.random()*68})}
function ensureBodies(){for(const id of ['A','B'])if(!body(id)){S.standardsBodies50.push({id:'STD-BODY'+(++S.standardBodySerial50),reality:id,name:'Interreality Software Standards Council',status:'independent',independence:.76,credibility:.66,capturedBy:null,ratified:0,selfCertified:0,created:Date.now(),x:12+Math.random()*76,y:12+Math.random()*68});remember('STANDARDS BODY: Reality '+id+' created a council to convert oversight findings into procurement rules',realm(id))}}
function reqBase(){return {security:.55,continuity:.55,compatibility:.52,sovereignty:.46,delivery:.48,independence:.5}}
function sourceTitle(issue){issue=String(issue||'').toLowerCase();if(issue.includes('criteria'))return 'Independent Evaluation Standard';if(issue.includes('sole-source'))return 'Competitive Continuity Standard';if(issue.includes('lock-in'))return 'Vendor Exit Portability Standard';if(issue.includes('breach'))return 'Maintenance Performance Standard';if(issue.includes('sponsor'))return 'Funding Independence Standard';if(issue.includes('debarred'))return 'Vendor Eligibility Standard';return 'Package Procurement Integrity Standard'}
function requirementsFor(issue){let r=reqBase(),x=String(issue||'').toLowerCase();if(x.includes('criteria'))r.independence=.72,r.sovereignty=.58;if(x.includes('sole-source'))r.continuity=.68,r.delivery=.58;if(x.includes('lock-in'))r.compatibility=.72,r.independence=.62;if(x.includes('breach'))r.delivery=.72,r.continuity=.68;if(x.includes('sponsor'))r.independence=.75,r.sovereignty=.66;if(x.includes('debarred'))r.independence=.78,r.security=.62;return r}
function activeStandards(id){return S.standards50.filter(s=>s.reality===id&&s.status==='ratified')}
function createStandard(id,issue='baseline procurement integrity',sourceFindingId=null,manual=true){ensureBodies();let s={id:'STD'+(++S.standardSerial50),reality:id,title:sourceTitle(issue),scope:'package-procurement',status:'draft',version:1,requirements:requirementsFor(issue),author:'Interreality Software Standards Council',sourceFindingIds:sourceFindingId?[sourceFindingId]:[],capturedBy:null,preferredVendorId:null,created:Date.now(),ratified:null,recognizedBy:[id],amendments:0,x:10+Math.random()*80,y:12+Math.random()*68};S.standards50.push(s);remember('STANDARD DRAFT '+s.id+': '+s.title+' proposed in Reality '+id,realm(id));if(typeof place==='function')place('warm','draft standard waiting to become procurement law',realm(id));if(manual){$('#msg').textContent=s.id+' drafted from '+issue+'.';renderAll();save50();openStandard(s)}return s}
function codifyLatestFinding(id=S.active){let f=[...(S.complianceFindings49||[])].reverse().find(f=>f.reality===id);if(!f)return createStandard(id,'baseline procurement integrity',null,true);return createStandard(id,f.issue,f.id,true)}
function ratify(s,manual=true){if(!s||s.status!=='draft')return;s.status='ratified';s.ratified=Date.now();S.standardsRatified50++;let b=body(s.reality);if(b){b.ratified++;b.credibility=cl(b.credibility+.01,0,1)}remember('STANDARD RATIFIED '+s.id+' v'+s.version+': '+s.title+' now governs future package procurement',realm(s.reality));trustRecord50(s.reality,'software-standard-ratified',s.id+' v'+s.version+' '+s.title);if(typeof place==='function')place('warm','compliance rule waiting for the next RFP',realm(s.reality));grandfatherExisting(s);checkDivergence(s);renderAll();save50();if(manual)openStandard(s)}
function grandfatherExisting(s){for(const c of (S.vendorContracts48||[]).filter(c=>c.reality===s.reality&&['active','stayed'].includes(c.status)&&c.started<s.ratified)){c.grandfatheredStandards50=c.grandfatheredStandards50||[];if(!c.grandfatheredStandards50.includes(s.id)){c.grandfatheredStandards50.push(s.id);S.grandfatheredContracts50++}}}
function trait(v,k){if(k==='independence'){let penalty=(v.breaches||0)*.06+(v.lockIn||0)*.25+(v.status==='debarred'?.5:0);return cl(.78-penalty,0,1)}return cl(v[k]||0,0,1)}
function scoreVendor(s,v){let vals=Object.entries(s.requirements).map(([k,t])=>Math.min(1,trait(v,k)/Math.max(.01,t))),base=vals.reduce((a,b)=>a+b,0)/vals.length;let captured=s.preferredVendorId===v.id?.12:0;return cl(base+captured,0,1.2)}
function currentCert(sid,vid){return [...S.certifications50].reverse().find(c=>c.standardId===sid&&c.vendorId===vid&&['certified','provisional'].includes(c.status)&&c.expires>Date.now())}
function certify(s,v,mode='independent',manual=true){if(!s||!v||s.status!=='ratified')return null;let score=scoreVendor(s,v),pass=score>=.96&&v.status!=='debarred';if(mode==='self'){pass=true;score=Math.max(score,.97)}let c={id:'CERT'+(++S.certificationSerial50),standardId:s.id,reality:s.reality,vendorId:v.id,vendor:v.name,status:pass?(mode==='self'?'provisional':'certified'):'failed',score,mode,issued:Date.now(),expires:Date.now()+(mode==='self'?45000:90000),version:s.version,x:10+Math.random()*80,y:12+Math.random()*68};S.certifications50.push(c);if(pass){S.certificationsIssued50++;remember('CERTIFICATION '+c.id+': '+v.name+' '+c.status+' under '+s.id+' v'+s.version,realm(s.reality));trustRecord50(s.reality,'software-certification-issued',c.id+' '+v.name+' '+s.id+' v'+s.version+' '+c.status);if(mode==='self'){S.selfCertified50++;let b=body(s.reality);b.selfCertified++;b.independence=cl(b.independence-.055,0,1);b.credibility=cl(b.credibility-.035,0,1);if(b.selfCertified>=3&&!b.capturedBy){b.capturedBy=v.name;b.status='captured';S.standardCaptures50++;remember('STANDARDS CAPTURE: '+v.name+' became a recurring source of evidence for its own certification',realm(s.reality));if(typeof place==='function'){place('cold','vendor self-certification became a market-access credential',realm(s.reality));place('dream','standards body using vendor evidence as law',realm(s.reality))}standardsCrisis(s.reality,'self-certification-capture')}}}else{S.certificationsFailed50++;remember('CERTIFICATION FAILED '+c.id+': '+v.name+' failed '+s.id+' at '+Math.round(score*100)+'%',realm(s.reality))}applyProcurementRules();if(manual){$('#msg').textContent=v.name+' '+(pass?'received':'failed')+' '+s.id+' certification.';renderAll();save50();openCertification(c)}return c}
function letVendorDraft(s,v){if(!s||s.status!=='draft'||!v)return;s.author=v.name;s.capturedBy=v.name;s.preferredVendorId=v.id;for(const k of ['security','continuity','compatibility','sovereignty','delivery'])s.requirements[k]=cl((v[k]||.5)-.04,.35,.82);s.requirements.independence=cl(.58-(v.lockIn||0)*.12,.38,.7);remember('STANDARD CAPTURE '+s.id+': '+v.name+' drafted thresholds around its own implementation profile',realm(s.reality));if(typeof place==='function'){place('cold','vendor wrote the certification profile it already satisfies',realm(s.reality));place('dream','open standard shaped like one supplier',realm(s.reality))}standardsCrisis(s.reality,'vendor-drafted-standard');renderAll();save50();openStandard(s)}
function amend(s,dir=1){if(!s||s.status!=='ratified')return;let key=pick(Object.keys(s.requirements));s.version++;s.amendments++;S.standardAmendments50++;s.requirements[key]=cl(s.requirements[key]+.06*dir,.3,.9);for(const c of S.certifications50.filter(c=>c.standardId===s.id&&['certified','provisional'].includes(c.status)&&c.version<s.version))c.status='stale';remember('STANDARD AMENDED '+s.id+' v'+s.version+': '+key+' threshold now '+Math.round(s.requirements[key]*100)+'%',realm(s.reality));trustRecord50(s.reality,'software-standard-amended',s.id+' v'+s.version+' '+key);if(typeof place==='function')place('cold','certification expired because the definition of compliant moved',realm(s.reality));applyProcurementRules();renderAll();save50();openStandard(s)}
function withdraw(s){if(!s||s.status!=='ratified')return;s.status='withdrawn';for(const c of S.certifications50.filter(c=>c.standardId===s.id&&['certified','provisional'].includes(c.status)))c.status='withdrawn-standard';remember('STANDARD WITHDRAWN '+s.id+': future procurements stop requiring it; prior exclusions remain historical',realm(s.reality));trustRecord50(s.reality,'software-standard-withdrawn',s.id+' v'+s.version);applyProcurementRules();renderAll();save50();openStandard(s)}
function recognizeForeign(s,target){if(!s||s.status!=='ratified'||s.reality===target)return;if(!s.recognizedBy.includes(target)){s.recognizedBy.push(target);S.mutualRecognitions50++;remember('MUTUAL RECOGNITION: Reality '+target+' accepts '+s.id+' from Reality '+s.reality,realm(target));if(typeof place==='function')place('warm','foreign compliance certificate accepted at border',realm(target))}renderAll();save50();openStandard(s)}
function standardsForProcurement(p){return S.standards50.filter(s=>s.status==='ratified'&&s.scope==='package-procurement'&&s.ratified<=p.opened&&s.recognizedBy.includes(p.reality))}
function vendorCompliant(p,v){let req=p.requiredStandards50||[];return req.every(id=>currentCert(id,v.id))}
function applyProcurementRules(){let now=Date.now();for(const c of S.certifications50)if(['certified','provisional'].includes(c.status)&&c.expires<=now)c.status='expired';for(const p of (S.procurements48||[])){if(!['bidding','evaluating'].includes(p.status))continue;if(!Array.isArray(p.requiredStandards50)){p.requiredStandards50=standardsForProcurement(p).map(s=>s.id);if(p.requiredStandards50.length)remember('RFP COMPLIANCE '+p.id+': requires '+p.requiredStandards50.join(', '),realm(p.reality))}for(const b of (S.bids48||[]).filter(b=>b.procurementId===p.id&&['submitted','noncompliant'].includes(b.status))){let v=vendor(b.vendorId),ok=v&&vendorCompliant(p,v);if(!ok&&b.status==='submitted'){b.status='noncompliant';b.noncompliant50=true;S.noncompliantBids50++;remember('NONCOMPLIANT BID '+b.id+': '+b.vendor+' lacks required certification for '+p.id,realm(p.reality))}else if(ok&&b.status==='noncompliant'&&b.noncompliant50){b.status='submitted';b.noncompliant50=false;remember('BID RESTORED '+b.id+': '+b.vendor+' obtained required certification',realm(p.reality))}}}}
function retrofit(s){if(!s||s.status!=='ratified')return;for(const p of (S.procurements48||[]).filter(p=>p.reality===s.reality&&['bidding','evaluating'].includes(p.status))){p.requiredStandards50=p.requiredStandards50||[];if(!p.requiredStandards50.includes(s.id))p.requiredStandards50.push(s.id)}applyProcurementRules();remember('RETROACTIVE STANDARD '+s.id+': active procurements must now satisfy the new rule',realm(s.reality));renderAll();save50();openStandard(s)}
function checkDivergence(s){let other=s.reality==='A'?'B':'A',rival=S.standards50.find(x=>x.reality===other&&x.status==='ratified'&&x.title===s.title);if(!rival)return;let delta=Object.keys(s.requirements).reduce((n,k)=>n+Math.abs((s.requirements[k]||0)-(rival.requirements[k]||0)),0);if(delta>.32){let key=[s.id,rival.id].sort().join('|');if(!S.standardsKeys50[key]){S.standardsKeys50[key]=1;S.standardDivergences50++;remember('STANDARDS DIVERGENCE: '+s.title+' means different things in Reality A and Reality B',realm('A'));remember('STANDARDS DIVERGENCE: '+s.title+' means different things in Reality A and Reality B',realm('B'));if(typeof place==='function'){place('cold','same compliance label different rules',realm(s.reality));place('dream','certified here noncompliant there',realm(other))}standardsCrisis(s.reality,'cross-reality-divergence')}}}
function standardsCrisis(id,reason){if(Date.now()-S.lastStandardsCrisis50<7000)return false;let key=id+'|'+reason+'|'+Math.floor(Date.now()/20000);if(S.standardsKeys50[key])return false;S.standardsKeys50[key]=1;S.standardsCrises50++;S.lastStandardsCrisis50=Date.now();for(const rid of ['A','B']){realm(rid).disputes=(realm(rid).disputes||0)+1;remember('STANDARDS CRISIS: certification became authority over which vendors can compete to define reality',realm(rid))}if(typeof place==='function'){place('cold','compliance certificate became market access',realm(id));place('dream','technical standard acting like procurement law',realm(id))}S.bailiffMood='asking whether the standard or the implementation defines compliance';return true}
function auditStandard(s){let certs=S.certifications50.filter(c=>c.standardId===s.id),a={id:'STDA'+(++S.standardAuditSerial50),standardId:s.id,reality:s.reality,version:s.version,author:s.author,capturedBy:s.capturedBy,certified:certs.filter(c=>c.status==='certified').length,provisional:certs.filter(c=>c.status==='provisional').length,failed:certs.filter(c=>c.status==='failed').length,created:Date.now()};S.standardAudits50.push(a);S.standardAudits50=S.standardAudits50.slice(-64);remember('STANDARD AUDIT '+a.id+': '+s.id+' v'+s.version+' author '+s.author,realm(s.reality));return a}
function openCertification(c){let s=standard(c.standardId),v=vendor(c.vendorId),b=[['close',closePanel]];panel(c.id+' · '+c.status.toUpperCase(),(v?.name||c.vendor)+' · '+(s?.id||c.standardId),'score '+Math.round(c.score*100)+'% · mode '+c.mode+' · standard version '+c.version+' · expires '+Math.max(0,Math.round((c.expires-Date.now())/1000))+'s',b)}
function openStandard(s){let vs=(S.vendorProfiles48||[]).filter(v=>v.reality===s.reality&&v.status!=='debarred'),b=[];if(s.status==='draft'){b.push(['ratify standard',()=>ratify(s)]);for(const v of vs.slice(0,4))b.push(['let '+v.name+' draft thresholds',()=>letVendorDraft(s,v)])}if(s.status==='ratified'){for(const v of vs.slice(0,4)){b.push(['certify '+v.name,()=>certify(s,v,'independent')],['self-certify '+v.name,()=>certify(s,v,'self')])}b.push(['tighten standard',()=>amend(s,1)],['relax standard',()=>amend(s,-1)],['apply to active RFPs',()=>retrofit(s)],['recognize in other reality',()=>recognizeForeign(s,s.reality==='A'?'B':'A')],['audit standard',()=>{auditStandard(s);renderAll();save50();openStandard(s)}],['withdraw standard',()=>withdraw(s)])}for(const c of [...S.certifications50].reverse().filter(c=>c.standardId===s.id).slice(0,4))b.push(['open '+c.id,()=>openCertification(c)]);b.push(['close',closePanel]);let req=Object.entries(s.requirements).map(([k,v])=>k+' '+Math.round(v*100)+'%').join(' · ');panel(s.id+' · '+s.status.toUpperCase(),s.title+' · v'+s.version+' · '+s.author,req+'\n'+(s.capturedBy?'captured by '+s.capturedBy+' · ':'')+'recognized '+s.recognizedBy.join(', ')+' · '+S.certifications50.filter(c=>c.standardId===s.id&&['certified','provisional'].includes(c.status)).length+' live certifications',b)}
function openStandards(id=S.active){ensureBodies();applyProcurementRules();let bdy=body(id),ss=[...S.standards50].reverse().filter(s=>s.reality===id),b=[['draft baseline standard',()=>createStandard(id)],['codify latest oversight finding',()=>codifyLatestFinding(id)]];for(const s of ss.slice(0,6))b.push([s.id+' · '+s.title,()=>openStandard(s)]);b.push(['close',closePanel]);panel('SOFTWARE STANDARDS · Reality '+id,bdy.status+' · independence '+Math.round(bdy.independence*100)+'% · credibility '+Math.round(bdy.credibility*100)+'%',S.standardsRatified50+' ratified · '+S.certificationsIssued50+' certifications · '+S.noncompliantBids50+' noncompliant bids · '+S.grandfatheredContracts50+' grandfathered contracts · '+S.standardCaptures50+' captures · '+S.standardDivergences50+' divergences · '+S.standardsCrises50+' crises',b)}
function autonomous(){ensureBodies();applyProcurementRules();let now=Date.now();if(now-S.lastStandardsTick50<1800)return;S.lastStandardsTick50=now;for(const id of ['A','B']){let findings=(S.complianceFindings49||[]).filter(f=>f.reality===id&&['open','stayed'].includes(f.status));if(findings.length&&!activeStandards(id).length&&Math.random()<.004){let f=pick(findings),s=createStandard(id,f.issue,f.id,false);ratify(s,false);break}let ss=activeStandards(id),vs=(S.vendorProfiles48||[]).filter(v=>v.reality===id&&v.status!=='debarred');if(ss.length&&vs.length&&Math.random()<.004){let s=pick(ss),v=pick(vs);if(!currentCert(s.id,v.id))certify(s,v,'independent',false);break}}}
function renderStandards(){ensureBodies();applyProcurementRules();let layer=$('#standardsLayer');if(!layer){layer=document.createElement('div');layer.id='standardsLayer';document.body.appendChild(layer)}layer.innerHTML='';for(const s of S.standards50.slice(-20)){let e=document.createElement('i');e.className='standardNode '+s.status+(s.capturedBy?' captured':'');e.dataset.label=s.id;e.style.left=s.x+'%';e.style.top=s.y+'%';e.onclick=()=>openStandard(s);layer.appendChild(e)}for(const c of S.certifications50.filter(c=>['certified','provisional','failed'].includes(c.status)).slice(-16)){let e=document.createElement('i');e.className='certNode '+c.status;e.dataset.label=c.id.replace('CERT','C');e.style.left=c.x+'%';e.style.top=c.y+'%';e.onclick=()=>openCertification(c);layer.appendChild(e)}let line=$('#standardsline');if(!line){line=document.createElement('div');line.id='standardsline';line.className='line';($('#oversightline')||$('#procurementline')||$('#economyline')||$('#enforcement')).after(line)}let id=S.active,ss=activeStandards(id),b=body(id),nc=(S.bids48||[]).filter(x=>x.reality===id&&x.status==='noncompliant').length;line.textContent='standards: '+ss.length+' ratified · '+S.certifications50.filter(c=>c.reality===id&&['certified','provisional'].includes(c.status)).length+' certified · '+nc+' blocked bids · '+(b?.capturedBy?'captured':'independence '+Math.round((b?.independence||0)*100)+'%')+' · '+S.standardsCrises50+' crises';let ctr=document.querySelector('#app .controls');if(ctr&&!$('#openStandardsButton')){let x=document.createElement('button');x.id='openStandardsButton';x.textContent='open standards';x.onclick=()=>openStandards(S.active);ctr.prepend(x)}if(ctr&&!$('#codifyStandardButton')){let x=document.createElement('button');x.id='codifyStandardButton';x.textContent='codify oversight';x.onclick=()=>codifyLatestFinding(S.active);ctr.prepend(x)}}
renderAll=function(){BR50();renderStandards()};let f=$('#forget');if(f)f.onclick=()=>{for(let i=2;i<=50;i++)localStorage.removeItem('nothing-state-v'+i);location.reload()};
setInterval(()=>{autonomous();renderStandards();save50()},2050);ensureBodies();applyProcurementRules();renderAll();save50();
})();
