(()=>{
const BS43=save,BR43=renderAll,O43=JSON.parse(localStorage.getItem('nothing-state-v43')||'null')||{},cl=(v,a,b)=>Math.max(a,Math.min(b,v)),pick=a=>a&&a.length?a[Math.floor(Math.random()*a.length)]:null;
const NODES=['traveler','bailiff','archive','court','administration'];
const COHORT={traveler:'traveler',bailiff:'bailiff',archive:'archive',court:'courts',administration:'agencies'};
S.replica43=O43.replica43||{A:null,B:null};
S.executionRounds43=O43.executionRounds43||[];
S.executionSnapshots43=O43.executionSnapshots43||[];
S.executionRoundSerial43=O43.executionRoundSerial43||0;
S.executionSnapshotSerial43=O43.executionSnapshotSerial43||0;
S.executionCommits43=O43.executionCommits43||0;
S.executionLags43=O43.executionLags43||0;
S.executionDivergences43=O43.executionDivergences43||0;
S.executionRepairs43=O43.executionRepairs43||0;
S.executionSnapshotsMade43=O43.executionSnapshotsMade43||0;
S.localReplicaPatches43=O43.localReplicaPatches43||0;
S.unverifiableFinality43=O43.unverifiableFinality43||0;
S.executionCrises43=O43.executionCrises43||0;
S.lastExecutionCrisis43=O43.lastExecutionCrisis43||0;
S.executionKeys43=O43.executionKeys43||{};
S.observedQC43=O43.observedQC43||{};
for(const id of ['A','B'])S.replica43[id]=Object.assign({executedHead:null,executedTerm:0,status:'idle',nodes:{}},S.replica43[id]||{});
for(const id of ['A','B'])for(const name of NODES){let n=S.replica43[id].nodes[name]||{};S.replica43[id].nodes[name]=Object.assign({name,appliedHead:null,appliedTerm:0,appliedSeq:0,stateHash:'00000000',state:{roots:0,certificates:0,crossSigns:0,audits:0,reconciliations:0,retrusts:0,operatorChanges:0,exceptions:0},status:'idle',lastApplied:0,lagged:0,localPatch:0,snapshotId:null},n)}
S.executionRounds43=S.executionRounds43.map((r,i)=>Object.assign({id:r.id||'ER'+(i+1),reality:r.reality||'A',qcId:r.qcId||null,head:r.head||null,term:r.term||0,status:r.status||'pending',results:r.results||[],created:r.created||Date.now(),completedAt:r.completedAt||null,x:Number.isFinite(r.x)?r.x:10+Math.random()*80,y:Number.isFinite(r.y)?r.y:12+Math.random()*68},r));
S.executionSnapshots43=S.executionSnapshots43.map((s,i)=>Object.assign({id:s.id||'SNAP'+(i+1),reality:s.reality||'A',head:s.head||null,term:s.term||0,stateHash:s.stateHash||'00000000',state:s.state||{},sourceNodes:s.sourceNodes||[],created:s.created||Date.now(),x:Number.isFinite(s.x)?s.x:10+Math.random()*80,y:Number.isFinite(s.y)?s.y:12+Math.random()*68},s));
function save43(){BS43();localStorage.setItem('nothing-state-v43',JSON.stringify({replica43:S.replica43,executionRounds43:S.executionRounds43,executionSnapshots43:S.executionSnapshots43,executionRoundSerial43:S.executionRoundSerial43,executionSnapshotSerial43:S.executionSnapshotSerial43,executionCommits43:S.executionCommits43,executionLags43:S.executionLags43,executionDivergences43:S.executionDivergences43,executionRepairs43:S.executionRepairs43,executionSnapshotsMade43:S.executionSnapshotsMade43,localReplicaPatches43:S.localReplicaPatches43,unverifiableFinality43:S.unverifiableFinality43,executionCrises43:S.executionCrises43,lastExecutionCrisis43:S.lastExecutionCrisis43,executionKeys43:S.executionKeys43,observedQC43:S.observedQC43}))}save=save43;
const realm=id=>S.real[id],replicas=id=>S.replica43[id],node=(id,name)=>replicas(id).nodes[name],log=id=>S.transparencyLogs?.[id],qcs=id=>(S.quorumCertificates||[]).filter(q=>q.reality===id&&['committed','conflicting'].includes(q.status)),entryForHead=(id,h)=>(S.transparencyEntries||[]).find(e=>e.reality===id&&e.visibility==='public'&&e.headAfter===h),entriesTo=(id,seq)=>(S.transparencyEntries||[]).filter(e=>e.reality===id&&e.visibility==='public'&&e.seq<=seq).sort((a,b)=>a.seq-b.seq);
function hash43(s){let h=2166136261>>>0;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)>>>0}return h.toString(16).padStart(8,'0')}
function engineFor(id,name){let rt=S.runtimeReality?.[id],cid=COHORT[name];return rt?.cohorts?.[cid]||rt?.stableHead||'legacy'}
function variant(engine){return parseInt(hash43(String(engine)).slice(-2),16)%3}
function blankState(){return{roots:0,certificates:0,crossSigns:0,audits:0,reconciliations:0,retrusts:0,operatorChanges:0,exceptions:0}}
function applyEntry(st,e,eng,localPatch=0){let v=(variant(eng)+localPatch)%3;switch(e.type){case'root':st.roots++;break;case'certificate':st.certificates++;break;case'cross-sign':st.crossSigns+=v===1?2:1;if(v===1)st.exceptions++;break;case'trust-audit':if(v===2)st.exceptions++;else st.audits++;break;case'reconciliation':st.reconciliations++;break;case'retrust':st.retrusts+=v===0?1:2;if(v!==0)st.exceptions++;break;case'operator-change':st.operatorChanges++;break;default:break}return st}
function replay(id,name,head,term){let n=node(id,name),e=entryForHead(id,head);if(!e){n.status='blocked';S.unverifiableFinality43++;return{node:name,status:'unverifiable',head,hash:n.stateHash,engine:engineFor(id,name)}}let st=blankState(),eng=engineFor(id,name);for(const x of entriesTo(id,e.seq))applyEntry(st,x,eng,n.localPatch||0);let h=hash43(JSON.stringify(st));n.appliedHead=head;n.appliedTerm=term;n.appliedSeq=e.seq;n.stateHash=h;n.state=st;n.status='healthy';n.lastApplied=Date.now();return{node:name,status:'applied',head,hash:h,engine:eng,state:st}}
function activePartition(id){return[...(S.consensusPartitions||[])].reverse().find(p=>p.reality===id&&p.status==='active')}
function partitionSide(p,name){if(!p)return'whole';if(p.left?.includes(name))return'left';if(p.right?.includes(name))return'right';return'isolated'}
function executeQC(q,manual=false){if(!q)return null;let id=q.reality,key='qc:'+q.id;if(S.observedQC43[key]&&!manual)return null;S.observedQC43[key]=1;let r={id:'ER'+(++S.executionRoundSerial43),reality:id,qcId:q.id,head:q.head,term:q.term,status:'running',results:[],created:Date.now(),completedAt:null,x:10+Math.random()*80,y:12+Math.random()*68},part=activePartition(id);S.executionRounds43.push(r);S.executionRounds43=S.executionRounds43.slice(-44);for(const name of NODES){let n=node(id,name),should=q.status==='conflicting'?q.signers?.includes(name)!==false:true;if(part&&q.status!=='conflicting'){let leaderSide=partitionSide(part,q.leader),side=partitionSide(part,name);if(side!==leaderSide&&Math.random()<.82)should=false}if(!should||(!manual&&Math.random()<.08)){n.status='lagging';n.lagged++;S.executionLags43++;r.results.push({node:name,status:'lagging',head:n.appliedHead,hash:n.stateHash,engine:engineFor(id,name)});continue}r.results.push(replay(id,name,q.head,q.term))}r.completedAt=Date.now();evaluateRound(r);save43();renderAll();if(manual)openRound(r);return r}
function majority(results){let m={};for(const x of results.filter(x=>x.status==='applied'))(m[x.hash]||(m[x.hash]=[])).push(x);let groups=Object.values(m).sort((a,b)=>b.length-a.length);return groups[0]||[]}
function evaluateRound(r){let id=r.reality,good=r.results.filter(x=>x.status==='applied'),maj=majority(r.results),hashes=[...new Set(good.map(x=>x.hash))];if(maj.length>=3&&hashes.length===1){r.status='executed';let rr=replicas(id);rr.executedHead=r.head;rr.executedTerm=r.term;rr.status='healthy';S.executionCommits43++;let op=(S.trustRoots||[]).find(x=>x.id===log(id)?.operatorRootId);if(op&&op.status==='active')op.strength=cl((op.strength||.55)+.006,.1,.99);remember('STATE MACHINE COMMIT '+r.id+': '+r.head+' executed identically on '+maj.length+'/5 replicas',realm(id));if(typeof place==='function')place('warm','final history executed the same way',realm(id));return}if(maj.length>=3){r.status='majority-with-divergence';replicas(id).executedHead=r.head;replicas(id).executedTerm=r.term;replicas(id).status='diverged';S.executionDivergences43++;remember('STATE MACHINE DIVERGENCE '+r.id+': quorum agreed on '+r.head+' but replicas computed '+hashes.length+' state hashes',realm(id));if(typeof place==='function'){place('cold','same quorum certificate different state hash',realm(id));place('dream','final history executed two ways',realm(id))}openExecutionIncident(id,'consensus-final history produced divergent replica state','SEV1');executionCrisis(id,'state-divergence');return}r.status=good.length?'under-replicated':'blocked';replicas(id).status=r.status;remember('STATE MACHINE '+r.id+': '+r.head+' is final but only '+good.length+'/5 replicas applied it',realm(id));if(typeof place==='function')place('cold','final history waiting to execute',realm(id))}
function latestQC(id){return[...qcs(id)].sort((a,b)=>(b.created||0)-(a.created||0))[0]||null}
function executeLatest(id=S.active){let q=latestQC(id);if(!q){$('#msg').textContent='Reality '+id+' has no quorum-certified history to execute yet.';return null}return executeQC(q,true)}
function catchUp(id,name){let q=latestQC(id);if(!q)return;let res=replay(id,name,q.head,q.term);remember('REPLICA CATCH-UP: '+name+' replayed '+q.head+' and reached '+res.hash,realm(id));evaluateReplicaSet(id);renderAll();save43();openReplica(id,name)}
function evaluateReplicaSet(id){let xs=NODES.map(name=>node(id,name)).filter(n=>n.appliedHead),byHead={};for(const n of xs){let k=(n.appliedHead||'none')+'|'+n.stateHash;(byHead[k]||(byHead[k]=[])).push(n)}let groups=Object.values(byHead).sort((a,b)=>b.length-a.length),maj=groups[0]||[];if(maj.length>=3){let rr=replicas(id);rr.executedHead=maj[0].appliedHead;rr.executedTerm=maj[0].appliedTerm;rr.status=groups.length>1?'diverged':'healthy'}return maj}
function repairFromMajority(id,name){let maj=evaluateReplicaSet(id),n=node(id,name);if(maj.length<3){$('#msg').textContent='No replica majority exists to repair from.';return}let src=maj[0];n.appliedHead=src.appliedHead;n.appliedTerm=src.appliedTerm;n.appliedSeq=src.appliedSeq;n.stateHash=src.stateHash;n.state=JSON.parse(JSON.stringify(src.state));n.status='repaired';n.lastApplied=Date.now();n.localPatch=0;S.executionRepairs43++;remember('REPLICA REPAIR: '+name+' copied majority state '+src.stateHash+' at '+src.appliedHead,realm(id));if(typeof place==='function')place('dream','replica repaired by copying the majority',realm(id));renderAll();save43();openReplica(id,name)}
function localPatch(id,name){let n=node(id,name);n.localPatch=(n.localPatch+1)%3;S.localReplicaPatches43++;remember('LOCAL REPLICA PATCH: '+name+' changed execution semantics without changing the consensus log',realm(id));if(typeof place==='function')place('cold','hotfix installed on one replica only',realm(id));let q=latestQC(id);if(q)replay(id,name,q.head,q.term);evaluateReplicaSet(id);executionCrisis(id,'local-patch');renderAll();save43();openReplica(id,name)}
function makeSnapshot(id=S.active){let maj=evaluateReplicaSet(id);if(maj.length<3){$('#msg').textContent='Snapshot refused: fewer than three replicas agree on one executed state.';return null}let src=maj[0],s={id:'SNAP'+(++S.executionSnapshotSerial43),reality:id,head:src.appliedHead,term:src.appliedTerm,stateHash:src.stateHash,state:JSON.parse(JSON.stringify(src.state)),sourceNodes:maj.map(n=>n.name),created:Date.now(),x:10+Math.random()*80,y:12+Math.random()*68};S.executionSnapshots43.push(s);S.executionSnapshots43=S.executionSnapshots43.slice(-24);S.executionSnapshotsMade43++;remember('STATE SNAPSHOT '+s.id+': '+s.stateHash+' compressed executed history at '+s.head,realm(id));if(typeof place==='function')place('warm','snapshot that remembers state but not replay',realm(id));renderAll();save43();openSnapshot(s);return s}
function restoreSnapshot(s,name){if(!s)return;let n=node(s.reality,name);n.appliedHead=s.head;n.appliedTerm=s.term;n.stateHash=s.stateHash;n.state=JSON.parse(JSON.stringify(s.state));n.status='snapshot-restored';n.snapshotId=s.id;n.lastApplied=Date.now();S.executionRepairs43++;remember('SNAPSHOT RESTORE '+s.id+': '+name+' accepted '+s.stateHash+' without replaying the full log',realm(s.reality));if(typeof place==='function')place('dream','replica that trusts a snapshot of history',realm(s.reality));renderAll();save43();openReplica(s.reality,name)}
function openExecutionIncident(id,title,severity='SEV2'){S.incidents=S.incidents||[];let x=S.incidents.find(n=>n.reality===id&&n.status==='open'&&n.title===title);if(x)return x;S.incidentSerial=S.incidentSerial||0;x={id:'INC'+(++S.incidentSerial),reality:id,title,severity,status:'open',alertIds:[],started:Date.now(),acknowledged:null,resolved:null,postmortem:null,owner:'state-machine review',x:10+Math.random()*80,y:12+Math.random()*68};S.incidents.push(x);remember('EXECUTION INCIDENT '+x.id+': '+title,realm(id));return x}
function executionCrisis(id,reason){if(Date.now()-S.lastExecutionCrisis43<8000)return false;let key=id+'|'+reason+'|'+Math.floor(Date.now()/20000);if(S.executionKeys43[key])return false;S.executionKeys43[key]=1;S.executionCrises43++;S.lastExecutionCrisis43=Date.now();for(const rid of ['A','B']){realm(rid).disputes=(realm(rid).disputes||0)+1;remember('STATE MACHINE CRISIS: consensus agreed on the input but institutions disagreed on the resulting reality',realm(rid))}realm(id).timelineDrift=(realm(id).timelineDrift||0)+1;if(typeof place==='function'){place('cold','agreement on history disagreement on state',realm(id));place('dream','determinism failed after finality',realm(id))}S.bailiffMood='asking whether agreement on input counts as agreement on reality';return true}
function autonomous(){for(const id of ['A','B']){let q=[...qcs(id)].sort((a,b)=>(a.created||0)-(b.created||0)).find(q=>!S.observedQC43['qc:'+q.id]);if(q){executeQC(q,false);continue}let lag=NODES.map(name=>node(id,name)).filter(n=>n.status==='lagging');if(lag.length&&Math.random()<.08){catchUp(id,pick(lag).name);break}}}
function openReplica(id,name){let n=node(id,name),b=[['replay latest finality',()=>catchUp(id,name)],['repair from majority',()=>repairFromMajority(id,name)],['install local hotfix',()=>localPatch(id,name)]];for(const s of [...S.executionSnapshots43].reverse().filter(s=>s.reality===id).slice(0,2))b.push(['restore '+s.id,()=>restoreSnapshot(s,name)]);b.push(['close',closePanel]);panel(name.toUpperCase()+' REPLICA · Reality '+id,'head '+(n.appliedHead||'none')+' · term '+n.appliedTerm+'\nstate '+n.stateHash+' · runtime '+engineFor(id,name),'status '+n.status+' · seq '+n.appliedSeq+' · lag '+n.lagged+' · local patch '+n.localPatch+'\nroots '+n.state.roots+' · certs '+n.state.certificates+' · cross-signs '+n.state.crossSigns+' · audits '+n.state.audits+' · semantic exceptions '+n.state.exceptions,b)}
function openRound(r){let b=[];for(const x of r.results)b.push([x.node+' · '+x.status+' · '+x.hash,()=>openReplica(r.reality,x.node)]);b.push(['close',closePanel]);panel(r.id+' · '+r.status.toUpperCase(),(r.qcId||'no QC')+' → '+r.head+' · term '+r.term,r.results.map(x=>x.node+': '+x.status+' / '+x.hash+' / '+x.engine).join('\n'),b)}
function openSnapshot(s){let b=[];for(const name of NODES)b.push(['restore to '+name,()=>restoreSnapshot(s,name)]);b.push(['close',closePanel]);panel(s.id+' · STATE SNAPSHOT',s.head+' · '+s.stateHash+' · term '+s.term,'source quorum: '+s.sourceNodes.join(', ')+'\nSnapshot preserves state, not the reasoning that produced it.',b)}
function openReplicas(id=S.active){let rr=replicas(id),b=NODES.map(name=>['open '+name,()=>openReplica(id,name)]);for(const r of [...S.executionRounds43].reverse().filter(r=>r.reality===id).slice(0,3))b.push(['open '+r.id,()=>openRound(r)]);b.push(['execute latest finality',()=>executeLatest(id)],['take majority snapshot',()=>makeSnapshot(id)],['close',closePanel]);panel('REPLICATED STATE · Reality '+id,'consensus-final '+(S.consensus42?.[id]?.committedHead||'none')+'\nexecuted '+(rr.executedHead||'none'),'status '+rr.status+' · '+S.executionCommits43+' clean executions · '+S.executionDivergences43+' divergences · '+S.executionLags43+' lag events · '+S.executionRepairs43+' repairs · '+S.executionCrises43+' crises',b)}
function renderReplicas(){let layer=$('#replicaLayer');if(!layer){layer=document.createElement('div');layer.id='replicaLayer';document.body.appendChild(layer)}layer.innerHTML='';for(const id of ['A','B'])for(const name of NODES){let n=node(id,name);if(!n.appliedHead&&n.status==='idle')continue;let e=document.createElement('i');e.className='replicaNode '+n.status;e.dataset.label=name.slice(0,2).toUpperCase();e.style.left=(8+NODES.indexOf(name)*18+(id==='B'?4:0))+'%';e.style.top=(id==='A'?13:79)+'%';e.onclick=()=>openReplica(id,name);layer.appendChild(e)}for(const r of S.executionRounds43.filter(r=>['majority-with-divergence','blocked','under-replicated'].includes(r.status)).slice(-8)){let e=document.createElement('i');e.className='executionFault '+r.status;e.dataset.label=r.id;e.style.left=r.x+'%';e.style.top=r.y+'%';e.onclick=()=>openRound(r);layer.appendChild(e)}let line=$('#replicaline');if(!line){line=document.createElement('div');line.id='replicaline';line.className='line';($('#quorumline')||$('#transparencyline')||$('#trustline')||$('#enforcement')).after(line)}let id=S.active,rr=replicas(id),heads=NODES.map(n=>node(id,n).appliedHead||'∅'),hashes=NODES.map(n=>node(id,n).stateHash),uniqueHeads=new Set(heads).size,uniqueHashes=new Set(hashes).size;line.textContent='state machine: executed '+(rr.executedHead||'none')+' · '+uniqueHeads+' replica heads · '+uniqueHashes+' state hashes · '+S.executionCommits43+' clean · '+S.executionDivergences43+' divergences · '+S.executionLags43+' lag · '+S.executionCrises43+' crises';let ctr=document.querySelector('#app .controls');if(ctr&&!$('#openReplicasButton')){let b=document.createElement('button');b.id='openReplicasButton';b.textContent='open replicas';b.onclick=()=>openReplicas(S.active);ctr.prepend(b)}if(ctr&&!$('#executeFinalityButton')){let b=document.createElement('button');b.id='executeFinalityButton';b.textContent='apply committed history';b.onclick=()=>executeLatest(S.active);ctr.prepend(b)}}
renderAll=function(){BR43();renderReplicas()};let f=$('#forget');if(f)f.onclick=()=>{for(let i=2;i<=43;i++)localStorage.removeItem('nothing-state-v'+i);location.reload()};
setInterval(()=>{autonomous();renderReplicas();save43()},1900);renderAll();save43();
})();
