(()=>{
const B91=save,R91=renderAll,O=JSON.parse(localStorage.getItem('nothing-state-v91')||'null')||{},RECOVER91=!Array.isArray(O.monetaryExceptionEvents91),K=['monetaryExceptionOffice91','monetaryExceptionEvents91','monetaryExceptionSerial91','monetaryExceptionRegistrations91','monetaryExceptionRatchets91','monetaryExceptionReimpositions91','monetaryExceptionAuthorities91','monetaryExceptionCrises91','monetaryExceptionKeys91','lastMonetaryExceptionTick91'];
for(const k of K)S[k]=O[k]??(k==='monetaryExceptionEvents91'?[]:/Serial|Registrations|Ratchets|Reimpositions|Authorities|Crises|Tick/.test(k)?0:/Keys/.test(k)?{}:/Office/.test(k)?null:[]);
function save91(){B91();let o={};for(const k of K)o[k]=S[k];localStorage.setItem('nothing-state-v91',JSON.stringify(o))}save=save91;
const q=s=>$(s),realm=id=>S.real[id],GR=['AAA','AA','A','BBB','BB','B','CCC','D'];
function trust(id,status,note){S.trustAudits=S.trustAudits||[];S.trustAuditSerial=S.trustAuditSerial||0;S.trustAudits.push({id:'TA'+(++S.trustAuditSerial),reality:id,status,created:Date.now(),note,x:10+Math.random()*80,y:12+Math.random()*68})}
function incident(id,title,sev='SEV2'){S.incidents=S.incidents||[];S.incidentSerial=S.incidentSerial||0;let ex=S.incidents.find(x=>x.reality===id&&x.title===title&&x.status==='open');if(ex)return ex;let i={id:'INC'+(++S.incidentSerial),reality:id,title,severity:sev,status:'open',started:Date.now(),owner:'supervisory exception register',x:10+Math.random()*80,y:12+Math.random()*68};S.incidents.push(i);return i}
function crisis(id,why,key){let n=Date.now(),k=id+'|'+key;if(S.monetaryExceptionKeys91[k]&&n-S.monetaryExceptionKeys91[k]<14000)return;S.monetaryExceptionKeys91[k]=n;S.monetaryExceptionCrises91++;remember('SUPERVISORY EXCEPTION: '+why+' made emergency lending consume the discretion that remediation was supposed to preserve',realm(id));if(typeof place==='function'){place('cold','an emergency exception becoming the new ordinary rule one loan at a time',realm(id));place('dream','a supervisor keeping a ledger of every time supervision was ignored',realm(id))}incident(id,'supervisory exception register: '+why,'SEV2')}
function ensure(){if(!S.monetaryRemediationOffice90||!S.interestMaterialityOffice89)return null;if(!S.monetaryExceptionOffice91){S.monetaryExceptionOffice91={id:'SXR1',name:'Interreality Supervisory Exception Register',status:'registering',created:Date.now(),x:50,y:74};remember('SUPERVISORY EXCEPTION REGISTER SXR1: monetary remediation acquired an exception ledger and policy ratchet',realm('A'));remember('SUPERVISORY EXCEPTION REGISTER SXR1: monetary remediation acquired an exception ledger and policy ratchet',realm('B'));trust('A','supervisory-exception-register-created','SXR1');trust('B','supervisory-exception-register-created','SXR1')}return S.monetaryExceptionOffice91}
function gradeIndex(g){let i=GR.indexOf(g);return i<0?GR.length:i}
function tighterFloor(current,required){return gradeIndex(current)<=gradeIndex(required)?current:required}
function stageBase(a){let s=Math.max(0,a.supervisoryStage90||0);return s===1?{rate:.075,floor:'A'}:s===2?{rate:.095,floor:'AA'}:s===3?{rate:.12,floor:'AAA'}:null}
function exceptionPolicy(a,count){let b=stageBase(a);if(!b)return null;let extra=Math.max(0,count-1),rate=Math.min(.20,b.rate+extra*.02),i=Math.max(0,gradeIndex(b.floor)-extra),floor=GR[Math.min(i,GR.length-1)]||'AAA';return{rate,floor,count,baseRate:b.rate,baseFloor:b.floor}}
function sourceKind(f){if(!f)return null;if(f.sterilizationOverride78)return'sterilization-override78';if(f.marginRefinanceOverride82)return'margin-refinance-override82';if(f.recoveryBridge70&&f.override)return'recovery-window-override70';if(f.override)return'build55-override';return null}
function eligibleFacility(f,a){let k=sourceKind(f);if(!k||!a||(a.supervisoryStage90||0)<=0||!a.supervisedSince90)return false;return(f.issued||0)+1>=a.supervisedSince90}
function authority(id){return(S.monetaryAuthorities55||[]).find(a=>a.id===id)}
function facilities(a){return(S.liquidityFacilities55||[]).filter(f=>f.authorityId===a.id&&eligibleFacility(f,a)).sort((x,y)=>(x.issued||0)-(y.issued||0)||String(x.id).localeCompare(String(y.id)))}
function upsert(arr,id,snap){let i=arr.findIndex(x=>x.id===id);if(i>=0)arr[i]=snap;else arr.push(snap)}
function authorityMarker(e,a){a.supervisoryExceptionMarkers91=a.supervisoryExceptionMarkers91||[];upsert(a.supervisoryExceptionMarkers91,e.id,JSON.parse(JSON.stringify(e)));a.supervisoryExceptionLatest91=e.id}
function facilityMarker(e,f){f.supervisoryExceptionMarker91=JSON.parse(JSON.stringify(e));f.supervisoryException91=e.id}
function event(kind,a,data={}){let e={id:'SER'+(++S.monetaryExceptionSerial91),kind91:kind,status:'recorded',authorityId:a.id,reality:a.reality,authorityName91:a.name,created:Date.now(),x:10+Math.random()*80,y:12+Math.random()*68,...data};S.monetaryExceptionEvents91.push(e);if(kind==='exception-registration')S.monetaryExceptionRegistrations91++;else if(kind==='exception-ratchet')S.monetaryExceptionRatchets91++;else S.monetaryExceptionReimpositions91++;authorityMarker(e,a);return e}
function registerFacility(f,a,number){if(f.supervisoryException91)return null;let kind=sourceKind(f),e=event('exception-registration',a,{facilityId55:f.id,sourceKind91:kind,exceptionNumber91:number,supervisoryStage90:a.supervisoryStage90||0,rateAtIssue91:f.rate||0,discountRateAtReview91:a.discountRate||0,collateralFloorAtReview91:a.collateralFloor,facilityCollateralGrade91:f.collateralGrade||null,facilityOverride91:!!f.override,issued91:f.issued||null});facilityMarker(e,f);f.supervisoryExceptionNumber91=number;f.supervisoryExceptionSource91=kind;remember('SUPERVISORY EXCEPTION '+e.id+': '+a.name+' registered '+f.id+' as post-remediation exception #'+number+' ('+kind+')',realm(a.reality));trust(a.reality,'supervisory-exception-registered',e.id+' '+f.id);if(number===1)crisis(a.reality,a.name+' used its first post-remediation lending exception','first-'+a.id);return e}
function applyPolicy(a,p){let before={discountRate91:a.discountRate,collateralFloor91:a.collateralFloor};a.discountRate=Math.max(a.discountRate||0,p.rate);a.collateralFloor=tighterFloor(a.collateralFloor,p.floor);return{before,after:{discountRate91:a.discountRate,collateralFloor91:a.collateralFloor}}}
function ratchetTo(a,count){let current=Math.max(1,a.supervisoryExceptionRatchetCount91||1),changed=false;for(let n=Math.max(2,current+1);n<=count;n++){let p=exceptionPolicy(a,n),prev=exceptionPolicy(a,n-1),same=prev&&Math.abs(p.rate-prev.rate)<=1e-9&&p.floor===prev.floor;a.supervisoryExceptionRatchetCount91=n;a.supervisoryExceptionMinRate91=p.rate;a.supervisoryExceptionFloor91=p.floor;a.supervisoryExceptionStatus91=n>=3?'exception-constrained':'exception-ratchet';if(same)continue;let changes=applyPolicy(a,p),e=event('exception-ratchet',a,{exceptionCount91:n,supervisoryStage90:a.supervisoryStage90||0,requiredDiscountRate91:p.rate,requiredCollateralFloor91:p.floor,baseDiscountRate90:p.baseRate,baseCollateralFloor90:p.baseFloor,...changes});remember('EXCEPTION RATCHET '+e.id+': '+a.name+' exception #'+n+' raised the supervisory minimum to '+(p.rate*100).toFixed(1)+'% / '+p.floor,realm(a.reality));trust(a.reality,'supervisory-exception-ratchet',e.id+' count '+n);crisis(a.reality,a.name+' reached supervised exception #'+n+' and tightened future monetary policy','ratchet-'+a.id+'-'+n);changed=true}return changed}
function reimpose(a,count){if(count<2)return null;let p=exceptionPolicy(a,count);if(!p)return null;let drift=(a.discountRate||0)+1e-9<p.rate||gradeIndex(a.collateralFloor)>gradeIndex(p.floor);if(!drift)return null;let changes=applyPolicy(a,p),e=event('exception-reimposition',a,{exceptionCount91:count,supervisoryStage90:a.supervisoryStage90||0,requiredDiscountRate91:p.rate,requiredCollateralFloor91:p.floor,...changes});a.supervisoryExceptionMinRate91=p.rate;a.supervisoryExceptionFloor91=p.floor;a.supervisoryExceptionReimpositions91=(a.supervisoryExceptionReimpositions91||0)+1;remember('EXCEPTION REIMPOSITION '+e.id+': '+a.name+' drifted below the policy required by '+count+' supervised exceptions; rate/floor restored to '+(a.discountRate*100).toFixed(1)+'% / '+a.collateralFloor,realm(a.reality));trust(a.reality,'supervisory-exception-policy-reimposed',e.id+' count '+count);return e}
function reviewAuthority(a){if((a.supervisoryStage90||0)<=0||!a.supervisedSince90)return false;let fs=facilities(a),changed=false,registered=fs.filter(f=>f.supervisoryException91).length;for(const f of fs){if(f.supervisoryException91)continue;registered++;if(registerFacility(f,a,registered))changed=true}let count=fs.filter(f=>f.supervisoryException91).length;a.supervisoryExceptionCount91=count;if(count>0&&!a.supervisoryExceptionStarted91){a.supervisoryExceptionStarted91=Date.now();S.monetaryExceptionAuthorities91++}if(count===1){a.supervisoryExceptionRatchetCount91=Math.max(1,a.supervisoryExceptionRatchetCount91||0);let p=exceptionPolicy(a,1);a.supervisoryExceptionMinRate91=p.rate;a.supervisoryExceptionFloor91=p.floor;a.supervisoryExceptionStatus91='first-exception'}if(count>=2&&ratchetTo(a,count))changed=true;if(reimpose(a,count))changed=true;return changed}
function reconstruct(){if(!RECOVER91)return false;let changed=false,seen=new Map();for(const a of(S.monetaryAuthorities55||[]))for(const m of(a.supervisoryExceptionMarkers91||[]))seen.set(m.id,m);for(const f of(S.liquidityFacilities55||[])){let m=f.supervisoryExceptionMarker91;if(m)seen.set(m.id,m)}for(const m of seen.values()){if((S.monetaryExceptionEvents91||[]).some(x=>x.id===m.id))continue;let e=JSON.parse(JSON.stringify(m));e.recovered=true;S.monetaryExceptionEvents91.push(e);if(e.kind91==='exception-registration')S.monetaryExceptionRegistrations91++;else if(e.kind91==='exception-ratchet')S.monetaryExceptionRatchets91++;else S.monetaryExceptionReimpositions91++;let n=Number(String(e.id).replace(/\D/g,''))||0;if(n>S.monetaryExceptionSerial91)S.monetaryExceptionSerial91=n;changed=true}S.monetaryExceptionAuthorities91=(S.monetaryAuthorities55||[]).filter(a=>(a.supervisoryExceptionCount91||0)>0||a.supervisoryExceptionStarted91).length;return changed}
function reconcile(){if(!ensure())return false;let changed=reconstruct();for(const a of(S.monetaryAuthorities55||[]))if(reviewAuthority(a))changed=true;return changed}
function openEvent(e){let detail=e.kind91==='exception-registration'?(e.facilityId55+' · exception #'+e.exceptionNumber91+' · '+e.sourceKind91+' · facility rate '+(e.rateAtIssue91*100).toFixed(1)+'% · reviewed at '+(e.discountRateAtReview91*100).toFixed(1)+'% / '+e.collateralFloorAtReview91):e.kind91==='exception-ratchet'?('exception count '+e.exceptionCount91+' · required '+(e.requiredDiscountRate91*100).toFixed(1)+'% / '+e.requiredCollateralFloor91+' · actual '+(e.after.discountRate91*100).toFixed(1)+'% / '+e.after.collateralFloor91):('exception count '+e.exceptionCount91+' · attempted '+(e.before.discountRate91*100).toFixed(1)+'% / '+e.before.collateralFloor91+' · restored '+(e.after.discountRate91*100).toFixed(1)+'% / '+e.after.collateralFloor91);panel(e.id+' · SUPERVISORY EXCEPTION',e.kind91.toUpperCase(),e.authorityName91+' · '+detail,[['close',closePanel]])}
function openOffice(){if(!ensure())return;let acts=[];for(const e of S.monetaryExceptionEvents91.slice(-10))acts.push(['open '+e.id+' · '+e.kind91,()=>openEvent(e)]);acts.push(['close',closePanel]);panel(S.monetaryExceptionOffice91.name,'REGISTERING · SXR1',S.monetaryExceptionRegistrations91+' exceptions · '+S.monetaryExceptionRatchets91+' ratchets · '+S.monetaryExceptionReimpositions91+' reimpositions · '+S.monetaryExceptionAuthorities91+' authorities',acts)}
function render91(){if(!ensure())return;let layer=q('#monetaryExceptionLayer91');if(!layer){layer=document.createElement('div');layer.id='monetaryExceptionLayer91';document.body.appendChild(layer)}layer.innerHTML='';let o=document.createElement('i');o.className='monetaryExceptionOffice91';o.dataset.label='EX';o.style.left='50%';o.style.top='74%';o.onclick=openOffice;layer.appendChild(o);for(const e of S.monetaryExceptionEvents91.slice(-8)){let n=document.createElement('i');n.className='monetaryException91 '+e.kind91;n.dataset.label=e.kind91==='exception-registration'?'E':e.kind91==='exception-ratchet'?'↑':'↺';n.style.left=e.x+'%';n.style.top=e.y+'%';n.onclick=()=>openEvent(e);layer.appendChild(n)}let line=q('#monetaryexceptionline91');if(!line){line=document.createElement('div');line.id='monetaryexceptionline91';line.className='line';(q('#monetaryremediationline90')||q('#interestmaterialityline89')||q('#monetaryline')||q('#enforcement')).after(line)}line.textContent='supervisory exceptions: '+S.monetaryExceptionRegistrations91+' registered · '+S.monetaryExceptionRatchets91+' ratchets · '+S.monetaryExceptionReimpositions91+' reimpositions';let ctr=document.querySelector('#app .controls');if(ctr&&!q('#openMonetaryException91')){let x=document.createElement('button');x.id='openMonetaryException91';x.textContent='open exception register';x.onclick=openOffice;ctr.prepend(x)}}
renderAll=function(){R91();let changed=reconcile();render91();if(changed)save91()};let f=q('#forget');if(f)f.onclick=()=>{for(let i=2;i<=91;i++)localStorage.removeItem('nothing-state-v'+i);location.reload()};setInterval(()=>{reconcile();render91();save91()},2300);ensure();reconcile();renderAll();save91();
})();