(()=>{
const B92=save,R92=renderAll,O=JSON.parse(localStorage.getItem('nothing-state-v92')||'null')||{},RECOVER92=!Array.isArray(O.supervisoryCapitalRequirements92),K=['supervisoryCapitalOffice92','supervisoryCapitalRequirements92','supervisoryCapitalActions92','supervisoryCapitalRequirementSerial92','supervisoryCapitalActionSerial92','supervisoryCapitalRequirementsCreated92','supervisoryCapitalTopups92','supervisoryCapitalTopupAmount92','supervisoryCapitalReleases92','supervisoryCapitalReleaseAmount92','supervisoryCapitalHeldTotal92','supervisoryCapitalShortfallTotal92','supervisoryCapitalAuthorities92','supervisoryCapitalCrises92','supervisoryCapitalKeys92','lastSupervisoryCapitalTick92'];
for(const k of K)S[k]=O[k]??(k==='supervisoryCapitalRequirements92'||k==='supervisoryCapitalActions92'?[]:/Serial|Created|Topups|Amount|Releases|HeldTotal|ShortfallTotal|Authorities|Crises|Tick/.test(k)?0:/Keys/.test(k)?{}:/Office/.test(k)?null:[]);
function save92(){B92();let o={};for(const k of K)o[k]=S[k];localStorage.setItem('nothing-state-v92',JSON.stringify(o))}save=save92;
const q=s=>$(s),realm=id=>S.real[id],GR=['AAA','AA','A','BBB','BB','B','CCC','D'];
function trust(id,status,note){S.trustAudits=S.trustAudits||[];S.trustAuditSerial=S.trustAuditSerial||0;S.trustAudits.push({id:'TA'+(++S.trustAuditSerial),reality:id,status,created:Date.now(),note,x:10+Math.random()*80,y:12+Math.random()*68})}
function incident(id,title,sev='SEV2'){S.incidents=S.incidents||[];S.incidentSerial=S.incidentSerial||0;let ex=S.incidents.find(x=>x.reality===id&&x.title===title&&x.status==='open');if(ex)return ex;let i={id:'INC'+(++S.incidentSerial),reality:id,title,severity:sev,status:'open',started:Date.now(),owner:'supervisory capital conservation board',x:10+Math.random()*80,y:12+Math.random()*68};S.incidents.push(i);return i}
function crisis(id,why,key,sev='SEV2'){let n=Date.now(),k=id+'|'+key;if(S.supervisoryCapitalKeys92[k]&&n-S.supervisoryCapitalKeys92[k]<14000)return;S.supervisoryCapitalKeys92[k]=n;S.supervisoryCapitalCrises92++;remember('SUPERVISORY CAPITAL CONSERVATION: '+why+' forced emergency lending to consume central-bank capital after price and collateral supervision had reached its ceiling',realm(id));if(typeof place==='function'){place('cold','a lender of last resort running out of policy levers and having to collateralize itself',realm(id));place('dream','central-bank capital locked behind an emergency loan that supervision could no longer make more expensive',realm(id))}incident(id,'supervisory capital conservation: '+why,sev)}
function ensure(){if(!S.monetaryExceptionOffice91||!S.monetaryRemediationOffice90)return null;if(!S.supervisoryCapitalOffice92){S.supervisoryCapitalOffice92={id:'SCB1',name:'Interreality Supervisory Capital Conservation Board',status:'ring-fencing',created:Date.now(),x:50,y:72};remember('SUPERVISORY CAPITAL SCB1: post-cap monetary exceptions acquired one-for-one central-bank capital backing',realm('A'));remember('SUPERVISORY CAPITAL SCB1: post-cap monetary exceptions acquired one-for-one central-bank capital backing',realm('B'));trust('A','supervisory-capital-conservation-created','SCB1');trust('B','supervisory-capital-conservation-created','SCB1')}return S.supervisoryCapitalOffice92}
function authority(id){return(S.monetaryAuthorities55||[]).find(a=>a.id===id)}
function facility(id){return(S.liquidityFacilities55||[]).find(f=>f.id===id)}
function stageBase(stage){return stage===1?{rate:.075,floor:'A'}:stage===2?{rate:.095,floor:'AA'}:stage===3?{rate:.12,floor:'AAA'}:null}
function gradeIndex(g){let i=GR.indexOf(g);return i<0?GR.length:i}
function policy(stage,count){let b=stageBase(stage);if(!b)return null;let extra=Math.max(0,count-1),rate=Math.min(.20,b.rate+extra*.02),i=Math.max(0,gradeIndex(b.floor)-extra),floor=GR[Math.min(i,GR.length-1)]||'AAA';return{rate,floor}}
function postCapRegistration(e){if(!e||e.kind91!=='exception-registration'||!(e.exceptionNumber91>1))return false;let prev=policy(e.supervisoryStage90,e.exceptionNumber91-1);return!!prev&&prev.rate>=.20-1e-9&&prev.floor==='AAA'}
function registrationEvents(){return(S.monetaryExceptionEvents91||[]).filter(postCapRegistration).sort((a,b)=>(a.created||0)-(b.created||0)||String(a.id).localeCompare(String(b.id)))}
function upsert(arr,id,snap){let i=arr.findIndex(x=>x.id===id);if(i>=0)arr[i]=snap;else arr.push(snap)}
function markReq(r,f,a){let snap=JSON.parse(JSON.stringify(r));if(f){f.supervisoryCapitalRequirement92=r.id;f.supervisoryCapitalMarker92=snap}if(a){a.supervisoryCapitalMarkers92=a.supervisoryCapitalMarkers92||[];upsert(a.supervisoryCapitalMarkers92,r.id,snap);a.supervisoryCapitalLatest92=r.id}}
function markAction(x,f,a){let snap=JSON.parse(JSON.stringify(x));if(f){f.supervisoryCapitalActions92=f.supervisoryCapitalActions92||[];upsert(f.supervisoryCapitalActions92,x.id,snap)}if(a){a.supervisoryCapitalActions92=a.supervisoryCapitalActions92||[];upsert(a.supervisoryCapitalActions92,x.id,snap);a.supervisoryCapitalActionLatest92=x.id}}
function reqForEvent(id){return(S.supervisoryCapitalRequirements92||[]).find(r=>r.exceptionEvent91===id)}
function action(kind,r,f,a,amount,before,after){let x={id:'SCA'+(++S.supervisoryCapitalActionSerial92),kind92:kind,requirementId92:r.id,exceptionEvent91:r.exceptionEvent91,facilityId55:r.facilityId55,authorityId:r.authorityId,reality:r.reality,amount92:amount,heldBefore92:before,heldAfter92:after,capitalAfter92:a.capital,created:Date.now()};S.supervisoryCapitalActions92.push(x);if(kind==='capital-topup'){S.supervisoryCapitalTopups92++;S.supervisoryCapitalTopupAmount92+=amount}else{S.supervisoryCapitalReleases92++;S.supervisoryCapitalReleaseAmount92+=amount}markAction(x,f,a);return x}
function createRequirement(e){if(reqForEvent(e.id))return null;let f=facility(e.facilityId55),a=authority(e.authorityId);if(!f||!a)return null;let target=['active','monetized'].includes(f.status)?Math.max(0,f.principal||0):0,r={id:'SCR'+(++S.supervisoryCapitalRequirementSerial92),exceptionEvent91:e.id,facilityId55:f.id,authorityId:a.id,reality:a.reality,sourceKind91:e.sourceKind91,exceptionNumber91:e.exceptionNumber91,supervisoryStage90:e.supervisoryStage90,originalPrincipal92:Math.max(0,f.principal||0),required92:target,held92:0,shortfall92:target,status:target>.0001?'pending-capital':'moot-repaid-before-build92',created:Date.now(),x:10+Math.random()*80,y:12+Math.random()*68};S.supervisoryCapitalRequirements92.push(r);S.supervisoryCapitalRequirementsCreated92++;f.supervisoryCapitalRequirement92=r.id;f.supervisoryCapitalBacked92=true;markReq(r,f,a);remember('SUPERVISORY CAPITAL '+r.id+': '+f.id+' exception #'+e.exceptionNumber91+' arrived after '+e.supervisoryStage90+'-stage policy had already reached 20% / AAA; one-for-one capital backing required',realm(a.reality));trust(a.reality,'post-cap-exception-capital-required',r.id+' '+f.id);if(target>.0001)crisis(a.reality,a.name+' issued '+f.id+' after the Build 91 policy ratchet was already saturated','requirement-'+r.id);return r}
function adjust(r){let f=facility(r.facilityId55),a=authority(r.authorityId);if(!a){r.status='orphaned-authority';return false}if(!f){r.status='orphaned-facility';markReq(r,null,a);return false}let target=['active','monetized'].includes(f.status)?Math.max(0,f.principal||0):0,changed=false;r.required92=target;if((r.held92||0)+1e-9<target){let gap=target-(r.held92||0),take=Math.min(gap,Math.max(0,a.capital||0));if(take>.0001){let before=r.held92||0;a.capital=Math.max(0,(a.capital||0)-take);r.held92=before+take;action('capital-topup',r,f,a,take,before,r.held92);changed=true}}if((r.held92||0)>target+1e-9){let rel=(r.held92||0)-target,before=r.held92||0;r.held92=target;a.capital=(a.capital||0)+rel;action('capital-release',r,f,a,rel,before,r.held92);changed=true}r.shortfall92=Math.max(0,target-(r.held92||0));if(target<=.0001&&r.held92<=.0001){r.required92=0;r.held92=0;r.shortfall92=0;r.status=f.status==='repaid'?'released-repaid':'released-closed';r.releasedAt92=r.releasedAt92||Date.now()}else if(r.shortfall92>.0001){r.status='capital-shortfall';crisis(a.reality,a.name+' could ring-fence only '+(r.held92||0).toFixed(2)+' of '+target.toFixed(2)+' required capital behind '+f.id,'shortfall-'+r.id,'SEV1')}else r.status=f.status==='monetized'?'reserved-monetized':'reserved-active';f.supervisoryCapitalHeld92=r.held92;f.supervisoryCapitalShortfall92=r.shortfall92;markReq(r,f,a);return changed}
function recompute(){let auths=new Set();S.supervisoryCapitalHeldTotal92=0;S.supervisoryCapitalShortfallTotal92=0;for(const a of(S.monetaryAuthorities55||[])){let rs=(S.supervisoryCapitalRequirements92||[]).filter(r=>r.authorityId===a.id&&!['orphaned-authority'].includes(r.status)),held=rs.reduce((n,r)=>n+Math.max(0,r.held92||0),0),short=rs.reduce((n,r)=>n+Math.max(0,r.shortfall92||0),0);a.supervisoryCapitalHeld92=held;a.supervisoryCapitalShortfall92=short;if(rs.length)auths.add(a.id);S.supervisoryCapitalHeldTotal92+=held;S.supervisoryCapitalShortfallTotal92+=short}S.supervisoryCapitalAuthorities92=auths.size}
function reconstruct(){if(!RECOVER92)return false;let changed=false,seenR=new Map(),seenA=new Map();for(const a of(S.monetaryAuthorities55||[])){for(const m of(a.supervisoryCapitalMarkers92||[]))seenR.set(m.id,m);for(const x of(a.supervisoryCapitalActions92||[]))seenA.set(x.id,x)}for(const f of(S.liquidityFacilities55||[])){let m=f.supervisoryCapitalMarker92;if(m)seenR.set(m.id,m);for(const x of(f.supervisoryCapitalActions92||[]))seenA.set(x.id,x)}for(const m of seenR.values()){if((S.supervisoryCapitalRequirements92||[]).some(x=>x.id===m.id))continue;let r=JSON.parse(JSON.stringify(m));r.recovered=true;S.supervisoryCapitalRequirements92.push(r);S.supervisoryCapitalRequirementsCreated92++;let n=Number(String(r.id).replace(/\D/g,''))||0;if(n>S.supervisoryCapitalRequirementSerial92)S.supervisoryCapitalRequirementSerial92=n;changed=true}for(const m of seenA.values()){if((S.supervisoryCapitalActions92||[]).some(x=>x.id===m.id))continue;let x=JSON.parse(JSON.stringify(m));x.recovered=true;S.supervisoryCapitalActions92.push(x);if(x.kind92==='capital-topup'){S.supervisoryCapitalTopups92++;S.supervisoryCapitalTopupAmount92+=x.amount92||0}else{S.supervisoryCapitalReleases92++;S.supervisoryCapitalReleaseAmount92+=x.amount92||0}let n=Number(String(x.id).replace(/\D/g,''))||0;if(n>S.supervisoryCapitalActionSerial92)S.supervisoryCapitalActionSerial92=n;changed=true}recompute();return changed}
function reconcile(){if(!ensure())return false;let changed=reconstruct();for(const e of registrationEvents())if(!reqForEvent(e.id)&&createRequirement(e))changed=true;for(const r of(S.supervisoryCapitalRequirements92||[]))if(adjust(r))changed=true;recompute();return changed}
function openReq(r){let f=facility(r.facilityId55),a=authority(r.authorityId),acts=[];for(const x of(S.supervisoryCapitalActions92||[]).filter(x=>x.requirementId92===r.id).slice(-6))acts.push(['open '+x.id,()=>openAction(x)]);acts.push(['close',closePanel]);panel(r.id+' · SUPERVISORY CAPITAL',r.status.toUpperCase(),(f?f.id:'missing facility')+' · exception #'+r.exceptionNumber91+' · required '+r.required92.toFixed(2)+' · held '+(r.held92||0).toFixed(2)+' · shortfall '+(r.shortfall92||0).toFixed(2)+' · authority free capital '+(a?a.capital.toFixed(2):'missing'),acts)}
function openAction(x){panel(x.id+' · SUPERVISORY CAPITAL ACTION',x.kind92.toUpperCase(),x.facilityId55+' · '+x.amount92.toFixed(2)+' · held '+x.heldBefore92.toFixed(2)+'→'+x.heldAfter92.toFixed(2)+' · authority free capital '+x.capitalAfter92.toFixed(2),[['close',closePanel]])}
function openOffice(){if(!ensure())return;let acts=[];for(const r of S.supervisoryCapitalRequirements92.slice(-10))acts.push(['open '+r.id+' · '+r.status,()=>openReq(r)]);acts.push(['close',closePanel]);panel(S.supervisoryCapitalOffice92.name,'RING-FENCING · SCB1',S.supervisoryCapitalRequirementsCreated92+' requirements · '+S.supervisoryCapitalHeldTotal92.toFixed(2)+' capital held · '+S.supervisoryCapitalShortfallTotal92.toFixed(2)+' shortfall · '+S.supervisoryCapitalReleaseAmount92.toFixed(2)+' released',acts)}
function render92(){if(!ensure())return;let layer=q('#supervisoryCapitalLayer92');if(!layer){layer=document.createElement('div');layer.id='supervisoryCapitalLayer92';document.body.appendChild(layer)}layer.innerHTML='';let o=document.createElement('i');o.className='supervisoryCapitalOffice92';o.dataset.label='CAP';o.style.left='50%';o.style.top='72%';o.onclick=openOffice;layer.appendChild(o);for(const r of S.supervisoryCapitalRequirements92.slice(-8)){let n=document.createElement('i');n.className='supervisoryCapital92 '+r.status;n.dataset.label=r.status==='capital-shortfall'?'C!':'C';n.style.left=r.x+'%';n.style.top=r.y+'%';n.onclick=()=>openReq(r);layer.appendChild(n)}let line=q('#supervisorycapitalline92');if(!line){line=document.createElement('div');line.id='supervisorycapitalline92';line.className='line';(q('#monetaryexceptionline91')||q('#monetaryremediationline90')||q('#monetaryline')||q('#enforcement')).after(line)}line.textContent='supervisory capital: '+S.supervisoryCapitalHeldTotal92.toFixed(2)+' held · '+S.supervisoryCapitalShortfallTotal92.toFixed(2)+' shortfall · '+S.supervisoryCapitalRequirementsCreated92+' requirements';let ctr=document.querySelector('#app .controls');if(ctr&&!q('#openSupervisoryCapital92')){let x=document.createElement('button');x.id='openSupervisoryCapital92';x.textContent='open supervisory capital';x.onclick=openOffice;ctr.prepend(x)}}
renderAll=function(){R92();let changed=reconcile();render92();if(changed)save92()};let f=q('#forget');if(f)f.onclick=()=>{for(let i=2;i<=92;i++)localStorage.removeItem('nothing-state-v'+i);location.reload()};setInterval(()=>{reconcile();render92();save92()},2300);ensure();reconcile();renderAll();save92();
})();