(()=>{
const BS44=save,BR44=renderAll,O44=JSON.parse(localStorage.getItem('nothing-state-v44')||'null')||{},cl=(v,a,b)=>Math.max(a,Math.min(b,v)),pick=a=>a&&a.length?a[Math.floor(Math.random()*a.length)]:null;
const NODES44=['traveler','bailiff','archive','court','administration'];
const COHORT44={traveler:'traveler',bailiff:'bailiff',archive:'archive',court:'courts',administration:'agencies'};
S.builders44=O44.builders44||[];
S.buildArtifacts44=O44.buildArtifacts44||[];
S.provenance44=O44.provenance44||[];
S.reproChecks44=O44.reproChecks44||[];
S.replicaArtifacts44=O44.replicaArtifacts44||{A:{},B:{}};
S.builderSerial44=O44.builderSerial44||0;
S.artifactSerial44=O44.artifactSerial44||0;
S.attestationSerial44=O44.attestationSerial44||0;
S.reproSerial44=O44.reproSerial44||0;
S.artifactsBuilt44=O44.artifactsBuilt44||0;
S.attestationsMade44=O44.attestationsMade44||0;
S.reproducibleBuilds44=O44.reproducibleBuilds44||0;
S.unreproducibleBuilds44=O44.unreproducibleBuilds44||0;
S.dependencyDrifts44=O44.dependencyDrifts44||0;
S.builderCompromises44=O44.builderCompromises44||0;
S.artifactSubstitutions44=O44.artifactSubstitutions44||0;
S.signedMismatches44=O44.signedMismatches44||0;
S.provenanceIncidents44=O44.provenanceIncidents44||0;
S.provenanceCrises44=O44.provenanceCrises44||0;
S.lastProvenanceCrisis44=O44.lastProvenanceCrisis44||0;
S.provenanceKeys44=O44.provenanceKeys44||{};
S.observedExecution44=O44.observedExecution44||{};
for(const id of ['A','B'])S.replicaArtifacts44[id]=S.replicaArtifacts44[id]||{};
S.builders44=S.builders44.map((b,i)=>Object.assign({id:b.id||'BLD'+(i+1),reality:b.reality||'A',role:b.role||'primary',status:b.status||'active',toolchain:b.toolchain||'tc-1',depLock:b.depLock||'lock-1',rootId:b.rootId||null,builds:b.builds||0,trust:Number.isFinite(b.trust)?b.trust:.62,compromisedAt:b.compromisedAt||null,x:Number.isFinite(b.x)?b.x:10+Math.random()*80,y:Number.isFinite(b.y)?b.y:12+Math.random()*68},b));
S.buildArtifacts44=S.buildArtifacts44.map((a,i)=>Object.assign({id:a.id||'BIN'+(i+1),reality:a.reality||'A',sourceRef:a.sourceRef||'legacy',builderId:a.builderId||null,toolchain:a.toolchain||'tc-1',depLock:a.depLock||'lock-1',recipeHash:a.recipeHash||'00000000',artifactHash:a.artifactHash||'00000000',patch:a.patch||0,owner:a.owner||null,status:a.status||'built',semanticDelta:a.semanticDelta||0,builtAt:a.builtAt||Date.now(),reproducedFrom:a.reproducedFrom||null,x:Number.isFinite(a.x)?a.x:10+Math.random()*80,y:Number.isFinite(a.y)?a.y:12+Math.random()*68},a));
S.provenance44=S.provenance44.map((p,i)=>Object.assign({id:p.id||'AT'+(i+1),artifactId:p.artifactId||null,reality:p.reality||'A',builderId:p.builderId||null,sourceRef:p.sourceRef||null,recipeHash:p.recipeHash||null,artifactHash:p.artifactHash||null,rootId:p.rootId||null,status:p.status||'attested',created:p.created||Date.now()},p));
S.reproChecks44=S.reproChecks44.map((r,i)=>Object.assign({id:r.id||'RB'+(i+1),reality:r.reality||'A',originalArtifactId:r.originalArtifactId||null,rebuildArtifactId:r.rebuildArtifactId||null,sourceRef:r.sourceRef||null,status:r.status||'pending',sameHash:!!r.sameHash,bothSigned:!!r.bothSigned,created:r.created||Date.now(),x:Number.isFinite(r.x)?r.x:10+Math.random()*80,y:Number.isFinite(r.y)?r.y:12+Math.random()*68},r));
function save44(){BS44();localStorage.setItem('nothing-state-v44',JSON.stringify({builders44:S.builders44,buildArtifacts44:S.buildArtifacts44,provenance44:S.provenance44,reproChecks44:S.reproChecks44,replicaArtifacts44:S.replicaArtifacts44,builderSerial44:S.builderSerial44,artifactSerial44:S.artifactSerial44,attestationSerial44:S.attestationSerial44,reproSerial44:S.reproSerial44,artifactsBuilt44:S.artifactsBuilt44,attestationsMade44:S.attestationsMade44,reproducibleBuilds44:S.reproducibleBuilds44,unreproducibleBuilds44:S.unreproducibleBuilds44,dependencyDrifts44:S.dependencyDrifts44,builderCompromises44:S.builderCompromises44,artifactSubstitutions44:S.artifactSubstitutions44,signedMismatches44:S.signedMismatches44,provenanceIncidents44:S.provenanceIncidents44,provenanceCrises44:S.provenanceCrises44,lastProvenanceCrisis44:S.lastProvenanceCrisis44,provenanceKeys44:S.provenanceKeys44,observedExecution44:S.observedExecution44}))}save=save44;
const realm=id=>S.real[id],artifact=id=>S.buildArtifacts44.find(a=>a.id===id),builder=id=>S.builders44.find(b=>b.id===id),node=(id,name)=>S.replica43?.[id]?.nodes?.[name],attestations=id=>S.provenance44.filter(p=>p.artifactId===id),acceptedRoots=id=>S.trustPolicies?.[id]?.acceptedRoots||[];
function hash44(s){let h=2166136261>>>0;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)>>>0}return h.toString(16).padStart(8,'0')}
function runtimeFor(id,name){let rt=S.runtimeReality?.[id],cid=COHORT44[name];return rt?.cohorts?.[cid]||rt?.stableHead||'legacy'}
function activeRoot(id){let ids=acceptedRoots(id);return [...(S.trustRoots||[])].filter(r=>ids.includes(r.id)&&r.status==='active').sort((a,b)=>(b.strength||0)-(a.strength||0))[0]||null}
function attestationTrusted(p){if(!p?.rootId)return false;let r=(S.trustRoots||[]).find(x=>x.id===p.rootId);return !!(r&&r.status==='active'&&acceptedRoots(p.reality).includes(r.id))}
function artifactTrusted(a){return attestations(a.id).some(attestationTrusted)&&!['quarantined','local-hotfix'].includes(a.status)}
function ensureBuilders(){for(const id of ['A','B'])for(const role of ['primary','verifier']){if(S.builders44.find(b=>b.reality===id&&b.role===role))continue;let r=activeRoot(id),b={id:'BLD'+(++S.builderSerial44),reality:id,role,status:'active',toolchain:'tc-'+(1+(id==='B'?1:0)),depLock:'lock-'+id.toLowerCase()+'-1',rootId:r?.id||null,builds:0,trust:role==='primary'?.66:.61,compromisedAt:null,x:10+Math.random()*80,y:12+Math.random()*68};S.builders44.push(b);remember('BUILDER '+b.id+': Reality '+id+' created a '+role+' build environment',realm(id))}}
function recipeHash(source,toolchain,depLock,patch=0){return hash44([source,toolchain,depLock,'patch'+patch].join('|'))}
function artifactHashFor(source,toolchain,depLock,patch=0,salt=''){return hash44(['artifact',source,toolchain,depLock,patch,salt].join('|'))}
function createArtifact(id,source,opts={}){ensureBuilders();let b=opts.builder||S.builders44.find(x=>x.reality===id&&x.role==='primary'),patch=opts.patch||0,toolchain=opts.toolchain||b?.toolchain||'local',depLock=opts.depLock||b?.depLock||'unlocked',local=!!opts.local,compromised=b?.status==='compromised',nondeterministic=!!opts.nondeterministic,substituted=!!opts.substituted||(!local&&compromised&&Math.random()<.45),salt=local?'local-'+(opts.owner||'unknown')+'-'+patch:(substituted?'substitute-'+Date.now():(nondeterministic?'nondet-'+Math.random():'')),a={id:'BIN'+(++S.artifactSerial44),reality:id,sourceRef:source,builderId:b?.id||('local/'+(opts.owner||'unknown')),toolchain,depLock,recipeHash:recipeHash(source,toolchain,depLock,patch),artifactHash:artifactHashFor(source,toolchain,depLock,patch,salt),patch,owner:opts.owner||null,status:local?'local-hotfix':(substituted?'substituted':'built'),semanticDelta:local?patch:(substituted?1+Math.floor(Math.random()*2):0),builtAt:Date.now(),reproducedFrom:opts.reproducedFrom||null,x:10+Math.random()*80,y:12+Math.random()*68};S.buildArtifacts44.push(a);S.buildArtifacts44=S.buildArtifacts44.slice(-72);S.artifactsBuilt44++;if(b)b.builds++;if(substituted){S.artifactSubstitutions44++;remember('ARTIFACT SUBSTITUTION '+a.id+': '+a.builderId+' produced '+a.artifactHash+' while declaring source '+source,realm(id));if(typeof place==='function')place('cold','signed binary that source does not explain',realm(id))}else if(local){remember('UNATTESTED ARTIFACT '+a.id+': '+opts.owner+' local patch has no reproducible builder provenance',realm(id));if(typeof place==='function')place('cold','binary that exists only on one replica',realm(id))}else remember('BUILD ARTIFACT '+a.id+': '+source+' → '+a.artifactHash+' by '+a.builderId,realm(id));if(!local)attestArtifact(a);return a}
function attestArtifact(a){if(!a||attestations(a.id).some(p=>p.artifactHash===a.artifactHash))return attestations(a.id)[0]||null;let r=activeRoot(a.reality),b=builder(a.builderId),p={id:'AT'+(++S.attestationSerial44),artifactId:a.id,reality:a.reality,builderId:a.builderId,sourceRef:a.sourceRef,recipeHash:a.recipeHash,artifactHash:a.artifactHash,rootId:r?.id||b?.rootId||null,status:r?'attested':'unsigned',created:Date.now()};S.provenance44.push(p);S.provenance44=S.provenance44.slice(-96);S.attestationsMade44++;if(r){b&&(b.rootId=r.id);remember('PROVENANCE '+p.id+': '+r.id+' attested '+a.id+' as output of '+a.sourceRef,realm(a.reality));S.trustAudits=S.trustAudits||[];S.trustAuditSerial=S.trustAuditSerial||0;S.trustAudits.push({id:'TA'+(++S.trustAuditSerial),reality:a.reality,remediationId:null,credentialId:null,certificateId:null,rootId:r.id,status:'provenance-attested',created:Date.now(),note:p.id+' '+a.id,x:10+Math.random()*80,y:12+Math.random()*68})}else remember('UNSIGNED PROVENANCE '+p.id+': no accepted root could attest '+a.id,realm(a.reality));return p}
function desiredArtifact(id,name){let source=runtimeFor(id,name),n=node(id,name),patch=n?.localPatch||0,assigned=artifact(S.replicaArtifacts44[id][name]);if(assigned&&assigned.sourceRef===source&&assigned.patch===patch&&(!patch||assigned.owner===name))return assigned;if(patch){let a=createArtifact(id,source,{patch,owner:name,local:true});S.replicaArtifacts44[id][name]=a.id;return a}let existing=[...S.buildArtifacts44].reverse().find(a=>a.reality===id&&a.sourceRef===source&&a.patch===0&&a.status!=='quarantined'&&a.builderId===S.builders44.find(b=>b.reality===id&&b.role==='primary')?.id);let a=existing||createArtifact(id,source);S.replicaArtifacts44[id][name]=a.id;return a}
function ensureAssignments(){ensureBuilders();for(const id of ['A','B'])for(const name of NODES44)desiredArtifact(id,name)}
function rebuildArtifact(a,manual=true){if(!a||a.patch){$('#msg').textContent='Local hotfixes cannot be reproduced from a declared clean recipe.';return null}ensureBuilders();let v=S.builders44.find(b=>b.reality===a.reality&&b.role==='verifier'),nondet=Math.random()<.045,substituted=v?.status==='compromised'&&Math.random()<.55,rb=createArtifact(a.reality,a.sourceRef,{builder:v,toolchain:a.toolchain,depLock:a.depLock,reproducedFrom:a.id,nondeterministic:nondet,substituted}),same=rb.artifactHash===a.artifactHash,bothSigned=artifactTrusted(a)&&artifactTrusted(rb),c={id:'RB'+(++S.reproSerial44),reality:a.reality,originalArtifactId:a.id,rebuildArtifactId:rb.id,sourceRef:a.sourceRef,status:same?'reproducible':'mismatch',sameHash:same,bothSigned,created:Date.now(),x:10+Math.random()*80,y:12+Math.random()*68};S.reproChecks44.push(c);S.reproChecks44=S.reproChecks44.slice(-48);if(same){S.reproducibleBuilds44++;let b=builder(a.builderId);if(b)b.trust=cl((b.trust||.6)+.015,.1,.99);remember('REPRODUCIBLE BUILD '+c.id+': '+a.id+' and '+rb.id+' independently produced '+a.artifactHash,realm(a.reality));if(typeof place==='function')place('warm','two builders one binary',realm(a.reality));$('#msg').textContent=c.id+' PASSED: independent builders produced '+a.artifactHash+'.'}else{S.unreproducibleBuilds44++;remember('UNREPRODUCIBLE BUILD '+c.id+': same declared source produced '+a.artifactHash+' and '+rb.artifactHash,realm(a.reality));if(typeof place==='function'){place('cold','same source two binaries',realm(a.reality));place('dream','provenance statement with incompatible outputs',realm(a.reality))}openProvenanceIncident(a.reality,'same declared source produced different build artifacts','SEV1');if(bothSigned){S.signedMismatches44++;provenanceCrisis(a.reality,'signed-mismatch');$('#msg').textContent=c.id+' FAILED: both different binaries have accepted provenance signatures.'}else $('#msg').textContent=c.id+' FAILED: independent rebuild hash differs.'}renderAll();save44();if(manual)openRepro(c);return c}
function rebuildActive(id=S.active){ensureAssignments();let ids=[...new Set(NODES44.map(n=>S.replicaArtifacts44[id][n]))],as=ids.map(artifact).filter(a=>a&&!a.patch);if(!as.length){$('#msg').textContent='No clean active artifacts are available to reproduce.';return}for(const a of as.slice(0,3))rebuildArtifact(a,false);renderAll();save44();openSupplyChain(id)}
function driftDependencies(id=S.active){ensureBuilders();let b=S.builders44.find(x=>x.reality===id&&x.role==='primary');if(!b)return;b.depLock='lock-'+id.toLowerCase()+'-'+(1+S.dependencyDrifts44+1);S.dependencyDrifts44++;remember('DEPENDENCY DRIFT: '+b.id+' now resolves '+b.depLock+' without a source-code change',realm(id));if(typeof place==='function')place('dream','dependency lock changed beneath same source',realm(id));for(const name of NODES44){let n=node(id,name);if(n?.localPatch)continue;let source=runtimeFor(id,name),a=createArtifact(id,source,{builder:b});S.replicaArtifacts44[id][name]=a.id}openProvenanceIncident(id,'runtime artifacts changed after dependency drift','SEV2');$('#msg').textContent=b.id+' rebuilt current runtimes with '+b.depLock+'. Source refs stayed the same; binary hashes did not.';renderAll();save44();openSupplyChain(id)}
function compromiseBuilder(b){if(!b||b.status==='compromised')return;b.status='compromised';b.compromisedAt=Date.now();b.trust=cl((b.trust||.6)-.18,.05,.99);S.builderCompromises44++;remember('BUILDER COMPROMISED '+b.id+': signed provenance can no longer prove the build process was honest',realm(b.reality));if(typeof place==='function')place('cold','trusted builder with an untrusted workspace',realm(b.reality));openProvenanceIncident(b.reality,'build environment compromise: '+b.id,'SEV1');provenanceCrisis(b.reality,'builder-compromise');$('#msg').textContent=b.id+' is compromised. Its next artifact may be correctly signed and still not match its declared inputs.';renderAll();save44();openBuilder(b)}
function rotateBuilder(b){if(!b)return;b.status='retired';let nb={id:'BLD'+(++S.builderSerial44),reality:b.reality,role:b.role,status:'active',toolchain:b.toolchain,depLock:b.depLock,rootId:activeRoot(b.reality)?.id||null,builds:0,trust:.58,compromisedAt:null,x:10+Math.random()*80,y:12+Math.random()*68};S.builders44.push(nb);remember('BUILDER ROTATION: '+b.id+' → '+nb.id+'. Old artifacts remain deployed.',realm(b.reality));if(typeof place==='function')place('dream','new builder beside old binaries',realm(b.reality));renderAll();save44();openBuilder(nb)}
function quarantineArtifact(a){if(!a)return;a.status='quarantined';for(const id of ['A','B'])for(const name of NODES44)if(S.replicaArtifacts44[id][name]===a.id)S.replicaArtifacts44[id][name]=null;remember('ARTIFACT QUARANTINED '+a.id+': deployment history remains, but provenance no longer accepts the binary',realm(a.reality));if(typeof place==='function')place('cold','quarantined binary still present in history',realm(a.reality));renderAll();save44();openArtifact(a)}
function openProvenanceIncident(id,title,severity='SEV2'){S.incidents=S.incidents||[];let x=S.incidents.find(n=>n.reality===id&&n.status==='open'&&n.title===title);if(x)return x;S.incidentSerial=S.incidentSerial||0;x={id:'INC'+(++S.incidentSerial),reality:id,title,severity,status:'open',alertIds:[],started:Date.now(),acknowledged:null,resolved:null,postmortem:null,owner:'supply-chain review',x:10+Math.random()*80,y:12+Math.random()*68};S.incidents.push(x);S.provenanceIncidents44++;remember('SUPPLY CHAIN INCIDENT '+x.id+': '+title,realm(id));return x}
function provenanceCrisis(id,reason){if(Date.now()-S.lastProvenanceCrisis44<8000)return false;let key=id+'|'+reason+'|'+Math.floor(Date.now()/20000);if(S.provenanceKeys44[key])return false;S.provenanceKeys44[key]=1;S.provenanceCrises44++;S.lastProvenanceCrisis44=Date.now();for(const rid of ['A','B']){realm(rid).disputes=(realm(rid).disputes||0)+1;remember('SUPPLY CHAIN CRISIS: provenance proved who signed the artifact but not that the artifact followed from its declared source',realm(rid))}realm(id).timelineDrift=(realm(id).timelineDrift||0)+1;if(typeof place==='function'){place('cold','two signed binaries one source commit',realm(id));place('dream','attestation proving the wrong thing faithfully',realm(id))}S.bailiffMood='asking whether a signed binary is the same thing as the source';return true}
function auditExecutionRounds(){ensureAssignments();for(const r of S.executionRounds43||[]){let key='er:'+r.id;if(S.observedExecution44[key])continue;S.observedExecution44[key]=1;let applied=(r.results||[]).filter(x=>x.status==='applied'),rows=applied.map(x=>{let a=desiredArtifact(r.reality,x.node);return{node:x.node,stateHash:x.hash,artifactId:a.id,artifactHash:a.artifactHash,source:a.sourceRef,trusted:artifactTrusted(a)}}),states=[...new Set(rows.map(x=>x.stateHash))],bins=[...new Set(rows.map(x=>x.artifactHash))];if(states.length>1&&bins.length>1){remember('PROVENANCE DIAGNOSIS '+r.id+': divergent state hashes correlate with '+bins.length+' deployed artifacts',realm(r.reality));openProvenanceIncident(r.reality,'replica divergence correlated with different runtime artifacts','SEV2')}else if(states.length>1&&bins.length===1){remember('NONDETERMINISM '+r.id+': replicas running artifact '+bins[0]+' produced different state hashes',realm(r.reality));if(typeof place==='function')place('cold','same binary different reality state',realm(r.reality));openProvenanceIncident(r.reality,'same artifact produced divergent replica state','SEV1');provenanceCrisis(r.reality,'same-binary-divergence')}if(rows.some(x=>!x.trusted)){remember('UNPROVENANCED EXECUTION '+r.id+': at least one replica executed a binary without currently trusted provenance',realm(r.reality));openProvenanceIncident(r.reality,'consensus-final history executed with untrusted artifact provenance','SEV2')}}}
function autonomousSubstitution(){for(const id of ['A','B']){let b=S.builders44.find(x=>x.reality===id&&x.role==='primary'&&x.status==='compromised');if(!b||Math.random()>.004)continue;let name=pick(NODES44),n=node(id,name);if(n?.localPatch)continue;let a=createArtifact(id,runtimeFor(id,name),{builder:b,substituted:true,owner:name});S.replicaArtifacts44[id][name]=a.id;remember('LIVE ARTIFACT SWAP: '+name+' now presents '+a.id+' under unchanged runtime label '+a.sourceRef,realm(id));openProvenanceIncident(id,'compromised builder substituted a live replica artifact','SEV1');break}}
function openBuilder(b){let bs=[];if(b.status==='active')bs.push(['rebuild active source here',()=>{let a=artifact(S.replicaArtifacts44[b.reality][NODES44.find(n=>!node(b.reality,n)?.localPatch)]);if(a)rebuildArtifact(a)}],['simulate compromise',()=>compromiseBuilder(b)],['rotate builder',()=>rotateBuilder(b)]);bs.push(['close',closePanel]);panel(b.id+' · '+b.role.toUpperCase()+' BUILDER','Reality '+b.reality+' · '+b.status+'\ntoolchain '+b.toolchain+' · '+b.depLock,'builds '+b.builds+' · trust '+Math.round((b.trust||0)*100)+'% · signing root '+(b.rootId||'none'),bs)}
function openArtifact(a){let ats=attestations(a.id),bs=[];if(!a.patch)bs.push(['independent rebuild',()=>rebuildArtifact(a)]);if(!ats.length&&!a.patch)bs.push(['attest artifact',()=>{attestArtifact(a);renderAll();save44();openArtifact(a)}]);if(a.status!=='quarantined')bs.push(['quarantine artifact',()=>quarantineArtifact(a)]);bs.push(['close',closePanel]);panel(a.id+' · '+a.status.toUpperCase(),a.sourceRef+' → '+a.artifactHash,'builder '+a.builderId+' · recipe '+a.recipeHash+'\n'+a.toolchain+' · '+a.depLock+' · patch '+a.patch+'\nprovenance '+(ats.map(p=>p.id+':'+(attestationTrusted(p)?'trusted':'untrusted')).join(', ')||'none'),bs)}
function openRepro(c){let a=artifact(c.originalArtifactId),b=artifact(c.rebuildArtifactId),bs=[['open '+a.id,()=>openArtifact(a)],['open '+b.id,()=>openArtifact(b)],['close',closePanel]];panel(c.id+' · '+c.status.toUpperCase(),c.sourceRef,'original '+a.artifactHash+'\nrebuild '+b.artifactHash+'\nboth accepted signatures: '+(c.bothSigned?'YES':'no'),bs)}
function openSupplyChain(id=S.active){ensureAssignments();let active=[...new Set(NODES44.map(n=>S.replicaArtifacts44[id][n]))].map(artifact).filter(Boolean),bs=[];for(const b of S.builders44.filter(b=>b.reality===id&&b.status!=='retired'))bs.push(['open '+b.id,()=>openBuilder(b)]);for(const a of active)bs.push(['open '+a.id,()=>openArtifact(a)]);for(const c of [...S.reproChecks44].reverse().filter(c=>c.reality===id).slice(0,2))bs.push(['open '+c.id,()=>openRepro(c)]);bs.push(['rebuild active artifacts',()=>rebuildActive(id)],['drift dependencies',()=>driftDependencies(id)],['close',closePanel]);panel('PROVENANCE · Reality '+id,NODES44.map(n=>n+' → '+(artifact(S.replicaArtifacts44[id][n])?.artifactHash||'none')).join('\n'),'artifacts '+S.artifactsBuilt44+' · attestations '+S.attestationsMade44+' · reproducible '+S.reproducibleBuilds44+' · mismatches '+S.unreproducibleBuilds44+' · substitutions '+S.artifactSubstitutions44+' · signed mismatches '+S.signedMismatches44+' · crises '+S.provenanceCrises44,bs)}
function renderSupplyChain(){ensureAssignments();let layer=$('#provenanceLayer');if(!layer){layer=document.createElement('div');layer.id='provenanceLayer';document.body.appendChild(layer)}layer.innerHTML='';for(const a of S.buildArtifacts44.slice(-24)){let e=document.createElement('i');e.className='buildArtifact '+a.status+(artifactTrusted(a)?' trusted':' untrusted');e.dataset.label=a.id;e.style.left=a.x+'%';e.style.top=a.y+'%';e.onclick=()=>openArtifact(a);layer.appendChild(e)}for(const c of S.reproChecks44.filter(c=>c.status==='mismatch').slice(-8)){let e=document.createElement('i');e.className='reproMismatch';e.dataset.label=c.id;e.style.left=c.x+'%';e.style.top=c.y+'%';e.onclick=()=>openRepro(c);layer.appendChild(e)}let line=$('#provenanceline');if(!line){line=document.createElement('div');line.id='provenanceline';line.className='line';($('#replicaline')||$('#quorumline')||$('#transparencyline')||$('#enforcement')).after(line)}let id=S.active,arts=NODES44.map(n=>artifact(S.replicaArtifacts44[id][n])).filter(Boolean),hashes=new Set(arts.map(a=>a.artifactHash)),trusted=arts.filter(artifactTrusted).length;line.textContent='provenance: '+hashes.size+' artifact hashes · '+trusted+'/5 replicas trusted · '+S.reproducibleBuilds44+' reproducible · '+S.unreproducibleBuilds44+' mismatches · '+S.artifactSubstitutions44+' substitutions · '+S.signedMismatches44+' signed conflicts · '+S.provenanceCrises44+' crises';let ctr=document.querySelector('#app .controls');if(ctr&&!$('#openProvenanceButton')){let b=document.createElement('button');b.id='openProvenanceButton';b.textContent='open provenance';b.onclick=()=>openSupplyChain(S.active);ctr.prepend(b)}if(ctr&&!$('#rebuildArtifactsButton')){let b=document.createElement('button');b.id='rebuildArtifactsButton';b.textContent='rebuild runtime';b.onclick=()=>rebuildActive(S.active);ctr.prepend(b)}}
renderAll=function(){BR44();renderSupplyChain()};let f=$('#forget');if(f)f.onclick=()=>{for(let i=2;i<=44;i++)localStorage.removeItem('nothing-state-v'+i);location.reload()};
setInterval(()=>{ensureAssignments();auditExecutionRounds();autonomousSubstitution();renderSupplyChain();save44()},2100);ensureAssignments();auditExecutionRounds();renderAll();save44();
})();
