(()=>{
const B95=save,R95=renderAll,O=JSON.parse(localStorage.getItem('nothing-state-v95')||'null')||{},RECOVER95=!Array.isArray(O.surchargeBreachEpisodes95)||!Array.isArray(O.surchargeRecidivismRequirements95)||!Array.isArray(O.surchargeRecidivismActions95),K=['surchargeRecidivismOffice95','surchargeBreachEpisodes95','surchargeRecidivismRequirements95','surchargeRecidivismActions95','surchargeBreachEpisodeSerial95','surchargeRecidivismRequirementSerial95','surchargeRecidivismActionSerial95','surchargeBreachEpisodesCreated95','surchargeRecidivismRequirementsCreated95','surchargeRecidivismTopups95','surchargeRecidivismTopupAmount95','surchargeRecidivismReleases95','surchargeRecidivismReleaseAmount95','surchargeRecidivismHeldTotal95','surchargeRecidivismShortfallTotal95','surchargeRecidivismAuthorities95','surchargeRecidivismCrises95','surchargeRecidivismKeys95','lastSurchargeRecidivismTick95'];
for(const k of K)S[k]=O[k]??(k==='surchargeBreachEpisodes95'||k==='surchargeRecidivismRequirements95'||k==='surchargeRecidivismActions95'?[]:/Serial|Created|Topups|Amount|Releases|HeldTotal|ShortfallTotal|Authorities|Crises|Tick/.test(k)?0:/Keys/.test(k)?{}:/Office/.test(k)?null:[]);
function save95(){B95();let o={};for(const k of K)o[k]=S[k];localStorage.setItem('nothing-state-v95',JSON.stringify(o))}save=save95;
const q=s=>$(s),realm=id=>S.real[id],EPS=.0001;
function trust(id,status,note){S.trustAudits=S.trustAudits||[];S.trustAuditSerial=S.trustAuditSerial||0;S.trustAudits.push({id:'TA'+(++S.trustAuditSerial),reality:id,status,created:Date.now(),note,x:10+Math.random()*80,y:12+Math.random()*68})}
function incident(id,title,sev='SEV2'){S.incidents=S.incidents||[];S.incidentSerial=S.incidentSerial||0;let ex=S.incidents.find(x=>x.reality===id&&x.title===title&&x.status==='open');if(ex)return ex;let i={id:'INC'+(++S.incidentSerial),reality:id,title,severity:sev,status:'open',started:Date.now(),owner:'surcharge recidivism board',x:10+Math.random()*80,y:12+Math.random()*68};S.incidents.push(i);return i}
function crisis(id,why,key,sev='SEV1'){let n=Date.now(),k=id+'|'+key;if(S.surchargeRecidivismKeys95[k]&&n-S.surchargeRecidivismKeys95[k]<14000)return;S.surchargeRecidivismKeys95[k]=n;S.surchargeRecidivismCrises95++;remember('SURCHARGE RECIDIVISM: '+why+' escalated the capital penalty because a prior restoration surcharge had already failed',realm(id));if(typeof place==='function'){place('cold','a central bank paying a higher capital price after the first restoration surcharge ran short',realm(id));place('dream','a supervisory strike that does not punish the first breach twice but makes the next exception more expensive',realm(id))}incident(id,'surcharge recidivism: '+why,sev)}
function ensure(){if(!S.restorationSurchargeOffice94||!S.capitalRestorationOffice93)return null;if(!S.surchargeRecidivismOffice95){S.surchargeRecidivismOffice95={id:'SRB1',name:'Interreality Surcharge Recidivism Board',status:'progressive-capital-penalty',created:Date.now(),x:50,y:90};remember('SURCHARGE RECIDIVISM SRB1: a Build 94 surcharge shortfall became a supervisory strike; only later exceptions in the same restoration episode receive the extra penalty',realm('A'));remember('SURCHARGE RECIDIVISM SRB1: a Build 94 surcharge shortfall became a supervisory strike; only later exceptions in the same restoration episode receive the extra penalty',realm('B'));trust('A','surcharge-recidivism-created','SRB1');trust('B','surcharge-recidivism-created','SRB1')}return S.surchargeRecidivismOffice95}
function authority(id){return(S.monetaryAuthorities55||[]).find(a=>a.id===id)}
function facility(id){return(S.liquidityFacilities55||[]).find(f=>f.id===id)}
function order93(id){return(S.capitalRestorationOrders93||[]).find(o=>o.id===id)}
function active93(o){return o&&!['released-exposure-closed','orphaned-authority'].includes(o.status)}
function req94(id){return(S.restorationSurchargeRequirements94||[]).find(r=>r.id===id)}
function reqs94ForOrder(id){return(S.restorationSurchargeRequirements94||[]).filter(r=>r.restorationOrderId93===id&&!['orphaned-authority','orphaned-facility'].includes(r.status))}
function episodeForOrder(id){return(S.surchargeBreachEpisodes95||[]).find(e=>e.restorationOrderId93===id)}
function penaltyFor94(id){return(S.surchargeRecidivismRequirements95||[]).find(r=>r.build94RequirementId===id)}
function upsert(arr,id,snap){let i=arr.findIndex(x=>x.id===id);if(i>=0)arr[i]=snap;else arr.push(snap)}
function markEpisode(e,a){if(!a)return;let snap=JSON.parse(JSON.stringify(e));a.surchargeBreachEpisodes95=a.surchargeBreachEpisodes95||[];upsert(a.surchargeBreachEpisodes95,e.id,snap);a.surchargeBreachLatest95=e.id}
function markReq(r,f,a){let snap=JSON.parse(JSON.stringify(r));if(f){f.surchargeRecidivismRequirement95=r.id;f.surchargeRecidivismMarker95=snap}if(a){a.surchargeRecidivismMarkers95=a.surchargeRecidivismMarkers95||[];upsert(a.surchargeRecidivismMarkers95,r.id,snap);a.surchargeRecidivismLatest95=r.id}}
function markAction(x,f,a){let snap=JSON.parse(JSON.stringify(x));if(f){f.surchargeRecidivismActions95=f.surchargeRecidivismActions95||[];upsert(f.surchargeRecidivismActions95,x.id,snap)}if(a){a.surchargeRecidivismActions95=a.surchargeRecidivismActions95||[];upsert(a.surchargeRecidivismActions95,x.id,snap);a.surchargeRecidivismActionLatest95=x.id}}
function action(kind,r,f,a,amount,before,after){let x={id:'RPA'+(++S.surchargeRecidivismActionSerial95),kind95:kind,requirementId95:r.id,build94RequirementId:r.build94RequirementId,breachEpisodeId95:r.breachEpisodeId95,restorationOrderId93:r.restorationOrderId93,facilityId55:r.facilityId55,authorityId:r.authorityId,reality:r.reality,amount95:amount,heldBefore95:before,heldAfter95:after,capitalAfter95:a.capital,created:Date.now()};S.surchargeRecidivismActions95.push(x);markAction(x,f,a);return x}
function observeBreaches(){let changed=false,office=ensure();if(!office)return false;for(const o of(S.capitalRestorationOrders93||[])){let a=authority(o.authorityId),rs=reqs94ForOrder(o.id),short=rs.reduce((n,r)=>n+Math.max(0,r.shortfall94||0),0),e=episodeForOrder(o.id);if(!active93(o)){if(e&&e.status!=='closed-restoration-ended'){e.currentShortfall95=0;e.status='closed-restoration-ended';e.closedAt95=Date.now();markEpisode(e,a);changed=true}continue}if(!e&&short>EPS){e={id:'SBE'+(++S.surchargeBreachEpisodeSerial95),restorationOrderId93:o.id,authorityId:o.authorityId,reality:o.reality,currentShortfall95:short,peakShortfall95:short,sourceRequirements95:rs.map(r=>r.id),status:'strike-active',created:Date.now(),x:10+Math.random()*80,y:12+Math.random()*68};S.surchargeBreachEpisodes95.push(e);markEpisode(e,a);trust(o.reality,'restoration-surcharge-breach-observed',e.id+' '+o.id);crisis(o.reality,(a?a.name:o.authorityId)+' failed a Build 94 restoration surcharge during '+o.id,'episode-'+e.id);changed=true}else if(e){let peak=Math.max(e.peakShortfall95||0,short),status='strike-active';if(Math.abs((e.currentShortfall95||0)-short)>1e-9||Math.abs((e.peakShortfall95||0)-peak)>1e-9||e.status!==status){e.currentShortfall95=short;e.peakShortfall95=peak;e.status=status;markEpisode(e,a);changed=true}}}return changed}
function eligible94(r){if(!r||penaltyFor94(r.id))return null;let office=ensure();if(!office||(r.created||0)<(office.created||0))return null;let e=episodeForOrder(r.restorationOrderId93);if(!e||e.status!=='strike-active'||(e.sourceRequirements95||[]).includes(r.id))return null;let o=order93(r.restorationOrderId93);if(!active93(o)||r.authorityId!==e.authorityId)return null;return e}
function createPenalty(r94,e){let f=facility(r94.facilityId55),a=authority(r94.authorityId);if(!f||!a)return null;let target=['active','monetized'].includes(f.status)?Math.max(0,f.principal||0)*.5:0,r={id:'RPR'+(++S.surchargeRecidivismRequirementSerial95),build94RequirementId:r94.id,exceptionEvent91:r94.exceptionEvent91,build92RequirementId:r94.build92RequirementId,breachEpisodeId95:e.id,restorationOrderId93:r94.restorationOrderId93,facilityId55:f.id,authorityId:a.id,reality:a.reality,exceptionNumber91:r94.exceptionNumber91,supervisoryStage90:r94.supervisoryStage90,penaltyRate95:.5,required95:target,held95:0,shortfall95:target,status:target>EPS?'pending-penalty':'moot-repaid-before-build95',created:Date.now(),x:10+Math.random()*80,y:12+Math.random()*68};S.surchargeRecidivismRequirements95.push(r);markReq(r,f,a);remember('SURCHARGE RECIDIVISM '+r.id+': '+f.id+' followed '+e.id+' in the same restoration episode and acquired another 50% capital penalty',realm(a.reality));trust(a.reality,'recidivist-exception-capital-penalty',r.id+' '+f.id);if(target>EPS)crisis(a.reality,a.name+' issued '+f.id+' after '+e.id+' had already recorded a failed restoration surcharge','penalty-'+r.id);return r}
function olderClaims95(a){let s92=(S.supervisoryCapitalRequirements92||[]).filter(r=>r.authorityId===a.id&&!['orphaned-authority'].includes(r.status)).reduce((n,r)=>n+Math.max(0,r.shortfall92||0),0),o=(S.capitalRestorationOrders93||[]).find(o=>o.authorityId===a.id&&!['released-exposure-closed','orphaned-authority'].includes(o.status)),g93=o?Math.max(0,o.bufferGap93||0):0,s94=(S.restorationSurchargeRequirements94||[]).filter(r=>r.authorityId===a.id&&!['orphaned-authority','orphaned-facility'].includes(r.status)).reduce((n,r)=>n+Math.max(0,r.shortfall94||0),0);return s92+g93+s94}
function adjust(r){let f=facility(r.facilityId55),a=authority(r.authorityId);if(!a){r.status='orphaned-authority';return false}if(!f){r.status='orphaned-facility';markReq(r,null,a);return false}let target=['active','monetized'].includes(f.status)?Math.max(0,f.principal||0)*.5:0,changed=false;r.required95=target;if((r.held95||0)+1e-9<target&&olderClaims95(a)<=EPS){let gap=target-(r.held95||0),take=Math.min(gap,Math.max(0,a.capital||0));if(take>EPS){let before=r.held95||0;a.capital=Math.max(0,(a.capital||0)-take);r.held95=before+take;action('recidivism-topup',r,f,a,take,before,r.held95);changed=true}}if((r.held95||0)>target+1e-9){let rel=(r.held95||0)-target,before=r.held95||0;r.held95=target;a.capital=(a.capital||0)+rel;action('recidivism-release',r,f,a,rel,before,r.held95);changed=true}r.shortfall95=Math.max(0,target-(r.held95||0));if(target<=EPS&&r.held95<=EPS){r.required95=0;r.held95=0;r.shortfall95=0;r.status=f.status==='repaid'?'released-repaid':'released-closed';r.releasedAt95=r.releasedAt95||Date.now()}else if(r.shortfall95>EPS){r.status='penalty-shortfall';crisis(a.reality,a.name+' could fund only '+(r.held95||0).toFixed(2)+' of '+target.toFixed(2)+' recidivism penalty behind '+f.id,'shortfall-'+r.id)}else r.status=f.status==='monetized'?'penalty-monetized':'penalty-active';f.surchargeRecidivismHeld95=r.held95;f.surchargeRecidivismShortfall95=r.shortfall95;markReq(r,f,a);return changed}
function recompute(){S.surchargeBreachEpisodesCreated95=(S.surchargeBreachEpisodes95||[]).length;S.surchargeRecidivismRequirementsCreated95=(S.surchargeRecidivismRequirements95||[]).length;let tops=(S.surchargeRecidivismActions95||[]).filter(x=>x.kind95==='recidivism-topup'),rels=(S.surchargeRecidivismActions95||[]).filter(x=>x.kind95==='recidivism-release');S.surchargeRecidivismTopups95=tops.length;S.surchargeRecidivismTopupAmount95=tops.reduce((n,x)=>n+(x.amount95||0),0);S.surchargeRecidivismReleases95=rels.length;S.surchargeRecidivismReleaseAmount95=rels.reduce((n,x)=>n+(x.amount95||0),0);S.surchargeRecidivismHeldTotal95=0;S.surchargeRecidivismShortfallTotal95=0;let auths=new Set();for(const a of(S.monetaryAuthorities55||[])){let rs=(S.surchargeRecidivismRequirements95||[]).filter(r=>r.authorityId===a.id&&!['orphaned-authority'].includes(r.status)),held=rs.reduce((n,r)=>n+Math.max(0,r.held95||0),0),short=rs.reduce((n,r)=>n+Math.max(0,r.shortfall95||0),0);a.surchargeRecidivismHeld95=held;a.surchargeRecidivismShortfall95=short;if(rs.length)auths.add(a.id);S.surchargeRecidivismHeldTotal95+=held;S.surchargeRecidivismShortfallTotal95+=short}S.surchargeRecidivismAuthorities95=auths.size}
function reconstruct(){if(!RECOVER95)return false;let changed=false,se=new Map(),sr=new Map(),sa=new Map();for(const a of(S.monetaryAuthorities55||[])){for(const e of(a.surchargeBreachEpisodes95||[]))se.set(e.id,e);for(const r of(a.surchargeRecidivismMarkers95||[]))sr.set(r.id,r);for(const x of(a.surchargeRecidivismActions95||[]))sa.set(x.id,x)}for(const f of(S.liquidityFacilities55||[])){let r=f.surchargeRecidivismMarker95;if(r)sr.set(r.id,r);for(const x of(f.surchargeRecidivismActions95||[]))sa.set(x.id,x)}for(const m of se.values()){if(S.surchargeBreachEpisodes95.some(x=>x.id===m.id))continue;let e=JSON.parse(JSON.stringify(m));e.recovered=true;S.surchargeBreachEpisodes95.push(e);let n=Number(String(e.id).replace(/\D/g,''))||0;if(n>S.surchargeBreachEpisodeSerial95)S.surchargeBreachEpisodeSerial95=n;changed=true}for(const m of sr.values()){if(S.surchargeRecidivismRequirements95.some(x=>x.id===m.id))continue;let r=JSON.parse(JSON.stringify(m));r.recovered=true;S.surchargeRecidivismRequirements95.push(r);let n=Number(String(r.id).replace(/\D/g,''))||0;if(n>S.surchargeRecidivismRequirementSerial95)S.surchargeRecidivismRequirementSerial95=n;changed=true}for(const m of sa.values()){if(S.surchargeRecidivismActions95.some(x=>x.id===m.id))continue;let x=JSON.parse(JSON.stringify(m));x.recovered=true;S.surchargeRecidivismActions95.push(x);let n=Number(String(x.id).replace(/\D/g,''))||0;if(n>S.surchargeRecidivismActionSerial95)S.surchargeRecidivismActionSerial95=n;changed=true}recompute();return changed}
function reconcile(){if(!ensure())return false;let changed=reconstruct();if(observeBreaches())changed=true;for(const r94 of(S.restorationSurchargeRequirements94||[])){let e=eligible94(r94);if(e&&createPenalty(r94,e))changed=true}for(const r of(S.surchargeRecidivismRequirements95||[]))if(adjust(r))changed=true;recompute();return changed}
function openEpisode(e){let a=authority(e.authorityId),acts=[];for(const r of(S.surchargeRecidivismRequirements95||[]).filter(r=>r.breachEpisodeId95===e.id).slice(-8))acts.push(['open '+r.id+' · '+r.status,()=>openReq(r)]);acts.push(['close',closePanel]);panel(e.id+' · SURCHARGE STRIKE',e.status.toUpperCase(),(a?a.name:e.authorityId)+' · restoration '+e.restorationOrderId93+' · observed shortfall '+(e.currentShortfall95||0).toFixed(2)+' · peak '+(e.peakShortfall95||0).toFixed(2)+' · grandfathered requirements '+(e.sourceRequirements95||[]).join(', '),acts)}
function openReq(r){let f=facility(r.facilityId55),a=authority(r.authorityId),acts=[];for(const x of(S.surchargeRecidivismActions95||[]).filter(x=>x.requirementId95===r.id).slice(-6))acts.push(['open '+x.id,()=>openAction(x)]);acts.push(['close',closePanel]);panel(r.id+' · RECIDIVISM PENALTY',r.status.toUpperCase(),(f?f.id:'missing facility')+' · Build 94 '+r.build94RequirementId+' · strike '+r.breachEpisodeId95+' · extra 50% · required '+(r.required95||0).toFixed(2)+' · held '+(r.held95||0).toFixed(2)+' · shortfall '+(r.shortfall95||0).toFixed(2)+' · authority free capital '+(a?(a.capital||0).toFixed(2):'missing'),acts)}
function openAction(x){panel(x.id+' · RECIDIVISM ACTION',x.kind95.toUpperCase(),x.facilityId55+' · '+(x.amount95||0).toFixed(2)+' · held '+(x.heldBefore95||0).toFixed(2)+'→'+(x.heldAfter95||0).toFixed(2)+' · authority free capital '+(x.capitalAfter95||0).toFixed(2),[['close',closePanel]])}
function openOffice(){if(!ensure())return;let acts=[];for(const e of S.surchargeBreachEpisodes95.slice(-6))acts.push(['open '+e.id+' · '+e.status,()=>openEpisode(e)]);for(const r of S.surchargeRecidivismRequirements95.slice(-8))acts.push(['open '+r.id+' · '+r.status,()=>openReq(r)]);acts.push(['close',closePanel]);panel(S.surchargeRecidivismOffice95.name,'PROGRESSIVE CAPITAL PENALTY · SRB1',S.surchargeBreachEpisodesCreated95+' strikes · '+S.surchargeRecidivismRequirementsCreated95+' penalties · '+S.surchargeRecidivismHeldTotal95.toFixed(2)+' capital held · '+S.surchargeRecidivismShortfallTotal95.toFixed(2)+' shortfall',acts)}
function render95(){if(!ensure())return;let layer=q('#surchargeRecidivismLayer95');if(!layer){layer=document.createElement('div');layer.id='surchargeRecidivismLayer95';document.body.appendChild(layer)}layer.innerHTML='';let o=document.createElement('i');o.className='surchargeRecidivismOffice95';o.dataset.label='REC';o.style.left='50%';o.style.top='90%';o.onclick=openOffice;layer.appendChild(o);for(const e of S.surchargeBreachEpisodes95.slice(-6)){let n=document.createElement('i');n.className='surchargeStrike95 '+e.status;n.dataset.label='X';n.style.left=e.x+'%';n.style.top=e.y+'%';n.onclick=()=>openEpisode(e);layer.appendChild(n)}for(const r of S.surchargeRecidivismRequirements95.slice(-8)){let n=document.createElement('i');n.className='surchargePenalty95 '+r.status;n.dataset.label=r.status==='penalty-shortfall'?'P!':'P';n.style.left=r.x+'%';n.style.top=r.y+'%';n.onclick=()=>openReq(r);layer.appendChild(n)}let line=q('#surchargerecidivismline95');if(!line){line=document.createElement('div');line.id='surchargerecidivismline95';line.className='line';(q('#restorationsurchargeline94')||q('#capitalrestorationline93')||q('#supervisorycapitalline92')||q('#monetaryline')||q('#enforcement')).after(line)}line.textContent='surcharge recidivism: '+S.surchargeBreachEpisodesCreated95+' strikes · '+S.surchargeRecidivismHeldTotal95.toFixed(2)+' held · '+S.surchargeRecidivismShortfallTotal95.toFixed(2)+' shortfall';let ctr=document.querySelector('#app .controls');if(ctr&&!q('#openSurchargeRecidivism95')){let x=document.createElement('button');x.id='openSurchargeRecidivism95';x.textContent='open surcharge recidivism';x.onclick=openOffice;ctr.prepend(x)}}
renderAll=function(){R95();let changed=reconcile();render95();if(changed)save95()};let f=q('#forget');if(f)f.onclick=()=>{for(let i=2;i<=95;i++)localStorage.removeItem('nothing-state-v'+i);location.reload()};setInterval(()=>{reconcile();render95();save95()},2300);ensure();reconcile();renderAll();save95();
})();