(()=>{
const BS=save,BR=renderAll,O17=JSON.parse(localStorage.getItem('nothing-state-v17')||'null')||{},sm=a=>a&&a.length?a[Math.floor(Math.random()*a.length)]:null,flip=s=>s==='prosecution'?'defense':'prosecution',cred=v=>Math.max(.05,Math.min(.99,v));
S.witnesses=O17.witnesses||[];S.witnessSerial=O17.witnessSerial||0;S.crossExams=O17.crossExams||0;S.perjury=O17.perjury||0;S.recantations=O17.recantations||0;S.testimonyContradictions=O17.testimonyContradictions||0;S.protectedWitnesses=O17.protectedWitnesses||0;
S.witnesses=S.witnesses.map((w,i)=>({id:w.id||'X'+(i+1),trialId:w.trialId,evidenceId:w.evidenceId,kind:w.kind||'memory',statement:w.statement||'I remember something.',originalStatement:w.originalStatement||w.statement||'I remember something.',side:w.side||'defense',credibility:Number.isFinite(w.credibility)?w.credibility:.6,examinations:w.examinations||0,status:w.status||'active',protected:!!w.protected,x:Number.isFinite(w.x)?w.x:12+Math.random()*76,y:Number.isFinite(w.y)?w.y:14+Math.random()*66,history:w.history||[]}));
function save17(){BS();localStorage.setItem('nothing-state-v17',JSON.stringify({witnesses:S.witnesses,witnessSerial:S.witnessSerial,crossExams:S.crossExams,perjury:S.perjury,recantations:S.recantations,testimonyContradictions:S.testimonyContradictions,protectedWitnesses:S.protectedWitnesses}))}save=save17;
const LT=()=>S.trials.filter(t=>t.status==='hearing'||t.status==='deliberating'),TB=id=>S.trials.find(t=>t.id===id),EW=w=>{let t=TB(w.trialId);return t&&t.evidence.find(e=>e.id===w.evidenceId)};
function baseCred(e){let s=(e.type||'').toLowerCase();return s.includes('dead')?.42:s.includes('future')?.5:s.includes('other')?.56:s.includes('letter')?.61:(s.includes('memory')||s.includes('place'))?.72:.64}
function summon(t,e){if(!t||!e)return;let x=S.witnesses.find(w=>w.trialId===t.id&&w.evidenceId===e.id&&w.status!=='discharged');if(x)return x;let w={id:'X'+(++S.witnessSerial),trialId:t.id,evidenceId:e.id,kind:e.type,statement:e.text,originalStatement:e.text,side:e.side,credibility:cred(baseCred(e)+(Math.random()-.5)*.12),examinations:0,status:'active',protected:false,x:12+Math.random()*76,y:14+Math.random()*66,history:['sworn for '+t.id]};S.witnesses.push(w);S.witnesses=S.witnesses.slice(-40);t.notes.push(w.id+' sworn from '+e.type);return w}
function seed(t){if(!t||t.status!=='hearing')return;let a=t.evidence.filter(e=>e.type!=='warrant'&&!S.witnesses.some(w=>w.trialId===t.id&&w.evidenceId===e.id));while(S.witnesses.filter(w=>w.trialId===t.id&&w.status!=='discharged').length<2&&a.length)summon(t,a.splice(Math.floor(Math.random()*a.length),1)[0])}
function sync(w,e){if(e){e.text=w.statement;e.side=w.side}}
function cross(w){let t=TB(w.trialId),e=EW(w);if(!t||!e||t.status!=='hearing'||w.protected||w.status==='recanted')return;w.examinations++;S.crossExams++;t.interventions++;let p=Math.random()+w.examinations*.07+(1-w.credibility)*.2;if(p<.36){w.credibility=cred(w.credibility+.08);e.weight=(e.weight||1)+.18;$('#msg').textContent=w.id+' repeated the same story.'}else if(p<.67){w.credibility=cred(w.credibility-.16);e.weight=Math.max(.15,(e.weight||1)-.35);w.statement='Correction: '+w.originalStatement+' — but not exactly as I first said.';S.testimonyContradictions++;R().timelineDrift++;sync(w,e);$('#msg').textContent=w.id+' changed one important detail under oath.'}else if(p<.84){w.status='recanted';w.credibility=.18;e.weight=.18;w.statement='I withdraw this statement.';if(Math.random()<.4)w.side=flip(w.side);S.recantations++;S.testimonyContradictions++;t.verdictAt+=2500;sync(w,e);$('#msg').textContent=w.id+' recanted.'}else{w.status='perjury';w.credibility=.09;w.side=flip(w.side);e.side=w.side;e.weight=Math.max(1.4,(e.weight||1)+.3);w.statement='Under oath: the opposite version is the true one.';S.perjury++;S.testimonyContradictions+=2;R().timelineDrift+=2;R().disputes++;sync(w,e);if(typeof place==='function')place('cold','perjury on the record',R());$('#msg').textContent=w.id+' appears to have lied under oath.'}openW(w);save17();renderW()}
function confront(w){let t=TB(w.trialId),e=EW(w);if(!t||!e||t.status!=='hearing'||w.protected)return;let om=sm(O().memories)||sm(O().places)?.name||'no matching record';S.crossExams++;t.interventions++;if(Math.random()<.48){w.credibility=cred(w.credibility+.13);e.weight=(e.weight||1)+.28;$('#msg').textContent='Reality '+other()+' corroborated '+w.id+'.'}else{w.credibility=cred(w.credibility-.2);e.weight=Math.max(.12,(e.weight||1)-.42);S.testimonyContradictions++;R().timelineDrift++;if(Math.random()<.28){w.side=flip(w.side);w.statement='The other reality says my version belongs to the wrong side.';sync(w,e)}$('#msg').textContent='Reality '+other()+' contradicted '+w.id+'.'}w.history.push(om);openW(w);save17();renderW()}
function protect(w){if(!w||w.protected)return;let e=EW(w);w.protected=true;w.status='protected';w.credibility=cred(w.credibility+.1);if(e)e.weight=(e.weight||1)+.22;S.protectedWitnesses++;w.x=8+Math.random()*20;w.y=70+Math.random()*18;if(typeof place==='function')place('dream','sealed witness address',R());$('#msg').textContent=w.id+' moved to an address that officially does not exist.';save17();renderAll()}
function discharge(){for(let w of S.witnesses){let t=TB(w.trialId);if(t&&!['hearing','deliberating'].includes(t.status)&&!w.protected)w.status='discharged'}}
function openW(w){let t=TB(w.trialId),e=EW(w),b=[];if(t&&t.status==='hearing'&&!w.protected){if(w.status!=='recanted')b.push(['cross-examine',()=>cross(w)]);b.push(['confront with other reality',()=>confront(w)],['protect witness',()=>protect(w)])}b.push(['close',closePanel]);panel(w.id+' · '+(w.protected?'protected witness':'witness'),w.statement,'trial '+w.trialId+' · '+w.kind+' · side '+w.side+' · credibility '+Math.round(w.credibility*100)+'% · examinations '+w.examinations+' · status '+w.status+(e?' · evidence '+(e.weight||1).toFixed(2):''),b)}
function renderW(){let l=$('#witnessLayer');if(!l){l=document.createElement('div');l.id='witnessLayer';document.body.appendChild(l)}l.innerHTML='';for(let w of S.witnesses.slice(-18)){if(!TB(w.trialId))continue;let n=document.createElement('i');n.className='witness '+w.status+(w.protected?' protected':'');n.dataset.label=w.id+' '+w.kind;n.style.left=w.x+'%';n.style.top=w.y+'%';n.onclick=()=>openW(w);l.appendChild(n)}let line=$('#testimonyline');if(!line){line=document.createElement('div');line.id='testimonyline';line.className='line';($('#courtline')||$('#enforcement')).after(line)}line.textContent='testimony: '+S.witnesses.filter(w=>w.status!=='discharged').length+' active · '+S.crossExams+' examinations · '+S.recantations+' recantations · '+S.perjury+' perjury · '+S.protectedWitnesses+' protected';let c=document.querySelector('#app .controls');if(c&&!$('#callWitness')){let b=document.createElement('button');b.id='callWitness';b.textContent='call witness';b.onclick=()=>{let t=[...LT()].reverse().find(t=>t.status==='hearing');if(!t)return $('#msg').textContent='No hearing is accepting testimony.';let e=t.evidence.find(e=>e.type!=='warrant'&&!S.witnesses.some(w=>w.trialId===t.id&&w.evidenceId===e.id)),w=e?summon(t,e):S.witnesses.find(w=>w.trialId===t.id&&w.status!=='discharged');w?openW(w):$('#msg').textContent='Everyone who can testify already has.'};c.prepend(b)}}
renderAll=function(){BR();discharge();for(let t of LT())seed(t);renderW()};let f=$('#forget');if(f)f.onclick=()=>{for(let i=2;i<=17;i++)localStorage.removeItem('nothing-state-v'+i);location.reload()};setInterval(()=>{for(let t of LT())seed(t);let a=S.witnesses.filter(w=>w.status==='active'&&!w.protected&&TB(w.trialId)?.status==='hearing');if(a.length&&Math.random()<.035){let w=sm(a),e=EW(w);w.credibility=cred(w.credibility-.08);e.weight=Math.max(.15,(e.weight||1)-.18);w.statement='Before anyone asked: '+w.statement;S.testimonyContradictions++;R().timelineDrift++;sync(w,e);$('#msg').textContent=w.id+' changed its testimony without being questioned.'}discharge();renderW();save17()},1500);renderAll();save17();
})();
