(()=>{
const BS57=save,BR57=renderAll,O57=JSON.parse(localStorage.getItem('nothing-state-v57')||'null')||{},cl=(v,a,b)=>Math.max(a,Math.min(b,v)),pick=a=>a&&a.length?a[Math.floor(Math.random()*a.length)]:null;
S.tradeAccounts57=O57.tradeAccounts57||[];
S.tradeContracts57=O57.tradeContracts57||[];
S.tradeInvoices57=O57.tradeInvoices57||[];
S.externalDebts57=O57.externalDebts57||[];
S.tradeAccountSerial57=O57.tradeAccountSerial57||0;
S.tradeContractSerial57=O57.tradeContractSerial57||0;
S.tradeInvoiceSerial57=O57.tradeInvoiceSerial57||0;
S.externalDebtSerial57=O57.externalDebtSerial57||0;
S.tradeContractsSigned57=O57.tradeContractsSigned57||0;
S.tradeInvoicesPaid57=O57.tradeInvoicesPaid57||0;
S.tradeInvoicesFinanced57=O57.tradeInvoicesFinanced57||0;
S.tradeDefaults57=O57.tradeDefaults57||0;
S.tradeSuspensions57=O57.tradeSuspensions57||0;
S.tradeReserveDrain57=O57.tradeReserveDrain57||0;
S.tradeReserveInvoices57=O57.tradeReserveInvoices57||0;
S.tradeDebtRollovers57=O57.tradeDebtRollovers57||0;
S.tradeCrises57=O57.tradeCrises57||0;
S.lastTradeCrisis57=O57.lastTradeCrisis57||0;
S.tradeKeys57=O57.tradeKeys57||{};
S.lastTradeTick57=O57.lastTradeTick57||Date.now();
function save57(){BS57();localStorage.setItem('nothing-state-v57',JSON.stringify({tradeAccounts57:S.tradeAccounts57,tradeContracts57:S.tradeContracts57,tradeInvoices57:S.tradeInvoices57,externalDebts57:S.externalDebts57,tradeAccountSerial57:S.tradeAccountSerial57,tradeContractSerial57:S.tradeContractSerial57,tradeInvoiceSerial57:S.tradeInvoiceSerial57,externalDebtSerial57:S.externalDebtSerial57,tradeContractsSigned57:S.tradeContractsSigned57,tradeInvoicesPaid57:S.tradeInvoicesPaid57,tradeInvoicesFinanced57:S.tradeInvoicesFinanced57,tradeDefaults57:S.tradeDefaults57,tradeSuspensions57:S.tradeSuspensions57,tradeReserveDrain57:S.tradeReserveDrain57,tradeReserveInvoices57:S.tradeReserveInvoices57,tradeDebtRollovers57:S.tradeDebtRollovers57,tradeCrises57:S.tradeCrises57,lastTradeCrisis57:S.lastTradeCrisis57,tradeKeys57:S.tradeKeys57,lastTradeTick57:S.lastTradeTick57}))}save=save57;
const realm=id=>S.real[id],fx=()=>S.fxMarkets56?.[0],currency=id=>(S.fxCurrencies56||[]).find(c=>c.reality===id),bank=id=>(S.monetaryAuthorities55||[]).find(a=>a.reality===id),ns=id=>(S.namespaces46||[]).find(n=>n.id===id),treasury=id=>(S.packageTreasuries47||[]).find(t=>t.namespaceId===id),pkg=id=>(S.packages45||[]).find(p=>p.id===id),account=id=>S.tradeAccounts57.find(a=>a.reality===id),contract=id=>S.tradeContracts57.find(c=>c.id===id),invoice=id=>S.tradeInvoices57.find(x=>x.id===id),debt=id=>S.externalDebts57.find(d=>d.id===id);
function trust57(id,status,note){let accepted=S.trustPolicies?.[id]?.acceptedRoots||[],r=[...(S.trustRoots||[])].filter(x=>accepted.includes(x.id)&&x.status==='active').sort((a,b)=>(b.strength||0)-(a.strength||0))[0];S.trustAudits=S.trustAudits||[];S.trustAuditSerial=S.trustAuditSerial||0;S.trustAudits.push({id:'TA'+(++S.trustAuditSerial),reality:id,remediationId:null,credentialId:null,certificateId:null,rootId:r?.id||null,status,created:Date.now(),note,x:10+Math.random()*80,y:12+Math.random()*68})}
function incident57(id,title,severity='SEV2'){S.incidents=S.incidents||[];let ex=S.incidents.find(i=>i.reality===id&&i.title===title&&i.status==='open');if(ex)return ex;S.incidentSerial=S.incidentSerial||0;let x={id:'INC'+(++S.incidentSerial),reality:id,title,severity,status:'open',alertIds:[],started:Date.now(),acknowledged:null,resolved:null,postmortem:null,owner:'interreality external accounts',x:10+Math.random()*80,y:12+Math.random()*68};S.incidents.push(x);return x}
function ensureAccounts(){for(const id of ['A','B'])if(!account(id))S.tradeAccounts57.push({id:'BOP'+(++S.tradeAccountSerial57),reality:id,exports:0,imports:0,currentAccount:0,externalDebt:0,arrears:0,reserveDrain:0,tradeCredits:0,defaults:0,compression:false,created:Date.now(),x:id==='A'?29:71,y:20})}
function rate(){return Math.max(.05,fx()?.rate||1)}
function domesticCode(id){return'R'+id}
function otherReality(id){return id==='A'?'B':'A'}
function foreignCode(id){return'R'+otherReality(id)}
function toDomestic(id,code,amount){let r=rate();if(code===domesticCode(id))return amount;if(id==='A'&&code==='RB')return amount/r;if(id==='B'&&code==='RA')return amount*r;return amount}
function toRA(code,amount){let r=rate();return code==='RA'?amount:amount/r}
function liveUsers(n){let ids=new Set();for(const sb of (S.sboms45||[]).filter(s=>s.reality===n.reality&&s.status==='current'))if((sb.components||[]).some(pid=>pkg(pid)?.name===n.name))ids.add(sb.artifactId);return ids.size}
function reverseDeps(n){return new Set((S.packages45||[]).filter(p=>p.reality===n.reality&&p.status!=='yanked'&&(p.dependencies||[]).includes(n.name)).map(p=>p.name)).size}
function criticality(n){return liveUsers(n)*2+reverseDeps(n)*1.2+((S.advisories45||[]).some(a=>a.reality===n.reality&&a.name===n.name&&['high','critical'].includes(a.severity)&&a.status!=='withdrawn')?2:0)}
function topExportNamespace(id){let xs=(S.namespaces46||[]).filter(n=>n.reality===id&&n.status!=='abandoned');xs.sort((a,b)=>criticality(b)-criticality(a));return xs[0]||null}
function refreshAccounts(){ensureAccounts();for(const a of S.tradeAccounts57){a.currentAccount=a.exports-a.imports;a.externalDebt=S.externalDebts57.filter(d=>d.debtorReality===a.reality&&['active','arrears'].includes(d.status)).reduce((n,d)=>n+toDomestic(a.reality,d.currency,(d.principal||0)+(d.accrued||0)),0);a.arrears=S.tradeInvoices57.filter(i=>i.importerReality===a.reality&&['arrears','default'].includes(i.status)).reduce((n,i)=>n+toDomestic(a.reality,i.currency,Math.max(0,i.amount-(i.paid||0))),0)}}
function reconcileContractArrears(c){if(!c)return;c.arrears=S.tradeInvoices57.filter(i=>i.contractId===c.id&&i.status==='arrears').reduce((n,i)=>n+Math.max(0,i.amount-(i.paid||0)),0)}
function tradeCrisis(id,kind,severity='SEV2'){let now=Date.now(),key=id+'|'+kind;if(S.tradeKeys57[key]&&now-S.tradeKeys57[key]<14000)return;S.tradeKeys57[key]=now;S.tradeCrises57++;S.lastTradeCrisis57=now;remember('BALANCE-OF-PAYMENTS CRISIS: '+kind+' made external settlement a constraint on software reality',realm(id));if(typeof place==='function'){place('cold','solvent in domestic money bankrupt in invoice currency',realm(id));place('dream','package updates waiting at the border of the balance sheet',realm(id))}let b=$('#bailiff');if(b)b.textContent='asking why a reality that can print money cannot pay its software supplier';incident57(id,'interreality balance-of-payments crisis: '+kind,severity)}
function makeContract(importer,manual=true){ensureAccounts();let exporter=otherReality(importer),n=topExportNamespace(exporter);if(!n){if(manual)$('#msg').textContent='No exportable package namespace exists.';return null}let m=fx(),reserve=m?.reserveCurrency?'R'+m.reserveCurrency:null,invoiceCurrency=domesticCode(exporter),base=1.6+criticality(n)*.36,price=Math.round(base*10)/10,c={id:'TRD'+(++S.tradeContractSerial57),exporterReality:exporter,importerReality:importer,namespaceId:n.id,packageName:n.name,status:'active',invoiceCurrency,price,frequency:11000,nextInvoice:Date.now()+1500,lastInvoice:null,arrears:0,criticality:criticality(n),reserveCandidate:reserve,created:Date.now(),x:10+Math.random()*80,y:12+Math.random()*68};S.tradeContracts57.push(c);S.tradeContractsSigned57++;remember('SOFTWARE TRADE '+c.id+': Reality '+importer+' contracted for '+n.name+' support from Reality '+exporter+' invoiced in '+invoiceCurrency,realm(importer));remember('SOFTWARE EXPORT '+c.id+': '+n.name+' became an external service sold to Reality '+importer,realm(exporter));trust57(importer,'interreality-software-import-contract',c.id+' '+n.name+' '+invoiceCurrency);if(typeof place==='function')place('warm','package support contract crossing the rift',realm(importer));issueInvoice(c,false);if(manual){$('#msg').textContent=c.id+' imports '+n.name+' support from Reality '+exporter+' in '+invoiceCurrency+'.';renderAll();save57();openContract(c)}return c}
function issueInvoice(c,manual=true){if(!c||c.status!=='active')return null;let i={id:'INV'+(++S.tradeInvoiceSerial57),contractId:c.id,exporterReality:c.exporterReality,importerReality:c.importerReality,namespaceId:c.namespaceId,currency:c.invoiceCurrency,amount:c.price,paid:0,status:'due',issued:Date.now(),due:Date.now()+17000,fxAtIssue:rate(),x:10+Math.random()*80,y:12+Math.random()*68};S.tradeInvoices57.push(i);c.lastInvoice=i.id;c.nextInvoice=Date.now()+c.frequency;remember('EXTERNAL INVOICE '+i.id+': Reality '+c.importerReality+' owes '+i.amount.toFixed(1)+' '+i.currency+' for '+c.packageName+' support',realm(c.importerReality));if(manual){renderAll();save57();openInvoice(i)}return i}
function creditExporter(i,foreignAmount){let c=contract(i.contractId),t=treasury(c?.namespaceId),exp=i.exporterReality,dom=toDomestic(exp,i.currency,foreignAmount);if(t)t.balance=(t.balance||0)+dom;let a=account(exp);a.exports+=dom;return dom}
function debitImporter(i,foreignAmount){let a=account(i.importerReality),dom=toDomestic(i.importerReality,i.currency,foreignAmount);a.imports+=dom;return dom}
function payInvoice(i,manual=true){if(!i||!['due','arrears'].includes(i.status))return false;let c=contract(i.contractId),imp=i.importerReality,exp=i.exporterReality,need=Math.max(0,i.amount-(i.paid||0)),ic=currency(imp),domestic=domesticCode(imp),paid=0;if(i.currency===domestic){paid=need;let ec=currency(exp);if(ec&&i.currency===ec.foreignReserveCode)ec.foreignReserves+=paid}else if(ic&&i.currency===ic.foreignReserveCode){paid=Math.min(need,ic.foreignReserves);ic.foreignReserves-=paid;ic.reserveDrain=(ic.reserveDrain||0)+paid;S.tradeReserveDrain57+=paid;account(imp).reserveDrain+=paid}else{let m=fx(),reserve=m?.reserveCurrency?'R'+m.reserveCurrency:null;if(reserve&&i.currency===reserve&&i.currency!==domestic){paid=Math.min(need,ic?.foreignReserves||0);if(ic){ic.foreignReserves-=paid;account(imp).reserveDrain+=paid;S.tradeReserveDrain57+=paid}}}
if(paid>0){i.paid+=paid;creditExporter(i,paid);debitImporter(i,paid)}if(i.paid+1e-9>=i.amount){i.status='paid';i.paidAt=Date.now();S.tradeInvoicesPaid57++;reconcileContractArrears(c);if(c&&c.status==='suspended')resumeContract(c,'invoice paid');remember('TRADE PAYMENT '+i.id+': Reality '+imp+' paid '+i.amount.toFixed(1)+' '+i.currency+' for '+c?.packageName,realm(imp));if(typeof place==='function')place('warm','foreign reserves became package maintenance revenue',realm(imp));if(manual)$('#msg').textContent=i.id+' paid in full.';refreshAccounts();return true}
i.status='arrears';i.arrearsAt=i.arrearsAt||Date.now();reconcileContractArrears(c);remember('EXTERNAL ARREARS '+i.id+': Reality '+imp+' could pay only '+paid.toFixed(1)+' of '+need.toFixed(1)+' '+i.currency,realm(imp));if(manual)$('#msg').textContent=i.id+' is in arrears; foreign reserves were insufficient.';refreshAccounts();if((ic?.foreignReserves||0)<2.5)tradeCrisis(imp,'foreign reserves insufficient for software imports','SEV1');return false}
function financeInvoice(i,manual=true){if(!i||!['due','arrears'].includes(i.status))return null;let remaining=Math.max(0,i.amount-(i.paid||0));if(remaining<=.01)return null;let c=contract(i.contractId),d={id:'EXTD'+(++S.externalDebtSerial57),contractId:i.contractId,invoiceId:i.id,debtorReality:i.importerReality,creditorReality:i.exporterReality,currency:i.currency,principal:remaining,accrued:0,rate:.085,status:'active',misses:0,issued:Date.now(),nextService:Date.now()+15000,lastAccrual:Date.now(),fxAtIssue:rate(),x:10+Math.random()*80,y:12+Math.random()*68};S.externalDebts57.push(d);i.status='financed';i.financedBy=d.id;reconcileContractArrears(c);S.tradeInvoicesFinanced57++;account(i.importerReality).tradeCredits+=toDomestic(i.importerReality,i.currency,remaining);remember('SUPPLIER CREDIT '+d.id+': Reality '+i.importerReality+' financed '+remaining.toFixed(1)+' '+i.currency+' of '+c?.packageName+' imports instead of paying reserves now',realm(i.importerReality));if(typeof place==='function')place('dream','software import converted into foreign-currency debt',realm(i.importerReality));trust57(i.importerReality,'interreality-supplier-credit',d.id+' '+remaining.toFixed(1)+' '+i.currency);refreshAccounts();if(manual){$('#msg').textContent=d.id+' financed '+remaining.toFixed(1)+' '+i.currency+' of unpaid imports.';renderAll();save57();openDebt(d)}return d}
function serviceDebt(d,manual=true){if(!d||!['active','arrears'].includes(d.status))return false;let c=contract(d.contractId),imp=d.debtorReality,ic=currency(imp),domestic=domesticCode(imp),due=Math.min(d.principal,d.principal*.18)+d.accrued,paid=0;if(d.currency===domestic)paid=due;else if(ic&&d.currency===ic.foreignReserveCode){paid=Math.min(due,ic.foreignReserves);ic.foreignReserves-=paid;account(imp).reserveDrain+=paid;S.tradeReserveDrain57+=paid}else{paid=Math.min(due,ic?.foreignReserves||0);if(ic){ic.foreignReserves-=paid;account(imp).reserveDrain+=paid;S.tradeReserveDrain57+=paid}}
let interestPaid=Math.min(d.accrued,paid);d.accrued-=interestPaid;let principalPaid=Math.min(d.principal,Math.max(0,paid-interestPaid));d.principal-=principalPaid;if(paid>0&&c){let fake={exporterReality:d.creditorReality,importerReality:d.debtorReality,currency:d.currency,contractId:d.contractId,namespaceId:c.namespaceId};creditExporter(fake,paid);debitImporter(fake,paid)}if(paid+1e-9>=due){d.status=d.principal<=.01?'repaid':'active';d.misses=0;d.nextService=Date.now()+15000;if(d.status==='repaid')d.repaid=Date.now();remember('EXTERNAL DEBT SERVICE '+d.id+': Reality '+imp+' paid '+paid.toFixed(1)+' '+d.currency,realm(imp));if(manual)$('#msg').textContent=d.id+' debt service paid.';refreshAccounts();return true}d.status='arrears';d.misses++;d.nextService=Date.now()+10000;remember('EXTERNAL DEBT ARREARS '+d.id+': Reality '+imp+' paid '+paid.toFixed(1)+' of '+due.toFixed(1)+' '+d.currency,realm(imp));if(d.misses>=2)defaultDebt(d);else if((ic?.foreignReserves||0)<2)tradeCrisis(imp,'external debt service draining scarce reserves','SEV1');if(manual)$('#msg').textContent=d.id+' missed foreign-currency debt service.';refreshAccounts();return false}
function defaultDebt(d){if(!d||d.status==='default')return;d.status='default';d.defaulted=Date.now();S.tradeDefaults57++;let a=account(d.debtorReality);a.defaults++;let c=contract(d.contractId);if(c)suspendContract(c,'foreign-currency debt default');remember('EXTERNAL DEFAULT '+d.id+': Reality '+d.debtorReality+' defaulted on '+(d.principal+d.accrued).toFixed(1)+' '+d.currency+' owed for software imports',realm(d.debtorReality));if(typeof place==='function'){place('cold','domestic printing press unable to print foreign debt service',realm(d.debtorReality));place('dream','dependency contract defaulted while deployed code kept running',realm(d.debtorReality))}tradeCrisis(d.debtorReality,'foreign-currency software debt default','SEV1')}
function rolloverDebt(d){if(!d||!['active','arrears'].includes(d.status))return;d.rate=cl(d.rate+.035,.03,.35);d.misses=0;d.status='active';d.nextService=Date.now()+18000;d.rolled=(d.rolled||0)+1;S.tradeDebtRollovers57++;remember('EXTERNAL DEBT ROLLOVER '+d.id+': maturity extended at '+(d.rate*100).toFixed(1)+'% because immediate repayment would interrupt '+contract(d.contractId)?.packageName+' support',realm(d.debtorReality));if(typeof place==='function')place('dream','temporary trade credit that keeps refinancing itself',realm(d.debtorReality));if(d.rolled>=2)tradeCrisis(d.debtorReality,'repeated external debt rollover');renderAll();save57();openDebt(d)}
function domesticDebtBurden(d){return toDomestic(d.debtorReality,d.currency,(d.principal||0)+(d.accrued||0))}
function suspendContract(c,reason){if(!c||c.status==='suspended')return;c.status='suspended';c.suspendedAt=Date.now();c.suspensionReason=reason;S.tradeSuspensions57++;let local=(S.namespaces46||[]).find(n=>n.reality===c.importerReality&&n.name===c.packageName);if(local){local.externalSupport57='suspended';for(const m of (S.maintainers46||[]).filter(m=>m.namespaceId===local.id&&m.status==='active'))m.fatigue=cl((m.fatigue||0)+.08,0,1)}remember('IMPORT SUSPENDED '+c.id+': '+c.packageName+' support stopped after '+reason+' while existing binaries remained deployed',realm(c.importerReality));if(typeof place==='function'){place('cold','package updates stopped at the balance-of-payments border',realm(c.importerReality));place('dream','existing binary outlived its foreign support contract',realm(c.importerReality))}let vul=(S.advisories45||[]).some(a=>a.reality===c.importerReality&&a.name===c.packageName&&['high','critical'].includes(a.severity)&&a.status!=='withdrawn');if(vul)incident57(c.importerReality,'foreign support suspended for vulnerable package: '+c.packageName,'SEV1')}
function resumeContract(c,why='arrears cured'){if(!c||c.status!=='suspended')return;c.status='active';c.suspensionReason=null;c.nextInvoice=Date.now()+c.frequency;let local=(S.namespaces46||[]).find(n=>n.reality===c.importerReality&&n.name===c.packageName);if(local)local.externalSupport57='active';remember('IMPORT RESUMED '+c.id+': '+c.packageName+' support resumed after '+why,realm(c.importerReality));if(typeof place==='function')place('warm','foreign package support resumed after payment',realm(c.importerReality))}
function compressImports(id){let a=account(id);a.compression=!a.compression;let cs=S.tradeContracts57.filter(c=>c.importerReality===id&&c.status==='active').sort((x,y)=>x.criticality-y.criticality);if(a.compression&&cs.length){let c=cs[0];suspendContract(c,'balance-of-payments import compression');remember('IMPORT COMPRESSION: Reality '+id+' suspended lower-priority software imports to preserve foreign reserves',realm(id));if(typeof place==='function')place('cold','dependency austerity imposed by foreign-reserve shortage',realm(id))}else if(!a.compression){for(const c of S.tradeContracts57.filter(c=>c.importerReality===id&&c.status==='suspended'&&c.suspensionReason==='balance-of-payments import compression'))resumeContract(c,'capital account reopened')}renderAll();save57();openExternal(id)}
function invoiceInReserveCurrency(c,manual=true){let rc=fx()?.reserveCurrency;if(!c||!rc){if(manual)$('#msg').textContent='No interreality reserve currency is dominant yet.';return}c.invoiceCurrency='R'+rc;S.tradeReserveInvoices57++;remember('RESERVE-CURRENCY INVOICING '+c.id+': '+c.packageName+' invoices switched to R'+rc,realm(c.importerReality));if(typeof place==='function')place('warm','reserve currency became the language of software trade',realm(c.importerReality));trust57(c.importerReality,'interreality-reserve-currency-invoicing',c.id+' R'+rc);if(manual){renderAll();save57();openContract(c)}}
function invoiceInBuyerCurrency(c){if(!c)return;c.invoiceCurrency=domesticCode(c.importerReality);remember('BUYER-CURRENCY INVOICING '+c.id+': exporter accepted '+c.invoiceCurrency+' and took the exchange-rate risk',realm(c.importerReality));if(typeof place==='function')place('dream','software seller accepting the buyer\'s printing press',realm(c.importerReality));renderAll();save57();openContract(c)}
function accrue(){let now=Date.now();for(const d of S.externalDebts57.filter(d=>['active','arrears'].includes(d.status))){let dt=Math.max(0,now-(d.lastAccrual||now));d.accrued+=(d.principal*d.rate)*(dt/60000)/20;d.lastAccrual=now;if(now>=d.nextService)serviceDebt(d,false)}for(const c of S.tradeContracts57.filter(c=>c.status==='active'))if(now>=c.nextInvoice&&!account(c.importerReality)?.compression)issueInvoice(c,false);for(const i of S.tradeInvoices57.filter(i=>i.status==='due'&&now>=i.due)){if(!payInvoice(i,false)){let c=contract(i.contractId);if(c&&Date.now()-i.due>9000)suspendContract(c,'unpaid external invoice '+i.id)}}refreshAccounts();for(const id of ['A','B']){let a=account(id),cur=currency(id);if(a.currentAccount<-10&&(cur?.foreignReserves||0)<4)tradeCrisis(id,'persistent current-account deficit exhausted reserves','SEV1');let foreignDebt=S.externalDebts57.filter(d=>d.debtorReality===id&&['active','arrears'].includes(d.status)&&d.currency!==domesticCode(id)).reduce((n,d)=>n+domesticDebtBurden(d),0);if(foreignDebt>Math.max(8,(cur?.foreignReserves||0)*4))tradeCrisis(id,'foreign-currency debt exceeded reserve capacity','SEV1')}}
function openInvoice(i){let c=contract(i.contractId),acts=[];if(['due','arrears'].includes(i.status))acts.push(['pay from reserves',()=>{payInvoice(i,true);renderAll();save57();openInvoice(i)}],['finance with supplier credit',()=>financeInvoice(i,true)]);acts.push(['open contract',()=>openContract(c)],['close',closePanel]);panel(i.id+' · '+i.status.toUpperCase(),c?.packageName+' · '+i.amount.toFixed(1)+' '+i.currency,'paid '+(i.paid||0).toFixed(1)+' · issued FX '+i.fxAtIssue.toFixed(3)+' · due '+new Date(i.due).toLocaleTimeString(),acts)}
function openDebt(d){let c=contract(d.contractId),acts=[];if(['active','arrears'].includes(d.status))acts.push(['service foreign debt',()=>{serviceDebt(d,true);renderAll();save57();openDebt(d)}],['roll over debt',()=>rolloverDebt(d)]);acts.push(['open contract',()=>openContract(c)],['close',closePanel]);panel(d.id+' · '+d.status.toUpperCase(),c?.packageName+' supplier credit',(d.principal+d.accrued).toFixed(1)+' '+d.currency+' outstanding · domestic burden '+domesticDebtBurden(d).toFixed(1)+' '+domesticCode(d.debtorReality)+' · rate '+(d.rate*100).toFixed(1)+'% · FX at issue '+d.fxAtIssue.toFixed(3)+' · misses '+d.misses,acts)}
function openContract(c){let acts=[];if(c.status==='active')acts.push(['issue invoice now',()=>issueInvoice(c,true)]);if(c.status==='suspended')acts.push(['resume support anyway',()=>{resumeContract(c,'policy override');renderAll();save57();openContract(c)}]);if(fx()?.reserveCurrency)acts.push(['invoice in reserve currency',()=>invoiceInReserveCurrency(c)]);acts.push(['invoice in buyer currency',()=>invoiceInBuyerCurrency(c)]);for(const i of S.tradeInvoices57.filter(i=>i.contractId===c.id).slice(-3))acts.push(['open '+i.id+' · '+i.status,()=>openInvoice(i)]);for(const d of S.externalDebts57.filter(d=>d.contractId===c.id).slice(-2))acts.push(['open '+d.id+' · '+d.status,()=>openDebt(d)]);acts.push(['close',closePanel]);panel(c.id+' · '+c.packageName,c.status.toUpperCase()+' · Reality '+c.exporterReality+' → '+c.importerReality,'invoice '+c.price.toFixed(1)+' '+c.invoiceCurrency+' · criticality '+c.criticality.toFixed(1)+' · arrears '+(c.arrears||0).toFixed(1)+(c.suspensionReason?' · '+c.suspensionReason:''),acts)}
function openExternal(id=S.active){ensureAccounts();refreshAccounts();let a=account(id),cur=currency(id),cs=S.tradeContracts57.filter(c=>c.importerReality===id),ds=S.externalDebts57.filter(d=>d.debtorReality===id&&['active','arrears','default'].includes(d.status)),acts=[['import critical package support',()=>makeContract(id,true)],[a.compression?'end import compression':'compress imports',()=>compressImports(id)]];for(const c of cs.slice(-5))acts.push(['open '+c.id+' '+c.packageName,()=>openContract(c)]);for(const d of ds.slice(-4))acts.push(['open '+d.id+' '+d.status,()=>openDebt(d)]);acts.push(['close',closePanel]);panel('EXTERNAL ACCOUNTS · Reality '+id,'current account '+a.currentAccount.toFixed(1)+' '+domesticCode(id)+' · reserves '+(cur?.foreignReserves||0).toFixed(1)+' '+foreignCode(id),'exports '+a.exports.toFixed(1)+' · imports '+a.imports.toFixed(1)+' · external debt '+a.externalDebt.toFixed(1)+' · arrears '+a.arrears.toFixed(1)+' · reserve drain '+a.reserveDrain.toFixed(1)+' · '+(a.compression?'IMPORT COMPRESSION':'open trade'),acts)}
function stressExternal(id=S.active){let c=makeContract(id,false);if(!c)return;c.price=Math.max(c.price,7.5);for(let k=0;k<3;k++){let i=issueInvoice(c,false);if(i)payInvoice(i,false)}let i=issueInvoice(c,false);if(i&&!payInvoice(i,false))financeInvoice(i,false);let cur=currency(id);if(cur)cur.foreignReserves=Math.min(cur.foreignReserves,1.5);refreshAccounts();tradeCrisis(id,'stress test concentrated software imports in foreign currency','SEV1');renderAll();save57();openExternal(id)}
function autonomous(){ensureAccounts();let now=Date.now();if(now-S.lastTradeTick57<1800)return;S.lastTradeTick57=now;accrue();if(Math.random()<.0014){let id=pick(['A','B']);if(S.tradeContracts57.filter(c=>c.importerReality===id&&c.status==='active').length<3)makeContract(id,false)}if(Math.random()<.001){let c=pick(S.tradeContracts57.filter(c=>c.status==='active'));if(c&&fx()?.reserveCurrency)invoiceInReserveCurrency(c,false)}}
function renderTrade(){ensureAccounts();refreshAccounts();let layer=$('#tradeLayer');if(!layer){layer=document.createElement('div');layer.id='tradeLayer';document.body.appendChild(layer)}layer.innerHTML='';for(const a of S.tradeAccounts57){let e=document.createElement('i');e.className='tradeAccount'+(a.currentAccount<0?' deficit':' surplus')+(a.compression?' compressed':'');e.dataset.label='BOP'+a.reality;e.style.left=a.x+'%';e.style.top=a.y+'%';e.onclick=()=>openExternal(a.reality);layer.appendChild(e)}for(const c of S.tradeContracts57.filter(c=>['active','suspended'].includes(c.status)).slice(-12)){let e=document.createElement('i');e.className='tradeContract '+c.status;e.dataset.label=c.packageName.slice(0,3);e.style.left=c.x+'%';e.style.top=c.y+'%';e.onclick=()=>openContract(c);layer.appendChild(e)}for(const i of S.tradeInvoices57.filter(i=>['due','arrears','default'].includes(i.status)).slice(-10)){let e=document.createElement('i');e.className='tradeInvoice '+i.status;e.dataset.label=i.currency;e.style.left=i.x+'%';e.style.top=i.y+'%';e.onclick=()=>openInvoice(i);layer.appendChild(e)}for(const d of S.externalDebts57.filter(d=>['active','arrears','default'].includes(d.status)).slice(-10)){let e=document.createElement('i');e.className='externalDebt '+d.status;e.dataset.label='FX$';e.style.left=d.x+'%';e.style.top=d.y+'%';e.onclick=()=>openDebt(d);layer.appendChild(e)}let line=$('#tradeline');if(!line){line=document.createElement('div');line.id='tradeline';line.className='line';($('#fxline')||$('#monetaryline')||$('#clearingline')||$('#enforcement')).after(line)}let a=account(S.active),cur=currency(S.active);line.textContent='external accounts: CA '+a.currentAccount.toFixed(1)+' '+domesticCode(S.active)+' · reserves '+(cur?.foreignReserves||0).toFixed(1)+' '+foreignCode(S.active)+' · debt '+a.externalDebt.toFixed(1)+' · arrears '+a.arrears.toFixed(1)+' · '+S.tradeDefaults57+' defaults · '+S.tradeCrises57+' crises';let ctr=document.querySelector('#app .controls');if(ctr&&!$('#openExternalButton')){let x=document.createElement('button');x.id='openExternalButton';x.textContent='open external accounts';x.onclick=()=>openExternal(S.active);ctr.prepend(x)}if(ctr&&!$('#importPackageButton')){let x=document.createElement('button');x.id='importPackageButton';x.textContent='import critical package support';x.onclick=()=>makeContract(S.active,true);ctr.prepend(x)}if(ctr&&!$('#stressExternalButton')){let x=document.createElement('button');x.id='stressExternalButton';x.textContent='stress external payments';x.onclick=()=>stressExternal(S.active);ctr.prepend(x)}}
renderAll=function(){BR57();renderTrade()};let f=$('#forget');if(f)f.onclick=()=>{for(let i=2;i<=57;i++)localStorage.removeItem('nothing-state-v'+i);location.reload()};
setInterval(()=>{autonomous();renderTrade();save57()},2200);ensureAccounts();refreshAccounts();renderAll();save57();
})();
