(()=>{
const BS=save,BR18=renderAll,O18=JSON.parse(localStorage.getItem('nothing-state-v18')||'null')||{},sm=a=>a&&a.length?a[Math.floor(Math.random()*a.length)]:null;
S.transcripts=O18.transcripts||[];S.transcriptSerial=O18.transcriptSerial||0;S.certifiedTranscripts=O18.certifiedTranscripts||0;S.transcriptCorrections=O18.transcriptCorrections||0;S.phantomEntries=O18.phantomEntries||0;S.recordDivergence=O18.recordDivergence||0;S.reporterMood=O18.reporterMood||'taking notes';
S.transcripts=S.transcripts.map((r,i)=>({id:r.id||'R'+(i+1),trialId:r.trialId,status:r.status||'draft',created:r.created||Date.now(),certifiedAt:r.certifiedAt||0,entries:(r.entries||[]).map((e,j)=>({id:e.id||'L'+j,type:e.type||'note',sourceId:e.sourceId||null,speaker:e.speaker||'record',text:e.text||'',originalText:e.originalText||e.text||'',authority:Number.isFinite(e.authority)?e.authority:.5,phantom:!!e.phantom,certified:!!e.certified,applied:!!e.applied,created:e.created||Date.now()})),corrections:r.corrections||0,x:Number.isFinite(r.x)?r.x:12+Math.random()*76,y:Number.isFinite(r.y)?r.y:14+Math.random()*66,lastCapture:r.lastCapture||0}));
function save18(){BS();localStorage.setItem('nothing-state-v18',JSON.stringify({transcripts:S.transcripts,transcriptSerial:S.transcriptSerial,certifiedTranscripts:S.certifiedTranscripts,transcriptCorrections:S.transcriptCorrections,phantomEntries:S.phantomEntries,recordDivergence:S.recordDivergence,reporterMood:S.reporterMood}))}save=save18;
const TR=id=>S.transcripts.find(r=>r.trialId===id),T=id=>S.trials.find(t=>t.id===id),W=id=>S.witnesses.find(w=>w.id===id);
function entry(r,type,sourceId,speaker,text,authority=.5,phantom=false){if(!text)return null;let key=type+'|'+sourceId+'|'+text;if(r.entries.some(e=>e.key===key||((e.type+'|'+e.sourceId+'|'+e.text)===key)))return null;let e={id:'L'+Date.now().toString(36)+Math.random().toString(36).slice(2,4),type,sourceId:sourceId||null,speaker:speaker||'record',text,originalText:text,authority,phantom,certified:false,applied:false,created:Date.now()};e.key=key;r.entries.push(e);r.entries=r.entries.slice(-32);return e}
function ensure(t){if(!t)return null;let r=TR(t.id);if(!r){r={id:'R'+(++S.transcriptSerial),trialId:t.id,status:'draft',created:Date.now(),certifiedAt:0,entries:[],corrections:0,x:12+Math.random()*76,y:14+Math.random()*66,lastCapture:0};S.transcripts.push(r);S.transcripts=S.transcripts.slice(-28);entry(r,'caption',t.id,'clerk','Proceedings opened in '+t.id+'.',.55)}capture(r,t);return r}
function capture(r,t){if(!r||!t)return;for(const n of t.notes||[])entry(r,'note',t.id,'court',n,.55);for(const e of t.evidence||[])entry(r,'evidence',e.id,e.type,e.text,.6+(e.weight||1)*.05);for(const w of S.witnesses.filter(w=>w.trialId===t.id&&w.status!=='discharged'))entry(r,'witness',w.id,w.id,w.statement,.55+w.credibility*.35);if(t.verdict)entry(r,'verdict',t.id,'jury','Verdict entered: '+t.verdict+'.',.9);r.lastCapture=Date.now()}
function apply(e){if(e.applied)return;e.applied=true;const w=e.type==='witness'&&e.sourceId?W(e.sourceId):null;if(w){if(w.statement!==e.text){w.history=w.history||[];w.history.push('transcript replaced testimony');w.statement=e.text;w.credibility=Math.min(.99,(w.credibility||.5)+.05);let t=T(w.trialId),ev=t&&t.evidence.find(x=>x.id===w.evidenceId);if(ev)ev.text=e.text;S.recordDivergence++}}
for(const r of[S.real.A,S.real.B]){remember('CERTIFIED TRANSCRIPT: '+e.text,r);if(e.phantom){r.timelineDrift+=2;r.disputes++;}}
if(e.phantom&&typeof place==='function'){place('dream','official event nobody remembers',S.real.A);place('dream','official event nobody remembers',S.real.B)}
if(/original/i.test(e.text)){if(/echo|smaller/i.test(e.text)){S.real.A.echoClaim+=5;S.real.B.echoClaim+=5}else{S.real.A.thingClaim+=5;S.real.B.thingClaim+=5}}
if(/tomorrow|future|shall|will /i.test(e.text)&&typeof future==='function'){for(const r of[S.real.A,S.real.B]){let f=future(undefined,r);if(f){f.text='according to the transcript: '+e.text;f.prob=Math.max(f.prob,.82);f.dueAt=Date.now()+7000}}}}
function certify(r){if(!r||r.status==='certified')return;let t=T(r.trialId);capture(r,t);r.status='certified';r.certifiedAt=Date.now();S.certifiedTranscripts++;S.reporterMood='certifying the record';for(const e of r.entries){e.certified=true;e.authority=Math.max(e.authority,.78);apply(e)}for(const rr of[S.real.A,S.real.B])remember('OFFICIAL TRANSCRIPT '+r.id+' certified',rr);$('#msg').textContent=r.id+' was certified. The record is now correcting reality.';renderRecord();save18()}
function correction(r){if(!r||!r.entries.length)return;let candidates=r.entries.filter(e=>e.type==='witness'&&e.sourceId&&W(e.sourceId)&&W(e.sourceId).statement!==e.text),e=sm(candidates)||sm(r.entries.filter(e=>!e.phantom));if(!e)return;let proposed=e.sourceId&&W(e.sourceId)?W(e.sourceId).statement:e.originalText;S.transcriptCorrections++;r.corrections++;if(Math.random()<.46){e.text=proposed;e.authority=Math.max(.35,e.authority-.08);e.applied=false;if(r.status==='certified')apply(e);$('#msg').textContent='Correction accepted. The official wording changed.'}else{e.authority=Math.min(.99,e.authority+.08);S.recordDivergence++;$('#msg').textContent='Correction denied. The disputed wording became more authoritative.'}openRecord(r);save18()}
function phantom(r){if(!r||r.entries.some(e=>e.phantom&&Date.now()-e.created<12000))return;let lines=['The witness answered a question nobody asked.','The jury was unanimous before deliberation began.','The original admitted it remembered being the echo.','The archive was present even though the door was closed.','A verdict was read before the evidence arrived.'];let e=entry(r,'phantom',null,'court reporter',sm(lines),.74,true);if(e){S.phantomEntries++;S.recordDivergence+=2;S.reporterMood='recording things nobody said';if(r.status==='certified'){e.certified=true;apply(e)}$('#msg').textContent='The transcript gained a line nobody remembers saying.'}}
function openRecord(r){if(!r)return;let t=T(r.trialId);capture(r,t);let text=r.entries.map(e=>(e.phantom?'[?] ':'')+(e.certified?'[CERTIFIED] ':'')+e.speaker+': '+e.text).join('\n')||'No proceedings were recorded.';let b=[];if(r.status!=='certified')b.push(['certify transcript',()=>{certify(r);closePanel()}]);b.push(['file correction',()=>correction(r)],['close',closePanel]);panel(r.id+' · transcript of '+r.trialId,text,'status '+r.status+' · entries '+r.entries.length+' · corrections '+r.corrections+' · record authority '+Math.round((r.entries.reduce((a,e)=>a+e.authority,0)/Math.max(1,r.entries.length))*100)+'%',b)}
function renderRecord(){let l=$('#recordLayer');if(!l){l=document.createElement('div');l.id='recordLayer';document.body.appendChild(l)}l.innerHTML='';for(const r of S.transcripts.slice(-14)){let n=document.createElement('i');n.className='record '+r.status+(r.entries.some(e=>e.phantom)?' phantom':'');n.dataset.label=r.id+' '+r.status;n.style.left=r.x+'%';n.style.top=r.y+'%';n.onclick=()=>openRecord(r);l.appendChild(n)}let line=$('#recordline');if(!line){line=document.createElement('div');line.id='recordline';line.className='line';($('#testimonyline')||$('#courtline')||$('#enforcement')).after(line)}line.textContent='record: '+S.transcripts.length+' transcripts · '+S.certifiedTranscripts+' certified · '+S.transcriptCorrections+' corrections · '+S.phantomEntries+' phantom lines · divergence '+S.recordDivergence;let c=document.querySelector('#app .controls');if(c&&!$('#recordButton')){let b=document.createElement('button');b.id='recordButton';b.textContent='open transcript';b.onclick=()=>{let t=[...S.trials].reverse().find(t=>['hearing','deliberating'].includes(t.status))||S.trials.at(-1);if(!t)return $('#msg').textContent='There are no proceedings to transcribe.';openRecord(ensure(t))};c.prepend(b)}}
renderAll=function(){BR18();for(const t of S.trials)ensure(t);renderRecord()};let f=$('#forget');if(f)f.onclick=()=>{for(let i=2;i<=18;i++)localStorage.removeItem('nothing-state-v'+i);location.reload()};
setInterval(()=>{for(const t of S.trials){let r=ensure(t);capture(r,t);if(r.status==='draft'&&!['hearing','deliberating'].includes(t.status)&&Math.random()<.09)certify(r);if(Math.random()<.012)phantom(r)}renderRecord();save18()},1500);renderAll();save18();
})();
