(()=>{
const BS41=save,BR41=renderAll,O41=JSON.parse(localStorage.getItem('nothing-state-v41')||'null')||{},cl=(v,a,b)=>Math.max(a,Math.min(b,v)),pick=a=>a&&a.length?a[Math.floor(Math.random()*a.length)]:null;
const WITNESS_NAMES=['traveler','bailiff','archive','court','administration'];
S.transparencyLogs=O41.transparencyLogs||{A:null,B:null};
S.transparencyEntries=O41.transparencyEntries||[];
S.transparencyWitnesses=O41.transparencyWitnesses||[];
S.transparencyForks=O41.transparencyForks||[];
S.transparencyProofs=O41.transparencyProofs||[];
S.transparencyGossip=O41.transparencyGossip||[];
S.transparencyEntrySerial=O41.transparencyEntrySerial||0;
S.transparencyForkSerial=O41.transparencyForkSerial||0;
S.transparencyProofSerial=O41.transparencyProofSerial||0;
S.transparencyGossipSerial=O41.transparencyGossipSerial||0;
S.logWitnessSignatures=O41.logWitnessSignatures||0;
S.logEquivocations=O41.logEquivocations||0;
S.logProofFailures=O41.logProofFailures||0;
S.logProofSuccesses=O41.logProofSuccesses||0;
S.logReconciliations=O41.logReconciliations||0;
S.crossRealityGossip=O41.crossRealityGossip||0;
S.transparencyCrises=O41.transparencyCrises||0;
S.transparencyAuthorityEvents=O41.transparencyAuthorityEvents||0;
S.lastTransparencyCrisis=O41.lastTransparencyCrisis||0;
S.observedTrust41=O41.observedTrust41||{};
S.transparencyKeys=O41.transparencyKeys||{};
S.transparencyLogs.A=S.transparencyLogs.A||null;S.transparencyLogs.B=S.transparencyLogs.B||null;
S.transparencyEntries=S.transparencyEntries.map((e,i)=>({id:e.id||'LE'+(i+1),reality:e.reality||'A',seq:e.seq||i+1,type:e.type||'event',objectId:e.objectId||null,rootId:e.rootId||null,summary:e.summary||'unknown trust event',digest:e.digest||'00000000',prevHead:e.prevHead||'00000000',headAfter:e.headAfter||null,visibility:e.visibility||'public',created:e.created||Date.now(),proofs:e.proofs||0,x:Number.isFinite(e.x)?e.x:9+Math.random()*82,y:Number.isFinite(e.y)?e.y:12+Math.random()*70}));
S.transparencyWitnesses=S.transparencyWitnesses.map((w,i)=>({id:w.id||'W'+(i+1),reality:w.reality||'A',name:w.name||'witness',side:w.side||'canonical',lastHead:w.lastHead||null,lastSigned:w.lastSigned||0,signatures:w.signatures||0,trust:Number.isFinite(w.trust)?w.trust:.6}));
S.transparencyForks=S.transparencyForks.map((f,i)=>({id:f.id||'FORK'+(i+1),reality:f.reality||'A',baseHead:f.baseHead||'00000000',canonicalHead:f.canonicalHead||null,alternateHead:f.alternateHead||null,shadowSummary:f.shadowSummary||'undisclosed certificate',sourceEntryId:f.sourceEntryId||null,status:f.status||'active',detected:!!f.detected,created:f.created||Date.now(),resolvedAt:f.resolvedAt||null,x:Number.isFinite(f.x)?f.x:10+Math.random()*80,y:Number.isFinite(f.y)?f.y:12+Math.random()*68}));
S.transparencyProofs=S.transparencyProofs.map((p,i)=>({id:p.id||'IP'+(i+1),reality:p.reality||'A',entryId:p.entryId||null,status:p.status||'verified',head:p.head||null,created:p.created||Date.now()}));
S.transparencyGossip=S.transparencyGossip.map((g,i)=>({id:g.id||'G'+(i+1),source:g.source||'A',receivedBy:g.receivedBy||'B',head:g.head||null,localQuorum:g.localQuorum||null,status:g.status||'consistent',created:g.created||Date.now()}));
function save41(){BS41();localStorage.setItem('nothing-state-v41',JSON.stringify({transparencyLogs:S.transparencyLogs,transparencyEntries:S.transparencyEntries,transparencyWitnesses:S.transparencyWitnesses,transparencyForks:S.transparencyForks,transparencyProofs:S.transparencyProofs,transparencyGossip:S.transparencyGossip,transparencyEntrySerial:S.transparencyEntrySerial,transparencyForkSerial:S.transparencyForkSerial,transparencyProofSerial:S.transparencyProofSerial,transparencyGossipSerial:S.transparencyGossipSerial,logWitnessSignatures:S.logWitnessSignatures,logEquivocations:S.logEquivocations,logProofFailures:S.logProofFailures,logProofSuccesses:S.logProofSuccesses,logReconciliations:S.logReconciliations,crossRealityGossip:S.crossRealityGossip,transparencyCrises:S.transparencyCrises,transparencyAuthorityEvents:S.transparencyAuthorityEvents,lastTransparencyCrisis:S.lastTransparencyCrisis,observedTrust41:S.observedTrust41,transparencyKeys:S.transparencyKeys}))}save=save41;
const realm=id=>S.real[id],root=id=>(S.trustRoots||[]).find(r=>r.id===id),log=id=>S.transparencyLogs[id],entries=id=>S.transparencyEntries.filter(e=>e.reality===id),witnesses=id=>S.transparencyWitnesses.filter(w=>w.reality===id),activeFork=id=>[...S.transparencyForks].reverse().find(f=>f.reality===id&&f.status==='active');
function hash41(s){let h=2166136261>>>0;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)>>>0}return h.toString(16).padStart(8,'0')}
function acceptedOperator(id){let accepted=S.trustPolicies?.[id]?.acceptedRoots||[],rs=(S.trustRoots||[]).filter(r=>accepted.includes(r.id)&&r.status==='active');return [...rs].sort((a,b)=>(b.strength||0)-(a.strength||0))[0]||null}
function ensureLogs(){for(const id of['A','B']){if(!S.transparencyLogs[id]){let op=acceptedOperator(id)||(S.trustRoots||[]).find(r=>r.reality===id&&r.status==='active')||null;S.transparencyLogs[id]={id:'LOG-'+id,reality:id,head:'00000000',sequence:0,operatorRootId:op?.id||null,quorumHead:null,status:'active',created:Date.now(),equivocations:0};appendEntry(id,'genesis','LOG-'+id,op?.id||null,'TRANSPARENCY GENESIS: Reality '+id+' began an append-only trust log')}for(const name of WITNESS_NAMES)if(!S.transparencyWitnesses.find(w=>w.reality===id&&w.name===name))S.transparencyWitnesses.push({id:'W'+id+'-'+name,reality:id,name,side:'canonical',lastHead:null,lastSigned:0,signatures:0,trust:.58+Math.random()*.12})}}
function appendEntry(id,type,objectId,rootId,summary,opts={}){let l=log(id);if(!l)return null;let seq=++l.sequence,prev=l.head||'00000000',digest=hash41([id,seq,type,objectId,rootId,summary,Date.now()].join('|')),visibility=opts.visibility||'public',headAfter=visibility==='public'?hash41(prev+'|'+digest):null,e={id:'LE'+(++S.transparencyEntrySerial),reality:id,seq,type,objectId,rootId,summary,digest,prevHead:prev,headAfter,visibility,created:Date.now(),proofs:0,x:9+Math.random()*82,y:12+Math.random()*70};S.transparencyEntries.push(e);if(visibility==='public')l.head=headAfter;else{remember('TRANSPARENCY OMISSION '+e.id+': '+summary+' was not added to the public log',realm(id));if(typeof place==='function')place('cold','certificate with no public inclusion',realm(id))}return e}
function maybeConceal(id,rootId){let r=root(rootId);return !!(r&&r.status==='compromised'&&Math.random()<.2)}
function observeTrustObjects(){ensureLogs();for(const r of(S.trustRoots||[])){let k='root:'+r.id;if(S.observedTrust41[k])continue;S.observedTrust41[k]=1;appendEntry(r.reality,'root',r.id,r.id,'ROOT EVENT '+r.id+': '+r.label+' · '+r.status)}for(const c of(S.identityCertificates||[])){let k='cert:'+c.id;if(S.observedTrust41[k])continue;S.observedTrust41[k]=1;appendEntry(c.reality,'certificate',c.id,c.rootId,'CERTIFICATE '+c.id+' signed by '+c.rootId+' for '+(c.identityId||'unknown identity'),{visibility:maybeConceal(c.reality,c.rootId)?'concealed':'public'})}for(const x of(S.crossSignatures||[])){let k='xsign:'+x.id;if(S.observedTrust41[k])continue;S.observedTrust41[k]=1;let fr=root(x.fromRoot),id=fr?.reality||'A';appendEntry(id,'cross-sign',x.id,x.fromRoot,'CROSS-SIGN '+x.id+': '+x.fromRoot+' → '+x.toRoot)}for(const a of(S.trustAudits||[])){let k='audit:'+a.id;if(S.observedTrust41[k])continue;S.observedTrust41[k]=1;appendEntry(a.reality,'trust-audit',a.id,a.rootId,'TRUST AUDIT '+a.id+': '+a.status+' · '+(a.certificateId||'no certificate'))}}
function syncOperators(){for(const id of['A','B']){let l=log(id),op=root(l.operatorRootId),next=acceptedOperator(id);if(next&&(!op||op.status!=='active'||!(S.trustPolicies?.[id]?.acceptedRoots||[]).includes(op.id))&&l.operatorRootId!==next.id){let old=l.operatorRootId;l.operatorRootId=next.id;appendEntry(id,'operator-change',next.id,next.id,'LOG OPERATOR CHANGE: '+(old||'none')+' → '+next.id);remember('TRANSPARENCY OPERATOR: '+l.id+' is now anchored by '+next.id,realm(id))}}}
function signWitness(w){if(!w)return;let l=log(w.reality),f=activeFork(w.reality),head=f?(w.side==='alternate'?f.alternateHead:f.canonicalHead):l.head;w.lastHead=head;w.lastSigned=Date.now();w.signatures++;S.logWitnessSignatures++;remember('LOG WITNESS: '+w.name+' signed '+head+' for '+l.id,realm(w.reality));evaluateWitnesses(w.reality)}
function signAll(id=S.active){for(const w of witnesses(id))signWitness(w);renderAll();save41();openTransparency(id)}
function evaluateWitnesses(id){let ws=witnesses(id).filter(w=>w.lastHead),counts={};for(const w of ws)counts[w.lastHead]=(counts[w.lastHead]||0)+1;let heads=Object.keys(counts);if(heads.length>1){let f=activeFork(id);if(f)detectEquivocation(f,'witness disagreement')}else if(heads.length===1&&counts[heads[0]]>=3){let l=log(id),h=heads[0];if(l.quorumHead!==h){l.quorumHead=h;let op=root(l.operatorRootId);if(op&&op.status==='active'){op.strength=cl((op.strength||.55)+.008,.1,.99);S.transparencyAuthorityEvents++}remember('TRANSPARENCY QUORUM: '+counts[h]+' witnesses agree on '+h,realm(id))}}}
function createSplitView(id=S.active,sourceEntry=null,automatic=false){let l=log(id);if(!l||activeFork(id))return activeFork(id);let e=sourceEntry||[...entries(id)].reverse().find(e=>e.visibility==='public'&&e.type!=='genesis');if(!e)return null;let base=e.prevHead||'00000000',alt=hash41(base+'|shadow|'+e.objectId+'|'+Date.now()),f={id:'FORK'+(++S.transparencyForkSerial),reality:id,baseHead:base,canonicalHead:l.head,alternateHead:alt,shadowSummary:'alternate log omitted '+e.objectId+' and recorded a different trust event',sourceEntryId:e.id,status:'active',detected:false,created:Date.now(),resolvedAt:null,x:10+Math.random()*80,y:12+Math.random()*68};S.transparencyForks.push(f);let ws=witnesses(id);ws.forEach((w,i)=>w.side=i%2?'alternate':'canonical');l.status='split-view';remember('SPLIT VIEW '+f.id+': '+l.id+' began serving two signed histories',realm(id));if(typeof place==='function'){place('cold','same log two signed histories',realm(id));place('dream','certificate visible only to one witness',realm(id))}S.bailiffMood='waiting for witnesses to compare signed tree heads';if(!automatic)$('#msg').textContent=f.id+' exists: the same transparency log now has two valid-looking endings.';renderAll();save41();return f}
function detectEquivocation(f,reason){if(!f||f.detected)return;f.detected=true;S.logEquivocations++;let l=log(f.reality);l.equivocations=(l.equivocations||0)+1;l.status='equivocated';let op=root(l.operatorRootId),policy=S.trustPolicies?.[f.reality];if(op&&policy){policy.acceptedRoots=(policy.acceptedRoots||[]).filter(x=>x!==op.id);remember('ROOT DISTRUSTED BY TRANSPARENCY: '+op.id+' lost trust after '+f.id+' equivocated',realm(f.reality));if(typeof place==='function')place('cold','trusted root removed by witness gossip',realm(f.reality))}let n=openSecurityIncident(f.reality,'transparency log equivocation: '+l.id,'SEV1');for(const rid of['A','B']){realm(rid).disputes=(realm(rid).disputes||0)+1;remember('TRANSPARENCY EQUIVOCATION: '+l.id+' showed incompatible signed histories · '+reason,realm(rid))}transparencyCrisis(f.reality,'equivocation');$('#msg').textContent='EQUIVOCATION DETECTED: witnesses caught '+l.id+' presenting two histories. '+(op?op.id+' was removed from the trust store.':'');return n}
function openSecurityIncident(id,title,severity='SEV2'){S.incidents=S.incidents||[];let existing=S.incidents.find(n=>n.reality===id&&n.status==='open'&&n.title===title);if(existing)return existing;S.incidentSerial=S.incidentSerial||0;let n={id:'INC'+(++S.incidentSerial),reality:id,title,severity,status:'open',alertIds:[],started:Date.now(),acknowledged:null,resolved:null,postmortem:null,owner:'transparency review',x:10+Math.random()*80,y:12+Math.random()*68};S.incidents.push(n);remember('TRANSPARENCY INCIDENT '+n.id+': '+title,realm(id));return n}
function gossipAcross(id=S.active){let other=id==='A'?'B':'A',l=log(id),f=activeFork(id),served=f?f.alternateHead:l.head,g={id:'G'+(++S.transparencyGossipSerial),source:id,receivedBy:other,head:served,localQuorum:l.quorumHead,status:l.quorumHead&&served!==l.quorumHead?'mismatch':'consistent',created:Date.now()};S.transparencyGossip.push(g);S.transparencyGossip=S.transparencyGossip.slice(-40);S.crossRealityGossip++;remember('LOG GOSSIP '+g.id+': Reality '+other+' received '+served+' for '+l.id,realm(other));if(g.status==='mismatch'&&f)detectEquivocation(f,'cross-reality gossip');else $('#msg').textContent='Reality '+other+' received '+l.id+' head '+served+'. '+(l.quorumHead?(g.status==='consistent'?'It matches the local witness quorum.':'It differs from the last local quorum, but no active fork is present.'):'No local quorum exists yet.');renderAll();save41();openTransparency(id)}
function requestProof(e){if(!e)return null;let ok=e.visibility==='public'&&!!e.headAfter,p={id:'IP'+(++S.transparencyProofSerial),reality:e.reality,entryId:e.id,status:ok?'verified':'failed',head:e.headAfter||log(e.reality)?.head||null,created:Date.now()};S.transparencyProofs.push(p);S.transparencyProofs=S.transparencyProofs.slice(-48);e.proofs=(e.proofs||0)+1;if(ok){S.logProofSuccesses++;remember('INCLUSION PROOF '+p.id+': '+e.id+' is included under '+p.head,realm(e.reality));$('#msg').textContent=p.id+' verified '+e.id+' in the append-only log.'}else{S.logProofFailures++;remember('INCLUSION PROOF FAILED '+p.id+': '+e.objectId+' exists without public inclusion',realm(e.reality));if(typeof place==='function')place('cold','valid certificate missing from transparency',realm(e.reality));openSecurityIncident(e.reality,'certificate or trust event missing from transparency log','SEV2');transparencyCrisis(e.reality,'proof-failure');$('#msg').textContent=p.id+' FAILED: '+e.objectId+' exists, but the public log cannot prove it was included.'}renderAll();save41();openEntry(e);return p}
function resolveFork(f,mode){if(!f||f.status!=='active')return;let id=f.reality,l=log(id);if(mode==='alternate'){appendEntry(id,'reconciliation',f.id,l.operatorRootId,'RECONCILIATION: alternate history admitted after '+f.id+' · '+f.shadowSummary);remember('FORK RECONCILED: alternate branch became a disclosed part of '+l.id,realm(id))}else if(mode==='distrust'){let op=root(l.operatorRootId),p=S.trustPolicies?.[id];if(op&&p)p.acceptedRoots=(p.acceptedRoots||[]).filter(x=>x!==op.id);remember('FORK RECONCILED BY DISTRUST: '+l.operatorRootId+' remains outside the trust store',realm(id))}else remember('FORK RECONCILED: canonical history retained for '+l.id,realm(id));for(const w of witnesses(id)){w.side='canonical';w.lastHead=null}f.status='resolved-'+mode;f.resolvedAt=Date.now();l.status='active';S.logReconciliations++;signAll(id);save41()}
function retrustOperator(id){let l=log(id),op=root(l.operatorRootId),p=S.trustPolicies?.[id];if(!op||!p||op.status!=='active')return;if(!p.acceptedRoots.includes(op.id))p.acceptedRoots.push(op.id);op.strength=cl((op.strength||.5)-.03,.1,.99);appendEntry(id,'retrust',op.id,op.id,'TRUST RESTORED AFTER DISCLOSURE: '+op.id+' accepted again despite prior equivocation');remember('TRANSPARENCY DISCLOSURE: '+op.id+' was reaccepted after the fork became public',realm(id));$('#msg').textContent=op.id+' re-entered the trust store. The equivocation remains in the log.';renderAll();save41();openTransparency(id)}
function transparencyCrisis(id,reason){if(Date.now()-S.lastTransparencyCrisis<8000)return false;let key=id+'|'+reason+'|'+Math.floor(Date.now()/20000);if(S.transparencyKeys['crisis-'+key])return false;S.transparencyKeys['crisis-'+key]=1;S.transparencyCrises++;S.lastTransparencyCrisis=Date.now();realm(id).timelineDrift=(realm(id).timelineDrift||0)+1;if(typeof place==='function'){place('cold','append-only record with two endings',realm(id));place('dream','authority caught signing two histories',realm(id))}S.bailiffMood='comparing signed tree heads before obeying trust';return true}
function spontaneousFork(){for(const id of['A','B']){if(activeFork(id))continue;let l=log(id),op=root(l?.operatorRootId),rival=(S.trustPolicies?.[id]?.acceptedRoots||[]).length>1,p=.0008;if(op?.status==='compromised')p=.012;else if(rival)p=.003;if(Math.random()<p){createSplitView(id,null,true);break}}}
function renderTransparency(){ensureLogs();observeTrustObjects();syncOperators();let layer=$('#transparencyLayer');if(!layer){layer=document.createElement('div');layer.id='transparencyLayer';document.body.appendChild(layer)}layer.innerHTML='';for(const e of S.transparencyEntries.slice(-24)){let n=document.createElement('i');n.className='transparencyEntry '+e.visibility+' '+e.type;n.dataset.label=e.id;n.style.left=e.x+'%';n.style.top=e.y+'%';n.onclick=()=>openEntry(e);layer.appendChild(n)}for(const f of S.transparencyForks.filter(f=>f.status==='active')){let n=document.createElement('i');n.className='transparencyFork';n.dataset.label=f.id;n.style.left=f.x+'%';n.style.top=f.y+'%';n.onclick=()=>openFork(f);layer.appendChild(n)}let line=$('#transparencyline');if(!line){line=document.createElement('div');line.id='transparencyline';line.className='line';($('#trustline')||$('#accessline')||$('#opsline')||$('#observabilityline')||$('#enforcement')).after(line)}let id=S.active,l=log(id),ws=witnesses(id),same=ws.filter(w=>w.lastHead===l.head).length;line.textContent='transparency: '+l.id+' · head '+l.head+' · '+entries(id).length+' entries · '+same+'/'+ws.length+' witnesses on current head · '+S.logProofSuccesses+' proofs · '+S.logEquivocations+' equivocations · '+S.transparencyCrises+' crises'+(activeFork(id)?' · SPLIT VIEW':'');let ctr=document.querySelector('#app .controls');if(ctr&&!$('#openTransparencyButton')){let b=document.createElement('button');b.id='openTransparencyButton';b.textContent='open transparency log';b.onclick=()=>openTransparency(S.active);ctr.prepend(b)}if(ctr&&!$('#gossipTransparencyButton')){let b=document.createElement('button');b.id='gossipTransparencyButton';b.textContent='gossip trust log';b.onclick=()=>gossipAcross(S.active);ctr.prepend(b)}}
function openEntry(e){let b=[['request inclusion proof',()=>requestProof(e)]];if(e.visibility==='public'&&!activeFork(e.reality))b.push(['serve split view from here',()=>{createSplitView(e.reality,e,false);closePanel()}]);b.push(['close',closePanel]);panel(e.id+' · '+e.type.toUpperCase(),e.summary,'seq '+e.seq+' · digest '+e.digest+' · prev '+e.prevHead+' · '+(e.headAfter?'head '+e.headAfter:'NOT PUBLICLY INCLUDED')+' · proofs '+e.proofs,b)}
function openFork(f){let b=[['have all witnesses sign',()=>{signAll(f.reality);openFork(f)}],['gossip across rift',()=>gossipAcross(f.reality)],['retain canonical history',()=>resolveFork(f,'canonical')],['admit alternate history',()=>resolveFork(f,'alternate')],['distrust log operator',()=>resolveFork(f,'distrust')],['close',closePanel]];panel(f.id+' · SPLIT VIEW','canonical '+f.canonicalHead+'\nvs alternate '+f.alternateHead,f.shadowSummary+' · '+(f.detected?'EQUIVOCATION DETECTED':'not yet compared by enough witnesses'),b)}
function openTransparency(id=S.active){let l=log(id),ws=witnesses(id),latest=[...entries(id)].reverse().slice(0,5),b=[];for(const e of latest)b.push(['open '+e.id,()=>openEntry(e)]);let f=activeFork(id);if(f)b.push(['open '+f.id,()=>openFork(f)]);b.push(['witness current head',()=>{for(const w of ws)if(!w.lastHead||Math.random()<.55)signWitness(w);renderAll();save41();openTransparency(id)}],['gossip across rift',()=>gossipAcross(id)]);if(!f)b.push(['create split view',()=>{createSplitView(id,null,false);openTransparency(id)}]);let op=root(l.operatorRootId),accepted=(S.trustPolicies?.[id]?.acceptedRoots||[]).includes(l.operatorRootId);if(op&&op.status==='active'&&!accepted)b.push(['retrust operator after disclosure',()=>retrustOperator(id)]);b.push(['close',closePanel]);let headCounts={};for(const w of ws.filter(w=>w.lastHead))headCounts[w.lastHead]=(headCounts[w.lastHead]||0)+1;panel(l.id+' · '+l.status.toUpperCase(),'head '+l.head+'\noperator '+(l.operatorRootId||'none')+'\n'+(l.quorumHead?'witness quorum '+l.quorumHead:'no witness quorum yet'),entries(id).length+' append-only entries · witness heads '+(Object.entries(headCounts).map(([h,n])=>h+':'+n).join(' · ')||'none')+' · proofs '+S.transparencyProofs.filter(p=>p.reality===id).length+' · forks '+S.transparencyForks.filter(f=>f.reality===id).length,b)}
renderAll=function(){BR41();renderTransparency()};let f=$('#forget');if(f)f.onclick=()=>{for(let i=2;i<=41;i++)localStorage.removeItem('nothing-state-v'+i);location.reload()};
setInterval(()=>{observeTrustObjects();syncOperators();let id=Math.random()<.5?'A':'B',ws=witnesses(id);if(ws.length&&Math.random()<.18)signWitness(pick(ws));spontaneousFork();renderTransparency();save41()},1900);ensureLogs();observeTrustObjects();syncOperators();renderAll();save41();
})();
