(()=>{
const BS60=save,BR60=renderAll,O60=JSON.parse(localStorage.getItem('nothing-state-v60')||'null')||{},cl=(v,a,b)=>Math.max(a,Math.min(b,v));
S.treaties60=O60.treaties60||[];
S.treatyArticles60=O60.treatyArticles60||[];
S.treatyJudges60=O60.treatyJudges60||[];
S.treatyCases60=O60.treatyCases60||[];
S.treatyAmendments60=O60.treatyAmendments60||[];
S.treatyWithdrawals60=O60.treatyWithdrawals60||[];
S.treatySerial60=O60.treatySerial60||0;
S.treatyCaseSerial60=O60.treatyCaseSerial60||0;
S.treatyAmendmentSerial60=O60.treatyAmendmentSerial60||0;
S.treatyWithdrawalSerial60=O60.treatyWithdrawalSerial60||0;
S.treatyCasesDecided60=O60.treatyCasesDecided60||0;
S.ultraViresFindings60=O60.ultraViresFindings60||0;
S.emergencyCustoms60=O60.emergencyCustoms60||0;
S.treatyAmendmentsPassed60=O60.treatyAmendmentsPassed60||0;
S.treatyWithdrawalsCompleted60=O60.treatyWithdrawalsCompleted60||0;
S.treatyCrises60=O60.treatyCrises60||0;
S.lastTreatyCrisis60=O60.lastTreatyCrisis60||0;
S.treatyKeys60=O60.treatyKeys60||{};
S.lastTreatyTick60=O60.lastTreatyTick60||Date.now();
function save60(){BS60();localStorage.setItem('nothing-state-v60',JSON.stringify({treaties60:S.treaties60,treatyArticles60:S.treatyArticles60,treatyJudges60:S.treatyJudges60,treatyCases60:S.treatyCases60,treatyAmendments60:S.treatyAmendments60,treatyWithdrawals60:S.treatyWithdrawals60,treatySerial60:S.treatySerial60,treatyCaseSerial60:S.treatyCaseSerial60,treatyAmendmentSerial60:S.treatyAmendmentSerial60,treatyWithdrawalSerial60:S.treatyWithdrawalSerial60,treatyCasesDecided60:S.treatyCasesDecided60,ultraViresFindings60:S.ultraViresFindings60,emergencyCustoms60:S.emergencyCustoms60,treatyAmendmentsPassed60:S.treatyAmendmentsPassed60,treatyWithdrawalsCompleted60:S.treatyWithdrawalsCompleted60,treatyCrises60:S.treatyCrises60,lastTreatyCrisis60:S.lastTreatyCrisis60,treatyKeys60:S.treatyKeys60,lastTreatyTick60:S.lastTreatyTick60}))}save=save60;
const realm=id=>S.real[id],fund60=()=>S.stabilizationFunds58?.[0],board60=()=>S.fundBoards59?.[0],quota60=id=>(S.stabilizationQuotas58||[]).find(q=>q.reality===id),director60=id=>(S.fundDirectors59||[]).find(d=>d.reality===id),program60=id=>(S.stabilizationPrograms58||[]).find(p=>p.id===id),currency60=id=>(S.fxCurrencies56||[]).find(c=>c.reality===id),acct60=id=>(S.tradeAccounts57||[]).find(a=>a.reality===id),treaty60=()=>S.treaties60[0],article60=key=>S.treatyArticles60.find(a=>a.key===key);
function trust60(id,status,note){let accepted=S.trustPolicies?.[id]?.acceptedRoots||[],r=[...(S.trustRoots||[])].filter(x=>accepted.includes(x.id)&&x.status==='active').sort((a,b)=>(b.strength||0)-(a.strength||0))[0];S.trustAudits=S.trustAudits||[];S.trustAuditSerial=S.trustAuditSerial||0;S.trustAudits.push({id:'TA'+(++S.trustAuditSerial),reality:id,remediationId:null,credentialId:null,certificateId:null,rootId:r?.id||null,status,created:Date.now(),note,x:10+Math.random()*80,y:12+Math.random()*68})}
function incident60(id,title,severity='SEV2'){S.incidents=S.incidents||[];let ex=S.incidents.find(i=>i.reality===id&&i.title===title&&i.status==='open');if(ex)return ex;S.incidentSerial=S.incidentSerial||0;let x={id:'INC'+(++S.incidentSerial),reality:id,title,severity,status:'open',alertIds:[],started:Date.now(),acknowledged:null,resolved:null,postmortem:null,owner:'stabilization treaty tribunal',x:10+Math.random()*80,y:12+Math.random()*68};S.incidents.push(x);return x}
function treatyCrisis(id,kind,severity='SEV2'){let now=Date.now(),k=id+'|'+kind;if(S.treatyKeys60[k]&&now-S.treatyKeys60[k]<14000)return;S.treatyKeys60[k]=now;S.treatyCrises60++;S.lastTreatyCrisis60=now;remember('TREATY CRISIS: '+kind+' made the law of rescue another source of authority over software reality',realm(id));if(typeof place==='function'){place('cold','treaty rule written after the emergency it now authorizes',realm(id));place('dream','sovereignty clause attached to a foreign-reserve balance sheet',realm(id))}let b=$('#bailiff');if(b)b.textContent='asking whether the treaty constrains power or merely records who already has it';incident60(id,'stabilization treaty crisis: '+kind,severity)}
function addArticle(key,title,text,x,y,opts={}){let a={id:'ART'+(S.treatyArticles60.length+1),treatyId:treaty60().id,key,title,text,version:1,status:'active',customary:false,entrenched:!!opts.entrenched,emergencyLimit:opts.emergencyLimit??null,created:Date.now(),x,y};S.treatyArticles60.push(a);return a}
function ensureTreaty(){if(!fund60()||!board60())return null;let t=treaty60();if(!t){t={id:'AOS'+(++S.treatySerial60),name:'Articles of Interreality Stabilization',status:'in-force',members:{A:'member',B:'member'},legitimacy:.8,amendmentThreshold:.75,customaryPrecedents:0,withdrawals:0,created:Date.now(),x:50,y:43};S.treaties60.push(t);addArticle('quota','Article I · Quota Representation','Voting weight follows stabilization quota and reserve contribution.',35,43);addArticle('recusal','Article II · Borrower Recusal','A member does not vote on major decisions governing its own rescue program.',40,47,{entrenched:true});addArticle('majority','Article III · Major Decisions','Major program action requires sixty percent of total voting weight.',45,43);addArticle('necessity','Article IV · Systemic Necessity','After a genuine board deadlock, the staff chair may execute one emergency act before renewed member authorization.',50,48,{emergencyLimit:1});addArticle('surveillance','Article V · Surveillance','Technical surveillance may inform program governance and review.',55,43);addArticle('conditionality','Article VI · Conditionality','Reserve access may be conditioned on domestic software, trade, exchange-rate, and monetary policy.',60,47);addArticle('withdrawal','Article VII · Withdrawal and Settlement','A member may leave the Articles, but accrued obligations and external debts survive withdrawal.',65,43,{entrenched:true});for(const [id,name,x] of [['A','Reality A treaty judge',43],['B','Reality B treaty judge',57],['N','Archive neutral judge',50]])S.treatyJudges60.push({id:'TJ'+id,treatyId:t.id,seat:id,name,status:'active',created:Date.now(),x,y:52});remember('ARTICLES OF STABILIZATION '+t.id+': rescue voting, recusal, conditionality, emergency power, and withdrawal became treaty text',realm('A'));remember('ARTICLES OF STABILIZATION '+t.id+': rescue voting, recusal, conditionality, emergency power, and withdrawal became treaty text',realm('B'));trust60('A','interreality-stabilization-treaty-created',t.id+' Articles of Interreality Stabilization');trust60('B','interreality-stabilization-treaty-created',t.id+' Articles of Interreality Stabilization')}return t}
function motionArticle(m){if(!m)return null;if(m.override)return article60('necessity');if(['tighten-conditionality','soften-conditionality','suspend-program'].includes(m.type))return article60('conditionality');if(m.type==='release-tranche')return article60('majority');if(m.type==='ratify-waiver')return article60('majority');return article60('quota')}
function latestMotion(id=null){let xs=[...(S.fundMotions59||[])].filter(m=>['passed','passed-override','rejected','deadlocked'].includes(m.status));if(id)xs=xs.filter(m=>m.targetReality===id);return xs.sort((a,b)=>(b.decided||b.created)-(a.decided||a.created))[0]||null}
function latestSurveillance60(id){return [...(S.surveillanceReports59||[])].filter(r=>r.reality===id).sort((a,b)=>b.created-a.created)[0]||null}
function judgeVote(j,c,m,a){if(!m||!a)return'void';let claimant=c.claimant,member=treaty60()?.members?.[claimant];if(member==='withdrawn')return'ultra-vires';if(m.override){if(a.customary)return'valid';let serial=(board60()?.chairPower||0);if(serial>a.emergencyLimit)return'ultra-vires';return'valid'}if(m.status==='passed'&&m.yesWeight+1e-9<(board60()?.majority||.6)*100)return'ultra-vires';if(m.type==='tighten-conditionality'){let s=latestSurveillance60(m.targetReality);if(!s||Date.now()-s.created>45000)return'ultra-vires'}if(j.seat===claimant&&m.targetReality===claimant&&m.yesWeight>60)return'ultra-vires';return'valid'}
function challengeLatest(id=S.active,manual=true){ensureTreaty();let m=latestMotion(id)||latestMotion();if(!m){if(manual)$('#msg').textContent='No decided fund-board action exists to challenge.';return null}let a=motionArticle(m),c={id:'TC'+(++S.treatyCaseSerial60),treatyId:treaty60().id,claimant:id,motionId:m.id,articleId:a?.id||null,articleKey:a?.key||null,status:'open',votes:{},decision:null,created:Date.now(),decided:null,x:10+Math.random()*80,y:12+Math.random()*68};S.treatyCases60.push(c);let valid=0,ultra=0;for(const j of S.treatyJudges60.filter(j=>j.status==='active')){let v=judgeVote(j,c,m,a);c.votes[j.id]=v;if(v==='valid')valid++;if(v==='ultra-vires')ultra++}c.decision=ultra>valid?'ultra-vires':'valid';c.status='decided';c.decided=Date.now();S.treatyCasesDecided60++;m.treatyCase60=c.id;m.treatyStatus60=c.decision;if(c.decision==='ultra-vires'){S.ultraViresFindings60++;remember('ULTRA VIRES '+c.id+': tribunal invalidated '+m.id+' under '+a.title+' after its institutional effects had already occurred',realm(id));if(typeof place==='function'){place('cold','unlawful reserve decision that cannot be unspent',realm(id));place('dream','legal invalidity arriving after operational finality',realm(id))}treatyCrisis(id,'tribunal invalidated an already-executed rescue decision','SEV1')}else{remember('TREATY JUDGMENT '+c.id+': '+m.id+' upheld under '+a.title,realm(id));trust60(id,'stabilization-treaty-judgment',c.id+' '+m.id+' '+c.decision)}if(manual){$('#msg').textContent=c.id+' decided '+c.decision.toUpperCase()+'. The underlying Build 59 effect was not rolled back.';renderAll();save60();openCase(c)}return c}
function formalizeNecessity(manual=true){ensureTreaty();let a=article60('necessity'),t=treaty60(),overrides=board60()?.chairPower||0;if(overrides<2){if(manual)$('#msg').textContent='Article IV has not accumulated enough repeated emergency practice to become customary law.';return null}if(a.customary){if(manual)openArticle(a);return a}let am={id:'AMD'+(++S.treatyAmendmentSerial60),treatyId:t.id,articleId:a.id,type:'codify-emergency-custom',status:'passed',votes:{A:quota60('A')?.votes||50,B:quota60('B')?.votes||50},threshold:t.amendmentThreshold,created:Date.now(),decided:Date.now(),x:10+Math.random()*80,y:12+Math.random()*68};S.treatyAmendments60.push(am);a.version++;a.customary=true;a.emergencyLimit=Infinity;a.text='Repeated systemic-necessity overrides, once openly recorded, constitute customary emergency authority until formally amended.';t.customaryPrecedents++;t.legitimacy=cl(t.legitimacy-.06,0,1);S.emergencyCustoms60++;S.treatyAmendmentsPassed60++;remember('EMERGENCY CUSTOM '+am.id+': repeated chair overrides hardened into Article IV treaty precedent',realm('A'));remember('EMERGENCY CUSTOM '+am.id+': repeated chair overrides hardened into Article IV treaty precedent',realm('B'));if(typeof place==='function')place('cold','exception repeated until it became constitutional text',realm(S.active));trust60('A','stabilization-emergency-custom-codified',am.id+' Article IV v'+a.version);trust60('B','stabilization-emergency-custom-codified',am.id+' Article IV v'+a.version);treatyCrisis(S.active,'emergency exception became treaty custom');if(manual){$('#msg').textContent='Article IV version '+a.version+' now recognizes repeated systemic-necessity overrides as customary authority.';renderAll();save60();openArticle(a)}return a}
function amendMajority(manual=true){ensureTreaty();let t=treaty60(),a=article60('majority'),qa=quota60('A')?.votes||50,qb=quota60('B')?.votes||50,yesA=t.members.A==='member',yesB=t.members.B==='member',yes=(yesA?qa:0)+(yesB?qb:0),am={id:'AMD'+(++S.treatyAmendmentSerial60),treatyId:t.id,articleId:a.id,type:'entrench-majority',status:yes+1e-9>=t.amendmentThreshold*100?'passed':'failed',votes:{A:yesA?'yes':'out',B:yesB?'yes':'out'},yesWeight:yes,threshold:t.amendmentThreshold,created:Date.now(),decided:Date.now(),x:10+Math.random()*80,y:12+Math.random()*68};S.treatyAmendments60.push(am);if(am.status==='passed'){a.version++;a.entrenched=true;a.text='Major program action requires sixty percent of total voting weight; alteration of this threshold requires treaty amendment.';S.treatyAmendmentsPassed60++;remember('TREATY AMENDMENT '+am.id+': Article III majority rule became entrenched',realm('A'));trust60('A','stabilization-treaty-amendment',am.id+' Article III v'+a.version)}if(manual){$('#msg').textContent=am.id+' '+am.status.toUpperCase()+' with '+yes.toFixed(1)+'% treaty weight.';renderAll();save60();openArticle(a)}return am}
function fileWithdrawal(id=S.active,manual=true){ensureTreaty();let t=treaty60();if(t.members[id]!=='member'){if(manual)$('#msg').textContent='Reality '+id+' is not an active treaty member.';return null}let existing=S.treatyWithdrawals60.find(w=>w.reality===id&&w.status==='notice');if(existing){if(manual)openWithdrawal(existing);return existing}let w={id:'WD'+(++S.treatyWithdrawalSerial60),treatyId:t.id,reality:id,status:'notice',filed:Date.now(),effectiveAt:Date.now()+30000,externalDebtAtNotice:acct60(id)?.externalDebt||0,programExposure:(S.stabilizationPrograms58||[]).filter(p=>p.reality===id).reduce((n,p)=>n+(p.disbursed||0),0),created:Date.now(),x:10+Math.random()*80,y:12+Math.random()*68};S.treatyWithdrawals60.push(w);t.members[id]='withdrawing';remember('TREATY WITHDRAWAL NOTICE '+w.id+': Reality '+id+' invoked Article VII while external obligations remained outstanding',realm(id));if(typeof place==='function')place('dream','sovereignty notice filed against a balance sheet',realm(id));if(manual){$('#msg').textContent='Reality '+id+' filed Article VII notice. Debts and deployed dependencies remain.';renderAll();save60();openWithdrawal(w)}return w}
function completeWithdrawal(w,manual=true){if(!w||w.status!=='notice')return false;let id=w.reality,t=treaty60(),q=quota60(id),d=director60(id),c=currency60(id),f=fund60(),code=id==='A'?'RB':'RA',contributed=id==='A'?(q?.contributedRB||0):(q?.contributedRA||0),pool=code==='RA'?(f?.poolRA||0):(f?.poolRB||0),returnAmt=Math.min(contributed,pool);if(f){if(code==='RA')f.poolRA=Math.max(0,f.poolRA-returnAmt);else f.poolRB=Math.max(0,f.poolRB-returnAmt)}if(c)c.foreignReserves=(c.foreignReserves||0)+returnAmt;if(q){q.rdr=0;q.votes=0}if(d)d.status='withdrawn';let oid=id==='A'?'B':'A',oq=quota60(oid),od=director60(oid);if(oq)oq.votes=100;if(od)od.votes=100;if(board60()){board60().dominant=oid;board60().status='single-member'}for(const p of (S.stabilizationPrograms58||[]).filter(p=>p.reality===id&&['active','off-track','funding-shortfall','board-suspended'].includes(p.status))){p.preWithdrawalStatus60=p.status;p.status='treaty-withdrawn';p.treatyAccessSuspended60=true}for(const m of (S.fundMotions59||[]).filter(m=>m.targetReality===id&&['pending','deadlocked'].includes(m.status)))m.status='treaty-barred';t.members[id]='withdrawn';t.status='fractured';t.withdrawals++;w.status='completed';w.completed=Date.now();w.reserveRepatriation=returnAmt;w.externalDebtAfter=acct60(id)?.externalDebt||0;S.treatyWithdrawalsCompleted60++;remember('ARTICLE VII WITHDRAWAL '+w.id+': Reality '+id+' left the stabilization treaty, recovered '+returnAmt.toFixed(1)+' '+code+', and retained '+w.externalDebtAfter.toFixed(1)+' of external debt',realm(id));if(typeof place==='function'){place('cold','left the institution but not the debt',realm(id));place('dream','formal sovereignty restored while foreign invoices remained',realm(id))}trust60(id,'stabilization-treaty-withdrawal',w.id+' reserve return '+returnAmt.toFixed(1)+' '+code);treatyCrisis(id,'member withdrew while financial obligations survived','SEV1');if(manual){$('#msg').textContent='Reality '+id+' withdrew. Board access ended; '+w.externalDebtAfter.toFixed(1)+' external debt remains.';renderAll();save60();openWithdrawal(w)}return true}
function reconcileTreaty(){ensureTreaty();let t=treaty60();for(const id of ['A','B'])if(t.members[id]==='withdrawn'){let d=director60(id),q=quota60(id);if(d)d.status='withdrawn';if(q)q.votes=0;for(const m of (S.fundMotions59||[]).filter(m=>m.targetReality===id&&['pending','deadlocked'].includes(m.status)))m.status='treaty-barred'}let a=article60('necessity');if((board60()?.chairPower||0)>=2&&!a.customary&&Math.random()<.0008)formalizeNecessity(false)}
function openCase(c){let m=(S.fundMotions59||[]).find(m=>m.id===c.motionId),a=S.treatyArticles60.find(a=>a.id===c.articleId),acts=[];if(m)acts.push(['open underlying board motion',()=>{if(typeof openMotion==='function')openMotion(m);else openTreaty()}]);acts.push(['open article',()=>openArticle(a)],['close',closePanel]);panel(c.id+' · TREATY CASE',c.decision.toUpperCase()+' · '+(a?.title||'unknown article'),'claimant Reality '+c.claimant+' · motion '+c.motionId+' · judges '+Object.entries(c.votes).map(([k,v])=>k+':'+v).join(' · ')+' · underlying operational effect preserved',acts)}
function openWithdrawal(w){let acts=[];if(w.status==='notice')acts.push(['complete withdrawal now',()=>completeWithdrawal(w,true)]);acts.push(['open Articles',openTreaty],['close',closePanel]);panel(w.id+' · ARTICLE VII WITHDRAWAL',w.status.toUpperCase()+' · Reality '+w.reality,'debt at notice '+w.externalDebtAtNotice.toFixed(1)+' · program exposure '+w.programExposure.toFixed(1)+(w.status==='completed'?' · reserves returned '+(w.reserveRepatriation||0).toFixed(1)+' · debt remaining '+(w.externalDebtAfter||0).toFixed(1):''),acts)}
function openArticle(a){if(!a)return openTreaty();let acts=[];if(a.key==='necessity')acts.push(['codify emergency custom',()=>formalizeNecessity(true)]);if(a.key==='majority')acts.push(['entrench majority rule',()=>amendMajority(true)]);acts.push(['challenge latest board decision',()=>challengeLatest(S.active,true)],['open Articles',openTreaty],['close',closePanel]);panel(a.title+' · v'+a.version,(a.customary?'CUSTOMARY · ':'')+(a.entrenched?'ENTRENCHED · ':'')+a.status.toUpperCase(),a.text,acts)}
function openTreaty(){ensureTreaty();let t=treaty60(),acts=[['challenge latest board decision',()=>challengeLatest(S.active,true)],['codify systemic-necessity precedent',()=>formalizeNecessity(true)],['file Article VII withdrawal',()=>fileWithdrawal(S.active,true)]];for(const a of S.treatyArticles60)acts.push([a.title,()=>openArticle(a)]);for(const c of S.treatyCases60.slice(-3))acts.push(['open '+c.id+' · '+c.decision,()=>openCase(c)]);for(const w of S.treatyWithdrawals60.slice(-2))acts.push(['open '+w.id+' · '+w.status,()=>openWithdrawal(w)]);acts.push(['close',closePanel]);panel(t.name+' · '+t.status.toUpperCase(),t.id+' · legitimacy '+t.legitimacy.toFixed(2),'members A '+t.members.A+' / B '+t.members.B+' · '+S.treatyArticles60.length+' articles · '+S.ultraViresFindings60+' ultra vires findings · '+S.emergencyCustoms60+' emergency customs · '+S.treatyWithdrawalsCompleted60+' withdrawals',acts)}
function autonomous(){ensureTreaty();let now=Date.now();if(now-S.lastTreatyTick60<2100)return;S.lastTreatyTick60=now;reconcileTreaty();let m=latestMotion();if(m&&m.override&&!m.treatyCase60&&(board60()?.chairPower||0)>=2&&Math.random()<.002)challengeLatest(m.targetReality||'A',false)}
function renderTreaty(){ensureTreaty();let layer=$('#treatyLayer');if(!layer){layer=document.createElement('div');layer.id='treatyLayer';document.body.appendChild(layer)}layer.innerHTML='';let t=treaty60(),te=document.createElement('i');te.className='treaty '+t.status;te.dataset.label='ARTICLES';te.style.left=t.x+'%';te.style.top=t.y+'%';te.onclick=openTreaty;layer.appendChild(te);for(const a of S.treatyArticles60){let e=document.createElement('i');e.className='treatyArticle'+(a.customary?' customary':'')+(a.entrenched?' entrenched':'');e.dataset.label=a.id.replace('ART','A');e.style.left=a.x+'%';e.style.top=a.y+'%';e.onclick=()=>openArticle(a);layer.appendChild(e)}for(const c of S.treatyCases60.slice(-8)){let e=document.createElement('i');e.className='treatyCase '+c.decision;e.dataset.label=c.decision==='ultra-vires'?'UV':'§';e.style.left=c.x+'%';e.style.top=c.y+'%';e.onclick=()=>openCase(c);layer.appendChild(e)}for(const w of S.treatyWithdrawals60.filter(w=>['notice','completed'].includes(w.status)).slice(-4)){let e=document.createElement('i');e.className='treatyWithdrawal '+w.status;e.dataset.label='EXIT';e.style.left=w.x+'%';e.style.top=w.y+'%';e.onclick=()=>openWithdrawal(w);layer.appendChild(e)}let line=$('#treatyline');if(!line){line=document.createElement('div');line.id='treatyline';line.className='line';($('#fundgovernanceline')||$('#stabilizationline')||$('#tradeline')||$('#enforcement')).after(line)}line.textContent='stabilization treaty: '+t.status+' · A '+t.members.A+' / B '+t.members.B+' · Article IV v'+article60('necessity').version+(article60('necessity').customary?' customary':'')+' · '+S.ultraViresFindings60+' ultra vires · '+S.treatyWithdrawalsCompleted60+' withdrawals · '+S.treatyCrises60+' crises';let ctr=document.querySelector('#app .controls');if(ctr&&!$('#openTreatyButton')){let x=document.createElement('button');x.id='openTreatyButton';x.textContent='open Articles of Agreement';x.onclick=openTreaty;ctr.prepend(x)}if(ctr&&!$('#challengeTreatyButton')){let x=document.createElement('button');x.id='challengeTreatyButton';x.textContent='challenge fund decision';x.onclick=()=>challengeLatest(S.active,true);ctr.prepend(x)}}
renderAll=function(){BR60();reconcileTreaty();renderTreaty()};let f=$('#forget');if(f)f.onclick=()=>{for(let i=2;i<=60;i++)localStorage.removeItem('nothing-state-v'+i);location.reload()};
setInterval(()=>{autonomous();renderTreaty();save60()},2300);ensureTreaty();reconcileTreaty();renderAll();save60();
})();
