(()=>{
const BS40=save,BR40=renderAll,O40=JSON.parse(localStorage.getItem('nothing-state-v40')||'null')||{},cl=(v,a,b)=>Math.max(a,Math.min(b,v)),pick=a=>a&&a.length?a[Math.floor(Math.random()*a.length)]:null;
const SCOPE40={
  'converge-runtime':'runtime.write',
  'rollback-release':'deployment.rollback',
  'rewrite-history':'history.write',
  'freeze-change':'change.freeze',
  'seal-record':'record.seal',
  'choose-citizenship':'citizenship.adjudicate'
};
S.trustRoots=O40.trustRoots||[];
S.identityCertificates=O40.identityCertificates||[];
S.trustPolicies=O40.trustPolicies||{A:{acceptedRoots:[]},B:{acceptedRoots:[]}};
S.crossSignatures=O40.crossSignatures||[];
S.trustAudits=O40.trustAudits||[];
S.trustRootSerial=O40.trustRootSerial||0;
S.identityCertificateSerial=O40.identityCertificateSerial||0;
S.crossSignatureSerial=O40.crossSignatureSerial||0;
S.trustAuditSerial=O40.trustAuditSerial||0;
S.rootRotations=O40.rootRotations||0;
S.rootCompromises=O40.rootCompromises||0;
S.rootRevocations=O40.rootRevocations||0;
S.certificatesIssued=O40.certificatesIssued||0;
S.certificatesRevoked=O40.certificatesRevoked||0;
S.crossRealityTrusts=O40.crossRealityTrusts||0;
S.untrustedRemediations=O40.untrustedRemediations||0;
S.forgedCertificates=O40.forgedCertificates||0;
S.trustCrises=O40.trustCrises||0;
S.rootAuthorityEvents=O40.rootAuthorityEvents||0;
S.lastTrustCrisis=O40.lastTrustCrisis||0;
S.trustKeys=O40.trustKeys||{};
S.observedRemediations40=O40.observedRemediations40||{};
S.trustAutomationHold=O40.trustAutomationHold||{A:false,B:false};
S.trustAutomationPriorGlobal=O40.trustAutomationPriorGlobal??null;
for(const id of['A','B'])S.trustPolicies[id]=Object.assign({acceptedRoots:[]},S.trustPolicies[id]||{});
S.trustRoots=S.trustRoots.map((r,i)=>({id:r.id||'ROOT'+(i+1),reality:r.reality||'A',label:r.label||'unknown root',sourceType:r.sourceType||'archive',sourceId:r.sourceId||null,status:r.status||'active',strength:Number.isFinite(r.strength)?r.strength:.58,created:r.created||Date.now(),rotatedFrom:r.rotatedFrom||null,retireAfter:r.retireAfter||null,compromisedAt:r.compromisedAt||null,version:r.version||1,x:Number.isFinite(r.x)?r.x:8+Math.random()*84,y:Number.isFinite(r.y)?r.y:10+Math.random()*72}));
S.identityCertificates=S.identityCertificates.map((c,i)=>({id:c.id||'CERT'+(i+1),reality:c.reality||'A',credentialId:c.credentialId||null,identityId:c.identityId||null,rootId:c.rootId||null,status:c.status||'valid',issuedAt:c.issuedAt||Date.now(),expiresAt:c.expiresAt||null,revokedAt:c.revokedAt||null,fingerprint:c.fingerprint||('00'+i),emergency:!!c.emergency,forged:!!c.forged,uses:c.uses||0,x:Number.isFinite(c.x)?c.x:10+Math.random()*80,y:Number.isFinite(c.y)?c.y:12+Math.random()*68}));
S.crossSignatures=S.crossSignatures.map((x,i)=>({id:x.id||'XS'+(i+1),fromRoot:x.fromRoot||null,toRoot:x.toRoot||null,status:x.status||'active',created:x.created||Date.now()}));
S.trustAudits=S.trustAudits.map((a,i)=>({id:a.id||'TA'+(i+1),reality:a.reality||'A',remediationId:a.remediationId||null,credentialId:a.credentialId||null,certificateId:a.certificateId||null,rootId:a.rootId||null,status:a.status||'trusted',created:a.created||Date.now(),note:a.note||'',x:Number.isFinite(a.x)?a.x:10+Math.random()*80,y:Number.isFinite(a.y)?a.y:12+Math.random()*68}));
function save40(){BS40();localStorage.setItem('nothing-state-v40',JSON.stringify({trustRoots:S.trustRoots,identityCertificates:S.identityCertificates,trustPolicies:S.trustPolicies,crossSignatures:S.crossSignatures,trustAudits:S.trustAudits,trustRootSerial:S.trustRootSerial,identityCertificateSerial:S.identityCertificateSerial,crossSignatureSerial:S.crossSignatureSerial,trustAuditSerial:S.trustAuditSerial,rootRotations:S.rootRotations,rootCompromises:S.rootCompromises,rootRevocations:S.rootRevocations,certificatesIssued:S.certificatesIssued,certificatesRevoked:S.certificatesRevoked,crossRealityTrusts:S.crossRealityTrusts,untrustedRemediations:S.untrustedRemediations,forgedCertificates:S.forgedCertificates,trustCrises:S.trustCrises,rootAuthorityEvents:S.rootAuthorityEvents,lastTrustCrisis:S.lastTrustCrisis,trustKeys:S.trustKeys,observedRemediations40:S.observedRemediations40,trustAutomationHold:S.trustAutomationHold,trustAutomationPriorGlobal:S.trustAutomationPriorGlobal}))}save=save40;
const realm=id=>S.real[id],root=id=>S.trustRoots.find(r=>r.id===id),credential=id=>(S.accessCredentials||[]).find(g=>g.id===id),identity=id=>(S.serviceIdentities||[]).find(x=>x.id===id),runbook=id=>(S.runbooks||[]).find(r=>r.id===id),alert=id=>(S.telemetryAlerts||[]).find(a=>a.id===id);
function authorityFor(id){let k=(S.constitutions||[]).find(c=>c.reality===id&&c.status==='ratified');if(k)return{type:'constitution',id:k.id||null,label:'constitutional root of Reality '+id};let o=[...(S.offices||[])].reverse().find(o=>o.reality===id&&['active','disputed'].includes(o.status)&&o.holder==='traveler');if(o)return{type:'office',id:o.id||null,label:'elected root of Reality '+id};let cg=(S.continuityCustodians||S.custodians||S.continuity||[]).find?.(c=>c.reality===id&&c.status!=='retired');if(cg)return{type:'continuity',id:cg.id||null,label:'continuity root of Reality '+id};let ex=(S.exileGovernments||S.governmentsInExile||[]).find?.(g=>g.reality===id&&g.status!=='dissolved');if(ex)return{type:'exile',id:ex.id||null,label:'exile root claiming Reality '+id};return{type:'archive',id:null,label:'archive root for Reality '+id}}
function makeRoot(id,opts={}){let a=opts.authority||authorityFor(id),r={id:'ROOT'+(++S.trustRootSerial),reality:id,label:opts.label||a.label,sourceType:opts.sourceType||a.type,sourceId:opts.sourceId??a.id,status:'active',strength:opts.strength??(.56+Math.random()*.12),created:Date.now(),rotatedFrom:opts.rotatedFrom||null,retireAfter:null,compromisedAt:null,version:opts.version||1,x:8+Math.random()*84,y:10+Math.random()*72};S.trustRoots.push(r);S.trustRoots=S.trustRoots.slice(-20);if(opts.accept!==false&&!S.trustPolicies[id].acceptedRoots.includes(r.id))S.trustPolicies[id].acceptedRoots.push(r.id);remember('ROOT OF TRUST '+r.id+': '+r.label+' became a trust anchor',realm(id));if(typeof place==='function')place('warm','root certificate nobody can sign above',realm(id));return r}
function activeRoots(id){return S.trustRoots.filter(r=>r.reality===id&&r.status==='active')}
function ensureRoots(){for(const id of['A','B'])if(!activeRoots(id).length)makeRoot(id)}
function rootAccepted(id,r,at=Date.now()){if(!r)return false;let accepted=S.trustPolicies[id]?.acceptedRoots?.includes(r.id);if(!accepted)return false;if(r.status==='revoked')return false;if(r.status==='retired'&&r.retireAfter&&at>r.retireAfter)return false;if(r.status==='compromised')return false;return true}
function fingerprint(){return Array.from({length:6},()=>Math.floor(Math.random()*256).toString(16).padStart(2,'0')).join(':')}
function certForCredential(g,at=Date.now(),targetReality=g?.reality){if(!g)return null;return [...S.identityCertificates].reverse().find(c=>c.credentialId===g.id&&c.issuedAt<=at&&(!c.expiresAt||c.expiresAt>at)&&c.status==='valid'&&rootAccepted(targetReality,root(c.rootId),at))||null}
function issueCertificate(g,r=null,opts={}){if(!g)return null;ensureRoots();r=r||activeRoots(g.reality)[0];if(!r)return null;let x=identity(g.identityId),dur=opts.duration??(g.breakGlass?55000:180000),c={id:'CERT'+(++S.identityCertificateSerial),reality:g.reality,credentialId:g.id,identityId:g.identityId,rootId:r.id,status:'valid',issuedAt:Date.now(),expiresAt:g.expiresAt?Math.min(g.expiresAt,Date.now()+dur):(opts.permanent?null:Date.now()+dur),revokedAt:null,fingerprint:fingerprint(),emergency:!!g.breakGlass,forged:!!opts.forged,uses:0,x:10+Math.random()*80,y:12+Math.random()*68};S.identityCertificates.push(c);S.identityCertificates=S.identityCertificates.slice(-56);S.certificatesIssued++;if(opts.forged){S.forgedCertificates++;remember('FORGED CERTIFICATE '+c.id+': '+r.id+' signed a credential for '+(x?.name||g.identityId)+' after trust was compromised',realm(g.reality));if(typeof place==='function')place('cold','valid signature attached to the wrong authority',realm(g.reality))}else remember('CERTIFICATE '+c.id+': '+r.id+' signed '+g.id+' for '+(x?.name||g.identityId),realm(g.reality));releaseTrustHold(g.reality);renderAll();save40();return c}
function revokeCertificate(c){if(!c||c.status!=='valid')return;c.status='revoked';c.revokedAt=Date.now();S.certificatesRevoked++;remember('CERTIFICATE REVOKED '+c.id+': its earlier authorized changes remain in history',realm(c.reality));if(typeof place==='function')place('dream','revoked signature beside an unchanged consequence',realm(c.reality));renderAll();save40();openCertificate(c)}
function expireCertificates(){let now=Date.now();for(const c of S.identityCertificates)if(c.status==='valid'&&c.expiresAt&&now>=c.expiresAt)c.status='expired';for(const r of S.trustRoots)if(r.status==='retired'&&r.retireAfter&&now>=r.retireAfter){let p=S.trustPolicies[r.reality];p.acceptedRoots=p.acceptedRoots.filter(x=>x!==r.id)}}
function rotateRoot(r){if(!r||r.status!=='active')return;r.status='retired';r.retireAfter=Date.now()+30000;S.rootRotations++;let nr=makeRoot(r.reality,{rotatedFrom:r.id,version:(r.version||1)+1,label:r.label+' v'+((r.version||1)+1)});remember('ROOT ROTATION: '+r.id+' → '+nr.id+'. Existing certificates have a 30-second trust grace period.',realm(r.reality));if(typeof place==='function')place('dream','new root beside credentials signed by the old one',realm(r.reality));$('#msg').textContent='Root rotated. Old certificate chains remain trusted briefly, but their consequences do not expire.';openRoot(nr);save40()}
function compromiseRoot(r,automatic=false){if(!r||r.status!=='active')return;r.status='compromised';r.compromisedAt=Date.now();S.rootCompromises++;for(const c of S.identityCertificates.filter(c=>c.rootId===r.id&&c.status==='valid'))c.status='suspect';remember('ROOT COMPROMISED '+r.id+': every certificate beneath it became disputed',realm(r.reality));if(typeof place==='function'){place('cold','trust anchor nobody can trust',realm(r.reality));place('dream','certificate chain ending in a compromised authority',realm(r.reality))}S.bailiffMood='asking who signed the root certificate';trustCrisis(r.reality,'root-compromised');if(!automatic)openRoot(r);renderAll();save40()}
function distrustRoot(id,r){if(!r)return;let p=S.trustPolicies[id];p.acceptedRoots=p.acceptedRoots.filter(x=>x!==r.id);S.rootRevocations++;remember('TRUST REMOVED: Reality '+id+' no longer accepts '+r.id,realm(id));if(typeof place==='function')place('cold','certificate valid somewhere else',realm(id));renderAll();save40();openRoot(r)}
function acceptRoot(id,r){if(!r)return;let p=S.trustPolicies[id];if(!p.acceptedRoots.includes(r.id))p.acceptedRoots.push(r.id);remember('TRUST STORE: Reality '+id+' accepted '+r.id+' as a root authority',realm(id));if(activeRoots(id).filter(x=>p.acceptedRoots.includes(x.id)).length>1)trustCrisis(id,'multiple-roots');renderAll();save40();openRoot(r)}
function createRivalRoot(id=S.active){let n=activeRoots(id).length+1,r=makeRoot(id,{label:'rival root '+n+' claiming Reality '+id,sourceType:'rival-government',accept:false,strength:.5+Math.random()*.18});remember('RIVAL ROOT '+r.id+': a second authority can now sign technically valid credentials for Reality '+id,realm(id));if(typeof place==='function')place('cold','two root certificates one reality',realm(id));$('#msg').textContent=r.id+' exists but is not trusted yet. A signature can be valid without being accepted.';openRoot(r);save40()}
function crossSign(r){if(!r)return;let other=r.reality==='A'?'B':'A',o=activeRoots(other)[0];if(!o)return;let exists=S.crossSignatures.find(x=>x.status==='active'&&x.fromRoot===r.id&&x.toRoot===o.id);if(exists)return openCrossSign(exists);let x={id:'XS'+(++S.crossSignatureSerial),fromRoot:r.id,toRoot:o.id,status:'active',created:Date.now()};S.crossSignatures.push(x);S.crossRealityTrusts++;if(!S.trustPolicies[r.reality].acceptedRoots.includes(o.id))S.trustPolicies[r.reality].acceptedRoots.push(o.id);remember('CROSS-SIGN '+x.id+': '+r.id+' accepted '+o.id+' as part of its trust chain',realm(r.reality));remember('FOREIGN ROOT RECOGNIZED: '+o.id+' is trusted in Reality '+r.reality,realm(other));if(typeof place==='function')place('dream','foreign root certificate accepted at home',realm(r.reality));trustCrisis(r.reality,'cross-reality-trust');renderAll();save40();openCrossSign(x)}
function metricKindForIncident(n){let a=(n?.alertIds||[]).map(alert).find(Boolean);if(a)return a.metricKind;let t=String(n?.title||'').toLowerCase();for(const k of['runtime-consistency','production-health','timeline-confidence','institutional-agreement','record-integrity','citizenship-legibility'])if(t.includes(k.replaceAll('-',' ')))return k;return'production-health'}
function bestRunbook40(n){let k=metricKindForIncident(n),rs=(S.runbooks||[]).filter(r=>r.reality===n.reality&&r.status==='active'&&r.metricKind===k);return [...rs].sort((a,b)=>(b.confidence||0)-(a.confidence||0))[0]||(S.runbooks||[]).find(r=>r.reality===n.reality&&r.status==='active')}
function identityForRunbook40(r){return (S.serviceIdentities||[]).find(x=>x.runbookId===r?.id&&x.status==='active')||null}
function activeCredential40(x,scope){let now=Date.now();return [...(S.accessCredentials||[])].reverse().find(g=>g.status==='active'&&(!g.expiresAt||g.expiresAt>now)&&g.scopes?.includes(scope)&&(g.identityId===x?.id||g.leakedTo===x?.id))||null}
function trustedPath(id,n){let r=bestRunbook40(n),x=identityForRunbook40(r),scope=SCOPE40[r?.kind]||'operations.execute',g=activeCredential40(x,scope),c=certForCredential(g,Date.now(),id);return{r,x,scope,g,c}}
function holdTrust(id,reason){if(S.trustAutomationHold[id])return;if(!Object.values(S.trustAutomationHold).some(Boolean))S.trustAutomationPriorGlobal=S.opsAutomationEnabled;S.trustAutomationHold[id]=true;S.opsAutomationEnabled=false;remember('TRUST GATE: automatic remediation paused in Reality '+id+' · '+reason,realm(id));S.bailiffMood='checking the certificate chain before obeying the service account'}
function releaseTrustHold(id){if(!S.trustAutomationHold[id])return;S.trustAutomationHold[id]=false;if(!Object.values(S.trustAutomationHold).some(Boolean)){let prior=S.trustAutomationPriorGlobal;S.trustAutomationPriorGlobal=null;if(prior===true&&!Object.values(S.iamAutomationHold||{}).some(Boolean))S.opsAutomationEnabled=true}remember('TRUST GATE CLEARED: Reality '+id+' has a trusted certificate chain',realm(id))}
function gateTrust(){ensureRoots();expireCertificates();for(const id of['A','B']){let n=[...(S.incidents||[])].reverse().find(n=>n.reality===id&&n.status==='open');if(!n){releaseTrustHold(id);continue}let p=trustedPath(id,n);if(p.c){releaseTrustHold(id);p.c.uses++;continue}if(p.g?.breakGlass&&!S.identityCertificates.some(c=>c.credentialId===p.g.id)&&Math.random()<.18){issueCertificate(p.g,activeRoots(id)[0],{duration:42000});releaseTrustHold(id);continue}holdTrust(id,p.g?(p.g.id+' has no trusted certificate chain'):'no scoped credential exists to certify')}}
function accessAuditFor(rm){return [...(S.accessAudits||[])].reverse().find(a=>a.remediationId===rm.id)}
function securityIncident40(id,title){S.incidentSerial=S.incidentSerial||0;let existing=(S.incidents||[]).find(n=>n.reality===id&&n.status==='open'&&n.title===title);if(existing)return existing;let n={id:'INC'+(++S.incidentSerial),reality:id,title,severity:'SEV2',status:'open',alertIds:[],started:Date.now(),acknowledged:null,resolved:null,postmortem:null,owner:'trust review',x:10+Math.random()*80,y:12+Math.random()*68};S.incidents=S.incidents||[];S.incidents.push(n);remember('TRUST INCIDENT '+n.id+': '+title,realm(id));if(typeof place==='function')place('cold','cryptographically valid question about an action that already happened',realm(id));return n}
function auditRemediation40(rm){if(!rm||S.observedRemediations40[rm.id])return;S.observedRemediations40[rm.id]=1;let aa=accessAuditFor(rm),g=credential(aa?.credentialId),c=g&&certForCredential(g,rm.created,rm.reality),r=c&&root(c.rootId),status=c?'trusted':'untrusted',note='';if(c){note=c.id+' chained '+g.id+' to '+r.id+' at execution time';c.uses++}else{S.untrustedRemediations++;note=aa?.status==='unauthorized'?'access control and trust both reject the action':'access control authorized the credential, but no accepted certificate chain existed';securityIncident40(rm.reality,'untrusted remediation executed after credential authorization');trustCrisis(rm.reality,'untrusted-remediation')}let a={id:'TA'+(++S.trustAuditSerial),reality:rm.reality,remediationId:rm.id,credentialId:g?.id||null,certificateId:c?.id||null,rootId:r?.id||null,status,created:Date.now(),note,x:10+Math.random()*80,y:12+Math.random()*68};S.trustAudits.push(a);S.trustAudits=S.trustAudits.slice(-48);remember('TRUST AUDIT '+a.id+': '+rm.id+' '+status.toUpperCase(),realm(rm.reality))}
function auditNewRemediations40(){for(const rm of(S.remediationRuns||[]))auditRemediation40(rm)}
function compromiseTick(){let pressure=(S.credentialLeaks||0)+(S.unauthorizedRemediations||0)+(S.untrustedRemediations||0);if(pressure>2&&Math.random()<.0045){let r=pick(S.trustRoots.filter(r=>r.status==='active'));if(r)compromiseRoot(r,true)}let bad=S.trustRoots.filter(r=>r.status==='compromised');if(bad.length&&Math.random()<.003){let r=pick(bad),g=pick((S.accessCredentials||[]).filter(g=>g.status==='active'&&g.reality===r.reality));if(g)issueCertificate(g,r,{forged:true,duration:75000})}}
function authorityCreep(){for(const r of S.trustRoots.filter(r=>r.status==='active')){let signed=S.identityCertificates.filter(c=>c.rootId===r.id).length;if(signed>=5){let key='authority-'+r.id;if(!S.trustKeys[key]&&Math.random()<.025){S.trustKeys[key]=1;S.rootAuthorityEvents++;r.strength=cl(r.strength+.1,.2,.99);remember('ROOT AUTHORITY: '+r.id+' became more legitimate because institutions kept accepting its signatures',realm(r.reality));if(typeof place==='function')place('dream','authority derived from signatures that derived from authority',realm(r.reality));trustCrisis(r.reality,'root-authority')}}}}
function trustCrisis(id,reason){if(Date.now()-S.lastTrustCrisis<8000)return false;let key=id+'|'+reason+'|'+Math.floor(Date.now()/20000);if(S.trustKeys['crisis-'+key])return false;S.trustKeys['crisis-'+key]=1;S.trustCrises++;S.lastTrustCrisis=Date.now();for(const rid of['A','B']){realm(rid).disputes=(realm(rid).disputes||0)+1;remember('ROOT OF TRUST CRISIS: the system that proves authority now needs an authority to prove it',realm(rid))}if(typeof place==='function'){place('cold','certificate chain with no final answer',realm(id));place('dream','two roots signing the same reality',realm(id))}S.bailiffMood='asking who signed the signer';$('#msg').textContent='ROOT OF TRUST CRISIS: every credential is verifiable, but the authorities disagree about which verification counts.';return true}
function openCrossSign(x){let a=root(x.fromRoot),b=root(x.toRoot);panel(x.id+' · CROSS-SIGN',(a?.id||'?')+' → '+(b?.id||'?'),'Reality '+(a?.reality||'?')+' accepts a chain ending at a foreign root. The foreign reality did not become the same reality.',[['close',closePanel]])}
function openCertificate(c){let g=credential(c.credentialId),r=root(c.rootId),b=[];if(g)b.push(['open '+g.id,()=>{let e=document.querySelector('[data-label="'+g.id+'"]');if(e)e.click()}]);if(r)b.push(['open '+r.id,()=>openRoot(r)]);if(c.status==='valid')b.push(['revoke certificate',()=>revokeCertificate(c)]);b.push(['close',closePanel]);panel(c.id+' · '+c.status.toUpperCase(),(g?.id||'credential')+' signed by '+(r?.id||'missing root'),'fingerprint '+c.fingerprint+'\n'+(c.emergency?'emergency certificate · ':'')+(c.forged?'FORGED · ':'')+'issued '+new Date(c.issuedAt).toLocaleTimeString()+(c.expiresAt?' · expires '+new Date(c.expiresAt).toLocaleTimeString():' · no expiry'),b)}
function openRoot(r){let p=S.trustPolicies[r.reality],accepted=p.acceptedRoots.includes(r.id),signed=S.identityCertificates.filter(c=>c.rootId===r.id).length,b=[];if(r.status==='active')b.push(['rotate root',()=>rotateRoot(r)],['mark compromised',()=>compromiseRoot(r,false)]);if(accepted)b.push(['remove from trust store',()=>distrustRoot(r.reality,r)]);else b.push(['accept in '+r.reality,()=>acceptRoot(r.reality,r)]);if(r.status==='active')b.push(['cross-sign other reality',()=>crossSign(r)]);b.push(['close',closePanel]);panel(r.id+' · '+r.status.toUpperCase(),r.label,'source '+r.sourceType+' · strength '+Math.round(r.strength*100)+'% · '+signed+' certificates · '+(accepted?'TRUSTED':'NOT TRUSTED')+(r.retireAfter?' · grace until '+new Date(r.retireAfter).toLocaleTimeString():''),b)}
function openTrustAudit(a){let c=S.identityCertificates.find(c=>c.id===a.certificateId),b=[];if(c)b.push(['open '+c.id,()=>openCertificate(c)]);b.push(['close',closePanel]);panel(a.id+' · '+a.status.toUpperCase(),a.remediationId||'unknown remediation',a.note,b)}
function signNext(){ensureRoots();let id=S.active,n=[...(S.incidents||[])].reverse().find(n=>n.reality===id&&n.status==='open'),p=n&&trustedPath(id,n);if(!p?.g){$('#msg').textContent='No scoped credential is available to sign. Authorize the runbook first.';return}let existing=S.identityCertificates.find(c=>c.credentialId===p.g.id&&c.status==='valid');if(existing)return openCertificate(existing);let r=activeRoots(id).find(r=>S.trustPolicies[id].acceptedRoots.includes(r.id))||activeRoots(id)[0],c=issueCertificate(p.g,r,{duration:p.g.breakGlass?42000:150000});$('#msg').textContent=c.id+' now chains '+p.g.id+' to '+r.id+'. The permission finally has a reason to be believed.';openCertificate(c)}
function openTrust(){ensureRoots();expireCertificates();let id=S.active,roots=S.trustRoots.filter(r=>r.reality===id),certs=[...S.identityCertificates].reverse().filter(c=>c.reality===id).slice(0,5),aud=[...S.trustAudits].reverse().filter(a=>a.reality===id).slice(0,4),b=[];for(const r of roots.slice(0,5))b.push(['open '+r.id,()=>openRoot(r)]);for(const c of certs)b.push(['certificate '+c.id,()=>openCertificate(c)]);for(const a of aud)b.push(['trust audit '+a.id,()=>openTrustAudit(a)]);b.push(['create rival root',()=>createRivalRoot(id)],['sign next credential',signNext],['audit trust now',()=>{auditNewRemediations40();gateTrust();openTrust()}],['close',closePanel]);let accepted=S.trustPolicies[id].acceptedRoots.map(root).filter(Boolean);panel('TRUST STORE · Reality '+id,(S.trustAutomationHold[id]?'AUTOMATION UNTRUSTED':'certificate gate clear')+'\n\n'+accepted.length+' accepted roots · '+S.identityCertificates.filter(c=>c.reality===id&&c.status==='valid').length+' valid certificates','rotations '+S.rootRotations+' · compromises '+S.rootCompromises+' · cross-signs '+S.crossRealityTrusts+' · untrusted executions '+S.untrustedRemediations+' · root authority '+S.rootAuthorityEvents+' · crises '+S.trustCrises,b)}
function renderTrust(){ensureRoots();expireCertificates();let l=$('#trustLayer');if(!l){l=document.createElement('div');l.id='trustLayer';document.body.appendChild(l)}l.innerHTML='';for(const r of S.trustRoots.slice(-12)){let n=document.createElement('i');n.className='trustRoot '+r.status+(S.trustPolicies[r.reality]?.acceptedRoots?.includes(r.id)?' accepted':'');n.dataset.label=r.id;n.style.left=r.x+'%';n.style.top=r.y+'%';n.onclick=()=>openRoot(r);l.appendChild(n)}for(const c of S.identityCertificates.slice(-18)){let n=document.createElement('i');n.className='identityCert '+c.status+(c.emergency?' emergency':'')+(c.forged?' forged':'');n.dataset.label=c.id;n.style.left=c.x+'%';n.style.top=c.y+'%';n.onclick=()=>openCertificate(c);l.appendChild(n)}let line=$('#trustline');if(!line){line=document.createElement('div');line.id='trustline';line.className='line';($('#accessline')||$('#opsline')||$('#observabilityline')||$('#deploymentline')||$('#ciline')||$('#versionline')||$('#enforcement')).after(line)}let id=S.active,accepted=S.trustPolicies[id].acceptedRoots.length,valid=S.identityCertificates.filter(c=>c.reality===id&&c.status==='valid').length;line.textContent='trust: '+accepted+' accepted roots · '+valid+' valid certificates · '+S.rootRotations+' rotations · '+S.rootCompromises+' compromised roots · '+S.crossRealityTrusts+' cross-signs · '+S.untrustedRemediations+' untrusted actions · '+S.trustCrises+' root crises'+(S.trustAutomationHold[id]?' · AUTOMATION UNTRUSTED':'');let ctr=document.querySelector('#app .controls');if(ctr&&!$('#openTrustButton')){let b=document.createElement('button');b.id='openTrustButton';b.textContent='open trust store';b.onclick=openTrust;ctr.prepend(b)}if(ctr&&!$('#signCredentialButton')){let b=document.createElement('button');b.id='signCredentialButton';b.textContent='sign next credential';b.onclick=signNext;ctr.prepend(b)}}
renderAll=function(){BR40();renderTrust()};let f=$('#forget');if(f)f.onclick=()=>{for(let i=2;i<=40;i++)localStorage.removeItem('nothing-state-v'+i);location.reload()};
setInterval(()=>{gateTrust();auditNewRemediations40();compromiseTick();authorityCreep();renderTrust();save40()},1750);ensureRoots();gateTrust();auditNewRemediations40();renderAll();save40();
})();
