(()=>{
const BS35=save,BR35=renderAll,O35=JSON.parse(localStorage.getItem('nothing-state-v35')||'null')||{},cl=(v,a,b)=>Math.max(a,Math.min(b,v));
S.realityTests=O35.realityTests||[];S.ciRuns=O35.ciRuns||[];S.testSerial=O35.testSerial||0;S.ciRunSerial=O35.ciRunSerial||0;S.realityDeployments=O35.realityDeployments||{A:{head:null,validatedAt:null},B:{head:null,validatedAt:null}};S.branchProtection=O35.branchProtection||{A:true,B:true};S.observedCommits35=O35.observedCommits35||{};S.observedMerges35=O35.observedMerges35||{};S.ciRunsMade=O35.ciRunsMade||0;S.ciPasses=O35.ciPasses||0;S.ciFailures=O35.ciFailures||0;S.ciOverrides=O35.ciOverrides||0;S.flakyTests=O35.flakyTests||0;S.disabledTests=O35.disabledTests||0;S.regressionsAccepted=O35.regressionsAccepted||0;S.institutionalizedRegressions=O35.institutionalizedRegressions||0;S.ciCrises=O35.ciCrises||0;S.lastCiCrisis=O35.lastCiCrisis||0;S.ciKeys=O35.ciKeys||{};
for(const id of['A','B'])S.realityDeployments[id]=Object.assign({head:null,validatedAt:null},S.realityDeployments[id]||{});
S.realityTests=S.realityTests.map((t,i)=>({id:t.id||'T'+(i+1),name:t.name||'unnamed invariant',scope:t.scope||'both',kind:t.kind||'timeline-stability',source:t.source||'test runner',status:t.status||'active',critical:!!t.critical,expected:t.expected||{},passes:t.passes||0,failures:t.failures||0,overrides:t.overrides||0,flaky:!!t.flaky,lastResult:t.lastResult||null,lastMessage:t.lastMessage||null,lastRunAt:t.lastRunAt||null,created:t.created||Date.now(),x:Number.isFinite(t.x)?t.x:10+Math.random()*80,y:Number.isFinite(t.y)?t.y:12+Math.random()*68}));
S.ciRuns=S.ciRuns.map((r,i)=>({id:r.id||'CI'+(i+1),reality:r.reality||'A',commitId:r.commitId||null,status:r.status||'running',results:r.results||[],created:r.created||Date.now(),finished:r.finished||null,overriddenAt:r.overriddenAt||null,x:Number.isFinite(r.x)?r.x:10+Math.random()*80,y:Number.isFinite(r.y)?r.y:12+Math.random()*68}));
function save35(){BS35();localStorage.setItem('nothing-state-v35',JSON.stringify({realityTests:S.realityTests,ciRuns:S.ciRuns,testSerial:S.testSerial,ciRunSerial:S.ciRunSerial,realityDeployments:S.realityDeployments,branchProtection:S.branchProtection,observedCommits35:S.observedCommits35,observedMerges35:S.observedMerges35,ciRunsMade:S.ciRunsMade,ciPasses:S.ciPasses,ciFailures:S.ciFailures,ciOverrides:S.ciOverrides,flakyTests:S.flakyTests,disabledTests:S.disabledTests,regressionsAccepted:S.regressionsAccepted,institutionalizedRegressions:S.institutionalizedRegressions,ciCrises:S.ciCrises,lastCiCrisis:S.lastCiCrisis,ciKeys:S.ciKeys}))}save=save35;
const realm=id=>S.real[id],commit=id=>(S.realityCommits||[]).find(c=>c.id===id),branch=id=>S.realityBranches?.[id]||{name:'reality/'+id,head:null,generation:0},activeTests=id=>S.realityTests.filter(t=>t.status==='active'&&(t.scope==='both'||t.scope===id)),ratified=id=>(S.constitutions||[]).filter(c=>c.reality===id&&c.status==='ratified'),activeOffices=id=>(S.offices||[]).filter(o=>o.reality===id&&['active','disputed'].includes(o.status)),activeAgencies=id=>(S.agencies||[]).filter(a=>a.reality===id&&a.status==='active'),liveCit=id=>(S.citizenships||[]).filter(c=>c.reality===id&&['active','disputed'].includes(c.status));
function maxOfficeHolders(id){let g={};for(const o of activeOffices(id)){if(!g[o.title])g[o.title]=new Set();g[o.title].add(o.holder)}return Object.values(g).reduce((m,s)=>Math.max(m,s.size),0)}
function markerCount(id){return(realm(id).places||[]).filter(p=>String(p.name||'').includes('<<<<<<<')||String(p.name||'').includes('>>>>>>>')||String(p.name||'').includes('both versions accepted')).length}
function issuerCount(id){return new Set(liveCit(id).map(c=>c.issuerId||c.issuerLabel||c.id)).size}
function addTest(name,scope,kind,source,expected={},critical=false){let existing=S.realityTests.find(t=>t.scope===scope&&t.kind===kind&&t.source===source&&t.status!=='retired');if(existing)return existing;let t={id:'T'+(++S.testSerial),name,scope,kind,source,status:'active',critical,expected,passes:0,failures:0,overrides:0,flaky:false,lastResult:null,lastMessage:null,lastRunAt:null,created:Date.now(),x:10+Math.random()*80,y:12+Math.random()*68};S.realityTests.push(t);S.realityTests=S.realityTests.slice(-32);return t}
function ensureTests(){addTest('Build 32 must remain physically absent','both','v32-absence','release history',{absent:true},true);for(const id of['A','B']){addTest('Reality '+id+' must remain describable',id,'conflict-markers','version control',{max:0},true);let drift=Math.ceil(realm(id).timelineDrift||0);addTest('Reality '+id+' timeline drift budget',id,'timeline-stability','history confidence',{max:Math.max(5,drift+4)},false);let ks=ratified(id);if(ks.length)addTest('Reality '+id+' constitutional contract',id,'constitution-contract','constitution '+ks[ks.length-1].id,{supremacy:ks[ks.length-1].supremacy,maxRatified:Math.max(1,ks.length)},true);let os=activeOffices(id);if(os.length)addTest('Reality '+id+' office uniqueness',id,'office-uniqueness','election certification',{maxHolders:Math.max(1,maxOfficeHolders(id))},false);let cs=liveCit(id);if(cs.length)addTest('Reality '+id+' citizenship issuer baseline',id,'citizenship-baseline','nationality registry',{maxIssuers:Math.max(1,issuerCount(id))},false);for(const a of activeAgencies(id).slice(-3))addTest(a.name+' doctrine contract',id,'agency-doctrine','agency '+a.id,{agencyId:a.id,doctrine:a.doctrine},false)}}
function evaluate(t,id){let ok=true,msg='';if(t.kind==='v32-absence'){ok=localStorage.getItem('nothing-state-v32')===null;msg=ok?'nothing-state-v32 is still absent':'nothing-state-v32 unexpectedly exists'}
else if(t.kind==='conflict-markers'){let n=markerCount(id);ok=n<=(t.expected.max??0);msg=n+' unresolved reality conflict markers (allowed '+(t.expected.max??0)+')'}
else if(t.kind==='timeline-stability'){let n=realm(id).timelineDrift||0;ok=n<=(t.expected.max??8);msg='timeline drift '+Math.round(n*10)/10+' / '+(t.expected.max??8)}
else if(t.kind==='constitution-contract'){let ks=ratified(id),same=ks.some(k=>k.supremacy===t.expected.supremacy);ok=same&&ks.length<=(t.expected.maxRatified??1);msg=ks.length+' ratified constitution(s); expected '+t.expected.supremacy+' supremacy'}
else if(t.kind==='office-uniqueness'){let n=maxOfficeHolders(id);ok=n<=(t.expected.maxHolders??1);msg='maximum '+n+' claimants for one office (baseline '+(t.expected.maxHolders??1)+')'}
else if(t.kind==='citizenship-baseline'){let n=issuerCount(id);ok=n<=(t.expected.maxIssuers??1);msg=n+' active citizenship issuer(s) (baseline '+(t.expected.maxIssuers??1)+')'}
else if(t.kind==='agency-doctrine'){let a=(S.agencies||[]).find(a=>a.id===t.expected.agencyId);ok=!!a&&a.status==='active'&&a.doctrine===t.expected.doctrine;msg=a?'doctrine is '+a.doctrine+'; expected '+t.expected.doctrine:'agency no longer exists'}
else{ok=true;msg='no assertion defined'}
let flake=t.flaky||(t.kind==='timeline-stability'&&(realm(id).timelineDrift||0)>7);if(flake&&Math.random()<.18){ok=!ok;msg+=' · nondeterministic runner disagreed'}return{ok,msg}}
function causalResult(t,id,ok){let r=realm(id);if(ok){if(t.kind==='constitution-contract'){let k=ratified(id).find(k=>k.supremacy===t.expected.supremacy);if(k)k.authority=cl((k.authority||.6)+.003,.3,.99)}if(t.kind==='agency-doctrine'){let a=(S.agencies||[]).find(a=>a.id===t.expected.agencyId);if(a)a.expertise=cl((a.expertise||.5)+.003,.1,.99)}}else{r.disputes=(r.disputes||0)+1;if(t.kind==='v32-absence'){for(const h of(S.missingBuildHypotheses||[]).filter(h=>h.status==='adopted'))h.status='disputed'}if(t.kind==='constitution-contract')r.timelineDrift=(r.timelineDrift||0)+.5;if(t.kind==='conflict-markers')r.timelineDrift=(r.timelineDrift||0)+.75}}
function runCI(id=S.active,cid=null,manual=true){ensureTests();let c=cid?commit(cid):commit(branch(id).head),run={id:'CI'+(++S.ciRunSerial),reality:id,commitId:c?.id||null,status:'running',results:[],created:Date.now(),finished:null,overriddenAt:null,x:10+Math.random()*80,y:12+Math.random()*68},tests=activeTests(id);for(const t of tests){let z=evaluate(t,id),status=z.ok?'passed':'failed';t.lastResult=status;t.lastMessage=z.msg;t.lastRunAt=Date.now();z.ok?t.passes++:t.failures++;run.results.push({testId:t.id,status,message:z.msg});causalResult(t,id,z.ok)}let failed=run.results.filter(x=>x.status==='failed'),critical=failed.filter(x=>S.realityTests.find(t=>t.id===x.testId)?.critical);run.status=failed.length?'failed':'passed';run.finished=Date.now();S.ciRuns.push(run);S.ciRuns=S.ciRuns.slice(-40);S.ciRunsMade++;if(run.status==='passed'){S.ciPasses++;if(c){c.ciStatus='passed';S.realityDeployments[id]={head:c.id,validatedAt:Date.now()}}remember('REALITY CI '+run.id+': '+(c?.id||branch(id).name)+' passed '+tests.length+' checks',realm(id));$('#msg').textContent=run.id+' passed. '+(c?.id||branch(id).name)+' is the latest validated reality.'}else{S.ciFailures++;if(c)c.ciStatus='failed';remember('REALITY CI '+run.id+': '+failed.length+' check(s) failed'+(critical.length?' including '+critical.length+' critical':''),realm(id));if(typeof place==='function')place('cold','reality failed automated checks',realm(id));S.bailiffMood='waiting for green checks on existence';$('#msg').textContent=run.id+' FAILED: '+failed.length+' check(s). HEAD exists, but validated reality stayed at '+(S.realityDeployments[id].head||'∅')+'.';ciCrisis(id,run)}S.observedCommits35[c?.id||('manual-'+id)]=run.id;renderAll();save35();if(manual)openRun(run);return run}
function ciCrisis(id,run){if(Date.now()-S.lastCiCrisis<7000)return false;let failed=run.results.filter(x=>x.status==='failed').map(x=>x.testId).sort().join(','),key=id+'|'+failed+'|'+(run.commitId||'manual');if(S.ciKeys[key])return false;if(run.status==='failed'&&S.realityDeployments[id].head&&branch(id).head!==S.realityDeployments[id].head){S.ciKeys[key]=1;S.ciCrises++;S.lastCiCrisis=Date.now();for(const r of[S.real.A,S.real.B]){r.disputes=(r.disputes||0)+1;remember('CONTINUOUS INTEGRATION CRISIS: committed reality and validated reality disagree about what may exist',r)}if(typeof place==='function'){place('dream','green check attached to an older universe',realm(id));place('cold','HEAD failed but continued existing',realm(id))}S.bailiffMood='enforcing the last green version of reality';$('#msg').textContent='CONTINUOUS INTEGRATION CRISIS: '+branch(id).name+' HEAD exists but is not the validated version.';return true}return false}
function overrideRun(run){if(!run||run.status!=='failed')return;run.status='overridden';run.overriddenAt=Date.now();S.ciOverrides++;let c=commit(run.commitId);if(c)c.ciStatus='overridden';S.realityDeployments[run.reality]={head:run.commitId||branch(run.reality).head,validatedAt:Date.now()};for(const x of run.results.filter(x=>x.status==='failed')){let t=S.realityTests.find(t=>t.id===x.testId);if(t)t.overrides++}realm(run.reality).timelineDrift=(realm(run.reality).timelineDrift||0)+1;remember('CI OVERRIDE '+run.id+': failed checks were accepted as deployable reality',realm(run.reality));if(typeof place==='function')place('cold','red check signed green by authority',realm(run.reality));$('#msg').textContent=run.id+' was overridden. The failing reality is now the validated reality.';renderAll();save35();openRun(run)}
function snapshotExpected(t,id){if(t.kind==='conflict-markers')t.expected.max=markerCount(id);else if(t.kind==='timeline-stability')t.expected.max=Math.ceil(realm(id).timelineDrift||0)+2;else if(t.kind==='constitution-contract'){let ks=ratified(id);if(ks.length){t.expected.supremacy=ks[ks.length-1].supremacy;t.expected.maxRatified=ks.length}}else if(t.kind==='office-uniqueness')t.expected.maxHolders=Math.max(1,maxOfficeHolders(id));else if(t.kind==='citizenship-baseline')t.expected.maxIssuers=Math.max(1,issuerCount(id));else if(t.kind==='agency-doctrine'){let a=(S.agencies||[]).find(a=>a.id===t.expected.agencyId);if(a)t.expected.doctrine=a.doctrine}else if(t.kind==='v32-absence')t.expected.absent=localStorage.getItem('nothing-state-v32')===null}
function bless(t,id=t.scope==='both'?S.active:t.scope,automatic=false){if(!t||t.status!=='active')return;snapshotExpected(t,id);t.lastResult='passed';S.regressionsAccepted++;if(automatic)S.institutionalizedRegressions++;remember((automatic?'INSTITUTIONALIZED REGRESSION: ':'BASELINE UPDATED: ')+t.name+' now defines current behavior as correct',realm(id));if(typeof place==='function')place('dream',automatic?'bug promoted to specification':'snapshot updated after failure',realm(id));$('#msg').textContent=t.id+' updated its expectation to match current reality.';renderAll();save35();if(!automatic)openTest(t)}
function markFlaky(t){if(!t||t.flaky)return;t.flaky=true;S.flakyTests++;remember('FLAKY TEST '+t.id+': contradiction reclassified as intermittent',realm(t.scope==='both'?S.active:t.scope));$('#msg').textContent=t.id+' is now flaky. Its failures count less emotionally, not mathematically.';renderAll();save35();openTest(t)}
function disableTest(t){if(!t||t.status!=='active')return;t.status='disabled';S.disabledTests++;remember('CHECK DISABLED '+t.id+': '+t.name,realm(t.scope==='both'?S.active:t.scope));$('#msg').textContent=t.id+' disabled. The condition may still be false; nobody is checking.';renderAll();save35();closePanel()}
function openTest(t){let id=t.scope==='both'?S.active:t.scope,b=[['run check',()=>{let z=evaluate(t,id);t.lastResult=z.ok?'passed':'failed';t.lastMessage=z.msg;t.lastRunAt=Date.now();z.ok?t.passes++:t.failures++;causalResult(t,id,z.ok);$('#msg').textContent=t.id+' '+t.lastResult.toUpperCase()+': '+z.msg;openTest(t);save35()}]];if(!t.flaky)b.push(['mark flaky',()=>markFlaky(t)]);if(t.lastResult==='failed')b.push(['update expected reality',()=>bless(t,id,false)]);b.push(['disable check',()=>disableTest(t)],['close',closePanel]);panel(t.id+' · '+t.status+(t.flaky?' · flaky':''),t.name+'\n\nsource: '+t.source,'last '+(t.lastResult||'never')+' · '+(t.lastMessage||'not run')+' · pass '+t.passes+' · fail '+t.failures+' · overrides '+t.overrides+(t.critical?' · REQUIRED':''),b)}
function openRun(run){let failed=run.results.filter(x=>x.status==='failed'),b=[['rerun checks',()=>runCI(run.reality,run.commitId,true)]];if(run.status==='failed')b.push(['override failed checks',()=>overrideRun(run)]);for(const x of failed.slice(0,3)){let t=S.realityTests.find(t=>t.id===x.testId);if(t)b.push(['open '+t.id,()=>openTest(t)])}b.push(['close',closePanel]);panel(run.id+' · '+run.status+' · '+(run.commitId||branch(run.reality).name),'Reality '+run.reality+' automated verification\n\n'+run.results.map(x=>x.testId+' '+x.status.toUpperCase()).join(' · '),run.results.map(x=>x.testId+': '+x.message).join(' | '),b)}
function openCI(){ensureTests();let id=S.active,last=[...S.ciRuns].reverse().find(r=>r.reality===id),b=[['run reality tests',()=>runCI(id,null,true)]];if(last)b.push(['open latest '+last.id,()=>openRun(last)]);for(const t of activeTests(id).slice(0,5))b.push(['open '+t.id,()=>openTest(t)]);b.push(['close',closePanel]);let d=S.realityDeployments[id];panel('REALITY CI · '+branch(id).name,'HEAD '+(branch(id).head||'∅')+'\nvalidated '+(d.head||'∅'),'checks '+activeTests(id).length+' · runs '+S.ciRunsMade+' · pass '+S.ciPasses+' · fail '+S.ciFailures+' · overrides '+S.ciOverrides+' · flaky '+S.flakyTests+' · accepted regressions '+S.regressionsAccepted+' · CI crises '+S.ciCrises,b)}
function autoLearn(){for(const t of S.realityTests.filter(t=>t.status==='active'&&t.failures>=3&&t.overrides>=2)){let key='learn-'+t.id+'-'+t.failures+'-'+t.overrides;if(S.ciKeys[key])continue;if(Math.random()<.035){S.ciKeys[key]=1;bless(t,t.scope==='both'?S.active:t.scope,true);break}}}
function autoRun(){ensureTests();for(const m of(S.mergeRequests||[]).slice(-10)){if(['merged'].includes(m.status)&&!S.observedMerges35[m.id]){S.observedMerges35[m.id]=1;runCI(m.to,m.commitId,false);return}}for(const c of(S.realityCommits||[]).slice(-12)){if(!S.observedCommits35[c.id]&&['committed','reverted'].includes(c.status)){runCI(c.reality,c.id,false);return}}}
function renderCI(){ensureTests();let l=$('#ciLayer');if(!l){l=document.createElement('div');l.id='ciLayer';document.body.appendChild(l)}l.innerHTML='';for(const r of S.ciRuns.slice(-14)){let n=document.createElement('i');n.className='ciRun '+r.status;n.dataset.label=r.id+' '+r.status;n.style.left=r.x+'%';n.style.top=r.y+'%';n.onclick=()=>openRun(r);l.appendChild(n)}for(const t of S.realityTests.filter(t=>t.lastResult==='failed').slice(-8)){let n=document.createElement('i');n.className='realityTest failed'+(t.flaky?' flaky':'');n.dataset.label=t.id;n.style.left=t.x+'%';n.style.top=t.y+'%';n.onclick=()=>openTest(t);l.appendChild(n)}let badge=$('#ciBadge');if(!badge){badge=document.createElement('div');badge.id='ciBadge';document.body.appendChild(badge)}let id=S.active,d=S.realityDeployments[id],head=branch(id).head,headCommit=commit(head);badge.className=headCommit?.ciStatus==='failed'?'failed':headCommit?.ciStatus==='passed'?'passed':headCommit?.ciStatus==='overridden'?'overridden':'pending';badge.textContent=(headCommit?.ciStatus||'unchecked').toUpperCase();badge.onclick=openCI;let line=$('#ciline');if(!line){line=document.createElement('div');line.id='ciline';line.className='line';($('#versionline')||$('#gapline')||$('#administrationline')||$('#enforcement')).after(line)}line.textContent='reality CI: '+activeTests(id).length+' checks · HEAD '+(head||'∅')+' '+(headCommit?.ciStatus||'unchecked')+' · validated '+(d.head||'∅')+' · '+S.ciPasses+' passes · '+S.ciFailures+' failures · '+S.ciOverrides+' overrides · '+S.institutionalizedRegressions+' bugs promoted to spec · '+S.ciCrises+' CI crises';let ctr=document.querySelector('#app .controls');if(ctr&&!$('#runCiButton')){let b=document.createElement('button');b.id='runCiButton';b.textContent='run reality tests';b.onclick=()=>runCI(S.active,null,true);ctr.prepend(b)}if(ctr&&!$('#openCiButton')){let b=document.createElement('button');b.id='openCiButton';b.textContent='open CI';b.onclick=openCI;ctr.prepend(b)}}
renderAll=function(){BR35();renderCI()};let f=$('#forget');if(f)f.onclick=()=>{for(let i=2;i<=35;i++)localStorage.removeItem('nothing-state-v'+i);location.reload()};
setInterval(()=>{autoRun();autoLearn();renderCI();save35()},1900);renderAll();save35();
})();
