(()=>{
const BS34=save,BR34=renderAll,O34=JSON.parse(localStorage.getItem('nothing-state-v34')||'null')||{},pick=a=>a&&a.length?a[Math.floor(Math.random()*a.length)]:null,cl=(v,a,b)=>Math.max(a,Math.min(b,v));
S.realityCommits=O34.realityCommits||[];S.mergeRequests=O34.mergeRequests||[];S.realityCommitSerial=O34.realityCommitSerial||0;S.mergeSerial=O34.mergeSerial||0;S.realityBranches=O34.realityBranches||{A:{name:'reality/A',head:null,generation:0},B:{name:'reality/B',head:null,generation:0}};S.realityCommitsMade=O34.realityCommitsMade||0;S.mergesAttempted=O34.mergesAttempted||0;S.mergesCompleted=O34.mergesCompleted||0;S.mergeConflicts=O34.mergeConflicts||0;S.conflictResolutions=O34.conflictResolutions||0;S.cherryPicks=O34.cherryPicks||0;S.realityReverts=O34.realityReverts||0;S.preservedConflicts=O34.preservedConflicts||0;S.versionControlCrises=O34.versionControlCrises||0;S.lastVersionCrisis=O34.lastVersionCrisis||0;S.versionKeys=O34.versionKeys||{};
for(const id of['A','B'])S.realityBranches[id]=Object.assign({name:'reality/'+id,head:null,generation:0},S.realityBranches[id]||{});
S.realityCommits=S.realityCommits.map((c,i)=>({id:c.id||'RC'+(i+1),reality:c.reality||'A',parentId:c.parentId||null,kind:c.kind||'memory',targetId:c.targetId||null,summary:c.summary||'state changed',payload:c.payload||{},status:c.status||'committed',created:c.created||Date.now(),mergedInto:c.mergedInto||[],revertedAt:c.revertedAt||null,x:Number.isFinite(c.x)?c.x:10+Math.random()*80,y:Number.isFinite(c.y)?c.y:12+Math.random()*68}));
S.mergeRequests=S.mergeRequests.map((m,i)=>({id:m.id||'MR'+(i+1),from:m.from||'A',to:m.to||'B',commitId:m.commitId||null,status:m.status||'open',conflict:m.conflict||null,resolution:m.resolution||null,created:m.created||Date.now(),cherry:!!m.cherry,x:Number.isFinite(m.x)?m.x:10+Math.random()*80,y:Number.isFinite(m.y)?m.y:12+Math.random()*68}));
function save34(){BS34();localStorage.setItem('nothing-state-v34',JSON.stringify({realityCommits:S.realityCommits,mergeRequests:S.mergeRequests,realityCommitSerial:S.realityCommitSerial,mergeSerial:S.mergeSerial,realityBranches:S.realityBranches,realityCommitsMade:S.realityCommitsMade,mergesAttempted:S.mergesAttempted,mergesCompleted:S.mergesCompleted,mergeConflicts:S.mergeConflicts,conflictResolutions:S.conflictResolutions,cherryPicks:S.cherryPicks,realityReverts:S.realityReverts,preservedConflicts:S.preservedConflicts,versionControlCrises:S.versionControlCrises,lastVersionCrisis:S.lastVersionCrisis,versionKeys:S.versionKeys}))}save=save34;
const realm=id=>S.real[id],otherId=id=>id==='A'?'B':'A',branch=id=>S.realityBranches[id],commit=id=>S.realityCommits.find(c=>c.id===id),charter=id=>[...(S.constitutions||[])].reverse().find(c=>c.reality===id&&c.status==='ratified'),office=id=>[...(S.offices||[])].reverse().find(o=>o.reality===id&&['active','disputed'].includes(o.status)),agency=id=>[...(S.agencies||[])].reverse().find(a=>a.reality===id&&a.status==='active'),citizenship=id=>[...(S.citizenships||[])].reverse().find(c=>c.reality===id&&['active','disputed'].includes(c.status)),hypothesis=id=>[...(S.missingBuildHypotheses||[])].reverse().find(h=>h.reality===id&&['adopted','certified','disputed'].includes(h.status)),order=id=>[...(S.executiveOrders||[])].reverse().find(d=>d.reality===id&&d.status==='active');
function snapshotCandidates(id){let r=realm(id),out=[],h=hypothesis(id),k=charter(id),o=office(id),a=agency(id),c=citizenship(id),d=order(id),mem=pick((r.memories||[]).slice(-10)),p=pick((r.places||[]).slice(-8));
if(h)out.push({kind:'build32',targetId:h.id,summary:'reconstruct Build 32 as '+h.theory,payload:{theory:h.theory,title:h.title,confidence:h.confidence,status:h.status}});
if(k)out.push({kind:'constitution',targetId:k.id,summary:'declare '+k.supremacy+' constitutionally supreme',payload:{supremacy:k.supremacy,authority:k.authority,articles:(k.articles||[]).slice(0,4)}});
if(o)out.push({kind:'office',targetId:o.id,summary:o.holderLabel+' occupies '+o.title,payload:{title:o.title,holder:o.holder,holderLabel:o.holderLabel,authority:o.authority,status:o.status,issuerType:o.issuerType,issuerId:o.issuerId}});
if(a)out.push({kind:'agency',targetId:a.id,summary:a.name+' follows '+a.doctrine+' doctrine',payload:{name:a.name,jurisdiction:a.jurisdiction,doctrine:a.doctrine,autonomy:a.autonomy,inertia:a.inertia,expertise:a.expertise}});
if(c)out.push({kind:'citizenship',targetId:c.id,summary:'traveler citizenship recognized by '+c.issuerLabel,payload:{issuerType:c.issuerType,issuerId:c.issuerId,issuerLabel:c.issuerLabel,authority:c.authority,status:c.status}});
if(d)out.push({kind:'order',targetId:d.id,summary:d.text,payload:{kind:d.kind,targetId:d.targetId,text:d.text,status:d.status}});
if(mem)out.push({kind:'memory',targetId:null,summary:'remember: '+String(mem).slice(0,70),payload:{text:String(mem)}});
if(p)out.push({kind:'place',targetId:null,summary:'preserve place: '+p.name,payload:{name:p.name,type:p.type||'dream'}});
return out}
function commitReality(id=S.active,forced=true){let options=snapshotCandidates(id);if(!options.length){remember('VERSION CONTROL: Reality '+id+' attempted to commit an empty state',realm(id));$('#msg').textContent='Reality '+id+' has nothing stable enough to commit yet.';return null}let s=pick(options),b=branch(id),c={id:'RC'+(++S.realityCommitSerial),reality:id,parentId:b.head,kind:s.kind,targetId:s.targetId,summary:s.summary,payload:s.payload,status:'committed',created:Date.now(),mergedInto:[],revertedAt:null,x:10+Math.random()*80,y:12+Math.random()*68};S.realityCommits.push(c);S.realityCommits=S.realityCommits.slice(-40);b.head=c.id;b.generation=(b.generation||0)+1;S.realityCommitsMade++;remember('REALITY COMMIT '+c.id+': '+c.summary,realm(id));if(typeof place==='function'&&forced)place('dream','working tree clean for several seconds',realm(id));$('#msg').textContent=c.id+' committed '+c.summary+' to '+b.name+'.';renderAll();save34();if(forced)openCommit(c);return c}
function conflictFor(c,to){if(!c)return null;if(c.kind==='build32'){let h=hypothesis(to);if(h&&h.theory!==c.payload.theory)return'Build 32 has incompatible reconstructed implementations'}
if(c.kind==='constitution'){let k=charter(to);if(k&&k.supremacy!==c.payload.supremacy)return'two supremacy clauses modify the same reality'}
if(c.kind==='office'){let o=(S.offices||[]).find(o=>o.reality===to&&['active','disputed'].includes(o.status)&&o.title===c.payload.title);if(o&&o.holder!==c.payload.holder)return'two holders modify the same public office'}
if(c.kind==='agency'){let a=(S.agencies||[]).find(a=>a.reality===to&&a.status==='active'&&a.jurisdiction===c.payload.jurisdiction);if(a&&a.doctrine!==c.payload.doctrine&&Math.max(a.autonomy||0,c.payload.autonomy||0)>.55)return'two bureaucratic doctrines modify the same agency'}
if(c.kind==='citizenship'){let cs=(S.citizenships||[]).filter(x=>x.reality===to&&['active','disputed'].includes(x.status));if(cs.some(x=>x.issuerId!==c.payload.issuerId))return'two governments modify the same citizenship record'}
if(c.kind==='order'){let d=(S.executiveOrders||[]).find(d=>d.reality===to&&d.status==='active'&&d.kind===c.payload.kind&&d.text!==c.payload.text);if(d)return'two executive instructions modify the same administrative surface'}
return null}
function applyCommit(c,to,mode='theirs'){let r=realm(to),p=c.payload||{},impact='';if(mode==='ours'){remember('MERGE '+c.id+': Reality '+to+' kept its existing version',r);return'kept target version'}
if(c.kind==='memory'){remember('MERGED FROM REALITY '+c.reality+': '+p.text,r);impact='memory copied across the rift'}
else if(c.kind==='place'){if(typeof place==='function')place(p.type||'dream',p.name+' [merged from '+c.reality+']',r);impact='place added to target history'}
else if(c.kind==='build32'){let h={id:'H32-'+(++S.missingBuildSerial),reality:to,theory:p.theory,title:p.title||('Merged Build 32: '+p.theory),text:'Imported by reality version control from Reality '+c.reality+'.',source:'merge commit '+c.id,confidence:cl((p.confidence||.5)-(mode==='both'?.08:0),.2,.98),status:'adopted',created:Date.now(),certifiedAt:Date.now(),adoptedAt:Date.now(),challenges:0,effectsApplied:true,x:10+Math.random()*80,y:12+Math.random()*68};S.missingBuildHypotheses.push(h);S.build32Adoptions=(S.build32Adoptions||0)+1;S.build32Status='reconstructed';remember('MERGED BUILD 32: '+h.title,r);impact='target reality adopted the source reconstruction of the missing build'}
else if(c.kind==='constitution'){let old=charter(to);if(old&&mode!=='both')old.status='superseded';let k={id:'K'+(++S.constitutionSerial),reality:to,supremacy:p.supremacy,status:'ratified',support:0,oppose:0,created:Date.now(),voteAt:Date.now(),authority:cl((p.authority||.6)-(mode==='both'?.12:.04),.5,.96),articles:p.articles?.length?p.articles:['MERGED ARTICLE — '+p.supremacy+' is supreme.'],amendments:0,pendingAmendment:null,enforced:0,x:10+Math.random()*80,y:12+Math.random()*68};S.constitutions.push(k);remember('MERGED CONSTITUTION '+k.id+': '+p.supremacy+' supremacy imported from Reality '+c.reality,r);impact=mode==='both'?'second ratified constitution kept beside the first':'source supremacy replaced target charter'}
else if(c.kind==='office'){let o={id:'O'+(++S.officeSerial),electionId:null,reality:to,title:p.title,holder:p.holder,holderLabel:p.holderLabel,status:'disputed',issuerType:'merge',issuerId:c.id,authority:cl((p.authority||.5)-(mode==='both'?.06:.02),.25,.9),orders:0,created:Date.now(),termEnd:Date.now()+45000,x:10+Math.random()*80,y:12+Math.random()*68};S.offices.push(o);remember('MERGED OFFICE '+o.id+': '+p.holderLabel+' imported as claimant to '+p.title,r);impact='source officeholder became a disputed target-reality officeholder'}
else if(c.kind==='agency'){let a=(S.agencies||[]).find(a=>a.reality===to&&a.status==='active'&&a.jurisdiction===p.jurisdiction);if(a){a.doctrine=mode==='both'?'conflicted: '+a.doctrine+' / '+p.doctrine:p.doctrine;a.autonomy=cl(((a.autonomy||.4)+(p.autonomy||.4))/2+(mode==='both'?.08:0),.05,.98);a.inertia=cl(Math.max(a.inertia||.4,p.inertia||.4),.05,.98);impact='target agency absorbed source doctrine'}else{a={id:'AG'+(++S.agencySerial),reality:to,name:(p.name||'Merged Administration')+' [merge]',jurisdiction:p.jurisdiction||'general',doctrine:p.doctrine||'procedure',loyalty:.35,autonomy:p.autonomy||.5,inertia:p.inertia||.5,expertise:p.expertise||.5,head:'acting merge custodian',headType:'career',status:'active',created:Date.now(),backlog:0,survivedTerms:0,lastOfficeId:null,lastHolder:null,actions:0,x:10+Math.random()*80,y:12+Math.random()*68};S.agencies.push(a);impact='source agency appeared in target administration'}remember('MERGED AGENCY DOCTRINE: '+p.jurisdiction+' now carries '+p.doctrine,r)}
else if(c.kind==='citizenship'){let exists=(S.citizenships||[]).some(x=>x.reality===to&&x.issuerId===p.issuerId&&['active','disputed'].includes(x.status));if(!exists){let x={id:'C'+(++S.citizenshipSerial),reality:to,issuerType:p.issuerType||'merge',issuerId:p.issuerId||c.id,issuerLabel:(p.issuerLabel||'merged authority')+' via '+c.id,status:'disputed',authority:cl((p.authority||.5)-.08,.3,.9),applied:Date.now(),decisionAt:Date.now(),decided:Date.now(),oathAt:Date.now(),grounds:'citizenship imported by reality merge',challenges:0,revocations:0,passportId:null,offered:false,x:10+Math.random()*80,y:12+Math.random()*68};S.citizenships.push(x)}remember('MERGED CITIZENSHIP: Reality '+to+' imported a nationality claim from '+c.reality,r);impact='another government now has a citizenship claim over the traveler'}
else if(c.kind==='order'){let d={id:'EO'+(++S.executiveOrderSerial),officeId:null,reality:to,kind:p.kind||'finding',targetId:p.targetId||null,status:'active',text:'MERGED FROM '+c.reality+': '+p.text,created:Date.now(),challenges:0,x:10+Math.random()*80,y:12+Math.random()*68};S.executiveOrders.push(d);remember(d.id+': '+d.text,r);impact='source executive instruction became active in target reality'}
else if(c.kind==='revert'){remember('MERGED REVERT: '+c.summary,r);impact='target history received a revert without losing the original historical evidence'}
if(mode==='both'){r.timelineDrift+=2;r.disputes++;if(typeof place==='function')place('cold','<<<<<<< both versions accepted >>>>>>>',r)}return impact||'commit applied'}
function startMerge(from=otherId(S.active),to=S.active,cid=null,cherry=false){let c=cid?commit(cid):commit(branch(from).head);if(!c){$('#msg').textContent='Reality '+from+' has no commit to merge yet.';return null}let conflict=conflictFor(c,to),m={id:'MR'+(++S.mergeSerial),from,to,commitId:c.id,status:conflict?'conflict':'open',conflict,resolution:null,created:Date.now(),cherry,x:10+Math.random()*80,y:12+Math.random()*68};S.mergeRequests.push(m);S.mergeRequests=S.mergeRequests.slice(-30);S.mergesAttempted++;if(conflict){S.mergeConflicts++;for(const id of[from,to]){realm(id).timelineDrift++;realm(id).disputes++;remember('MERGE CONFLICT '+m.id+': '+conflict,realm(id))}if(typeof place==='function'){place('cold','<<<<<<< '+branch(to).name,realm(to));place('cold','>>>>>>> '+branch(from).name,realm(to))}S.bailiffMood='reading conflict markers as binding instructions';$('#msg').textContent='MERGE CONFLICT '+m.id+': '+conflict+'.'}else{m.status='merged';m.resolution='theirs';m.impact=applyCommit(c,to,'theirs');S.mergesCompleted++;c.mergedInto.push(to);branch(to).head=c.id;branch(to).generation=(branch(to).generation||0)+1;if(cherry)S.cherryPicks++;remember((cherry?'CHERRY-PICK ':'MERGE ')+m.id+': '+c.summary,realm(to));$('#msg').textContent=(cherry?'CHERRY-PICK ':'MERGE ')+m.id+' applied '+c.id+' to '+branch(to).name+'.'}renderAll();save34();if(conflict)openMerge(m);return m}
function resolveMerge(m,mode){if(!m||m.status!=='conflict')return;let c=commit(m.commitId);m.resolution=mode;m.status=mode==='abandon'?'abandoned':'merged';S.conflictResolutions++;if(mode==='abandon'){$('#msg').textContent=m.id+' was abandoned. The conflict remains as historical evidence.';return openMerge(m)}m.impact=applyCommit(c,m.to,mode);S.mergesCompleted++;if(mode==='both'){S.preservedConflicts++;versionCrisis(m,c)}if(c&&!c.mergedInto.includes(m.to))c.mergedInto.push(m.to);branch(m.to).head=c?.id||branch(m.to).head;branch(m.to).generation=(branch(m.to).generation||0)+1;remember('MERGE RESOLUTION '+m.id+': '+mode+' · '+m.impact,realm(m.to));$('#msg').textContent=m.id+' resolved with '+mode+'. '+m.impact+'.';openMerge(m);renderAll();save34()}
function versionCrisis(m,c){if(Date.now()-S.lastVersionCrisis<7000)return false;let key=m.from+'|'+m.to+'|'+c.kind+'|'+m.id;if(S.versionKeys[key])return false;S.versionKeys[key]=1;S.versionControlCrises++;S.lastVersionCrisis=Date.now();for(const id of['A','B']){realm(id).timelineDrift+=2;realm(id).disputes++;remember('VERSION CONTROL CRISIS: incompatible versions were deliberately merged as both true',realm(id))}if(typeof place==='function'){place('dream','merge commit with two incompatible parents',realm('A'));place('dream','working tree cannot describe current reality',realm('B'))}S.bailiffMood='requesting someone resolve HEAD';$('#msg').textContent='VERSION CONTROL CRISIS: the merge preserved incompatible versions as one history.';return true}
function revertCommit(c){if(!c||c.status!=='committed')return;let r=realm(c.reality),p=c.payload||{};c.status='reverted';c.revertedAt=Date.now();S.realityReverts++;if(c.kind==='build32'){let h=(S.missingBuildHypotheses||[]).find(h=>h.id===c.targetId&&h.reality===c.reality);if(h&&h.status==='adopted')h.status='disputed'}else if(c.kind==='constitution'){let k=charter(c.reality);if(k&&k.supremacy===p.supremacy){k.status='superseded';r.timelineDrift++}}else if(c.kind==='office'){let o=(S.offices||[]).find(o=>o.id===c.targetId);if(o&&['active','disputed'].includes(o.status))o.status='disputed'}else if(c.kind==='agency'){let a=(S.agencies||[]).find(a=>a.id===c.targetId);if(a){a.autonomy=cl((a.autonomy||.5)-.08,.05,.98);a.inertia=cl((a.inertia||.5)-.05,.05,.98);a.doctrine='procedure'}}else if(c.kind==='citizenship'){let x=(S.citizenships||[]).find(x=>x.id===c.targetId);if(x&&['active','disputed'].includes(x.status))x.status='disputed'}else if(c.kind==='order'){let d=(S.executiveOrders||[]).find(d=>d.id===c.targetId);if(d&&d.status==='active')d.status='vacated'}
remember('REVERT '+c.id+': the effect was challenged, but the commit remains in history',r);let b=branch(c.reality),rv={id:'RC'+(++S.realityCommitSerial),reality:c.reality,parentId:b.head,kind:'revert',targetId:c.id,summary:'revert '+c.id+' without erasing that it happened',payload:{reverted:c.id},status:'committed',created:Date.now(),mergedInto:[],revertedAt:null,x:10+Math.random()*80,y:12+Math.random()*68};S.realityCommits.push(rv);b.head=rv.id;b.generation++;S.realityCommitsMade++;if(typeof place==='function')place('dream','revert that remembers what it removed',r);$('#msg').textContent=rv.id+' reverted '+c.id+'. History kept both the event and its reversal.';openCommit(rv);renderAll();save34()}
function openCommit(c){let b=[];if(c.status==='committed'&&c.kind!=='revert')b.push(['cherry-pick to '+otherId(c.reality),()=>startMerge(c.reality,otherId(c.reality),c.id,true)],['revert commit',()=>revertCommit(c)]);b.push(['merge into '+otherId(c.reality),()=>startMerge(c.reality,otherId(c.reality),c.id,false)],['close',closePanel]);panel(c.id+' · '+c.status+' · '+branch(c.reality).name,c.summary,'kind '+c.kind+' · parent '+(c.parentId||'root')+' · merged into '+(c.mergedInto.length?c.mergedInto.join(', '):'nowhere')+(c.revertedAt?' · reverted later':''),b)}
function openMerge(m){let c=commit(m.commitId),b=[];if(m.status==='conflict')b.push(['resolve ours',()=>resolveMerge(m,'ours')],['resolve theirs',()=>resolveMerge(m,'theirs')],['keep both',()=>resolveMerge(m,'both')],['abandon merge',()=>resolveMerge(m,'abandon')]);if(c)b.push(['open '+c.id,()=>openCommit(c)]);b.push(['close',closePanel]);panel(m.id+' · '+m.status+(m.cherry?' cherry-pick':' merge'),branch(m.from).name+' → '+branch(m.to).name+'\n\n'+(c?.summary||'missing commit'),(m.conflict?'CONFLICT: '+m.conflict:'no conflict')+(m.resolution?' · resolution '+m.resolution:'')+(m.impact?' · '+m.impact:''),b)}
function openVersionControl(){let id=S.active,b=branch(id),c=commit(b.head),mrs=[...S.mergeRequests].reverse().filter(m=>m.to===id||m.from===id).slice(0,4),buttons=[['commit current reality',()=>commitReality(id,true)],['merge other reality',()=>startMerge(otherId(id),id,null,false)]];if(c)buttons.push(['open HEAD '+c.id,()=>openCommit(c)]);for(const m of mrs)buttons.push(['open '+m.id,()=>openMerge(m)]);buttons.push(['close',closePanel]);panel('REALITY VERSION CONTROL · '+b.name,'HEAD '+(b.head||'∅')+' · generation '+b.generation+'\nother HEAD '+(branch(otherId(id)).head||'∅'),'commits '+S.realityCommitsMade+' · merges '+S.mergesCompleted+'/'+S.mergesAttempted+' · conflicts '+S.mergeConflicts+' · reverts '+S.realityReverts+' · preserved conflicts '+S.preservedConflicts+' · version crises '+S.versionControlCrises,buttons)}
function renderVersionControl(){let l=$('#versionLayer');if(!l){l=document.createElement('div');l.id='versionLayer';document.body.appendChild(l)}l.innerHTML='';for(const c of S.realityCommits.slice(-20)){let n=document.createElement('i');n.className='realityCommit '+c.reality+' '+c.status+' '+c.kind;n.dataset.label=c.id+' '+c.reality;n.style.left=c.x+'%';n.style.top=c.y+'%';n.onclick=()=>openCommit(c);l.appendChild(n)}for(const m of S.mergeRequests.slice(-12)){let n=document.createElement('i');n.className='mergeRequest '+m.status;n.dataset.label=m.id;n.style.left=m.x+'%';n.style.top=m.y+'%';n.onclick=()=>openMerge(m);l.appendChild(n)}let heads=$('#branchHeads');if(!heads){heads=document.createElement('div');heads.id='branchHeads';document.body.appendChild(heads)}heads.innerHTML='<span>reality/A → '+(branch('A').head||'∅')+'</span><span>reality/B → '+(branch('B').head||'∅')+'</span>';let line=$('#versionline');if(!line){line=document.createElement('div');line.id='versionline';line.className='line';($('#gapline')||$('#administrationline')||$('#enforcement')).after(line)}line.textContent='version control: A '+(branch('A').head||'∅')+' · B '+(branch('B').head||'∅')+' · '+S.realityCommitsMade+' commits · '+S.mergesCompleted+' merges · '+S.mergeConflicts+' conflicts · '+S.realityReverts+' reverts · '+S.versionControlCrises+' version crises';let ctr=document.querySelector('#app .controls');if(ctr&&!$('#commitRealityButton')){let b=document.createElement('button');b.id='commitRealityButton';b.textContent='commit reality';b.onclick=()=>commitReality(S.active,true);ctr.prepend(b)}if(ctr&&!$('#mergeRealityButton')){let b=document.createElement('button');b.id='mergeRealityButton';b.textContent='merge other reality';b.onclick=()=>startMerge(otherId(S.active),S.active,null,false);ctr.prepend(b)}if(ctr&&!$('#versionControlButton')){let b=document.createElement('button');b.id='versionControlButton';b.textContent='open version control';b.onclick=openVersionControl;ctr.prepend(b)}}
renderAll=function(){BR34();renderVersionControl()};let f=$('#forget');if(f)f.onclick=()=>{for(let i=2;i<=34;i++)localStorage.removeItem('nothing-state-v'+i);location.reload()};
setInterval(()=>{for(const id of['A','B'])if(!branch(id).head&&snapshotCandidates(id).length&&Math.random()<.025)commitReality(id,false);if(Math.random()<.006){let id=Math.random()<.5?'A':'B';if(branch(id).head&&branch(otherId(id)).head&&!(S.mergeRequests||[]).some(m=>m.status==='conflict'))startMerge(id,otherId(id),null,false)}renderVersionControl();save34()},1800);renderAll();save34();
})();
